<?php
declare(strict_types=1);

function public_form_markup(array $form,array $values=[],array $errors=[]):string { ob_start(); ?>
<form action="/interest-submit.php" class="interest-form" method="post" novalidate>
<input type="hidden" name="_csrf" value="<?= h(csrf_token('interest')) ?>"><input type="hidden" name="_started_at" value="<?= time() ?>"><div class="honeypot" aria-hidden="true"><label>Leave this field blank<input name="_website" tabindex="-1" autocomplete="off"></label></div>
<?php foreach (interest_form_groups($form) as $group): if ($group['label'] !== ''): ?><fieldset><legend><?= h($group['label']) ?></legend><?php endif; foreach ($group['fields'] as $field): $id=$field['id']; $type=$field['type']; $value=$values[$id]??''; ?>
<?php if ($type==='radio'): ?><div class="radio-question"><p><?= h($field['label']) ?><?= !empty($field['required'])?' *':'' ?></p><div class="radio-grid"><?php foreach ($field['options']??[] as $option): $title=$option['title']??null; $description=$option['description']??null; if (!is_string($title)||!is_string($description)) [$title,$description]=array_pad(explode(' — ',$option['label']??'',2),2,''); ?><label><input type="radio" name="<?= h($id) ?>" value="<?= h($option['value']) ?>" <?= $value===$option['value']?'checked':'' ?> <?= !empty($field['required'])?'required':'' ?>><span><strong><?= h($title) ?></strong><?= h($description) ?></span></label><?php endforeach; ?></div><?php if (isset($errors[$id])): ?><p class="form-error"><?= h($errors[$id]) ?></p><?php endif; ?></div>
<?php elseif (in_array($type,['checkbox','consent'],true)): ?><label class="consent"><input type="checkbox" name="<?= h($id) ?>" value="1" <?= $value==='1'?'checked':'' ?> <?= !empty($field['required'])?'required':'' ?>><span><?= h($field['label']) ?><?= !empty($field['required'])?' *':'' ?></span></label><?php if (isset($errors[$id])): ?><p class="form-error"><?= h($errors[$id]) ?></p><?php endif; ?>
<?php else: ?><label class="public-field"><span><?= h($field['label']) ?><?= !empty($field['required'])?' *':'' ?></span><?php if ($type==='textarea'): ?><textarea name="<?= h($id) ?>" rows="<?= h($field['rows']??4) ?>" placeholder="<?= h($field['placeholder']??'') ?>" <?= !empty($field['required'])?'required':'' ?>><?= h($value) ?></textarea><?php elseif ($type==='select'): ?><select name="<?= h($id) ?>" <?= !empty($field['required'])?'required':'' ?>><option value="">Select</option><?php foreach ($field['options']??[] as $option): ?><option value="<?= h($option['value']) ?>" <?= $value===$option['value']?'selected':'' ?>><?= h($option['label']) ?></option><?php endforeach; ?></select><?php else: ?><input type="<?= h($type) ?>" name="<?= h($id) ?>" value="<?= h($value) ?>" placeholder="<?= h($field['placeholder']??'') ?>" autocomplete="<?= h($field['autocomplete']??'') ?>" <?= !empty($field['required'])?'required':'' ?>><?php endif; ?></label><?php if (!empty($field['help'])): ?><small><?= h($field['help']) ?></small><?php endif; ?><?php if (isset($errors[$id])): ?><p class="form-error"><?= h($errors[$id]) ?></p><?php endif; ?>
<?php endif; endforeach; if ($group['label'] !== ''): ?></fieldset><?php endif; endforeach; ?><button class="button" type="submit"><?= h($form['submitLabel']) ?> <span aria-hidden="true">↗</span></button></form><?php return (string)ob_get_clean(); }

function public_video_markup(array $value):string{$src=h((string)($value['src']??''));$poster=h((string)($value['poster']??''));$attributes=(!empty($value['controls'])?' controls':'').(!empty($value['muted'])?' muted':'').(!empty($value['loop'])?' loop':'').(!empty($value['autoplay'])&&!empty($value['muted'])?' autoplay':'').' playsinline preload="metadata"';return '<video'.$attributes.($poster!==''?' poster="'.$poster.'"':'').'><source src="'.$src.'"></video>';}
function public_responsive_images(string $html,array $images):string{foreach($images as $id=>$value){if(!is_array($value))continue;$source=media_image_sources(database(),isset($value['mediaAssetId'])?(int)$value['mediaAssetId']:null,isset($value['mediaVersionId'])?(int)$value['mediaVersionId']:null,(string)($value['src']??''));$html=preg_replace_callback('~<img\b[^>]*data-editable-image="'.preg_quote((string)$id,'~').'"[^>]*>~i',function(array $match)use($source){$tag=preg_replace('~\s(?:src|srcset|sizes)="[^"]*"~i','',$match[0])??$match[0];$attributes=' src="'.h($source['src']).'" sizes="(max-width: 720px) 100vw, 50vw"';if($source['srcset']!=='')$attributes.=' srcset="'.h($source['srcset']).'"';return rtrim($tag,'>').$attributes.'>';},$html,1)??$html;}return $html;}
function public_apply_videos(string $html,array $videos):string{$html=public_responsive_images($html,public_content()['images']??[]);foreach($videos as $id=>$value){if(!is_array($value))continue;$video=public_video_markup($value);$native='~<video\b[^>]*data-editable-video="'.preg_quote((string)$id,'~').'"[^>]*>.*?</video>~is';$count=0;$html=preg_replace($native,$video,$html,1,$count)??$html;if($count===0){$wrapper='~(<div\b[^>]*data-editable-video="'.preg_quote((string)$id,'~').'"[^>]*>).*?(</div>)~is';$html=preg_replace($wrapper,'$1'.$video.'$2',$html,1)??$html;}}return $html;}

function render_public_page(array $values=[],array $errors=[],bool $success=false):void{$content=public_content();$html=file_get_contents(__DIR__.'/index.html');$html=str_replace(['href="page.css?responsive-framing=3"','src="page.js?responsive-framing=3"','src="page.js"','../assets/'],['href="/template/page.css"','src="/assets/public.js"','src="/assets/public.js"','/assets/'],$html);foreach($content['texts'] as $id=>$v){$pattern='~(<([a-z][a-z0-9]*)\b[^>]*data-editable-text="'.preg_quote($id,'~').'"[^>]*>).*?(</\2>)~is';$html=preg_replace_callback($pattern,fn($m)=>$m[1].$v['html'].$m[3],$html,1)??$html;}foreach($content['images'] as $id=>$v){$html=preg_replace_callback('/(<img[^>]*data-editable-image="'.preg_quote($id,'/').'"[^>]*src=")[^"]*(")/',fn($m)=>$m[1].h(str_replace('../','/',$v['src'])).$m[2],$html,1)??$html;}$html=public_apply_videos($html,$content['videos']??[]);$form=public_form_markup(interest_form_definition(),$values,$errors);$html=preg_replace_callback('/<form action="#" class="interest-form".*?<\/form>/s',fn()=>$form,$html,1)??$html;if($success)$html=str_replace('class="interest" data-section="interest-form"','class="interest has-success" data-section="interest-form"',$html);$notice=$success?'<p class="form-status form-success" role="status">Your interest was registered. This does not reserve a place and no payment has been made. We may use your contact to share workshop dates and conditions.</p>':'';$html=str_replace('<form action="/interest-submit.php"',$notice.'<form action="/interest-submit.php"',$html);echo $html;}
