<?php
declare(strict_types=1);
require __DIR__.'/app/bootstrap.php';

function media_stream_error(int $status,string $message):never{http_response_code($status);header('Content-Type: text/plain; charset=UTF-8');echo $message;exit;}
function media_stream_range(int $size):array{$range=$_SERVER['HTTP_RANGE']??'';if($range==='')return [0,$size-1,200];if(!preg_match('/^bytes=(\d*)-(\d*)$/',$range,$match))throw new RangeException();$start=$match[1]===''?null:(int)$match[1];$end=$match[2]===''?null:(int)$match[2];if($start===null){$length=$end??0;if($length<1)throw new RangeException();$start=max(0,$size-$length);$end=$size-1;}else{$end=$end??$size-1;}if($start<0||$start>=$size||$end<$start)throw new RangeException();return [$start,min($end,$size-1),206];}

$assetId=filter_input(INPUT_GET,'asset',FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);$versionId=filter_input(INPUT_GET,'version',FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if(!$assetId||!$versionId)media_stream_error(404,'Media not found');
$query=database()->prepare('SELECT a.kind,a.visibility,v.original_path,v.mime_type,v.processing_status FROM media_assets a JOIN media_versions v ON v.asset_id=a.id WHERE a.id=? AND v.id=?');$query->execute([$assetId,$versionId]);$media=$query->fetch();if(!$media||$media['kind']!=='video'||$media['processing_status']!=='ready'||!in_array($media['mime_type'],['video/mp4','video/webm'],true))media_stream_error(404,'Media not found');if(media_visibility((string)($media['visibility']??'public'))==='private'&&!current_admin())media_stream_error(404,'Media not found');
// Streaming a video while the PHP session is still open keeps the session file locked.
if(session_status()===PHP_SESSION_ACTIVE)session_write_close();
$root=realpath(media_upload_root());$file=realpath(media_upload_root().'/'.$media['original_path']);if($root===false||$file===false||!str_starts_with(str_replace('\\','/',$file),str_replace('\\','/',$root).'/')||!is_file($file))media_stream_error(404,'Media not found');
$size=filesize($file);if($size===false||$size<1)media_stream_error(404,'Media not found');try{[$start,$end,$status]=media_stream_range($size);}catch(Throwable){http_response_code(416);header('Content-Range: bytes */'.$size);exit;}$length=$end-$start+1;http_response_code($status);header('Content-Type: '.$media['mime_type']);header('Accept-Ranges: bytes');header('Content-Length: '.(string)$length);if($status===206)header('Content-Range: bytes '.$start.'-'.$end.'/'.$size);header('Cache-Control: '.(media_visibility((string)($media['visibility']??'public'))==='private'?'private, no-store':'public, max-age=3600'));if($_SERVER['REQUEST_METHOD']==='HEAD')exit;$handle=fopen($file,'rb');if($handle===false)media_stream_error(500,'Media unavailable');fseek($handle,$start);$remaining=$length;while($remaining>0&&!feof($handle)){$chunk=fread($handle,min(8192,$remaining));if($chunk===false)break;echo $chunk;$remaining-=strlen($chunk);flush();}fclose($handle);
