<?php
declare(strict_types=1);

return static function(PDO $db): void {
    $hasPages=(bool)$db->query("SELECT 1 FROM sqlite_master WHERE type='table' AND name='cms_pages'")->fetchColumn();
    $hasActivities=(bool)$db->query("SELECT 1 FROM sqlite_master WHERE type='table' AND name='activities'")->fetchColumn();
    if(!$hasPages||!$hasActivities||!function_exists('cms_page_document'))return;

    $activity=$db->query("SELECT * FROM activities WHERE status!='archived' ORDER BY is_root DESC,id LIMIT 1")->fetch(PDO::FETCH_ASSOC);
    if(!$activity)return;
    $activityId=(int)$activity['id'];$now=gmdate('c');

    $html=<<<'HTML'
<style id="positive-handbook-style">
.positive-handbook{--paper:#f2f2ef;--ink:#0b0c0d;--muted:#60635f;--line:#bfc1be;--soft:#e7e7e2;--accent:#186f4d;--display:"Saira Extra Condensed","Arial Narrow",sans-serif;--body:"IBM Plex Sans",Arial,sans-serif;--mono:"IBM Plex Mono",Consolas,monospace;background:#d8d9d4;color:var(--ink);padding:42px 18px 72px;font-family:var(--body)}
.positive-handbook *{box-sizing:border-box}.positive-handbook .sheet{width:min(100%,980px);margin:0 auto 28px;padding:58px 68px 64px;background:var(--paper);box-shadow:0 16px 48px rgba(0,0,0,.12)}
.positive-handbook .cover{display:grid;grid-template-columns:minmax(0,.9fr) minmax(300px,1.1fr);padding:0;overflow:hidden}.positive-handbook .cover-copy{padding:72px 58px 64px 68px;display:flex;min-height:760px;flex-direction:column;justify-content:space-between}.positive-handbook .cover-visual{position:relative;min-height:760px;background:#0b0c0d;overflow:hidden;border-left:2px solid #0b0c0d}.positive-handbook .cover-visual:before{content:"";position:absolute;inset:8%;border:1px solid #6b6e69}.positive-handbook .cover-visual:after{content:"";position:absolute;left:-18%;right:-18%;top:27%;height:45%;transform:rotate(-13deg);background:linear-gradient(110deg,#080808 0%,#313431 42%,#d8d9d4 77%,#f2f2ef 100%)}
.positive-handbook .eyebrow,.positive-handbook .kicker{font:500 11px/1.3 var(--mono);letter-spacing:.1em;text-transform:uppercase;color:var(--accent)}.positive-handbook .eyebrow{color:var(--muted)}
.positive-handbook h1,.positive-handbook h2,.positive-handbook h3{margin:0;font-family:var(--display);font-weight:500;text-transform:uppercase}.positive-handbook h1{margin-top:40px;font-size:clamp(62px,7vw,92px);line-height:.79}.positive-handbook h2{font-size:clamp(44px,5vw,62px);line-height:.87}.positive-handbook h3{font-size:30px;line-height:.95}.positive-handbook .deck{max-width:430px;margin:34px 0 0;font-size:21px;line-height:1.38;font-weight:300}.positive-handbook .cover-meta{padding-top:16px;border-top:2px solid var(--ink);font:400 11px/1.55 var(--mono);letter-spacing:.04em;text-transform:uppercase;color:var(--muted)}
.positive-handbook .section-head{display:grid;grid-template-columns:250px 1fr;gap:42px;align-items:start;margin-bottom:38px}.positive-handbook .lead{margin:0;font-size:25px;line-height:1.34;font-weight:300}.positive-handbook .body{font-size:17px;line-height:1.62}.positive-handbook .body p{margin:0 0 18px}.positive-handbook .body p:last-child{margin-bottom:0}.positive-handbook .cols{display:grid;grid-template-columns:1fr 1fr;gap:42px}.positive-handbook .callout{padding:25px 28px;background:var(--soft);font-size:18px;line-height:1.5}.positive-handbook .callout strong{font-family:var(--display);font-size:33px;line-height:.95;text-transform:uppercase;font-weight:500}.positive-handbook .rule{border-top:2px solid var(--ink)}
.positive-handbook .table{width:100%;border-collapse:collapse;margin-top:30px;font-size:15px}.positive-handbook .table th,.positive-handbook .table td{padding:13px 9px;border-top:1px solid var(--line);vertical-align:top;text-align:left}.positive-handbook .table th{font:500 11px/1.3 var(--mono);letter-spacing:.06em;text-transform:uppercase;color:var(--muted)}.positive-handbook .table tr:first-child th{border-top:2px solid var(--ink)}
.positive-handbook .steps{counter-reset:step;margin-top:30px}.positive-handbook .steps>div{counter-increment:step;display:grid;grid-template-columns:42px 1fr;gap:14px;padding:14px 0;border-top:1px solid var(--line)}.positive-handbook .steps>div:first-child{border-top:2px solid var(--ink)}.positive-handbook .steps>div:before{content:counter(step,decimal-leading-zero);font:500 12px var(--mono);color:var(--accent)}.positive-handbook .steps p{margin:0;font-size:16px;line-height:1.5}
.positive-handbook .formula{margin-top:28px;padding:24px 28px;border-left:5px solid var(--accent);background:#fbfbf8;font:500 18px/1.45 var(--mono)}.positive-handbook .two-metrics{display:grid;grid-template-columns:1fr 1fr;gap:1px;margin-top:32px;background:var(--line);border:1px solid var(--line)}.positive-handbook .metric{background:var(--paper);padding:24px}.positive-handbook .metric b{display:block;font:500 54px/.9 var(--display);text-transform:uppercase}.positive-handbook .metric span{display:block;margin-top:8px;color:var(--muted);font-size:14px;line-height:1.45}
.positive-handbook .diagram{margin-top:34px;border:1px solid var(--line);background:#f8f8f4;padding:28px}.positive-handbook .diagram svg{display:block;width:100%;height:auto}.positive-handbook .notes{display:grid;gap:0;margin-top:28px;border-top:2px solid var(--ink)}.positive-handbook .note{display:grid;grid-template-columns:170px 1fr;gap:24px;padding:16px 0;border-bottom:1px solid var(--line)}.positive-handbook .note b{font:500 11px/1.35 var(--mono);letter-spacing:.05em;text-transform:uppercase}.positive-handbook .note p{margin:0;font-size:15px;line-height:1.5}
.positive-handbook .final{background:#0b0c0d;color:#f2f2ef}.positive-handbook .final .kicker{color:#79cba7}.positive-handbook .final p{color:#d2d3cf}.positive-handbook .final .statement{margin:26px 0 44px;font:500 clamp(54px,6vw,78px)/.83 var(--display);text-transform:uppercase}.positive-handbook .final .statement em{font-style:normal;color:#79cba7}
@media(max-width:760px){.positive-handbook{padding:0;background:var(--paper)}.positive-handbook .sheet{margin:0;padding:34px 22px 42px;box-shadow:none;border-bottom:1px solid var(--line)}.positive-handbook .cover{grid-template-columns:1fr}.positive-handbook .cover-copy{min-height:590px;padding:42px 22px 38px}.positive-handbook .cover-visual{min-height:430px;border-left:0;border-top:2px solid var(--ink)}.positive-handbook .section-head,.positive-handbook .cols{grid-template-columns:1fr;gap:22px}.positive-handbook .two-metrics{grid-template-columns:1fr}.positive-handbook .note{grid-template-columns:1fr;gap:7px}.positive-handbook .lead{font-size:21px}.positive-handbook .body{font-size:16px}.positive-handbook .table{display:block;overflow-x:auto}}
</style>
<div class="positive-handbook">
<section class="sheet cover" data-cms-section="caderno-capa" data-cms-section-name="Capa">
  <div class="cover-copy"><div><p class="eyebrow" data-cms-editable>João Saidler · fotografia química</p><h1 data-cms-editable>Positivo direto<br>em filme<br>de raio-X</h1><p class="deck" data-cms-editable>Exposição, energia, revelação e reversão pensadas como partes do mesmo processo.</p></div><div class="cover-meta" data-cms-editable>Caderno de processo<br>Material técnico de referência<br>Petrópolis · Brasil</div></div>
  <div class="cover-visual" role="img" aria-label="Composição abstrata entre densidade e transparência da base do filme"></div>
</section>

<section class="sheet" data-cms-section="caderno-01-principio" data-cms-section-name="O positivo que procuro">
  <div class="section-head"><div><p class="kicker" data-cms-editable>01 · Princípio geral</p><h2 data-cms-editable>O positivo<br>que procuro</h2></div><p class="lead" data-cms-editable>Pretos densos o suficiente para bloquear a luz; altas luzes chegando à transparência da base do filme — e fotografia entre uma coisa e outra.</p></div>
  <div class="cols"><div class="body"><p data-cms-editable>Um preto absoluto e uma transparência absoluta sem nada no meio podem produzir um excelente estêncil, mas não necessariamente a fotografia que procurávamos.</p><p data-cms-editable>O ponto importante é preservar diferenças entre valores próximos. O resultado final precisa continuar sendo a fotografia que procurávamos.</p></div><div class="two-metrics"><div class="metric"><b data-cms-editable>Preto</b><span data-cms-editable>densidade suficiente para impedir a passagem da luz</span></div><div class="metric"><b data-cms-editable>Branco</b><span data-cms-editable>aproximação da transparência da base do filme</span></div></div></div>
</section>

<section class="sheet" data-cms-section="caderno-02-filme" data-cms-section-name="Filme de raio-X">
  <div class="section-head"><div><p class="kicker" data-cms-editable>02 · O material</p><h2 data-cms-editable>Fuji<br>Super HR-U</h2></div><p class="lead" data-cms-editable>O filme é ortocromático e possui emulsão nos dois lados. Essas duas características influenciam tanto a exposição quanto o processamento.</p></div>
  <div class="cols"><div class="body"><p data-cms-editable>Vermelhos tendem a aparecer mais escuros; verdes e azuis tendem a ser registrados com mais facilidade. Não é uma reprodução neutra das cores da cena.</p><p data-cms-editable>A dupla emulsão aumenta a quantidade de material fotossensível disponível, mas também exige cuidado no processamento molhado: as duas faces podem riscar e idealmente devem receber tratamento equivalente.</p></div><div class="diagram"><svg viewBox="0 0 520 360" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><rect x="78" y="70" width="364" height="220" fill="#d7d8d3" stroke="#0b0c0d" stroke-width="2"/><rect x="78" y="70" width="364" height="26" fill="#0b0c0d"/><rect x="78" y="264" width="364" height="26" fill="#0b0c0d"/><text x="260" y="45" text-anchor="middle" font-family="monospace" font-size="17">CHAPA · DUPLA EMULSÃO</text><text x="457" y="91" font-family="monospace" font-size="12" fill="#186f4d">EMULSÃO</text><text x="457" y="184" font-family="monospace" font-size="12" fill="#186f4d">BASE</text><text x="457" y="286" font-family="monospace" font-size="12" fill="#186f4d">EMULSÃO</text></svg></div></div>
</section>

<section class="sheet" data-cms-section="caderno-03-exposicao" data-cms-section-name="Exposição e energia">
  <div class="section-head"><div><p class="kicker" data-cms-editable>03 · Exposição</p><h2 data-cms-editable>Uma cena,<br>muitas energias</h2></div><p class="lead" data-cms-editable>Há uma única exposição para a chapa inteira, mas cada região da cena entrega uma quantidade diferente de energia ao filme.</p></div>
  <div class="body"><p data-cms-editable>Uma região que recebe um ponto a menos entrega metade da energia. Três pontos a menos entregam 1/8. Cinco pontos a menos, 1/32.</p><p data-cms-editable>No positivo direto, mais energia de exposição gera mais prata metálica na primeira revelação. Essa prata será removida no branqueamento e a região tende à transparência. Menos energia gera menos prata na primeira revelação e deixa mais material para a inversão, produzindo maior densidade no positivo.</p><p data-cms-editable>Quando a exposição é insuficiente, as regiões profundas deixam de se separar. Mais revelador não devolve a energia que não chegou ao filme.</p></div>
  <div class="formula" data-cms-editable>−1 EV = 1/2 · −3 EV = 1/8 · −5 EV = 1/32</div>
</section>

<section class="sheet" data-cms-section="caderno-04-reciprocidade" data-cms-section-name="Falha de reciprocidade">
  <div class="section-head"><div><p class="kicker" data-cms-editable>04 · Tempos longos</p><h2 data-cms-editable>Falha de<br>reciprocidade</h2></div><p class="lead" data-cms-editable>Em exposições longas, dobrar o tempo já não significa necessariamente entregar ao filme o dobro do efeito fotográfico.</p></div>
  <div class="formula" data-cms-editable>tempo corrigido = tempo calculado<sup>1,3854</sup></div>
  <table class="table"><tr><th data-cms-editable>Condição</th><th data-cms-editable>Tempo calculado</th><th data-cms-editable>Tempo corrigido</th></tr><tr><td data-cms-editable>EV 13</td><td data-cms-editable>8 s</td><td data-cms-editable>18 s</td></tr><tr><td data-cms-editable>EV 10</td><td data-cms-editable>1 min</td><td data-cms-editable>5 min</td></tr><tr><td data-cms-editable>EV 8</td><td data-cms-editable>4 min</td><td data-cms-editable>mais de 30 min</td></tr><tr><td data-cms-editable>EV 6</td><td data-cms-editable>17 min</td><td data-cms-editable>mais de 4 h</td></tr></table>
  <div class="callout" style="margin-top:30px"><strong data-cms-editable>São duas coisas diferentes.</strong><p data-cms-editable>Uma cena pode ter regiões com pouca energia mesmo em tempos curtos. A falha de reciprocidade é outro fenômeno: aparece porque o filme responde de maneira menos eficiente quando a exposição se prolonga.</p></div>
</section>

<section class="sheet" data-cms-section="caderno-05-ei" data-cms-section-name="Índice de exposição">
  <div class="section-head"><div><p class="kicker" data-cms-editable>05 · Fotometria</p><h2 data-cms-editable>EI,<br>não ISO</h2></div><p class="lead" data-cms-editable>Para esse uso fotográfico do Super HR-U, EI é uma referência operacional de exposição, não uma sensibilidade fotográfica fornecida pelo fabricante.</p></div>
  <div class="cols"><div class="body"><p data-cms-editable>Passar de EI 200 para EI 400 retira uma parada de exposição: a segunda condição entrega ao filme metade da luz da primeira.</p><p data-cms-editable>Pensando pelo Sistema de Zonas, uma região colocada em Zona III com EI 200 passa para Zona II quando o fotômetro é ajustado para EI 400, mantidas as demais condições.</p></div><div class="callout"><strong data-cms-editable>Exposição e revelação trabalham juntas.</strong><p data-cms-editable>Cada uma, porém, tem seu trabalho. A revelação pode controlar até onde a reação avança; não pode reconstruir detalhe de sombra que nunca recebeu energia suficiente.</p></div></div>
  <table class="table"><tr><th data-cms-editable></th><th data-cms-editable>Condição A</th><th data-cms-editable>Condição B</th></tr><tr><td data-cms-editable>EI</td><td data-cms-editable>200</td><td data-cms-editable>400</td></tr><tr><td data-cms-editable>Parodinal</td><td data-cms-editable>10 ml + água até 550 ml</td><td data-cms-editable>20 ml + água até 550 ml</td></tr><tr><td data-cms-editable>Tempo</td><td data-cms-editable>7 min</td><td data-cms-editable>7 min</td></tr><tr><td data-cms-editable>Temperatura</td><td data-cms-editable>26 °C</td><td data-cms-editable>26 °C</td></tr><tr><td data-cms-editable>Agitação</td><td data-cms-editable>leve</td><td data-cms-editable>leve</td></tr></table>
</section>

<section class="sheet" data-cms-section="caderno-06-imagem-latente" data-cms-section-name="Imagem latente e prata metálica">
  <div class="section-head"><div><p class="kicker" data-cms-editable>06 · Química da imagem</p><h2 data-cms-editable>O que estamos<br>revelando</h2></div><p class="lead" data-cms-editable>A emulsão contém cristais de haletos de prata. A luz altera parte desses cristais e forma uma imagem latente que ainda não vemos.</p></div>
  <div class="cols"><div class="body"><p data-cms-editable>O revelador é uma solução redutora. Nas regiões adequadamente expostas, ele favorece a transformação dos íons de prata em prata metálica.</p><p data-cms-editable>A densidade que vemos depois da revelação é formada pela prata metálica produzida nesse processo.</p></div><div class="formula" data-cms-editable>Ag⁺ + elétron → Ag⁰</div></div>
  <div class="diagram"><svg viewBox="0 0 760 270" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><rect x="0" y="0" width="300" height="210" fill="#fff" stroke="#bfc1be"/><rect x="460" y="0" width="300" height="210" fill="#fff" stroke="#bfc1be"/><g fill="#b8bab5"><circle cx="70" cy="70" r="26"/><circle cx="150" cy="105" r="34"/><circle cx="235" cy="62" r="23"/><circle cx="90" cy="160" r="22"/><circle cx="220" cy="160" r="31"/></g><g fill="#0b0c0d"><circle cx="530" cy="70" r="26"/><circle cx="610" cy="105" r="34"/><circle cx="695" cy="62" r="23"/><circle cx="550" cy="160" r="22"/><circle cx="680" cy="160" r="31"/></g><line x1="330" y1="105" x2="430" y2="105" stroke="#186f4d" stroke-width="5"/><polygon points="430,105 406,92 406,118" fill="#186f4d"/><text x="150" y="250" text-anchor="middle" font-family="monospace" font-size="16">HALETOS</text><text x="610" y="250" text-anchor="middle" font-family="monospace" font-size="16">PRATA METÁLICA</text></svg></div>
</section>

<section class="sheet" data-cms-section="caderno-07-revelador" data-cms-section-name="O revelador">
  <div class="section-head"><div><p class="kicker" data-cms-editable>07 · Revelação</p><h2 data-cms-editable>Três partes<br>básicas</h2></div><p class="lead" data-cms-editable>Um revelador precisa, em termos simples, de um agente redutor, um meio alcalino e água. A partir daí as fórmulas podem acrescentar conservantes e combinar mais de um agente revelador.</p></div>
  <div class="notes"><div class="note"><b data-cms-editable>Agente revelador</b><p data-cms-editable>reduz a prata exposta e permite a formação de prata metálica.</p></div><div class="note"><b data-cms-editable>Alcalinizante</b><p data-cms-editable>eleva o pH e cria o ambiente químico em que o agente revelador trabalha.</p></div><div class="note"><b data-cms-editable>Água</b><p data-cms-editable>é o meio no qual os componentes ficam dissolvidos e chegam à emulsão.</p></div></div>
</section>

<section class="sheet" data-cms-section="caderno-08-parodinal" data-cms-section-name="Parodinal">
  <div class="section-head"><div><p class="kicker" data-cms-editable>08 · Receita</p><h2 data-cms-editable>Parodinal</h2></div><p class="lead" data-cms-editable>No concentrado, a soda cáustica cria o meio alcalino e participa da transformação do paracetamol em p-aminofenol. O sulfito de sódio ajuda na conservação.</p></div>
  <table class="table"><tr><th data-cms-editable>Quantidade</th><th data-cms-editable>Componente</th></tr><tr><td data-cms-editable>250 ml</td><td data-cms-editable>água destilada ou desmineralizada</td></tr><tr><td data-cms-editable>15 g</td><td data-cms-editable>paracetamol</td></tr><tr><td data-cms-editable>50 g</td><td data-cms-editable>sulfito de sódio</td></tr><tr><td data-cms-editable>20 g</td><td data-cms-editable>hidróxido de sódio — soda cáustica perolizada P.A.</td></tr></table>
  <div class="steps"><div><p data-cms-editable>Ferver a água e deixar esfriar até aproximadamente 60 °C.</p></div><div><p data-cms-editable>Adicionar o paracetamol e o sulfito de sódio.</p></div><div><p data-cms-editable>Adicionar a soda cáustica lentamente.</p></div><div><p data-cms-editable>Manter fechado por três dias, agitando diariamente.</p></div><div><p data-cms-editable>Filtrar e guardar em frasco âmbar.</p></div></div>
  <div class="callout" style="margin-top:30px"><strong data-cms-editable>O concentrado é diluído.</strong><p data-cms-editable>15/550 significa 15 ml de Parodinal e água até completar 550 ml. O volume final é 550 ml.</p></div>
  <table class="table"><tr><th data-cms-editable>Parodinal</th><th data-cms-editable>Volume final</th></tr><tr><td data-cms-editable>15 ml</td><td data-cms-editable>água até 550 ml</td></tr><tr><td data-cms-editable>11 ml</td><td data-cms-editable>água até 550 ml</td></tr><tr><td data-cms-editable>6 ml</td><td data-cms-editable>água até 550 ml</td></tr><tr><td data-cms-editable>5 ml</td><td data-cms-editable>água até 550 ml</td></tr></table>
</section>

<section class="sheet" data-cms-section="caderno-09-caffenol" data-cms-section-name="Brewed Caffenol">
  <div class="section-head"><div><p class="kicker" data-cms-editable>09 · Revelador</p><h2 data-cms-editable>Brewed<br>Caffenol</h2></div><p class="lead" data-cms-editable>O Caffenol combina compostos fenólicos do café com ascorbato. É preparado diretamente na concentração de trabalho e deve ser usado fresco.</p></div>
  <table class="table"><tr><th data-cms-editable>Quantidade</th><th data-cms-editable>Componente</th></tr><tr><td data-cms-editable>37 g</td><td data-cms-editable>café moído de torra extra-forte</td></tr><tr><td data-cms-editable>54 g</td><td data-cms-editable>carbonato de sódio</td></tr><tr><td data-cms-editable>20 g</td><td data-cms-editable>ácido ascórbico</td></tr><tr><td data-cms-editable>até 1 litro</td><td data-cms-editable>água</td></tr></table>
  <div class="body" style="margin-top:30px"><p data-cms-editable>Ferver cerca de 500 ml de água com o café por aproximadamente cinco minutos e deixar repousar por dez. Em outra porção de água, dissolver primeiro o carbonato e depois o ácido ascórbico. Filtrar o café e misturar as duas partes; completar o volume final para um litro.</p><p data-cms-editable>Os fenólicos tendem a trabalhar de modo mais lento; o ascorbato acelera a atividade e se esgota com mais facilidade. Sem sulfito como conservante, a oxidação do preparado acontece rapidamente.</p></div>
</section>

<section class="sheet" data-cms-section="caderno-10-caminhos" data-cms-section-name="Negativo e positivo">
  <div class="section-head"><div><p class="kicker" data-cms-editable>10 · Depois da primeira revelação</p><h2 data-cms-editable>Positivo?<br>Negativo?</h2></div><p class="lead" data-cms-editable>Depois da primeira revelação, o filme contém uma mistura: prata metálica nas regiões que avançaram e haletos ainda não revelados nas regiões que avançaram menos.</p></div>
  <div class="two-metrics"><div class="metric"><b data-cms-editable>Negativo</b><span data-cms-editable>mantém a prata metálica da primeira revelação e remove os haletos não revelados com fixador.</span></div><div class="metric"><b data-cms-editable>Positivo</b><span data-cms-editable>remove a prata metálica da primeira revelação e preserva o material restante para uma segunda revelação.</span></div></div>
  <div class="formula" data-cms-editable>exposição → 1ª revelação → branqueamento → limpeza → 2ª revelação → positivo</div>
</section>

<section class="sheet" data-cms-section="caderno-11-peracetica" data-cms-section-name="Solução peracética">
  <div class="section-head"><div><p class="kicker" data-cms-editable>11 · Branqueamento</p><h2 data-cms-editable>Solução<br>peracética</h2></div><p class="lead" data-cms-editable>Na solução peracética, a prata metálica é oxidada. Durante a reação, o peróxido também libera oxigênio; as bolhas podem aderir à emulsão e produzir manchas.</p></div>
  <table class="table"><tr><th data-cms-editable>Quantidade</th><th data-cms-editable>Componente</th></tr><tr><td data-cms-editable>650 ml</td><td data-cms-editable>água</td></tr><tr><td data-cms-editable>150 ml</td><td data-cms-editable>vinagre de álcool</td></tr><tr><td data-cms-editable>200 ml</td><td data-cms-editable>peróxido de hidrogênio 50%</td></tr></table>
  <div class="body" style="margin-top:28px"><p data-cms-editable>Ordem de preparo: água, vinagre e depois peróxido. O preparado descansa antes do uso; o tempo de branqueamento observado costuma ficar em torno de dois minutos, mas varia com a solução e com o modo de uso.</p></div>
  <div class="callout" style="margin-top:28px"><strong data-cms-editable>Peróxido a 50% é concentrado.</strong><p data-cms-editable>Use proteção adequada, recipientes compatíveis e ventilação.</p></div>
</section>

<section class="sheet" data-cms-section="caderno-12-fecl3" data-cms-section-name="Cloreto férrico e amônia">
  <div class="section-head"><div><p class="kicker" data-cms-editable>12 · Branqueamento</p><h2 data-cms-editable>FeCl₃<br>+ amônia</h2></div><p class="lead" data-cms-editable>O cloreto férrico re-halogeniza a prata: oxida a prata metálica e forma cloreto de prata. A amônia vem depois, em um banho separado, para solubilizar e remover esse material.</p></div>
  <div class="cols"><div><h3 data-cms-editable>Cloreto férrico</h3><div class="formula" data-cms-editable>1 parte de FeCl₃ em pó : 4 partes de água</div><div class="body" style="margin-top:20px"><p data-cms-editable>Exemplo: 100 g de cloreto férrico + 400 ml de água. Coloque a água primeiro e adicione o pó lentamente; a dissolução libera calor.</p></div></div><div><h3 data-cms-editable>Amônia</h3><div class="formula" data-cms-editable>1 parte de amônia : 4 partes de água</div><div class="body" style="margin-top:20px"><p data-cms-editable>Exemplo: 100 ml de amônia + 400 ml de água. Use produto simples, sem perfume ou detergente. Concentrações comerciais variam.</p></div></div></div>
  <div class="callout" style="margin-top:30px"><strong data-cms-editable>Nunca misture amônia com cloro.</strong><p data-cms-editable>Amônia não deve ser combinada com água sanitária, hipoclorito ou outros produtos clorados.</p></div>
</section>

<section class="sheet" data-cms-section="caderno-13-segunda-revelacao" data-cms-section-name="Segunda revelação">
  <div class="section-head"><div><p class="kicker" data-cms-editable>13 · Reversão</p><h2 data-cms-editable>Segunda<br>revelação</h2></div><p class="lead" data-cms-editable>Depois que a prata da primeira revelação foi removida, a segunda revelação trabalha o material restante e constrói a densidade final do positivo.</p></div>
  <div class="body"><p data-cms-editable>Em um processo padrão, essa etapa pode seguir até o fim. Se ela for interrompida deliberadamente, haletos ainda não revelados permanecem fotossensíveis e precisam ser fixados.</p><p data-cms-editable>A reversão não corrige exposição insuficiente. Ela apenas transforma em imagem o material que sobreviveu às etapas anteriores.</p></div>
</section>

<section class="sheet" data-cms-section="caderno-14-parametros" data-cms-section-name="Quatro parâmetros da revelação">
  <div class="section-head"><div><p class="kicker" data-cms-editable>14 · Controle</p><h2 data-cms-editable>Quatro<br>parâmetros</h2></div><p class="lead" data-cms-editable>Concentração, tempo, agitação e temperatura não são quatro formas equivalentes de fazer a mesma coisa. Cada uma altera o processo de uma maneira própria.</p></div>
  <div class="notes"><div class="note"><b data-cms-editable>Concentração</b><p data-cms-editable>altera a quantidade de agente revelador disponível; concentrações muito altas podem tornar o processo rápido demais para preencher, agitar e esvaziar o tanque de forma uniforme.</p></div><div class="note"><b data-cms-editable>Tempo</b><p data-cms-editable>controla até onde a reação avança e influencia a separação geral entre valores.</p></div><div class="note"><b data-cms-editable>Agitação</b><p data-cms-editable>renova o revelador junto à emulsão. Sem agitação, a exaustão local aparece mais fortemente nas regiões de maior exposição e pode produzir efeito compensador.</p></div><div class="note"><b data-cms-editable>Temperatura</b><p data-cms-editable>altera a velocidade das reações. Temperaturas altas aceleram o processo e também aumentam o risco de amolecer a gelatina.</p></div></div>
  <div class="callout" style="margin-top:30px"><strong data-cms-editable>Para estudar uma variável, estabilize as outras três.</strong><p data-cms-editable>Se mudamos várias ao mesmo tempo, criamos outra condição de processamento e perdemos a referência do que produziu a diferença.</p></div>
</section>

<section class="sheet" data-cms-section="caderno-15-normal" data-cms-section-name="Hipótese de desenvolvimento normal">
  <div class="section-head"><div><p class="kicker" data-cms-editable>15 · Hipótese de trabalho</p><h2 data-cms-editable>Onde está<br>o normal?</h2></div><p class="lead" data-cms-editable>O comportamento observado com 10 ml de Parodinal, 550 ml finais, 26 °C e agitação leve sugere que sete minutos já representem uma revelação estendida.</p></div>
  <div class="formula" data-cms-editable>10 ml Parodinal · água até 550 ml · 26 °C · 5 min · agitação leve</div>
  <div class="body" style="margin-top:26px"><p data-cms-editable>A hipótese atual é que o desenvolvimento normal esteja mais próximo de cinco minutos. Isso ainda precisa ser confirmado.</p><p data-cms-editable>Se os cinco minutos se confirmarem, sete minutos representam aproximadamente 40% a mais de tempo. Isso não significa que todos os valores avancem 40%: a resposta não é linear e cada região parte de uma quantidade diferente de exposição.</p></div>
</section>

<section class="sheet" data-cms-section="caderno-16-materiais" data-cms-section-name="Materiais e fornecedores">
  <div class="section-head"><div><p class="kicker" data-cms-editable>16 · Materiais</p><h2 data-cms-editable>Onde<br>encontrar</h2></div><p class="lead" data-cms-editable>Os nomes abaixo são uma referência prática de compra; a concentração e a pureza do produto real devem ser conferidas antes do uso.</p></div>
  <div class="notes"><div class="note"><b data-cms-editable>Água desmineralizada</b><p data-cms-editable>lojas de produtos automotivos; verificar ausência de aditivos.</p></div><div class="note"><b data-cms-editable>Paracetamol</b><p data-cms-editable>farmácias; comprimidos sem revestimento facilitam o preparo.</p></div><div class="note"><b data-cms-editable>Sulfito / NaOH P.A.</b><p data-cms-editable>fornecedores de produtos químicos.</p></div><div class="note"><b data-cms-editable>Carbonato de sódio</b><p data-cms-editable>lojas de produtos para piscina.</p></div><div class="note"><b data-cms-editable>Peróxido 50%</b><p data-cms-editable>fornecedores de produtos para piscina; produto concentrado.</p></div><div class="note"><b data-cms-editable>Cloreto férrico</b><p data-cms-editable>lojas de eletrônica.</p></div><div class="note"><b data-cms-editable>Amônia</b><p data-cms-editable>lojas de produtos para cabelo ou artigos religiosos; usar fórmula simples, sem perfume ou detergente.</p></div><div class="note"><b data-cms-editable>Filme de raio-X</b><p data-cms-editable>distribuidores de material radiológico. O formato 13×18 cm pode ser mais difícil de encontrar.</p></div></div>
</section>

<section class="sheet" data-cms-section="caderno-17-registro" data-cms-section-name="Registro de testes">
  <div class="section-head"><div><p class="kicker" data-cms-editable>17 · Pesquisa</p><h2 data-cms-editable>Anote<br>os testes</h2></div><p class="lead" data-cms-editable>Um teste que não pode ser comparado depois vale muito menos. O registro transforma resultado isolado em referência de processo.</p></div>
  <table class="table"><tr><th data-cms-editable>Exposição</th><th data-cms-editable>Revelação</th><th data-cms-editable>Resultado</th></tr><tr><td data-cms-editable>filme e lote; EI; abertura; tempo calculado; tempo corrigido; condição de luz</td><td data-cms-editable>revelador; diluição; temperatura; tempo; agitação; branqueamento e limpeza</td><td data-cms-editable>separação de sombras; altas luzes; densidade máxima; manchas; riscos; observações</td></tr></table>
</section>

<section class="sheet final" data-cms-section="caderno-18-final" data-cms-section-name="Referência final">
  <p class="kicker" data-cms-editable>Referência final</p><div class="statement" data-cms-editable>Apenas dois momentos decisivos:<br><em>exposição e revelação.</em></div><div class="body"><p data-cms-editable>A exposição decide quanta energia cada região do filme recebe. A revelação decide até onde a reação avança sobre essa distribuição. O positivo direto aparece da relação entre as duas.</p><p data-cms-editable>A receita é um ponto de partida. O processo é a relação entre as variáveis.</p></div>
</section>
</div>
HTML;

    $document=cms_page_document(['theme'=>'auto','meta'=>['title'=>'Caderno de processo — Positivo Direto em Filme de Raio-X','description'=>'Material técnico protegido do workshop sobre exposição, revelação e produção de positivos diretos em filme de raio-X.'],'html'=>$html]);
    $json=json_encode($document,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);
    $q=$db->prepare("SELECT * FROM cms_pages WHERE activity_id=? AND locale='pt-BR' AND slug='caderno-positivo-direto' AND status!='archived' LIMIT 1");$q->execute([$activityId]);$page=$q->fetch(PDO::FETCH_ASSOC)?:null;
    if($page){$revision=max((int)$page['draft_revision'],(int)($page['published_revision']??0))+1;$db->prepare("UPDATE cms_pages SET title=?,nav_title=?,show_in_nav=0,draft_document_json=?,published_document_json=?,draft_revision=?,published_revision=?,draft_updated_at=?,published_at=?,updated_at=?,access_level='enrolled' WHERE id=?")->execute(['Caderno de processo — Positivo Direto em Filme de Raio-X','Caderno de processo',$json,$json,$revision,$revision,$now,$now,$now,(int)$page['id']]);$pageId=(int)$page['id'];}
    else{$sortQ=$db->prepare("SELECT COALESCE(MAX(sort_order),0)+1 FROM cms_pages WHERE activity_id=? AND locale='pt-BR'");$sortQ->execute([$activityId]);$sort=(int)$sortQ->fetchColumn();$db->prepare("INSERT INTO cms_pages(page_uuid,activity_id,locale,slug,title,nav_title,status,is_home,show_in_nav,sort_order,draft_document_json,published_document_json,draft_revision,published_revision,draft_updated_at,published_at,created_at,updated_at,access_level) VALUES(?,?,?,?,?,?, 'active',0,0,?,?,?,?,?,?,?,?,?,'enrolled')")->execute([bin2hex(random_bytes(16)),$activityId,'pt-BR','caderno-positivo-direto','Caderno de processo — Positivo Direto em Filme de Raio-X','Caderno de processo',$sort,$json,$json,1,1,$now,$now,$now,$now]);$pageId=(int)$db->lastInsertId();}

    if((bool)$db->query("SELECT 1 FROM sqlite_master WHERE type='table' AND name='cms_page_seo'")->fetchColumn())$db->prepare("INSERT INTO cms_page_seo(page_id,title,description,social_title,social_description,social_image,canonical_url,robots,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(page_id) DO UPDATE SET title=excluded.title,description=excluded.description,robots=excluded.robots,updated_at=excluded.updated_at")->execute([$pageId,'Caderno de processo — Positivo Direto em Filme de Raio-X','Material técnico protegido do workshop.','','','','','noindex,nofollow',$now]);

    if((bool)$db->query("SELECT 1 FROM sqlite_master WHERE type='table' AND name='course_page_sections'")->fetchColumn()){
        $lessonQ=$db->prepare('SELECT id,lesson_key FROM course_lessons WHERE activity_id=?');$lessonQ->execute([$activityId]);$lessons=[];foreach($lessonQ->fetchAll(PDO::FETCH_ASSOC) as $row)$lessons[(string)$row['lesson_key']]=(int)$row['id'];
        $map=$db->prepare('INSERT INTO course_page_sections(page_id,section_key,lesson_id,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(page_id,section_key) DO UPDATE SET lesson_id=excluded.lesson_id,updated_at=excluded.updated_at');
        foreach(['caderno-01-principio','caderno-02-filme','caderno-03-exposicao','caderno-04-reciprocidade','caderno-05-ei'] as $section)if(isset($lessons['aula-1']))$map->execute([$pageId,$section,$lessons['aula-1'],$now,$now]);
        foreach(['caderno-06-imagem-latente','caderno-07-revelador','caderno-08-parodinal','caderno-09-caffenol','caderno-10-caminhos','caderno-11-peracetica','caderno-12-fecl3','caderno-13-segunda-revelacao','caderno-14-parametros','caderno-15-normal','caderno-16-materiais','caderno-17-registro','caderno-18-final'] as $section)if(isset($lessons['aula-2']))$map->execute([$pageId,$section,$lessons['aula-2'],$now,$now]);
    }
};
