<?php
declare(strict_types=1);
function content_decode(?string $json): ?array {return $json?validate_content_document(json_decode($json,true,512,JSON_THROW_ON_ERROR)):null;}
function content_for_public(PDO $db,?int $activityId=null): array {$activityId??=(int)root_activity($db)['id'];$row=content_current($db,$activityId);$document=content_decode($row['published_json'])??canonical_content();return workshop_settings_apply_to_document($document,$db,$activityId);}
function content_for_draft(PDO $db,?int $activityId=null): array {$activityId??=(int)root_activity($db)['id'];$row=content_current($db,$activityId);$document=content_decode($row['draft_json'])??content_decode($row['published_json'])??canonical_content();return workshop_settings_apply_to_document($document,$db,$activityId);}
function content_metadata(array $row): array{return ['draftRevision'=>(int)$row['draft_revision'],'publishedRevision'=>$row['published_revision']===null?null:(int)$row['published_revision'],'draftUpdatedAt'=>$row['draft_updated_at'],'publishedAt'=>$row['published_at']];}
function content_save_draft(PDO $db,array $document,int $revision,?int $activityId=null): array {$activityId??=(int)root_activity($db)['id'];$document=workshop_settings_apply_to_document($document,$db,$activityId);$document=validate_content_document($document);$db->beginTransaction();try{content_current($db,$activityId);$new=$revision+1;$q=$db->prepare('UPDATE content_documents SET draft_json=?,schema_version=?,draft_revision=?,draft_updated_at=?,updated_at=? WHERE activity_id=? AND draft_revision=?');$now=gmdate('c');$q->execute([json_encode($document,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),$document['schemaVersion'],$new,$now,$now,$activityId,$revision]);if($q->rowCount()!==1)throw new RuntimeException('revision_conflict');$db->commit();return content_current($db,$activityId);}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
function content_publish(PDO $db,?int $activityId=null): array {$activityId??=(int)root_activity($db)['id'];$db->beginTransaction();try{$row=content_current($db,$activityId);$doc=content_decode($row['draft_json']);$now=gmdate('c');$q=$db->prepare('UPDATE content_documents SET published_json=?,published_revision=?,published_at=?,published_by=?,updated_at=? WHERE activity_id=?');$q->execute([json_encode($doc,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),(int)$row['draft_revision'],$now,(int)current_admin()['id'],$now,$activityId]);$db->commit();return content_current($db,$activityId);}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
function content_restore(PDO $db,?int $activityId=null): array {$activityId??=(int)root_activity($db)['id'];$db->beginTransaction();try{$row=content_current($db,$activityId);$doc=content_decode($row['published_json'])??canonical_content();$revision=(int)$row['draft_revision']+1;$now=gmdate('c');$q=$db->prepare('UPDATE content_documents SET draft_json=?,draft_revision=?,draft_updated_at=?,updated_at=? WHERE activity_id=?');$q->execute([json_encode($doc,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),$revision,$now,$now,$activityId]);$db->commit();return content_current($db,$activityId);}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
