<?php
declare(strict_types=1);

function canonical_content(): array { static $doc;return $doc??=json_decode(file_get_contents(dirname(__DIR__,2).'/data/public-content.json'),true,512,JSON_THROW_ON_ERROR); }
function content_validation_error(string $message): never { throw new InvalidArgumentException($message); }
function content_media_reference_valid(array $item,array $keys):bool{foreach($keys as $key)if(array_key_exists($key,$item)&&$item[$key]!==null&&(!is_int($item[$key])||$item[$key]<1))return false;return true;}
function validate_content_document(mixed $document): array {
    if(!is_array($document)||array_keys($document)!==array_filter(array_keys($document),'is_string'))content_validation_error('invalid_document');
    $canonical=canonical_content();$allowed=['schemaVersion','version','template','theme','texts','images','videos','sections','forms'];
    foreach($document as $key=>$_)if(!in_array($key,$allowed,true))content_validation_error('unexpected_property');
    if(($document['schemaVersion']??null)!==($canonical['schemaVersion']??null)||!is_int($document['schemaVersion'])||($document['version']??null)!==($canonical['version']??null)||($document['template']??null)!==($canonical['template']??null))content_validation_error('schema_version_incompatible');
    if(!in_array($document['theme']??'auto',['auto','light','dark'],true))content_validation_error('invalid_theme');
    foreach(['texts','images','videos','forms'] as $group)if(!is_array($document[$group]??null)||array_keys($document[$group])!==array_keys($canonical[$group]))content_validation_error('invalid_'.$group);
    foreach($document['texts'] as $item){$html=$item['html']??null;if(!is_array($item)||!is_string($html)||strlen($html)>12000||strip_tags($html,'<strong><em><b><i><a><span><br>')!==$html||preg_match('~<\s*(script|style|iframe|object)|on\w+\s*=|javascript:~i',$html))content_validation_error('invalid_text');}
    foreach($document['images'] as $item){$keys=['src','alt','objectFit','objectPosition','positionX','positionY','zoom','poster','autoplay','muted','loop','controls','aspectRatio','mediaAssetId','mediaVersionId'];if(!is_array($item)||array_diff(array_keys($item),$keys)||!content_media_reference_valid($item,['mediaAssetId','mediaVersionId']))content_validation_error('invalid_media');foreach($item as $value)if((!is_string($value)&&!is_bool($value)&&!is_int($value)&&!is_float($value)&&$value!==null)||(is_string($value)&&(strlen($value)>4000||preg_match('~javascript:~i',$value))))content_validation_error('invalid_media');}
    foreach($document['videos'] as $item){$keys=['src','alt','caption','objectFit','objectPosition','positionX','positionY','zoom','poster','autoplay','muted','loop','controls','aspectRatio','playsinline','mediaAssetId','mediaVersionId','posterId','posterTimestamp'];if(!is_array($item)||array_diff(array_keys($item),$keys)||!content_media_reference_valid($item,['mediaAssetId','mediaVersionId','posterId'])||(!empty($item['autoplay'])&&empty($item['muted'])))content_validation_error('invalid_media');if(array_key_exists('posterTimestamp',$item)&&$item['posterTimestamp']!==null&&(!is_float($item['posterTimestamp'])&&!is_int($item['posterTimestamp'])||$item['posterTimestamp']<0||!is_finite((float)$item['posterTimestamp'])))content_validation_error('invalid_poster_timestamp');foreach($item as $value)if((!is_string($value)&&!is_bool($value)&&!is_int($value)&&!is_float($value)&&$value!==null)||(is_string($value)&&(strlen($value)>4000||preg_match('~javascript:~i',$value))))content_validation_error('invalid_media');}
    if(!is_array($document['sections']??null)||count($document['sections'])!==count($canonical['sections']))content_validation_error('invalid_sections');$known=array_column($canonical['sections'],'id');$seen=[];foreach($document['sections'] as $section){if(!is_array($section)||!in_array($section['id']??'', $known,true)||isset($seen[$section['id']])||!is_bool($section['visible']??null))content_validation_error('invalid_sections');$seen[$section['id']]=true;}
    foreach($document['forms'] as $form){if(!is_array($form)||!is_array($form['fields']??null)||!is_string($form['submitLabel']??null)||strlen($form['submitLabel'])>500)content_validation_error('invalid_form');$ids=[];foreach($form['fields'] as $field){if(!is_array($field)||!preg_match('/^[a-z][a-z0-9_]{0,63}$/',$field['id']??'')||isset($ids[$field['id']])||!in_array($field['type']??'', ['text','email','textarea','select','radio','checkbox'],true)||!is_string($field['label']??null)||strlen($field['label'])>500||!is_bool($field['required']??null)||!in_array($field['audience']??'both',['both','en','pt-BR'],true))content_validation_error('invalid_form');$ids[$field['id']]=true;if(isset($field['options'])){if(!is_array($field['options'])||!in_array($field['type'],['select','radio'],true))content_validation_error('invalid_form');foreach($field['options'] as $option)if(!is_array($option)||!is_string($option['label']??null)||!is_string($option['value']??null)||strlen($option['label'])>500||strlen($option['value'])>200)content_validation_error('invalid_form');}}}
    $json=json_encode($document,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);if(strlen($json)>500000)content_validation_error('document_too_large');return $document;
}
