<?php
declare(strict_types=1);

const CMS_PAGE_DOCUMENT_VERSION=2;

function cms_page_uuid(): string { return bin2hex(random_bytes(16)); }
function cms_page_slug(string $value): string {
    $value=trim($value);
    if($value==='')return '';
    return activity_slug($value);
}
function cms_sanitize_html(string $html): string {
    if(trim($html)==='')return '';
    $previous=libxml_use_internal_errors(true);
    $dom=new DOMDocument('1.0','UTF-8');
    $wrapped='<!doctype html><html><body><div id="cms-root">'.$html.'</div></body></html>';
    $dom->loadHTML('<?xml encoding="utf-8" ?>'.$wrapped,LIBXML_HTML_NOIMPLIED|LIBXML_HTML_NODEFDTD);
    $xpath=new DOMXPath($dom);
    foreach(['script','iframe','object','embed','base','meta','link'] as $tag){foreach(iterator_to_array($xpath->query('//'.$tag)?:[]) as $node)$node->parentNode?->removeChild($node);}
    foreach(iterator_to_array($xpath->query('//*')?:[]) as $element){
        if(!$element instanceof DOMElement)continue;
        for($i=$element->attributes->length-1;$i>=0;$i--){$attr=$element->attributes->item($i);if(!$attr)continue;$name=strtolower($attr->name);$value=trim($attr->value);if(str_starts_with($name,'on')){$element->removeAttributeNode($attr);continue;}if(in_array($name,['href','src','action'],true)&&preg_match('~^\s*(?:javascript|data:text/html)\s*:~i',$value)){$element->removeAttributeNode($attr);}}
    }
    $root=$dom->getElementById('cms-root');$out='';if($root)foreach(iterator_to_array($root->childNodes) as $child)$out.=$dom->saveHTML($child);
    libxml_clear_errors();libxml_use_internal_errors($previous);return $out;
}
function cms_page_document(array $document): array {
    $theme=in_array($document['theme']??'auto',['auto','light','dark'],true)?$document['theme']:'auto';
    $meta=is_array($document['meta']??null)?$document['meta']:[];
    return [
        'version'=>CMS_PAGE_DOCUMENT_VERSION,
        'theme'=>$theme,
        'meta'=>[
            'title'=>trim((string)($meta['title']??'')),
            'description'=>trim((string)($meta['description']??'')),
        ],
        'html'=>cms_sanitize_html((string)($document['html']??'')),
    ];
}
function cms_default_home_document(string $locale): array {
    $pt=$locale===PUBLIC_LOCALE_PT_BR;
    if($pt){
        $html=<<<'HTML'
<section class="hero" data-cms-section="hero" data-cms-section-name="Início">
  <div class="hero-copy">
    <div class="hero-top">
      <p class="label" data-cms-editable>Nova turma em formação · Workshop em português</p>
      <h1 data-cms-editable><span>Positivo</span><span>Direto</span><span>em Filme de Raios X</span></h1>
      <p class="hero-intro" data-cms-editable>Um workshop on-line e ao vivo para entender, testar e controlar o positivo direto em filme de raios X — da exposição à leitura do resultado.</p>
    </div>
    <div class="hero-bottom">
      <dl class="hero-facts">
        <div><dt>Formato</dt><dd data-cms-editable>3 encontros ao vivo</dd></div>
        <div><dt>Turma</dt><dd data-cms-editable>Máximo de 10</dd></div>
        <div><dt>Idioma</dt><dd data-cms-editable>Português</dd></div>
        <div><dt>Valor</dt><dd data-cms-editable>R$ 698 via Pix</dd></div>
      </dl>
      <div class="cta-row"><a class="button button-primary" href="#inscricao" data-cms-editable>Quero participar da nova turma <span aria-hidden="true">↘</span></a><p class="microcopy" data-cms-editable>Pagamento por cartão também disponível, inclusive parcelado, com as taxas da plataforma.</p></div>
    </div>
  </div>
  <figure class="hero-image" data-cms-image-block><img src="/assets/media/hero-medusa.webp" alt="Medusa, retrato em preto e branco feito como positivo direto em filme de raios X" data-cms-image><figcaption><span data-cms-editable>Medusa · Filme de raios X positivo direto</span><span data-cms-editable>Highly Commended · Siena Creative Photo Awards 2025</span></figcaption></figure>
</section>
<section class="section" data-cms-section="workshop" data-cms-section-name="O workshop">
  <p class="section-label" data-cms-editable>01 / O workshop</p>
  <div class="statement-grid"><h2 data-cms-editable>A imagem acontece ao vivo, da exposição ao positivo.</h2><div class="statement-copy"><p data-cms-editable>Nada de aula gravada ou resultado preparado de antemão. Você acompanha em tempo real as decisões que antecedem a revelação, a exposição e a transformação do filme até a imagem positiva.</p><p data-cms-editable>Na segunda aula eu fotografo ao vivo e produzo o maior número de positivos que o tempo permitir, variando exposições e outros parâmetros para compararmos o que muda no resultado. A proposta não é entregar uma receita universal, mas tornar o processo compreensível o bastante para que cada participante tome as próprias decisões.</p></div></div>
</section>
<section class="cms-proof" data-cms-section="first-cohort" data-cms-section-name="Primeira turma">
  <div class="cms-proof-inner"><p class="section-label" data-cms-editable>02 / Primeira turma</p><div class="cms-proof-grid"><h2 data-cms-editable>A primeira turma colocou o processo à prova.</h2><div><p data-cms-editable>Durante a segunda aula produzimos uma sequência de positivos alterando exposição e parâmetros de processamento para observar as diferenças no resultado. Trabalhamos, entre outros testes, com o filme de raios X exposto em ISO 200 e ISO 400 e com diferentes diluições.</p><p data-cms-editable>No terceiro encontro, os resultados produzidos pelos próprios participantes voltam para a aula. Analisamos juntos as escolhas feitas, o comportamento do processo e o que cada imagem permite concluir para o teste seguinte.</p></div></div></div>
</section>
<section class="apparatus" data-cms-section="camera" data-cms-section-name="Câmera">
  <div class="apparatus-copy"><p class="section-label" data-cms-editable>03 / Equipamento</p><h2 data-cms-editable>A câmera faz parte do processo — mas você trabalha com o equipamento que tiver.</h2><p data-cms-editable>A NINA é uma câmera artesanal de grande formato criada para trabalhar com positivo direto em filme de raios X. Ela aparece no workshop porque torna visíveis as decisões que formam a imagem, não porque o participante precise reproduzi-la.</p><p class="technical-note" data-cms-editable>É possível trabalhar com 35 mm, médio formato ou grande formato. O foco do workshop é compreender o processo e suas variáveis.</p></div>
  <div class="apparatus-media"><figure class="media-figure vertical-frame" data-cms-image-block><div class="media-area"><img src="/assets/media/nina-poster.webp" alt="Câmera artesanal NINA" data-cms-image></div><figcaption class="media-caption frame-data" data-cms-editable>NINA · Câmera artesanal de grande formato</figcaption></figure></div>
</section>
<section class="section process" data-cms-section="process" data-cms-section-name="Processo">
  <div class="process-copy cms-process-wide"><p class="section-label" data-cms-editable>04 / Da exposição ao positivo</p><h2 data-cms-editable>Os parâmetros são observados em relação ao resultado — não como uma receita fixa.</h2><div class="process-list"><article class="process-item"><span>01</span><h3 data-cms-editable>Exposição</h3><p data-cms-editable>Medição da luz, índice de exposição, distribuição tonal e limites do filme de raios X.</p></article><article class="process-item"><span>02</span><h3 data-cms-editable>Primeira revelação</h3><p data-cms-editable>Tempo, temperatura, agitação, revelador e diluição como variáveis que modificam o positivo.</p></article><article class="process-item"><span>03</span><h3 data-cms-editable>Reversão</h3><p data-cms-editable>Branqueamento, limpeza, reexposição e segunda revelação acompanhados como partes da mesma cadeia.</p></article><article class="process-item"><span>04</span><h3 data-cms-editable>Leitura do resultado</h3><p data-cms-editable>Sombras, meios-tons, altas luzes e falhas do processo usados para orientar a decisão seguinte.</p></article></div></div>
</section>
<section class="cms-support" data-cms-section="support" data-cms-section-name="Suporte incluído">
  <div class="cms-support-inner"><div><p class="section-label" data-cms-editable>05 / Ferramenta incluída</p><h2 data-cms-editable>Uma ferramenta criada para um problema real do processo.</h2><p data-cms-editable>O filme de raios X possui emulsão nas duas faces e, durante o processamento, o contato com a bandeja pode produzir riscos. Por isso desenvolvi um suporte dobrável que mantém a chapa afastada da superfície durante os banhos.</p><p class="technical-note" data-cms-editable>Cada participante da turma em português recebe um suporte desenvolvido especificamente para esse uso.</p></div><div class="cms-media-placeholder" data-cms-image-placeholder><span>Adicione aqui a fotografia do suporte</span></div></div>
</section>
<section class="format" data-cms-section="format" data-cms-section-name="Formato">
  <div class="format-inner"><p class="section-label" data-cms-editable>06 / Formato</p><div class="format-heading"><h2 data-cms-editable>Três encontros para ver, testar e voltar com resultados.</h2><p data-cms-editable>A estrutura acompanha o processo antes, durante e depois da primeira tentativa de cada participante.</p></div><div class="format-grid"><article class="format-card"><span class="number">01</span><h3 data-cms-editable>Primeiro encontro</h3><p data-cms-editable>Filme de raios X, exposição e decisões que precisam ser tomadas antes da revelação.</p></article><article class="format-card"><span class="number">02</span><h3 data-cms-editable>Segundo encontro</h3><p data-cms-editable>Demonstração prática ao vivo, com o maior número possível de fotografias e variação deliberada de exposição e parâmetros.</p></article><article class="format-card"><span class="number">03</span><h3 data-cms-editable>Terceiro encontro</h3><p data-cms-editable>Análise dos resultados produzidos pelos participantes e discussão das decisões para os testes seguintes.</p></article><article class="format-card"><span class="number">04</span><h3 data-cms-editable>Turma pequena</h3><p data-cms-editable>Até 10 participantes, sem gravação, com espaço real para perguntas e análise das imagens.</p></article></div></div>
</section>
<section class="section about" data-cms-section="about" data-cms-section-name="João Saidler">
  <div class="about-copy"><p class="section-label" data-cms-editable>07 / O fotógrafo</p><h2 data-cms-editable>João Saidler</h2><p class="about-lead" data-cms-editable>Fotógrafo e pesquisador independente. Desde 2018, desenvolve imagens com câmeras artesanais de grande formato, filme de raios X e química fotográfica acessível.</p><p data-cms-editable>Seu trabalho parte da imagem e das perguntas que ela impõe. Câmeras, obturadores, tanques e métodos de processamento são ferramentas de uma prática que mantém exposição, química e objeto final sob o controle de quem fotografa.</p></div><figure class="media-figure about-image" data-cms-image-block><div class="media-area"><img src="/assets/media/joao-portrait.webp" alt="Fotógrafo João Saidler" data-cms-image></div><figcaption class="media-caption" data-cms-editable>João Saidler · Fotógrafo e pesquisador independente</figcaption></figure>
</section>
<section class="interest cms-form-section" id="inscricao" data-cms-section="registration" data-cms-section-name="Inscrição">
  <div class="interest-inner"><div class="interest-intro"><p class="section-label" data-cms-editable>08 / Nova turma</p><h2 data-cms-editable>Quer participar da próxima turma?</h2><p data-cms-editable>Preencha seus dados e sua disponibilidade. A inscrição acontece aqui no site; eu entro em contato com as próximas etapas e a organização das datas.</p></div><div data-cms-form-key="registration"></div></div>
</section>
HTML;
        return cms_page_document(['theme'=>'auto','meta'=>['title'=>'Positivo Direto em Filme de Raios X — Workshop On-line','description'=>'Workshop on-line e ao vivo sobre positivo direto em filme de raios X, exposição, revelação por reversão e análise de resultados.'],'html'=>$html]);
    }
    $html=<<<'HTML'
<section class="hero" data-cms-section="hero" data-cms-section-name="Home">
  <div class="hero-copy"><div class="hero-top"><p class="label" data-cms-editable>First English-language cohort · Interest list</p><h1 data-cms-editable><span>Direct</span><span>Positive</span><span>X-Ray Film</span></h1><p class="hero-intro" data-cms-editable>A fully live online workshop on exposure, reversal processing and reading the physical positive.</p></div><div class="hero-bottom"><dl class="hero-facts"><div><dt>Format</dt><dd data-cms-editable>3 live sessions</dd></div><div><dt>Group</dt><dd data-cms-editable>Maximum 10</dd></div><div><dt>Language</dt><dd data-cms-editable>English</dd></div><div><dt>Planned price</dt><dd data-cms-editable>US$195</dd></div></dl><div class="cta-row"><a class="button button-primary" href="#interest" data-cms-editable>Join the interest list <span aria-hidden="true">↘</span></a><p class="microcopy" data-cms-editable>No payment now. The survey will help define dates and time zones.</p></div></div></div>
  <figure class="hero-image" data-cms-image-block><img src="/assets/media/hero-medusa.webp" alt="Medusa, a black-and-white direct-positive portrait made on X-ray film" data-cms-image><figcaption><span data-cms-editable>Medusa · Direct-positive X-ray film</span><span data-cms-editable>Highly Commended · Siena Creative Photo Awards 2025</span></figcaption></figure>
</section>
<section class="section" data-cms-section="workshop" data-cms-section-name="The workshop"><p class="section-label" data-cms-editable>01 / The workshop</p><div class="statement-grid"><h2 data-cms-editable>The photograph is made live, from exposure to positive.</h2><div class="statement-copy"><p data-cms-editable>This is not a prerecorded course and not a demonstration assembled after the fact. Exposure decisions, chemistry and the physical transformation of the film are presented live from the studio in Brazil.</p><p data-cms-editable>During the second session I make as many photographs as the time allows, deliberately changing exposure and processing parameters so the group can compare what each decision changes. The purpose is not to hand out a universal recipe, but to make the process understandable and controllable.</p></div></div></section>
<section class="cms-proof" data-cms-section="first-cohort" data-cms-section-name="First cohort evidence"><div class="cms-proof-inner"><p class="section-label" data-cms-editable>02 / Tested in practice</p><div class="cms-proof-grid"><h2 data-cms-editable>The workshop has already been tested with a Portuguese-language cohort in Brazil.</h2><div><p data-cms-editable>During the live practical session we produced a sequence of positives while changing exposure and processing parameters. Among the comparisons were X-ray film exposed at EI 200 and EI 400 and different developer dilutions.</p><p data-cms-editable>The participants then produced their own tests. Their results became the material for the third meeting, where we discussed what each choice changed and what to try next. I am now forming the first English-language cohort.</p></div></div></div></section>
<section class="apparatus" data-cms-section="camera" data-cms-section-name="Camera"><div class="apparatus-copy"><p class="section-label" data-cms-editable>03 / Apparatus</p><h2 data-cms-editable>The camera is part of my process — not a requirement for yours.</h2><p data-cms-editable>The NINA is a handmade large-format camera developed for direct-positive X-ray film. It appears in the workshop because it makes the photographic chain visible, not because participants need to reproduce it.</p><p class="technical-note" data-cms-editable>You can work with 35 mm, medium format or large format. The workshop is about understanding the process and its variables.</p></div><div class="apparatus-media"><figure class="media-figure vertical-frame" data-cms-image-block><div class="media-area"><img src="/assets/media/nina-poster.webp" alt="NINA handmade large-format camera" data-cms-image></div><figcaption class="media-caption frame-data" data-cms-editable>NINA · Handmade large-format camera</figcaption></figure></div></section>
<section class="section process" data-cms-section="process" data-cms-section-name="Process"><div class="process-copy cms-process-wide"><p class="section-label" data-cms-editable>04 / From exposure to positive</p><h2 data-cms-editable>The parameters are read in relation to the result, not memorized as a fixed recipe.</h2><div class="process-list"><article class="process-item"><span>01</span><h3 data-cms-editable>Exposure</h3><p data-cms-editable>Metering, working EI, tonal placement, reciprocity and the particular limits of X-ray film.</p></article><article class="process-item"><span>02</span><h3 data-cms-editable>First development</h3><p data-cms-editable>Time, temperature, agitation, developer and dilution as variables that change the final positive.</p></article><article class="process-item"><span>03</span><h3 data-cms-editable>Reversal</h3><p data-cms-editable>Bleaching, clearing, re-exposure and second development treated as one connected chain.</p></article><article class="process-item"><span>04</span><h3 data-cms-editable>Reading the result</h3><p data-cms-editable>Shadows, midtones, highlights and defects used to decide what the next test should change.</p></article></div></div></section>
<section class="cms-support" data-cms-section="support" data-cms-section-name="Processing support"><div class="cms-support-inner"><div><p class="section-label" data-cms-editable>05 / A tool developed from the process</p><h2 data-cms-editable>A simple solution to a problem specific to double-emulsion film.</h2><p data-cms-editable>X-ray film carries emulsion on both sides, so wet sheets are especially vulnerable to scratches against processing trays. I developed a foldable support that keeps the sheet away from the tray surface during the baths.</p><p class="technical-note" data-cms-editable>The support is used in the workshop demonstrations. International delivery, if offered, will be confirmed separately for each cohort.</p></div><div class="cms-media-placeholder" data-cms-image-placeholder><span>Add a photograph of the processing support</span></div></div></section>
<section class="format" data-cms-section="format" data-cms-section-name="Format"><div class="format-inner"><p class="section-label" data-cms-editable>06 / Format</p><div class="format-heading"><h2 data-cms-editable>Three meetings: understand, observe, test and return with results.</h2><p data-cms-editable>The structure follows the process before, during and after each participant's first tests.</p></div><div class="format-grid"><article class="format-card"><span class="number">01</span><h3 data-cms-editable>First meeting</h3><p data-cms-editable>X-ray film, exposure and the decisions that need to be made before processing.</p></article><article class="format-card"><span class="number">02</span><h3 data-cms-editable>Second meeting</h3><p data-cms-editable>Live practical demonstration with as many photographs as possible and deliberate changes in exposure and processing parameters.</p></article><article class="format-card"><span class="number">03</span><h3 data-cms-editable>Third meeting</h3><p data-cms-editable>Analysis of participants' own results and discussion of what their next tests should change.</p></article><article class="format-card"><span class="number">04</span><h3 data-cms-editable>Small group</h3><p data-cms-editable>Maximum 10 participants, no recordings, with real time for questions and result analysis.</p></article></div></div></section>
<section class="section about" data-cms-section="about" data-cms-section-name="João Saidler"><div class="about-copy"><p class="section-label" data-cms-editable>07 / The photographer</p><h2 data-cms-editable>João Saidler</h2><p class="about-lead" data-cms-editable>Photographer and independent researcher working with handmade large-format cameras, direct-positive X-ray film and accessible photographic chemistry since 2018.</p><p data-cms-editable>His practice is centered on the photographic image. Cameras, shutters, tanks and processing systems are developed as parts of a working chain that keeps exposure, chemistry and the final physical object under the photographer's control.</p></div><figure class="media-figure about-image" data-cms-image-block><div class="media-area"><img src="/assets/media/joao-portrait.webp" alt="Photographer João Saidler" data-cms-image></div><figcaption class="media-caption" data-cms-editable>João Saidler · Photographer and independent researcher</figcaption></figure></section>
<section class="interest cms-form-section" id="interest" data-cms-section="interest" data-cms-section-name="Interest survey"><div class="interest-inner"><div class="interest-intro"><p class="section-label" data-cms-editable>08 / First English-language cohort</p><h2 data-cms-editable>Would you seriously consider joining?</h2><p data-cms-editable>The Portuguese-language cohort has already been completed. This survey will be used to define dates, time zones and the first English-language group.</p></div><div data-cms-form-key="interest"></div></div></section>
HTML;
    return cms_page_document(['theme'=>'auto','meta'=>['title'=>'Direct Positive X-Ray Film — Live Online Workshop','description'=>'Live online workshop on direct-positive X-ray film, exposure, reversal processing and reading the physical positive.'],'html'=>$html]);
}
function cms_pages_seed(PDO $db,int $activityId): void {
    $q=$db->prepare("SELECT COUNT(*) FROM cms_pages WHERE activity_id=? AND status!='archived'");$q->execute([$activityId]);if((int)$q->fetchColumn()>0)return;
    cms_forms_seed($db,$activityId);$now=utc_now();$insert=$db->prepare('INSERT INTO cms_pages(page_uuid,activity_id,locale,slug,title,nav_title,status,is_home,show_in_nav,sort_order,draft_document_json,published_document_json,draft_revision,published_revision,draft_updated_at,published_at,created_at,updated_at)VALUES(?,?,?,?,?,?,"active",1,1,1,?,?,1,1,?,?,?,?)');
    foreach([[PUBLIC_LOCALE_PT_BR,'Positivo Direto em Filme de Raios X','Workshop'],[PUBLIC_LOCALE_EN,'Direct Positive X-Ray Film','Workshop']] as [$locale,$title,$nav]){$doc=cms_default_home_document($locale);$json=json_encode($doc,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$insert->execute([cms_page_uuid(),$activityId,$locale,'',$title,$nav,$json,$json,$now,$now,$now,$now]);}
}
function cms_pages(PDO $db,int $activityId,?string $locale=null,bool $includeArchived=false): array {
    $sql='SELECT * FROM cms_pages WHERE activity_id=?';$args=[$activityId];if($locale!==null){$sql.=' AND locale=?';$args[]=$locale;}if(!$includeArchived)$sql.=" AND status!='archived'";$sql.=' ORDER BY locale,sort_order,id';$q=$db->prepare($sql);$q->execute($args);return $q->fetchAll();
}
function cms_page_by_id(PDO $db,int $id): ?array {$q=$db->prepare('SELECT * FROM cms_pages WHERE id=?');$q->execute([$id]);return $q->fetch()?:null;}
function cms_page_by_uuid(PDO $db,string $uuid): ?array {$q=$db->prepare("SELECT * FROM cms_pages WHERE page_uuid=? AND status!='archived'");$q->execute([$uuid]);return $q->fetch()?:null;}
function cms_page_home(PDO $db,int $activityId,string $locale): ?array {$q=$db->prepare("SELECT * FROM cms_pages WHERE activity_id=? AND locale=? AND is_home=1 AND status!='archived' LIMIT 1");$q->execute([$activityId,$locale]);return $q->fetch()?:null;}
function cms_page_by_slug(PDO $db,int $activityId,string $locale,string $slug): ?array {$slug=cms_page_slug($slug);if($slug==='')return cms_page_home($db,$activityId,$locale);$q=$db->prepare("SELECT * FROM cms_pages WHERE activity_id=? AND locale=? AND slug=? AND status!='archived' LIMIT 1");$q->execute([$activityId,$locale,$slug]);return $q->fetch()?:null;}
function cms_page_doc(array $page,bool $published=true): array {$json=$published?($page['published_document_json']??null):($page['draft_document_json']??null);if(!$json)$json=$page['draft_document_json']??'{}';$doc=json_decode((string)$json,true);return cms_page_document(is_array($doc)?$doc:[]);}
function cms_page_unique_slug(PDO $db,int $activityId,string $locale,string $slug,?int $exceptId=null): string {$slug=cms_page_slug($slug);if($slug==='')$slug='pagina';$base=$slug;$n=2;while(true){$sql='SELECT id FROM cms_pages WHERE activity_id=? AND locale=? AND slug=? AND status!="archived"';$args=[$activityId,$locale,$slug];if($exceptId){$sql.=' AND id!=?';$args[]=$exceptId;}$q=$db->prepare($sql);$q->execute($args);if(!$q->fetchColumn())return $slug;$slug=$base.'-'.$n++;}}
function cms_page_create(PDO $db,int $activityId,string $locale,string $title,string $slug='',?int $copyId=null): array {
    $locale=normalize_public_locale($locale)??PUBLIC_LOCALE_EN;$copy=$copyId?cms_page_by_id($db,$copyId):null;$doc=$copy?cms_page_doc($copy,false):cms_page_document(['theme'=>'auto','meta'=>['title'=>$title,'description'=>''],'html'=>'<section class="section" data-cms-section="intro" data-cms-section-name="Nova seção"><p class="section-label" data-cms-editable>01 / Nova página</p><div class="statement-grid"><h2 data-cms-editable>'.h($title).'</h2><div class="statement-copy"><p data-cms-editable>Edite este conteúdo diretamente na página.</p></div></div></section>']);$slug=cms_page_unique_slug($db,$activityId,$locale,$slug?:$title);$json=json_encode($doc,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$now=utc_now();$q=$db->prepare('SELECT COALESCE(MAX(sort_order),0)+1 FROM cms_pages WHERE activity_id=? AND locale=?');$q->execute([$activityId,$locale]);$order=(int)$q->fetchColumn();$insert=$db->prepare('INSERT INTO cms_pages(page_uuid,activity_id,locale,slug,title,nav_title,status,is_home,show_in_nav,sort_order,draft_document_json,published_document_json,draft_revision,published_revision,draft_updated_at,published_at,created_at,updated_at)VALUES(?,?,?,?,?,?,"active",0,1,?,?,NULL,1,NULL,?,NULL,?,?)');$insert->execute([cms_page_uuid(),$activityId,$locale,$slug,trim($title)?:'Nova página',trim($title)?:'Nova página',$order,$json,$now,$now,$now]);return cms_page_by_id($db,(int)$db->lastInsertId())??throw new RuntimeException('page_create_failed');
}
function cms_page_save(PDO $db,int $id,array $document,int $revision,array $settings=[]): array {
    $page=cms_page_by_id($db,$id)??throw new RuntimeException('page_not_found');$document=cms_page_document($document);$json=json_encode($document,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$locale=normalize_public_locale((string)($settings['locale']??$page['locale']))??$page['locale'];$slug=(int)$page['is_home']===1?'':cms_page_unique_slug($db,(int)$page['activity_id'],$locale,(string)($settings['slug']??$page['slug']),$id);$title=trim((string)($settings['title']??$page['title']))?:$page['title'];$nav=trim((string)($settings['nav_title']??$page['nav_title']))?:$title;$show=!empty($settings['show_in_nav'])?1:0;$new=$revision+1;$now=utc_now();$q=$db->prepare('UPDATE cms_pages SET locale=?,slug=?,title=?,nav_title=?,show_in_nav=?,draft_document_json=?,draft_revision=?,draft_updated_at=?,updated_at=? WHERE id=? AND draft_revision=?');$q->execute([$locale,$slug,$title,$nav,$show,$json,$new,$now,$now,$id,$revision]);if($q->rowCount()!==1)throw new RuntimeException('revision_conflict');return cms_page_by_id($db,$id)??throw new RuntimeException('page_not_found');
}
function cms_page_publish(PDO $db,int $id): array {$page=cms_page_by_id($db,$id)??throw new RuntimeException('page_not_found');$now=utc_now();$q=$db->prepare('UPDATE cms_pages SET published_document_json=draft_document_json,published_revision=draft_revision,published_at=?,updated_at=? WHERE id=?');$q->execute([$now,$now,$id]);return cms_page_by_id($db,$id)??throw new RuntimeException('page_not_found');}
function cms_page_set_home(PDO $db,int $id): array {$page=cms_page_by_id($db,$id)??throw new RuntimeException('page_not_found');$db->beginTransaction();try{$q=$db->prepare('UPDATE cms_pages SET is_home=0 WHERE activity_id=? AND locale=?');$q->execute([(int)$page['activity_id'],$page['locale']]);$q=$db->prepare("UPDATE cms_pages SET is_home=1,slug='',show_in_nav=1,updated_at=? WHERE id=?");$q->execute([utc_now(),$id]);$db->commit();return cms_page_by_id($db,$id)??throw new RuntimeException('page_not_found');}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}
function cms_page_archive(PDO $db,int $id): void {$page=cms_page_by_id($db,$id)??throw new RuntimeException('page_not_found');if((int)$page['is_home']===1)throw new RuntimeException('cannot_archive_home');$q=$db->prepare("UPDATE cms_pages SET status='archived',show_in_nav=0,updated_at=? WHERE id=?");$q->execute([utc_now(),$id]);}
function cms_nav_pages(PDO $db,int $activityId,string $locale): array {$q=$db->prepare("SELECT * FROM cms_pages WHERE activity_id=? AND locale=? AND status!='archived' AND show_in_nav=1 AND published_document_json IS NOT NULL ORDER BY sort_order,id");$q->execute([$activityId,$locale]);return $q->fetchAll();}
