<?php
declare(strict_types=1);

function course_domain_available(PDO $db): bool {return (bool)$db->query("SELECT 1 FROM sqlite_master WHERE type='table' AND name='courses'")->fetchColumn();}
function course_by_id(PDO $db,int $courseId): ?array {$q=$db->prepare("SELECT * FROM courses WHERE id=? AND status!='archived' LIMIT 1");$q->execute([$courseId]);return $q->fetch()?:null;}
function course_list(PDO $db,?int $activityId=null): array {$sql="SELECT c.*,p.title public_page_title,p.slug public_page_slug,f.title registration_form_title,f.form_key registration_form_key FROM courses c LEFT JOIN cms_pages p ON p.id=c.public_page_id LEFT JOIN cms_forms f ON f.id=c.registration_form_id WHERE c.status!='archived'";$args=[];if($activityId!==null){$sql.=' AND c.activity_id=?';$args[]=$activityId;}$sql.=' ORDER BY c.title COLLATE NOCASE,c.id';$q=$db->prepare($sql);$q->execute($args);return $q->fetchAll();}
function course_by_public_page(PDO $db,int $pageId): ?array {$q=$db->prepare("SELECT * FROM courses WHERE public_page_id=? AND status!='archived' LIMIT 1");$q->execute([$pageId]);return $q->fetch()?:null;}
function course_by_registration_form(PDO $db,int $formId): array {$q=$db->prepare("SELECT * FROM courses WHERE registration_form_id=? AND status!='archived' ORDER BY id");$q->execute([$formId]);return $q->fetchAll();}
function course_slug_unique(PDO $db,int $activityId,string $slug,int $ignoreId=0): string {$base=activity_slug($slug);if($base==='')$base='curso';$candidate=$base;$n=2;while(true){$q=$db->prepare('SELECT id FROM courses WHERE activity_id=? AND slug=?'.($ignoreId>0?' AND id!=?':''));$args=[$activityId,$candidate];if($ignoreId>0)$args[]=$ignoreId;$q->execute($args);if(!$q->fetchColumn())return $candidate;$candidate=$base.'-'.$n++;}}
function course_create_from_page(PDO $db,int $pageId,int $registrationFormId=0): array {
    $page=cms_page_by_id($db,$pageId)??throw new RuntimeException('Página do curso não encontrada.');if((string)$page['status']==='archived')throw new RuntimeException('A página do curso está arquivada.');if(course_by_public_page($db,$pageId))throw new RuntimeException('Esta página já está associada a um curso.');
    $activityId=(int)$page['activity_id'];$form=null;if($registrationFormId>0){$form=cms_form_by_id($db,$registrationFormId);if(!$form||(int)$form['activity_id']!==$activityId||(string)$form['status']==='archived'||cms_form_purpose($form)!=='enrollment')throw new RuntimeException('Escolha um formulário de inscrição válido deste site.');}
    $now=utc_now();$slug=course_slug_unique($db,$activityId,(string)$page['slug']);$db->prepare("INSERT INTO courses(course_uuid,activity_id,title,slug,status,public_page_id,registration_form_id,created_at,updated_at) VALUES(?,?,?,?, 'active',?,?,?,?)")->execute([student_uuid(),$activityId,trim((string)$page['title'])?:'Curso',$slug,$pageId,$form?(int)$form['id']:null,$now,$now]);return course_by_id($db,(int)$db->lastInsertId())??throw new RuntimeException('course_create_failed');
}
function course_update(PDO $db,int $courseId,array $input): array {
    $course=course_by_id($db,$courseId)??throw new RuntimeException('Curso não encontrado.');$activityId=(int)$course['activity_id'];$title=trim((string)($input['title']??$course['title']));if($title==='')throw new RuntimeException('Informe o nome do curso.');$slug=course_slug_unique($db,$activityId,(string)($input['slug']??$course['slug']),$courseId);
    $pageId=(int)($input['public_page_id']??$course['public_page_id']??0);$page=$pageId>0?cms_page_by_id($db,$pageId):null;if(!$page||(int)$page['activity_id']!==$activityId||(string)$page['status']==='archived')throw new RuntimeException('Página pública inválida.');$other=course_by_public_page($db,$pageId);if($other&&(int)$other['id']!==$courseId)throw new RuntimeException('Esta página já pertence a outro curso.');
    $formId=(int)($input['registration_form_id']??0);$form=$formId>0?cms_form_by_id($db,$formId):null;if($formId>0&&(!$form||(int)$form['activity_id']!==$activityId||(string)$form['status']==='archived'||cms_form_purpose($form)!=='enrollment'))throw new RuntimeException('Formulário de inscrição inválido.');
    $db->prepare('UPDATE courses SET title=?,slug=?,public_page_id=?,registration_form_id=?,updated_at=? WHERE id=?')->execute([$title,$slug,$pageId,$formId>0?$formId:null,utc_now(),$courseId]);return course_by_id($db,$courseId)??throw new RuntimeException('course_update_failed');
}
function course_registration_course_for_form(PDO $db,int $formId,int $pageId=0): ?array {
    $candidates=course_by_registration_form($db,$formId);if(count($candidates)===1)return $candidates[0];if(!$candidates||$pageId<1)return null;
    foreach($candidates as $candidate){$root=(int)($candidate['public_page_id']??0);if($root<1)continue;if($pageId===$root||in_array($pageId,cms_page_descendant_ids($db,$root),true))return $candidate;}
    return null;
}
function course_bind_submission(PDO $db,int $submissionId,int $formId,int $pageId): ?array {$course=course_registration_course_for_form($db,$formId,$pageId);if(!$course)return null;$db->prepare('UPDATE cms_form_submissions SET course_id=?,updated_at=? WHERE id=?')->execute([(int)$course['id'],utc_now(),$submissionId]);return $course;}

function course_cohorts_for_course(PDO $db,int $courseId,bool $includeArchived=false): array {$sql='SELECT * FROM course_cohorts WHERE course_id=?';if(!$includeArchived)$sql.=" AND status!='archived'";$sql.=' ORDER BY starts_at IS NULL,starts_at,id DESC';$q=$db->prepare($sql);$q->execute([$courseId]);return $q->fetchAll();}
function course_create_cohort_for_course(PDO $db,int $courseId,string $title,string $slug='',?string $startsAt=null,?string $endsAt=null): array {
    $course=course_by_id($db,$courseId)??throw new RuntimeException('Curso não encontrado.');$title=trim($title);if($title==='')throw new RuntimeException('Informe o nome da turma.');$base=course_cohort_slug($slug!==''?$slug:$title);$candidate=$base;$n=2;$check=$db->prepare('SELECT 1 FROM course_cohorts WHERE course_id=? AND slug=?');while(true){$check->execute([$courseId,$candidate]);if(!$check->fetchColumn())break;$candidate=$base.'-'.$n++;}
    $now=utc_now();$db->prepare("INSERT INTO course_cohorts(cohort_uuid,activity_id,workshop_page_id,course_id,title,slug,status,is_registration_default,starts_at,ends_at,created_at,updated_at) VALUES(?,?,?,?,?,?,'active',0,?,?,?,?)")->execute([student_uuid(),(int)$course['activity_id'],(int)($course['public_page_id']??0)?:null,$courseId,$title,$candidate,$startsAt?:null,$endsAt?:null,$now,$now]);$id=(int)$db->lastInsertId();course_sync_release_rows_for_course($db,$id,$courseId);return course_cohort_by_id($db,$id)??throw new RuntimeException('cohort_create_failed');
}
function course_lessons_for_course(PDO $db,int $courseId): array {$q=$db->prepare('SELECT * FROM course_lessons WHERE course_id=? ORDER BY sort_order,id');$q->execute([$courseId]);return $q->fetchAll();}
function course_add_lesson_for_course(PDO $db,int $courseId,string $title,string $key=''): array {
    $course=course_by_id($db,$courseId)??throw new RuntimeException('Curso não encontrado.');$title=trim($title);if($title==='')throw new RuntimeException('Informe o nome da aula.');$base=activity_slug($key!==''?$key:$title);if($base==='')$base='aula';$candidate=$base;$n=2;$check=$db->prepare('SELECT 1 FROM course_lessons WHERE course_id=? AND lesson_key=?');while(true){$check->execute([$courseId,$candidate]);if(!$check->fetchColumn())break;$candidate=$base.'-'.$n++;}$q=$db->prepare('SELECT COALESCE(MAX(sort_order),0)+1 FROM course_lessons WHERE course_id=?');$q->execute([$courseId]);$sort=(int)$q->fetchColumn();$now=utc_now();$db->prepare('INSERT INTO course_lessons(activity_id,workshop_page_id,course_id,lesson_key,title,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)')->execute([(int)$course['activity_id'],(int)($course['public_page_id']??0)?:null,$courseId,$candidate,$title,$sort,$now,$now]);$id=(int)$db->lastInsertId();foreach(course_cohorts_for_course($db,$courseId) as $cohort)$db->prepare('INSERT OR IGNORE INTO cohort_lesson_releases(cohort_id,lesson_id,released_at,created_at,updated_at) VALUES(?,?,NULL,?,?)')->execute([(int)$cohort['id'],$id,$now,$now]);$s=$db->prepare('SELECT * FROM course_lessons WHERE id=?');$s->execute([$id]);return $s->fetch()?:throw new RuntimeException('lesson_create_failed');
}
function course_sync_release_rows_for_course(PDO $db,int $cohortId,int $courseId): void {$now=utc_now();$q=$db->prepare('SELECT id FROM course_lessons WHERE course_id=?');$q->execute([$courseId]);$insert=$db->prepare('INSERT OR IGNORE INTO cohort_lesson_releases(cohort_id,lesson_id,released_at,created_at,updated_at) VALUES(?,?,NULL,?,?)');foreach($q->fetchAll(PDO::FETCH_COLUMN) as $lessonId)$insert->execute([$cohortId,(int)$lessonId,$now,$now]);}
function course_lesson_release_rows_for_course(PDO $db,int $cohortId,int $courseId): array {$cohort=course_cohort_by_id($db,$cohortId);if(!$cohort||(int)($cohort['course_id']??0)!==$courseId)throw new RuntimeException('Turma não pertence a este curso.');course_sync_release_rows_for_course($db,$cohortId,$courseId);$q=$db->prepare('SELECT l.*,r.released_at FROM course_lessons l JOIN cohort_lesson_releases r ON r.lesson_id=l.id AND r.cohort_id=? WHERE l.course_id=? ORDER BY l.sort_order,l.id');$q->execute([$cohortId,$courseId]);return $q->fetchAll();}
function course_set_lesson_release_for_course(PDO $db,int $courseId,int $cohortId,int $lessonId,string $mode,string $scheduled=''): ?string {$cohort=course_cohort_by_id($db,$cohortId);if(!$cohort||(int)($cohort['course_id']??0)!==$courseId)throw new RuntimeException('Turma inválida.');$q=$db->prepare('SELECT id FROM course_lessons WHERE id=? AND course_id=?');$q->execute([$lessonId,$courseId]);if(!$q->fetchColumn())throw new RuntimeException('Aula inválida.');$releasedAt=match($mode){'release'=>utc_now(),'block'=>null,'schedule'=>cms_access_local_to_utc($scheduled),default=>throw new RuntimeException('Ação de liberação inválida.')};if($mode==='schedule'&&$releasedAt===null)throw new RuntimeException('Informe data e hora válidas.');$now=utc_now();$db->prepare('INSERT INTO cohort_lesson_releases(cohort_id,lesson_id,released_at,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(cohort_id,lesson_id) DO UPDATE SET released_at=excluded.released_at,updated_at=excluded.updated_at')->execute([$cohortId,$lessonId,$releasedAt,$now,$now]);return $releasedAt;}

function course_material_pages(PDO $db,int $courseId): array {$q=$db->prepare("SELECT p.*,m.sort_order material_sort_order FROM course_material_pages m JOIN cms_pages p ON p.id=m.page_id WHERE m.course_id=? AND p.status!='archived' ORDER BY m.sort_order,p.sort_order,p.id");$q->execute([$courseId]);return $q->fetchAll();}
function course_material_courses_for_page(PDO $db,int $pageId): array {$q=$db->prepare("SELECT c.* FROM course_material_pages m JOIN courses c ON c.id=m.course_id WHERE m.page_id=? AND c.status!='archived' ORDER BY c.id");$q->execute([$pageId]);return $q->fetchAll();}
function course_material_page_is_associated(PDO $db,int $courseId,int $pageId): bool {$q=$db->prepare('SELECT 1 FROM course_material_pages WHERE course_id=? AND page_id=?');$q->execute([$courseId,$pageId]);return (bool)$q->fetchColumn();}
function course_material_add_page(PDO $db,int $courseId,int $pageId): void {$course=course_by_id($db,$courseId)??throw new RuntimeException('Curso não encontrado.');$page=cms_page_by_id($db,$pageId)??throw new RuntimeException('Página não encontrada.');if((int)$page['activity_id']!==(int)$course['activity_id']||(string)$page['status']==='archived')throw new RuntimeException('A página precisa pertencer ao mesmo site.');$q=$db->prepare('SELECT COALESCE(MAX(sort_order),0)+1 FROM course_material_pages WHERE course_id=?');$q->execute([$courseId]);$sort=(int)$q->fetchColumn();$now=utc_now();$db->prepare('INSERT INTO course_material_pages(course_id,page_id,sort_order,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(course_id,page_id) DO NOTHING')->execute([$courseId,$pageId,$sort,$now,$now]);}
function course_material_remove_page(PDO $db,int $courseId,int $pageId): void {$db->prepare('DELETE FROM course_material_sections WHERE course_id=? AND page_id=?')->execute([$courseId,$pageId]);$db->prepare('DELETE FROM course_material_pages WHERE course_id=? AND page_id=?')->execute([$courseId,$pageId]);}
function course_material_sections_from_page(PDO $db,int $pageId): array {$page=cms_page_by_id($db,$pageId)??throw new RuntimeException('Página não encontrada.');$document=cms_page_doc($page,false);$html=(string)($document['html']??'');if($html==='')return [];$previous=libxml_use_internal_errors(true);$dom=new DOMDocument('1.0','UTF-8');$dom->loadHTML('<?xml encoding="utf-8" ?><div id="course-material-root">'.$html.'</div>',LIBXML_HTML_NOIMPLIED|LIBXML_HTML_NODEFDTD);$xpath=new DOMXPath($dom);$out=[];foreach(iterator_to_array($xpath->query('//*[@data-cms-section]')?:[]) as $node){if(!$node instanceof DOMElement)continue;$key=trim($node->getAttribute('data-cms-section'));if($key===''||isset($out[$key]))continue;$out[$key]=trim($node->getAttribute('data-cms-section-name'))?:$key;}libxml_clear_errors();libxml_use_internal_errors($previous);return $out;}
function course_material_section_map(PDO $db,int $courseId,int $pageId): array {$q=$db->prepare('SELECT s.section_key,s.lesson_id,l.title,l.lesson_key FROM course_material_sections s JOIN course_lessons l ON l.id=s.lesson_id WHERE s.course_id=? AND s.page_id=? AND l.course_id=?');$q->execute([$courseId,$pageId,$courseId]);$out=[];foreach($q->fetchAll() as $row)$out[(string)$row['section_key']]=$row;return $out;}
function course_material_page_release_summary(PDO $db,int $courseId,int $cohortId,int $pageId,?array $releaseRows=null,?int $now=null): array {
    if(!course_material_page_is_associated($db,$courseId,$pageId))throw new RuntimeException('A página não está associada a este curso.');
    $sections=course_material_sections_from_page($db,$pageId);$map=course_material_section_map($db,$courseId,$pageId);
    if(!$map)return ['state'=>'available','label'=>'Disponível','released'=>0,'scheduled'=>0,'blocked'=>0,'unrestricted'=>count($sections)];
    if($releaseRows===null)$releaseRows=course_lesson_release_rows_for_course($db,$cohortId,$courseId);
    $lessonStates=[];foreach($releaseRows as $row)$lessonStates[(int)$row['id']]=function_exists('cms_access_lesson_release_state')?cms_access_lesson_release_state($row,$now):['state'=>((string)($row['released_at']??'')!==''?'released':'blocked')];
    $released=0;$scheduled=0;$blocked=0;$mapped=0;
    foreach($sections as $key=>$name){if(!isset($map[$key]))continue;$mapped++;$lessonId=(int)$map[$key]['lesson_id'];$state=(string)($lessonStates[$lessonId]['state']??'blocked');if($state==='released')$released++;elseif($state==='scheduled')$scheduled++;else $blocked++;}
    $unrestricted=max(0,count($sections)-$mapped);$restricted=$scheduled+$blocked;
    if($restricted===0)$state='available';elseif($released+$unrestricted>0)$state='partial';elseif($scheduled>0&&$blocked===0)$state='scheduled';else $state='blocked';
    $label=match($state){'available'=>'Disponível','partial'=>'Parcial','scheduled'=>'Agendado',default=>'Aguardando'};
    return ['state'=>$state,'label'=>$label,'released'=>$released,'scheduled'=>$scheduled,'blocked'=>$blocked,'unrestricted'=>$unrestricted];
}
function course_material_set_section_lesson(PDO $db,int $courseId,int $pageId,string $sectionKey,?int $lessonId): void {$sectionKey=trim($sectionKey);if($sectionKey==='')throw new RuntimeException('Seção inválida.');if(!course_material_page_is_associated($db,$courseId,$pageId))throw new RuntimeException('A página não está associada a este curso.');if($lessonId===null||$lessonId<1){$db->prepare('DELETE FROM course_material_sections WHERE course_id=? AND page_id=? AND section_key=?')->execute([$courseId,$pageId,$sectionKey]);return;}$q=$db->prepare('SELECT 1 FROM course_lessons WHERE id=? AND course_id=?');$q->execute([$lessonId,$courseId]);if(!$q->fetchColumn())throw new RuntimeException('A aula não pertence a este curso.');$sections=course_material_sections_from_page($db,$pageId);if(!isset($sections[$sectionKey]))throw new RuntimeException('A seção não existe mais na página.');$now=utc_now();$db->prepare('INSERT INTO course_material_sections(course_id,page_id,section_key,lesson_id,created_at,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(course_id,page_id,section_key) DO UPDATE SET lesson_id=excluded.lesson_id,updated_at=excluded.updated_at')->execute([$courseId,$pageId,$sectionKey,$lessonId,$now,$now]);}

function course_registration_assign_cohort(PDO $db,int $submissionId,int $courseId,int $cohortId): void {$course=course_by_id($db,$courseId)??throw new RuntimeException('Curso não encontrado.');$cohort=course_cohort_by_id($db,$cohortId);if(!$cohort||(int)($cohort['course_id']??0)!==$courseId||(string)$cohort['status']==='archived')throw new RuntimeException('Turma não pertence a este curso.');$q=$db->prepare("SELECT s.* FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE s.id=? AND s.course_id=? AND f.purpose='enrollment'");$q->execute([$submissionId,$courseId]);$row=$q->fetch()?:throw new RuntimeException('Inscrição não pertence a este curso.');$old=(int)($row['cohort_id']??0);$studentId=(int)($row['student_id']??0);$db->prepare('UPDATE cms_form_submissions SET cohort_id=?,updated_at=? WHERE id=?')->execute([$cohortId,utc_now(),$submissionId]);if($old>0&&$old!==$cohortId&&$studentId>0)$db->prepare("UPDATE course_enrollments SET status='disabled',updated_at=? WHERE student_id=? AND cohort_id=? AND source_submission_id=?")->execute([utc_now(),$studentId,$old,$submissionId]);if(function_exists('student_enrollment_reconcile_confirmed'))student_enrollment_reconcile_confirmed($db,(int)$course['activity_id']);}
function course_registration_unassign_cohort(PDO $db,int $submissionId,int $courseId): void {$q=$db->prepare('SELECT student_id,cohort_id FROM cms_form_submissions WHERE id=? AND course_id=?');$q->execute([$submissionId,$courseId]);$row=$q->fetch()?:throw new RuntimeException('Inscrição não encontrada.');$studentId=(int)($row['student_id']??0);$cohortId=(int)($row['cohort_id']??0);$db->prepare('UPDATE cms_form_submissions SET cohort_id=NULL,updated_at=? WHERE id=?')->execute([utc_now(),$submissionId]);if($studentId>0&&$cohortId>0)$db->prepare("UPDATE course_enrollments SET status='disabled',updated_at=? WHERE student_id=? AND cohort_id=? AND source_submission_id=?")->execute([utc_now(),$studentId,$cohortId,$submissionId]);}
function course_enrollment_for_student(PDO $db,int $studentId,int $courseId,string $cohortUuid=''): ?array {$sql="SELECT e.*,c.title cohort_title,c.cohort_uuid,c.activity_id,c.course_id,c.workshop_page_id,c.status cohort_status,cr.title course_title,cr.public_page_id FROM course_enrollments e JOIN course_cohorts c ON c.id=e.cohort_id JOIN courses cr ON cr.id=c.course_id WHERE e.student_id=? AND c.course_id=? AND e.status='active' AND c.status!='archived'";$args=[$studentId,$courseId];if($cohortUuid!==''){$sql.=' AND c.cohort_uuid=?';$args[]=$cohortUuid;}$sql.=' ORDER BY e.confirmed_at DESC,e.id DESC LIMIT 1';$q=$db->prepare($sql);$q->execute($args);return $q->fetch()?:null;}