<?php
declare(strict_types=1);

/** Canonical enrollment service.
 * student_users is the global identity.
 * Course membership is enrollment -> cohort -> course.
 * A confirmed registration may exist without a cohort and therefore without an enrollment.
 */
function student_enrollment_course_domain_available(PDO $db): bool {return function_exists('course_domain_available')&&course_domain_available($db);}
function student_enrollment_payload_identity(array $values): array {$email=student_normalize_email((string)($values['email']??''));$cpfHash=student_account_cpf_lookup_hash((string)($values['cpf']??''));return [$email,$cpfHash];}
function student_enrollment_validate_authenticated_identity(PDO $db,array $values,array $student): int {$studentId=(int)($student['id']??0);if($studentId<1)throw new RuntimeException('student_identity_invalid');$q=$db->prepare("SELECT * FROM student_users WHERE id=? AND status='active' LIMIT 1");$q->execute([$studentId]);$account=$q->fetch()?:throw new RuntimeException('student_identity_invalid');[$email,$cpfHash]=student_enrollment_payload_identity($values);if($email!==''||$cpfHash!==''){$candidate=student_account_find_identity($db,$email,$cpfHash);if($candidate&&(int)$candidate['id']!==$studentId)throw new RuntimeException('student_identity_conflict');}return (int)$account['id'];}
function student_enrollment_bind_authenticated_submission(PDO $db,int $submissionId,array $form,array $values,array $student): int {if(cms_form_purpose($form)!=='enrollment')return 0;$studentId=student_enrollment_validate_authenticated_identity($db,$values,$student);$q=$db->prepare("SELECT s.id,s.form_id,s.activity_id,f.purpose FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE s.id=? LIMIT 1");$q->execute([$submissionId]);$submission=$q->fetch()?:throw new RuntimeException('submission_not_found');if((int)$submission['form_id']!==(int)$form['id']||(int)$submission['activity_id']!==(int)$form['activity_id']||cms_form_purpose(['purpose'=>$submission['purpose']])!=='enrollment')throw new RuntimeException('submission_identity_scope_invalid');$db->prepare('UPDATE cms_form_submissions SET student_id=?,updated_at=? WHERE id=?')->execute([$studentId,utc_now(),$submissionId]);return $studentId;}
function student_enrollment_student_from_submission(PDO $db,array $submission): int {$payload=json_decode((string)($submission['payload_json']??''),true);if(!is_array($payload))throw new RuntimeException('submission_payload_invalid');$boundStudentId=(int)($submission['student_id']??0);if($boundStudentId<1)return student_account_upsert_from_submission($db,$submission);$q=$db->prepare("SELECT * FROM student_users WHERE id=? AND status='active' LIMIT 1");$q->execute([$boundStudentId]);$student=$q->fetch()?:throw new RuntimeException('bound_student_not_found');student_enrollment_validate_authenticated_identity($db,$payload,$student);student_account_merge_profile_from_payload($db,$boundStudentId,$payload);return $boundStudentId;}
function student_enrollment_submission_course(PDO $db,array $submission): ?array {if(!student_enrollment_course_domain_available($db))return null;$courseId=(int)($submission['course_id']??0);if($courseId>0)return course_by_id($db,$courseId);$course=course_registration_course_for_form($db,(int)($submission['form_id']??0),(int)($submission['page_id']??0));if($course)$db->prepare('UPDATE cms_form_submissions SET course_id=?,updated_at=? WHERE id=?')->execute([(int)$course['id'],utc_now(),(int)$submission['id']]);return $course;}
function student_enrollment_explicit_cohort(PDO $db,array $submission,?array $course): ?array {$cohortId=(int)($submission['cohort_id']??0);if($cohortId<1){if(!$course){$default=course_default_cohort($db,(int)$submission['activity_id'],false);return $default?:null;}return null;}$cohort=course_cohort_by_id($db,$cohortId);if(!$cohort||(string)$cohort['status']==='archived')throw new RuntimeException('assigned_cohort_invalid');if($course&&(int)($cohort['course_id']??0)!==(int)$course['id'])throw new RuntimeException('assigned_cohort_course_mismatch');if(!$course&&(int)$cohort['activity_id']!==(int)$submission['activity_id'])throw new RuntimeException('assigned_cohort_activity_mismatch');return $cohort;}
function student_enrollment_reconcile_confirmed(PDO $db,?int $activityId=null): array {
    $sql="SELECT s.*,f.form_key,f.purpose FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE f.purpose='enrollment'";$args=[];if($activityId!==null){$sql.=' AND s.activity_id=?';$args[]=$activityId;}$sql.=' ORDER BY s.id';$q=$db->prepare($sql);$q->execute($args);$processed=0;$pendingAssignment=0;$disabled=0;$errors=[];
    foreach($q->fetchAll() as $row){try{
        if(student_account_submission_confirmed($row)){
            $course=student_enrollment_submission_course($db,$row);$studentId=student_enrollment_student_from_submission($db,$row);$cohort=student_enrollment_explicit_cohort($db,$row,$course);$now=utc_now();
            if(student_enrollment_course_domain_available($db))$db->prepare('UPDATE cms_form_submissions SET student_id=?,course_id=COALESCE(course_id,?),updated_at=? WHERE id=?')->execute([$studentId,$course?(int)$course['id']:null,$now,(int)$row['id']]);else $db->prepare('UPDATE cms_form_submissions SET student_id=?,updated_at=? WHERE id=?')->execute([$studentId,$now,(int)$row['id']]);
            if(!$cohort){$pendingAssignment++;continue;}
            $cohortId=(int)$cohort['id'];$db->prepare("INSERT INTO course_enrollments(enrollment_uuid,student_id,cohort_id,source_submission_id,status,confirmed_at,created_at,updated_at) VALUES(?,?,?,?, 'active',?,?,?) ON CONFLICT(student_id,cohort_id) DO UPDATE SET source_submission_id=excluded.source_submission_id,status='active',confirmed_at=excluded.confirmed_at,updated_at=excluded.updated_at")->execute([student_uuid(),$studentId,$cohortId,(int)$row['id'],(string)($row['payment_confirmed_at']?:$row['updated_at']?:$now),$now,$now]);if((int)($row['cohort_id']??0)<1&&!$course)$db->prepare('UPDATE cms_form_submissions SET cohort_id=?,updated_at=? WHERE id=?')->execute([$cohortId,$now,(int)$row['id']]);$processed++;
        }elseif(!empty($row['student_id'])&&!empty($row['cohort_id'])){$db->prepare("UPDATE course_enrollments SET status='disabled',updated_at=? WHERE student_id=? AND cohort_id=? AND source_submission_id=?")->execute([utc_now(),(int)$row['student_id'],(int)$row['cohort_id'],(int)$row['id']]);$disabled++;}
    }catch(Throwable $e){$errors[]=['submission_id'=>(int)$row['id'],'error'=>$e->getMessage()];error_log('Student enrollment reconciliation failed for submission '.(int)$row['id'].': '.$e->getMessage());}}
    return ['processed'=>$processed,'pending_assignment'=>$pendingAssignment,'disabled'=>$disabled,'errors'=>$errors];
}
function student_enrollment_install_reconciliation_hook(): void {$script=str_replace('\\','/',(string)($_SERVER['SCRIPT_NAME']??$_SERVER['PHP_SELF']??''));if(($_SERVER['REQUEST_METHOD']??'GET')!=='POST'||(!str_ends_with($script,'/admin/submissions.php')&&!str_ends_with($script,'/admin/registrations.php')))return;register_shutdown_function(static function(): void {try{student_enrollment_reconcile_confirmed(database());}catch(Throwable $e){error_log('Student enrollment reconciliation hook failed: '.$e->getMessage());}});}

function student_enrollment_list(PDO $db,int $studentId): array {
    $hasCourse=student_enrollment_course_domain_available($db);$courseSelect=$hasCourse?'c.course_id,cr.title canonical_course_title,cr.public_page_id,':'NULL course_id,NULL canonical_course_title,NULL public_page_id,';$courseJoin=$hasCourse?' LEFT JOIN courses cr ON cr.id=c.course_id ':'';$hasWorkshop=function_exists('workshop_course_scope_available')&&workshop_course_scope_available($db);$workshopSelect=$hasWorkshop?'c.workshop_page_id,wp.title workshop_title,wp.slug workshop_slug,wp.locale workshop_locale,':'NULL workshop_page_id,NULL workshop_title,NULL workshop_slug,NULL workshop_locale,';$workshopJoin=$hasWorkshop?' LEFT JOIN cms_pages wp ON wp.id=c.workshop_page_id ':'';
    $sql="SELECT e.*,c.title cohort_title,c.cohort_uuid,c.activity_id,c.status cohort_status,$courseSelect$workshopSelect a.public_title,a.admin_name,a.slug activity_slug,a.is_root FROM course_enrollments e JOIN course_cohorts c ON c.id=e.cohort_id JOIN activities a ON a.id=c.activity_id $courseJoin $workshopJoin WHERE e.student_id=? AND e.status='active' AND c.status!='archived' ORDER BY e.confirmed_at DESC,e.id DESC";$q=$db->prepare($sql);$q->execute([$studentId]);$rows=$q->fetchAll();foreach($rows as &$row)$row['course_title']=trim((string)($row['canonical_course_title']??''))?:trim((string)($row['workshop_title']??''))?:((string)($row['public_title']??''));unset($row);return $rows;
}
function student_enrollment_pages_for_enrollment(PDO $db,array $enrollment): array {$courseId=(int)($enrollment['course_id']??0);if($courseId>0&&student_enrollment_course_domain_available($db))return array_values(array_filter(course_material_pages($db,$courseId),static fn(array $page): bool=>!empty($page['published_document_json'])));$workshopId=(int)($enrollment['workshop_page_id']??0);if($workshopId>0&&function_exists('cms_page_workshop_ids')){$ids=cms_page_workshop_ids($db,$workshopId);if(!$ids)return [];$placeholders=implode(',',array_fill(0,count($ids),'?'));$sql="SELECT * FROM cms_pages WHERE id IN ($placeholders) AND (access_level IN ('activity','enrolled') OR (access_level='cohort' AND access_cohort_id=?)) AND status!='archived' AND published_document_json IS NOT NULL ORDER BY locale,sort_order,id";$q=$db->prepare($sql);$q->execute([...$ids,(int)$enrollment['cohort_id']]);return $q->fetchAll();}$q=$db->prepare("SELECT * FROM cms_pages WHERE activity_id=? AND (access_level IN ('activity','enrolled') OR (access_level='cohort' AND access_cohort_id=?)) AND status!='archived' AND published_document_json IS NOT NULL ORDER BY locale,sort_order,id");$q->execute([(int)$enrollment['activity_id'],(int)$enrollment['cohort_id']]);return $q->fetchAll();}
function student_enrollment_dashboard_context(array $enrollments,string $cohortUuid=''): ?array {$cohortUuid=trim($cohortUuid);if($cohortUuid!==''){foreach($enrollments as $enrollment)if((string)($enrollment['cohort_uuid']??'')===$cohortUuid)return $enrollment;return null;}$values=array_values($enrollments);return count($values)===1?$values[0]:null;}
function student_enrollment_cohort_status_label(string $status): string {return match($status){'active'=>'Turma ativa','closed'=>'Turma encerrada',default=>'Estado da turma indisponível'};}
function student_enrollment_material_context(PDO $db,array $student,array $page,string $cohortUuid=''): ?array {
    $studentId=(int)($student['id']??0);if($studentId<1)return null;
    if(student_enrollment_course_domain_available($db)){$courses=course_material_courses_for_page($db,(int)$page['id']);$matches=[];foreach($courses as $course){$context=course_enrollment_for_student($db,$studentId,(int)$course['id'],trim($cohortUuid));if($context){$context['material_page_id']=(int)$page['id'];$matches[]=$context;}}if(count($matches)===1)return $matches[0];if(count($matches)>1&&trim($cohortUuid)!=='')return $matches[0];if($courses)return null;}
    $access=(string)($page['access_level']??'public');if(!in_array($access,['activity','enrolled','cohort'],true))return null;$activityId=(int)($page['activity_id']??0);if($activityId<1)return null;if($access==='cohort'){$cohortId=(int)($page['access_cohort_id']??0);if($cohortId<1)return null;$courseColumn=student_enrollment_course_domain_available($db)?',c.course_id':'';$workshopColumn=(function_exists('workshop_course_scope_available')&&workshop_course_scope_available($db))?',c.workshop_page_id':'';$q=$db->prepare("SELECT e.*,c.title cohort_title,c.cohort_uuid,c.activity_id$courseColumn$workshopColumn,c.status cohort_status FROM course_enrollments e JOIN course_cohorts c ON c.id=e.cohort_id WHERE e.student_id=? AND e.cohort_id=? AND c.activity_id=? AND e.status='active' AND c.status!='archived' ORDER BY e.confirmed_at DESC,e.id DESC LIMIT 1");$q->execute([$studentId,$cohortId,$activityId]);$row=$q->fetch()?:null;if($row)$row['material_page_id']=(int)$page['id'];return $row;}
    if(function_exists('cms_page_workshop_root_id')&&function_exists('workshop_course_scope_available')&&workshop_course_scope_available($db)){$workshopId=cms_page_workshop_root_id($db,$page);if($workshopId>0){$context=workshop_course_enrollment_for_student($db,$studentId,$workshopId,trim($cohortUuid));if($context){$context['material_page_id']=(int)$page['id'];return $context;}}}
    $context=student_account_enrollment_for_activity($db,$studentId,$activityId,trim($cohortUuid));if($context)$context['material_page_id']=(int)$page['id'];return $context;
}
function student_enrollment_owned_tests_context(array $tests,array $enrollment): array {$cohortId=(int)($enrollment['cohort_id']??0);if($cohortId<1)return [];return array_values(array_filter($tests,static fn(array $test): bool=>(int)($test['cohort_id']??0)===$cohortId));}
function student_enrollment_shared_tests_context(array $tests,array $enrollment): array {$cohortId=(int)($enrollment['cohort_id']??0);$activityId=(int)($enrollment['activity_id']??0);$courseId=(int)($enrollment['course_id']??0);$workshopId=(int)($enrollment['workshop_page_id']??0);if($cohortId<1||$activityId<1)return [];return array_values(array_filter($tests,static function(array $test) use($cohortId,$activityId,$courseId,$workshopId): bool {$testCourseId=(int)($test['course_id']??0);if($courseId>0&&$testCourseId>0&&$testCourseId!==$courseId)return false;$testWorkshopId=(int)($test['workshop_page_id']??0);if($courseId===0&&$workshopId>0&&$testWorkshopId>0&&$testWorkshopId!==$workshopId)return false;if($courseId===0&&$workshopId===0&&(int)($test['activity_id']??0)!==$activityId)return false;$visibility=(string)($test['visibility']??'private');if($visibility==='course')return true;return $visibility==='cohort'&&(int)($test['cohort_id']??0)===$cohortId;}));}
function student_enrollment_owned_test_navigation_context(array $enrollments,array $test,string $cohortUuid=''): ?array {$testCohortId=(int)($test['cohort_id']??0);if($testCohortId<1)return null;$match=null;foreach($enrollments as $enrollment){if((int)($enrollment['cohort_id']??0)===$testCohortId){$match=$enrollment;break;}}if(!$match)return null;$cohortUuid=trim($cohortUuid);if($cohortUuid!==''&&(string)($match['cohort_uuid']??'')!==$cohortUuid)return null;return $match;}
function student_enrollment_shared_test_navigation_context(array $enrollments,array $test,string $cohortUuid=''): ?array {$activityId=(int)($test['activity_id']??0);$testCohortId=(int)($test['cohort_id']??0);$testCourseId=(int)($test['course_id']??0);$testWorkshopId=(int)($test['workshop_page_id']??0);$visibility=(string)($test['visibility']??'private');if($activityId<1||$testCohortId<1||!in_array($visibility,['cohort','course'],true))return null;$eligible=[];foreach($enrollments as $enrollment){if($testCourseId>0&&(int)($enrollment['course_id']??0)!==$testCourseId)continue;if($testCourseId===0&&$testWorkshopId>0&&(int)($enrollment['workshop_page_id']??0)!==$testWorkshopId)continue;if($testCourseId===0&&$testWorkshopId===0&&(int)($enrollment['activity_id']??0)!==$activityId)continue;if($visibility==='cohort'&&(int)($enrollment['cohort_id']??0)!==$testCohortId)continue;$eligible[]=$enrollment;}$cohortUuid=trim($cohortUuid);if($cohortUuid!==''){foreach($eligible as $enrollment)if((string)($enrollment['cohort_uuid']??'')===$cohortUuid)return $enrollment;return null;}return count($eligible)===1?$eligible[0]:null;}
