<?php
declare(strict_types=1);

const STUDENT_PRIVACY_NOTICE_VERSION='2026-09-23';
const STUDENT_ACTIVATION_TIMEOUT_SECONDS=900;
const STUDENT_MEDIA_URL_TTL_SECONDS=600;

function student_account_normalize_cpf(string $cpf): string { return preg_replace('/\D+/','',$cpf)??''; }
function student_account_cpf_lookup_hash(string $cpf): string {
    $digits=student_account_normalize_cpf($cpf);if(strlen($digits)!==11)return '';
    return hash_hmac('sha256','student-cpf|'.$digits,(string)app_config()['app_secret']);
}
function student_account_crypto_key(): string { return hash('sha256','student-profile-cpf|'.(string)app_config()['app_secret'],true); }
function student_account_encrypt_cpf(string $cpf): string {
    $digits=student_account_normalize_cpf($cpf);if(strlen($digits)!==11||!function_exists('openssl_encrypt'))return '';
    $iv=random_bytes(12);$tag='';$cipher=openssl_encrypt($digits,'aes-256-gcm',student_account_crypto_key(),OPENSSL_RAW_DATA,$iv,$tag,'student-profile');
    return is_string($cipher)?base64_encode($iv.$tag.$cipher):'';
}
function student_account_decrypt_cpf(string $encoded): string {
    if($encoded===''||!function_exists('openssl_decrypt'))return '';$raw=base64_decode($encoded,true);if(!is_string($raw)||strlen($raw)<29)return '';
    $iv=substr($raw,0,12);$tag=substr($raw,12,16);$cipher=substr($raw,28);$plain=openssl_decrypt($cipher,'aes-256-gcm',student_account_crypto_key(),OPENSSL_RAW_DATA,$iv,$tag,'student-profile');
    return is_string($plain)&&strlen($plain)===11?$plain:'';
}
function student_account_random_unusable_hash(): string { return password_hash(bin2hex(random_bytes(32)),PASSWORD_DEFAULT)?:throw new RuntimeException('password_hash_failed'); }
function student_account_start_session(array $user): void {
    session_regenerate_id(true);$now=time();$_SESSION['student']=['id'=>(int)$user['id'],'email'=>(string)$user['email'],'name'=>(string)$user['name'],'issued_at'=>$now,'last_activity'=>$now];unset($_SESSION['student_activation']);
}
function student_account_current(PDO $db): ?array { return current_student($db); }
function student_account_has_any_enrollment(PDO $db,int $studentId): bool {
    $q=$db->prepare("SELECT 1 FROM course_enrollments e JOIN course_cohorts c ON c.id=e.cohort_id WHERE e.student_id=? AND e.status='active' AND c.status!='archived' LIMIT 1");$q->execute([$studentId]);return (bool)$q->fetchColumn();
}
function student_account_has_activity(PDO $db,int $studentId,int $activityId): bool {
    $q=$db->prepare("SELECT 1 FROM course_enrollments e JOIN course_cohorts c ON c.id=e.cohort_id WHERE e.student_id=? AND c.activity_id=? AND e.status='active' AND c.status!='archived' LIMIT 1");$q->execute([$studentId,$activityId]);return (bool)$q->fetchColumn();
}

function course_cohort_slug(string $value): string { return activity_slug($value)!==''?activity_slug($value):'turma-'.substr(bin2hex(random_bytes(4)),0,8); }
function course_default_cohort(PDO $db,int $activityId,bool $create=true): ?array {
    $q=$db->prepare("SELECT * FROM course_cohorts WHERE activity_id=? AND is_registration_default=1 AND status!='archived' ORDER BY id DESC LIMIT 1");$q->execute([$activityId]);$row=$q->fetch()?:null;if($row||!$create)return $row;
    $now=utc_now();$slug='turma-atual';$n=2;while(true){$check=$db->prepare('SELECT 1 FROM course_cohorts WHERE activity_id=? AND slug=?');$check->execute([$activityId,$slug]);if(!$check->fetchColumn())break;$slug='turma-atual-'.$n++;}
    $db->prepare("INSERT INTO course_cohorts(cohort_uuid,activity_id,title,slug,status,is_registration_default,created_at,updated_at) VALUES(?,?,?,?, 'active',1,?,?)")->execute([student_uuid(),$activityId,'Turma atual',$slug,$now,$now]);
    return course_cohort_by_id($db,(int)$db->lastInsertId());
}
function course_cohort_by_id(PDO $db,int $id): ?array {$q=$db->prepare('SELECT * FROM course_cohorts WHERE id=?');$q->execute([$id]);return $q->fetch()?:null;}
function course_cohorts(PDO $db,int $activityId): array {$q=$db->prepare("SELECT * FROM course_cohorts WHERE activity_id=? AND status!='archived' ORDER BY is_registration_default DESC,id DESC");$q->execute([$activityId]);return $q->fetchAll();}
function course_create_cohort(PDO $db,int $activityId,string $title,string $slug='',bool $makeDefault=false): array {
    $title=trim($title);if($title==='')throw new RuntimeException('Informe o nome da turma.');$slug=course_cohort_slug($slug!==''?$slug:$title);$now=utc_now();
    $db->beginTransaction();try{if($makeDefault)$db->prepare('UPDATE course_cohorts SET is_registration_default=0,updated_at=? WHERE activity_id=?')->execute([$now,$activityId]);$db->prepare("INSERT INTO course_cohorts(cohort_uuid,activity_id,title,slug,status,is_registration_default,created_at,updated_at) VALUES(?,?,?,?, 'active',?,?,?)")->execute([student_uuid(),$activityId,$title,$slug,$makeDefault?1:0,$now,$now]);$id=(int)$db->lastInsertId();if(!$makeDefault&&!course_default_cohort($db,$activityId,false))$db->prepare('UPDATE course_cohorts SET is_registration_default=1 WHERE id=?')->execute([$id]);course_sync_release_rows($db,$id,$activityId);$db->commit();return course_cohort_by_id($db,$id)??throw new RuntimeException('cohort_create_failed');}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
}
function course_set_default_cohort(PDO $db,int $activityId,int $cohortId): void {
    $cohort=course_cohort_by_id($db,$cohortId);if(!$cohort||(int)$cohort['activity_id']!==$activityId||$cohort['status']==='archived')throw new RuntimeException('Turma inválida.');$now=utc_now();$db->beginTransaction();try{$db->prepare('UPDATE course_cohorts SET is_registration_default=0,updated_at=? WHERE activity_id=?')->execute([$now,$activityId]);$db->prepare('UPDATE course_cohorts SET is_registration_default=1,status=CASE WHEN status="archived" THEN "active" ELSE status END,updated_at=? WHERE id=?')->execute([$now,$cohortId]);$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
}
function course_set_cohort_status(PDO $db,int $activityId,int $cohortId,string $status): void {if(!in_array($status,['active','closed','archived'],true))throw new RuntimeException('Estado inválido.');$db->prepare('UPDATE course_cohorts SET status=?,is_registration_default=CASE WHEN ?="archived" THEN 0 ELSE is_registration_default END,updated_at=? WHERE id=? AND activity_id=?')->execute([$status,$status,utc_now(),$cohortId,$activityId]);if($status==='archived'&&!course_default_cohort($db,$activityId,false))course_default_cohort($db,$activityId,true);}

function course_lessons(PDO $db,int $activityId): array {$q=$db->prepare('SELECT * FROM course_lessons WHERE activity_id=? ORDER BY sort_order,id');$q->execute([$activityId]);return $q->fetchAll();}
function course_add_lesson(PDO $db,int $activityId,string $title,string $key=''): array {
    $title=trim($title);if($title==='')throw new RuntimeException('Informe o nome da aula.');$key=activity_slug($key!==''?$key:$title);if($key==='')$key='aula-'.substr(bin2hex(random_bytes(4)),0,8);$q=$db->prepare('SELECT COALESCE(MAX(sort_order),0)+1 FROM course_lessons WHERE activity_id=?');$q->execute([$activityId]);$sort=(int)$q->fetchColumn();$now=utc_now();$db->prepare('INSERT INTO course_lessons(activity_id,lesson_key,title,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?)')->execute([$activityId,$key,$title,$sort,$now,$now]);$id=(int)$db->lastInsertId();foreach(course_cohorts($db,$activityId) as $cohort)$db->prepare('INSERT OR IGNORE INTO cohort_lesson_releases(cohort_id,lesson_id,released_at,created_at,updated_at) VALUES(?,?,NULL,?,?)')->execute([(int)$cohort['id'],$id,$now,$now]);$s=$db->prepare('SELECT * FROM course_lessons WHERE id=?');$s->execute([$id]);return $s->fetch();
}
function course_sync_release_rows(PDO $db,int $cohortId,int $activityId): void {$now=utc_now();$q=$db->prepare('SELECT id FROM course_lessons WHERE activity_id=?');$q->execute([$activityId]);$insert=$db->prepare('INSERT OR IGNORE INTO cohort_lesson_releases(cohort_id,lesson_id,released_at,created_at,updated_at) VALUES(?,?,NULL,?,?)');foreach($q->fetchAll(PDO::FETCH_COLUMN) as $id)$insert->execute([$cohortId,(int)$id,$now,$now]);}
function course_lesson_release_rows(PDO $db,int $cohortId,int $activityId): array {course_sync_release_rows($db,$cohortId,$activityId);$q=$db->prepare('SELECT l.*,r.released_at FROM course_lessons l JOIN cohort_lesson_releases r ON r.lesson_id=l.id AND r.cohort_id=? WHERE l.activity_id=? ORDER BY l.sort_order,l.id');$q->execute([$cohortId,$activityId]);return $q->fetchAll();}
function course_set_lesson_release(PDO $db,int $cohortId,int $lessonId,bool $released): void {$cohort=course_cohort_by_id($db,$cohortId);if(!$cohort)throw new RuntimeException('Turma inválida.');$q=$db->prepare('SELECT 1 FROM course_lessons WHERE id=? AND activity_id=?');$q->execute([$lessonId,(int)$cohort['activity_id']]);if(!$q->fetchColumn())throw new RuntimeException('Aula inválida.');$now=utc_now();$db->prepare('INSERT INTO cohort_lesson_releases(cohort_id,lesson_id,released_at,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(cohort_id,lesson_id) DO UPDATE SET released_at=excluded.released_at,updated_at=excluded.updated_at')->execute([$cohortId,$lessonId,$released?$now:null,$now,$now]);}

function student_account_profile(PDO $db,int $studentId): array {
    $q=$db->prepare('SELECT u.id,u.user_uuid,u.name,u.email,u.status,u.activated_at,u.privacy_ack_at,u.privacy_notice_version,p.cpf_ciphertext,p.cpf_last4,p.phone,p.instagram,p.address,p.city_state,p.postal_code FROM student_users u LEFT JOIN student_profiles p ON p.student_id=u.id WHERE u.id=?');$q->execute([$studentId]);$row=$q->fetch()?:throw new RuntimeException('student_not_found');$row['cpf']=student_account_decrypt_cpf((string)($row['cpf_ciphertext']??''));return $row;
}
function student_account_profile_values(PDO $db,int $studentId): array {$p=student_account_profile($db,$studentId);return ['name'=>(string)$p['name'],'email'=>(string)$p['email'],'cpf'=>(string)$p['cpf'],'phone'=>(string)($p['phone']??''),'instagram'=>(string)($p['instagram']??''),'address'=>(string)($p['address']??''),'city_state'=>(string)($p['city_state']??''),'postal_code'=>(string)($p['postal_code']??'')];}
function student_account_update_profile(PDO $db,int $studentId,array $input): void {
    $name=trim((string)($input['name']??''));$email=student_normalize_email((string)($input['email']??''));$cpf=student_account_normalize_cpf((string)($input['cpf']??''));if($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($cpf)!==11)throw new RuntimeException('Revise nome, e-mail e CPF.');$hash=student_account_cpf_lookup_hash($cpf);$now=utc_now();
    $emailCheck=$db->prepare('SELECT id FROM student_users WHERE email=? AND id!=?');$emailCheck->execute([$email,$studentId]);if($emailCheck->fetchColumn())throw new RuntimeException('Este e-mail já pertence a outra conta.');$cpfCheck=$db->prepare('SELECT student_id FROM student_profiles WHERE cpf_lookup_hash=? AND student_id!=?');$cpfCheck->execute([$hash,$studentId]);if($cpfCheck->fetchColumn())throw new RuntimeException('Este CPF já pertence a outra conta.');
    $db->beginTransaction();try{$db->prepare('UPDATE student_users SET name=?,email=?,updated_at=? WHERE id=?')->execute([$name,$email,$now,$studentId]);$db->prepare('INSERT INTO student_profiles(student_id,cpf_lookup_hash,cpf_ciphertext,cpf_last4,phone,instagram,address,city_state,postal_code,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(student_id) DO UPDATE SET cpf_lookup_hash=excluded.cpf_lookup_hash,cpf_ciphertext=excluded.cpf_ciphertext,cpf_last4=excluded.cpf_last4,phone=excluded.phone,instagram=excluded.instagram,address=excluded.address,city_state=excluded.city_state,postal_code=excluded.postal_code,updated_at=excluded.updated_at')->execute([$studentId,$hash,student_account_encrypt_cpf($cpf),substr($cpf,-4),trim((string)($input['phone']??'')),trim((string)($input['instagram']??'')),trim((string)($input['address']??'')),trim((string)($input['city_state']??'')),trim((string)($input['postal_code']??'')),$now,$now]);$db->commit();if(isset($_SESSION['student'])&&(int)($_SESSION['student']['id']??0)===$studentId){$_SESSION['student']['name']=$name;$_SESSION['student']['email']=$email;}}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
}
function student_account_merge_profile_from_payload(PDO $db,int $studentId,array $payload): void {
    $existing=student_account_profile($db,$studentId);$input=[];foreach(['name','email','cpf','phone','instagram','address','city_state','postal_code'] as $key)$input[$key]=trim((string)($payload[$key]??($existing[$key]??'')));if(student_account_normalize_cpf((string)$input['cpf'])==='')$input['cpf']=student_account_decrypt_cpf((string)($existing['cpf_ciphertext']??''));student_account_update_profile($db,$studentId,$input);
}
function student_account_find_identity(PDO $db,string $email,string $cpfHash): ?array {
    $byCpf=null;$byEmail=null;if($cpfHash!==''){$q=$db->prepare('SELECT u.* FROM student_users u JOIN student_profiles p ON p.student_id=u.id WHERE p.cpf_lookup_hash=? LIMIT 1');$q->execute([$cpfHash]);$byCpf=$q->fetch()?:null;}$q=$db->prepare('SELECT * FROM student_users WHERE email=? LIMIT 1');$q->execute([$email]);$byEmail=$q->fetch()?:null;if($byCpf&&$byEmail&&(int)$byCpf['id']!==(int)$byEmail['id'])throw new RuntimeException('student_identity_conflict');return $byCpf?:$byEmail;
}
function student_account_upsert_from_submission(PDO $db,array $submission): int {
    $payload=json_decode((string)($submission['payload_json']??''),true);if(!is_array($payload))throw new RuntimeException('submission_payload_invalid');$name=trim((string)($payload['name']??''));$email=student_normalize_email((string)($payload['email']??''));$cpf=student_account_normalize_cpf((string)($payload['cpf']??''));if($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($cpf)!==11)throw new RuntimeException('confirmed_registration_missing_identity');$hash=student_account_cpf_lookup_hash($cpf);$user=student_account_find_identity($db,$email,$hash);$now=utc_now();
    if(!$user){$db->prepare("INSERT INTO student_users(user_uuid,name,email,password_hash,status,must_change_password,last_login_at,created_at,updated_at,activated_at,privacy_ack_at,privacy_notice_version) VALUES(?,?,?,?, 'active',1,NULL,?,?,NULL,NULL,'')")->execute([student_uuid(),$name,$email,student_account_random_unusable_hash(),$now,$now]);$studentId=(int)$db->lastInsertId();$db->prepare('INSERT INTO student_profiles(student_id,cpf_lookup_hash,cpf_ciphertext,cpf_last4,phone,instagram,address,city_state,postal_code,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute([$studentId,$hash,student_account_encrypt_cpf($cpf),substr($cpf,-4),trim((string)($payload['phone']??'')),trim((string)($payload['instagram']??'')),trim((string)($payload['address']??'')),trim((string)($payload['city_state']??'')),trim((string)($payload['postal_code']??'')),$now,$now]);}
    else{$studentId=(int)$user['id'];student_account_merge_profile_from_payload($db,$studentId,$payload);$db->prepare("UPDATE student_users SET status='active',updated_at=? WHERE id=?")->execute([$now,$studentId]);}
    return $studentId;
}
function student_account_submission_confirmed(array $row): bool {return ($row['status']??'')!=='archived'&&(($row['status']??'')==='converted'||($row['payment_status']??'pending')==='paid');}
function student_account_reconcile_confirmed_registrations(PDO $db,?int $activityId=null): array {
    $sql="SELECT s.*,f.form_key FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE f.purpose='enrollment'";$args=[];if($activityId!==null){$sql.=' AND s.activity_id=?';$args[]=$activityId;}$sql.=' ORDER BY s.id';$q=$db->prepare($sql);$q->execute($args);$created=0;$disabled=0;$errors=[];
    foreach($q->fetchAll() as $row){try{if(student_account_submission_confirmed($row)){$cohortId=(int)($row['cohort_id']??0);$cohort=$cohortId?course_cohort_by_id($db,$cohortId):null;if(!$cohort||(int)$cohort['activity_id']!==(int)$row['activity_id']){$cohort=course_default_cohort($db,(int)$row['activity_id'],true);$cohortId=(int)$cohort['id'];}$studentId=student_account_upsert_from_submission($db,$row);$now=utc_now();$db->prepare("INSERT INTO course_enrollments(enrollment_uuid,student_id,cohort_id,source_submission_id,status,confirmed_at,created_at,updated_at) VALUES(?,?,?,?, 'active',?,?,?) ON CONFLICT(student_id,cohort_id) DO UPDATE SET source_submission_id=excluded.source_submission_id,status='active',confirmed_at=excluded.confirmed_at,updated_at=excluded.updated_at")->execute([student_uuid(),$studentId,$cohortId,(int)$row['id'],(string)($row['payment_confirmed_at']?:$row['updated_at']?:$now),$now,$now]);$db->prepare('UPDATE cms_form_submissions SET student_id=?,cohort_id=?,updated_at=? WHERE id=?')->execute([$studentId,$cohortId,$now,(int)$row['id']]);$created++;}elseif(!empty($row['student_id'])&&!empty($row['cohort_id'])){$db->prepare("UPDATE course_enrollments SET status='disabled',updated_at=? WHERE student_id=? AND cohort_id=? AND source_submission_id=?")->execute([utc_now(),(int)$row['student_id'],(int)$row['cohort_id'],(int)$row['id']]);$disabled++;}}catch(Throwable $e){$errors[]=['submission_id'=>(int)$row['id'],'error'=>$e->getMessage()];error_log('Student registration reconciliation failed for submission '.(int)$row['id'].': '.$e->getMessage());}}
    return ['processed'=>$created,'disabled'=>$disabled,'errors'=>$errors];
}
function student_account_install_reconciliation_hook(): void {
    $script=str_replace('\\','/',(string)($_SERVER['SCRIPT_NAME']??$_SERVER['PHP_SELF']??''));if(($_SERVER['REQUEST_METHOD']??'GET')!=='POST'||!str_ends_with($script,'/admin/submissions.php'))return;
    register_shutdown_function(static function(): void {try{student_account_reconcile_confirmed_registrations(database());}catch(Throwable $e){error_log('Student reconciliation hook failed: '.$e->getMessage());}});
}
function student_account_assign_submission_cohort(PDO $db,int $submissionId,int $activityId,int $cohortId): void {
    $cohort=course_cohort_by_id($db,$cohortId);if(!$cohort||(int)$cohort['activity_id']!==$activityId)throw new RuntimeException('Turma inválida.');$q=$db->prepare("SELECT s.* FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE s.id=? AND s.activity_id=? AND f.purpose='enrollment'");$q->execute([$submissionId,$activityId]);$row=$q->fetch()?:throw new RuntimeException('Inscrição inválida.');$oldCohort=(int)($row['cohort_id']??0);$studentId=(int)($row['student_id']??0);$db->prepare('UPDATE cms_form_submissions SET cohort_id=?,updated_at=? WHERE id=?')->execute([$cohortId,utc_now(),$submissionId]);if($oldCohort&&$oldCohort!==$cohortId&&$studentId)$db->prepare("UPDATE course_enrollments SET status='disabled',updated_at=? WHERE student_id=? AND cohort_id=? AND source_submission_id=?")->execute([utc_now(),$studentId,$oldCohort,$submissionId]);student_account_reconcile_confirmed_registrations($db,$activityId);
}

function student_account_login(PDO $db,string $email,string $password): bool {
    student_account_reconcile_confirmed_registrations($db);$email=student_normalize_email($email);if($email===''||student_login_blocked($db,$email))return false;$q=$db->prepare("SELECT * FROM student_users WHERE email=? AND status='active'");$q->execute([$email]);$user=$q->fetch()?:null;$legacyActivated=$user&&empty($user['activated_at'])&&(int)($user['must_change_password']??1)===0;
    if(!$user||(!$user['activated_at']&&!$legacyActivated)||!password_verify($password,(string)$user['password_hash'])||!student_account_has_any_enrollment($db,(int)$user['id'])){student_record_failed_login($db,$email);return false;}student_clear_login_attempts($db,$email);if($legacyActivated)$db->prepare('UPDATE student_users SET activated_at=?,privacy_notice_version=? WHERE id=?')->execute([utc_now(),STUDENT_PRIVACY_NOTICE_VERSION,(int)$user['id']]);student_account_start_session($user);$db->prepare('UPDATE student_users SET last_login_at=?,updated_at=? WHERE id=?')->execute([utc_now(),utc_now(),(int)$user['id']]);return true;
}
function student_account_begin_activation(PDO $db,string $email,string $cpf): string {
    student_account_reconcile_confirmed_registrations($db);$email=student_normalize_email($email);$hash=student_account_cpf_lookup_hash($cpf);if($email===''||$hash===''||student_login_blocked($db,$email)){student_record_failed_login($db,$email);return 'invalid';}$q=$db->prepare("SELECT u.* FROM student_users u JOIN student_profiles p ON p.student_id=u.id WHERE u.email=? AND p.cpf_lookup_hash=? AND u.status='active' LIMIT 1");$q->execute([$email,$hash]);$user=$q->fetch()?:null;if(!$user||!student_account_has_any_enrollment($db,(int)$user['id'])){student_record_failed_login($db,$email);return 'invalid';}if(!empty($user['activated_at']))return 'already_active';student_clear_login_attempts($db,$email);$_SESSION['student_activation']=['student_id'=>(int)$user['id'],'issued_at'=>time()];return 'ok';
}
function student_account_activation_user(PDO $db): ?array {$s=is_array($_SESSION['student_activation']??null)?$_SESSION['student_activation']:null;if(!$s||time()-(int)($s['issued_at']??0)>STUDENT_ACTIVATION_TIMEOUT_SECONDS){unset($_SESSION['student_activation']);return null;}$q=$db->prepare("SELECT * FROM student_users WHERE id=? AND status='active'");$q->execute([(int)$s['student_id']]);return $q->fetch()?:null;}
function student_account_complete_activation(PDO $db,string $password,bool $privacyAcknowledged): void {
    $user=student_account_activation_user($db);if(!$user)throw new RuntimeException('A ativação expirou. Comece novamente.');if(!$privacyAcknowledged)throw new RuntimeException('Confirme que leu o Aviso de Privacidade.');if(!student_password_valid($password))throw new RuntimeException('A senha precisa ter pelo menos 12 caracteres.');$hash=password_hash($password,PASSWORD_DEFAULT);if(!is_string($hash)||$hash==='')throw new RuntimeException('password_hash_failed');$now=utc_now();$db->prepare('UPDATE student_users SET password_hash=?,must_change_password=0,activated_at=?,privacy_ack_at=?,privacy_notice_version=?,updated_at=? WHERE id=?')->execute([$hash,$now,$now,STUDENT_PRIVACY_NOTICE_VERSION,$now,(int)$user['id']]);$user['name']=(string)$user['name'];$user['email']=(string)$user['email'];student_account_start_session($user);
}
function student_account_change_password(PDO $db,int $studentId,string $password): void {if(!student_password_valid($password))throw new RuntimeException('A senha precisa ter pelo menos 12 caracteres.');$hash=password_hash($password,PASSWORD_DEFAULT);if(!is_string($hash)||$hash==='')throw new RuntimeException('password_hash_failed');$db->prepare('UPDATE student_users SET password_hash=?,must_change_password=0,updated_at=? WHERE id=?')->execute([$hash,utc_now(),$studentId]);}

function student_account_enrollments(PDO $db,int $studentId): array {$q=$db->prepare("SELECT e.*,c.title cohort_title,c.cohort_uuid,c.activity_id,c.status cohort_status,a.public_title,a.admin_name,a.slug activity_slug,a.is_root FROM course_enrollments e JOIN course_cohorts c ON c.id=e.cohort_id JOIN activities a ON a.id=c.activity_id WHERE e.student_id=? AND e.status='active' AND c.status!='archived' ORDER BY e.confirmed_at DESC,e.id DESC");$q->execute([$studentId]);return $q->fetchAll();}
function student_account_enrollment_for_activity(PDO $db,int $studentId,int $activityId,string $cohortUuid=''): ?array {$sql="SELECT e.*,c.title cohort_title,c.cohort_uuid,c.activity_id,c.status cohort_status FROM course_enrollments e JOIN course_cohorts c ON c.id=e.cohort_id WHERE e.student_id=? AND c.activity_id=? AND e.status='active' AND c.status!='archived'";$args=[$studentId,$activityId];if($cohortUuid!==''){$sql.=' AND c.cohort_uuid=?';$args[]=$cohortUuid;}$sql.=' ORDER BY e.confirmed_at DESC,e.id DESC LIMIT 1';$q=$db->prepare($sql);$q->execute($args);return $q->fetch()?:null;}
function student_account_page_context(PDO $db,array $student,array $page,string $cohortUuid=''): ?array {return student_account_enrollment_for_activity($db,(int)$student['id'],(int)$page['activity_id'],$cohortUuid);}
function student_page_is_protected(array $page): bool {return ($page['access_level']??'public')==='enrolled';}
function student_page_sections_from_document(array $document): array {
    $html=(string)($document['html']??'');if($html==='')return [];$previous=libxml_use_internal_errors(true);$dom=new DOMDocument('1.0','UTF-8');$dom->loadHTML('<?xml encoding="utf-8" ?><div id="student-section-root">'.$html.'</div>',LIBXML_HTML_NOIMPLIED|LIBXML_HTML_NODEFDTD);$xpath=new DOMXPath($dom);$out=[];foreach(iterator_to_array($xpath->query('//*[@data-cms-section]')?:[]) as $node){if(!$node instanceof DOMElement)continue;$key=trim($node->getAttribute('data-cms-section'));if($key===''||isset($out[$key]))continue;$out[$key]=trim($node->getAttribute('data-cms-section-name'))?:$key;}libxml_clear_errors();libxml_use_internal_errors($previous);return $out;
}
function student_page_section_map(PDO $db,int $pageId): array {$q=$db->prepare('SELECT s.section_key,s.lesson_id,l.title,l.lesson_key FROM course_page_sections s JOIN course_lessons l ON l.id=s.lesson_id WHERE s.page_id=?');$q->execute([$pageId]);$out=[];foreach($q->fetchAll() as $row)$out[(string)$row['section_key']]=$row;return $out;}
function student_page_set_section_lesson(PDO $db,int $pageId,string $sectionKey,?int $lessonId): void {$sectionKey=trim($sectionKey);if($sectionKey==='')return;if($lessonId===null||$lessonId<1){$db->prepare('DELETE FROM course_page_sections WHERE page_id=? AND section_key=?')->execute([$pageId,$sectionKey]);return;}$page=cms_page_by_id($db,$pageId)??throw new RuntimeException('Página inválida.');$q=$db->prepare('SELECT 1 FROM course_lessons WHERE id=? AND activity_id=?');$q->execute([$lessonId,(int)$page['activity_id']]);if(!$q->fetchColumn())throw new RuntimeException('Aula inválida.');$now=utc_now();$db->prepare('INSERT INTO course_page_sections(page_id,section_key,lesson_id,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(page_id,section_key) DO UPDATE SET lesson_id=excluded.lesson_id,updated_at=excluded.updated_at')->execute([$pageId,$sectionKey,$lessonId,$now,$now]);}
function student_page_set_access(PDO $db,int $activityId,int $pageId,string $access): void {if(!in_array($access,['public','enrolled'],true))throw new RuntimeException('Acesso inválido.');$db->prepare('UPDATE cms_pages SET access_level=?,show_in_nav=CASE WHEN ?="enrolled" THEN 0 ELSE show_in_nav END,updated_at=? WHERE id=? AND activity_id=?')->execute([$access,$access,utc_now(),$pageId,$activityId]);}
function student_page_released_lesson_ids(PDO $db,int $cohortId): array {$q=$db->prepare('SELECT lesson_id FROM cohort_lesson_releases WHERE cohort_id=? AND released_at IS NOT NULL');$q->execute([$cohortId]);return array_fill_keys(array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN)),true);}
function student_page_filter_document(PDO $db,array $page,array $document,array $enrollment): array {
    $map=student_page_section_map($db,(int)$page['id']);if(!$map)return $document;$released=student_page_released_lesson_ids($db,(int)$enrollment['cohort_id']);$html=(string)($document['html']??'');$previous=libxml_use_internal_errors(true);$dom=new DOMDocument('1.0','UTF-8');$dom->loadHTML('<?xml encoding="utf-8" ?><div id="student-filter-root">'.$html.'</div>',LIBXML_HTML_NOIMPLIED|LIBXML_HTML_NODEFDTD);$xpath=new DOMXPath($dom);foreach(iterator_to_array($xpath->query('//*[@data-cms-section]')?:[]) as $node){if(!$node instanceof DOMElement)continue;$key=$node->getAttribute('data-cms-section');$rule=$map[$key]??null;if(!$rule||isset($released[(int)$rule['lesson_id']]))continue;$node->parentNode?->removeChild($node);}$root=$dom->getElementById('student-filter-root');$out='';if($root)foreach(iterator_to_array($root->childNodes) as $child)$out.=$dom->saveHTML($child);libxml_clear_errors();libxml_use_internal_errors($previous);$document['html']=$out;return $document;
}
function student_page_prefill_forms(PDO $db,array $student,array $document): void {
    $html=(string)($document['html']??'');if(!str_contains($html,'data-cms-form-key'))return;$values=student_account_profile_values($db,(int)$student['id']);$previous=libxml_use_internal_errors(true);$dom=new DOMDocument('1.0','UTF-8');$dom->loadHTML('<?xml encoding="utf-8" ?><div>'.$html.'</div>',LIBXML_HTML_NOIMPLIED|LIBXML_HTML_NODEFDTD);$xpath=new DOMXPath($dom);foreach(iterator_to_array($xpath->query('//*[@data-cms-form-key]')?:[]) as $node){if(!$node instanceof DOMElement)continue;$key=trim($node->getAttribute('data-cms-form-key'));if($key==='')continue;$pageActivity=(int)($GLOBALS['student_prefill_activity_id']??0);if($pageActivity<1)continue;$locale=(string)($GLOBALS['student_prefill_locale']??PUBLIC_LOCALE_PT_BR);$form=cms_form_by_key($db,$pageActivity,$locale,$key);if(!$form)continue;$uuid=(string)$form['form_uuid'];if(isset($_SESSION['cms_form_flash'][$uuid]))continue;$_SESSION['cms_form_flash'][$uuid]=['values'=>$values,'errors'=>[],'success'=>false];}libxml_clear_errors();libxml_use_internal_errors($previous);
}
function student_page_prefill_for_page(PDO $db,array $student,array $page,array $document): void {$GLOBALS['student_prefill_activity_id']=(int)$page['activity_id'];$GLOBALS['student_prefill_locale']=(string)$page['locale'];try{student_page_prefill_forms($db,$student,$document);}finally{unset($GLOBALS['student_prefill_activity_id'],$GLOBALS['student_prefill_locale']);}}

function student_private_media_root(): string {return dirname(__DIR__).'/storage/student-media';}
function student_private_media_mkdir(): void {$dir=student_private_media_root();if(!is_dir($dir)&&!mkdir($dir,0750,true)&&!is_dir($dir))throw new RuntimeException('Não foi possível criar o armazenamento privado.');}
function student_private_media_create(PDO $db,int $activityId,int $pageId,string $title,array $file): array {
    $page=cms_page_by_id($db,$pageId);if(!$page||(int)$page['activity_id']!==$activityId||!student_page_is_protected($page))throw new RuntimeException('Selecione uma página protegida.');if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK||!is_file((string)($file['tmp_name']??''))||($file['size']??0)<1)throw new RuntimeException('Arquivo inválido.');if((int)$file['size']>25*1024*1024)throw new RuntimeException('O arquivo excede 25 MB.');$mime=(new finfo(FILEINFO_MIME_TYPE))->file((string)$file['tmp_name'])?:'';$ext=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'][$mime]??null;if($ext===null)throw new RuntimeException('Use JPEG, PNG ou WebP.');$uuid=student_uuid();student_private_media_mkdir();$relative=$uuid.'.'.$ext;$dest=student_private_media_root().'/'.$relative;if(!move_uploaded_file((string)$file['tmp_name'],$dest))throw new RuntimeException('Falha ao armazenar arquivo.');$now=utc_now();try{$db->prepare('INSERT INTO student_private_media(asset_uuid,activity_id,page_id,title,original_name,mime_type,byte_size,storage_path,checksum,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute([$uuid,$activityId,$pageId,trim($title)!==''?trim($title):pathinfo((string)($file['name']??'imagem'),PATHINFO_FILENAME),(string)($file['name']??$relative),$mime,(int)$file['size'],$relative,hash_file('sha256',$dest),$now,$now]);}catch(Throwable $e){@unlink($dest);throw $e;}return student_private_media_by_uuid($db,$uuid)??throw new RuntimeException('media_create_failed');
}
function student_private_media_by_uuid(PDO $db,string $uuid): ?array {$q=$db->prepare('SELECT * FROM student_private_media WHERE asset_uuid=?');$q->execute([$uuid]);return $q->fetch()?:null;}
function student_private_media_for_page(PDO $db,int $pageId): array {$q=$db->prepare('SELECT * FROM student_private_media WHERE page_id=? ORDER BY id DESC');$q->execute([$pageId]);return $q->fetchAll();}
function student_private_media_sig(int $studentId,string $uuid,int $pageId,int $cohortId,int $expires): string {return hash_hmac('sha256',$studentId.'|'.$uuid.'|'.$pageId.'|'.$cohortId.'|'.$expires,(string)app_config()['app_secret']);}
function student_private_media_url(int $studentId,string $uuid,int $pageId,int $cohortId): string {$expires=time()+STUDENT_MEDIA_URL_TTL_SECONDS;$sig=student_private_media_sig($studentId,$uuid,$pageId,$cohortId,$expires);return '/aluno/media.php?asset='.rawurlencode($uuid).'&page='.$pageId.'&cohort='.$cohortId.'&expires='.$expires.'&sig='.$sig;}
function student_page_sign_private_media(array $document,array $student,array $page,array $enrollment): array {
    $html=(string)($document['html']??'');$studentId=(int)$student['id'];$pageId=(int)$page['id'];$cohortId=(int)$enrollment['cohort_id'];$html=preg_replace_callback('~(?:https?://[^\"\']+)?/aluno/media\.php\?asset=([a-f0-9]{32})(?:&amp;|&[^\"\']*)?~i',static fn($m)=>h(student_private_media_url($studentId,strtolower($m[1]),$pageId,$cohortId)),$html)??$html;$document['html']=$html;return $document;
}
function student_private_media_authorize(PDO $db,array $student,string $uuid,int $pageId,int $cohortId,int $expires,string $sig): ?array {
    if($expires<time()||$expires>time()+STUDENT_MEDIA_URL_TTL_SECONDS+60)return null;$expected=student_private_media_sig((int)$student['id'],$uuid,$pageId,$cohortId,$expires);if(!hash_equals($expected,$sig))return null;$page=cms_page_by_id($db,$pageId);if(!$page||!student_page_is_protected($page))return null;$context=student_account_enrollment_for_activity($db,(int)$student['id'],(int)$page['activity_id']);if(!$context||(int)$context['cohort_id']!==$cohortId)return null;$asset=student_private_media_by_uuid($db,$uuid);if(!$asset||(int)$asset['page_id']!==$pageId||(int)$asset['activity_id']!==(int)$page['activity_id'])return null;return $asset;
}
function student_private_media_placeholder(array $asset): string {return '/aluno/media.php?asset='.(string)$asset['asset_uuid'];}

function student_account_pages_for_enrollment(PDO $db,array $enrollment): array {$q=$db->prepare("SELECT * FROM cms_pages WHERE activity_id=? AND access_level='enrolled' AND status!='archived' AND published_document_json IS NOT NULL ORDER BY locale,sort_order,id");$q->execute([(int)$enrollment['activity_id']]);return $q->fetchAll();}
function student_account_confirmed_submissions(PDO $db,int $activityId): array {$q=$db->prepare("SELECT s.*,f.title form_title FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE s.activity_id=? AND f.purpose='enrollment' AND s.status!='archived' AND (s.status='converted' OR s.payment_status='paid') ORDER BY s.created_at DESC");$q->execute([$activityId]);return $q->fetchAll();}
