<?php
declare(strict_types=1);

function student_shell_start(string $title,?array $activity=null,?array $student=null): void {
    $assetVersion=function_exists('admin_asset_version')?admin_asset_version():(string)(@filemtime(dirname(__DIR__).'/assets/student-area.css')?:1);
    $path=(string)parse_url((string)($_SERVER['REQUEST_URI']??'/aluno/'),PHP_URL_PATH);
    $active=str_contains($path,'test')?'tests':(str_contains($path,'perfil')||str_contains($path,'senha')?'account':'courses');
    ?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><meta name="theme-color" content="#f2f2ef"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=IBM+Plex+Sans:wght@300;400;500;600&family=Saira+Extra+Condensed:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/student-area.css?v=<?=h($assetVersion)?>"><link rel="stylesheet" href="/assets/student-dashboard.css?v=<?=h($assetVersion)?>"><title><?=h($title)?></title></head><body class="student-page"><div class="student-shell"><header class="student-topbar"><a class="student-wordmark" href="/aluno/">Direct Positive Workshop</a><?php if($student):?><nav class="student-desktop-nav" aria-label="Área do aluno"><a href="/aluno/"<?=$active==='courses'?' aria-current="page"':''?>>Cursos</a><a href="/aluno/testes.php"<?=$active==='tests'?' aria-current="page"':''?>>Testes</a><a href="/aluno/perfil.php"<?=$active==='account'?' aria-current="page"':''?>>Conta</a></nav><span class="student-topbar-spacer"></span><span class="student-user"><?=h((string)$student['name'])?></span><form method="post" action="/aluno/logout.php" class="student-logout-form"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-logout'))?>"><button class="student-logout" type="submit">Sair</button></form><?php endif;?></header><main class="student-main"><?php
}
function student_shell_end(): void {
    $student=function_exists('student_account_current')?student_account_current(database()):null;
    $path=(string)parse_url((string)($_SERVER['REQUEST_URI']??'/aluno/'),PHP_URL_PATH);$active=str_contains($path,'test')?'tests':(str_contains($path,'perfil')||str_contains($path,'senha')?'account':'courses');
    ?></main><?php if($student):?><nav class="student-mobile-nav" aria-label="Navegação da área do aluno"><a href="/aluno/"<?=$active==='courses'?' aria-current="page"':''?>><span>01</span>Cursos</a><a href="/aluno/testes.php"<?=$active==='tests'?' aria-current="page"':''?>><span>02</span>Testes</a><a href="/aluno/perfil.php"<?=$active==='account'?' aria-current="page"':''?>><span>03</span>Conta</a></nav><?php endif;?></div></body></html><?php }
