<?php
declare(strict_types=1);

function student_shell_start(string $title,?array $activity=null,?array $student=null): void {
    $assetVersion=function_exists('admin_asset_version')?admin_asset_version():(string)(@filemtime(dirname(__DIR__).'/assets/student-area.css')?:1);
    $path=(string)(parse_url((string)($_SERVER['REQUEST_URI']??'/aluno/'),PHP_URL_PATH)?:'/aluno/');
    $isCourses=$path==='/aluno/'||str_ends_with($path,'/index.php');
    $isTests=str_contains($path,'/aluno/teste');
    $isProfile=str_contains($path,'/aluno/perfil')||str_contains($path,'/aluno/senha');
    ?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><meta name="theme-color" content="#f2f2ef"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=IBM+Plex+Sans:wght@300;400;500;600&family=Saira+Extra+Condensed:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/student-area.css?v=<?=h($assetVersion)?>"><title><?=h($title)?></title></head><body class="student-page"><div class="student-shell"><header class="student-topbar"><a class="student-wordmark" href="/">João Saidler Fotografia</a><?php if($student):?><nav class="student-desktop-nav" aria-label="Área do aluno"><a href="/aluno/"<?=$isCourses?' aria-current="page"':''?>>Cursos</a><a href="/aluno/testes.php"<?=$isTests?' aria-current="page"':''?>>Testes</a><a href="/aluno/perfil.php"<?=$isProfile?' aria-current="page"':''?>>Perfil</a></nav><div class="student-account"><span class="student-user"><?=h((string)$student['name'])?></span><form method="post" action="/aluno/logout.php"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-logout'))?>"><button class="student-logout" type="submit">Sair</button></form></div><?php endif;?><div class="student-theme" aria-label="Tema"><button type="button" data-theme-value="auto" aria-label="Tema automático">Auto</button><button type="button" data-theme-value="light" aria-label="Tema claro">Light</button><button type="button" data-theme-value="dark" aria-label="Tema escuro">Dark</button></div></header><main class="student-main"><?php
}
function student_shell_end(): void {?></main><?php $student=student_account_current(database());if($student):?><nav class="student-bottom-nav" aria-label="Navegação da Área do aluno"><a href="/aluno/"><span>Cursos</span></a><a href="/aluno/testes.php"><span>Testes</span></a><a href="/aluno/perfil.php"><span>Perfil</span></a></nav><?php endif;?><script src="/assets/student-area.js?v=<?=h(function_exists('admin_asset_version')?admin_asset_version():(string)(@filemtime(dirname(__DIR__).'/assets/student-area.js')?:1))?>"></script></div></body></html><?php }
