<?php
declare(strict_types=1);

function student_shell_activity(?array $activity,?array $student): ?array {return $activity;}
function student_shell_active_area(string $path): string {
    if(str_contains($path,'perfil')||str_contains($path,'senha'))return 'account';
    if(str_contains($path,'caderno')||str_contains($path,'teste')||str_contains($path,'comparar-processos'))return 'notebook';
    if(str_contains($path,'ferramentas')||str_contains($path,'reciprocidade')||str_contains($path,'exposicao')||str_contains($path,'temporizador')||str_contains($path,'calibracao')||str_contains($path,'preparo-solucoes')||str_contains($path,'inventario')||str_contains($path,'preparos'))return 'tools';
    return 'courses';
}
function student_course_context_header(array $enrollment,string $active='overview',string $materialUrl=''): void {
    $cohortUuid=(string)($enrollment['cohort_uuid']??'');$overviewUrl='/aluno/?cohort='.rawurlencode($cohortUuid);$questionsUrl='/aluno/duvidas.php?cohort='.rawurlencode($cohortUuid);$statusLabel=function_exists('student_enrollment_cohort_status_label')?student_enrollment_cohort_status_label((string)($enrollment['cohort_status']??'')):(string)($enrollment['cohort_status']??'');?>
    <header class="student-course-context" aria-label="Contexto do curso"><a class="student-course-context-back" href="/aluno/">← Meus cursos</a><div class="student-course-context-head"><div><p class="student-course-context-kicker"><?=h((string)($enrollment['cohort_title']??''))?></p><h1 class="student-course-context-title"><?=h((string)($enrollment['course_title']??'Curso'))?></h1></div><?php if($statusLabel!==''):?><span class="student-status student-course-context-status"><?=h($statusLabel)?></span><?php endif;?></div><nav class="student-course-context-nav" aria-label="Navegação do curso"><a href="<?=h($overviewUrl)?>"<?=$active==='overview'?' aria-current="page"':''?>>Visão geral</a><?php if($materialUrl!==''):?><a href="<?=h($materialUrl)?>"<?=$active==='material'?' aria-current="page"':''?>>Material</a><?php endif;?><a href="<?=h($questionsUrl)?>"<?=$active==='questions'?' aria-current="page"':''?>>Dúvidas</a></nav></header><?php
}
function student_shell_nav(string $active,string $class): void {?>
<nav class="<?=h($class)?>" aria-label="Área do aluno"><a href="/aluno/"<?=$active==='courses'?' aria-current="page"':''?>><span>01</span>Meus cursos</a><a href="/aluno/caderno.php"<?=$active==='notebook'?' aria-current="page"':''?>><span>02</span>Caderno</a><a href="/aluno/ferramentas.php"<?=$active==='tools'?' aria-current="page"':''?>><span>03</span>Ferramentas</a><a href="/aluno/perfil.php"<?=$active==='account'?' aria-current="page"':''?>><span>04</span>Conta</a></nav><?php
}
function student_shell_start(string $title,?array $activity=null,?array $student=null): void {
    $assetVersion=function_exists('admin_asset_version')?admin_asset_version():(string)(@filemtime(dirname(__DIR__).'/assets/ui-core.css')?:1);$resolvedActivity=student_shell_activity($activity,$student);$design=$resolvedActivity?cms_design_settings(database(),(int)$resolvedActivity['id'],PUBLIC_LOCALE_PT_BR):cms_design_defaults();$path=(string)parse_url((string)($_SERVER['REQUEST_URI']??'/aluno/'),PHP_URL_PATH);$active=student_shell_active_area($path);$brand=function_exists('installation_brand_name')?installation_brand_name():'JSaidler Fotografia';?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="noindex,nofollow,noarchive,nosnippet"><meta name="theme-color" content="<?=h((string)($design['colors']['bg']??'#f2f2ef'))?>"><style data-cms-design-fonts><?=cms_design_font_import_css($design)?></style><link rel="stylesheet" href="/template/page.css?v=<?=h($assetVersion)?>"><style data-cms-design-tokens><?=cms_design_css($design)?></style><link rel="stylesheet" href="/assets/ui-core.css?v=<?=h($assetVersion)?>"><link rel="stylesheet" href="/assets/student-area.css?v=<?=h($assetVersion)?>"><link rel="stylesheet" href="/assets/student-workbench.css?v=<?=h($assetVersion)?>"><title><?=h($title)?></title></head><body class="student-page"><div class="student-shell"><header class="student-topbar"><a class="brand student-wordmark" href="/aluno/"><?=h($brand)?></a><?php if($student)student_shell_nav($active,'student-desktop-nav');?><span class="student-topbar-spacer"></span><div aria-label="Tema" class="theme-switch student-theme-switch"><button aria-pressed="true" data-theme-value="auto" type="button">Auto</button><button aria-pressed="false" data-theme-value="light" type="button">Light</button><button aria-pressed="false" data-theme-value="dark" type="button">Dark</button></div><?php if($student):?><span class="student-user"><?=h((string)$student['name'])?></span><form method="post" action="/aluno/logout.php" class="student-logout-form"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-logout'))?>"><button class="student-logout" type="submit">Sair</button></form><?php endif;?></header><main class="student-main"><?php
}
function student_shell_end(): void {
    $student=function_exists('student_account_current')?student_account_current(database()):null;$path=(string)parse_url((string)($_SERVER['REQUEST_URI']??'/aluno/'),PHP_URL_PATH);$active=student_shell_active_area($path);$assetVersion=function_exists('admin_asset_version')?admin_asset_version():(string)(@filemtime(dirname(__DIR__).'/assets/ui-core.js')?:1);$reciprocityVersion=(string)(@filemtime(dirname(__DIR__).'/assets/student-reciprocity.js')?:$assetVersion);$workbenchVersion=(string)(@filemtime(dirname(__DIR__).'/assets/student-workbench.js')?:$assetVersion);?></main><?php if($student)student_shell_nav($active,'student-mobile-nav');?></div><script defer src="/assets/ui-core.js?v=<?=h($assetVersion)?>"></script><script defer src="/assets/student-reciprocity.js?v=<?=h($reciprocityVersion)?>"></script><script defer src="/assets/student-workbench.js?v=<?=h($workbenchVersion)?>"></script></body></html><?php }
