const STORAGE_KEY='controlled-visual-editor-content-v1',frame=document.querySelector('#page-frame'),properties=document.querySelector('#properties'),overlay=document.querySelector('#editor-overlay-layer'),modal=document.querySelector('#media-modal'),mediaGrid=document.querySelector('#media-grid'),toast=document.querySelector('#toast'),sectionsList=document.querySelector('#sections-list');
let content,selected={type:'none'},editing=null,framing=null,sectionDrag=null,history=[],historyIndex=-1,hookedDocument=null;var activitySuffix=new URLSearchParams(location.search).get('activity');activitySuffix=activitySuffix?`?activity=${encodeURIComponent(activitySuffix)}`:'';
const clone=value=>JSON.parse(JSON.stringify(value)),typeFor=element=>element.hasAttribute('data-editable-image')?'image':element.hasAttribute('data-editable-video')?'video':element.hasAttribute('data-editable-text')?'text':element.hasAttribute('data-editable-form')||element.matches('form.interest-form')?'form':element.hasAttribute('data-section')?'section':'none',keyFor=(type,element)=>element.dataset[`editable${type[0].toUpperCase()+type.slice(1)}`],sel=(type,key)=>`[data-editable-${type}="${CSS.escape(key)}"]`,clamp=(value,min=0,max=100)=>Math.max(min,Math.min(max,value));
function announce(message){toast.textContent=message;toast.classList.add('show');clearTimeout(announce.timer);announce.timer=setTimeout(()=>toast.classList.remove('show'),1600)}
function historyControls(){document.querySelector('#undo').disabled=historyIndex<1;document.querySelector('#redo').disabled=historyIndex>=history.length-1}function push(){history=history.slice(0,historyIndex+1);history.push(clone(content));historyIndex=history.length-1;historyControls();if(typeof contentStatus==='function')contentStatus()}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(content));announce('Conteúdo salvo no navegador.')}
function positionPart(value,index){const part=String(value||'50% 50%').split(' ')[index];const number=Number.parseFloat(part);return Number.isFinite(number)?clamp(number):50}
function imageFrame(value){return {...value,objectFit:value.objectFit||'cover',positionX:clamp(Number.isFinite(value.positionX)?value.positionX:positionPart(value.objectPosition,0)),positionY:clamp(Number.isFinite(value.positionY)?value.positionY:positionPart(value.objectPosition,1)),zoom:clamp(Number.isFinite(value.zoom)?value.zoom:1,1,3)}}
function applyImage(element,value){if(!element)return;const frameValue=imageFrame(value),contain=frameValue.objectFit==='contain',zoom=contain?1:frameValue.zoom;element.src=frameValue.src;element.alt=frameValue.alt||'';element.style.objectFit=frameValue.objectFit;element.style.objectPosition=`${frameValue.positionX}% ${frameValue.positionY}%`;element.style.transformOrigin=`${frameValue.positionX}% ${frameValue.positionY}%`;element.style.transform=zoom===1?'':`scale(${zoom})`;element.style.clipPath=zoom===1?'':'inset(0)';element.parentElement.style.overflow='clip'}
function sectionName(id){return({hero:'Início',workshop:'Workshop',camera:'Câmera',process:'Processo',format:'Formato',about:'Fotógrafo','interest-form':'Formulário'})[id]||id}
function applyVideo(element,value){if(!element)return;const video=element.tagName==='VIDEO'?element:element.querySelector('video');if(!video)return;const source=video.querySelector('source');if(source)source.src=value.src||'';else video.src=value.src||'';video.poster=value.poster||'';video.controls=!!value.controls;video.muted=!!value.muted;video.loop=!!value.loop;video.playsInline=value.playsinline!==false;video.autoplay=!!value.autoplay&&!!value.muted;video.load()}
function apply(){const doc=frame.contentDocument;if(!doc||!content)return;Object.entries(content.texts||{}).forEach(([key,value])=>{const element=doc.querySelector(sel('text',key));if(element&&element!==editing)element.innerHTML=value.html});Object.entries(content.images||{}).forEach(([key,value])=>applyImage(doc.querySelector(sel('image',key)),value));Object.entries(content.videos||{}).forEach(([key,value])=>applyVideo(doc.querySelector(sel('video',key)),value));const main=doc.querySelector('main');(content.sections||[]).forEach(section=>{const element=doc.querySelector(`[data-section="${section.id}"]`);if(!element)return;element.hidden=section.visible===false;if(main)main.append(element)});renderSectionsPanel();renderHiddenBands()}
function clear(){overlay.replaceChildren();selected={type:'none'};properties.classList.remove('open');renderHiddenBands()}
function geometry(element){const host=frame.getBoundingClientRect(),rect=element.getBoundingClientRect();if(element.hasAttribute('data-editable-image')){const value=imageFrame(content.images[keyFor('image',element)]),zoom=value.objectFit==='contain'?1:value.zoom,width=rect.width/zoom,height=rect.height/zoom,left=rect.left+width*(zoom-1)*value.positionX/100,top=rect.top+height*(zoom-1)*value.positionY/100;return{x:host.left+left,y:host.top+top,width,height}}return{x:host.left+rect.left,y:host.top+rect.top,width:rect.width,height:rect.height}}
function visible(rect){return rect.y+rect.height>58&&rect.y<window.innerHeight&&rect.x+rect.width>0&&rect.x<window.innerWidth}
function box(element,label){overlay.replaceChildren();const rect=geometry(element);if(!visible(rect))return null;const border=document.createElement('div'),tag=document.createElement('div');border.className='selection-box';border.style.cssText=`left:${rect.x}px;top:${rect.y}px;width:${rect.width}px;height:${rect.height}px`;tag.className='overlay-label';tag.textContent=label;tag.style.cssText=`left:${rect.x}px;top:${Math.max(58,rect.y-18)}px`;overlay.append(border,tag);return rect}
function toolbar(rect,html){if(!rect)return null;const bar=document.createElement('div');bar.className='overlay-toolbar';bar.style.visibility='hidden';bar.innerHTML=html;overlay.append(bar);const width=bar.offsetWidth||250,height=bar.offsetHeight||34,limit=properties.classList.contains('open')?window.innerWidth-306:window.innerWidth,left=Math.max(8,Math.min(rect.x,limit-width-8)),above=rect.y-height-8,below=rect.y+rect.height+8;bar.style.left=`${left}px`;bar.style.top=`${above>=62?above:Math.min(below,window.innerHeight-height-8)}px`;bar.style.visibility='visible';return bar}
function scrollSectionIntoView(element){const doc=element?.ownerDocument,scroller=doc?.scrollingElement;if(!scroller)return;const target=Math.max(0,element.offsetTop-100);scroller.scrollTop=target}
function renderSectionsPanel(){if(!sectionsList||!content)return;sectionsList.innerHTML=(content.sections||[]).map(section=>`<button class="structure-row ${selected.type==='section'&&selected.key===section.id?'is-selected':''}" data-section-select="${section.id}"><span>${sectionName(section.id)}</span><small>${section.visible===false?'Oculta':'Visível'}</small></button>`).join('');sectionsList.querySelectorAll('[data-section-select]').forEach(button=>button.onclick=()=>{const element=frame.contentDocument.querySelector(`[data-section="${button.dataset.sectionSelect}"]`);if(element&&!element.hidden){scrollSectionIntoView(element);requestAnimationFrame(()=>select(element))}})}
function renderHiddenBands(){overlay.querySelectorAll('.hidden-section-band').forEach(band=>band.remove());if(!content||selected.type!=='none')return;const doc=frame.contentDocument;if(!doc)return;(content.sections||[]).filter(section=>section.visible===false).forEach(section=>{const index=content.sections.findIndex(item=>item.id===section.id),next=content.sections.slice(index+1).map(item=>doc.querySelector(`[data-section="${item.id}"]`)).find(item=>item&&!item.hidden),host=frame.getBoundingClientRect(),nextRect=next?geometry(next):null,band=document.createElement('div');band.className='hidden-section-band';band.style.left=`${nextRect?nextRect.x:host.left+8}px`;band.style.top=`${nextRect?Math.max(62,nextRect.y-42):host.bottom-50}px`;band.style.width=`${nextRect?nextRect.width:host.width-16}px`;band.innerHTML=`<span>${sectionName(section.id)} está oculta</span><button data-show-section="${section.id}">Mostrar</button>`;overlay.append(band)});overlay.querySelectorAll('[data-show-section]').forEach(button=>button.onclick=()=>showSection(button.dataset.showSection))}
function normalizeSectionOrder(){content.sections.forEach((section,index)=>section.order=index+1)}
function moveSection(id,direction){const from=content.sections.findIndex(section=>section.id===id),to=from+direction;if(from<0||to<0||to>=content.sections.length)return;content.sections.splice(to,0,content.sections.splice(from,1)[0]);normalizeSectionOrder();apply();push();const element=frame.contentDocument.querySelector(`[data-section="${id}"]`);if(element)select(element)}
function hideSection(id){const section=content.sections.find(item=>item.id===id);if(!section)return;section.visible=false;selected={type:'none'};overlay.replaceChildren();apply();push();announce(`${sectionName(id)} ocultada.`)}
function showSection(id){const section=content.sections.find(item=>item.id===id);if(!section)return;section.visible=true;apply();push();const element=frame.contentDocument.querySelector(`[data-section="${id}"]`);if(element){scrollSectionIntoView(element);select(element)}announce(`${sectionName(id)} restaurada.`)}
function sectionHandle(rect,id){const handle=document.createElement('button');handle.type='button';handle.className='section-drag-handle';handle.dataset.sectionHandle=id;handle.textContent='⋮⋮';handle.setAttribute('aria-label',`Arrastar seção ${sectionName(id)}`);handle.style.left=`${Math.max(8,rect.x+6)}px`;handle.style.top=`${Math.max(62,rect.y+6)}px`;handle.onpointerdown=event=>startSectionDrag(event,id);overlay.append(handle)}
function renderSectionSelection(rect){if(!rect)return;sectionHandle(rect,selected.key);const label=overlay.querySelector('.overlay-label');if(label)label.textContent=`Seção: ${sectionName(selected.key)}`}
function renderSectionHover(element){if(selected.type!=='none'||sectionDrag)return;const rect=geometry(element);if(!visible(rect))return;overlay.replaceChildren();const tag=document.createElement('button');tag.type='button';tag.className='overlay-label section-hover-label';tag.textContent=`Seção: ${sectionName(element.dataset.section)}`;tag.style.left=`${rect.x}px`;tag.style.top=`${Math.max(62,rect.y-18)}px`;tag.onclick=()=>select(element);overlay.append(tag);sectionHandle(rect,element.dataset.section);renderHiddenBands()}
function insertionIndex(y,id){const doc=frame.contentDocument,items=content.sections.filter(section=>section.id!==id&&section.visible!==false);for(const item of items){const rect=geometry(doc.querySelector(`[data-section="${item.id}"]`));if(y<rect.y+rect.height/2)return content.sections.findIndex(section=>section.id===item.id)}return content.sections.length}
function renderDropIndicator(index){overlay.querySelectorAll('.section-drop-indicator,.section-drag-ghost').forEach(node=>node.remove());const doc=frame.contentDocument,reference=content.sections[index]&&doc.querySelector(`[data-section="${content.sections[index].id}"]`),host=frame.getBoundingClientRect(),rect=reference?geometry(reference):null,line=document.createElement('div');line.className='section-drop-indicator';line.style.left=`${rect?rect.x:host.left+8}px`;line.style.top=`${rect?rect.y-3:host.bottom-8}px`;line.style.width=`${rect?rect.width:host.width-16}px`;overlay.append(line)}
function startSectionDrag(event,id){if(event.button!==0)return;event.preventDefault();event.stopPropagation();const element=frame.contentDocument.querySelector(`[data-section="${id}"]`),rect=geometry(element);if(!element)return;sectionDrag={id,from:content.sections.findIndex(section=>section.id===id),to:0};const ghost=document.createElement('div');ghost.className='section-drag-ghost';ghost.textContent=`Movendo: ${sectionName(id)}`;ghost.style.left=`${rect.x+12}px`;ghost.style.top=`${rect.y+12}px`;overlay.append(ghost);renderDropIndicator(sectionDrag.from);overlay.append(ghost);const move=pointer=>{if(!sectionDrag)return;ghost.style.top=`${Math.max(62,Math.min(window.innerHeight-44,pointer.clientY-18))}px`;sectionDrag.to=insertionIndex(pointer.clientY,id);renderDropIndicator(sectionDrag.to);overlay.append(ghost);const host=frame.getBoundingClientRect(),scroller=frame.contentDocument.scrollingElement;if(pointer.clientY<host.top+42)scroller.scrollTop-=18;if(pointer.clientY>host.bottom-42)scroller.scrollTop+=18};const finish=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('mousemove',move);if(!sectionDrag)return;const drag=sectionDrag;sectionDrag=null;overlay.querySelectorAll('.section-drop-indicator,.section-drag-ghost').forEach(node=>node.remove());let to=drag.to;if(to>drag.from)to--;if(to!==drag.from){content.sections.splice(to,0,content.sections.splice(drag.from,1)[0]);normalizeSectionOrder();apply();push()}const active=frame.contentDocument.querySelector(`[data-section="${drag.id}"]`);if(active){scrollSectionIntoView(active);select(active)}};document.addEventListener('pointermove',move);document.addEventListener('mousemove',move);document.addEventListener('pointerup',finish,{once:true});document.addEventListener('mouseup',finish,{once:true})}
function select(element){if(framing&&framing.element!==element)cancelFraming();if(editing)finish(true);const type=typeFor(element);if(type==='none')return clear();selected={type,key:type==='section'?element.dataset.section:keyFor(type,element),element};const label=type==='section'?`Seção: ${sectionName(element.dataset.section)}`:type==='image'?'Imagem':type==='video'?'Vídeo':type==='text'?'Texto':type==='form'?'Formulário':type;const rect=box(element,label);if(type==='image')renderImageTools(rect);if(type==='video')renderVideoTools(rect);if(type==='form')renderFormTools(rect);if(type==='section'){renderSectionSelection(rect);renderSectionTools(rect)}renderSectionsPanel()}
function renderImageTools(rect){const bar=toolbar(rect,'<button data-a="replace">Substituir</button><button data-a="frame">Enquadrar</button><button data-a="properties">Propriedades</button><button data-a="remove">Remover</button>');if(!bar)return;bar.onclick=event=>{const action=event.target.dataset.a;if(action==='replace')openMedia();if(action==='frame')startFraming();if(action==='properties')imageProperties();if(action==='remove'){content.images[selected.key].src='';apply();push()}}}
function renderVideoTools(rect){const bar=toolbar(rect,'<button data-a="replace-video">Biblioteca</button><button data-a="remove-video">Remover</button>');if(!bar)return;bar.onclick=event=>{if(event.target.dataset.a==='replace-video')openVideoMedia();if(event.target.dataset.a==='remove-video'){content.videos[selected.key].src='';apply();push()}}}
function renderFormTools(rect){const bar=toolbar(rect,'<button data-form="fields">Campos do formulário</button>');if(!bar)return;bar.onclick=()=>{properties.classList.add('open');properties.innerHTML='<button id="close-properties" class="icon-button" aria-label="Fechar propriedades">×</button><p class="eyebrow">Formulário</p><h2>Campos do formulário</h2><p>Os campos exibidos seguem a mesma definição usada na prévia e no público.</p>';properties.querySelector('#close-properties').onclick=()=>properties.classList.remove('open')}}
function renderSectionTools(rect){const bar=toolbar(rect,'<button data-a="up">Mover para cima</button><button data-a="down">Mover para baixo</button><button data-a="hide">Ocultar</button>');if(!bar)return;bar.classList.add('section-toolbar');bar.onclick=event=>{const action=event.target.dataset.a;if(action==='up')moveSection(selected.key,-1);if(action==='down')moveSection(selected.key,1);if(action==='hide')hideSection(selected.key)}}
function startFraming(){if(selected.type!=='image')return;properties.classList.remove('open');const value=content.images[selected.key];framing={key:selected.key,element:selected.element,original:clone(value),draft:imageFrame(clone(value))};renderFraming()}
function compactFraming(){return frame.parentElement.classList.contains('tablet')||frame.parentElement.classList.contains('mobile')||window.innerWidth<=800}
function renderFraming(){if(!framing)return;const rect=box(framing.element,'Imagem');if(!rect)return;const border=overlay.querySelector('.selection-box'),value=framing.draft; border.classList.add('framing-box');border.classList.toggle('contain-mode',value.objectFit==='contain');border.onpointerdown=startImageDrag;const focus=value.objectFit==='contain'?'Imagem inteira':`Foco ${Math.round(value.positionX)}/${Math.round(value.positionY)}`,bar=toolbar(rect,`<button data-frame="zoom-down" aria-label="zoom −">zoom −</button><input data-frame="zoom" aria-label="Controle de zoom" type="range" min="1" max="3" step="0.05" value="${value.zoom}"><button data-frame="zoom-up" aria-label="zoom +">zoom +</button><span class="framing-focus">${focus}</span><button data-frame="cover" ${value.objectFit==='cover'?'aria-pressed="true"':''}>Cover</button><button data-frame="contain" ${value.objectFit==='contain'?'aria-pressed="true"':''}>Contain</button><button data-frame="restore">Restaurar</button><button data-frame="cancel">Cancelar</button><button data-frame="apply">Aplicar</button>`);if(!bar)return;bar.classList.add('framing-toolbar');if(compactFraming()){const host=frame.getBoundingClientRect(),width=Math.min(host.width-16,window.innerWidth-16);bar.style.width=`${Math.max(0,width)}px`;bar.style.left=`${Math.max(8,Math.min(host.left+8,window.innerWidth-width-8))}px`;bar.style.top='auto';bar.style.bottom='8px'}bar.oninput=event=>{if(event.target.dataset.frame==='zoom'){framing.draft.zoom=Number(event.target.value);applyImage(framing.element,framing.draft)}};bar.onclick=event=>{const action=event.target.dataset.frame;if(!action)return;if(action==='zoom-down'){framing.draft.zoom=clamp(framing.draft.zoom-.1,1,3);renderFraming();applyImage(framing.element,framing.draft)}if(action==='zoom-up'){framing.draft.zoom=clamp(framing.draft.zoom+.1,1,3);renderFraming();applyImage(framing.element,framing.draft)}if(action==='cover'||action==='contain'){framing.draft.objectFit=action;renderFraming();applyImage(framing.element,framing.draft)}if(action==='restore'){framing.draft=imageFrame(clone(framing.original));renderFraming();applyImage(framing.element,framing.draft)}if(action==='cancel')cancelFraming();if(action==='apply')applyFraming()}}
function startImageDrag(event){if(!framing||framing.draft.objectFit==='contain')return;event.preventDefault();const target=event.currentTarget,startX=event.clientX,startY=event.clientY,originX=framing.draft.positionX,originY=framing.draft.positionY,rect=target.getBoundingClientRect();target.setPointerCapture(event.pointerId);target.classList.add('is-dragging');const move=pointer=>{framing.draft.positionX=clamp(originX-(pointer.clientX-startX)/rect.width*100);framing.draft.positionY=clamp(originY-(pointer.clientY-startY)/rect.height*100);applyImage(framing.element,framing.draft)};const finish=()=>{target.classList.remove('is-dragging');target.removeEventListener('pointermove',move);target.removeEventListener('pointerup',finish);target.removeEventListener('pointercancel',finish)};target.addEventListener('pointermove',move);target.addEventListener('pointerup',finish);target.addEventListener('pointercancel',finish)}
function cancelFraming(){if(!framing)return;const active=framing.element,original=framing.original;framing=null;applyImage(active,original);select(active)}
function applyFraming(){if(!framing)return;const active=framing.element,value=imageFrame(framing.draft);Object.assign(content.images[framing.key],value,{objectPosition:`${value.positionX}% ${value.positionY}%`});framing=null;apply();push();select(active);announce('Enquadramento aplicado.')}
function finish(keep=true){if(!editing)return;const element=editing,key=element.dataset.editableText;editing=null;element.contentEditable='false';if(content.texts[key].html!==element.innerHTML){content.texts[key].html=element.innerHTML;push()}if(keep)select(element)}
function cancelEdit(){if(!editing)return;const element=editing;element.innerHTML=content.texts[element.dataset.editableText].html;editing=null;element.contentEditable='false';select(element)}
function edit(element,event){editing=element;element.contentEditable='true';element.focus();const doc=element.ownerDocument,selection=doc.getSelection();selection.removeAllRanges();let range=doc.caretRangeFromPoint?.(event.clientX,event.clientY);if(!range||!element.contains(range.startContainer)){range=doc.createRange();range.selectNodeContents(element);range.collapse(false)}selection.addRange(range);const rect=box(element,'Texto'),bar=toolbar(rect,'<button data-f="bold">Negrito</button><button data-f="italic">Itálico</button><button data-f="link">Link</button><button data-f="removeFormat">Limpar</button><button data-f="done">Concluir</button>');if(bar)bar.onclick=event=>{const format=event.target.dataset.f;if(format==='done')finish();else if(format==='link'){const url=prompt('URL');if(url)frame.contentDocument.execCommand('createLink',false,url)}else frame.contentDocument.execCommand(format,false,null)}}
function imageProperties(){const value=content.images[selected.key];properties.classList.add('open');properties.innerHTML=`<button id="close-properties" class="icon-button">×</button><p class="eyebrow">Imagem</p><h2>Propriedades</h2><div class="property-block"><label>Texto alternativo<input id="image-alt" value="${String(value.alt||'').replaceAll('"','&quot;')}"></label><label>Fit<select id="image-fit"><option ${value.objectFit==='cover'?'selected':''}>cover</option><option ${value.objectFit==='contain'?'selected':''}>contain</option></select></label></div>`;properties.querySelector('#close-properties').onclick=()=>properties.classList.remove('open');properties.querySelector('#image-alt').onchange=event=>{value.alt=event.target.value;apply();push()};properties.querySelector('#image-fit').onchange=event=>{value.objectFit=event.target.value;apply();push()}}
async function openMedia(){modal.hidden=false;mediaGrid.innerHTML='<p>Carregando mídia…</p>';try{await MediaLibrary.load();mediaGrid.innerHTML=MediaLibrary.images.map((item,index)=>`<button class="media-item" data-i="${index}"><img src="${item.src}" alt=""><span>${item.label}</span></button>`).join('')||'<p>Nenhuma imagem pronta.</p>';mediaGrid.querySelectorAll('button').forEach(button=>button.onclick=()=>{const item=MediaLibrary.images[+button.dataset.i];content.images[selected.key].src=item.src;if(!content.images[selected.key].alt&&item.alt)content.images[selected.key].alt=item.alt;apply();push();modal.hidden=true});}catch{mediaGrid.innerHTML='<p>Não foi possível carregar a biblioteca.</p>'}}
async function openVideoMedia(){modal.hidden=false;mediaGrid.innerHTML='<p>Carregando vídeos…</p>';try{await MediaLibrary.load();mediaGrid.innerHTML=MediaLibrary.videos.map((item,index)=>`<button class="media-item" data-i="${index}"><span>${item.label}</span><small>${item.src}</small></button>`).join('')||'<p>Nenhum vídeo pronto.</p>';mediaGrid.querySelectorAll('button').forEach(button=>button.onclick=()=>{const item=MediaLibrary.videos[+button.dataset.i],video=content.videos[selected.key];video.src=item.src;if(item.poster)video.poster=item.poster;apply();push();modal.hidden=true;announce('Vídeo selecionado. Salve o rascunho para persistir.');});}catch{mediaGrid.innerHTML='<p>Não foi possível carregar a biblioteca.</p>'}}
function refresh(){if(!selected.element)return;if(framing)return renderFraming();const active=selected.element;if(editing){const rect=box(active,'Texto');toolbar(rect,'<button data-f="bold">Negrito</button><button data-f="italic">Itálico</button><button data-f="link">Link</button><button data-f="removeFormat">Limpar</button><button data-f="done">Concluir</button>')}else select(active)}
function hook(){const doc=frame.contentDocument;doc.addEventListener('click',event=>{const section=event.target.closest('[data-section]'),element=event.target.closest('[data-editable-text],[data-editable-image],[data-editable-video],[data-editable-form],form.interest-form');if(!element&&!section)return clear();event.preventDefault();select(element||section)});doc.addEventListener('dblclick',event=>{const element=event.target.closest('[data-editable-text]');if(element){event.preventDefault();event.stopPropagation();select(element);edit(element,event)}});doc.addEventListener('mousemove',event=>{const section=event.target.closest('[data-section]');if(section&&selected.type==='none'&&event.clientY-section.getBoundingClientRect().top<34)renderSectionHover(section)});doc.defaultView.addEventListener('scroll',refresh);doc.defaultView.addEventListener('resize',refresh);window.addEventListener('resize',refresh);doc.querySelectorAll('a,button').forEach(element=>element.addEventListener('click',event=>event.preventDefault()))}
document.querySelectorAll('[data-viewport]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-viewport]').forEach(item=>item.classList.toggle('active',item===button));document.querySelector('.frame-shell').className=`frame-shell ${button.dataset.viewport==='desktop'?'':button.dataset.viewport}`;requestAnimationFrame(refresh)});document.querySelector('#save').onclick=save;document.querySelector('#restore').onclick=()=>{try{content=JSON.parse(localStorage.getItem(STORAGE_KEY));apply();push();clear();announce('Conteúdo restaurado.')}catch{announce('Não há conteúdo salvo para restaurar.') }};document.querySelector('#preview').onclick=()=>{save();window.open('../preview/','_blank','noopener')};document.querySelector('#undo').onclick=()=>{if(historyIndex>0){content=clone(history[--historyIndex]);apply();historyControls();if(typeof contentStatus==='function')contentStatus()}};document.querySelector('#redo').onclick=()=>{if(historyIndex<history.length-1){content=clone(history[++historyIndex]);apply();historyControls();if(typeof contentStatus==='function')contentStatus()}};document.querySelector('#close-media').onclick=()=>modal.hidden=true;
document.addEventListener('keydown',event=>{if(sectionDrag&&event.key==='Escape'){sectionDrag=null;overlay.querySelectorAll('.section-drop-indicator,.section-drag-ghost').forEach(node=>node.remove());event.preventDefault();return}if(framing){const step=event.shiftKey?8:1;if(event.key==='Escape'){event.preventDefault();cancelFraming()}else if(event.key==='Enter'){event.preventDefault();applyFraming()}else if(event.key==='ArrowLeft'||event.key==='ArrowRight'||event.key==='ArrowUp'||event.key==='ArrowDown'){event.preventDefault();if(event.key==='ArrowLeft')framing.draft.positionX=clamp(framing.draft.positionX-step);if(event.key==='ArrowRight')framing.draft.positionX=clamp(framing.draft.positionX+step);if(event.key==='ArrowUp')framing.draft.positionY=clamp(framing.draft.positionY-step);if(event.key==='ArrowDown')framing.draft.positionY=clamp(framing.draft.positionY+step);applyImage(framing.element,framing.draft)}return}if(!editing&&selected.type==='section'&&event.altKey&&(event.key==='ArrowUp'||event.key==='ArrowDown')){event.preventDefault();moveSection(selected.key,event.key==='ArrowUp'?-1:1);return}if(event.key==='Escape'){cancelEdit();if(!editing)clear()}if((event.ctrlKey||event.metaKey)&&event.key==='Enter')finish();if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();save()}});
async function initializeFrame(){const doc=frame.contentDocument;if(!doc||hookedDocument===doc)return;hookedDocument=doc;if(!content){try{content=JSON.parse(localStorage.getItem(STORAGE_KEY))}catch{}if(!content)content=await (await fetch('../data/default-content.json')).json();push()}apply();hook()}
frame.addEventListener('load',initializeFrame);if(frame.contentDocument?.readyState==='complete')initializeFrame();

let serverRevision=0,serverCsrf='',serverSnapshot='',serverConflict=false;const activityQuery=new URLSearchParams(location.search).get('activity');activitySuffix=activityQuery?`?activity=${encodeURIComponent(activityQuery)}`:'';
const conflictStrip=document.createElement('div'),conflictMessage=document.createElement('span');conflictStrip.className='editor-conflict-strip';conflictStrip.hidden=true;conflictStrip.append(conflictMessage,document.querySelector('#load-latest'));document.querySelector('.editor-bar').after(conflictStrip);
function contentDirty(){return !!content&&JSON.stringify(content)!==serverSnapshot}
function contentStatus(message=''){const status=document.querySelector('#content-status');if(status)status.textContent=message||`${contentDirty()?'Alterações não salvas':'Rascunho salvo'}${serverRevision?` · rev. ${serverRevision}`:''}`;updateServerControls()}
function updateServerControls(){const dirty=contentDirty(),saveButton=document.querySelector('#save'),publishButton=document.querySelector('#publish'),restoreButton=document.querySelector('#restore'),latest=document.querySelector('#load-latest');saveButton.disabled=serverConflict;publishButton.disabled=serverConflict||dirty;restoreButton.disabled=serverConflict;publishButton.title=dirty?'Salve o rascunho antes de publicar':'';conflictStrip.hidden=!serverConflict;conflictMessage.textContent=serverConflict?document.querySelector('#content-status').textContent:'';latest.hidden=!serverConflict;latest.style.display=serverConflict?'':'none'}
async function serverRequest(path,payload={}){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},credentials:'same-origin',body:JSON.stringify({...payload,csrf:serverCsrf})}),data=await response.json().catch(()=>({error:{code:'invalid_response'}}));if(!response.ok){const error=new Error(data.error?.code||'request_failed');error.status=response.status;throw error}return data}
async function loadServerDocument(){const response=await fetch('/admin/api/content-load.php'+activitySuffix,{credentials:'same-origin',headers:{Accept:'application/json'}});if(!response.ok)throw new Error('load_failed');const data=await response.json();content=data.document;serverRevision=data.meta.draftRevision;serverCsrf=data.csrf;serverSnapshot=JSON.stringify(content);serverConflict=false;history=[];historyIndex=-1;push();contentStatus(`Rascunho carregado · rev. ${serverRevision}`)}
async function initializeFrame(){const doc=frame.contentDocument;if(!doc||hookedDocument===doc)return;hookedDocument=doc;try{await loadServerDocument();apply();hook()}catch{announce('Não foi possível carregar o rascunho do servidor.');contentStatus('Erro ao carregar')}}
async function save(){if(!content||serverConflict)return;contentStatus('Salvando…');try{const data=await serverRequest('/admin/api/content-save.php'+activitySuffix,{document:content,draftRevision:serverRevision});content=data.document;serverRevision=data.meta.draftRevision;serverSnapshot=JSON.stringify(content);contentStatus('Rascunho salvo');announce('Rascunho salvo.')}catch(error){if(error.status===409){serverConflict=true;contentStatus('Conflito: há uma versão mais recente no servidor.');announce('Conflito de revisão. Carregue a versão mais recente.')}else{contentStatus('Erro ao salvar');announce('Não foi possível salvar o rascunho.')}}}
async function restoreServer(){if(serverConflict||!confirm('Descartar o rascunho atual e restaurar a última versão publicada?'))return;try{const data=await serverRequest('/admin/api/content-restore.php'+activitySuffix);content=data.document;serverRevision=data.meta.draftRevision;serverSnapshot=JSON.stringify(content);history=[];historyIndex=-1;push();apply();clear();contentStatus('Rascunho restaurado');announce('Rascunho restaurado.')}catch{announce('Não foi possível restaurar o rascunho.')}}
async function publishServer(){if(serverConflict||contentDirty())return;try{const data=await serverRequest('/admin/api/content-publish.php');contentStatus(`Publicado · rev. ${data.meta.publishedRevision}`);announce('Conteúdo publicado.')}catch{announce('Não foi possível publicar. A versão pública anterior foi preservada.')}}
async function loadLatest(){if(!serverConflict)return;await loadServerDocument();apply();clear();announce('Versão mais recente carregada.')}
const publishModal=document.querySelector('#publish-modal'),conflictModal=document.querySelector('#conflict-modal');document.querySelector('#save').onclick=save;document.querySelector('#restore').onclick=restoreServer;document.querySelector('#publish').onclick=()=>{if(!contentDirty()&&!serverConflict)publishModal.hidden=false};document.querySelector('#cancel-publish').onclick=()=>publishModal.hidden=true;document.querySelector('#confirm-publish').onclick=async()=>{publishModal.hidden=true;await publishServer()};document.querySelector('#load-latest').onclick=()=>{if(serverConflict)conflictModal.hidden=false};document.querySelector('#cancel-conflict').onclick=()=>conflictModal.hidden=true;document.querySelector('#confirm-conflict').onclick=async()=>{conflictModal.hidden=true;await loadLatest()};document.querySelector('#preview').onclick=()=>window.open('/admin/preview.php','_blank','noopener');
// The iframe reports coordinates in its own viewport; clip every overlay to the visible canvas.
function geometry(element){const host=frame.getBoundingClientRect(),rect=element.getBoundingClientRect();return{x:host.left+rect.left,y:host.top+rect.top,width:rect.width,height:rect.height}}
function canvasBounds(){const canvas=document.querySelector('.canvas').getBoundingClientRect(),host=frame.getBoundingClientRect();return{left:Math.max(canvas.left,host.left),top:Math.max(canvas.top,host.top),right:Math.min(canvas.right,host.right),bottom:Math.min(canvas.bottom,host.bottom)}}
function clipRect(rect,element=null){const limit=canvasBounds(),excludePublicTopbar=element?.hasAttribute('data-editable-video')||element?.matches('form.interest-form'),publicBar=excludePublicTopbar?frame.contentDocument?.querySelector('.topbar')?.getBoundingClientRect().bottom||0:0,left=Math.max(rect.x,limit.left),top=Math.max(rect.y,limit.top,frame.getBoundingClientRect().top+publicBar),right=Math.min(rect.x+rect.width,limit.right),bottom=Math.min(rect.y+rect.height,limit.bottom);return right>left&&bottom>top?{x:left,y:top,width:right-left,height:bottom-top}:null}
function visible(rect){return !!clipRect(rect)}
function box(element,label){overlay.replaceChildren();const rect=clipRect(geometry(element),element);if(!rect)return null;const border=document.createElement('div'),tag=document.createElement('div');border.className='selection-box';border.style.cssText=`left:${rect.x}px;top:${rect.y}px;width:${rect.width}px;height:${rect.height}px`;tag.className='overlay-label';tag.textContent=label;tag.style.cssText=`left:${rect.x}px;top:${element.matches('form.interest-form')?rect.y+4:Math.max(canvasBounds().top,rect.y-18)}px`;overlay.append(border,tag);return rect}
function toolbar(rect,html){if(!rect)return null;const bar=document.createElement('div'),limit=canvasBounds();bar.className='overlay-toolbar';bar.style.visibility='hidden';bar.innerHTML=html;overlay.append(bar);const width=bar.offsetWidth||250,height=bar.offsetHeight||34,left=Math.max(limit.left+8,Math.min(rect.x,limit.right-width-8)),above=rect.y-height-8,below=rect.y+rect.height+8,top=selected.type==='video'?Math.min(rect.y+8,limit.bottom-height-8):selected.type==='form'?Math.min(rect.y+28,limit.bottom-height-8):(above>=limit.top+4?above:Math.min(below,limit.bottom-height-8));bar.style.left=`${left}px`;bar.style.top=`${top}px`;bar.style.visibility='visible';return bar}
document.querySelector('.canvas').addEventListener('scroll',refresh);
document.querySelectorAll('[data-viewport]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-viewport]').forEach(item=>item.classList.toggle('active',item===button));document.querySelector('.frame-shell').className=`frame-shell ${button.dataset.viewport==='desktop'?'':button.dataset.viewport}`;requestAnimationFrame(refresh)});
