const STORAGE_KEY='controlled-visual-editor-content-v1',frame=document.querySelector('#page-frame'),properties=document.querySelector('#properties'),overlay=document.querySelector('#editor-overlay-layer'),modal=document.querySelector('#media-modal'),mediaGrid=document.querySelector('#media-grid'),toast=document.querySelector('#toast');
let content,selected={type:'none'},editing=null,framing=null,history=[],historyIndex=-1,hookedDocument=null;
const clone=value=>JSON.parse(JSON.stringify(value)),typeFor=element=>element.hasAttribute('data-editable-image')?'image':element.hasAttribute('data-editable-video')?'video':element.hasAttribute('data-editable-text')?'text':element.hasAttribute('data-section')?'section':'none',keyFor=(type,element)=>element.dataset[`editable${type[0].toUpperCase()+type.slice(1)}`],sel=(type,key)=>`[data-editable-${type}="${CSS.escape(key)}"]`,clamp=(value,min=0,max=100)=>Math.max(min,Math.min(max,value));
function announce(message){toast.textContent=message;toast.classList.add('show');clearTimeout(announce.timer);announce.timer=setTimeout(()=>toast.classList.remove('show'),1600)}
function historyControls(){document.querySelector('#undo').disabled=historyIndex<1;document.querySelector('#redo').disabled=historyIndex>=history.length-1}function push(){history=history.slice(0,historyIndex+1);history.push(clone(content));historyIndex=history.length-1;historyControls()}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(content));announce('Conteúdo salvo no navegador.')}
function positionPart(value,index){const part=String(value||'50% 50%').split(' ')[index];const number=Number.parseFloat(part);return Number.isFinite(number)?clamp(number):50}
function imageFrame(value){return {...value,objectFit:value.objectFit||'cover',positionX:clamp(Number.isFinite(value.positionX)?value.positionX:positionPart(value.objectPosition,0)),positionY:clamp(Number.isFinite(value.positionY)?value.positionY:positionPart(value.objectPosition,1)),zoom:clamp(Number.isFinite(value.zoom)?value.zoom:1,1,3)}}
function applyImage(element,value){if(!element)return;const frameValue=imageFrame(value),contain=frameValue.objectFit==='contain',zoom=contain?1:frameValue.zoom;element.src=frameValue.src;element.alt=frameValue.alt||'';element.style.objectFit=frameValue.objectFit;element.style.objectPosition=`${frameValue.positionX}% ${frameValue.positionY}%`;element.style.transformOrigin=`${frameValue.positionX}% ${frameValue.positionY}%`;element.style.transform=zoom===1?'':`scale(${zoom})`;element.style.clipPath=zoom===1?'':'inset(0)';element.parentElement.style.overflow='clip'}
function apply(){const doc=frame.contentDocument;if(!doc||!content)return;Object.entries(content.texts||{}).forEach(([key,value])=>{const element=doc.querySelector(sel('text',key));if(element&&element!==editing)element.innerHTML=value.html});Object.entries(content.images||{}).forEach(([key,value])=>applyImage(doc.querySelector(sel('image',key)),value));(content.sections||[]).forEach(section=>{const element=doc.querySelector(`[data-section="${section.id}"]`);if(element)element.hidden=section.visible===false})}
function clear(){overlay.replaceChildren();selected={type:'none'};properties.classList.remove('open')}
function geometry(element){const host=frame.getBoundingClientRect(),rect=element.getBoundingClientRect();if(element.hasAttribute('data-editable-image')){const value=imageFrame(content.images[keyFor('image',element)]),zoom=value.objectFit==='contain'?1:value.zoom,width=rect.width/zoom,height=rect.height/zoom,left=rect.left+width*(zoom-1)*value.positionX/100,top=rect.top+height*(zoom-1)*value.positionY/100;return{x:host.left+left,y:host.top+top,width,height}}return{x:host.left+rect.left,y:host.top+rect.top,width:rect.width,height:rect.height}}
function visible(rect){return rect.y+rect.height>58&&rect.y<window.innerHeight&&rect.x+rect.width>0&&rect.x<window.innerWidth}
function box(element,label){overlay.replaceChildren();const rect=geometry(element);if(!visible(rect))return null;const border=document.createElement('div'),tag=document.createElement('div');border.className='selection-box';border.style.cssText=`left:${rect.x}px;top:${rect.y}px;width:${rect.width}px;height:${rect.height}px`;tag.className='overlay-label';tag.textContent=label;tag.style.cssText=`left:${rect.x}px;top:${Math.max(58,rect.y-18)}px`;overlay.append(border,tag);return rect}
function toolbar(rect,html){if(!rect)return null;const bar=document.createElement('div');bar.className='overlay-toolbar';bar.style.visibility='hidden';bar.innerHTML=html;overlay.append(bar);const width=bar.offsetWidth||250,height=bar.offsetHeight||34,limit=properties.classList.contains('open')?window.innerWidth-306:window.innerWidth,left=Math.max(8,Math.min(rect.x,limit-width-8)),above=rect.y-height-8,below=rect.y+rect.height+8;bar.style.left=`${left}px`;bar.style.top=`${above>=62?above:Math.min(below,window.innerHeight-height-8)}px`;bar.style.visibility='visible';return bar}
function select(element){if(framing&&framing.element!==element)cancelFraming();if(editing)finish(true);const type=typeFor(element);if(type==='none')return clear();selected={type,key:type==='section'?element.dataset.section:keyFor(type,element),element};const label=type==='section'?`Seção: ${element.dataset.section}`:type==='image'?'Imagem':type==='text'?'Texto':type;const rect=box(element,label);if(type==='image')renderImageTools(rect);if(type==='section')renderSectionTools(rect)}
function renderImageTools(rect){const bar=toolbar(rect,'<button data-a="replace">Substituir</button><button data-a="frame">Enquadrar</button><button data-a="properties">Propriedades</button><button data-a="remove">Remover</button>');if(!bar)return;bar.onclick=event=>{const action=event.target.dataset.a;if(action==='replace')openMedia();if(action==='frame')startFraming();if(action==='properties')imageProperties();if(action==='remove'){content.images[selected.key].src='';apply();push()}}}
function renderSectionTools(rect){const bar=toolbar(rect,'<button data-a="up">Mover para cima</button><button data-a="down">Mover para baixo</button><button data-a="hide">Ocultar</button>');if(!bar)return;bar.onclick=event=>{const action=event.target.dataset.a,sections=content.sections,index=sections.findIndex(section=>section.id===selected.key);if(action==='up'&&index>0)sections.splice(index-1,0,sections.splice(index,1)[0]);if(action==='down'&&index<sections.length-1)sections.splice(index+1,0,sections.splice(index,1)[0]);if(action==='hide')sections[index].visible=false;apply();push();clear()}}
function startFraming(){if(selected.type!=='image')return;properties.classList.remove('open');const value=content.images[selected.key];framing={key:selected.key,element:selected.element,original:clone(value),draft:imageFrame(clone(value))};renderFraming()}
function compactFraming(){return frame.parentElement.classList.contains('tablet')||frame.parentElement.classList.contains('mobile')||window.innerWidth<=800}
function renderFraming(){if(!framing)return;const rect=box(framing.element,'Imagem');if(!rect)return;const border=overlay.querySelector('.selection-box'),value=framing.draft; border.classList.add('framing-box');border.classList.toggle('contain-mode',value.objectFit==='contain');border.onpointerdown=startImageDrag;const focus=value.objectFit==='contain'?'Imagem inteira':`Foco ${Math.round(value.positionX)}/${Math.round(value.positionY)}`,bar=toolbar(rect,`<button data-frame="zoom-down" aria-label="zoom −">zoom −</button><input data-frame="zoom" aria-label="Controle de zoom" type="range" min="1" max="3" step="0.05" value="${value.zoom}"><button data-frame="zoom-up" aria-label="zoom +">zoom +</button><span class="framing-focus">${focus}</span><button data-frame="cover" ${value.objectFit==='cover'?'aria-pressed="true"':''}>Cover</button><button data-frame="contain" ${value.objectFit==='contain'?'aria-pressed="true"':''}>Contain</button><button data-frame="restore">Restaurar</button><button data-frame="cancel">Cancelar</button><button data-frame="apply">Aplicar</button>`);if(!bar)return;bar.classList.add('framing-toolbar');if(compactFraming()){const host=frame.getBoundingClientRect(),width=Math.min(host.width-16,window.innerWidth-16);bar.style.width=`${Math.max(0,width)}px`;bar.style.left=`${Math.max(8,Math.min(host.left+8,window.innerWidth-width-8))}px`;bar.style.top='auto';bar.style.bottom='8px'}bar.oninput=event=>{if(event.target.dataset.frame==='zoom'){framing.draft.zoom=Number(event.target.value);applyImage(framing.element,framing.draft)}};bar.onclick=event=>{const action=event.target.dataset.frame;if(!action)return;if(action==='zoom-down'){framing.draft.zoom=clamp(framing.draft.zoom-.1,1,3);renderFraming();applyImage(framing.element,framing.draft)}if(action==='zoom-up'){framing.draft.zoom=clamp(framing.draft.zoom+.1,1,3);renderFraming();applyImage(framing.element,framing.draft)}if(action==='cover'||action==='contain'){framing.draft.objectFit=action;renderFraming();applyImage(framing.element,framing.draft)}if(action==='restore'){framing.draft=imageFrame(clone(framing.original));renderFraming();applyImage(framing.element,framing.draft)}if(action==='cancel')cancelFraming();if(action==='apply')applyFraming()}}
function startImageDrag(event){if(!framing||framing.draft.objectFit==='contain')return;event.preventDefault();const target=event.currentTarget,startX=event.clientX,startY=event.clientY,originX=framing.draft.positionX,originY=framing.draft.positionY,rect=target.getBoundingClientRect();target.setPointerCapture(event.pointerId);target.classList.add('is-dragging');const move=pointer=>{framing.draft.positionX=clamp(originX-(pointer.clientX-startX)/rect.width*100);framing.draft.positionY=clamp(originY-(pointer.clientY-startY)/rect.height*100);applyImage(framing.element,framing.draft)};const finish=()=>{target.classList.remove('is-dragging');target.removeEventListener('pointermove',move);target.removeEventListener('pointerup',finish);target.removeEventListener('pointercancel',finish)};target.addEventListener('pointermove',move);target.addEventListener('pointerup',finish);target.addEventListener('pointercancel',finish)}
function cancelFraming(){if(!framing)return;const active=framing.element,original=framing.original;framing=null;applyImage(active,original);select(active)}
function applyFraming(){if(!framing)return;const active=framing.element,value=imageFrame(framing.draft);Object.assign(content.images[framing.key],value,{objectPosition:`${value.positionX}% ${value.positionY}%`});framing=null;apply();push();select(active);announce('Enquadramento aplicado.')}
function finish(keep=true){if(!editing)return;const element=editing,key=element.dataset.editableText;editing=null;element.contentEditable='false';if(content.texts[key].html!==element.innerHTML){content.texts[key].html=element.innerHTML;push()}if(keep)select(element)}
function cancelEdit(){if(!editing)return;const element=editing;element.innerHTML=content.texts[element.dataset.editableText].html;editing=null;element.contentEditable='false';select(element)}
function edit(element,event){editing=element;element.contentEditable='true';element.focus();const doc=element.ownerDocument,selection=doc.getSelection();selection.removeAllRanges();let range=doc.caretRangeFromPoint?.(event.clientX,event.clientY);if(!range||!element.contains(range.startContainer)){range=doc.createRange();range.selectNodeContents(element);range.collapse(false)}selection.addRange(range);const rect=box(element,'Texto'),bar=toolbar(rect,'<button data-f="bold">Negrito</button><button data-f="italic">Itálico</button><button data-f="link">Link</button><button data-f="removeFormat">Limpar</button><button data-f="done">Concluir</button>');if(bar)bar.onclick=event=>{const format=event.target.dataset.f;if(format==='done')finish();else if(format==='link'){const url=prompt('URL');if(url)frame.contentDocument.execCommand('createLink',false,url)}else frame.contentDocument.execCommand(format,false,null)}}
function imageProperties(){const value=content.images[selected.key];properties.classList.add('open');properties.innerHTML=`<button id="close-properties" class="icon-button">×</button><p class="eyebrow">Imagem</p><h2>Propriedades</h2><div class="property-block"><label>Texto alternativo<input id="image-alt" value="${String(value.alt||'').replaceAll('"','&quot;')}"></label><label>Fit<select id="image-fit"><option ${value.objectFit==='cover'?'selected':''}>cover</option><option ${value.objectFit==='contain'?'selected':''}>contain</option></select></label></div>`;properties.querySelector('#close-properties').onclick=()=>properties.classList.remove('open');properties.querySelector('#image-alt').onchange=event=>{value.alt=event.target.value;apply();push()};properties.querySelector('#image-fit').onchange=event=>{value.objectFit=event.target.value;apply();push()}}
function openMedia(){mediaGrid.innerHTML=MediaLibrary.images.map((item,index)=>`<button class="media-item" data-i="${index}"><img src="${item.src}"><span>${item.label}</span></button>`).join('');mediaGrid.querySelectorAll('button').forEach(button=>button.onclick=()=>{content.images[selected.key].src=MediaLibrary.images[+button.dataset.i].src;apply();push();modal.hidden=true});modal.hidden=false}
function refresh(){if(!selected.element)return;if(framing)return renderFraming();const active=selected.element;if(editing){const rect=box(active,'Texto');toolbar(rect,'<button data-f="bold">Negrito</button><button data-f="italic">Itálico</button><button data-f="link">Link</button><button data-f="removeFormat">Limpar</button><button data-f="done">Concluir</button>')}else select(active)}
function hook(){const doc=frame.contentDocument;doc.addEventListener('click',event=>{const section=event.target.closest('[data-section]'),element=event.target.closest('[data-editable-text],[data-editable-image],[data-editable-video]');if(!element&&!section)return clear();event.preventDefault();select(element||section)});doc.addEventListener('dblclick',event=>{const element=event.target.closest('[data-editable-text]');if(element){event.preventDefault();event.stopPropagation();select(element);edit(element,event)}});doc.addEventListener('mousemove',event=>{const section=event.target.closest('[data-section]');if(section&&selected.type==='none'){const rect=geometry(section);if(!visible(rect))return;overlay.replaceChildren();const tag=document.createElement('div');tag.className='overlay-label';tag.textContent=`Seção: ${section.dataset.section}`;tag.style.cssText=`left:${rect.x}px;top:${rect.y}px`;overlay.append(tag)}});doc.defaultView.addEventListener('scroll',refresh);doc.defaultView.addEventListener('resize',refresh);window.addEventListener('resize',refresh);doc.querySelectorAll('a,button').forEach(element=>element.addEventListener('click',event=>event.preventDefault()))}
document.querySelectorAll('[data-viewport]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-viewport]').forEach(item=>item.classList.toggle('active',item===button));document.querySelector('.frame-shell').className=`frame-shell ${button.dataset.viewport==='desktop'?'':button.dataset.viewport}`;clear()});document.querySelector('#save').onclick=save;document.querySelector('#restore').onclick=()=>{try{content=JSON.parse(localStorage.getItem(STORAGE_KEY));apply();push();clear();announce('Conteúdo restaurado.')}catch{announce('Não há conteúdo salvo para restaurar.') }};document.querySelector('#preview').onclick=()=>{save();window.open('../preview/','_blank','noopener')};document.querySelector('#undo').onclick=()=>{if(historyIndex>0){content=clone(history[--historyIndex]);apply();historyControls()}};document.querySelector('#redo').onclick=()=>{if(historyIndex<history.length-1){content=clone(history[++historyIndex]);apply();historyControls()}};document.querySelector('#close-media').onclick=()=>modal.hidden=true;
document.addEventListener('keydown',event=>{if(framing){const step=event.shiftKey?8:1;if(event.key==='Escape'){event.preventDefault();cancelFraming()}else if(event.key==='Enter'){event.preventDefault();applyFraming()}else if(event.key==='ArrowLeft'||event.key==='ArrowRight'||event.key==='ArrowUp'||event.key==='ArrowDown'){event.preventDefault();if(event.key==='ArrowLeft')framing.draft.positionX=clamp(framing.draft.positionX-step);if(event.key==='ArrowRight')framing.draft.positionX=clamp(framing.draft.positionX+step);if(event.key==='ArrowUp')framing.draft.positionY=clamp(framing.draft.positionY-step);if(event.key==='ArrowDown')framing.draft.positionY=clamp(framing.draft.positionY+step);applyImage(framing.element,framing.draft)}return}if(event.key==='Escape'){cancelEdit();if(!editing)clear()}if((event.ctrlKey||event.metaKey)&&event.key==='Enter')finish();if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();save()}});
async function initializeFrame(){const doc=frame.contentDocument;if(!doc||hookedDocument===doc)return;hookedDocument=doc;if(!content){try{content=JSON.parse(localStorage.getItem(STORAGE_KEY))}catch{}if(!content)content=await (await fetch('../data/default-content.json')).json();push()}apply();hook()}
frame.addEventListener('load',initializeFrame);if(frame.contentDocument?.readyState==='complete')initializeFrame();
