(() => {
  const core = window.EditorCore, list = document.querySelector('#sections-list'), props = document.querySelector('#properties');
  const names = { hero:'Hero', workshop:'Workshop', camera:'Câmera', process:'Processo', format:'Formato', about:'Fotógrafo', 'interest-form':'Formulário de interesse' };
  const types = ['text','email','tel','number','textarea','select','radio','checkbox','consent'];
  let sectionId = null, fieldId = null, dragId = null;
  const esc = value => String(value || '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const ensure = state => { state.schemaVersion = 1; state.sections = (state.sections || []).map((item, index) => ({ id:item.id, visible:item.visible !== false, order:index + 1 })); state.forms ||= {}; Object.values(state.forms).forEach(form => form.fields ||= []); };
  const current = () => { if (!core.content) return null; ensure(core.content); return core.content; };
  const move = (items, from, to) => { if (to < 0 || to >= items.length) return; items.splice(to, 0, items.splice(from, 1)[0]); };
  const commit = message => { core.apply(); renderSections(); core.commit(message); };
  function apply(doc, state) {
    ensure(state);
    const main = doc.querySelector('main');
    state.sections.forEach(section => { const el = doc.querySelector(`[data-section="${section.id}"]`); if (!el) return; main.append(el); const hidden = !section.visible; const old = doc.querySelector(`[data-hidden-section="${section.id}"]`); if (old) old.remove(); el.hidden = hidden; if(hidden && doc.defaultView.location.search.includes('editor')) { const band=doc.createElement('button'); band.type='button'; band.dataset.hiddenSection=section.id; band.textContent=`Seção oculta: ${names[section.id]||section.id} — mostrar`; band.style.cssText='display:block;width:100%;padding:14px;border:1px dashed #186f4d;background:#edf4ef;color:#186f4d;font:12px monospace;text-align:left;cursor:pointer'; band.onclick=()=>{const target=current().sections.find(item=>item.id===section.id);target.visible=true;commit('Seção restaurada.');}; el.before(band); } });
    Object.entries(state.forms).forEach(([id, form]) => renderForm(doc.querySelector(`[data-editable-form="${id}"]`), form));
  }
  function renderForm(form, data) {
    if (!form) return; form.noValidate = true; form.innerHTML = data.fields.map(field => {
      const id = `form-${field.id}`, label = `<span>${esc(field.label)}${field.required ? ' *' : ''}</span>`, help = field.help ? `<small>${esc(field.help)}</small>` : '';
      if (field.type === 'textarea') return `<label>${label}<textarea id="${id}" name="${esc(field.id)}" placeholder="${esc(field.placeholder)}" ${field.required?'required':''}></textarea>${help}</label>`;
      if (field.type === 'select') return `<label>${label}<select id="${id}" name="${esc(field.id)}" ${field.required?'required':''}><option value="">Selecione</option>${(field.options||[]).map(option=>`<option value="${esc(option.value)}">${esc(option.label)}</option>`).join('')}</select>${help}</label>`;
      if (field.type === 'radio') return `<fieldset><legend>${esc(field.label)}</legend>${(field.options||[]).map((option,index)=>`<label><input type="radio" name="${esc(field.id)}" value="${esc(option.value)}" ${field.required&&index===0?'required':''}>${esc(option.label)}</label>`).join('')}${help}</fieldset>`;
      if (field.type === 'checkbox' || field.type === 'consent') return `<label class="consent"><input id="${id}" type="checkbox" name="${esc(field.id)}" ${field.required?'required':''}><span>${esc(field.label)}</span>${help}</label>`;
      return `<label>${label}<input id="${id}" type="${field.type}" name="${esc(field.id)}" placeholder="${esc(field.placeholder)}" ${field.required?'required':''}>${help}</label>`;
    }).join('') + `<button class="button" type="submit">${esc(data.submitLabel || 'Enviar')}</button><p class="form-status"></p>`;
    form.onsubmit = event => { event.preventDefault(); form.querySelector('.form-status').textContent = data.successMessage || 'Formulário de demonstração.'; };
  }
  function renderSections() {
    const state = current(); if (!state) return; list.innerHTML = state.sections.map((section,index) => `<div class="section-row ${sectionId===section.id?'selected':''} ${section.visible?'':'off'}" draggable="true" data-section-id="${section.id}"><button title="Mostrar ou ocultar">${section.visible?'◉':'○'}</button><div><strong>${names[section.id]||section.id}</strong><small>${section.visible?section.id:`${section.id} · Oculta`}</small></div><span><button data-up="${index}" title="Mover para cima">↑</button><button data-down="${index}" title="Mover para baixo">↓</button></span></div>`).join('');
    list.querySelectorAll('.section-row').forEach(row => { row.onclick = event => { if (event.target.tagName === 'BUTTON') return; selectSection(row.dataset.sectionId); }; row.ondragstart = () => dragId = row.dataset.sectionId; row.ondragover = event => event.preventDefault(); row.ondrop = event => { event.preventDefault(); const items=current().sections, from=items.findIndex(x=>x.id===dragId), to=items.findIndex(x=>x.id===row.dataset.sectionId); if(from!==to){move(items,from,to);commit('Seção reordenada.');} }; });
    list.querySelectorAll('[data-up]').forEach(button => button.onclick = () => { move(current().sections,Number(button.dataset.up),Number(button.dataset.up)-1);commit('Seção movida.'); });
    list.querySelectorAll('[data-down]').forEach(button => button.onclick = () => { move(current().sections,Number(button.dataset.down),Number(button.dataset.down)+1);commit('Seção movida.'); });
    list.querySelectorAll('.section-row>button').forEach(button => button.onclick = () => { const id=button.parentElement.dataset.sectionId, section=current().sections.find(x=>x.id===id); if(section.visible && current().sections.filter(x=>x.visible).length===1){core.announce('Mantenha ao menos uma seção visível.');return;} section.visible=!section.visible;commit('Visibilidade atualizada.'); });
  }
  function selectSection(id) { sectionId=id; renderSections(); if(id==='interest-form') renderFormPanel(); const el=core.frame.contentDocument.querySelector(`[data-section="${id}"]`); if(el){el.scrollIntoView({behavior:'smooth',block:'start'}); el.style.outline='2px solid #186f4d'; setTimeout(()=>el.style.outline='',1300);} }
  function fieldById() { return current().forms['interest-form'].fields.find(field => field.id === fieldId); }
  function uniqueId(base='field') { const ids=new Set(current().forms['interest-form'].fields.map(field=>field.id)); let n=1,id=base.replace(/[^a-z0-9_-]/gi,'-').toLowerCase()||'field'; while(ids.has(id)) id=`${base}-${n++}`; return id; }
  function renderFormPanel() {
    const form=current().forms['interest-form']; if(!form) return; const field=fieldById();
    props.innerHTML = `<p class="eyebrow">Formulário editável</p><h2>Interest form</h2><div class="property-block"><label>Texto introdutório<textarea id="form-intro">${esc(form.intro)}</textarea></label><label>Texto do botão<input id="form-submit" value="${esc(form.submitLabel)}"></label><label>Mensagem de sucesso<textarea id="form-success">${esc(form.successMessage)}</textarea></label></div><div class="property-block"><button id="add-field">Adicionar campo</button>${form.fields.map((item,index)=>`<div class="field-row ${item.id===fieldId?'selected':''}" data-field="${item.id}">${esc(item.label)} <small>${item.id}</small> <button data-fup="${index}">↑</button><button data-fdown="${index}">↓</button></div>`).join('')}</div>${field?`<div class="property-block"><label>ID<input readonly value="${esc(field.id)}"></label><label>Rótulo<input id="field-label" value="${esc(field.label)}"></label><label>Placeholder<input id="field-placeholder" value="${esc(field.placeholder)}"></label><label>Ajuda<textarea id="field-help">${esc(field.help)}</textarea></label><label>Tipo<select id="field-type">${types.map(type=>`<option ${type===field.type?'selected':''}>${type}</option>`).join('')}</select></label><label class="check"><input id="field-required" type="checkbox" ${field.required?'checked':''}>Obrigatório</label><button id="duplicate-field">Duplicar campo</button><button class="danger" id="delete-field">Excluir campo</button>${['select','radio'].includes(field.type)?`<h3>Opções</h3><button id="add-option">Adicionar opção</button>${(field.options||[]).map((option,index)=>`<div><input data-option="${index}" value="${esc(option.label)}"><input data-option-value="${index}" value="${esc(option.value)}"><button data-oup="${index}">↑</button><button data-odown="${index}">↓</button><button data-odel="${index}">×</button></div>`).join('')}`:''}</div>`:''}`;
    ['intro','submit','success'].forEach(key => props.querySelector(`#form-${key}`).onchange = event => { form[key === 'submit' ? 'submitLabel' : key === 'success' ? 'successMessage' : 'intro'] = event.target.value; commit('Formulário atualizado.'); });
    props.querySelector('#add-field').onclick=()=>{const id=uniqueId();form.fields.push({id,type:'text',label:'Novo campo',placeholder:'',help:'',required:false,options:[]});fieldId=id;commit('Campo adicionado.');renderFormPanel();};
    props.querySelectorAll('[data-field]').forEach(row=>row.onclick=()=>{fieldId=row.dataset.field;renderFormPanel();});
    props.querySelectorAll('[data-fup]').forEach(button=>button.onclick=event=>{event.stopPropagation();move(form.fields,Number(button.dataset.fup),Number(button.dataset.fup)-1);commit('Campo movido.');renderFormPanel();}); props.querySelectorAll('[data-fdown]').forEach(button=>button.onclick=event=>{event.stopPropagation();move(form.fields,Number(button.dataset.fdown),Number(button.dataset.fdown)+1);commit('Campo movido.');renderFormPanel();});
    if(!field)return; ['label','placeholder','help','type'].forEach(key=>props.querySelector(`#field-${key}`).onchange=event=>{field[key]=event.target.value; if(key==='type'&&!['select','radio'].includes(field.type))field.options=[]; if(['select','radio'].includes(field.type)&&!field.options.length)field.options=[{value:'option-1',label:'Opção 1'}];commit('Campo atualizado.');renderFormPanel();}); props.querySelector('#field-required').onchange=event=>{field.required=event.target.checked;commit('Obrigatoriedade atualizada.');}; props.querySelector('#duplicate-field').onclick=()=>{const copy=JSON.parse(JSON.stringify(field));copy.id=uniqueId(`${field.id}-copy`);form.fields.splice(form.fields.indexOf(field)+1,0,copy);fieldId=copy.id;commit('Campo duplicado.');renderFormPanel();}; props.querySelector('#delete-field').onclick=()=>{form.fields.splice(form.fields.indexOf(field),1);fieldId=null;commit('Campo removido.');renderFormPanel();};
    if(['select','radio'].includes(field.type)){props.querySelector('#add-option').onclick=()=>{field.options.push({value:`option-${field.options.length+1}`,label:`Opção ${field.options.length+1}`});commit('Opção adicionada.');renderFormPanel();}; props.querySelectorAll('[data-option]').forEach(input=>input.onchange=()=>{const option=field.options[Number(input.dataset.option)];option.label=input.value;option.value=uniqueId(input.value);commit('Opção atualizada.');}); props.querySelectorAll('[data-oup]').forEach(button=>button.onclick=()=>{move(field.options,Number(button.dataset.oup),Number(button.dataset.oup)-1);commit('Opção movida.');renderFormPanel();}); props.querySelectorAll('[data-odown]').forEach(button=>button.onclick=()=>{move(field.options,Number(button.dataset.odown),Number(button.dataset.odown)+1);commit('Opção movida.');renderFormPanel();}); props.querySelectorAll('[data-odel]').forEach(button=>button.onclick=()=>{field.options.splice(Number(button.dataset.odel),1);commit('Opção removida.');renderFormPanel();});}
  }
  function valid(state) { return state && state.schemaVersion === 1 && state.texts && state.images && state.videos && Array.isArray(state.sections) && state.forms; }
  function exportContent(){const blob=new Blob([JSON.stringify(current(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`workshop-content-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);}
  document.querySelector('#export-content').onclick=exportContent; document.querySelector('#import-content').onclick=()=>document.querySelector('#import-file').click(); document.querySelector('#import-file').onchange=event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{let next;try{next=JSON.parse(reader.result);}catch{core.announce('JSON inválido. O estado atual foi preservado.');return;}if(!valid(next)){core.announce('Versão incompatível ou estrutura inválida.');return;}if(confirm(`Importar conteúdo: ${next.sections.length} seções e ${Object.keys(next.forms).length} formulário(s)?`)){ensure(next);core.replace(next,'Conteúdo importado.');renderSections();}};reader.readAsText(file);};
  let pendingImport;
  const importFile = document.querySelector('#import-file'), importModal = document.querySelector('#import-modal');
  document.querySelector('#import-content').onclick=()=>importFile.click();
  importFile.onchange=event=>{const file=event.target.files[0]; if(!file)return; const reader=new FileReader(); reader.onload=()=>{let next;try{next=JSON.parse(reader.result);}catch{props.innerHTML='<p class="eyebrow">Importação</p><h2>JSON inválido</h2><div class="property-block">O arquivo não foi aplicado. O conteúdo atual foi preservado.</div>';return;} if(!valid(next)){props.innerHTML='<p class="eyebrow">Importação</p><h2>Arquivo incompatível</h2><div class="property-block">schemaVersion ausente, incompatível ou estrutura incompleta. O conteúdo atual foi preservado.</div>';return;} pendingImport=next; document.querySelector('#import-summary').innerHTML=`<p><strong>${esc(file.name)}</strong></p><p>schemaVersion: ${next.schemaVersion}</p><p>Textos: ${Object.keys(next.texts).length} · Imagens: ${Object.keys(next.images).length} · Vídeos: ${Object.keys(next.videos).length}</p><p>Seções: ${next.sections.length} · Formulários: ${Object.keys(next.forms).length}</p><p>O conteúdo atual será substituído somente após confirmar.</p>`; importModal.hidden=false;}; reader.readAsText(file);};
  document.querySelector('#cancel-import').onclick=()=>{pendingImport=null;importModal.hidden=true;}; document.querySelector('#confirm-import').onclick=()=>{if(!pendingImport)return;ensure(pendingImport);core.replace(pendingImport,'Conteúdo importado.');renderSections();importModal.hidden=true;pendingImport=null;};
  document.addEventListener('DOMContentLoaded',()=>{ document.head.insertAdjacentHTML('beforeend','<style>.workspace{grid-template-columns:250px minmax(0,1fr) 296px}.sections-panel{overflow:auto;padding:18px;background:#fff;border-right:1px solid #d4d8d5}.sections-panel h2{margin:0 0 14px}.section-row{display:grid;grid-template-columns:18px 1fr auto;gap:6px;padding:9px 2px;border-bottom:1px solid #d4d8d5;cursor:grab}.section-row.selected{background:#edf4ef}.section-row.off{opacity:.45}.section-row small{display:block;color:#656d6b}.section-row button,.panel-actions button{border:1px solid #d4d8d5;background:#f5f6f4}.panel-actions{display:grid;gap:6px;margin-top:16px}.field-row{padding:8px;border-bottom:1px solid #d4d8d5;cursor:pointer}.field-row.selected{background:#edf4ef}.property-block textarea{width:100%;min-height:68px}</style>'); setTimeout(renderSections,300); });
  function bindFrame(){renderSections();const doc=core.frame.contentDocument;if(doc.__stage2Bound)return;doc.__stage2Bound=true;doc.addEventListener('click',event=>{const section=event.target.closest('[data-section]'),form=event.target.closest('[data-editable-form]');if(section)selectSection(section.dataset.section);if(form){event.preventDefault();fieldId=null;renderFormPanel();}});}
  core.frame.addEventListener('load',bindFrame); setTimeout(bindFrame,500);
  function selectForm(formElement){ sectionId = formElement.closest('[data-section]')?.dataset.section || 'interest-form'; formElement.style.outline='2px solid #186f4d'; setTimeout(()=>formElement.style.outline='',1300); renderSections(); fieldId=null; renderFormPanel(); }
  window.EditorStage2={apply,selectForm};
})();
