const STORAGE_KEY = 'controlled-visual-editor-content-v1';
const frame = document.querySelector('#preview-frame');
const clean = value => value === 'auto' ? null : value;
function apply(doc, content) {
  if (!content) return;
  doc.documentElement.toggleAttribute('data-theme', false);
  const theme = clean(content.theme || 'auto'); if (theme) doc.documentElement.setAttribute('data-theme', theme);
  doc.querySelectorAll('[data-theme-value]').forEach(button => button.setAttribute('aria-pressed', String(button.dataset.themeValue === (content.theme || 'auto'))));
  (content.sections || []).forEach(section => { const el = doc.querySelector(`[data-section="${section.id}"]`); if (el) el.hidden = section.visible === false; });
  const main = doc.querySelector('main'); (content.sections || []).forEach(section => { const el = doc.querySelector(`[data-section="${section.id}"]`); if (el) main.append(el); });
  Object.entries(content.forms || {}).forEach(([id, form]) => { const el = doc.querySelector(`[data-editable-form="${id}"]`); if (!el) return; el.innerHTML = (form.fields || []).map(field => { const key = `preview-${field.id}`, label = `<span>${field.label}${field.required?' *':''}</span>`; if(field.type==='textarea') return `<label>${label}<textarea id="${key}" placeholder="${field.placeholder||''}" ${field.required?'required':''}></textarea>${field.help?`<small>${field.help}</small>`:''}</label>`; if(field.type==='select') return `<label>${label}<select id="${key}" ${field.required?'required':''}>${(field.options||[]).map(option=>`<option value="${option.value}">${option.label}</option>`).join('')}</select></label>`; if(field.type==='radio') return `<fieldset><legend>${field.label}</legend>${(field.options||[]).map(option=>`<label><input type="radio" name="${field.id}" value="${option.value}">${option.label}</label>`).join('')}</fieldset>`; if(field.type==='checkbox'||field.type==='consent') return `<label class="consent"><input id="${key}" type="checkbox" ${field.required?'required':''}><span>${field.label}</span></label>`; return `<label>${label}<input id="${key}" type="${field.type}" placeholder="${field.placeholder||''}" ${field.required?'required':''}>${field.help?`<small>${field.help}</small>`:''}</label>`; }).join('') + `<button class="button" type="submit">${form.submitLabel||'Enviar'}</button><p class="form-status"></p>`; el.onsubmit = event => event.preventDefault(); });
  Object.entries(content.texts || {}).forEach(([key, value]) => { const el = doc.querySelector(`[data-editable-text="${key}"]`); if (el) el.innerHTML = value.html; });
  Object.entries(content.images || {}).forEach(([key, value]) => { const el = doc.querySelector(`[data-editable-image="${key}"]`); if (el) { const x = Number.isFinite(value.positionX) ? value.positionX : Number.parseFloat((value.objectPosition || '50% 50%').split(' ')[0]) || 50, y = Number.isFinite(value.positionY) ? value.positionY : Number.parseFloat((value.objectPosition || '50% 50%').split(' ')[1]) || 50, zoom = Number.isFinite(value.zoom) ? value.zoom : 1; el.src = value.src; el.alt = value.alt || ''; el.style.objectFit = value.objectFit || ''; el.style.objectPosition = `${x}% ${y}%`; el.style.transformOrigin = `${x}% ${y}%`; el.style.transform = zoom === 1 ? '' : `scale(${zoom})`; el.style.clipPath = zoom === 1 ? '' : 'inset(0)'; } });
  Object.entries(content.videos || {}).forEach(([key, value]) => { const el = doc.querySelector(`[data-editable-video="${key}"]`); if (!el) return; if (el.tagName === 'VIDEO') { el.querySelector('source')?.setAttribute('src', value.src); el.poster = value.poster || ''; el.controls = !!value.controls; el.autoplay = !!value.autoplay; el.muted = !!value.muted; el.loop = !!value.loop; el.load(); } else if (value.src) el.innerHTML = `<video ${value.controls ? 'controls' : ''} ${value.muted ? 'muted' : ''} ${value.loop ? 'loop' : ''} ${value.autoplay ? 'autoplay' : ''} playsinline poster="${value.poster || ''}"><source src="${value.src}" type="video/mp4"></video>`; });
}
frame.addEventListener('load', () => { try { apply(frame.contentDocument, JSON.parse(localStorage.getItem(STORAGE_KEY))); } catch {} });
