<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/admin_shell.php';security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];$locale=normalize_public_locale($_GET['lang']??$_POST['locale']??PUBLIC_LOCALE_PT_BR)??PUBLIC_LOCALE_PT_BR;
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('cms-blocks',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}
    $action=(string)($_POST['action']??'');$id=(int)($_POST['block_id']??0);
    try{if($action==='rename')cms_block_rename($db,$activityId,$id,(string)($_POST['name']??''));if($action==='delete')cms_block_delete($db,$activityId,$id);$_SESSION['admin_notice']='Blocos atualizados.';}catch(Throwable $e){$_SESSION['admin_notice']=$e->getMessage();}
    header('Location: /admin/blocks.php?activity='.$activityId.'&lang='.rawurlencode(public_locale_query($locale)));exit;
}
$blocks=cms_blocks($db,$activityId,$locale);$notice=$_SESSION['admin_notice']??null;unset($_SESSION['admin_notice']);
admin_shell_start('blocks','Blocos reutilizáveis',$state);?>
<?php if($notice):?><div class="admin-notice"><?=h((string)$notice)?></div><?php endif;?>
<section class="overview-hero"><div><p class="admin-kicker">Biblioteca de componentes</p><h2>Seções salvas para reutilizar</h2><p>Salve qualquer seção do editor visual e insira a mesma composição em outras páginas. A inserção cria uma cópia independente, que pode ser adaptada sem modificar o modelo salvo.</p></div><div class="hero-actions"><a class="admin-button" href="/admin/blocks.php?activity=<?=$activityId?>&lang=pt-br"<?=$locale===PUBLIC_LOCALE_PT_BR?' aria-current="page"':''?>>PT</a><a class="admin-button" href="/admin/blocks.php?activity=<?=$activityId?>&lang=en"<?=$locale===PUBLIC_LOCALE_EN?' aria-current="page"':''?>>EN</a></div></section>
<?php if(!$blocks):?><div class="admin-empty"><h2>Nenhum bloco salvo</h2><p>No editor de páginas, selecione uma seção e use “Salvar bloco”.</p></div><?php else:?><section class="overview-grid"><?php foreach($blocks as $block):?><article class="overview-card"><p class="admin-kicker"><?=h($block['category'])?></p><h2><?=h($block['name'])?></h2><p>Atualizado em <?=h($block['updated_at'])?></p><details><summary>Conteúdo</summary><div class="block-code-preview"><?=h(mb_strimwidth(trim(preg_replace('/\s+/u',' ',strip_tags((string)$block['html']))??''),0,500,'…'))?></div></details><form method="post" class="stack-form"><input type="hidden" name="_csrf" value="<?=h(csrf_token('cms-blocks'))?>"><input type="hidden" name="locale" value="<?=h($locale)?>"><input type="hidden" name="block_id" value="<?=(int)$block['id']?>"><label>Nome<input name="name" value="<?=h((string)$block['name'])?>"></label><div class="admin-card-actions"><button class="link-button" name="action" value="rename">Renomear</button><button class="link-button danger" name="action" value="delete" data-confirm="Excluir este bloco reutilizável?">Excluir</button></div></form></article><?php endforeach;?></section><?php endif;?>
<?php admin_shell_end();
