<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];
$courses=course_list($db,$activityId);$courseId=max(0,(int)($_GET['course']??$_POST['course_id']??0));$course=$courseId>0?course_by_id($db,$courseId):null;if(!$course||(int)$course['activity_id']!==$activityId){if(count($courses)===1){header('Location: '.admin_course_url($activityId,(int)$courses[0]['id'],'cohorts'),true,302);exit;}header('Location: /admin/courses.php?activity='.$activityId,true,302);exit;}
$cohortId=max(0,(int)($_GET['cohort']??$_POST['cohort_id']??0));$cohort=$cohortId>0?admin_course_cohort($db,$courseId,$cohortId,true):null;if($cohortId>0&&!$cohort){$_SESSION['admin_cohorts_notice']='A turma solicitada não existe ou não pertence a este curso.';header('Location: '.admin_course_url($activityId,$courseId,'cohorts'),true,302);exit;}
$q=trim((string)($_GET['q']??''));$status=(string)($_GET['status']??'active');if(!in_array($status,['active','archived','all'],true))$status='active';$showNew=!empty($_GET['new']);$showEdit=!empty($_GET['edit']);
function cohort_workspace_list_url(int $activityId,int $courseId,string $q='',string $status='active'): string {$args=['activity'=>$activityId,'course'=>$courseId];if($q!=='')$args['q']=$q;if($status!=='active')$args['status']=$status;return '/admin/cohorts.php?'.http_build_query($args);}
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('cohorts-admin',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}$action=(string)($_POST['action']??'');
    try{
        if($action==='create'){$created=course_create_cohort_for_course($db,$courseId,(string)($_POST['title']??''),'',(string)($_POST['starts_at']??'')?:null,(string)($_POST['ends_at']??'')?:null);$cohortId=(int)$created['id'];$_SESSION['admin_cohorts_notice']='Turma criada.';}
        elseif($action==='update'){$cohortId=(int)($_POST['cohort_id']??0);admin_course_update_cohort($db,$courseId,$cohortId,$_POST);$_SESSION['admin_cohorts_notice']='Turma atualizada.';}
        elseif($action==='archive'){$cohortId=(int)($_POST['cohort_id']??0);admin_course_set_cohort_archived($db,$courseId,$cohortId,true);$_SESSION['admin_cohorts_notice']='Turma arquivada. Matrículas e histórico foram preservados.';}
        elseif($action==='restore'){$cohortId=(int)($_POST['cohort_id']??0);admin_course_set_cohort_archived($db,$courseId,$cohortId,false);$_SESSION['admin_cohorts_notice']='Turma reativada.';}
        else throw new RuntimeException('Ação inválida.');
    }catch(Throwable $e){$_SESSION['admin_cohorts_notice']='Não foi possível concluir: '.$e->getMessage();}
    $target=$cohortId>0?admin_cohort_url($activityId,$courseId,$cohortId):admin_course_url($activityId,$courseId,'cohorts');header('Location: '.$target,true,303);exit;
}
$notice=(string)($_SESSION['admin_cohorts_notice']??'');unset($_SESSION['admin_cohorts_notice']);$noticeTone=str_starts_with($notice,'Não foi possível')?'error':'success';
admin_shell_start('cohorts',$cohort?'Turma':'Turmas',$state,['/assets/admin-operations.css','/assets/admin-teaching.css']);?>
<?php if($notice!==''):?><div class="admin-notice <?=h($noticeTone)?>" role="<?=$noticeTone==='error'?'alert':'status'?>"><?=h($notice)?></div><?php endif;?>
<?php if($cohort):$stats=admin_course_cohort_stats($db,$courseId,$cohortId);$materials=course_material_pages($db,$courseId);admin_cohort_context($course,$cohort,$activityId,'overview',admin_course_cohort_period($cohort));?>
<?php if($showEdit):?>
<section class="admin-page-intro admin-focused-task"><div><h2>Editar turma</h2><p>Corrija nome e período sem recriar a turma ou suas matrículas.</p></div><a class="admin-button secondary" href="<?=h(admin_cohort_url($activityId,$courseId,$cohortId))?>">Cancelar</a></section>
<section class="admin-card admin-focused-task"><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('cohorts-admin'))?>"><input type="hidden" name="action" value="update"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="cohort_id" value="<?=$cohortId?>"><label class="admin-form-span-2">Nome<input name="title" value="<?=h((string)$cohort['title'])?>" required></label><label>Início<input type="date" name="starts_at" value="<?=h((string)($cohort['starts_at']??''))?>"></label><label>Fim<input type="date" name="ends_at" value="<?=h((string)($cohort['ends_at']??''))?>"></label><div class="admin-form-actions"><button class="admin-button" type="submit">Salvar alterações</button></div></form></section>
<section class="admin-card admin-teaching-danger admin-focused-task"><h3><?=(string)$cohort['status']==='archived'?'Reativar turma':'Arquivar turma'?></h3><p><?=(string)$cohort['status']==='archived'?'A turma volta a aparecer entre as turmas ativas.':'Arquivar retira a turma da operação corrente, sem apagar alunos, liberações ou histórico.'?></p><form method="post"<?=(string)$cohort['status']==='archived'?'':' data-confirm="Arquivar esta turma? O histórico será preservado."'?>><input type="hidden" name="_csrf" value="<?=h(csrf_token('cohorts-admin'))?>"><input type="hidden" name="action" value="<?=(string)$cohort['status']==='archived'?'restore':'archive'?>"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="cohort_id" value="<?=$cohortId?>"><button class="admin-button <?=(string)$cohort['status']==='archived'?'secondary':'danger'?>" type="submit"><?=(string)$cohort['status']==='archived'?'Reativar turma':'Arquivar turma'?></button></form></section>
<?php else:?>
<div class="admin-detail-lead"><div class="admin-teaching-meta"><?=admin_badge(admin_course_cohort_phase($cohort),(string)$cohort['status']==='archived'?'muted':'good')?><span><?=h(admin_course_cohort_period($cohort))?></span></div><div class="admin-page-actions"><a class="admin-button secondary" href="<?=h(admin_cohort_url($activityId,$courseId,$cohortId).'&edit=1')?>">Editar turma</a><?php if($materials):?><a class="admin-button secondary" href="/admin/course-preview.php?<?=h(http_build_query(['activity'=>$activityId,'course'=>$courseId,'cohort'=>$cohortId,'page'=>(int)$materials[0]['id']]))?>" target="_blank" rel="noopener">Visualizar como esta turma ↗</a><?php endif;?></div></div>
<dl class="admin-teaching-summary" aria-label="Resumo da turma"><div><dt>Alunos</dt><dd><?=$stats['students']?><?php if($stats['activation_pending']>0):?><small><?=$stats['activation_pending']?> ativação pendente</small><?php endif;?></dd></div><div><dt>Aulas liberadas</dt><dd><?=$stats['release']['released']?><small><?=$stats['release']['scheduled']?> agendadas · <?=$stats['release']['blocked']?> bloqueadas</small></dd></div><div><dt>Dúvidas abertas</dt><dd><?=$stats['questions']?></dd></div><div><dt>Testes para acompanhar</dt><dd><?=$stats['tests']?></dd></div></dl>
<div class="admin-workspace-grid">
<section class="admin-card"><header><div><h2>Alunos</h2><p><?=$stats['students']?> matrícula(s) ativa(s) nesta turma.</p></div><a class="admin-button secondary" href="<?=h(admin_cohort_url($activityId,$courseId,$cohortId,'students'))?>">Ver alunos</a></header></section>
<section class="admin-card"><header><div><h2>Aulas e acesso</h2><p><?=$stats['release']['released']?> liberada(s), <?=$stats['release']['scheduled']?> agendada(s), <?=$stats['release']['blocked']?> bloqueada(s).</p></div><a class="admin-button secondary" href="<?=h(admin_cohort_url($activityId,$courseId,$cohortId,'lessons'))?>">Gerenciar acesso</a></header></section>
<section class="admin-card"><header><div><h2>Acompanhamento</h2><p><?=$stats['questions']?> dúvida(s) aberta(s) · <?=$stats['tests']?> teste(s) para acompanhar.</p></div><div class="admin-card-actions"><a class="admin-button secondary" href="<?=h(admin_cohort_url($activityId,$courseId,$cohortId,'questions'))?>">Dúvidas</a><a class="admin-button secondary" href="<?=h(admin_cohort_url($activityId,$courseId,$cohortId,'tests'))?>">Testes</a></div></header></section>
</div>
<?php endif;?>
<?php else:admin_course_context($course,$activityId,'cohorts','Execuções deste curso.');
$where=['course_id=?'];$args=[$courseId];if($status==='active')$where[]="status!='archived'";elseif($status==='archived')$where[]="status='archived'";if($q!==''){$where[]='title LIKE ?';$args[]='%'.$q.'%';}$stmt=$db->prepare('SELECT * FROM course_cohorts WHERE '.implode(' AND ',$where).' ORDER BY starts_at IS NULL,starts_at DESC,id DESC');$stmt->execute($args);$rows=$stmt->fetchAll();?>
<?php if($showNew):?>
<section class="admin-page-intro admin-focused-task"><div><a class="admin-list-return" href="<?=h(admin_course_url($activityId,$courseId,'cohorts'))?>">← Voltar às turmas</a><h2>Nova turma</h2><p>Defina identificação e período. O endereço interno é gerado automaticamente.</p></div></section>
<section class="admin-card admin-focused-task"><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('cohorts-admin'))?>"><input type="hidden" name="action" value="create"><input type="hidden" name="course_id" value="<?=$courseId?>"><label class="admin-form-span-2">Nome<input name="title" required autofocus></label><label>Início<input type="date" name="starts_at"></label><label>Fim<input type="date" name="ends_at"></label><div class="admin-form-actions"><button class="admin-button" type="submit">Criar turma</button><a class="admin-button secondary" href="<?=h(admin_course_url($activityId,$courseId,'cohorts'))?>">Cancelar</a></div></form></section>
<?php else:?>
<section class="admin-page-intro"><div><h2>Turmas</h2><p>Abra uma turma para administrar alunos, aulas, acesso e acompanhamento.</p></div><a class="admin-button" href="<?=h(admin_course_url($activityId,$courseId,'cohorts').'&new=1')?>">Nova turma</a></section>
<form class="admin-data-toolbar" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><input type="hidden" name="course" value="<?=$courseId?>"><label>Status<select name="status"><option value="active"<?=$status==='active'?' selected':''?>>Ativas</option><option value="archived"<?=$status==='archived'?' selected':''?>>Arquivadas</option><option value="all"<?=$status==='all'?' selected':''?>>Todas</option></select></label><label class="grow">Buscar turma<input name="q" value="<?=h($q)?>" placeholder="Nome da turma"></label><div class="admin-inline-actions"><button class="admin-button secondary" type="submit">Filtrar</button><?php if($q!==''||$status!=='active'):?><a class="admin-button secondary" href="<?=h(cohort_workspace_list_url($activityId,$courseId))?>">Limpar</a><?php endif;?></div></form>
<?php if(!$rows):?><div class="admin-empty">Nenhuma turma encontrada.</div><?php else:?><div class="admin-table-scroll" tabindex="0" role="region" aria-label="Turmas do curso"><table class="admin-data-table admin-responsive-list"><thead><tr><th>Turma</th><th>Período</th><th>Alunos</th><th>Aulas</th><th>Acompanhamento</th><th></th></tr></thead><tbody><?php foreach($rows as $row):$cs=admin_course_cohort_stats($db,$courseId,(int)$row['id']);?><tr><td data-primary="true" data-label="Turma"><div class="admin-table-primary"><strong><?=h((string)$row['title'])?></strong><span><?=h(admin_course_cohort_phase($row))?></span></div></td><td data-label="Período"><?=h(admin_course_cohort_period($row))?></td><td data-label="Alunos"><?=$cs['students']?><?php if($cs['activation_pending']>0):?><div class="muted"><?=$cs['activation_pending']?> ativação pendente</div><?php endif;?></td><td data-label="Aulas"><div class="admin-table-compact-counts"><span><strong><?=$cs['release']['released']?></strong> liberadas</span><span><strong><?=$cs['release']['scheduled']?></strong> agendadas</span><span><strong><?=$cs['release']['blocked']?></strong> bloqueadas</span></div></td><td data-label="Acompanhamento"><div class="admin-table-compact-counts"><span><strong><?=$cs['questions']?></strong> dúvidas</span><span><strong><?=$cs['tests']?></strong> testes</span></div></td><td data-actions="true" data-label="" class="actions"><a class="admin-button secondary admin-table-action" href="<?=h(admin_cohort_url($activityId,$courseId,(int)$row['id']))?>">Abrir turma</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<?php endif;?>
<?php endif;?>
<?php admin_shell_end();