<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];
$courseId=max(0,(int)($_GET['course']??$_POST['course_id']??0));$course=$courseId>0?course_by_id($db,$courseId):null;if($course&&(int)$course['activity_id']!==$activityId){$course=null;$courseId=0;}
$view=(string)($_GET['view']??'overview');if(!in_array($view,['overview','setup','new'],true))$view='overview';
$q=trim((string)($_GET['q']??$_POST['return_q']??''));$page=max(1,(int)($_GET['page']??$_POST['return_page']??1));$pageSize=25;
function course_catalog_url(int $activityId,int $courseId=0,string $view='overview',string $q='',int $page=1): string {$args=['activity'=>$activityId];if($courseId>0)$args['course']=$courseId;if(in_array($view,['setup','new'],true))$args['view']=$view;if($q!=='')$args['q']=$q;if($page>1)$args['page']=$page;return '/admin/courses.php?'.http_build_query($args);}
$pageOptions=[];$formOptions=[];if(!$course||$view==='setup'){$pageOptions=array_values(array_filter(cms_pages($db,$activityId,null,true),static fn(array $p): bool=>(string)$p['status']!=='archived'));$formOptions=array_values(array_filter(cms_forms($db,$activityId),static fn(array $f): bool=>cms_form_purpose($f)==='enrollment'&&(string)($f['status']??'')!=='archived'));}
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('courses-admin',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}$action=(string)($_POST['action']??'');
    try{
        if($action==='create_from_page'){$created=course_create_from_page($db,(int)($_POST['public_page_id']??0),(int)($_POST['registration_form_id']??0));$courseId=(int)$created['id'];$course=$created;$view='overview';$_SESSION['admin_courses_notice']='Curso criado. Você já pode configurar turmas, conteúdo e inscrições.';}
        elseif($action==='update_course'&&$course){$course=course_update($db,$courseId,$_POST);$view='setup';$_SESSION['admin_courses_notice']='Configuração salva.';}
        else throw new RuntimeException('Ação inválida.');
    }catch(Throwable $e){$_SESSION['admin_courses_notice']='Não foi possível concluir: '.$e->getMessage();}
    header('Location: '.course_catalog_url($activityId,$courseId,$view,$q,$page),true,303);exit;
}
$notice=(string)($_SESSION['admin_courses_notice']??'');unset($_SESSION['admin_courses_notice']);$noticeTone=str_starts_with($notice,'Não foi possível')?'error':'success';
admin_shell_start('courses',$course?'Curso':'Cursos',$state,['/assets/admin-teaching.css','/assets/admin-operations.css']);?>
<?php if($notice!==''):?><div class="admin-notice <?=h($noticeTone)?>" role="<?=$noticeTone==='error'?'alert':'status'?>"><?=h($notice)?></div><?php endif;?>
<?php if(!$course):
$where=["c.activity_id=?","c.status!='archived'"];$args=[$activityId];if($q!==''){$where[]='(c.title LIKE ? OR c.slug LIKE ? OR p.title LIKE ? OR f.title LIKE ?)';$like='%'.$q.'%';array_push($args,$like,$like,$like,$like);}$whereSql=implode(' AND ',$where);
$count=$db->prepare("SELECT COUNT(*) FROM courses c LEFT JOIN cms_pages p ON p.id=c.public_page_id LEFT JOIN cms_forms f ON f.id=c.registration_form_id WHERE $whereSql");$count->execute($args);$total=(int)$count->fetchColumn();$pagesCount=max(1,(int)ceil($total/$pageSize));if($page>$pagesCount)$page=$pagesCount;$offset=($page-1)*$pageSize;
$sql="SELECT c.*,p.title public_page_title,p.status public_page_status,f.title registration_form_title,(SELECT COUNT(*) FROM course_cohorts cc WHERE cc.course_id=c.id AND cc.status!='archived') cohorts,(SELECT COUNT(*) FROM course_enrollments e JOIN course_cohorts cc ON cc.id=e.cohort_id WHERE cc.course_id=c.id AND cc.status!='archived' AND e.status='active') students,(SELECT COUNT(*) FROM cms_form_submissions s WHERE s.course_id=c.id AND s.status!='archived' AND s.payment_status!='paid' AND s.status!='converted') pending,(SELECT COUNT(*) FROM cms_form_submissions s WHERE s.course_id=c.id AND s.status!='archived' AND (s.payment_status='paid' OR s.status='converted') AND s.cohort_id IS NULL) unassigned,(SELECT COUNT(*) FROM student_questions sq JOIN course_cohorts cc ON cc.id=sq.cohort_id WHERE cc.course_id=c.id AND sq.status='open') questions,(SELECT COUNT(*) FROM student_tests t JOIN course_cohorts cc ON cc.id=t.cohort_id WHERE cc.course_id=c.id AND t.status IN ('submitted','needs_revision')) tests FROM courses c LEFT JOIN cms_pages p ON p.id=c.public_page_id LEFT JOIN cms_forms f ON f.id=c.registration_form_id WHERE $whereSql ORDER BY c.title COLLATE NOCASE,c.id LIMIT $pageSize OFFSET $offset";$stmt=$db->prepare($sql);$stmt->execute($args);$rows=$stmt->fetchAll();?>
<?php if($view==='new'):?>
<section class="admin-page-intro admin-focused-task"><div><a class="admin-list-return" href="<?=h(course_catalog_url($activityId))?>">← Voltar aos cursos</a><h2>Novo curso</h2><p>Associe uma página pública existente. O formulário de inscrição pode ser ligado agora ou depois.</p></div></section>
<section class="admin-card admin-focused-task"><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('courses-admin'))?>"><input type="hidden" name="action" value="create_from_page"><label class="admin-form-span-2">Página pública<select name="public_page_id" required><option value="">Escolha uma página</option><?php foreach($pageOptions as $item):if(course_by_public_page($db,(int)$item['id']))continue;?><option value="<?=(int)$item['id']?>"><?=h((string)$item['title'].' · '.public_language_label((string)$item['locale']))?></option><?php endforeach;?></select></label><label class="admin-form-span-2">Formulário de inscrição<select name="registration_form_id"><option value="0">Associar depois</option><?php foreach($formOptions as $item):?><option value="<?=(int)$item['id']?>"><?=h((string)$item['title'].' · '.public_language_label((string)$item['locale']))?></option><?php endforeach;?></select></label><div class="admin-form-actions"><button class="admin-button" type="submit">Criar curso</button><a class="admin-button secondary" href="<?=h(course_catalog_url($activityId))?>">Cancelar</a></div></form></section>
<?php else:?>
<section class="admin-page-intro"><div><h2>Cursos</h2><p>Escolha um curso para administrar inscrições, turmas, alunos, conteúdo e acompanhamento.</p></div><a class="admin-button" href="<?=h(course_catalog_url($activityId,0,'new'))?>">Novo curso</a></section>
<form class="admin-data-toolbar" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><label class="grow">Buscar curso<input name="q" value="<?=h($q)?>" placeholder="Nome do curso"></label><div class="admin-inline-actions"><button class="admin-button" type="submit">Buscar</button><?php if($q!==''):?><a class="admin-button secondary" href="<?=h(course_catalog_url($activityId))?>">Limpar</a><?php endif;?></div></form>
<?php if($q!==''):?><div class="admin-active-filters" aria-label="Filtros ativos"><span>Filtros ativos</span><?=admin_filter_chip('Busca',$q,course_catalog_url($activityId))?></div><?php endif;?>
<div class="admin-list-summary"><span><?php if($total>0):?>Mostrando <?=($offset+1)?>–<?=min($offset+$pageSize,$total)?> de <?=$total?> curso(s)<?php else:?>Nenhum curso encontrado<?php endif;?></span></div>
<?php if(!$rows):?><div class="admin-empty">Nenhum curso configurado.</div><?php else:?><div class="admin-table-scroll" tabindex="0" role="region" aria-label="Lista de cursos"><table class="admin-data-table admin-responsive-list"><thead><tr><th>Curso</th><th>Turmas e alunos</th><th>Precisa de atenção</th><th></th></tr></thead><tbody><?php foreach($rows as $row):$attention=(int)$row['pending']+(int)$row['unassigned']+(int)$row['questions']+(int)$row['tests'];?><tr><td data-primary="true" data-label="Curso"><div class="admin-table-primary"><strong><?=h((string)$row['title'])?></strong><span><?=admin_badge(admin_status_label('course',(string)$row['status']),admin_status_tone('course',(string)$row['status']))?><?=!empty($row['public_page_title'])?' · '.h((string)$row['public_page_title']):''?></span></div></td><td data-label="Turmas e alunos"><div class="admin-table-compact-counts"><span><strong><?=(int)$row['cohorts']?></strong> turmas</span><span><strong><?=(int)$row['students']?></strong> alunos</span></div></td><td data-label="Precisa de atenção"><?php if($attention===0):?><span class="muted">Nada pendente</span><?php else:?><div class="admin-table-compact-counts"><?php if((int)$row['pending']>0):?><span><strong><?=(int)$row['pending']?></strong> pagamentos</span><?php endif;?><?php if((int)$row['unassigned']>0):?><span><strong><?=(int)$row['unassigned']?></strong> sem turma</span><?php endif;?><?php if((int)$row['questions']>0):?><span><strong><?=(int)$row['questions']?></strong> dúvidas</span><?php endif;?><?php if((int)$row['tests']>0):?><span><strong><?=(int)$row['tests']?></strong> testes</span><?php endif;?></div><?php endif;?></td><td data-actions="true" data-label="" class="actions"><a class="admin-button admin-table-action" href="<?=h(course_catalog_url($activityId,(int)$row['id'],'overview',$q,$page))?>">Abrir curso</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<div class="admin-pagination"><span>Página <?=$page?> de <?=$pagesCount?></span><?php if($pagesCount>1):?><nav aria-label="Paginação de cursos"><?php if($page>1):?><a href="<?=h(course_catalog_url($activityId,0,'overview',$q,$page-1))?>">← Anterior</a><?php endif;?><?php if($page<$pagesCount):?><a href="<?=h(course_catalog_url($activityId,0,'overview',$q,$page+1))?>">Próxima →</a><?php endif;?></nav><?php endif;?></div>
<?php endif;?>
<?php else:
$publicPage=(int)($course['public_page_id']??0)>0?cms_page_by_id($db,(int)$course['public_page_id']):null;$registrationForm=(int)($course['registration_form_id']??0)>0?cms_form_by_id($db,(int)$course['registration_form_id']):null;
admin_course_context($course,$activityId,'overview',$view==='setup'?'Configuração do curso.':'Trabalho e pendências deste curso.');?>
<div class="admin-detail-lead"><div class="admin-teaching-meta"><?=admin_badge(admin_status_label('course',(string)$course['status']),admin_status_tone('course',(string)$course['status']))?><?php if($publicPage):?><span>Página pública: <?=h((string)$publicPage['title'])?></span><?php endif;?><?php if($registrationForm):?><span>Inscrição: <?=h((string)$registrationForm['title'])?></span><?php endif;?></div><div class="admin-page-actions"><?php if($view==='setup'):?><a class="admin-button secondary" href="<?=h(course_catalog_url($activityId,$courseId,'overview',$q,$page))?>">Voltar ao curso</a><?php else:?><a class="admin-button secondary" href="<?=h(course_catalog_url($activityId,$courseId,'setup',$q,$page))?>">Configurar curso</a><?php endif;?><?php if($publicPage):?><a class="admin-button secondary" href="/editor/?page=<?=(int)$publicPage['id']?>">Editar página</a><?php endif;?></div></div>
<?php if($view==='setup'):$course=course_by_id($db,$courseId)??$course;?>
<section class="admin-card"><header><div><h2>Configuração do curso</h2><p>Nome, endereço público e formulário usado para receber inscrições.</p></div></header><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('courses-admin'))?>"><input type="hidden" name="action" value="update_course"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="return_q" value="<?=h($q)?>"><input type="hidden" name="return_page" value="<?=$page?>"><label class="admin-form-span-2">Nome do curso<input name="title" value="<?=h((string)$course['title'])?>" required></label><label>Endereço curto<input name="slug" value="<?=h((string)$course['slug'])?>" required></label><label>Página pública<select name="public_page_id" required><?php foreach($pageOptions as $item):$owner=course_by_public_page($db,(int)$item['id']);if($owner&&(int)$owner['id']!==$courseId)continue;?><option value="<?=(int)$item['id']?>"<?=(int)$course['public_page_id']===(int)$item['id']?' selected':''?>><?=h((string)$item['title'].' · '.admin_status_label('page',(string)$item['status']))?></option><?php endforeach;?></select></label><label class="admin-form-span-2">Formulário de inscrição<select name="registration_form_id"><option value="0">Nenhum</option><?php foreach($formOptions as $item):?><option value="<?=(int)$item['id']?>"<?=(int)($course['registration_form_id']??0)===(int)$item['id']?' selected':''?>><?=h((string)$item['title'])?></option><?php endforeach;?></select></label><div class="admin-form-actions"><button class="admin-button" type="submit">Salvar configuração</button><?php if($registrationForm):?><a class="admin-button secondary" href="/admin/forms.php?activity=<?=$activityId?>&form=<?=(int)$registrationForm['id']?>">Editar formulário</a><?php endif;?></div></form></section>
<?php else:
$attention=admin_course_attention($db,$courseId);$cohorts=course_cohorts_for_course($db,$courseId);$lessons=course_lessons_for_course($db,$courseId);$materials=course_material_pages($db,$courseId);$enrollmentQ=$db->prepare("SELECT COUNT(*) FROM course_enrollments e JOIN course_cohorts cc ON cc.id=e.cohort_id WHERE cc.course_id=? AND e.status='active' AND cc.status!='archived'");$enrollmentQ->execute([$courseId]);$studentCount=(int)$enrollmentQ->fetchColumn();?>
<section class="admin-card"><header><div><h2>Precisa de atenção</h2><p>Itens que pedem uma decisão ou resposta.</p></div></header><div class="admin-work-queue">
<?php if(array_sum($attention)===0):?><div class="admin-empty compact">Nenhuma pendência neste curso.</div><?php endif;?>
<?php if($attention['pending_payment']>0):?><a class="admin-work-item" href="<?=h(admin_course_url($activityId,$courseId,'registrations').'&status=pending')?>"><strong><?=$attention['pending_payment']?> aguardando pagamento</strong><span>Revisar inscrições</span></a><?php endif;?>
<?php if($attention['unassigned']>0):?><a class="admin-work-item" href="<?=h(admin_course_url($activityId,$courseId,'registrations').'&status=unassigned')?>"><strong><?=$attention['unassigned']?> confirmada(s) sem turma</strong><span>Atribuir turma</span></a><?php endif;?>
<?php if($attention['tests']>0):?><a class="admin-work-item" href="<?=h(admin_course_url($activityId,$courseId,'tests'))?>"><strong><?=$attention['tests']?> teste(s) aguardando acompanhamento</strong><span>Avaliar testes</span></a><?php endif;?>
<?php if($attention['questions']>0):?><a class="admin-work-item" href="<?=h(admin_course_url($activityId,$courseId,'questions').'&status=open')?>"><strong><?=$attention['questions']?> dúvida(s) aberta(s)</strong><span>Responder dúvidas</span></a><?php endif;?>
</div></section>
<section class="admin-card"><header><div><h2>Turmas</h2><p><?=count($cohorts)?> turma(s) · <?=$studentCount?> aluno(s) ativos.</p></div><a class="admin-button" href="<?=h(admin_course_url($activityId,$courseId,'cohorts').'&new=1')?>">Nova turma</a></header>
<?php if(!$cohorts):?><div class="admin-empty">Crie a primeira turma para começar a organizar alunos e liberações.</div><?php else:?><div class="admin-table-scroll" tabindex="0" role="region" aria-label="Turmas do curso"><table class="admin-data-table admin-responsive-list"><thead><tr><th>Turma</th><th>Período</th><th>Alunos</th><th>Aulas</th><th>Acompanhamento</th><th></th></tr></thead><tbody><?php foreach($cohorts as $cohort):$cs=admin_course_cohort_stats($db,$courseId,(int)$cohort['id']);?><tr><td data-primary="true" data-label="Turma"><div class="admin-table-primary"><strong><?=h((string)$cohort['title'])?></strong><span><?=h(admin_course_cohort_phase($cohort))?></span></div></td><td data-label="Período"><?=h(admin_course_cohort_period($cohort))?></td><td data-label="Alunos"><strong><?=$cs['students']?></strong><?php if($cs['activation_pending']>0):?><div class="muted"><?=$cs['activation_pending']?> ativação pendente</div><?php endif;?></td><td data-label="Aulas"><div class="admin-table-compact-counts"><span><strong><?=$cs['release']['released']?></strong> liberadas</span><span><strong><?=$cs['release']['scheduled']?></strong> agendadas</span><span><strong><?=$cs['release']['blocked']?></strong> bloqueadas</span></div></td><td data-label="Acompanhamento"><div class="admin-table-compact-counts"><span><strong><?=$cs['questions']?></strong> dúvidas</span><span><strong><?=$cs['tests']?></strong> testes</span></div></td><td data-actions="true" data-label="" class="actions"><a class="admin-button secondary admin-table-action" href="<?=h(admin_cohort_url($activityId,$courseId,(int)$cohort['id']))?>">Abrir turma</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="admin-card"><header><div><h2>Conteúdo do curso</h2><p><?=count($lessons)?> aula(s) · <?=count($materials)?> página(s) de material.</p></div><div class="admin-card-actions"><a class="admin-button secondary" href="<?=h(admin_course_url($activityId,$courseId,'lessons'))?>">Aulas</a><a class="admin-button secondary" href="<?=h(admin_course_url($activityId,$courseId,'material'))?>">Material</a></div></header></section>
<?php endif;?>
<?php endif;?>
<?php admin_shell_end();