<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];
$courseId=(int)($_GET['course']??$_POST['course_id']??0);$course=$courseId>0?course_by_id($db,$courseId):null;if($course&&(int)$course['activity_id']!==$activityId)$course=null;
$view=(string)($_GET['view']??'setup');if(!in_array($view,['setup','cohorts','students','lessons','material'],true))$view='setup';
function course_admin_url(int $activityId,int $courseId=0,string $view='setup',array $extra=[]): string {$args=['activity'=>$activityId];if($courseId>0){$args['course']=$courseId;$args['view']=$view;}return '/admin/courses.php?'.http_build_query($args+$extra);}
function course_admin_tabs(int $activityId,int $courseId,string $view): void {$items=['setup'=>'Configuração','cohorts'=>'Turmas','students'=>'Alunos','lessons'=>'Aulas','material'=>'Material'];echo '<nav class="admin-subtabs" aria-label="Curso">';foreach($items as $key=>$label)echo '<a href="'.h(course_admin_url($activityId,$courseId,$key)).'"'.($key===$view?' aria-current="page"':'').'>'.h($label).'</a>';echo '</nav>';}
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('courses-admin',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}$action=(string)($_POST['action']??'');
    try{
        if($action==='create_from_page'){$created=course_create_from_page($db,(int)($_POST['public_page_id']??0),(int)($_POST['registration_form_id']??0));$courseId=(int)$created['id'];$view='setup';}
        elseif(!$course)throw new RuntimeException('Escolha um curso.');
        elseif($action==='update_course')course_update($db,(int)$course['id'],$_POST);
        elseif($action==='create_cohort')course_create_cohort_for_course($db,(int)$course['id'],(string)($_POST['title']??''),(string)($_POST['slug']??''),(string)($_POST['starts_at']??'')?:null,(string)($_POST['ends_at']??'')?:null);
        elseif($action==='add_lesson')course_add_lesson_for_course($db,(int)$course['id'],(string)($_POST['title']??''),(string)($_POST['lesson_key']??''));
        elseif($action==='set_release')course_set_lesson_release_for_course($db,(int)$course['id'],(int)($_POST['cohort_id']??0),(int)($_POST['lesson_id']??0),(string)($_POST['mode']??'block'),(string)($_POST['scheduled_at']??''));
        elseif($action==='add_material')course_material_add_page($db,(int)$course['id'],(int)($_POST['page_id']??0));
        elseif($action==='remove_material')course_material_remove_page($db,(int)$course['id'],(int)($_POST['page_id']??0));
        elseif($action==='map_section'){course_material_set_section_lesson($db,(int)$course['id'],(int)($_POST['page_id']??0),(string)($_POST['section_key']??''),(int)($_POST['lesson_id']??0)?:null);}
        else throw new RuntimeException('Ação inválida.');
        $_SESSION['admin_notice']='Alteração salva.';
    }catch(Throwable $e){$_SESSION['admin_notice']='Não foi possível concluir: '.$e->getMessage();}
    header('Location: '.course_admin_url($activityId,$courseId,$view),true,303);exit;
}
$courses=course_list($db,$activityId);$pages=array_values(array_filter(cms_pages($db,$activityId,null,true),static fn(array $p): bool=>(string)$p['status']!=='archived'));$forms=array_values(array_filter(cms_forms($db,$activityId),static fn(array $f): bool=>cms_form_purpose($f)==='enrollment'));
$notice=(string)($_SESSION['admin_notice']??'');unset($_SESSION['admin_notice']);
admin_shell_start('courses','Cursos',$state);?>
<?php if($notice!==''):?><div class="admin-notice"><?=h($notice)?></div><?php endif;?>
<?php if(!$course):?>
<section class="overview-hero"><div><p class="admin-kicker">Inscrições e alunos</p><h2>Cursos</h2><p>Curso é a entidade que reúne formulário de inscrição, turmas, aulas e páginas CMS de material. Páginas e formulários continuam sendo editados nas ferramentas globais.</p></div></section>
<div class="overview-grid">
<?php foreach($courses as $row):?><article class="overview-card"><p class="admin-kicker">Curso</p><h2><?=h((string)$row['title'])?></h2><p><?=h((string)($row['public_page_title']?:'Sem página pública'))?><?php if(!empty($row['registration_form_title'])):?> · <?=h((string)$row['registration_form_title'])?><?php endif;?></p><div class="admin-card-actions"><a class="admin-button" href="<?=h(course_admin_url($activityId,(int)$row['id']))?>">Administrar</a></div></article><?php endforeach;?>
</div>
<section class="admin-card"><header><div><h2>Associar página como curso</h2><p>Isso não cria uma nova página, um novo site ou um novo editor. Apenas cria a identidade de domínio para uma página CMS já existente.</p></div></header>
<form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('courses-admin'))?>"><input type="hidden" name="action" value="create_from_page"><label class="admin-form-span-2">Página pública<select name="public_page_id" required><option value="">Escolha uma página</option><?php foreach($pages as $page):if(course_by_public_page($db,(int)$page['id']))continue;?><option value="<?=(int)$page['id']?>"><?=h((string)$page['title'].' · '.public_language_label((string)$page['locale']))?></option><?php endforeach;?></select></label><label class="admin-form-span-2">Formulário de inscrição<select name="registration_form_id"><option value="0">Associar depois</option><?php foreach($forms as $form):?><option value="<?=(int)$form['id']?>"><?=h((string)$form['title'].' · '.public_language_label((string)$form['locale']))?></option><?php endforeach;?></select></label><div class="admin-form-actions"><button class="admin-button" type="submit">Associar curso</button><a class="admin-button secondary" href="/admin/pages.php?activity=<?=$activityId?>">Gerenciar páginas</a></div></form></section>
<?php else:$courseId=(int)$course['id'];?>
<div class="overview-hero"><div><p class="admin-kicker">Curso</p><h2><?=h((string)$course['title'])?></h2><p>Inscrições, turmas, alunos, aulas e material didático deste curso.</p></div><div class="hero-actions"><a class="admin-button secondary" href="<?=h(course_admin_url($activityId))?>">Todos os cursos</a><a class="admin-button secondary" href="/admin/registrations.php?activity=<?=$activityId?>&course=<?=$courseId?>">Inscrições</a></div></div>
<?php course_admin_tabs($activityId,$courseId,$view);?>
<?php if($view==='setup'):$course=course_by_id($db,$courseId)??$course;?>
<section class="admin-card"><header><div><h2>Configuração</h2><p>A página pública e o formulário continuam sendo objetos globais do CMS. Aqui apenas os associamos ao curso.</p></div></header><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('courses-admin'))?>"><input type="hidden" name="action" value="update_course"><input type="hidden" name="course_id" value="<?=$courseId?>"><label class="admin-form-span-2">Nome do curso<input name="title" value="<?=h((string)$course['title'])?>" required></label><label>Slug<input name="slug" value="<?=h((string)$course['slug'])?>" required></label><label>Página pública<select name="public_page_id" required><?php foreach($pages as $page):$owner=course_by_public_page($db,(int)$page['id']);if($owner&&(int)$owner['id']!==$courseId)continue;?><option value="<?=(int)$page['id']?>"<?=(int)$course['public_page_id']===(int)$page['id']?' selected':''?>><?=h((string)$page['title'])?></option><?php endforeach;?></select></label><label class="admin-form-span-2">Formulário de inscrição<select name="registration_form_id"><option value="0">Nenhum</option><?php foreach($forms as $form):?><option value="<?=(int)$form['id']?>"<?=(int)($course['registration_form_id']??0)===(int)$form['id']?' selected':''?>><?=h((string)$form['title'])?></option><?php endforeach;?></select></label><div class="admin-form-actions"><button class="admin-button" type="submit">Salvar</button><?php if((int)$course['public_page_id']>0):?><a class="admin-button secondary" href="/editor/?page=<?=(int)$course['public_page_id']?>">Editar página pública</a><?php endif;?><?php if((int)($course['registration_form_id']??0)>0):?><a class="admin-button secondary" href="/admin/forms.php?activity=<?=$activityId?>&form=<?=(int)$course['registration_form_id']?>">Editar formulário</a><?php endif;?></div></form></section>
<?php elseif($view==='cohorts'):$cohorts=course_cohorts_for_course($db,$courseId);?>
<section class="admin-card"><header><div><h2>Turmas</h2><p>Turma é uma execução concreta do curso. Inscrições são atribuídas a uma turma somente depois da organização das disponibilidades.</p></div></header><?php if(!$cohorts):?><div class="admin-empty">Nenhuma turma cadastrada.</div><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Turma</th><th>Período</th><th>Status</th></tr></thead><tbody><?php foreach($cohorts as $cohort):?><tr><td><strong><?=h((string)$cohort['title'])?></strong><div class="muted"><?=h((string)$cohort['slug'])?></div></td><td><?=h((string)($cohort['starts_at']?:'—'))?> → <?=h((string)($cohort['ends_at']?:'—'))?></td><td><?=h((string)$cohort['status'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="admin-card"><header><div><h2>Nova turma</h2></div></header><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('courses-admin'))?>"><input type="hidden" name="action" value="create_cohort"><input type="hidden" name="course_id" value="<?=$courseId?>"><label class="admin-form-span-2">Nome<input name="title" required></label><label>Slug<input name="slug"></label><label>Início<input type="date" name="starts_at"></label><label>Fim<input type="date" name="ends_at"></label><div class="admin-form-actions"><button class="admin-button" type="submit">Criar turma</button></div></form></section>
<?php elseif($view==='students'):$q=$db->prepare("SELECT u.name,u.email,p.cpf_last4,c.title cohort_title,e.confirmed_at FROM course_enrollments e JOIN course_cohorts c ON c.id=e.cohort_id JOIN student_users u ON u.id=e.student_id LEFT JOIN student_profiles p ON p.student_id=u.id WHERE c.course_id=? AND e.status='active' AND c.status!='archived' ORDER BY u.name COLLATE NOCASE");$q->execute([$courseId]);$students=$q->fetchAll();?>
<section class="admin-card"><header><div><h2>Alunos matriculados</h2><p>Cada linha é uma matrícula deste curso. A identidade do aluno continua global e pode aparecer em outros cursos sem ser duplicada.</p></div></header><?php if(!$students):?><div class="admin-empty">Nenhum aluno matriculado neste curso.</div><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Aluno</th><th>CPF</th><th>Turma</th><th>Matrícula</th></tr></thead><tbody><?php foreach($students as $row):?><tr><td><strong><?=h((string)$row['name'])?></strong><div class="muted"><?=h((string)$row['email'])?></div></td><td><?=$row['cpf_last4']?'***.'.h((string)$row['cpf_last4']):'—'?></td><td><?=h((string)$row['cohort_title'])?></td><td><?=h(date('d/m/Y',strtotime((string)$row['confirmed_at'])))?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php elseif($view==='lessons'):$lessons=course_lessons_for_course($db,$courseId);$cohorts=course_cohorts_for_course($db,$courseId);?>
<section class="admin-card"><header><div><h2>Aulas</h2><p>A aula é a unidade de liberação progressiva. Uma aula pode liberar seções em várias páginas de material.</p></div></header><?php if(!$lessons):?><div class="admin-empty">Nenhuma aula cadastrada.</div><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Aula</th><?php foreach($cohorts as $cohort):?><th><?=h((string)$cohort['title'])?></th><?php endforeach;?></tr></thead><tbody><?php foreach($lessons as $lesson):?><tr><td><strong><?=h((string)$lesson['title'])?></strong><div class="muted"><?=h((string)$lesson['lesson_key'])?></div></td><?php foreach($cohorts as $cohort):$release=course_lesson_release_rows_for_course($db,(int)$cohort['id'],$courseId);$by=[];foreach($release as $r)$by[(int)$r['id']]=$r;$row=$by[(int)$lesson['id']]??null;$state=cms_access_lesson_release_state($row['released_at']??null);?><td><form class="admin-inline-actions" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('courses-admin'))?>"><input type="hidden" name="action" value="set_release"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="cohort_id" value="<?=(int)$cohort['id']?>"><input type="hidden" name="lesson_id" value="<?=(int)$lesson['id']?>"><span><?=h($state)?></span><button class="admin-button secondary" name="mode" value="<?=$state==='released'?'block':'release'?>" type="submit"><?=$state==='released'?'Bloquear':'Liberar'?></button></form></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="admin-card"><header><div><h2>Nova aula</h2></div></header><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('courses-admin'))?>"><input type="hidden" name="action" value="add_lesson"><input type="hidden" name="course_id" value="<?=$courseId?>"><label>Nome<input name="title" required></label><label>Chave<input name="lesson_key" placeholder="aula-1"></label><div class="admin-form-actions"><button class="admin-button" type="submit">Criar aula</button></div></form></section>
<?php elseif($view==='material'):$materialPages=course_material_pages($db,$courseId);$lessons=course_lessons_for_course($db,$courseId);$materialIds=array_fill_keys(array_map(static fn(array $p): int=>(int)$p['id'],$materialPages),true);?>
<section class="admin-card"><header><div><h2>Páginas de material</h2><p>São páginas CMS normais. A associação ao curso não cria cópia nem editor separado.</p></div><div class="admin-card-actions"><a class="admin-button secondary" href="/admin/pages.php?activity=<?=$activityId?>">Abrir Páginas</a></div></header><?php if(!$materialPages):?><div class="admin-empty">Nenhuma página associada.</div><?php endif;?><?php foreach($materialPages as $page):$sections=course_material_sections_from_page($db,(int)$page['id']);$map=course_material_section_map($db,$courseId,(int)$page['id']);?><section class="admin-card"><header><div><p class="admin-kicker">Página CMS</p><h3><?=h((string)$page['title'])?></h3></div><div class="admin-card-actions"><a class="admin-button secondary" href="/editor/?page=<?=(int)$page['id']?>">Editar página</a><form method="post" data-confirm="Remover esta página do material do curso? A página não será excluída."><input type="hidden" name="_csrf" value="<?=h(csrf_token('courses-admin'))?>"><input type="hidden" name="action" value="remove_material"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="page_id" value="<?=(int)$page['id']?>"><button class="admin-button secondary" type="submit">Desassociar</button></form></div></header><?php if(!$sections):?><div class="admin-empty compact">A página não possui seções CMS identificáveis no rascunho atual.</div><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Seção</th><th>Liberação</th></tr></thead><tbody><?php foreach($sections as $key=>$label):$lessonId=(int)($map[$key]['lesson_id']??0);?><tr><td><strong><?=h($label)?></strong><div class="muted"><?=h($key)?></div></td><td><form class="admin-inline-actions" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('courses-admin'))?>"><input type="hidden" name="action" value="map_section"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="page_id" value="<?=(int)$page['id']?>"><input type="hidden" name="section_key" value="<?=h($key)?>"><select name="lesson_id"><option value="0">Sempre disponível</option><?php foreach($lessons as $lesson):?><option value="<?=(int)$lesson['id']?>"<?=$lessonId===(int)$lesson['id']?' selected':''?>><?=h((string)$lesson['title'])?></option><?php endforeach;?></select><button class="admin-button secondary" type="submit">Salvar</button></form></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section><?php endforeach;?></section>
<section class="admin-card"><header><div><h2>Associar página existente</h2><p>A página permanece na biblioteca editorial global e continua usando o editor CMS normal.</p></div></header><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('courses-admin'))?>"><input type="hidden" name="action" value="add_material"><input type="hidden" name="course_id" value="<?=$courseId?>"><label class="admin-form-span-2">Página<select name="page_id" required><option value="">Escolha</option><?php foreach($pages as $page):if(isset($materialIds[(int)$page['id']]))continue;?><option value="<?=(int)$page['id']?>"><?=h((string)$page['title'].' · '.public_language_label((string)$page['locale']))?></option><?php endforeach;?></select></label><div class="admin-form-actions"><button class="admin-button" type="submit">Associar ao material</button></div></form></section>
<?php endif;?>
<?php endif;?>
<?php admin_shell_end();
