<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];
$courseId=(int)($_GET['course']??$_POST['course_id']??0);$course=$courseId>0?course_by_id($db,$courseId):null;if($course&&(int)$course['activity_id']!==$activityId)$course=null;
$view=(string)($_GET['view']??'overview');if(!in_array($view,['overview','setup','cohorts','students','lessons','material'],true))$view='overview';
function course_page_url(int $activityId,int $courseId=0,string $view='overview'): string {return $courseId>0?admin_course_url($activityId,$courseId,$view):'/admin/courses.php?'.http_build_query(['activity'=>$activityId]);}
function course_index_url(int $activityId,string $q='',int $page=1): string {$args=['activity'=>$activityId];if($q!=='')$args['q']=$q;if($page>1)$args['page']=$page;return '/admin/courses.php?'.http_build_query($args);}
function course_students_url(int $activityId,int $courseId,string $q='',int $page=1): string {$args=['activity'=>$activityId,'course'=>$courseId,'view'=>'students'];if($q!=='')$args['q']=$q;if($page>1)$args['page']=$page;return '/admin/courses.php?'.http_build_query($args);}
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('courses-admin',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}$action=(string)($_POST['action']??'');
    try{
        if($action==='create_from_page'){$created=course_create_from_page($db,(int)($_POST['public_page_id']??0),(int)($_POST['registration_form_id']??0));$courseId=(int)$created['id'];$view='overview';}
        elseif(!$course)throw new RuntimeException('Escolha um curso.');
        elseif($action==='update_course')course_update($db,(int)$course['id'],$_POST);
        elseif($action==='create_cohort')course_create_cohort_for_course($db,(int)$course['id'],(string)($_POST['title']??''),(string)($_POST['slug']??''),(string)($_POST['starts_at']??'')?:null,(string)($_POST['ends_at']??'')?:null);
        elseif($action==='add_lesson')course_add_lesson_for_course($db,(int)$course['id'],(string)($_POST['title']??''),(string)($_POST['lesson_key']??''));
        elseif($action==='set_release')course_set_lesson_release_for_course($db,(int)$course['id'],(int)($_POST['cohort_id']??0),(int)($_POST['lesson_id']??0),(string)($_POST['mode']??'block'),(string)($_POST['scheduled_at']??''));
        elseif($action==='add_material')course_material_add_page($db,(int)$course['id'],(int)($_POST['page_id']??0));
        elseif($action==='remove_material')course_material_remove_page($db,(int)$course['id'],(int)($_POST['page_id']??0));
        elseif($action==='map_section')course_material_set_section_lesson($db,(int)$course['id'],(int)($_POST['page_id']??0),(string)($_POST['section_key']??''),(int)($_POST['lesson_id']??0)?:null);
        else throw new RuntimeException('Ação inválida.');
        $_SESSION['admin_notice']='Alteração salva.';
    }catch(Throwable $e){$_SESSION['admin_notice']='Não foi possível concluir: '.$e->getMessage();}
    header('Location: '.course_page_url($activityId,$courseId,$view),true,303);exit;
}
$pages=array_values(array_filter(cms_pages($db,$activityId,null,true),static fn(array $p): bool=>(string)$p['status']!=='archived'));$forms=array_values(array_filter(cms_forms($db,$activityId),static fn(array $f): bool=>cms_form_purpose($f)==='enrollment'));
$notice=(string)($_SESSION['admin_notice']??'');unset($_SESSION['admin_notice']);
admin_shell_start('courses','Cursos',$state);?>
<?php if($notice!==''):?><div class="admin-notice"><?=h($notice)?></div><?php endif;?>
<?php if(!$course):
$courseQ=trim((string)($_GET['q']??''));$coursePage=max(1,(int)($_GET['page']??1));$coursePageSize=25;$where=["c.activity_id=?","c.status!='archived'"];$args=[$activityId];if($courseQ!==''){$where[]='(c.title LIKE ? OR c.slug LIKE ? OR p.title LIKE ?)';$like='%'.$courseQ.'%';array_push($args,$like,$like,$like);}$whereSql=implode(' AND ',$where);
$count=$db->prepare("SELECT COUNT(*) FROM courses c LEFT JOIN cms_pages p ON p.id=c.public_page_id WHERE $whereSql");$count->execute($args);$courseTotal=(int)$count->fetchColumn();$coursePages=max(1,(int)ceil($courseTotal/$coursePageSize));if($coursePage>$coursePages)$coursePage=$coursePages;$courseOffset=($coursePage-1)*$coursePageSize;
$sql="SELECT c.*,p.title public_page_title,
(SELECT COUNT(*) FROM course_cohorts cc WHERE cc.course_id=c.id AND cc.status!='archived') cohorts,
(SELECT COUNT(*) FROM course_enrollments e JOIN course_cohorts cc ON cc.id=e.cohort_id WHERE cc.course_id=c.id AND cc.status!='archived' AND e.status='active') students,
(SELECT COUNT(*) FROM cms_form_submissions s WHERE s.course_id=c.id AND s.status!='archived') registrations,
(SELECT COUNT(*) FROM cms_form_submissions s WHERE s.course_id=c.id AND s.status!='archived' AND (s.payment_status='paid' OR s.status='converted') AND s.cohort_id IS NULL) unassigned
FROM courses c LEFT JOIN cms_pages p ON p.id=c.public_page_id WHERE $whereSql ORDER BY c.title COLLATE NOCASE,c.id LIMIT $coursePageSize OFFSET $courseOffset";$list=$db->prepare($sql);$list->execute($args);$courseRows=$list->fetchAll();?>
<section class="overview-hero"><div><p class="admin-kicker">Operação educacional</p><h2>Cursos</h2><p>Localize o curso e entre no contexto de trabalho. A listagem permanece utilizável quando o catálogo crescer.</p></div></section>
<form class="admin-data-toolbar" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><label class="grow">Buscar curso<input name="q" value="<?=h($courseQ)?>" placeholder="Nome, slug ou página pública"></label><button class="admin-button secondary" type="submit">Buscar</button><?php if($courseQ!==''):?><a class="admin-button secondary" href="<?=h(course_index_url($activityId))?>">Limpar</a><?php endif;?></form>
<?php if(!$courseRows):?><section class="admin-card"><div class="admin-empty"><?=$courseQ!==''?'Nenhum curso corresponde à busca.':'Nenhum curso configurado.'?></div></section><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Curso</th><th>Página pública</th><th>Inscrições</th><th>Turmas</th><th>Alunos</th><th></th></tr></thead><tbody><?php foreach($courseRows as $row):$cid=(int)$row['id'];?><tr><td><div class="admin-table-primary"><strong><?=h((string)$row['title'])?></strong><span><?=h((string)$row['slug'])?></span></div></td><td><?=h((string)($row['public_page_title']?:'Sem página pública'))?></td><td class="admin-table-number"><strong><?=(int)$row['registrations']?></strong><?php if((int)$row['unassigned']>0):?><div class="muted"><?=(int)$row['unassigned']?> confirmada(s) sem turma</div><?php endif;?></td><td class="admin-table-number"><?=(int)$row['cohorts']?></td><td class="admin-table-number"><?=(int)$row['students']?></td><td class="actions"><a class="admin-button secondary admin-table-action" href="<?=h(admin_course_url($activityId,$cid,'overview'))?>">Abrir</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<div class="admin-pagination"><span><?php if($courseTotal>0):?>Mostrando <?=($courseOffset+1)?>–<?=min($courseOffset+$coursePageSize,$courseTotal)?> de <?=$courseTotal?> curso(s)<?php else:?>0 cursos<?php endif;?></span><?php if($coursePages>1):?><nav aria-label="Paginação de cursos"><?php if($coursePage>1):?><a href="<?=h(course_index_url($activityId,$courseQ,$coursePage-1))?>">← Anterior</a><?php endif;?><span>Página <?=$coursePage?> de <?=$coursePages?></span><?php if($coursePage<$coursePages):?><a href="<?=h(course_index_url($activityId,$courseQ,$coursePage+1))?>">Próxima →</a><?php endif;?></nav><?php endif;?></div>
<details class="admin-secondary-setup"><summary>Configuração avançada · associar uma página CMS a um novo curso</summary><section class="admin-card"><header><div><h2>Associar página como curso</h2><p>Use apenas quando uma página CMS existente passar a representar um novo curso. Isso não cria outra página nem outro editor.</p></div></header><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('courses-admin'))?>"><input type="hidden" name="action" value="create_from_page"><label class="admin-form-span-2">Página pública<select name="public_page_id" required><option value="">Escolha uma página</option><?php foreach($pages as $page):if(course_by_public_page($db,(int)$page['id']))continue;?><option value="<?=(int)$page['id']?>"><?=h((string)$page['title'].' · '.public_language_label((string)$page['locale']))?></option><?php endforeach;?></select></label><label class="admin-form-span-2">Formulário de inscrição<select name="registration_form_id"><option value="0">Associar depois</option><?php foreach($forms as $form):?><option value="<?=(int)$form['id']?>"><?=h((string)$form['title'].' · '.public_language_label((string)$form['locale']))?></option><?php endforeach;?></select></label><div class="admin-form-actions"><button class="admin-button" type="submit">Associar curso</button></div></form></section></details>
<?php else:$courseId=(int)$course['id'];admin_course_context($course,$activityId,$view==='setup'?'overview':$view,'Inscrições, turmas, alunos, aulas e material deste curso.');?>

<?php if($view==='overview'):
$q=$db->prepare("SELECT (SELECT COUNT(*) FROM course_cohorts WHERE course_id=? AND status!='archived') cohorts,(SELECT COUNT(*) FROM course_enrollments e JOIN course_cohorts c ON c.id=e.cohort_id WHERE c.course_id=? AND e.status='active') students,(SELECT COUNT(*) FROM course_lessons WHERE course_id=?) lessons,(SELECT COUNT(*) FROM course_material_pages WHERE course_id=?) material,(SELECT COUNT(*) FROM cms_form_submissions WHERE course_id=? AND status!='archived') registrations,(SELECT COUNT(*) FROM cms_form_submissions WHERE course_id=? AND status!='archived' AND (payment_status='paid' OR status='converted') AND cohort_id IS NULL) unassigned");$q->execute([$courseId,$courseId,$courseId,$courseId,$courseId,$courseId]);$stats=$q->fetch()?:[];?>
<div class="admin-stat-grid"><div class="admin-stat"><span>Inscrições</span><strong><?=(int)($stats['registrations']??0)?></strong></div><div class="admin-stat"><span>Confirmadas sem turma</span><strong><?=(int)($stats['unassigned']??0)?></strong></div><div class="admin-stat"><span>Turmas</span><strong><?=(int)($stats['cohorts']??0)?></strong></div><div class="admin-stat"><span>Alunos</span><strong><?=(int)($stats['students']??0)?></strong></div><div class="admin-stat"><span>Aulas</span><strong><?=(int)($stats['lessons']??0)?></strong></div><div class="admin-stat"><span>Páginas de material</span><strong><?=(int)($stats['material']??0)?></strong></div></div>
<section class="admin-card"><header><div><h2>Próximas ações</h2><p>Entre diretamente na operação que precisa de atenção.</p></div></header><div class="admin-card-actions"><a class="admin-button" href="<?=h(admin_course_url($activityId,$courseId,'registrations'))?>">Ver inscrições</a><a class="admin-button secondary" href="<?=h(admin_course_url($activityId,$courseId,'cohorts'))?>">Gerenciar turmas</a><a class="admin-button secondary" href="<?=h(admin_course_url($activityId,$courseId,'material'))?>">Gerenciar material</a><a class="admin-button secondary" href="<?=h(course_page_url($activityId,$courseId,'setup'))?>">Configuração do curso</a></div></section>

<?php elseif($view==='setup'):$course=course_by_id($db,$courseId)??$course;?>
<section class="admin-card"><header><div><h2>Configuração do curso</h2><p>Página pública e formulário continuam sendo objetos globais do CMS. Aqui apenas os relacionamos ao curso.</p></div></header><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('courses-admin'))?>"><input type="hidden" name="action" value="update_course"><input type="hidden" name="course_id" value="<?=$courseId?>"><label class="admin-form-span-2">Nome do curso<input name="title" value="<?=h((string)$course['title'])?>" required></label><label>Slug<input name="slug" value="<?=h((string)$course['slug'])?>" required></label><label>Página pública<select name="public_page_id" required><?php foreach($pages as $page):$owner=course_by_public_page($db,(int)$page['id']);if($owner&&(int)$owner['id']!==$courseId)continue;?><option value="<?=(int)$page['id']?>"<?=(int)$course['public_page_id']===(int)$page['id']?' selected':''?>><?=h((string)$page['title'])?></option><?php endforeach;?></select></label><label class="admin-form-span-2">Formulário de inscrição<select name="registration_form_id"><option value="0">Nenhum</option><?php foreach($forms as $form):?><option value="<?=(int)$form['id']?>"<?=(int)($course['registration_form_id']??0)===(int)$form['id']?' selected':''?>><?=h((string)$form['title'])?></option><?php endforeach;?></select></label><div class="admin-form-actions"><button class="admin-button" type="submit">Salvar</button><?php if((int)$course['public_page_id']>0):?><a class="admin-button secondary" href="/editor/?page=<?=(int)$course['public_page_id']?>">Editar página pública</a><?php endif;?><?php if((int)($course['registration_form_id']??0)>0):?><a class="admin-button secondary" href="/admin/forms.php?activity=<?=$activityId?>&form=<?=(int)$course['registration_form_id']?>">Editar formulário</a><?php endif;?></div></form></section>

<?php elseif($view==='cohorts'):$cohorts=course_cohorts_for_course($db,$courseId);?>
<section class="admin-card"><header><div><h2>Turmas</h2><p>Turma é uma execução concreta do curso. Atribuir uma inscrição à turma cria o vínculo educacional correspondente.</p></div></header><?php if(!$cohorts):?><div class="admin-empty">Nenhuma turma cadastrada.</div><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Turma</th><th>Período</th><th>Alunos</th><th>Status</th></tr></thead><tbody><?php foreach($cohorts as $cohort):$q=$db->prepare("SELECT COUNT(*) FROM course_enrollments WHERE cohort_id=? AND status='active'");$q->execute([(int)$cohort['id']]);?><tr><td><strong><?=h((string)$cohort['title'])?></strong><div class="muted"><?=h((string)$cohort['slug'])?></div></td><td><?=h((string)($cohort['starts_at']?:'—'))?> → <?=h((string)($cohort['ends_at']?:'—'))?></td><td><?=(int)$q->fetchColumn()?></td><td><?=h((string)$cohort['status'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="admin-card"><header><div><h2>Nova turma</h2><p>Crie a turma somente quando houver uma execução concreta do curso a organizar.</p></div></header><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('courses-admin'))?>"><input type="hidden" name="action" value="create_cohort"><input type="hidden" name="course_id" value="<?=$courseId?>"><label class="admin-form-span-2">Nome<input name="title" required></label><label>Slug<input name="slug"></label><label>Início<input type="date" name="starts_at"></label><label>Fim<input type="date" name="ends_at"></label><div class="admin-form-actions"><button class="admin-button" type="submit">Criar turma</button></div></form></section>

<?php elseif($view==='students'):
$studentQ=trim((string)($_GET['q']??''));$studentPage=max(1,(int)($_GET['page']??1));$studentPageSize=50;$studentWhere=["c.course_id=?","e.status='active'","c.status!='archived'"];$studentArgs=[$courseId];if($studentQ!==''){$studentWhere[]='(u.name LIKE ? OR u.email LIKE ? OR p.cpf_last4 LIKE ? OR c.title LIKE ?)';$like='%'.$studentQ.'%';array_push($studentArgs,$like,$like,$like,$like);}$studentWhereSql=implode(' AND ',$studentWhere);$count=$db->prepare("SELECT COUNT(*) FROM course_enrollments e JOIN course_cohorts c ON c.id=e.cohort_id JOIN student_users u ON u.id=e.student_id LEFT JOIN student_profiles p ON p.student_id=u.id WHERE $studentWhereSql");$count->execute($studentArgs);$studentTotal=(int)$count->fetchColumn();$studentPages=max(1,(int)ceil($studentTotal/$studentPageSize));if($studentPage>$studentPages)$studentPage=$studentPages;$studentOffset=($studentPage-1)*$studentPageSize;$q=$db->prepare("SELECT u.id,u.name,u.email,p.cpf_last4,c.title cohort_title,e.confirmed_at FROM course_enrollments e JOIN course_cohorts c ON c.id=e.cohort_id JOIN student_users u ON u.id=e.student_id LEFT JOIN student_profiles p ON p.student_id=u.id WHERE $studentWhereSql ORDER BY u.name COLLATE NOCASE,u.id LIMIT $studentPageSize OFFSET $studentOffset");$q->execute($studentArgs);$students=$q->fetchAll();?>
<form class="admin-data-toolbar" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><input type="hidden" name="course" value="<?=$courseId?>"><input type="hidden" name="view" value="students"><label class="grow">Buscar aluno<input name="q" value="<?=h($studentQ)?>" placeholder="Nome, e-mail, CPF ou turma"></label><button class="admin-button secondary" type="submit">Buscar</button><?php if($studentQ!==''):?><a class="admin-button secondary" href="<?=h(course_students_url($activityId,$courseId))?>">Limpar</a><?php endif;?></form>
<section class="admin-card"><header><div><h2>Alunos</h2><p>Matrículas ativas deste curso. A identidade da pessoa continua global em Pessoas.</p></div><div class="admin-card-actions"><a class="admin-button secondary" href="/admin/people.php?activity=<?=$activityId?>">Abrir Pessoas</a></div></header><?php if(!$students):?><div class="admin-empty">Nenhum aluno encontrado.</div><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Aluno</th><th>CPF</th><th>Turma</th><th>Matrícula</th></tr></thead><tbody><?php foreach($students as $row):?><tr><td><a href="/admin/people.php?activity=<?=$activityId?>&person=<?=(int)$row['id']?>"><strong><?=h((string)$row['name'])?></strong></a><div class="muted"><?=h((string)$row['email'])?></div></td><td><?=$row['cpf_last4']?'***.'.h((string)$row['cpf_last4']):'—'?></td><td><?=h((string)$row['cohort_title'])?></td><td><?=h(date('d/m/Y',strtotime((string)$row['confirmed_at'])))?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<div class="admin-pagination"><span><?php if($studentTotal>0):?>Mostrando <?=($studentOffset+1)?>–<?=min($studentOffset+$studentPageSize,$studentTotal)?> de <?=$studentTotal?> aluno(s)<?php else:?>0 alunos<?php endif;?></span><?php if($studentPages>1):?><nav aria-label="Paginação de alunos"><?php if($studentPage>1):?><a href="<?=h(course_students_url($activityId,$courseId,$studentQ,$studentPage-1))?>">← Anterior</a><?php endif;?><span>Página <?=$studentPage?> de <?=$studentPages?></span><?php if($studentPage<$studentPages):?><a href="<?=h(course_students_url($activityId,$courseId,$studentQ,$studentPage+1))?>">Próxima →</a><?php endif;?></nav><?php endif;?></div>

<?php elseif($view==='lessons'):$lessons=course_lessons_for_course($db,$courseId);$cohorts=course_cohorts_for_course($db,$courseId);$releaseByCohort=[];foreach($cohorts as $cohort){$rows=course_lesson_release_rows_for_course($db,(int)$cohort['id'],$courseId);foreach($rows as $releaseRow)$releaseByCohort[(int)$cohort['id']][(int)$releaseRow['id']]=$releaseRow;}?>
<section class="admin-card"><header><div><h2>Aulas</h2><p>A aula é a unidade de liberação progressiva. O mesmo mapa vale para o curso; cada turma controla apenas o estado de liberação.</p></div></header><?php if(!$lessons):?><div class="admin-empty">Nenhuma aula cadastrada.</div><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Aula</th><?php foreach($cohorts as $cohort):?><th><?=h((string)$cohort['title'])?></th><?php endforeach;?></tr></thead><tbody><?php foreach($lessons as $lesson):?><tr><td><strong><?=h((string)$lesson['title'])?></strong><div class="muted"><?=h((string)$lesson['lesson_key'])?></div></td><?php foreach($cohorts as $cohort):$row=$releaseByCohort[(int)$cohort['id']][(int)$lesson['id']]??null;$stateLabel=cms_access_lesson_release_state($row['released_at']??null);?><td><form class="admin-inline-actions" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('courses-admin'))?>"><input type="hidden" name="action" value="set_release"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="cohort_id" value="<?=(int)$cohort['id']?>"><input type="hidden" name="lesson_id" value="<?=(int)$lesson['id']?>"><span><?=h($stateLabel)?></span><button class="admin-button secondary" name="mode" value="<?=$stateLabel==='released'?'block':'release'?>" type="submit"><?=$stateLabel==='released'?'Bloquear':'Liberar'?></button></form></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="admin-card"><header><div><h2>Nova aula</h2></div></header><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('courses-admin'))?>"><input type="hidden" name="action" value="add_lesson"><input type="hidden" name="course_id" value="<?=$courseId?>"><label>Nome<input name="title" required></label><label>Chave<input name="lesson_key" placeholder="aula-1"></label><div class="admin-form-actions"><button class="admin-button" type="submit">Criar aula</button></div></form></section>

<?php elseif($view==='material'):$materialPages=course_material_pages($db,$courseId);$lessons=course_lessons_for_course($db,$courseId);$materialIds=array_fill_keys(array_map(static fn(array $p): int=>(int)$p['id'],$materialPages),true);?>
<section class="admin-card"><header><div><h2>Material</h2><p>Material é uma visão contextual das mesmas páginas do CMS. Não existe editor ou conteúdo paralelo.</p></div><div class="admin-card-actions"><a class="admin-button secondary" href="/admin/pages.php?activity=<?=$activityId?>">Abrir Páginas</a></div></header><?php if(!$materialPages):?><div class="admin-empty">Nenhuma página associada.</div><?php endif;?><?php foreach($materialPages as $page):$sections=course_material_sections_from_page($db,(int)$page['id']);$map=course_material_section_map($db,$courseId,(int)$page['id']);?><section class="admin-card"><header><div><p class="admin-kicker">Página CMS</p><h3><?=h((string)$page['title'])?></h3></div><div class="admin-card-actions"><a class="admin-button secondary" href="/editor/?page=<?=(int)$page['id']?>">Editar página</a><form method="post" data-confirm="Remover esta página do material do curso? A página não será excluída."><input type="hidden" name="_csrf" value="<?=h(csrf_token('courses-admin'))?>"><input type="hidden" name="action" value="remove_material"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="page_id" value="<?=(int)$page['id']?>"><button class="admin-button secondary" type="submit">Desassociar</button></form></div></header><?php if(!$sections):?><div class="admin-empty compact">A página não possui seções CMS identificáveis no rascunho atual.</div><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Seção</th><th>Liberação</th></tr></thead><tbody><?php foreach($sections as $key=>$label):$lessonId=(int)($map[$key]['lesson_id']??0);?><tr><td><strong><?=h($label)?></strong><div class="muted"><?=h($key)?></div></td><td><form class="admin-inline-actions" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('courses-admin'))?>"><input type="hidden" name="action" value="map_section"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="page_id" value="<?=(int)$page['id']?>"><input type="hidden" name="section_key" value="<?=h($key)?>"><select name="lesson_id"><option value="0">Sempre disponível</option><?php foreach($lessons as $lesson):?><option value="<?=(int)$lesson['id']?>"<?=$lessonId===(int)$lesson['id']?' selected':''?>><?=h((string)$lesson['title'])?></option><?php endforeach;?></select><button class="admin-button secondary" type="submit">Salvar</button></form></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section><?php endforeach;?></section>
<section class="admin-card"><header><div><h2>Associar página existente</h2><p>A página permanece na biblioteca editorial global e continua usando o editor CMS normal.</p></div></header><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('courses-admin'))?>"><input type="hidden" name="action" value="add_material"><input type="hidden" name="course_id" value="<?=$courseId?>"><label class="admin-form-span-2">Página<select name="page_id" required><option value="">Escolha</option><?php foreach($pages as $page):if(isset($materialIds[(int)$page['id']]))continue;?><option value="<?=(int)$page['id']?>"><?=h((string)$page['title'].' · '.public_language_label((string)$page['locale']))?></option><?php endforeach;?></select></label><div class="admin-form-actions"><button class="admin-button" type="submit">Associar ao material</button></div></form></section>
<?php endif;?>
<?php endif;?>
<?php admin_shell_end();
