<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/admin_shell.php';security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];$locale=normalize_public_locale($_GET['lang']??$_POST['locale']??PUBLIC_LOCALE_PT_BR)??PUBLIC_LOCALE_PT_BR;
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('cms-design',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}
    $defaults=cms_design_defaults();$settings=[
        'colors'=>array_intersect_key($_POST['colors']??[],$defaults['colors']),
        'layout'=>array_intersect_key($_POST['layout']??[],$defaults['layout']),
        'type'=>array_intersect_key($_POST['type']??[],$defaults['type']),
        'buttons'=>array_intersect_key($_POST['buttons']??[],$defaults['buttons']),
        'advanced'=>['customCss'=>(string)($_POST['advanced']['customCss']??'')],
    ];
    cms_settings_save($db,'design',$activityId,$locale,$settings);$_SESSION['admin_notice']='Design atualizado.';header('Location: /admin/design.php?activity='.$activityId.'&lang='.rawurlencode(public_locale_query($locale)));exit;
}
$design=cms_design_settings($db,$activityId,$locale);$home=cms_page_home($db,$activityId,$locale);$notice=$_SESSION['admin_notice']??null;unset($_SESSION['admin_notice']);
function d_input(string $label,string $name,mixed $value,string $type='number',string $extra=''):void{?><label><?=$label?><input type="<?=$type?>" name="<?=$name?>" value="<?=h((string)$value)?>" <?=$extra?>></label><?php }
admin_shell_start('design','Design',$state);?>
<?php if($notice):?><div class="admin-notice"><?=h((string)$notice)?></div><?php endif;?>
<section class="overview-hero"><div><p class="admin-kicker">Sistema visual</p><h2>Controle global do site</h2><p>Tipografia, cor, largura, espaçamento e botões são tokens globais. Você altera uma vez e todas as páginas que herdam o sistema visual acompanham.</p></div><div class="hero-actions"><a class="admin-button" href="/admin/design.php?activity=<?=$activityId?>&lang=pt-br"<?=$locale===PUBLIC_LOCALE_PT_BR?' aria-current="page"':''?>>PT</a><a class="admin-button" href="/admin/design.php?activity=<?=$activityId?>&lang=en"<?=$locale===PUBLIC_LOCALE_EN?' aria-current="page"':''?>>EN</a></div></section>
<?php if($home):?><section class="design-preview-panel"><header><div><p class="admin-kicker">Prévia ao vivo</p><h2>Página inicial</h2><p class="admin-muted">Os controles abaixo afetam esta prévia antes de salvar.</p></div><div class="design-preview-actions"><button type="button" data-design-viewport="desktop" class="active">Desktop</button><button type="button" data-design-viewport="tablet">Tablet</button><button type="button" data-design-viewport="mobile">Mobile</button><select id="design-preview-theme" aria-label="Tema da prévia"><option value="auto">Auto</option><option value="light">Claro</option><option value="dark">Escuro</option></select></div></header><div class="design-preview-device desktop" id="design-preview-device"><iframe id="design-preview-frame" src="/preview/?page=<?=(int)$home['id']?>" title="Prévia do design"></iframe></div></section><?php endif;?>
<form class="admin-editor-card cms-settings-form" method="post" id="cms-design-form"><input type="hidden" name="_csrf" value="<?=h(csrf_token('cms-design'))?>"><input type="hidden" name="locale" value="<?=h($locale)?>">
<section><p class="admin-kicker">Cores · tema claro</p><div class="form-grid two-columns"><?php foreach(['bg'=>'Fundo','surface'=>'Superfície','surface2'=>'Superfície secundária','text'=>'Texto','muted'=>'Texto secundário','line'=>'Linhas','accent'=>'Destaque','buttonBg'=>'Botão · fundo','buttonText'=>'Botão · texto','buttonBorder'=>'Botão · borda'] as $key=>$label)d_input($label,"colors[$key]",$design['colors'][$key],'color');?></div></section>
<section><p class="admin-kicker">Cores · tema escuro</p><div class="form-grid two-columns"><?php foreach(['darkBg'=>'Fundo','darkSurface'=>'Superfície','darkSurface2'=>'Superfície secundária','darkText'=>'Texto','darkMuted'=>'Texto secundário','darkLine'=>'Linhas','darkAccent'=>'Destaque','darkButtonBg'=>'Botão · fundo','darkButtonText'=>'Botão · texto','darkButtonBorder'=>'Botão · borda'] as $key=>$label)d_input($label,"colors[$key]",$design['colors'][$key],'color');?></div></section>
<section><p class="admin-kicker">Layout global</p><div class="form-grid two-columns"><?php d_input('Largura máxima (px)','layout[maxWidth]',$design['layout']['maxWidth'],'number','min="900" max="2200"');d_input('Conteúdo estreito (px)','layout[contentNarrow]',$design['layout']['contentNarrow'],'number','min="560" max="1400"');d_input('Gutter mínimo (px)','layout[gutterMin]',$design['layout']['gutterMin']);d_input('Gutter fluido (vw)','layout[gutterVw]',$design['layout']['gutterVw'],'number','step="0.1"');d_input('Gutter máximo (px)','layout[gutterMax]',$design['layout']['gutterMax']);d_input('Seção mínima (px)','layout[sectionMin]',$design['layout']['sectionMin']);d_input('Seção fluida (vw)','layout[sectionVw]',$design['layout']['sectionVw'],'number','step="0.1"');d_input('Seção máxima (px)','layout[sectionMax]',$design['layout']['sectionMax']);?></div></section>
<section><p class="admin-kicker">Tipografia</p><div class="form-grid two-columns"><?php d_input('Fonte do corpo','type[bodyFont]',$design['type']['bodyFont'],'text');d_input('Fonte de títulos','type[displayFont]',$design['type']['displayFont'],'text');d_input('Fonte técnica/mono','type[monoFont]',$design['type']['monoFont'],'text');d_input('Corpo (px)','type[bodySize]',$design['type']['bodySize']);d_input('Entrelinha do corpo','type[bodyLineHeight]',$design['type']['bodyLineHeight'],'number','step="0.01" min="1.1" max="2.2"');d_input('Entrelinha de títulos','type[displayLineHeight]',$design['type']['displayLineHeight'],'number','step="0.01" min="1" max="1.4"');d_input('Tracking global (px)','type[letterSpacing]',$design['type']['letterSpacing'],'number','step="0.1" min="-3" max="8"');d_input('H1 mínimo (px)','type[h1Min]',$design['type']['h1Min']);d_input('H1 fluido (vw)','type[h1Vw]',$design['type']['h1Vw'],'number','step="0.1"');d_input('H1 máximo (px)','type[h1Max]',$design['type']['h1Max']);d_input('H2 mínimo (px)','type[h2Min]',$design['type']['h2Min']);d_input('H2 fluido (vw)','type[h2Vw]',$design['type']['h2Vw'],'number','step="0.1"');d_input('H2 máximo (px)','type[h2Max]',$design['type']['h2Max']);d_input('H3 (px)','type[h3Size]',$design['type']['h3Size']);d_input('Texto de destaque (px)','type[leadSize]',$design['type']['leadSize']);d_input('Texto pequeno (px)','type[smallSize]',$design['type']['smallSize']);?></div><p class="admin-muted">Os padrões usam as fontes já aprovadas no site: <code>var(--sans)</code>, <code>var(--title)</code> e <code>var(--mono)</code>. Você pode substituir por uma pilha CSS válida.</p></section>
<section><p class="admin-kicker">Botões</p><div class="form-grid two-columns"><?php d_input('Altura mínima (px)','buttons[height]',$design['buttons']['height']);d_input('Raio dos cantos (px)','buttons[radius]',$design['buttons']['radius']);d_input('Borda (px)','buttons[borderWidth]',$design['buttons']['borderWidth']);d_input('Padding horizontal (px)','buttons[paddingX]',$design['buttons']['paddingX']);?></div></section>
<section><p class="admin-kicker">Avançado</p><label>CSS adicional<textarea name="advanced[customCss]" rows="12" spellcheck="false" placeholder="/* opcional */"><?=h((string)$design['advanced']['customCss'])?></textarea></label><p class="admin-muted">Escape hatch para ajustes muito específicos. O editor visual continua sendo o caminho principal; este campo existe para você não ficar bloqueado por uma propriedade que ainda não ganhou controle gráfico.</p></section>
<div class="dialog-actions"><button class="admin-button" type="submit">Salvar design</button><a class="link-button" href="<?=h(admin_public_activity_url($activity).'?lang='.public_locale_query($locale))?>" target="_blank" rel="noopener">Ver site</a></div></form>
<script src="/assets/design-admin.js"></script>
<?php admin_shell_end();
