<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
security_headers();
require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];$locale=normalize_public_locale($_GET['lang']??$_POST['locale']??PUBLIC_LOCALE_PT_BR)??PUBLIC_LOCALE_PT_BR;
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('cms-design',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}
    $defaults=cms_design_defaults();$settings=['colors'=>array_intersect_key($_POST['colors']??[],$defaults['colors']),'layout'=>array_intersect_key($_POST['layout']??[],$defaults['layout']),'type'=>array_intersect_key($_POST['type']??[],$defaults['type']),'buttons'=>array_intersect_key($_POST['buttons']??[],$defaults['buttons']),'advanced'=>['customCss'=>(string)($_POST['advanced']['customCss']??'')]];
    cms_settings_save($db,'design',$activityId,$locale,$settings);$_SESSION['admin_notice']='Design atualizado.';header('Location: /admin/design.php?activity='.$activityId.'&lang='.rawurlencode(public_locale_query($locale)));exit;
}
$design=cms_design_settings($db,$activityId,$locale);$home=cms_page_home($db,$activityId,$locale);$notice=$_SESSION['admin_notice']??null;unset($_SESSION['admin_notice']);
function d_input(string $label,string $name,mixed $value,string $type='number',string $extra=''):void{?><label><?=$label?><input type="<?=$type?>" name="<?=$name?>" value="<?=h((string)$value)?>" <?=$extra?>></label><?php }
function d_font_select(string $label,string $name,string $value,string $role):void{$fonts=cms_design_google_fonts()[$role]??[];?><label><?=$label?><select name="<?=$name?>" data-design-font-role="<?=h($role)?>"><?php foreach($fonts as $family=>$meta):$stack=cms_design_font_stack((string)$family,$role);?><option value="<?=h((string)$family)?>" data-font-stack="<?=h($stack)?>" data-font-weights="<?=h((string)$meta['weights'])?>"<?=$value===$family?' selected':''?>><?=h((string)$family)?></option><?php endforeach;?></select></label><?php }
admin_shell_start('design','Design',$state,['/assets/admin-site.css']);?>
<?php if($notice):?><div class="admin-notice"><?=h((string)$notice)?></div><?php endif;?>
<section class="site-intro"><p class="site-intro-copy">Controle o sistema visual herdado pelas páginas: cor, tipografia, largura, ritmo e botões. Ajustes específicos devem permanecer exceção, não a base do layout.</p><div class="site-intro-actions"><div class="site-language-switch" aria-label="Idioma do design"><a href="/admin/design.php?activity=<?=$activityId?>&lang=pt-br"<?=$locale===PUBLIC_LOCALE_PT_BR?' aria-current="page"':''?>>PT</a><a href="/admin/design.php?activity=<?=$activityId?>&lang=en"<?=$locale===PUBLIC_LOCALE_EN?' aria-current="page"':''?>>EN</a></div></div></section>
<nav class="site-section-nav" aria-label="Seções do sistema visual"><a href="#visual-preview">Prévia</a><a href="#visual-colors">Cores</a><a href="#visual-layout">Layout</a><a href="#visual-type">Tipografia</a><a href="#visual-buttons">Botões</a><a href="#visual-advanced">Avançado</a></nav>
<?php if($home):?><section class="site-design-preview design-preview-panel" id="visual-preview"><header><div><h2>Prévia ao vivo · Página inicial</h2><p>Os controles abaixo afetam esta prévia antes de salvar.</p></div><div class="design-preview-actions"><button type="button" data-design-viewport="desktop" class="active">Desktop</button><button type="button" data-design-viewport="tablet">Tablet</button><button type="button" data-design-viewport="mobile">Mobile</button><select id="design-preview-theme" aria-label="Tema da prévia"><option value="auto">Auto</option><option value="light">Claro</option><option value="dark">Escuro</option></select></div></header><div class="design-preview-device desktop" id="design-preview-device"><iframe id="design-preview-frame" src="/preview/?page=<?=(int)$home['id']?>" title="Prévia do design"></iframe></div></section><?php endif;?>
<form method="post" id="cms-design-form"><input type="hidden" name="_csrf" value="<?=h(csrf_token('cms-design'))?>"><input type="hidden" name="locale" value="<?=h($locale)?>"><div class="site-settings-stack">
<section class="site-settings-section" id="visual-colors"><header><div><h2>Cores</h2><p>Paleta semântica dos temas claro e escuro. Os mesmos papéis são reutilizados por todas as páginas.</p></div></header><h3>Tema claro</h3><div class="form-grid two-columns"><?php foreach(['bg'=>'Fundo','surface'=>'Superfície','surface2'=>'Superfície secundária','text'=>'Texto','muted'=>'Texto secundário','line'=>'Linhas','accent'=>'Destaque','buttonBg'=>'Botão · fundo','buttonText'=>'Botão · texto','buttonBorder'=>'Botão · borda'] as $key=>$label)d_input($label,"colors[$key]",$design['colors'][$key],'color');?></div><h3 class="admin-block-gap">Tema escuro</h3><div class="form-grid two-columns"><?php foreach(['darkBg'=>'Fundo','darkSurface'=>'Superfície','darkSurface2'=>'Superfície secundária','darkText'=>'Texto','darkMuted'=>'Texto secundário','darkLine'=>'Linhas','darkAccent'=>'Destaque','darkButtonBg'=>'Botão · fundo','darkButtonText'=>'Botão · texto','darkButtonBorder'=>'Botão · borda'] as $key=>$label)d_input($label,"colors[$key]",$design['colors'][$key],'color');?></div></section>
<section class="site-settings-section" id="visual-layout"><header><div><h2>Layout global</h2><p>Largura de conteúdo, gutters e espaçamento vertical das seções.</p></div></header><div class="form-grid two-columns"><?php d_input('Largura máxima (px)','layout[maxWidth]',$design['layout']['maxWidth'],'number','min="900" max="2200"');d_input('Conteúdo estreito (px)','layout[contentNarrow]',$design['layout']['contentNarrow'],'number','min="560" max="1400"');d_input('Gutter mínimo (px)','layout[gutterMin]',$design['layout']['gutterMin']);d_input('Gutter fluido (vw)','layout[gutterVw]',$design['layout']['gutterVw'],'number','step="0.1"');d_input('Gutter máximo (px)','layout[gutterMax]',$design['layout']['gutterMax']);d_input('Seção mínima (px)','layout[sectionMin]',$design['layout']['sectionMin']);d_input('Seção fluida (vw)','layout[sectionVw]',$design['layout']['sectionVw'],'number','step="0.1"');d_input('Seção máxima (px)','layout[sectionMax]',$design['layout']['sectionMax']);?></div></section>
<section class="site-settings-section" id="visual-type"><header><div><h2>Tipografia</h2><p>Famílias, escalas e métricas globais para corpo e títulos.</p></div></header><div class="form-grid two-columns"><?php d_font_select('Fonte do corpo','type[bodyFont]',(string)$design['type']['bodyFont'],'body');d_font_select('Fonte de títulos','type[displayFont]',(string)$design['type']['displayFont'],'display');d_font_select('Fonte técnica/mono','type[monoFont]',(string)$design['type']['monoFont'],'mono');d_input('Corpo (px)','type[bodySize]',$design['type']['bodySize']);d_input('Entrelinha do corpo','type[bodyLineHeight]',$design['type']['bodyLineHeight'],'number','step="0.01" min="1.1" max="2.2"');d_input('Entrelinha de títulos','type[displayLineHeight]',$design['type']['displayLineHeight'],'number','step="0.01" min="1" max="1.4"');d_input('Tracking global (px)','type[letterSpacing]',$design['type']['letterSpacing'],'number','step="0.1" min="-3" max="8"');d_input('H1 mínimo (px)','type[h1Min]',$design['type']['h1Min']);d_input('H1 fluido (vw)','type[h1Vw]',$design['type']['h1Vw'],'number','step="0.1"');d_input('H1 máximo (px)','type[h1Max]',$design['type']['h1Max']);d_input('H2 mínimo (px)','type[h2Min]',$design['type']['h2Min']);d_input('H2 fluido (vw)','type[h2Vw]',$design['type']['h2Vw'],'number','step="0.1"');d_input('H2 máximo (px)','type[h2Max]',$design['type']['h2Max']);d_input('H3 (px)','type[h3Size]',$design['type']['h3Size']);d_input('Texto de destaque (px)','type[leadSize]',$design['type']['leadSize']);d_input('Texto pequeno (px)','type[smallSize]',$design['type']['smallSize']);?></div></section>
<section class="site-settings-section" id="visual-buttons"><header><div><h2>Botões</h2><p>Dimensões compartilhadas por ações primárias e secundárias.</p></div></header><div class="form-grid two-columns"><?php d_input('Altura mínima (px)','buttons[height]',$design['buttons']['height']);d_input('Raio dos cantos (px)','buttons[radius]',$design['buttons']['radius']);d_input('Borda (px)','buttons[borderWidth]',$design['buttons']['borderWidth']);d_input('Padding horizontal (px)','buttons[paddingX]',$design['buttons']['paddingX']);?></div></section>
<section class="site-settings-section" id="visual-advanced"><header><div><h2>Avançado</h2><p>Escape hatch para uma necessidade ainda não coberta pelo sistema visual. Evite usar este campo para corrigir componentes existentes.</p></div></header><details class="site-advanced"<?=trim((string)$design['advanced']['customCss'])!==''?' open':''?>><summary>CSS adicional</summary><label>CSS adicional<textarea name="advanced[customCss]" rows="12" spellcheck="false" placeholder="/* opcional */"><?=h((string)$design['advanced']['customCss'])?></textarea></label></details></section>
</div><div class="site-savebar"><a class="link-button" href="<?=h(admin_public_activity_url($activity).'?lang='.public_locale_query($locale))?>" target="_blank" rel="noopener">Ver site ↗</a><button class="admin-button" type="submit">Salvar visual</button></div></form>
<script src="<?=h(admin_asset_url('/assets/design-admin.js'))?>"></script>
<?php admin_shell_end();
