<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/admin_shell.php';security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];cms_forms_seed($db,$activityId);
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('cms-forms',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}
    $action=(string)($_POST['action']??'');$redirectForm=0;
    try{
        if($action==='create'){$form=cms_form_create($db,$activityId,(string)($_POST['locale']??PUBLIC_LOCALE_PT_BR),(string)($_POST['title']??'Novo formulário'),(string)($_POST['form_key']??'form'),(string)($_POST['kind']??'interest'));header('Location: /admin/forms.php?activity='.$activityId.'&form='.(int)$form['id']);exit;}
        if($action==='archive'){cms_form_archive($db,(int)($_POST['form_id']??0));}
        if($action==='save-workflow'){
            $redirectForm=(int)($_POST['form_id']??0);$form=cms_form_by_id($db,$redirectForm);if(!$form||(int)$form['activity_id']!==$activityId)throw new RuntimeException('form_not_found');
            $schema=cms_form_schema($form,false);$schema=cms_form_workflow_update($schema,$_POST);$form=cms_form_save($db,(int)$form['id'],$schema,(int)$form['draft_revision'],null);
            if(!empty($_POST['publish_workflow'])){$form=cms_form_publish($db,(int)$form['id']);$_SESSION['admin_notice']='Fluxo salvo e publicado.';}else $_SESSION['admin_notice']='Fluxo salvo no rascunho.';
        }
        if($action==='save-conditions'){
            $redirectForm=(int)($_POST['form_id']??0);$form=cms_form_by_id($db,$redirectForm);if(!$form||(int)$form['activity_id']!==$activityId)throw new RuntimeException('form_not_found');
            $schema=cms_form_schema($form,false);$schema=cms_form_conditions_update($schema,$_POST);$form=cms_form_save($db,(int)$form['id'],$schema,(int)$form['draft_revision'],null);
            if(!empty($_POST['publish_conditions'])){$form=cms_form_publish($db,(int)$form['id']);$_SESSION['admin_notice']='Condições salvas e publicadas.';}else $_SESSION['admin_notice']='Condições salvas no rascunho.';
        }
    }catch(RuntimeException $error){$_SESSION['admin_notice']=$error->getMessage();}
    header('Location: /admin/forms.php?activity='.$activityId.($redirectForm?'&form='.$redirectForm:''));exit;
}
$forms=cms_forms($db,$activityId,null,false);$selectedId=(int)($_GET['form']??0);$selected=$selectedId?cms_form_by_id($db,$selectedId):null;$notice=$_SESSION['admin_notice']??null;unset($_SESSION['admin_notice']);
$draftSchema=$selected?cms_form_schema($selected,false):null;$workflow=$draftSchema?cms_form_workflow($draftSchema):null;$conditions=$draftSchema?cms_form_conditions($draftSchema):[];$conditionFields=is_array($draftSchema['fields']??null)?$draftSchema['fields']:[];
admin_shell_start('forms','Formulários',$state);?>
<?php if($notice):?><div class="admin-notice"><?=h((string)$notice)?></div><?php endif;?>
<section class="overview-hero"><div><p class="admin-kicker">Formulários próprios</p><h2>Inscrições e pesquisas dentro do site</h2><p>Campos, mensagens, condições, destino após envio e notificações podem ser administrados aqui. As respostas continuam armazenadas no próprio sistema e podem ser exportadas.</p></div><div class="hero-actions"><button class="admin-button" type="button" data-dialog-open="new-form">Novo formulário</button></div></section>
<section class="overview-grid"><?php foreach($forms as $form):$unpublished=$form['published_revision']===null||(int)$form['draft_revision']!==(int)$form['published_revision'];?><article class="overview-card"><p class="admin-kicker"><?=h(public_language_label($form['locale']))?> · <?=h($form['form_key'])?></p><h2><?=h($form['title'])?></h2><p><?= $unpublished?'Há alterações não publicadas.':'Publicado e atualizado.' ?></p><a href="/admin/forms.php?activity=<?=$activityId?>&form=<?=(int)$form['id']?>">Editar formulário</a><form method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('cms-forms'))?>"><input type="hidden" name="form_id" value="<?=(int)$form['id']?>"><button class="link-button danger" name="action" value="archive" data-confirm="Arquivar este formulário?">Arquivar</button></form></article><?php endforeach;?></section>
<?php if($selected&&$selected['status']!=='archived'):?>
<section class="admin-editor-card"><div class="admin-editor-header"><div><p class="admin-kicker">Editor de formulário</p><h2><?=h($selected['title'])?></h2></div><p>As alterações ficam em rascunho até serem publicadas.</p></div><div id="form-admin-root" data-form-id="<?=(int)$selected['id']?>"></div></section><script src="/assets/forms-admin.js"></script>
<section class="admin-editor-card"><div class="admin-editor-header"><div><p class="admin-kicker">Lógica condicional</p><h2>Mostrar campos somente quando fizer sentido</h2></div><p>Cada campo pode depender de uma resposta anterior. Campos ocultos não são exigidos nem enviados como resposta ativa.</p></div>
<form method="post" class="cms-settings-form"><input type="hidden" name="_csrf" value="<?=h(csrf_token('cms-forms'))?>"><input type="hidden" name="action" value="save-conditions"><input type="hidden" name="form_id" value="<?=(int)$selected['id']?>">
<div class="conditions-builder"><div class="conditions-head"><strong>Campo</strong><strong>Mostrar quando</strong><strong>Operador</strong><strong>Valor</strong></div>
<?php foreach($conditionFields as $target):$targetId=(string)($target['id']??'');if($targetId==='')continue;$rule=$conditions[$targetId]??['source'=>'','operator'=>'equals','value'=>''];?>
<div class="condition-row"><div><strong><?=h((string)($target['label']??$targetId))?></strong><small><?=h($targetId)?></small></div><label><span class="sr-only">Campo de origem</span><select name="condition_source[<?=h($targetId)?>]"><option value="">Sempre mostrar</option><?php foreach($conditionFields as $source):$sourceId=(string)($source['id']??'');if($sourceId===''||$sourceId===$targetId)continue;?><option value="<?=h($sourceId)?>"<?=$rule['source']===$sourceId?' selected':''?>><?=h((string)($source['label']??$sourceId))?></option><?php endforeach;?></select></label><label><span class="sr-only">Operador</span><select name="condition_operator[<?=h($targetId)?>]"><?php foreach(['equals'=>'é igual a','not_equals'=>'é diferente de','contains'=>'contém','checked'=>'está marcado / preenchido','not_checked'=>'não está marcado / está vazio'] as $op=>$label):?><option value="<?=$op?>"<?=$rule['operator']===$op?' selected':''?>><?=h($label)?></option><?php endforeach;?></select></label><label><span class="sr-only">Valor esperado</span><input name="condition_value[<?=h($targetId)?>]" value="<?=h((string)$rule['value'])?>" placeholder="valor/opção"></label></div>
<?php endforeach;?></div>
<p class="admin-muted">Para listas, rádio e múltipla escolha, use o <strong>valor</strong> interno da opção — ele aparece no editor de campos. “Marcado / preenchido” funciona bem para checkbox, aceite e campos em que basta existir uma resposta.</p>
<div class="dialog-actions"><button class="admin-button" type="submit">Salvar condições</button><label class="check-row"><input type="checkbox" name="publish_conditions" value="1"> Salvar e publicar imediatamente</label></div></form></section>
<section class="admin-editor-card"><div class="admin-editor-header"><div><p class="admin-kicker">Fluxo após envio</p><h2>Confirmação e notificação</h2></div><p>Configure o que acontece depois que uma resposta válida é gravada.</p></div>
<form method="post" class="cms-settings-form"><input type="hidden" name="_csrf" value="<?=h(csrf_token('cms-forms'))?>"><input type="hidden" name="action" value="save-workflow"><input type="hidden" name="form_id" value="<?=(int)$selected['id']?>">
<div class="form-grid two-columns"><label>Depois do envio<select name="success_mode"><option value="inline"<?=$workflow['successMode']==='inline'?' selected':''?>>Mostrar confirmação no próprio formulário</option><option value="redirect"<?=$workflow['successMode']==='redirect'?' selected':''?>>Redirecionar para outra página</option></select></label><label>Caminho de redirecionamento<input name="redirect_path" value="<?=h($workflow['redirectPath'])?>" placeholder="/obrigado/?lang=pt-br"></label></div>
<p class="admin-muted">O redirecionamento aceita somente um caminho interno começando por <code>/</code>. Isso evita que o formulário seja usado como redirecionador externo.</p>
<div class="form-grid two-columns"><label>E-mail para notificação<input type="email" name="notification_email" value="<?=h($workflow['notificationEmail'])?>" placeholder="voce@exemplo.com"></label><label>Assunto da notificação<input name="notification_subject" value="<?=h($workflow['notificationSubject'])?>" placeholder="Nova inscrição pelo site"></label></div>
<p class="admin-muted">Se um e-mail for informado, o sistema tenta enviar um resumo usando o serviço de e-mail do servidor. A resposta é salva mesmo se o envio da notificação falhar.</p>
<div class="dialog-actions"><button class="admin-button" type="submit">Salvar fluxo</button><label class="check-row"><input type="checkbox" name="publish_workflow" value="1"> Salvar e publicar imediatamente</label></div></form></section>
<?php endif;?>
<dialog id="new-form" class="admin-dialog"><form method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('cms-forms'))?>"><input type="hidden" name="action" value="create"><header><p class="admin-kicker">Novo formulário</p><h2>Criar formulário</h2></header><label>Título<input name="title" required></label><label>Chave<input name="form_key" placeholder="ex.: inscricao" required></label><label>Idioma<select name="locale"><option value="pt-BR">Português (Brasil)</option><option value="en">English</option></select></label><label>Modelo inicial<select name="kind"><option value="registration">Inscrição</option><option value="interest">Pesquisa de interesse</option></select></label><div class="dialog-actions"><button type="button" data-dialog-close>Cancelar</button><button class="admin-button" type="submit">Criar</button></div></form></dialog>
<style>.conditions-builder{border:1px solid #d8d8d2}.conditions-head,.condition-row{display:grid;grid-template-columns:minmax(180px,1fr) minmax(180px,1fr) minmax(180px,.8fr) minmax(150px,.8fr);gap:12px;padding:12px 14px;align-items:center}.conditions-head{background:#f3f3ef;font-size:12px;text-transform:uppercase;letter-spacing:.04em}.condition-row{border-top:1px solid #d8d8d2}.condition-row:first-of-type{border-top:0}.condition-row>div{display:flex;flex-direction:column}.condition-row small{color:#777}.condition-row label{margin:0}.condition-row select,.condition-row input{width:100%;box-sizing:border-box}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}@media(max-width:1050px){.conditions-head{display:none}.condition-row{grid-template-columns:1fr}.condition-row label{display:block}}</style>
<?php admin_shell_end();
