<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/admin_shell.php';security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];
if(!$activity){admin_shell_start('overview','Visão geral',$state);?><section class="admin-empty"><h2>Crie o primeiro site</h2><p>Configure a identidade do site para começar a editar páginas, cursos, inscrições e mídia.</p><a class="admin-button" href="/admin/activities.php">Configurar site</a></section><?php admin_shell_end();exit;}
$id=(int)$activity['id'];cms_pages_seed($db,$id);cms_forms_seed($db,$id);$pages=cms_pages($db,$id);$forms=cms_forms($db,$id);$courses=course_list($db,$id);
$home=null;foreach($pages as $candidate){if(($candidate['locale']??'')===PUBLIC_LOCALE_PT_BR&&(int)($candidate['is_home']??0)===1){$home=$candidate;break;}}if(!$home){foreach($pages as $candidate)if((int)($candidate['is_home']??0)===1){$home=$candidate;break;}}if(!$home&&$pages)$home=$pages[0];
$pendingPages=array_values(array_filter($pages,static fn(array $page): bool=>(int)($page['draft_revision']??0)!==(int)($page['published_revision']??0)||empty($page['published_document_json'])));$pendingForms=array_values(array_filter($forms,static fn(array $form): bool=>(int)($form['draft_revision']??0)!==(int)($form['published_revision']??0)||empty($form['published_schema_json'])));$publicationPending=count($pendingPages)+count($pendingForms);
$analytics=analytics_dashboard($db,$id,30);$analyticsCounts=$analytics['counts'];$analyticsRates=$analytics['rates'];
$courseRows=[];$teaching=['pending_payment'=>0,'unassigned'=>0,'questions'=>0,'tests'=>0];foreach($courses as $course){$attention=admin_course_attention($db,(int)$course['id']);foreach($teaching as $key=>$value)$teaching[$key]+=(int)$attention[$key];$cohorts=course_cohorts_for_course($db,(int)$course['id']);$students=0;foreach($cohorts as $cohort){$stats=admin_course_cohort_stats($db,(int)$course['id'],(int)$cohort['id']);$students+=$stats['students'];}$courseRows[]=['course'=>$course,'attention'=>$attention,'cohorts'=>count($cohorts),'students'=>$students];}
$homeUrl=$home?'/editor/?page='.(int)$home['id']:'/admin/pages.php?activity='.$id;
admin_shell_start('overview','Visão geral',$state,['/assets/admin-teaching.css']);?>
<section class="admin-card"><header><div><h2>Trabalho em aberto</h2><p>O que precisa de uma decisão ou resposta agora.</p></div><a class="admin-button secondary" href="/admin/courses.php?activity=<?=$id?>">Abrir cursos</a></header><div class="admin-work-queue">
<?php if(array_sum($teaching)===0):?><div class="admin-empty compact">Nenhuma pendência de curso neste momento.</div><?php endif;?>
<?php if($teaching['pending_payment']>0):?><a class="admin-work-item" href="/admin/courses.php?activity=<?=$id?>"><strong><?=$teaching['pending_payment']?> pagamento(s) aguardando confirmação</strong><span>Abrir cursos</span></a><?php endif;?>
<?php if($teaching['unassigned']>0):?><a class="admin-work-item" href="/admin/courses.php?activity=<?=$id?>"><strong><?=$teaching['unassigned']?> inscrição(ões) paga(s) sem turma</strong><span>Atribuir turma</span></a><?php endif;?>
<?php if($teaching['tests']>0):?><a class="admin-work-item" href="/admin/courses.php?activity=<?=$id?>"><strong><?=$teaching['tests']?> teste(s) aguardando acompanhamento</strong><span>Avaliar</span></a><?php endif;?>
<?php if($teaching['questions']>0):?><a class="admin-work-item" href="/admin/courses.php?activity=<?=$id?>"><strong><?=$teaching['questions']?> dúvida(s) aberta(s)</strong><span>Responder</span></a><?php endif;?>
</div></section>
<section class="admin-card"><header><div><h2>Cursos</h2><p><?=count($courses)?> curso(s) ativo(s).</p></div><a class="admin-button secondary" href="/admin/courses.php?activity=<?=$id?>">Gerenciar cursos</a></header><?php if(!$courseRows):?><div class="admin-empty">Nenhum curso configurado.</div><?php else:?><div class="admin-table-scroll" tabindex="0"><table class="admin-data-table"><thead><tr><th>Curso</th><th>Turmas</th><th>Alunos</th><th>Precisa de atenção</th><th></th></tr></thead><tbody><?php foreach($courseRows as $item):$course=$item['course'];$attention=$item['attention'];$n=array_sum($attention);?><tr><td><strong><?=h((string)$course['title'])?></strong></td><td class="admin-table-number"><?=(int)$item['cohorts']?></td><td class="admin-table-number"><?=(int)$item['students']?></td><td><?php if($n===0):?><span class="muted">Nada pendente</span><?php else:?><div class="admin-table-compact-counts"><?php if($attention['pending_payment']):?><span><strong><?=$attention['pending_payment']?></strong> pagamentos</span><?php endif;?><?php if($attention['unassigned']):?><span><strong><?=$attention['unassigned']?></strong> sem turma</span><?php endif;?><?php if($attention['tests']):?><span><strong><?=$attention['tests']?></strong> testes</span><?php endif;?><?php if($attention['questions']):?><span><strong><?=$attention['questions']?></strong> dúvidas</span><?php endif;?></div><?php endif;?></td><td class="actions"><a class="admin-button secondary admin-table-action" href="<?=h(admin_course_url($id,(int)$course['id']))?>">Abrir</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="admin-card"><header><div><h2>Site</h2><p>Publicação e desempenho do site atual.</p></div><div class="admin-inline-actions"><a class="admin-button" href="<?=h($homeUrl)?>">Editar página inicial</a><a class="admin-button secondary" href="/admin/activities.php?activity=<?=$id?>">Configurar site</a></div></header><section class="admin-stat-grid" aria-label="Resumo do site"><div class="admin-stat"><span>Publicação</span><strong><?=$publicationPending>0?h(admin_quantity_label($publicationPending,'pendência','pendências')):'Em dia'?></strong><span>Páginas e formulários</span></div><div class="admin-stat"><span>Sessões · 30 dias</span><strong><?=number_format((int)$analyticsCounts['sessions'],0,',','.')?></strong><span><?=number_format((int)$analyticsCounts['views'],0,',','.')?> visualizações</span></div><div class="admin-stat"><span>Conversão · 30 dias</span><strong><?=number_format((float)$analyticsRates['visitToSubmit'],1,',','.')?>%</strong><span>Acesso → resposta</span></div></section></section>
<?php admin_shell_end();