<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/admin_shell.php';security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];
if(!$activity){admin_shell_start('overview','Visão geral',$state);?><section class="admin-empty"><p class="admin-kicker">Nenhuma atividade configurada</p><h2>Comece pela primeira atividade</h2><a class="admin-button" href="/admin/activities.php">Configurar atividade</a></section><?php admin_shell_end();exit;}
$id=(int)$activity['id'];cms_pages_seed($db,$id);cms_forms_seed($db,$id);$pages=cms_pages($db,$id);$forms=cms_forms($db,$id);$q=$db->prepare('SELECT COUNT(*) FROM cms_form_submissions WHERE activity_id=?');$q->execute([$id]);$responses=(int)$q->fetchColumn();$q=$db->prepare('SELECT created_at FROM cms_form_submissions WHERE activity_id=? ORDER BY created_at DESC LIMIT 1');$q->execute([$id]);$latestResponse=$q->fetchColumn()?:null;$assets=$db->query("SELECT kind,COUNT(*) total,MAX(updated_at) latest FROM media_assets WHERE archived_at IS NULL GROUP BY kind")->fetchAll();$media=['image'=>0,'video'=>0];$latestMedia=null;foreach($assets as $asset){$media[$asset['kind']]=(int)$asset['total'];if($asset['latest']&&(!$latestMedia||strtotime($asset['latest'])>strtotime($latestMedia)))$latestMedia=$asset['latest'];}$unpublishedPages=count(array_filter($pages,fn(array $p)=>$p['published_revision']===null||(int)$p['draft_revision']!==(int)$p['published_revision']));$unpublishedForms=count(array_filter($forms,fn(array $f)=>$f['published_revision']===null||(int)$f['draft_revision']!==(int)$f['published_revision']));
function admin_date(?string $date): string{return $date?date('d/m/Y · H:i',strtotime($date)):'Ainda não disponível';}
admin_shell_start('overview','Visão geral',$state);?>
<section class="overview-hero"><div><p class="admin-kicker">Site administrado</p><h2><?=h($activity['admin_name'])?></h2><p class="public-url"><span>URL pública</span><a href="/<?=h($activity['slug'])?>/" target="_blank" rel="noopener">/<?=h($activity['slug'])?>/</a></p></div><div class="editorial-state"><strong><?= $unpublishedPages||$unpublishedForms?'Há alterações não publicadas':'Site publicado e atualizado' ?></strong><span><?= $unpublishedPages ?> página(s) e <?= $unpublishedForms ?> formulário(s) com rascunho pendente.</span></div><div class="hero-actions"><a class="admin-button" href="/admin/pages.php?activity=<?=$id?>">Gerenciar páginas</a><a class="admin-button secondary" href="/<?=h($activity['slug'])?>/" target="_blank" rel="noopener">Abrir site</a></div></section>
<section class="overview-grid"><article class="overview-card"><p class="admin-kicker">Páginas</p><h2><?=count($pages)?> páginas</h2><p>Português e inglês têm conteúdo independente, URL própria e publicação separada.</p><a href="/admin/pages.php?activity=<?=$id?>">Abrir páginas</a></article><article class="overview-card"><p class="admin-kicker">Formulários</p><h2><?=count($forms)?> formulários</h2><p>Campos editáveis, inscrição e pesquisa de interesse sem Google Forms.</p><a href="/admin/forms.php?activity=<?=$id?>">Editar formulários</a></article><article class="overview-card"><p class="admin-kicker">Respostas</p><h2><?=$responses?> <?= $responses===1?'resposta':'respostas' ?></h2><p><?= $latestResponse?'Mais recente: '.h(admin_date($latestResponse)):'Nenhuma resposta recebida pelo novo sistema ainda.' ?></p><a href="/admin/submissions.php?activity=<?=$id?>">Ver respostas</a></article><article class="overview-card"><p class="admin-kicker">Mídia</p><h2><?=h(admin_media_summary($media['image'],$media['video']))?></h2><p><?= $latestMedia?'Arquivo mais recente: '.h(admin_date($latestMedia)):'A biblioteca ainda não possui arquivos.' ?></p><a href="/admin/media.php?activity=<?=$id?>">Abrir biblioteca</a></article></section>
<section class="recent-activity"><div><p class="admin-kicker">Fluxo editorial</p><h2>O novo CMS separa estrutura, conteúdo e captação</h2></div><ol><li><strong>Páginas</strong><span>Crie, duplique, arquive e publique páginas por idioma.</span></li><li><strong>Editor visual</strong><span>Edite texto e imagens sobre a página real, adicione e remova seções.</span></li><li><strong>Formulários</strong><span>Adicione, remova e reordene campos sem alterar código.</span></li><li><strong>Respostas</strong><span>Acompanhe inscrições e pesquisas no próprio painel e exporte CSV.</span></li></ol></section>
<?php admin_shell_end();
