<?php
require __DIR__ . '/../app/bootstrap.php';
security_headers();
require_admin();
$db = database();
$activity = (int) ($_GET['activity'] ?? 0);
$activities = $db->query('SELECT id, admin_name, slug FROM activities ORDER BY admin_name')->fetchAll();
$where = $activity ? ' WHERE i.activity_id = ?' : '';
$q = $db->prepare('SELECT i.*, a.admin_name, a.slug FROM interest_submissions i LEFT JOIN activities a ON a.id = i.activity_id' . $where . ' ORDER BY i.id DESC');
$q->execute($activity ? [$activity] : []);
$rows = $q->fetchAll();
$recordLabel = count($rows) === 1 ? 'record' : 'records';
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/admin/admin.css"><title>Interest submissions</title></head><body class="admin-page"><main class="admin-shell"><header class="admin-header"><div><p class="admin-kicker">Workshop administration</p><h1 class="admin-title">Responses</h1></div><nav class="admin-nav" aria-label="Administration"><a href="/admin/activities.php">Activities</a><a href="/admin/interests.php" aria-current="page">Responses</a></nav></header><div class="admin-toolbar"><form method="get" class="admin-filter"><label class="admin-field">Activity<select name="activity"><option value="">All activities</option><?php foreach ($activities as $a): ?><option value="<?= $a['id'] ?>" <?= $activity === (int) $a['id'] ? 'selected' : '' ?>><?= h($a['admin_name']) ?> (<?= h($a['slug']) ?>)</option><?php endforeach; ?></select></label><button class="admin-button">Filter</button></form><div class="admin-actions"><a href="/admin/export.php<?= $activity ? '?activity=' . $activity : '' ?>">Export CSV</a><span><?= count($rows) ?> <?= $recordLabel ?></span></div></div><section class="submission-list"><?php foreach ($rows as $r): $p = json_decode($r['payload_json'], true) ?: []; $date = date('d M Y · H:i', strtotime((string) $r['created_at'])); $detailId = 'submission-' . (int) $r['id']; ?><article class="submission-card"><button class="submission-toggle" type="button" aria-expanded="false" aria-controls="<?= $detailId ?>"><span class="submission-summary"><span><strong><?= h($r['name']) ?></strong><small><?= h($r['email']) ?></small></span><span><small><?= h($date) ?></small></span></span><span class="admin-meta"><span class="meta-identity">Activity <b><?= h($r['admin_name'] ?? 'Original activity') ?></b></span><span class="meta-identity">Slug <b>/<?= h($r['slug'] ?? '') ?></b></span></span></button><div class="submission-detail" id="<?= $detailId ?>" hidden><dl><dt>Activity</dt><dd><?= h($r['admin_name'] ?? 'Original activity') ?> &middot; /<?= h($r['slug'] ?? '') ?></dd><?php foreach ($p as $k => $v): ?><dt><?= h($k) ?></dt><dd><?= nl2br(h((string) $v)) ?></dd><?php endforeach; ?></dl></div></article><?php endforeach; ?></section></main><script src="/assets/admin.js"></script></body></html>
