<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$admin=current_admin();$adminId=(int)($admin['id']??0);$tab=(string)($_GET['tab']??$_POST['tab']??'stages');if(!in_array($tab,['stages','developers'],true))$tab='stages';

if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('admin-lab-catalogs',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}
    try{
        $action=(string)($_POST['action']??'');
        if($action==='save_stage'){
            student_process_admin_update_stage($db,$adminId,(string)($_POST['stage_key']??''),$_POST);
            $_SESSION['admin_lab_catalog_notice']='Etapa salva. Novos usos passam a enxergar esta definição.';
        }elseif($action==='save_developer'){
            student_process_admin_update_developer($db,$adminId,(string)($_POST['developer_key']??''),$_POST);
            $_SESSION['admin_lab_catalog_notice']='Revelador salvo. Novos usos passam a enxergar esta definição.';
        }else throw new RuntimeException('Ação inválida.');
    }catch(Throwable $e){$_SESSION['admin_lab_catalog_notice']='Não foi possível concluir: '.$e->getMessage();}
    header('Location: /admin/lab-catalogs.php?tab='.rawurlencode($tab),true,303);exit;
}

$stages=student_process_stage_catalog_rows($db,false);$developers=student_process_developer_catalog_rows($db,false);$notice=(string)($_SESSION['admin_lab_catalog_notice']??'');unset($_SESSION['admin_lab_catalog_notice']);$tone=str_starts_with($notice,'Não foi possível')?'error':'success';
admin_shell_start('lab-catalogs','Catálogos do laboratório',$state,['/assets/admin-processes.css']);?>
<?php if($notice!==''):?><div class="admin-notice <?=h($tone)?>" role="<?=$tone==='error'?'alert':'status'?>"><?=h($notice)?></div><?php endif;?>
<section class="admin-card"><header><div><p class="admin-kicker">Dados de domínio</p><h2>Etapas e reveladores</h2><p>Estes catálogos alimentam os editores de processos. Desativar uma entrada impede novos usos sem apagar snapshots ou registros históricos que já usam a chave.</p></div></header><nav class="admin-inline-actions" aria-label="Catálogos"><a class="admin-button <?=$tab==='stages'?'':'secondary'?>" href="/admin/lab-catalogs.php?tab=stages">Etapas</a><a class="admin-button <?=$tab==='developers'?'':'secondary'?>" href="/admin/lab-catalogs.php?tab=developers">Reveladores</a></nav></section>

<?php if($tab==='stages'):?>
<section class="admin-card"><header><div><p class="admin-kicker">Etapas</p><h2><?=count($stages)?> definições</h2><p>A chave é a identidade histórica da etapa. Depois que uma chave entra em uso, prefira alterar seus metadados ou desativá-la em vez de criar outro significado para a mesma chave.</p></div></header>
<div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Etapa</th><th>Tipo</th><th>Químico padrão</th><th>Estado</th><th>Ordem</th><th></th></tr></thead><tbody><?php foreach($stages as $row):?><tr><td><div class="admin-table-primary"><strong><?=h((string)$row['label'])?></strong><span><?=h((string)$row['stage_key'])?></span></div></td><td><?=h((string)$row['stage_type'])?></td><td><?=h((string)($row['chemical_name']?:'—'))?></td><td><?=admin_badge((int)$row['enabled']===1?'Ativa':'Desativada',(int)$row['enabled']===1?'good':'muted')?></td><td class="admin-table-number"><?=(int)$row['sort_order']?></td><td><details><summary class="admin-button secondary admin-table-action">Editar</summary><form class="admin-form-grid admin-process-step-form" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('admin-lab-catalogs'))?>"><input type="hidden" name="action" value="save_stage"><input type="hidden" name="tab" value="stages"><input type="hidden" name="stage_key" value="<?=h((string)$row['stage_key'])?>"><label class="admin-form-span-2">Nome<input name="label" maxlength="120" required value="<?=h((string)$row['label'])?>"></label><label>Tipo<select name="stage_type"><?php foreach(['development'=>'Revelação','wash'=>'Lavagem','chemical'=>'Banho químico','dry'=>'Secagem','custom'=>'Livre'] as $key=>$label):?><option value="<?=h($key)?>"<?=$key===(string)$row['stage_type']?' selected':''?>><?=h($label)?></option><?php endforeach;?></select></label><label>Ordem<input type="number" min="0" name="sort_order" value="<?=(int)$row['sort_order']?>"></label><label class="admin-form-span-2">Nome químico padrão<input name="chemical_name" maxlength="180" value="<?=h((string)$row['chemical_name'])?>"></label><label class="admin-check admin-form-span-2"><input type="checkbox" name="enabled" value="1"<?=(int)$row['enabled']===1?' checked':''?>><span>Disponível para novos usos</span></label><div class="admin-form-actions admin-form-span-2"><button class="admin-button" type="submit">Salvar etapa</button></div></form></details></td></tr><?php endforeach;?></tbody></table></div>
<details class="admin-secondary-setup"><summary class="admin-button secondary">Nova etapa</summary><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('admin-lab-catalogs'))?>"><input type="hidden" name="action" value="save_stage"><input type="hidden" name="tab" value="stages"><label>Chave estável<input name="stage_key" pattern="[a-z0-9_-]+" placeholder="lavagem_intermediaria" required></label><label>Ordem<input type="number" min="0" name="sort_order" value="500"></label><label class="admin-form-span-2">Nome<input name="label" maxlength="120" required></label><label>Tipo<select name="stage_type"><option value="chemical">Banho químico</option><option value="development">Revelação</option><option value="wash">Lavagem</option><option value="dry">Secagem</option><option value="custom">Livre</option></select></label><label>Nome químico padrão<input name="chemical_name" maxlength="180"></label><label class="admin-check admin-form-span-2"><input type="checkbox" name="enabled" value="1" checked><span>Disponível para novos usos</span></label><div class="admin-form-actions admin-form-span-2"><button class="admin-button" type="submit">Criar etapa</button></div></form></details>
</section>
<?php else:?>
<section class="admin-card"><header><div><p class="admin-kicker">Reveladores</p><h2><?=count($developers)?> definições</h2><p>O modo de preparo determina como o sistema interpreta volume e diluição. Desativar não altera processos e registros que já guardaram esse revelador no snapshot.</p></div></header>
<div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Revelador</th><th>Preparo</th><th>Armazenável</th><th>Estado</th><th>Ordem</th><th></th></tr></thead><tbody><?php foreach($developers as $row):?><tr><td><div class="admin-table-primary"><strong><?=h((string)$row['label'])?></strong><span><?=h((string)$row['developer_key'])?></span></div></td><td><?=h((string)$row['preparation_mode'])?></td><td><?=((int)$row['storable']===1?'Sim':'Não')?></td><td><?=admin_badge((int)$row['enabled']===1?'Ativo':'Desativado',(int)$row['enabled']===1?'good':'muted')?></td><td class="admin-table-number"><?=(int)$row['sort_order']?></td><td><details><summary class="admin-button secondary admin-table-action">Editar</summary><form class="admin-form-grid admin-process-step-form" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('admin-lab-catalogs'))?>"><input type="hidden" name="action" value="save_developer"><input type="hidden" name="tab" value="developers"><input type="hidden" name="developer_key" value="<?=h((string)$row['developer_key'])?>"><label class="admin-form-span-2">Nome<input name="label" maxlength="160" required value="<?=h((string)$row['label'])?>"></label><label>Modo<select name="preparation_mode"><?php foreach(['concentrate'=>'Concentrado + água','stock'=>'Solução estoque','fresh'=>'Preparo fresco','custom'=>'Personalizado'] as $key=>$label):?><option value="<?=h($key)?>"<?=$key===(string)$row['preparation_mode']?' selected':''?>><?=h($label)?></option><?php endforeach;?></select></label><label>Ordem<input type="number" min="0" name="sort_order" value="<?=(int)$row['sort_order']?>"></label><label class="admin-check"><input type="checkbox" name="storable" value="1"<?=(int)$row['storable']===1?' checked':''?>><span>Armazenável</span></label><label class="admin-check"><input type="checkbox" name="enabled" value="1"<?=(int)$row['enabled']===1?' checked':''?>><span>Disponível para novos usos</span></label><div class="admin-form-actions admin-form-span-2"><button class="admin-button" type="submit">Salvar revelador</button></div></form></details></td></tr><?php endforeach;?></tbody></table></div>
<details class="admin-secondary-setup"><summary class="admin-button secondary">Novo revelador</summary><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('admin-lab-catalogs'))?>"><input type="hidden" name="action" value="save_developer"><input type="hidden" name="tab" value="developers"><label>Chave estável<input name="developer_key" pattern="[a-z0-9_-]+" placeholder="meu-revelador" required></label><label>Ordem<input type="number" min="0" name="sort_order" value="500"></label><label class="admin-form-span-2">Nome<input name="label" maxlength="160" required></label><label>Modo<select name="preparation_mode"><option value="concentrate">Concentrado + água</option><option value="stock">Solução estoque</option><option value="fresh">Preparo fresco</option><option value="custom">Personalizado</option></select></label><label class="admin-check"><input type="checkbox" name="storable" value="1" checked><span>Armazenável</span></label><label class="admin-check admin-form-span-2"><input type="checkbox" name="enabled" value="1" checked><span>Disponível para novos usos</span></label><div class="admin-form-actions admin-form-span-2"><button class="admin-button" type="submit">Criar revelador</button></div></form></details>
</section>
<?php endif;?>
<?php admin_shell_end();