<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];
$courses=course_list($db,$activityId);$courseId=max(0,(int)($_GET['course']??$_POST['course_id']??0));$course=$courseId>0?course_by_id($db,$courseId):null;if($course&&(int)$course['activity_id']!==$activityId){$course=null;$courseId=0;}$q=trim((string)($_GET['q']??''));$page=max(1,(int)($_GET['page']??1));$pageSize=25;
function lessons_admin_url(int $activityId,int $courseId=0,string $q='',int $page=1): string {$args=['activity'=>$activityId];if($courseId>0)$args['course']=$courseId;if($q!=='')$args['q']=$q;if($page>1)$args['page']=$page;return '/admin/lessons.php?'.http_build_query($args);}
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('lessons-admin',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}$action=(string)($_POST['action']??'');
    try{
        if(!$course)throw new RuntimeException('Escolha um curso.');
        if($action==='add_lesson')course_add_lesson_for_course($db,$courseId,(string)($_POST['title']??''),(string)($_POST['lesson_key']??''));
        elseif($action==='set_release')course_set_lesson_release_for_course($db,$courseId,(int)($_POST['cohort_id']??0),(int)($_POST['lesson_id']??0),(string)($_POST['mode']??'block'),(string)($_POST['scheduled_at']??''));
        else throw new RuntimeException('Ação inválida.');
        $_SESSION['admin_lessons_notice']='Alteração salva.';
    }catch(Throwable $e){$_SESSION['admin_lessons_notice']='Não foi possível concluir: '.$e->getMessage();}
    header('Location: '.lessons_admin_url($activityId,$courseId,$q,$page),true,303);exit;
}
$where=['c.activity_id=?',"c.status!='archived'"];$args=[$activityId];if($courseId>0){$where[]='l.course_id=?';$args[]=$courseId;}if($q!==''){$where[]='(l.title LIKE ? OR l.lesson_key LIKE ? OR c.title LIKE ?)';$like='%'.$q.'%';array_push($args,$like,$like,$like);}$whereSql=implode(' AND ',$where);
$count=$db->prepare("SELECT COUNT(*) FROM course_lessons l JOIN courses c ON c.id=l.course_id WHERE $whereSql");$count->execute($args);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$pageSize));if($page>$pages)$page=$pages;$offset=($page-1)*$pageSize;
$sql="SELECT l.id,l.course_id,l.lesson_key,l.title,l.sort_order,c.title course_title FROM course_lessons l JOIN courses c ON c.id=l.course_id WHERE $whereSql ORDER BY c.title COLLATE NOCASE,l.sort_order,l.id LIMIT $pageSize OFFSET $offset";$stmt=$db->prepare($sql);$stmt->execute($args);$rows=$stmt->fetchAll();
$cohorts=[];$releaseMap=[];if($course){$cohorts=course_cohorts_for_course($db,$courseId);foreach($cohorts as $cohort)course_sync_release_rows_for_course($db,(int)$cohort['id'],$courseId);$lessonIds=array_map(static fn(array $row): int=>(int)$row['id'],$rows);if($lessonIds&&$cohorts){$placeholders=implode(',',array_fill(0,count($lessonIds),'?'));$params=$lessonIds;$release=$db->prepare("SELECT cohort_id,lesson_id,released_at FROM cohort_lesson_releases WHERE lesson_id IN ($placeholders)");$release->execute($params);foreach($release->fetchAll() as $row)$releaseMap[(int)$row['cohort_id']][(int)$row['lesson_id']]=$row['released_at'];}}
$notice=(string)($_SESSION['admin_lessons_notice']??'');unset($_SESSION['admin_lessons_notice']);
admin_shell_start('lessons','Aulas',$state);?>
<?php if($notice!==''):?><div class="admin-notice"><?=h($notice)?></div><?php endif;?>
<form class="admin-filter-bar" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><label>Curso<select name="course"><option value="0">Todos os cursos</option><?php foreach($courses as $item):?><option value="<?=(int)$item['id']?>"<?=$courseId===(int)$item['id']?' selected':''?>><?=h((string)$item['title'])?></option><?php endforeach;?></select></label><label class="grow">Buscar<input name="q" value="<?=h($q)?>" placeholder="Aula, chave ou curso"></label><div class="admin-filter-actions"><button class="admin-button secondary" type="submit">Aplicar</button><?php if($courseId>0||$q!==''):?><a class="admin-button secondary" href="<?=h(lessons_admin_url($activityId))?>">Limpar</a><?php endif;?></div></form>
<div class="admin-list-summary"><span><?php if($total>0):?>Mostrando <?=($offset+1)?>–<?=min($offset+$pageSize,$total)?> de <?=$total?> aula(s)<?php else:?>Nenhuma aula neste filtro<?php endif;?></span><?php if(!$course):?><span>Selecione um curso para controlar a liberação por turma.</span><?php endif;?></div>
<?php if(!$rows):?><div class="admin-empty">Nenhuma aula encontrada.</div><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Aula</th><?php if(!$course):?><th>Curso</th><?php else:foreach($cohorts as $cohort):?><th><?=h((string)$cohort['title'])?></th><?php endforeach;endif;?><th></th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><div class="admin-table-primary"><strong><?=h((string)$row['title'])?></strong><span><?=h((string)$row['lesson_key'])?> · ordem <?=(int)$row['sort_order']?></span></div></td><?php if(!$course):?><td><a href="<?=h(lessons_admin_url($activityId,(int)$row['course_id']))?>"><?=h((string)$row['course_title'])?></a></td><?php else:foreach($cohorts as $cohort):$released=$releaseMap[(int)$cohort['id']][(int)$row['id']]??null;$stateLabel=cms_access_lesson_release_state($released);?><td><form class="admin-inline-actions" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('lessons-admin'))?>"><input type="hidden" name="action" value="set_release"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="lesson_id" value="<?=(int)$row['id']?>"><input type="hidden" name="cohort_id" value="<?=(int)$cohort['id']?>"><span class="admin-state-text"><?=h($stateLabel)?></span><button class="admin-button secondary admin-table-action" name="mode" value="<?=$stateLabel==='released'?'block':'release'?>" type="submit"><?=$stateLabel==='released'?'Bloquear':'Liberar'?></button></form></td><?php endforeach;endif;?><td class="actions"><?php if(!$course):?><a class="admin-button secondary admin-table-action" href="<?=h(lessons_admin_url($activityId,(int)$row['course_id']))?>">Gerenciar</a><?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<div class="admin-pagination"><span>Página <?=$page?> de <?=$pages?></span><?php if($pages>1):?><nav aria-label="Paginação de aulas"><?php if($page>1):?><a href="<?=h(lessons_admin_url($activityId,$courseId,$q,$page-1))?>">← Anterior</a><?php endif;?><?php if($page<$pages):?><a href="<?=h(lessons_admin_url($activityId,$courseId,$q,$page+1))?>">Próxima →</a><?php endif;?></nav><?php endif;?></div>
<?php if($course):?><details class="admin-secondary-setup"><summary>Criar aula em <?=h((string)$course['title'])?></summary><section class="admin-card"><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('lessons-admin'))?>"><input type="hidden" name="action" value="add_lesson"><input type="hidden" name="course_id" value="<?=$courseId?>"><label class="admin-form-span-2">Nome<input name="title" required></label><label>Chave<input name="lesson_key" placeholder="aula-1"></label><div class="admin-form-actions"><button class="admin-button" type="submit">Criar aula</button></div></form></section></details><?php endif;?>
<?php admin_shell_end();
