<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];
$courses=course_list($db,$activityId);$courseId=max(0,(int)($_GET['course']??$_POST['course_id']??0));$course=$courseId>0?course_by_id($db,$courseId):null;if($course&&(int)$course['activity_id']!==$activityId){$course=null;$courseId=0;}
$cohortId=max(0,(int)($_GET['cohort']??$_POST['cohort_id']??0));$selectedLessonId=max(0,(int)($_GET['lesson']??$_POST['lesson_id']??0));$q=trim((string)($_GET['q']??$_POST['return_q']??''));$page=max(1,(int)($_GET['page']??$_POST['return_page']??1));$pageSize=25;
function lessons_admin_url(int $activityId,int $courseId=0,int $cohortId=0,string $q='',int $page=1,int $lessonId=0): string {$args=['activity'=>$activityId];if($courseId>0)$args['course']=$courseId;if($cohortId>0)$args['cohort']=$cohortId;if($q!=='')$args['q']=$q;if($page>1)$args['page']=$page;if($lessonId>0)$args['lesson']=$lessonId;return '/admin/lessons.php?'.http_build_query($args);}
function lesson_release_display(?string $utc): string {if(!$utc)return '';try{$dt=new DateTimeImmutable($utc);$tz=new DateTimeZone((string)(app_config()['timezone']??'UTC'));return $dt->setTimezone($tz)->format('d/m/Y · H:i');}catch(Throwable){return (string)$utc;}}
$cohortOptions=$course?course_cohorts_for_course($db,$courseId):[];$selectedCohort=null;if($cohortId>0){foreach($cohortOptions as $item){if((int)$item['id']===$cohortId){$selectedCohort=$item;break;}}if(!$selectedCohort)$cohortId=0;}
if(!$course){$cohortId=0;$selectedLessonId=0;}
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('lessons-admin',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}$action=(string)($_POST['action']??'');
    try{
        if(!$course)throw new RuntimeException('Escolha um curso.');
        if($action==='add_lesson'){$created=course_add_lesson_for_course($db,$courseId,(string)($_POST['title']??''),(string)($_POST['lesson_key']??''));$selectedLessonId=$cohortId>0?(int)$created['id']:0;}
        elseif($action==='set_release'){if($cohortId<1)throw new RuntimeException('Escolha a turma.');course_set_lesson_release_for_course($db,$courseId,$cohortId,(int)($_POST['lesson_id']??0),(string)($_POST['mode']??'block'),(string)($_POST['scheduled_at']??''));$selectedLessonId=(int)($_POST['lesson_id']??0);}
        else throw new RuntimeException('Ação inválida.');
        $_SESSION['admin_lessons_notice']='Alteração salva.';
    }catch(Throwable $e){$_SESSION['admin_lessons_notice']='Não foi possível concluir: '.$e->getMessage();}
    header('Location: '.lessons_admin_url($activityId,$courseId,$cohortId,$q,$page,$selectedLessonId),true,303);exit;
}
$where=['c.activity_id=?',"c.status!='archived'"];$args=[$activityId];if($courseId>0){$where[]='l.course_id=?';$args[]=$courseId;}if($q!==''){$where[]='(l.title LIKE ? OR l.lesson_key LIKE ? OR c.title LIKE ?)';$like='%'.$q.'%';array_push($args,$like,$like,$like);}$whereSql=implode(' AND ',$where);
$count=$db->prepare("SELECT COUNT(*) FROM course_lessons l JOIN courses c ON c.id=l.course_id WHERE $whereSql");$count->execute($args);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$pageSize));if($page>$pages)$page=$pages;$offset=($page-1)*$pageSize;
$sql="SELECT l.id,l.course_id,l.lesson_key,l.title,l.sort_order,c.title course_title FROM course_lessons l JOIN courses c ON c.id=l.course_id WHERE $whereSql ORDER BY c.title COLLATE NOCASE,l.sort_order,l.id LIMIT $pageSize OFFSET $offset";$stmt=$db->prepare($sql);$stmt->execute($args);$rows=$stmt->fetchAll();
$releaseMap=[];if($course&&$cohortId>0){course_sync_release_rows_for_course($db,$cohortId,$courseId);$lessonIds=array_map(static fn(array $row): int=>(int)$row['id'],$rows);if($lessonIds){$placeholders=implode(',',array_fill(0,count($lessonIds),'?'));$params=array_merge([$cohortId],$lessonIds);$release=$db->prepare("SELECT lesson_id,released_at FROM cohort_lesson_releases WHERE cohort_id=? AND lesson_id IN ($placeholders)");$release->execute($params);foreach($release->fetchAll() as $row)$releaseMap[(int)$row['lesson_id']]=$row['released_at'];}}
$selectedLesson=null;$selectedReleasedAt=null;if($course&&$cohortId>0&&$selectedLessonId>0){$stmt=$db->prepare('SELECT l.id,l.course_id,l.lesson_key,l.title,l.sort_order FROM course_lessons l WHERE l.id=? AND l.course_id=? LIMIT 1');$stmt->execute([$selectedLessonId,$courseId]);$selectedLesson=$stmt->fetch()?:null;if($selectedLesson){course_sync_release_rows_for_course($db,$cohortId,$courseId);$stmt=$db->prepare('SELECT released_at FROM cohort_lesson_releases WHERE cohort_id=? AND lesson_id=?');$stmt->execute([$cohortId,$selectedLessonId]);$value=$stmt->fetchColumn();$selectedReleasedAt=is_string($value)&&trim($value)!==''?$value:null;}else $selectedLessonId=0;}
$notice=(string)($_SESSION['admin_lessons_notice']??'');unset($_SESSION['admin_lessons_notice']);$noticeTone=str_starts_with($notice,'Não foi possível')?'error':'success';
admin_shell_start('lessons','Aulas',$state,['/assets/admin-teaching.css']);?>
<?php if($notice!==''):?><div class="admin-notice <?=h($noticeTone)?>" role="<?=$noticeTone==='error'?'alert':'status'?>"><?=h($notice)?></div><?php endif;?>
<form class="admin-data-toolbar" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><label>Curso<select name="course"><option value="0">Todos os cursos</option><?php foreach($courses as $item):?><option value="<?=(int)$item['id']?>"<?=$courseId===(int)$item['id']?' selected':''?>><?=h((string)$item['title'])?></option><?php endforeach;?></select></label><?php if($course):?><label>Turma<select name="cohort"><option value="0">Escolha uma turma</option><?php foreach($cohortOptions as $item):?><option value="<?=(int)$item['id']?>"<?=$cohortId===(int)$item['id']?' selected':''?>><?=h((string)$item['title'])?></option><?php endforeach;?></select></label><?php endif;?><label class="grow">Buscar<input name="q" value="<?=h($q)?>" placeholder="Aula, chave ou curso"></label><div class="admin-inline-actions"><button class="admin-button" type="submit">Aplicar filtros</button><?php if($courseId>0||$cohortId>0||$q!==''):?><a class="admin-button secondary" href="<?=h(lessons_admin_url($activityId))?>">Limpar tudo</a><?php endif;?></div></form>
<?php if($courseId>0||$cohortId>0||$q!==''):?><div class="admin-active-filters" aria-label="Filtros ativos"><span>Filtros ativos</span><?php if($course):?><?=admin_filter_chip('Curso',(string)$course['title'],lessons_admin_url($activityId,0,0,$q,1))?><?php endif;?><?php if($selectedCohort):?><?=admin_filter_chip('Turma',(string)$selectedCohort['title'],lessons_admin_url($activityId,$courseId,0,$q,1))?><?php endif;?><?php if($q!==''):?><?=admin_filter_chip('Busca',$q,lessons_admin_url($activityId,$courseId,$cohortId,'',1))?><?php endif;?></div><?php endif;?>
<?php if($selectedLesson&&$selectedCohort):$releaseState=cms_access_lesson_release_state($selectedReleasedAt);?>
<section class="admin-card admin-teaching-detail"><header><div><a class="admin-back" href="<?=h(lessons_admin_url($activityId,$courseId,$cohortId,$q,$page))?>">← Aulas</a><p class="admin-kicker">Liberação da aula</p><h2><?=h((string)$selectedLesson['title'])?></h2><div class="admin-teaching-meta"><span><?=h((string)$course['title'])?></span><span>Turma: <?=h((string)$selectedCohort['title'])?></span><?=admin_badge(admin_status_label('release',$releaseState),admin_status_tone('release',$releaseState))?></div></div></header>
<div class="admin-teaching-section admin-release-editor"><h3>Disponibilidade para esta turma</h3><div class="admin-release-current"><?=admin_badge(admin_status_label('release',$releaseState),admin_status_tone('release',$releaseState))?><span><?=$selectedReleasedAt?h(lesson_release_display($selectedReleasedAt)):'Sem data de liberação'?></span></div><form class="admin-release-form" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('lessons-admin'))?>"><input type="hidden" name="action" value="set_release"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="cohort_id" value="<?=$cohortId?>"><input type="hidden" name="lesson_id" value="<?=$selectedLessonId?>"><input type="hidden" name="return_q" value="<?=h($q)?>"><input type="hidden" name="return_page" value="<?=$page?>"><label>Agendar para<input type="datetime-local" name="scheduled_at" value="<?=h(cms_access_local_input_value($selectedReleasedAt))?>"></label><div class="admin-release-actions"><button class="admin-button secondary" type="submit" name="mode" value="schedule">Agendar</button><button class="admin-button" type="submit" name="mode" value="release">Liberar agora</button><button class="admin-button secondary" type="submit" name="mode" value="block">Bloquear</button></div></form></div></section>
<?php else:?>
<div class="admin-list-summary"><span><?php if($total>0):?>Mostrando <?=($offset+1)?>–<?=min($offset+$pageSize,$total)?> de <?=$total?> aula(s)<?php else:?>Nenhuma aula neste filtro<?php endif;?></span><?php if(!$course):?><span>Filtre por curso para gerenciar liberação.</span><?php elseif(!$selectedCohort):?><span>Escolha uma turma para editar os estados de liberação sem criar uma coluna por turma.</span><?php else:?><span>Liberação exibida para <?=h((string)$selectedCohort['title'])?>.</span><?php endif;?></div>
<?php if(!$rows):?><div class="admin-empty">Nenhuma aula encontrada.</div><?php else:?><div class="admin-table-scroll" tabindex="0" role="region" aria-label="Lista de aulas"><table class="admin-data-table"><thead><tr><th>Aula</th><?php if(!$course):?><th>Curso</th><?php endif;?><?php if($selectedCohort):?><th>Liberação</th><th>Data</th><?php endif;?><th></th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><div class="admin-table-primary"><strong><?=h((string)$row['title'])?></strong><span><?=h((string)$row['lesson_key'])?> · ordem <?=(int)$row['sort_order']?></span></div></td><?php if(!$course):?><td><a href="<?=h(lessons_admin_url($activityId,(int)$row['course_id'],0,$q,1))?>"><?=h((string)$row['course_title'])?></a></td><?php endif;?><?php if($selectedCohort):$releasedAt=$releaseMap[(int)$row['id']]??null;$releaseState=cms_access_lesson_release_state(is_string($releasedAt)?$releasedAt:null);?><td><?=admin_badge(admin_status_label('release',$releaseState),admin_status_tone('release',$releaseState))?></td><td><?=is_string($releasedAt)&&$releasedAt!==''?h(lesson_release_display($releasedAt)):'—'?></td><?php endif;?><td class="actions"><?php if(!$course):?><a class="admin-button secondary admin-table-action" href="<?=h(lessons_admin_url($activityId,(int)$row['course_id'],0,$q,1))?>">Filtrar curso</a><?php elseif($selectedCohort):?><a class="admin-button secondary admin-table-action" href="<?=h(lessons_admin_url($activityId,$courseId,$cohortId,$q,$page,(int)$row['id']))?>">Gerenciar liberação</a><?php else:?><span class="muted">Escolha a turma acima</span><?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<div class="admin-pagination"><span>Página <?=$page?> de <?=$pages?></span><?php if($pages>1):?><nav aria-label="Paginação de aulas"><?php if($page>1):?><a href="<?=h(lessons_admin_url($activityId,$courseId,$cohortId,$q,$page-1))?>">← Anterior</a><?php endif;?><?php if($page<$pages):?><a href="<?=h(lessons_admin_url($activityId,$courseId,$cohortId,$q,$page+1))?>">Próxima →</a><?php endif;?></nav><?php endif;?></div>
<?php if($course):?><div class="admin-teaching-create"><details class="admin-secondary-setup"><summary class="admin-button secondary">Criar aula</summary><section class="admin-card"><header><div><h2>Nova aula</h2><p><?=h((string)$course['title'])?></p></div></header><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('lessons-admin'))?>"><input type="hidden" name="action" value="add_lesson"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="cohort_id" value="<?=$cohortId?>"><input type="hidden" name="return_q" value="<?=h($q)?>"><input type="hidden" name="return_page" value="<?=$page?>"><label class="admin-form-span-2">Nome<input name="title" required></label><label>Chave<input name="lesson_key" placeholder="aula-1"></label><div class="admin-form-actions"><button class="admin-button" type="submit">Criar aula</button></div></form></section></details></div><?php endif;?>
<?php endif;?>
<?php admin_shell_end();
