<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/admin_shell.php';security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];
$courses=course_list($db,$activityId);$courseId=max(0,(int)($_GET['course']??$_POST['course_id']??0));$course=$courseId>0?course_by_id($db,$courseId):null;if(!$course||(int)$course['activity_id']!==$activityId){if(count($courses)===1){header('Location: '.admin_course_url($activityId,(int)$courses[0]['id'],'lessons'),true,302);exit;}header('Location: /admin/courses.php?activity='.$activityId,true,302);exit;}
$cohortId=max(0,(int)($_GET['cohort']??$_POST['cohort_id']??0));$cohort=$cohortId>0?admin_course_cohort($db,$courseId,$cohortId,false):null;if($cohortId>0&&!$cohort){$_SESSION['admin_cohorts_notice']='A turma solicitada não existe ou não está ativa neste curso.';header('Location: '.admin_course_url($activityId,$courseId,'cohorts'),true,302);exit;}
function lesson_release_display(?string $utc): string {if(!$utc)return '';try{$dt=new DateTimeImmutable($utc);$tz=new DateTimeZone((string)(app_config()['timezone']??'UTC'));return $dt->setTimezone($tz)->format('d/m/Y · H:i');}catch(Throwable){return (string)$utc;}}
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
 if(!verify_csrf('lessons-admin',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}$action=(string)($_POST['action']??'');
 try{
  if($action==='add_lesson')course_add_lesson_for_course($db,$courseId,(string)($_POST['title']??''),(string)($_POST['lesson_key']??''));
  elseif($action==='update_lesson')admin_course_update_lesson($db,$courseId,(int)($_POST['lesson_id']??0),(string)($_POST['title']??''));
  elseif($action==='move_lesson')admin_course_move_lesson($db,$courseId,(int)($_POST['lesson_id']??0),(int)($_POST['direction']??0));
  elseif($action==='set_release'){if(!$cohort)throw new RuntimeException('Escolha a turma.');course_set_lesson_release_for_course($db,$courseId,$cohortId,(int)($_POST['lesson_id']??0),(string)($_POST['mode']??'block'),(string)($_POST['scheduled_at']??''));}
  elseif($action==='set_tool_release'){student_tool_course_set_release_lesson($db,$courseId,(string)($_POST['tool_key']??''),(int)($_POST['release_lesson_id']??0)?:null);}
  else throw new RuntimeException('Ação inválida.');$_SESSION['admin_lessons_notice']='Alteração salva.';
 }catch(Throwable $e){$_SESSION['admin_lessons_notice']='Não foi possível concluir: '.$e->getMessage();}
 $target=$cohort?admin_cohort_url($activityId,$courseId,$cohortId,'lessons'):admin_course_url($activityId,$courseId,'lessons');header('Location: '.$target,true,303);exit;
}
$lessons=course_lessons_for_course($db,$courseId);$impact=admin_course_lesson_material_impact($db,$courseId);$materials=course_material_pages($db,$courseId);$notice=(string)($_SESSION['admin_lessons_notice']??'');unset($_SESSION['admin_lessons_notice']);$tone=str_starts_with($notice,'Não foi possível')?'error':'success';
admin_shell_start('lessons',$cohort?'Aulas e acesso':'Aulas',$state,['/assets/admin-teaching.css','/assets/admin-operations.css']);?>
<?php if($notice!==''):?><div class="admin-notice <?=h($tone)?>" role="<?=$tone==='error'?'alert':'status'?>"><?=h($notice)?></div><?php endif;?>
<?php if($cohort):admin_cohort_context($course,$cohort,$activityId,'lessons','Disponibilidade do conteúdo nesta turma.');$releaseRows=course_lesson_release_rows_for_course($db,$cohortId,$courseId);?>
<section class="admin-card admin-teaching-detail"><header><div><h2>Aulas e acesso</h2><p>Liberar uma aula torna disponíveis os materiais e recursos do aluno associados a ela.</p></div><?php if($materials):?><a class="admin-button secondary" href="/admin/course-preview.php?<?=h(http_build_query(['activity'=>$activityId,'course'=>$courseId,'cohort'=>$cohortId,'page'=>(int)$materials[0]['id']]))?>" target="_blank" rel="noopener">Visualizar como esta turma ↗</a><?php endif;?></header></section>
<?php if(!$releaseRows):?><div class="admin-empty">Este curso ainda não possui aulas.</div><?php else:?><div class="admin-release-list"><?php foreach($releaseRows as $row):$releasedAt=is_string($row['released_at']??null)?$row['released_at']:null;$releaseState=cms_access_lesson_release_state($releasedAt);$impactRow=$impact[(int)$row['id']]??['sections'=>0,'pages'=>0];$items=admin_course_lesson_material_items($db,$courseId,(int)$row['id']);$toolItems=student_tools_released_by_lesson($db,$courseId,(int)$row['id']);?>
<section class="admin-card admin-release-card"><header><div><p class="admin-kicker">Aula</p><h2><?=h((string)$row['title'])?></h2><div class="admin-teaching-meta"><?=admin_badge(admin_status_label('release',$releaseState),admin_status_tone('release',$releaseState))?><span><?=$releasedAt?h(lesson_release_display($releasedAt)):'Sem data de liberação'?></span></div></div></header><div class="admin-release-impact"><strong><?=(int)$impactRow['sections']?> seção(ões) em <?=(int)$impactRow['pages']?> página(s)</strong><?php if($items):?><details><summary>Ver conteúdo afetado</summary><ul><?php foreach($items as $item):?><li><strong><?=h((string)$item['page_title'])?></strong> · <?=h((string)$item['section_label'])?></li><?php endforeach;?></ul></details><?php elseif(!$toolItems):?><span class="muted">Nenhuma seção depende desta aula.</span><?php endif;?><?php if($toolItems):?><div class="admin-teaching-meta"><strong>Também libera:</strong><?php foreach($toolItems as $tool):?><span><?=h((string)$tool['label'])?></span><?php endforeach;?></div><?php endif;?></div><form class="admin-release-form" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('lessons-admin'))?>"><input type="hidden" name="action" value="set_release"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="cohort_id" value="<?=$cohortId?>"><input type="hidden" name="lesson_id" value="<?=(int)$row['id']?>"><label>Agendar para<input type="datetime-local" name="scheduled_at" value="<?=h(cms_access_local_input_value($releasedAt))?>"></label><div class="admin-release-actions"><button class="admin-button secondary" type="submit" name="mode" value="schedule">Agendar</button><button class="admin-button" type="submit" name="mode" value="release" data-confirm="Liberar esta aula agora? O material associado ficará disponível para esta turma.">Liberar agora</button><button class="admin-button secondary" type="submit" name="mode" value="block" data-confirm="Bloquear esta aula para a turma?">Bloquear</button></div></form></section>
<?php endforeach;?></div><?php endif;?>
<?php else:admin_course_context($course,$activityId,'content','Estrutura didática compartilhada pelas turmas.');?>
<nav class="admin-content-tabs" aria-label="Conteúdo do curso"><a href="<?=h(admin_course_url($activityId,$courseId,'lessons'))?>" aria-current="page">Aulas</a><a href="<?=h(admin_course_url($activityId,$courseId,'material'))?>">Material</a></nav>
<section class="admin-card admin-teaching-detail"><header><div><h2>Aulas</h2><p>Defina a ordem e os nomes das aulas. A disponibilidade é controlada dentro de cada turma.</p></div></header></section>
<?php if(!$lessons):?><div class="admin-empty">Nenhuma aula cadastrada.</div><?php else:?><ol class="admin-lesson-structure"><?php foreach($lessons as $i=>$lesson):$impactRow=$impact[(int)$lesson['id']]??['sections'=>0,'pages'=>0];?><li class="admin-card"><div class="admin-lesson-row"><span class="admin-lesson-index"><?=str_pad((string)($i+1),2,'0',STR_PAD_LEFT)?></span><div class="admin-table-primary"><strong><?=h((string)$lesson['title'])?></strong><span><?=(int)$impactRow['sections']?> seção(ões) de material</span></div><div class="admin-inline-actions"><form method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('lessons-admin'))?>"><input type="hidden" name="action" value="move_lesson"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="lesson_id" value="<?=(int)$lesson['id']?>"><button class="admin-button secondary admin-table-action" name="direction" value="-1"<?=$i===0?' disabled':''?> aria-label="Mover para cima">↑</button><button class="admin-button secondary admin-table-action" name="direction" value="1"<?=$i===count($lessons)-1?' disabled':''?> aria-label="Mover para baixo">↓</button></form><details class="admin-inline-editor"><summary class="admin-button secondary admin-table-action">Editar</summary><form class="admin-inline-actions" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('lessons-admin'))?>"><input type="hidden" name="action" value="update_lesson"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="lesson_id" value="<?=(int)$lesson['id']?>"><input name="title" value="<?=h((string)$lesson['title'])?>" required><button class="admin-button" type="submit">Salvar</button></form></details></div></div></li><?php endforeach;?></ol><?php endif;?>
<?php $courseTools=student_tool_course_access_rows($db,$courseId);if($courseTools):?><section class="admin-card admin-block-gap"><header><div><h2>Recursos liberados com as aulas</h2><p>Defina em qual aula cada recurso passa a ficar disponível para o aluno. O bloqueio vale também para acesso direto pela URL.</p></div></header><div class="admin-release-list"><?php foreach($courseTools as $tool):?><form class="admin-release-form" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('lessons-admin'))?>"><input type="hidden" name="action" value="set_tool_release"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="tool_key" value="<?=h((string)$tool['tool_key'])?>"><label><?=h((string)$tool['label'])?><select name="release_lesson_id"><option value="0"<?=(int)($tool['release_lesson_id']??0)===0?' selected':''?>>Desde a matrícula</option><?php foreach($lessons as $lesson):?><option value="<?=(int)$lesson['id']?>"<?=(int)($tool['release_lesson_id']??0)===(int)$lesson['id']?' selected':''?>>Ao liberar: <?=h((string)$lesson['title'])?></option><?php endforeach;?></select></label><button class="admin-button secondary" type="submit">Salvar acesso</button></form><?php endforeach;?></div></section><?php endif;?>
<details class="admin-secondary-setup admin-block-gap"><summary class="admin-button secondary">Adicionar aula</summary><section class="admin-card"><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('lessons-admin'))?>"><input type="hidden" name="action" value="add_lesson"><input type="hidden" name="course_id" value="<?=$courseId?>"><label class="admin-form-span-2">Nome da aula<input name="title" required></label><div class="admin-form-actions"><button class="admin-button" type="submit">Adicionar aula</button></div></form></section></details>
<?php endif;?>
<?php admin_shell_end();