<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/admin_shell.php';security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];
$courses=course_list($db,$activityId);$courseId=max(0,(int)($_GET['course']??$_POST['course_id']??0));$course=$courseId>0?course_by_id($db,$courseId):null;if(!$course||(int)$course['activity_id']!==$activityId){if(count($courses)===1){header('Location: '.admin_course_url($activityId,(int)$courses[0]['id'],'material'),true,302);exit;}header('Location: /admin/courses.php?activity='.$activityId,true,302);exit;}
$selectedPageId=max(0,(int)($_GET['material_page']??$_POST['page_id']??0));$availableQ=trim((string)($_GET['available_q']??''));
function material_admin_url(int $activityId,int $courseId,int $selectedPageId=0,string $availableQ=''): string {$args=['activity'=>$activityId,'course'=>$courseId];if($selectedPageId>0)$args['material_page']=$selectedPageId;if($availableQ!=='')$args['available_q']=$availableQ;return '/admin/material.php?'.http_build_query($args);}
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
 if(!verify_csrf('material-admin',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}$action=(string)($_POST['action']??'');
 try{if($action==='add_material')course_material_add_page($db,$courseId,(int)($_POST['page_id']??0));elseif($action==='remove_material')course_material_remove_page($db,$courseId,(int)($_POST['page_id']??0));elseif($action==='map_section')course_material_set_section_lesson($db,$courseId,(int)($_POST['page_id']??0),(string)($_POST['section_key']??''),(int)($_POST['lesson_id']??0)?:null);else throw new RuntimeException('Ação inválida.');$_SESSION['admin_material_notice']='Alteração salva.';}catch(Throwable $e){$_SESSION['admin_material_notice']='Não foi possível concluir: '.$e->getMessage();}
 $target=$action==='remove_material'?0:(int)($_POST['page_id']??0);header('Location: '.material_admin_url($activityId,$courseId,$target),true,303);exit;
}
$rows=course_material_pages($db,$courseId);$selectedPage=null;$sections=[];$sectionMap=[];$lessons=course_lessons_for_course($db,$courseId);if($selectedPageId>0&&course_material_page_is_associated($db,$courseId,$selectedPageId)){$selectedPage=cms_page_by_id($db,$selectedPageId);if($selectedPage&&(int)$selectedPage['activity_id']===$activityId){$sections=course_material_sections_from_page($db,$selectedPageId);$sectionMap=course_material_section_map($db,$courseId,$selectedPageId);}else{$selectedPage=null;$selectedPageId=0;}}
$availableWhere=["p.activity_id=?","p.status!='archived'",'NOT EXISTS (SELECT 1 FROM course_material_pages m WHERE m.course_id=? AND m.page_id=p.id)'];$availableArgs=[$activityId,$courseId];if($availableQ!==''){$availableWhere[]='(p.title LIKE ? OR p.slug LIKE ?)';$like='%'.$availableQ.'%';array_push($availableArgs,$like,$like);}$availableStmt=$db->prepare('SELECT p.id,p.title,p.slug,p.locale,p.status FROM cms_pages p WHERE '.implode(' AND ',$availableWhere).' ORDER BY p.title COLLATE NOCASE,p.id LIMIT 50');$availableStmt->execute($availableArgs);$availablePages=$availableStmt->fetchAll();
$notice=(string)($_SESSION['admin_material_notice']??'');unset($_SESSION['admin_material_notice']);$tone=str_starts_with($notice,'Não foi possível')?'error':'success';
admin_shell_start('material','Conteúdo · Material',$state,['/assets/admin-teaching.css','/assets/admin-operations.css']);?>
<?php if($notice!==''):?><div class="admin-notice <?=h($tone)?>" role="<?=$tone==='error'?'alert':'status'?>"><?=h($notice)?></div><?php endif;?>
<?php admin_course_context($course,$activityId,'content','Estrutura didática compartilhada pelas turmas.');?>
<nav class="admin-content-tabs" aria-label="Conteúdo do curso"><a href="<?=h(admin_course_url($activityId,$courseId,'lessons'))?>">Aulas</a><a href="<?=h(admin_course_url($activityId,$courseId,'material'))?>" aria-current="page">Material</a></nav>
<?php if($selectedPage):?>
<section class="admin-card admin-teaching-detail"><header><div><a class="admin-back" href="<?=h(material_admin_url($activityId,$courseId))?>">← Material</a><p class="admin-kicker">Página de material</p><h2><?=h((string)$selectedPage['title'])?></h2><div class="admin-teaching-meta"><span><?=h(public_language_label((string)$selectedPage['locale']))?></span><?=admin_badge(admin_status_label('page',(string)$selectedPage['status']),admin_status_tone('page',(string)$selectedPage['status']))?></div></div><a class="admin-button secondary" href="/editor/?page=<?=$selectedPageId?>">Editar página</a></header></section>
<section class="admin-card"><header><div><h2>Organizar por aula</h2><p>Escolha a aula a partir da qual cada seção ficará disponível. Se ficar como “Sempre disponível”, a seção não depende da liberação de uma aula.</p></div></header><?php if(!$sections):?><div class="admin-empty compact">Esta página não possui seções organizáveis no conteúdo atual.</div><?php else:?><div class="admin-table-scroll" tabindex="0" role="region" aria-label="Organização das seções por aula"><table class="admin-data-table"><thead><tr><th>Seção</th><th>Disponível a partir de</th></tr></thead><tbody><?php foreach($sections as $key=>$label):$lessonId=(int)($sectionMap[$key]['lesson_id']??0);?><tr><td><strong><?=h($label)?></strong></td><td><form class="admin-inline-actions" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('material-admin'))?>"><input type="hidden" name="action" value="map_section"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="page_id" value="<?=$selectedPageId?>"><input type="hidden" name="section_key" value="<?=h($key)?>"><select name="lesson_id"><option value="0">Sempre disponível</option><?php foreach($lessons as $lesson):?><option value="<?=(int)$lesson['id']?>"<?=$lessonId===(int)$lesson['id']?' selected':''?>><?=h((string)$lesson['title'])?></option><?php endforeach;?></select><button class="admin-button secondary admin-table-action" type="submit">Salvar</button></form></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="admin-card admin-teaching-danger"><h3>Retirar do material do curso</h3><p>A página continuará existindo no site, mas deixará de aparecer como material deste curso. A organização por aula desta página será removida.</p><form method="post" data-confirm="Retirar esta página do material do curso?"><input type="hidden" name="_csrf" value="<?=h(csrf_token('material-admin'))?>"><input type="hidden" name="action" value="remove_material"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="page_id" value="<?=$selectedPageId?>"><button class="admin-button danger" type="submit">Retirar do material</button></form></section>
<?php else:?>
<section class="admin-card admin-teaching-detail"><header><div><h2>Material</h2><p>Páginas que os alunos acessam neste curso. Organize suas seções pelas aulas do curso.</p></div></header></section>
<?php if(!$rows):?><div class="admin-empty">Nenhuma página de material associada a este curso.</div><?php else:?><div class="admin-table-scroll" tabindex="0" role="region" aria-label="Material do curso"><table class="admin-data-table"><thead><tr><th>Página</th><th>Status</th><th>Idioma</th><th></th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><div class="admin-table-primary"><strong><?=h((string)$row['title'])?></strong></div></td><td><?=admin_badge(admin_status_label('page',(string)$row['status']),admin_status_tone('page',(string)$row['status']))?></td><td><?=h(public_language_label((string)$row['locale']))?></td><td class="actions"><a class="admin-button secondary admin-table-action" href="/editor/?page=<?=(int)$row['id']?>">Editar página</a><a class="admin-button secondary admin-table-action" href="<?=h(material_admin_url($activityId,$courseId,(int)$row['id']))?>">Organizar por aula</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<details class="admin-secondary-setup admin-block-gap"<?=$availableQ!==''?' open':''?>><summary class="admin-button secondary">Adicionar página ao material</summary><section class="admin-card"><form class="admin-data-toolbar" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><input type="hidden" name="course" value="<?=$courseId?>"><label class="grow">Buscar página<input name="available_q" value="<?=h($availableQ)?>" placeholder="Título ou endereço"></label><button class="admin-button secondary" type="submit">Pesquisar</button></form><?php if(!$availablePages):?><div class="admin-empty compact">Nenhuma página disponível para esta busca.</div><?php else:?><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('material-admin'))?>"><input type="hidden" name="action" value="add_material"><input type="hidden" name="course_id" value="<?=$courseId?>"><label class="admin-form-span-2">Página<select name="page_id" required><option value="">Escolha uma página</option><?php foreach($availablePages as $item):?><option value="<?=(int)$item['id']?>"><?=h((string)$item['title'].' · '.public_language_label((string)$item['locale']))?></option><?php endforeach;?></select></label><div class="admin-form-actions"><button class="admin-button" type="submit">Adicionar ao material</button></div></form><?php endif;?></section></details>
<?php endif;?>
<?php admin_shell_end();