<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];
$courses=course_list($db,$activityId);$courseId=max(0,(int)($_GET['course']??$_POST['course_id']??0));$course=$courseId>0?course_by_id($db,$courseId):null;if($course&&(int)$course['activity_id']!==$activityId){$course=null;$courseId=0;}
$q=trim((string)($_GET['q']??$_POST['return_q']??''));$page=max(1,(int)($_GET['page']??$_POST['return_page']??1));$pageSize=25;$selectedPageId=max(0,(int)($_GET['material_page']??$_POST['page_id']??0));$availableQ=trim((string)($_GET['available_q']??''));
function material_admin_url(int $activityId,int $courseId=0,string $q='',int $page=1,int $selectedPageId=0): string {$args=['activity'=>$activityId];if($courseId>0)$args['course']=$courseId;if($q!=='')$args['q']=$q;if($page>1)$args['page']=$page;if($selectedPageId>0)$args['material_page']=$selectedPageId;return '/admin/material.php?'.http_build_query($args);}
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('material-admin',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}$action=(string)($_POST['action']??'');
    try{
        if(!$course)throw new RuntimeException('Escolha um curso.');
        if($action==='add_material')course_material_add_page($db,$courseId,(int)($_POST['page_id']??0));
        elseif($action==='remove_material')course_material_remove_page($db,$courseId,(int)($_POST['page_id']??0));
        elseif($action==='map_section')course_material_set_section_lesson($db,$courseId,(int)($_POST['page_id']??0),(string)($_POST['section_key']??''),(int)($_POST['lesson_id']??0)?:null);
        else throw new RuntimeException('Ação inválida.');
        $_SESSION['admin_material_notice']='Alteração salva.';
    }catch(Throwable $e){$_SESSION['admin_material_notice']='Não foi possível concluir: '.$e->getMessage();}
    $target=$action==='remove_material'?0:(int)($_POST['page_id']??0);header('Location: '.material_admin_url($activityId,$courseId,$q,$page,$target),true,303);exit;
}
$where=['c.activity_id=?',"c.status!='archived'","p.status!='archived'"];$args=[$activityId];if($courseId>0){$where[]='m.course_id=?';$args[]=$courseId;}if($q!==''){$where[]='(p.title LIKE ? OR p.slug LIKE ? OR c.title LIKE ?)';$like='%'.$q.'%';array_push($args,$like,$like,$like);}$whereSql=implode(' AND ',$where);
$count=$db->prepare("SELECT COUNT(*) FROM course_material_pages m JOIN courses c ON c.id=m.course_id JOIN cms_pages p ON p.id=m.page_id WHERE $whereSql");$count->execute($args);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$pageSize));if($page>$pages)$page=$pages;$offset=($page-1)*$pageSize;
$sql="SELECT m.course_id,m.page_id,m.sort_order,c.title course_title,p.title page_title,p.slug page_slug,p.locale,p.status page_status FROM course_material_pages m JOIN courses c ON c.id=m.course_id JOIN cms_pages p ON p.id=m.page_id WHERE $whereSql ORDER BY c.title COLLATE NOCASE,m.sort_order,p.title COLLATE NOCASE LIMIT $pageSize OFFSET $offset";$stmt=$db->prepare($sql);$stmt->execute($args);$rows=$stmt->fetchAll();
$selectedPage=null;$sections=[];$sectionMap=[];$lessons=[];if($course&&$selectedPageId>0&&course_material_page_is_associated($db,$courseId,$selectedPageId)){$selectedPage=cms_page_by_id($db,$selectedPageId);if($selectedPage&&(int)$selectedPage['activity_id']===$activityId){$sections=course_material_sections_from_page($db,$selectedPageId);$sectionMap=course_material_section_map($db,$courseId,$selectedPageId);$lessons=course_lessons_for_course($db,$courseId);}else{$selectedPage=null;$selectedPageId=0;}}
$availablePages=[];$availableCount=0;if($course&&!$selectedPage){$availableWhere=["p.activity_id=?","p.status!='archived'",'NOT EXISTS (SELECT 1 FROM course_material_pages m WHERE m.course_id=? AND m.page_id=p.id)'];$availableArgs=[$activityId,$courseId];if($availableQ!==''){$availableWhere[]='(p.title LIKE ? OR p.slug LIKE ?)';$like='%'.$availableQ.'%';array_push($availableArgs,$like,$like);}$availableWhereSql=implode(' AND ',$availableWhere);$availableCountStmt=$db->prepare("SELECT COUNT(*) FROM cms_pages p WHERE $availableWhereSql");$availableCountStmt->execute($availableArgs);$availableCount=(int)$availableCountStmt->fetchColumn();$availableStmt=$db->prepare("SELECT p.id,p.title,p.slug,p.locale,p.status FROM cms_pages p WHERE $availableWhereSql ORDER BY p.title COLLATE NOCASE,p.id LIMIT 50");$availableStmt->execute($availableArgs);$availablePages=$availableStmt->fetchAll();}
$notice=(string)($_SESSION['admin_material_notice']??'');unset($_SESSION['admin_material_notice']);$noticeTone=str_starts_with($notice,'Não foi possível')?'error':'success';
admin_shell_start('material','Material',$state,['/assets/admin-teaching.css']);?>
<?php if($notice!==''):?><div class="admin-notice <?=h($noticeTone)?>" role="<?=$noticeTone==='error'?'alert':'status'?>"><?=h($notice)?></div><?php endif;?>
<form class="admin-data-toolbar" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><label>Curso<select name="course"><option value="0">Todos os cursos</option><?php foreach($courses as $item):?><option value="<?=(int)$item['id']?>"<?=$courseId===(int)$item['id']?' selected':''?>><?=h((string)$item['title'])?></option><?php endforeach;?></select></label><label class="grow">Buscar<input name="q" value="<?=h($q)?>" placeholder="Página, slug ou curso"></label><div class="admin-inline-actions"><button class="admin-button" type="submit">Aplicar filtros</button><?php if($courseId>0||$q!==''):?><a class="admin-button secondary" href="<?=h(material_admin_url($activityId))?>">Limpar tudo</a><?php endif;?></div></form>
<?php if($courseId>0||$q!==''):?><div class="admin-active-filters" aria-label="Filtros ativos"><span>Filtros ativos</span><?php if($course):?><?=admin_filter_chip('Curso',(string)$course['title'],material_admin_url($activityId,0,$q,1))?><?php endif;?><?php if($q!==''):?><?=admin_filter_chip('Busca',$q,material_admin_url($activityId,$courseId,'',1))?><?php endif;?></div><?php endif;?>
<?php if($selectedPage&&$course):?>
<section class="admin-card admin-teaching-detail"><header><div><a class="admin-back" href="<?=h(material_admin_url($activityId,$courseId,$q,$page))?>">← Material</a><p class="admin-kicker">Página de material</p><h2><?=h((string)$selectedPage['title'])?></h2><div class="admin-teaching-meta"><span><?=h((string)$course['title'])?></span><span><?=h(public_language_label((string)$selectedPage['locale']))?></span><?=admin_badge(admin_status_label('page',(string)$selectedPage['status']),admin_status_tone('page',(string)$selectedPage['status']))?></div></div><div class="admin-card-actions"><a class="admin-button secondary" href="/editor/?page=<?=$selectedPageId?>">Editar página</a></div></header>
<section class="admin-teaching-section"><h3>Liberação por aula</h3><p>Cada seção pode ficar sempre disponível ou depender da liberação de uma aula deste mesmo curso.</p><?php if(!$sections):?><div class="admin-empty compact">A página não possui seções CMS identificáveis no rascunho atual.</div><?php else:?><div class="admin-table-scroll" tabindex="0" role="region" aria-label="Liberação das seções do material"><table class="admin-data-table"><thead><tr><th>Seção</th><th>Disponível a partir de</th></tr></thead><tbody><?php foreach($sections as $key=>$label):$lessonId=(int)($sectionMap[$key]['lesson_id']??0);?><tr><td><div class="admin-table-primary"><strong><?=h($label)?></strong><span><?=h($key)?></span></div></td><td><form class="admin-inline-actions" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('material-admin'))?>"><input type="hidden" name="action" value="map_section"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="page_id" value="<?=$selectedPageId?>"><input type="hidden" name="section_key" value="<?=h($key)?>"><input type="hidden" name="return_q" value="<?=h($q)?>"><input type="hidden" name="return_page" value="<?=$page?>"><select name="lesson_id"><option value="0">Sempre disponível</option><?php foreach($lessons as $lesson):?><option value="<?=(int)$lesson['id']?>"<?=$lessonId===(int)$lesson['id']?' selected':''?>><?=h((string)$lesson['title'])?></option><?php endforeach;?></select><button class="admin-button secondary admin-table-action" type="submit">Salvar</button></form></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="admin-teaching-danger"><h3>Vínculo com o curso</h3><p>Desassociar remove esta página do material de <?=h((string)$course['title'])?> e apaga os mapeamentos de seção. A página CMS continua existindo.</p><form method="post" data-confirm="Remover esta página do material do curso? A página CMS não será excluída."><input type="hidden" name="_csrf" value="<?=h(csrf_token('material-admin'))?>"><input type="hidden" name="action" value="remove_material"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="page_id" value="<?=$selectedPageId?>"><input type="hidden" name="return_q" value="<?=h($q)?>"><input type="hidden" name="return_page" value="<?=$page?>"><button class="admin-button danger" type="submit">Desassociar do curso</button></form></section></section>
<?php else:?>
<div class="admin-list-summary"><span><?php if($total>0):?>Mostrando <?=($offset+1)?>–<?=min($offset+$pageSize,$total)?> de <?=$total?> associação(ões)<?php else:?>Nenhum material neste filtro<?php endif;?></span><span>O conteúdo continua sendo a página CMS; aqui se administra o vínculo educacional.</span></div>
<?php if(!$rows):?><div class="admin-empty">Nenhuma página de material encontrada.</div><?php else:?><div class="admin-table-scroll" tabindex="0" role="region" aria-label="Lista de material"><table class="admin-data-table"><thead><tr><th>Página</th><th>Curso</th><th>Status</th><th>Idioma</th><th>Ordem</th><th></th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><div class="admin-table-primary"><strong><?=h((string)$row['page_title'])?></strong><span><?=h((string)$row['page_slug'])?></span></div></td><td><a href="<?=h(material_admin_url($activityId,(int)$row['course_id'],$q,1))?>"><?=h((string)$row['course_title'])?></a></td><td><?=admin_badge(admin_status_label('page',(string)$row['page_status']),admin_status_tone('page',(string)$row['page_status']))?></td><td><?=h(public_language_label((string)$row['locale']))?></td><td class="admin-table-number"><?=(int)$row['sort_order']?></td><td class="actions"><a class="admin-button secondary admin-table-action" href="/editor/?page=<?=(int)$row['page_id']?>">Editar</a><a class="admin-button secondary admin-table-action" href="<?=h(material_admin_url($activityId,(int)$row['course_id'],$q,$page,(int)$row['page_id']))?>">Gerenciar liberação</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<div class="admin-pagination"><span>Página <?=$page?> de <?=$pages?></span><?php if($pages>1):?><nav aria-label="Paginação de material"><?php if($page>1):?><a href="<?=h(material_admin_url($activityId,$courseId,$q,$page-1))?>">← Anterior</a><?php endif;?><?php if($page<$pages):?><a href="<?=h(material_admin_url($activityId,$courseId,$q,$page+1))?>">Próxima →</a><?php endif;?></nav><?php endif;?></div>
<?php if($course):?><div class="admin-teaching-create"><details class="admin-secondary-setup"<?=$availableQ!==''?' open':''?>><summary class="admin-button secondary">Associar página</summary><section class="admin-card"><header><div><h2>Associar página ao material</h2><p>Busque entre as páginas deste site que ainda não pertencem ao material do curso.</p></div></header><form class="admin-data-toolbar" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><input type="hidden" name="course" value="<?=$courseId?>"><input type="hidden" name="q" value="<?=h($q)?>"><input type="hidden" name="page" value="<?=$page?>"><label class="grow">Buscar página disponível<input name="available_q" value="<?=h($availableQ)?>" placeholder="Título ou slug"></label><div class="admin-inline-actions"><button class="admin-button secondary" type="submit">Pesquisar</button><?php if($availableQ!==''):?><a class="admin-button secondary" href="<?=h(material_admin_url($activityId,$courseId,$q,$page))?>">Limpar busca</a><?php endif;?></div></form><?php if($availableCount>50):?><p class="admin-operation-note">Mostrando 50 de <?=$availableCount?> páginas disponíveis. Refine a busca para localizar a página desejada.</p><?php endif;?><?php if(!$availablePages):?><div class="admin-empty compact">Nenhuma página disponível para esta busca.</div><?php else:?><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('material-admin'))?>"><input type="hidden" name="action" value="add_material"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="return_q" value="<?=h($q)?>"><input type="hidden" name="return_page" value="<?=$page?>"><label class="admin-form-span-2">Página<select name="page_id" required><option value="">Escolha uma página</option><?php foreach($availablePages as $item):?><option value="<?=(int)$item['id']?>"><?=h((string)$item['title'].' · '.public_language_label((string)$item['locale']).' · '.admin_status_label('page',(string)$item['status']))?></option><?php endforeach;?></select></label><div class="admin-form-actions"><button class="admin-button" type="submit">Associar ao material</button></div></form><?php endif;?></section></details></div><?php endif;?>
<?php endif;?>
<?php admin_shell_end();
