<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];
$courses=course_list($db,$activityId);$courseId=max(0,(int)($_GET['course']??$_POST['course_id']??0));$course=$courseId>0?course_by_id($db,$courseId):null;if($course&&(int)$course['activity_id']!==$activityId){$course=null;$courseId=0;}$q=trim((string)($_GET['q']??''));$page=max(1,(int)($_GET['page']??1));$pageSize=25;$selectedPageId=max(0,(int)($_GET['material_page']??0));
function material_admin_url(int $activityId,int $courseId=0,string $q='',int $page=1,int $selectedPageId=0): string {$args=['activity'=>$activityId];if($courseId>0)$args['course']=$courseId;if($q!=='')$args['q']=$q;if($page>1)$args['page']=$page;if($selectedPageId>0)$args['material_page']=$selectedPageId;return '/admin/material.php?'.http_build_query($args);}
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('material-admin',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}$action=(string)($_POST['action']??'');
    try{
        if(!$course)throw new RuntimeException('Escolha um curso.');
        if($action==='add_material')course_material_add_page($db,$courseId,(int)($_POST['page_id']??0));
        elseif($action==='remove_material')course_material_remove_page($db,$courseId,(int)($_POST['page_id']??0));
        elseif($action==='map_section')course_material_set_section_lesson($db,$courseId,(int)($_POST['page_id']??0),(string)($_POST['section_key']??''),(int)($_POST['lesson_id']??0)?:null);
        else throw new RuntimeException('Ação inválida.');
        $_SESSION['admin_material_notice']='Alteração salva.';
    }catch(Throwable $e){$_SESSION['admin_material_notice']='Não foi possível concluir: '.$e->getMessage();}
    $target=$action==='remove_material'?0:(int)($_POST['page_id']??0);header('Location: '.material_admin_url($activityId,$courseId,$q,$page,$target),true,303);exit;
}
$where=['c.activity_id=?',"c.status!='archived'","p.status!='archived'"];$args=[$activityId];if($courseId>0){$where[]='m.course_id=?';$args[]=$courseId;}if($q!==''){$where[]='(p.title LIKE ? OR p.slug LIKE ? OR c.title LIKE ?)';$like='%'.$q.'%';array_push($args,$like,$like,$like);}$whereSql=implode(' AND ',$where);
$count=$db->prepare("SELECT COUNT(*) FROM course_material_pages m JOIN courses c ON c.id=m.course_id JOIN cms_pages p ON p.id=m.page_id WHERE $whereSql");$count->execute($args);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$pageSize));if($page>$pages)$page=$pages;$offset=($page-1)*$pageSize;
$sql="SELECT m.course_id,m.page_id,m.sort_order,c.title course_title,p.title page_title,p.slug page_slug,p.locale FROM course_material_pages m JOIN courses c ON c.id=m.course_id JOIN cms_pages p ON p.id=m.page_id WHERE $whereSql ORDER BY c.title COLLATE NOCASE,m.sort_order,p.title COLLATE NOCASE LIMIT $pageSize OFFSET $offset";$stmt=$db->prepare($sql);$stmt->execute($args);$rows=$stmt->fetchAll();
$selectedPage=null;$sections=[];$sectionMap=[];$lessons=[];if($course&&$selectedPageId>0&&course_material_page_is_associated($db,$courseId,$selectedPageId)){$selectedPage=cms_page_by_id($db,$selectedPageId);if($selectedPage&&(int)$selectedPage['activity_id']===$activityId){$sections=course_material_sections_from_page($db,$selectedPageId);$sectionMap=course_material_section_map($db,$courseId,$selectedPageId);$lessons=course_lessons_for_course($db,$courseId);}else{$selectedPage=null;}}
$availablePages=[];if($course){$allPages=array_values(array_filter(cms_pages($db,$activityId,null,true),static fn(array $row): bool=>(string)$row['status']!=='archived'));$materialIds=array_fill_keys(array_map(static fn(array $row): int=>(int)$row['id'],course_material_pages($db,$courseId)),true);$availablePages=array_values(array_filter($allPages,static fn(array $row): bool=>!isset($materialIds[(int)$row['id']])));}
$notice=(string)($_SESSION['admin_material_notice']??'');unset($_SESSION['admin_material_notice']);
admin_shell_start('material','Material',$state);?>
<?php if($notice!==''):?><div class="admin-notice"><?=h($notice)?></div><?php endif;?>
<form class="admin-filter-bar" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><label>Curso<select name="course"><option value="0">Todos os cursos</option><?php foreach($courses as $item):?><option value="<?=(int)$item['id']?>"<?=$courseId===(int)$item['id']?' selected':''?>><?=h((string)$item['title'])?></option><?php endforeach;?></select></label><label class="grow">Buscar<input name="q" value="<?=h($q)?>" placeholder="Página, slug ou curso"></label><div class="admin-filter-actions"><button class="admin-button secondary" type="submit">Aplicar</button><?php if($courseId>0||$q!==''):?><a class="admin-button secondary" href="<?=h(material_admin_url($activityId))?>">Limpar</a><?php endif;?></div></form>
<div class="admin-list-summary"><span><?php if($total>0):?>Mostrando <?=($offset+1)?>–<?=min($offset+$pageSize,$total)?> de <?=$total?> associação(ões)<?php else:?>Nenhum material neste filtro<?php endif;?></span><span>O conteúdo continua sendo a página CMS; aqui se administra apenas o vínculo educacional.</span></div>
<?php if(!$rows):?><div class="admin-empty">Nenhuma página de material encontrada.</div><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Página</th><th>Curso</th><th>Idioma</th><th>Ordem</th><th></th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><div class="admin-table-primary"><strong><?=h((string)$row['page_title'])?></strong><span><?=h((string)$row['page_slug'])?></span></div></td><td><a href="<?=h(material_admin_url($activityId,(int)$row['course_id']))?>"><?=h((string)$row['course_title'])?></a></td><td><?=h(public_language_label((string)$row['locale']))?></td><td class="admin-table-number"><?=(int)$row['sort_order']?></td><td class="actions"><a class="admin-button secondary admin-table-action" href="/editor/?page=<?=(int)$row['page_id']?>">Editar</a><a class="admin-button secondary admin-table-action" href="<?=h(material_admin_url($activityId,(int)$row['course_id'],$q,$page,(int)$row['page_id']))?>">Liberação</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<div class="admin-pagination"><span>Página <?=$page?> de <?=$pages?></span><?php if($pages>1):?><nav aria-label="Paginação de material"><?php if($page>1):?><a href="<?=h(material_admin_url($activityId,$courseId,$q,$page-1))?>">← Anterior</a><?php endif;?><?php if($page<$pages):?><a href="<?=h(material_admin_url($activityId,$courseId,$q,$page+1))?>">Próxima →</a><?php endif;?></nav><?php endif;?></div>
<?php if($selectedPage):?><section class="admin-record-panel"><header><div><span class="admin-scope-label">Liberação por aula</span><h2><?=h((string)$selectedPage['title'])?></h2><p><?=h((string)$course['title'])?></p></div><div class="admin-card-actions"><a class="admin-button secondary" href="/editor/?page=<?=$selectedPageId?>">Editar página</a><form method="post" data-confirm="Remover esta página do material do curso? A página CMS não será excluída."><input type="hidden" name="_csrf" value="<?=h(csrf_token('material-admin'))?>"><input type="hidden" name="action" value="remove_material"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="page_id" value="<?=$selectedPageId?>"><button class="admin-button secondary" type="submit">Desassociar</button></form></div></header><?php if(!$sections):?><div class="admin-empty compact">A página não possui seções CMS identificáveis no rascunho atual.</div><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Seção</th><th>Disponível a partir de</th></tr></thead><tbody><?php foreach($sections as $key=>$label):$lessonId=(int)($sectionMap[$key]['lesson_id']??0);?><tr><td><div class="admin-table-primary"><strong><?=h($label)?></strong><span><?=h($key)?></span></div></td><td><form class="admin-inline-actions" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('material-admin'))?>"><input type="hidden" name="action" value="map_section"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="page_id" value="<?=$selectedPageId?>"><input type="hidden" name="section_key" value="<?=h($key)?>"><select name="lesson_id"><option value="0">Sempre disponível</option><?php foreach($lessons as $lesson):?><option value="<?=(int)$lesson['id']?>"<?=$lessonId===(int)$lesson['id']?' selected':''?>><?=h((string)$lesson['title'])?></option><?php endforeach;?></select><button class="admin-button secondary admin-table-action" type="submit">Salvar</button></form></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section><?php endif;?>
<?php if($course):?><details class="admin-secondary-setup"><summary>Associar página a <?=h((string)$course['title'])?></summary><section class="admin-card"><?php if(!$availablePages):?><div class="admin-empty compact">Não há outra página disponível para associar.</div><?php else:?><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('material-admin'))?>"><input type="hidden" name="action" value="add_material"><input type="hidden" name="course_id" value="<?=$courseId?>"><label class="admin-form-span-2">Página<select name="page_id" required><option value="">Escolha uma página</option><?php foreach($availablePages as $item):?><option value="<?=(int)$item['id']?>"><?=h((string)$item['title'].' · '.public_language_label((string)$item['locale']))?></option><?php endforeach;?></select></label><div class="admin-form-actions"><button class="admin-button" type="submit">Associar</button></div></form><?php endif;?></section></details><?php endif;?>
<?php admin_shell_end();
