<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/admin_shell.php';security_headers();require_admin();$state=admin_activity_resolution(database());admin_shell_start('media','Biblioteca de mídia',$state);
?><section class="overview-hero"><div><p class="admin-kicker">DAM</p><h2>Biblioteca de mídia</h2><p>Imagens e vídeos com metadata, versões, ponto focal, tags, rastreamento de uso e ações em lote.</p></div><label class="admin-button upload-button">Enviar arquivos<input id="library-upload" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" multiple hidden></label></section>
<section class="admin-filters media-filters"><label>Buscar<input id="media-search" type="search" placeholder="Título, arquivo, tag…"></label><label>Tipo<select id="media-kind"><option value="all">Todos</option><option value="image">Imagens</option><option value="video">Vídeos</option></select></label><label>Status<select id="media-status-filter"><option value="active">Ativos</option><option value="archived">Arquivados</option><option value="all">Todos</option></select></label><label>Ordenar<select id="media-sort"><option value="newest">Mais recentes</option><option value="oldest">Mais antigos</option><option value="title">Título</option></select></label></section>
<section class="media-bulk-bar" id="media-bulk-bar" hidden><strong id="media-selected-count">0 selecionados</strong><input id="media-bulk-tags" placeholder="Adicionar tags: retrato, workshop…"><button type="button" class="link-button" id="media-bulk-tag">Adicionar tags</button><button type="button" class="link-button danger" id="media-bulk-archive">Arquivar</button><button type="button" class="link-button" id="media-bulk-restore" hidden>Restaurar</button><button type="button" class="link-button" id="media-clear-selection">Limpar seleção</button></section>
<p class="library-status" id="library-status" aria-live="polite">Carregando biblioteca…</p><section class="library-grid media-library-pro" id="library-grid" aria-label="Arquivos de mídia"></section>
<dialog id="media-detail" class="admin-dialog media-detail-dialog"><form method="dialog"><header class="media-detail-header"><div><p class="admin-kicker" id="media-detail-kind">Mídia</p><h2 id="media-detail-title">Arquivo</h2></div><button value="cancel" aria-label="Fechar">×</button></header><div id="media-detail-body"></div></form></dialog>
<script src="/editor/media-library.js"></script><script src="/assets/admin-media.js"></script><?php admin_shell_end();
