<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/admin_shell.php';security_headers();require_admin();
$db=database();$pageId=(int)($_GET['page']??$_POST['page_id']??0);$page=cms_page_by_id($db,$pageId);if(!$page||$page['status']==='archived'){http_response_code(404);exit('Page not found');}$activity=activity_by_id($db,(int)$page['activity_id']);if(!$activity){http_response_code(404);exit('Activity not found');}$state=admin_activity_resolution($db);$state['activity']=$activity;
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('cms-history',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}$revisionId=(int)($_POST['revision_id']??0);$q=$db->prepare('SELECT * FROM cms_page_revisions WHERE id=? AND page_id=?');$q->execute([$revisionId,$pageId]);$revision=$q->fetch();if(!$revision){$_SESSION['admin_notice']='Revisão não encontrada.';header('Location: /admin/page-history.php?page='.$pageId);exit;}$settings=json_decode((string)$revision['settings_json'],true);if(!is_array($settings))$settings=[];$newRevision=(int)$page['draft_revision']+1;$now=gmdate('c');$q=$db->prepare('UPDATE cms_pages SET title=?,nav_title=?,slug=?,show_in_nav=?,draft_document_json=?,draft_revision=?,draft_updated_at=?,updated_at=? WHERE id=?');$q->execute([(string)($settings['title']??$page['title']),(string)($settings['nav_title']??$page['nav_title']),(string)($settings['slug']??$page['slug']),!empty($settings['show_in_nav'])?1:0,(string)$revision['document_json'],$newRevision,$now,$now,$pageId]);$page=cms_page_by_id($db,$pageId);if($page)cms_revision_store($db,$page,'draft');$_SESSION['admin_notice']='Revisão restaurada como novo rascunho. Revise e publique quando estiver pronto.';header('Location: /editor/?page='.$pageId);exit;
}
$q=$db->prepare('SELECT * FROM cms_page_revisions WHERE page_id=? ORDER BY id DESC LIMIT 100');$q->execute([$pageId]);$revisions=$q->fetchAll();$notice=$_SESSION['admin_notice']??null;unset($_SESSION['admin_notice']);admin_shell_start('pages','Histórico da página',$state);?>
<?php if($notice):?><div class="admin-notice"><?=h((string)$notice)?></div><?php endif;?>
<section class="overview-hero"><div><p class="admin-kicker">Versões</p><h2><?=h($page['title'])?></h2><p>Cada salvamento e publicação cria uma revisão persistente. Restaurar nunca apaga o estado atual: cria um novo rascunho.</p></div><div class="hero-actions"><a class="admin-button" href="/editor/?page=<?=$pageId?>">Voltar ao editor</a></div></section>
<section class="submission-list"><?php if(!$revisions):?><div class="admin-empty" style="padding:18px">Ainda não há revisões registradas para esta página.</div><?php endif;?><?php foreach($revisions as $revision):?><article class="submission-row"><div><strong>Revisão <?=h((string)$revision['revision'])?></strong><span><?=h($revision['state']==='published'?'Publicada':'Rascunho')?> · <?=h((string)$revision['created_at'])?></span></div><form method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('cms-history'))?>"><input type="hidden" name="page_id" value="<?=$pageId?>"><input type="hidden" name="revision_id" value="<?=(int)$revision['id']?>"><button class="link-button" type="submit" data-confirm="Restaurar esta revisão como novo rascunho?">Restaurar</button></form></article><?php endforeach;?></section>
<?php admin_shell_end();
