<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity']??null;$activityId=(int)($activity['id']??0);$courses=$activityId>0?course_list($db,$activityId):[];
$q=trim((string)($_GET['q']??''));$courseId=max(0,(int)($_GET['course']??0));$page=max(1,(int)($_GET['page']??1));$pageSize=50;$personId=max(0,(int)($_GET['person']??0));$course=null;
if($courseId>0){$course=course_by_id($db,$courseId);if(!$course||($activityId>0&&(int)$course['activity_id']!==$activityId)){$courseId=0;$course=null;}}
function people_admin_url(int $activityId=0,int $personId=0,int $courseId=0,string $q='',int $page=1): string {$args=[];if($activityId>0)$args['activity']=$activityId;if($personId>0)$args['person']=$personId;if($courseId>0)$args['course']=$courseId;if($q!=='')$args['q']=$q;if($page>1)$args['page']=$page;return '/admin/people.php'.($args?'?'.http_build_query($args):'');}
$where=[];$params=[];if($courseId>0){$where[]="EXISTS (SELECT 1 FROM course_enrollments fe JOIN course_cohorts fc ON fc.id=fe.cohort_id WHERE fe.student_id=u.id AND fc.course_id=? AND fe.status='active')";$params[]=$courseId;}if($q!==''){$where[]='(u.name LIKE ? OR u.email LIKE ? OR p.cpf_last4 LIKE ?)';$like='%'.$q.'%';array_push($params,$like,$like,$like);}$whereSql=$where?' WHERE '.implode(' AND ',$where):'';
$count=$db->prepare("SELECT COUNT(*) FROM student_users u LEFT JOIN student_profiles p ON p.student_id=u.id".$whereSql);$count->execute($params);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$pageSize));if($page>$pages)$page=$pages;$offset=($page-1)*$pageSize;
$sql="SELECT u.id,u.name,u.email,u.status,u.activated_at,u.last_login_at,p.cpf_last4,(SELECT COUNT(*) FROM course_enrollments e WHERE e.student_id=u.id AND e.status='active') enrollment_count,(SELECT COUNT(*) FROM course_enrollments e JOIN course_cohorts c ON c.id=e.cohort_id WHERE e.student_id=u.id AND e.status='active' AND c.course_id IS NULL) orphan_enrollment_count,(SELECT COUNT(*) FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE s.student_id=u.id AND f.purpose='enrollment') registration_count FROM student_users u LEFT JOIN student_profiles p ON p.student_id=u.id".$whereSql." ORDER BY u.name COLLATE NOCASE,u.id LIMIT $pageSize OFFSET $offset";$stmt=$db->prepare($sql);$stmt->execute($params);$people=$stmt->fetchAll();
$selected=null;$enrollments=[];$registrations=[];if($personId>0){$stmt=$db->prepare("SELECT u.id,u.name,u.email,u.status,u.activated_at,u.last_login_at,p.cpf_last4,p.phone,p.instagram,p.city_state FROM student_users u LEFT JOIN student_profiles p ON p.student_id=u.id WHERE u.id=? LIMIT 1");$stmt->execute([$personId]);$selected=$stmt->fetch()?:null;if($selected){$stmt=$db->prepare("SELECT e.id,e.status,e.confirmed_at,e.source_submission_id,c.id cohort_id,c.title cohort_title,c.status cohort_status,c.course_id,c.workshop_page_id,cr.title course_title FROM course_enrollments e JOIN course_cohorts c ON c.id=e.cohort_id LEFT JOIN courses cr ON cr.id=c.course_id WHERE e.student_id=? ORDER BY e.confirmed_at DESC,e.id DESC");$stmt->execute([$personId]);$enrollments=$stmt->fetchAll();$stmt=$db->prepare("SELECT s.id,s.status,s.payment_status,s.created_at,s.course_id,s.cohort_id,c.title course_title,cc.title cohort_title,f.title form_title FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id LEFT JOIN courses c ON c.id=s.course_id LEFT JOIN course_cohorts cc ON cc.id=s.cohort_id WHERE s.student_id=? AND f.purpose='enrollment' ORDER BY s.created_at DESC,s.id DESC");$stmt->execute([$personId]);$registrations=$stmt->fetchAll();}}
admin_shell_start('people','Pessoas',$state,['/assets/admin-operations.css']);?>
<form class="admin-data-toolbar" method="get"><?php if($activityId>0):?><input type="hidden" name="activity" value="<?=$activityId?>"><?php endif;?><label>Curso<select name="course"><option value="0">Todos os cursos</option><?php foreach($courses as $item):?><option value="<?=(int)$item['id']?>"<?=$courseId===(int)$item['id']?' selected':''?>><?=h((string)$item['title'])?></option><?php endforeach;?></select></label><label class="grow">Buscar pessoa<input name="q" value="<?=h($q)?>" placeholder="Nome, e-mail ou final do CPF"></label><div class="admin-inline-actions"><button class="admin-button" type="submit">Aplicar filtros</button><?php if($courseId>0||$q!==''):?><a class="admin-button secondary" href="<?=h(people_admin_url($activityId))?>">Limpar tudo</a><?php endif;?></div></form>
<?php if($courseId>0||$q!==''):?><div class="admin-active-filters" aria-label="Filtros ativos"><span>Filtros ativos</span><?php if($course):?><?=admin_filter_chip('Curso',(string)$course['title'],people_admin_url($activityId,0,0,$q,1))?><?php endif;?><?php if($q!==''):?><?=admin_filter_chip('Busca',$q,people_admin_url($activityId,0,$courseId,'',1))?><?php endif;?></div><?php endif;?>
<?php if($selected):$accountStatus=(string)$selected['status'];?>
<section class="admin-card admin-section-stack admin-operation-detail" id="person-detail"><header><div><p class="admin-kicker">Pessoa #<?=(int)$selected['id']?></p><h2><?=h((string)$selected['name'])?></h2><div class="admin-detail-meta"><span><?=h((string)$selected['email'])?></span><?=admin_badge(admin_status_label('account',$accountStatus),admin_status_tone('account',$accountStatus))?><?php if(!$selected['activated_at']):?><?=admin_badge('Ativação pendente','attention')?><?php endif;?></div></div><div class="admin-card-actions"><a class="admin-button secondary" href="<?=h(people_admin_url($activityId,0,$courseId,$q,$page))?>">Voltar à lista</a><?php if($activityId>0):?><a class="admin-button secondary" href="/admin/data-integrity.php?activity=<?=$activityId?>">Ver integridade</a><?php endif;?></div></header>
<section class="admin-operation-section"><h3>Identidade e contato</h3><div class="admin-table-scroll" tabindex="0" aria-label="Dados da pessoa"><table class="admin-data-table"><thead><tr><th>CPF</th><th>Telefone</th><th>Instagram</th><th>Cidade</th><th>Ativação</th><th>Último acesso</th></tr></thead><tbody><tr><td><?=$selected['cpf_last4']?'***.'.h((string)$selected['cpf_last4']):'—'?></td><td><?=h((string)($selected['phone']?:'—'))?></td><td><?=h((string)($selected['instagram']?:'—'))?></td><td><?=h((string)($selected['city_state']?:'—'))?></td><td><?=h((string)($selected['activated_at']?date('d/m/Y',strtotime((string)$selected['activated_at'])):'Pendente'))?></td><td><?=h((string)($selected['last_login_at']?date('d/m/Y H:i',strtotime((string)$selected['last_login_at'])):'—'))?></td></tr></tbody></table></div></section>
<section class="admin-operation-section"><h3>Matrículas</h3><?php if(!$enrollments):?><p>Nenhuma matrícula vinculada.</p><?php else:?><div class="admin-table-scroll" tabindex="0" aria-label="Matrículas da pessoa"><table class="admin-data-table"><thead><tr><th>Curso</th><th>Turma</th><th>Origem</th><th>Status</th></tr></thead><tbody><?php foreach($enrollments as $row):$enrollmentStatus=(string)$row['status'];?><tr><td><?php if((int)($row['course_id']??0)>0):?><a href="/admin/students.php?<?=h(http_build_query(['activity'=>$activityId,'course'=>(int)$row['course_id']]))?>"><?=h((string)$row['course_title'])?></a><?php else:?><span class="muted">Sem curso associado</span><?php endif;?></td><td><?=h((string)$row['cohort_title'])?></td><td><?php if($row['source_submission_id']??null):?><a href="/admin/registrations.php?<?=h(http_build_query(['activity'=>$activityId,'course'=>(int)$row['course_id'],'submission'=>(int)$row['source_submission_id']]))?>">Inscrição #<?=(int)$row['source_submission_id']?></a><?php else:?>Importação/manual<?php endif;?></td><td><?=admin_badge(admin_status_label('enrollment',$enrollmentStatus),admin_status_tone('enrollment',$enrollmentStatus))?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="admin-operation-section"><h3>Inscrições</h3><?php if(!$registrations):?><p>Nenhuma inscrição vinculada.</p><?php else:?><div class="admin-table-scroll" tabindex="0" aria-label="Inscrições da pessoa"><table class="admin-data-table"><thead><tr><th>Curso</th><th>Formulário</th><th>Pagamento</th><th>Turma</th><th></th></tr></thead><tbody><?php foreach($registrations as $row):$payment=(string)($row['payment_status']?:$row['status']);?><tr><td><?=h((string)($row['course_title']?:'Sem curso associado'))?></td><td><?=h((string)$row['form_title'])?></td><td><?=admin_badge(admin_status_label('payment',$payment),admin_status_tone('payment',$payment))?></td><td><?=h((string)($row['cohort_title']?:'Não definida'))?></td><td class="actions"><?php if($activityId>0):?><a class="admin-button secondary admin-table-action" href="/admin/registrations.php?<?=h(http_build_query(['activity'=>$activityId,'course'=>(int)$row['course_id'],'submission'=>(int)$row['id']]))?>">Abrir</a><?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section></section><?php endif;?>
<div class="admin-list-summary"><span><?php if($total>0):?>Mostrando <?=($offset+1)?>–<?=min($offset+$pageSize,$total)?> de <?=$total?> pessoa(s)<?php else:?>Nenhuma pessoa neste filtro<?php endif;?></span><span class="admin-operation-note">Pessoa é a identidade global; inscrições e matrículas formam o histórico relacionado.</span></div>
<?php if(!$people):?><div class="admin-empty">Nenhuma pessoa encontrada com os filtros atuais.</div><?php else:?><div class="admin-table-scroll" tabindex="0" aria-label="Lista de pessoas"><table class="admin-data-table"><thead><tr><th>Pessoa</th><th>Conta</th><th>Matrículas</th><th>Inscrições</th><th>Último acesso</th><th></th></tr></thead><tbody><?php foreach($people as $row):$rowStatus=(string)$row['status'];?><tr><td><div class="admin-table-primary"><strong><?=h((string)$row['name'])?></strong><span><?=h((string)$row['email'])?><?=$row['cpf_last4']?' · ***.'.h((string)$row['cpf_last4']):''?></span></div></td><td><?=admin_badge(admin_status_label('account',$rowStatus),admin_status_tone('account',$rowStatus))?><?php if(!$row['activated_at']):?><div class="muted">Ativação pendente</div><?php endif;?></td><td class="admin-table-number"><?=(int)$row['enrollment_count']?><?php if((int)$row['orphan_enrollment_count']>0):?><div class="muted"><?=(int)$row['orphan_enrollment_count']?> sem curso</div><?php endif;?></td><td class="admin-table-number"><?=(int)$row['registration_count']?></td><td><?=h((string)($row['last_login_at']?date('d/m/Y H:i',strtotime((string)$row['last_login_at'])):'—'))?></td><td class="actions"><a class="admin-button secondary admin-table-action" href="<?=h(people_admin_url($activityId,(int)$row['id'],$courseId,$q,$page))?>#person-detail">Abrir</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<div class="admin-pagination"><span>Página <?=$page?> de <?=$pages?></span><?php if($pages>1):?><nav aria-label="Paginação de pessoas"><?php if($page>1):?><a href="<?=h(people_admin_url($activityId,0,$courseId,$q,$page-1))?>">← Anterior</a><?php endif;?><?php if($page<$pages):?><a href="<?=h(people_admin_url($activityId,0,$courseId,$q,$page+1))?>">Próxima →</a><?php endif;?></nav><?php endif;?></div>
<?php admin_shell_end();
