<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];
$courseId=max(0,(int)($_GET['course']??$_POST['course_id']??0));$course=$courseId>0?course_by_id($db,$courseId):null;if(!$course||(int)$course['activity_id']!==$activityId){header('Location: /admin/courses.php?activity='.$activityId,true,302);exit;}
$questionId=max(0,(int)($_GET['id']??$_POST['question_id']??0));$status=(string)($_GET['status']??'');if(!in_array($status,['','open','resolved'],true))$status='';$cohortId=max(0,(int)($_GET['cohort']??0));$error='';$notice=(string)($_SESSION['admin_questions_notice']??'');unset($_SESSION['admin_questions_notice']);
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('admin-questions',$_POST['_csrf']??null)){$error='Solicitação inválida.';}
    else try{
        $action=(string)($_POST['action']??'');$targetId=(int)($_POST['question_id']??0);$target=student_question_for_admin($db,$targetId,$courseId)??throw new RuntimeException('Dúvida não encontrada neste curso.');
        if($action==='reply'){$messageId=student_question_admin_reply($db,$targetId,(string)($_POST['body']??''));if(!empty($_POST['resolve_after']))student_question_admin_resolve($db,$targetId,$messageId);$_SESSION['admin_questions_notice']=!empty($_POST['resolve_after'])?'Resposta publicada e dúvida marcada como resolvida.':'Resposta publicada.';}
        elseif($action==='resolve'){student_question_admin_resolve($db,$targetId,(int)($_POST['accepted_message_id']??0)?:null);$_SESSION['admin_questions_notice']='Dúvida marcada como resolvida.';}
        else throw new RuntimeException('Ação inválida.');
        header('Location: /admin/questions.php?'.http_build_query(['activity'=>$activityId,'course'=>$courseId,'id'=>$targetId]),true,303);exit;
    }catch(Throwable $e){$error=$e->getMessage();}
}
$cohorts=course_cohorts_for_course($db,$courseId,true);$questions=student_questions_for_admin($db,$courseId,$cohortId,$status);$question=$questionId>0?student_question_for_admin($db,$questionId,$courseId):null;$messages=$question?student_question_messages($db,$questionId):[];
admin_shell_start('courses','Dúvidas · '.(string)$course['title'],$state,['/assets/admin-teaching.css']);
admin_course_context($course,$activityId,'overview','Dúvidas e soluções das turmas deste curso.');?>
<?php if($notice!==''):?><div class="admin-notice success" role="status"><?=h($notice)?></div><?php endif;?><?php if($error!==''):?><div class="admin-notice error" role="alert"><?=h($error)?></div><?php endif;?>
<?php if($question):?>
<section class="admin-card admin-teaching-detail"><header><div><a class="admin-back" href="/admin/questions.php?<?=h(http_build_query(['activity'=>$activityId,'course'=>$courseId]))?>">← Todas as dúvidas</a><p class="admin-kicker"><?=h((string)$question['cohort_title'])?> · <?=h((string)$question['topic'])?></p><h2><?=h((string)$question['title'])?></h2><div class="admin-teaching-meta"><?=admin_badge((string)$question['status']==='resolved'?'Resolvida':'Aberta',(string)$question['status']==='resolved'?'good':'attention')?><?=admin_badge((string)$question['visibility']==='private'?'Privada':'Turma','muted')?><span><?=h((string)$question['student_name'])?> · <?=h((string)$question['student_email'])?></span></div></div></header><div class="admin-card-body"><p><?=nl2br(h((string)$question['body']))?></p><?php if((int)($question['test_id']??0)>0):?><p><strong>Registro relacionado:</strong> #<?=(int)$question['test_id']?></p><?php endif;?></div></section>
<section class="admin-card"><header><div><h2>Conversa</h2><p>As respostas do professor aparecem identificadas na área do aluno.</p></div></header><?php if(!$messages):?><div class="admin-empty">Ainda não há respostas.</div><?php else:?><div class="admin-thread"><?php foreach($messages as $message):$accepted=(int)($question['accepted_message_id']??0)===(int)$message['id'];?><article class="admin-note"><header><strong><?=$message['author_role']==='admin'?'Professor':h((string)($message['student_name']??'Aluno'))?></strong><?php if($accepted):?> <?=admin_badge('Solução confirmada','good')?><?php endif;?></header><p><?=nl2br(h((string)$message['body']))?></p><small><?=h(student_test_message_date((string)$message['created_at']))?></small><?php if((string)$question['status']!=='resolved'&&$message['author_role']==='admin'):?><form method="post" class="admin-inline-form"><input type="hidden" name="_csrf" value="<?=h(csrf_token('admin-questions'))?>"><input type="hidden" name="action" value="resolve"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="question_id" value="<?=(int)$question['id']?>"><input type="hidden" name="accepted_message_id" value="<?=(int)$message['id']?>"><button class="admin-button secondary" type="submit">Marcar como solução</button></form><?php endif;?></article><?php endforeach;?></div><?php endif;?></section>
<?php if((string)$question['status']!=='resolved'):?><section class="admin-card"><header><div><h2>Responder</h2></div></header><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('admin-questions'))?>"><input type="hidden" name="action" value="reply"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="question_id" value="<?=(int)$question['id']?>"><label class="admin-form-span-2">Resposta<textarea name="body" rows="7" required></textarea></label><label class="admin-checkbox admin-form-span-2"><input type="checkbox" name="resolve_after" value="1"><span>Esta resposta resolve a dúvida</span></label><div class="admin-form-actions"><button class="admin-button" type="submit">Publicar resposta</button></div></form></section><?php endif;?>
<?php else:?>
<form class="admin-data-toolbar" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><input type="hidden" name="course" value="<?=$courseId?>"><label>Turma<select name="cohort"><option value="0">Todas</option><?php foreach($cohorts as $cohort):?><option value="<?=(int)$cohort['id']?>"<?=$cohortId===(int)$cohort['id']?' selected':''?>><?=h((string)$cohort['title'])?></option><?php endforeach;?></select></label><label>Status<select name="status"><option value="">Todos</option><option value="open"<?=$status==='open'?' selected':''?>>Abertas</option><option value="resolved"<?=$status==='resolved'?' selected':''?>>Resolvidas</option></select></label><div class="admin-inline-actions"><button class="admin-button" type="submit">Filtrar</button><a class="admin-button secondary" href="<?=h(admin_course_url($activityId,$courseId))?>">Voltar ao curso</a></div></form>
<div class="admin-list-summary"><span><?=count($questions)?> dúvida(s)</span><span>Questões privadas ficam entre aluno e professor; questões de turma podem receber participação dos colegas.</span></div>
<?php if(!$questions):?><div class="admin-empty">Nenhuma dúvida encontrada para este filtro.</div><?php else:?><div class="admin-table-scroll" tabindex="0" role="region" aria-label="Dúvidas do curso"><table class="admin-data-table"><thead><tr><th>Dúvida</th><th>Aluno / turma</th><th>Status</th><th>Respostas</th><th></th></tr></thead><tbody><?php foreach($questions as $row):?><tr><td><div class="admin-table-primary"><strong><?=h((string)$row['title'])?></strong><span><?=h((string)$row['topic'])?></span></div></td><td><div class="admin-table-primary"><strong><?=h((string)$row['student_name'])?></strong><span><?=h((string)$row['cohort_title'])?></span></div></td><td><?=admin_badge((string)$row['status']==='resolved'?'Resolvida':'Aberta',(string)$row['status']==='resolved'?'good':'attention')?> <?=admin_badge((string)$row['visibility']==='private'?'Privada':'Turma','muted')?></td><td class="admin-table-number"><?=(int)$row['message_count']?></td><td class="actions"><a class="admin-button secondary admin-table-action" href="/admin/questions.php?<?=h(http_build_query(['activity'=>$activityId,'course'=>$courseId,'id'=>(int)$row['id']]))?>">Abrir</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<?php endif;?>
<?php admin_shell_end();