<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];
function registration_payload(array $row): array {return json_decode((string)($row['payload_json']??''),true)?:[];}
function registration_snapshot(array $row): array {return json_decode((string)($row['form_snapshot_json']??''),true)?:[];}
function registration_fields(array $row): array {$map=[];foreach(registration_snapshot($row)['fields']??[] as $field)if(is_array($field)&&isset($field['id']))$map[(string)$field['id']]=$field;return $map;}
function registration_value_label(array $field,mixed $value): string {if(is_array($value))return implode(', ',array_map(fn($item)=>registration_value_label($field,(string)$item),$value));$raw=(string)$value;foreach($field['options']??[] as $option)if(is_array($option)&&(string)($option['value']??'')===$raw)return (string)($option['label']??$raw);return $raw;}
function registration_name(array $row): string {$p=registration_payload($row);return trim((string)($p['name']??$p['full_name']??''))?:trim((string)($p['email']??''))?:'Inscrição #'.(int)$row['id'];}
function registration_status_label(array $row): string {if(($row['status']??'')==='archived')return 'Cancelada';if((int)($row['cohort_id']??0)>0&&student_account_submission_confirmed($row))return 'Com turma';if(student_account_submission_confirmed($row))return 'Confirmada · sem turma';return 'Aguardando pagamento';}
function registration_admin_url(int $activityId,int $courseId=0,int $cohortId=0,int $submissionId=0,string $filter='',string $search='',int $page=1): string {$args=['activity'=>$activityId];if($courseId>0)$args['course']=$courseId;if($cohortId>0)$args['cohort']=$cohortId;if($submissionId>0)$args['submission']=$submissionId;if($filter!=='')$args['status']=$filter;if($search!=='')$args['q']=$search;if($page>1)$args['page']=$page;return '/admin/registrations.php?'.http_build_query($args);}
function registration_availability_summary(array $rows): array {$counts=[];foreach($rows as $row){$payload=registration_payload($row);$fields=registration_fields($row);foreach(['availability','preferred_days','preferred_time'] as $key){$value=$payload[$key]??null;if($value===null||$value===''||$value===[])continue;$values=is_array($value)?$value:[$value];foreach($values as $item){$label=trim(registration_value_label($fields[$key]??[],(string)$item));if($label==='')continue;$counts[$label]=($counts[$label]??0)+1;}}}arsort($counts,SORT_NUMERIC);return $counts;}
$courses=course_list($db,$activityId);$courseId=max(0,(int)($_GET['course']??0));$cohortId=max(0,(int)($_GET['cohort']??0));$filter=(string)($_GET['status']??'');$allowedFilters=['','pending','unassigned','assigned','cancelled'];if(!in_array($filter,$allowedFilters,true))$filter='';$search=trim((string)($_GET['q']??''));$page=max(1,(int)($_GET['page']??1));$pageSize=50;$selectedId=max(0,(int)($_GET['submission']??0));
$course=$courseId>0?course_by_id($db,$courseId):null;if($course&&(int)$course['activity_id']!==$activityId){$course=null;$courseId=0;}
$cohortArgs=[$activityId];$cohortSql="SELECT cc.id,cc.title,cc.course_id,c.title course_title FROM course_cohorts cc JOIN courses c ON c.id=cc.course_id WHERE cc.activity_id=? AND cc.status!='archived' AND c.status!='archived'";if($courseId>0){$cohortSql.=' AND cc.course_id=?';$cohortArgs[]=$courseId;}$cohortSql.=' ORDER BY c.title COLLATE NOCASE,cc.title COLLATE NOCASE';$stmt=$db->prepare($cohortSql);$stmt->execute($cohortArgs);$cohortOptions=$stmt->fetchAll();if($cohortId>0&&!array_filter($cohortOptions,static fn(array $row): bool=>(int)$row['id']===$cohortId))$cohortId=0;
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('course-registrations',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}$id=(int)($_POST['submission_id']??0);$action=(string)($_POST['action']??'');
    try{
        $stmt=$db->prepare("SELECT s.* FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE s.id=? AND f.activity_id=? AND f.purpose='enrollment'");$stmt->execute([$id,$activityId]);$row=$stmt->fetch()?:throw new RuntimeException('Inscrição não encontrada.');$rowCourseId=(int)($row['course_id']??0);$rowCourse=$rowCourseId>0?course_by_id($db,$rowCourseId):null;$now=utc_now();$paymentNote=array_key_exists('payment_note',$_POST)?trim((string)$_POST['payment_note']):(string)($row['payment_note']??'');
        if($action==='confirm')$db->prepare("UPDATE cms_form_submissions SET status='converted',payment_status='paid',payment_confirmed_at=?,payment_note=?,updated_at=? WHERE id=?")->execute([$now,$paymentNote,$now,$id]);
        elseif($action==='pending')$db->prepare("UPDATE cms_form_submissions SET status='new',payment_status='pending',payment_confirmed_at=NULL,payment_note=?,updated_at=? WHERE id=?")->execute([$paymentNote,$now,$id]);
        elseif($action==='archive')$db->prepare("UPDATE cms_form_submissions SET status='archived',payment_note=?,updated_at=? WHERE id=?")->execute([$paymentNote,$now,$id]);
        elseif($action==='assign_cohort'){if(!$rowCourse)throw new RuntimeException('A inscrição não possui curso associado.');course_registration_assign_cohort($db,$id,$rowCourseId,(int)($_POST['cohort_id']??0));}
        elseif($action==='unassign_cohort'){if(!$rowCourse)throw new RuntimeException('A inscrição não possui curso associado.');course_registration_unassign_cohort($db,$id,$rowCourseId);}
        elseif($action==='delete_registration')admin_registration_delete($db,$id,$activityId);
        else throw new RuntimeException('Ação inválida.');
        student_enrollment_reconcile_confirmed($db,$activityId);$_SESSION['admin_registrations_notice']='Alteração salva.';
    }catch(Throwable $e){$_SESSION['admin_registrations_notice']='Não foi possível concluir: '.$e->getMessage();}
    $redirectCourse=max(0,(int)($_POST['filter_course_id']??0));$redirectCohort=max(0,(int)($_POST['filter_cohort_id']??0));$redirectFilter=(string)($_POST['filter_status']??'');$redirectSearch=trim((string)($_POST['search_q']??''));$redirectPage=max(1,(int)($_POST['list_page']??1));header('Location: '.registration_admin_url($activityId,$redirectCourse,$redirectCohort,$action==='delete_registration'?0:$id,$redirectFilter,$redirectSearch,$redirectPage),true,303);exit;
}
$baseWhere=["f.activity_id=?","f.purpose='enrollment'"];$baseArgs=[$activityId];if($courseId>0){$baseWhere[]='s.course_id=?';$baseArgs[]=$courseId;}if($cohortId>0){$baseWhere[]='s.cohort_id=?';$baseArgs[]=$cohortId;}$statsWhere=implode(' AND ',$baseWhere);$statsStmt=$db->prepare("SELECT SUM(CASE WHEN s.status!='archived' THEN 1 ELSE 0 END) total,SUM(CASE WHEN s.status!='archived' AND s.payment_status!='paid' AND s.status!='converted' THEN 1 ELSE 0 END) pending,SUM(CASE WHEN s.status!='archived' AND (s.payment_status='paid' OR s.status='converted') AND s.cohort_id IS NULL THEN 1 ELSE 0 END) unassigned,SUM(CASE WHEN s.status!='archived' AND s.cohort_id IS NOT NULL THEN 1 ELSE 0 END) assigned FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE $statsWhere");$statsStmt->execute($baseArgs);$stats=$statsStmt->fetch()?:['total'=>0,'pending'=>0,'unassigned'=>0,'assigned'=>0];
$where=$baseWhere;$args=$baseArgs;if($filter==='pending')$where[]="s.status!='archived' AND s.payment_status!='paid' AND s.status!='converted'";elseif($filter==='unassigned')$where[]="s.status!='archived' AND (s.payment_status='paid' OR s.status='converted') AND s.cohort_id IS NULL";elseif($filter==='assigned')$where[]="s.status!='archived' AND s.cohort_id IS NOT NULL";elseif($filter==='cancelled')$where[]="s.status='archived'";else $where[]="s.status!='archived'";if($search!==''){$where[]='(s.payload_json LIKE ? OR CAST(s.id AS TEXT) LIKE ? OR f.title LIKE ? OR c.title LIKE ?)';$like='%'.$search.'%';array_push($args,$like,$like,$like,$like);}$whereSql=implode(' AND ',$where);
$count=$db->prepare("SELECT COUNT(*) FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id LEFT JOIN courses c ON c.id=s.course_id WHERE $whereSql");$count->execute($args);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$pageSize));if($page>$pages)$page=$pages;$offset=($page-1)*$pageSize;
$sql="SELECT s.*,f.title form_title,c.title course_title,cc.title cohort_title FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id LEFT JOIN courses c ON c.id=s.course_id LEFT JOIN course_cohorts cc ON cc.id=s.cohort_id WHERE $whereSql ORDER BY s.created_at DESC,s.id DESC LIMIT $pageSize OFFSET $offset";$stmt=$db->prepare($sql);$stmt->execute($args);$rows=$stmt->fetchAll();
$selected=null;$selectedCourse=null;$selectedCohorts=[];if($selectedId>0){$stmt=$db->prepare("SELECT s.*,f.title form_title,c.title course_title,cc.title cohort_title FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id LEFT JOIN courses c ON c.id=s.course_id LEFT JOIN course_cohorts cc ON cc.id=s.cohort_id WHERE s.id=? AND f.activity_id=? AND f.purpose='enrollment'");$stmt->execute([$selectedId,$activityId]);$selected=$stmt->fetch()?:null;if($selected&&(int)($selected['course_id']??0)>0){$selectedCourse=course_by_id($db,(int)$selected['course_id']);if($selectedCourse)$selectedCohorts=course_cohorts_for_course($db,(int)$selectedCourse['id']);}}
$availability=[];if($courseId>0){$availabilityStmt=$db->prepare("SELECT s.payload_json,s.form_snapshot_json FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE s.course_id=? AND s.status!='archived' AND f.purpose='enrollment' ORDER BY s.created_at DESC");$availabilityStmt->execute([$courseId]);$availability=registration_availability_summary($availabilityStmt->fetchAll());}
$notice=(string)($_SESSION['admin_registrations_notice']??'');unset($_SESSION['admin_registrations_notice']);
admin_shell_start('registrations','Inscrições',$state);?>
<?php if($notice!==''):?><div class="admin-notice"><?=h($notice)?></div><?php endif;?>
<div class="admin-stat-grid"><div class="admin-stat"><span>Total ativo</span><strong><?=(int)($stats['total']??0)?></strong></div><div class="admin-stat"><span>Aguardando pagamento</span><strong><?=(int)($stats['pending']??0)?></strong></div><div class="admin-stat"><span>Confirmadas sem turma</span><strong><?=(int)($stats['unassigned']??0)?></strong></div><div class="admin-stat"><span>Com turma</span><strong><?=(int)($stats['assigned']??0)?></strong></div></div>
<form class="admin-filter-bar" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><label>Curso<select name="course"><option value="0">Todos os cursos</option><?php foreach($courses as $item):?><option value="<?=(int)$item['id']?>"<?=$courseId===(int)$item['id']?' selected':''?>><?=h((string)$item['title'])?></option><?php endforeach;?></select></label><label>Turma<select name="cohort"><option value="0">Todas as turmas</option><?php foreach($cohortOptions as $item):?><option value="<?=(int)$item['id']?>"<?=$cohortId===(int)$item['id']?' selected':''?>><?=h(($courseId>0?'':(string)$item['course_title'].' · ').(string)$item['title'])?></option><?php endforeach;?></select></label><label>Status<select name="status"><option value=""<?=$filter===''?' selected':''?>>Ativas</option><option value="pending"<?=$filter==='pending'?' selected':''?>>Aguardando pagamento</option><option value="unassigned"<?=$filter==='unassigned'?' selected':''?>>Confirmadas sem turma</option><option value="assigned"<?=$filter==='assigned'?' selected':''?>>Com turma</option><option value="cancelled"<?=$filter==='cancelled'?' selected':''?>>Canceladas</option></select></label><label class="grow">Buscar<input name="q" value="<?=h($search)?>" placeholder="Nome, e-mail, telefone ou número"></label><div class="admin-filter-actions"><button class="admin-button secondary" type="submit">Aplicar</button><?php if($courseId>0||$cohortId>0||$filter!==''||$search!==''):?><a class="admin-button secondary" href="<?=h(registration_admin_url($activityId))?>">Limpar</a><?php endif;?></div></form>
<div class="admin-list-summary"><span><?php if($total>0):?>Mostrando <?=($offset+1)?>–<?=min($offset+$pageSize,$total)?> de <?=$total?> inscrição(ões)<?php else:?>Nenhuma inscrição neste filtro<?php endif;?></span><?php if($course):?><span>Filtro de curso: <?=h((string)$course['title'])?></span><?php else:?><span>Pagamento e turma são dimensões independentes.</span><?php endif;?></div>
<?php if($availability):?><section class="admin-compact-summary"><header><strong>Disponibilidade agregada · <?=h((string)$course['title'])?></strong><span>Base: inscrições ativas do curso</span></header><div class="admin-availability-grid"><?php foreach($availability as $label=>$count):?><div class="admin-availability-item"><strong><?=(int)$count?></strong><span><?=h((string)$label)?></span></div><?php endforeach;?></div></section><?php endif;?>
<?php if(!$rows):?><div class="admin-empty">Nenhuma inscrição encontrada.</div><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Pessoa</th><th>Curso</th><th>Status</th><th>Pagamento</th><th>Turma</th><th>Data</th><th></th></tr></thead><tbody><?php foreach($rows as $row):$payload=registration_payload($row);?><tr><td><div class="admin-table-primary"><strong><?=h(registration_name($row))?></strong><span><?=h((string)($payload['email']??$payload['phone']??''))?> · #<?=(int)$row['id']?></span></div></td><td><?=h((string)($row['course_title']?:'Sem curso associado'))?></td><td><?=h(registration_status_label($row))?></td><td><?=h((string)($row['payment_status']?:'pending'))?></td><td><?=h((string)($row['cohort_title']?:'—'))?></td><td><?=h(date('d/m/Y',strtotime((string)$row['created_at'])))?></td><td class="actions"><a class="admin-button secondary admin-table-action" href="<?=h(registration_admin_url($activityId,$courseId,$cohortId,(int)$row['id'],$filter,$search,$page))?>">Abrir</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<div class="admin-pagination"><span>Página <?=$page?> de <?=$pages?></span><?php if($pages>1):?><nav aria-label="Paginação de inscrições"><?php if($page>1):?><a href="<?=h(registration_admin_url($activityId,$courseId,$cohortId,0,$filter,$search,$page-1))?>">← Anterior</a><?php endif;?><?php if($page<$pages):?><a href="<?=h(registration_admin_url($activityId,$courseId,$cohortId,0,$filter,$search,$page+1))?>">Próxima →</a><?php endif;?></nav><?php endif;?></div>
<?php if($selected):$payload=registration_payload($selected);$fields=registration_fields($selected);?>
<section class="admin-record-panel"><header><div><span class="admin-scope-label">Inscrição #<?=(int)$selected['id']?></span><h2><?=h(registration_name($selected))?></h2><p><?=h((string)($selected['course_title']?:'Sem curso associado'))?> · <?=h(date('d/m/Y · H:i',strtotime((string)$selected['created_at'])))?></p></div><a class="admin-button secondary" href="<?=h(registration_admin_url($activityId,$courseId,$cohortId,0,$filter,$search,$page))?>">Fechar detalhe</a></header>
<div class="admin-record-columns"><section class="registration-admin-group"><h3>Contato</h3><dl class="inbox-fields"><?php foreach(['cpf'=>'CPF','phone'=>'WhatsApp','email'=>'E-mail','instagram'=>'Instagram','city_state'=>'Cidade/UF','city'=>'Cidade'] as $key=>$label):$value=$payload[$key]??'';if($value===''||$value===[])continue;?><div><dt><?=h($label)?></dt><dd><?=h(registration_value_label($fields[$key]??[],$value))?></dd></div><?php endforeach;?></dl></section><section class="registration-admin-group"><h3>Disponibilidade</h3><?php $shown=false;foreach(['availability','preferred_days','preferred_time'] as $key):$value=$payload[$key]??'';if($value===''||$value===[])continue;$shown=true;?><p><strong><?=h((string)($fields[$key]['label']??$key))?>:</strong> <?=h(registration_value_label($fields[$key]??[],$value))?></p><?php endforeach;?><?php if(!$shown):?><p class="muted">Nenhuma disponibilidade registrada.</p><?php endif;?></section></div>
<section class="registration-admin-group"><h3>Turma</h3><?php if(!$selectedCourse):?><p class="muted">A inscrição não possui curso associado; não é possível atribuir turma.</p><?php elseif((int)($selected['cohort_id']??0)>0):?><p><strong><?=h((string)($selected['cohort_title']?:'Turma definida'))?></strong></p><form method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('course-registrations'))?>"><input type="hidden" name="action" value="unassign_cohort"><input type="hidden" name="submission_id" value="<?=(int)$selected['id']?>"><input type="hidden" name="filter_course_id" value="<?=$courseId?>"><input type="hidden" name="filter_cohort_id" value="<?=$cohortId?>"><input type="hidden" name="filter_status" value="<?=h($filter)?>"><input type="hidden" name="search_q" value="<?=h($search)?>"><input type="hidden" name="list_page" value="<?=$page?>"><button class="admin-button secondary" type="submit">Remover atribuição</button></form><?php else:?><form class="admin-inline-actions" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('course-registrations'))?>"><input type="hidden" name="action" value="assign_cohort"><input type="hidden" name="submission_id" value="<?=(int)$selected['id']?>"><input type="hidden" name="filter_course_id" value="<?=$courseId?>"><input type="hidden" name="filter_cohort_id" value="<?=$cohortId?>"><input type="hidden" name="filter_status" value="<?=h($filter)?>"><input type="hidden" name="search_q" value="<?=h($search)?>"><input type="hidden" name="list_page" value="<?=$page?>"><select name="cohort_id" required><option value="">Escolha a turma</option><?php foreach($selectedCohorts as $item):?><option value="<?=(int)$item['id']?>"><?=h((string)$item['title'])?></option><?php endforeach;?></select><button class="admin-button" type="submit">Atribuir turma</button></form><?php endif;?></section>
<section class="registration-admin-payment"><p class="admin-kicker">Pagamento</p><h3><?=($selected['payment_status']??'pending')==='paid'?'Confirmado':'Aguardando confirmação'?></h3><form method="post" class="registration-payment-form"><input type="hidden" name="_csrf" value="<?=h(csrf_token('course-registrations'))?>"><input type="hidden" name="submission_id" value="<?=(int)$selected['id']?>"><input type="hidden" name="filter_course_id" value="<?=$courseId?>"><input type="hidden" name="filter_cohort_id" value="<?=$cohortId?>"><input type="hidden" name="filter_status" value="<?=h($filter)?>"><input type="hidden" name="search_q" value="<?=h($search)?>"><input type="hidden" name="list_page" value="<?=$page?>"><label>Informações do pagamento<textarea name="payment_note" rows="3"><?=h((string)($selected['payment_note']??''))?></textarea></label><div class="registration-payment-actions"><?php if(($selected['payment_status']??'pending')!=='paid'):?><button class="admin-button" type="submit" name="action" value="confirm">Confirmar pagamento</button><?php else:?><button class="admin-button secondary" type="submit" name="action" value="pending">Marcar como aguardando</button><?php endif;?><button class="admin-button secondary" type="submit" name="action" value="archive">Cancelar inscrição</button></div></form></section>
<section class="registration-admin-delete"><h3>Excluir inscrição</h3><p>Remove esta inscrição. A identidade global da pessoa não é apagada.</p><form method="post" data-confirm="Excluir definitivamente esta inscrição?"><input type="hidden" name="_csrf" value="<?=h(csrf_token('course-registrations'))?>"><input type="hidden" name="action" value="delete_registration"><input type="hidden" name="submission_id" value="<?=(int)$selected['id']?>"><input type="hidden" name="filter_course_id" value="<?=$courseId?>"><input type="hidden" name="filter_cohort_id" value="<?=$cohortId?>"><input type="hidden" name="filter_status" value="<?=h($filter)?>"><input type="hidden" name="search_q" value="<?=h($search)?>"><input type="hidden" name="list_page" value="<?=$page?>"><button class="admin-button danger" type="submit">Excluir definitivamente</button></form></section>
</section><?php endif;?>
<link rel="stylesheet" href="<?=h(admin_asset_url('/assets/admin-registration.css'))?>">
<?php admin_shell_end();
