<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];
function registration_payload(array $row): array {return json_decode((string)($row['payload_json']??''),true)?:[];}
function registration_snapshot(array $row): array {return json_decode((string)($row['form_snapshot_json']??''),true)?:[];}
function registration_fields(array $row): array {$map=[];foreach(registration_snapshot($row)['fields']??[] as $field)if(is_array($field)&&isset($field['id']))$map[(string)$field['id']]=$field;return $map;}
function registration_value_label(array $field,mixed $value): string {if(is_array($value))return implode(', ',array_map(fn($item)=>registration_value_label($field,(string)$item),$value));$raw=(string)$value;foreach($field['options']??[] as $option)if(is_array($option)&&(string)($option['value']??'')===$raw)return (string)($option['label']??$raw);return $raw;}
function registration_name(array $row): string {$p=registration_payload($row);return trim((string)($p['name']??$p['full_name']??''))?:trim((string)($p['email']??''))?:'Inscrição #'.(int)$row['id'];}
function registration_status_label(array $row): string {if(($row['status']??'')==='archived')return 'Cancelada';if((int)($row['cohort_id']??0)>0&&student_account_submission_confirmed($row))return 'Turma definida';if(student_account_submission_confirmed($row))return 'Confirmada · sem turma';return 'Aguardando pagamento';}
function registration_admin_url(int $activityId,int $courseId=0,int $submissionId=0,string $filter='',string $search='',int $page=1): string {$args=['activity'=>$activityId];if($courseId>0)$args['course']=$courseId;if($submissionId>0)$args['submission']=$submissionId;if($filter!=='')$args['status']=$filter;if($search!=='')$args['q']=$search;if($page>1)$args['page']=$page;return '/admin/registrations.php?'.http_build_query($args);}
function registration_availability_summary(array $rows): array {
    $counts=[];
    foreach($rows as $row){$payload=registration_payload($row);$fields=registration_fields($row);foreach(['availability','preferred_days','preferred_time'] as $key){$value=$payload[$key]??null;if($value===null||$value===''||$value===[])continue;$values=is_array($value)?$value:[$value];foreach($values as $item){$label=trim(registration_value_label($fields[$key]??[],(string)$item));if($label==='')continue;$counts[$label]=($counts[$label]??0)+1;}}}
    arsort($counts,SORT_NUMERIC);return $counts;
}
$courses=course_list($db,$activityId);$courseId=(int)($_GET['course']??$_POST['course_id']??0);if($courseId<1&&count($courses)===1)$courseId=(int)$courses[0]['id'];$course=$courseId>0?course_by_id($db,$courseId):null;if($course&&(int)$course['activity_id']!==$activityId)$course=null;
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('course-registrations',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}$id=(int)($_POST['submission_id']??0);$action=(string)($_POST['action']??'');
    try{
        if(!$course)throw new RuntimeException('Escolha o curso desta inscrição.');$q=$db->prepare("SELECT s.* FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE s.id=? AND s.course_id=? AND f.purpose='enrollment'");$q->execute([$id,(int)$course['id']]);$row=$q->fetch()?:throw new RuntimeException('Inscrição não encontrada neste curso.');$now=utc_now();$paymentNote=array_key_exists('payment_note',$_POST)?trim((string)$_POST['payment_note']):(string)($row['payment_note']??'');
        if($action==='confirm')$db->prepare("UPDATE cms_form_submissions SET status='converted',payment_status='paid',payment_confirmed_at=?,payment_note=?,updated_at=? WHERE id=?")->execute([$now,$paymentNote,$now,$id]);
        elseif($action==='pending')$db->prepare("UPDATE cms_form_submissions SET status='new',payment_status='pending',payment_confirmed_at=NULL,payment_note=?,updated_at=? WHERE id=?")->execute([$paymentNote,$now,$id]);
        elseif($action==='archive')$db->prepare("UPDATE cms_form_submissions SET status='archived',payment_note=?,updated_at=? WHERE id=?")->execute([$paymentNote,$now,$id]);
        elseif($action==='assign_cohort')course_registration_assign_cohort($db,$id,(int)$course['id'],(int)($_POST['cohort_id']??0));
        elseif($action==='unassign_cohort')course_registration_unassign_cohort($db,$id,(int)$course['id']);
        elseif($action==='delete_registration')admin_registration_delete($db,$id,$activityId);
        else throw new RuntimeException('Ação inválida.');
        student_enrollment_reconcile_confirmed($db,$activityId);$_SESSION['admin_registrations_notice']='Alteração salva.';
    }catch(Throwable $e){$_SESSION['admin_registrations_notice']='Não foi possível concluir: '.$e->getMessage();}
    $redirectFilter=(string)($_POST['filter_status']??'');$redirectSearch=trim((string)($_POST['search_q']??''));$redirectPage=max(1,(int)($_POST['list_page']??1));header('Location: '.registration_admin_url($activityId,$courseId,$action==='delete_registration'?0:$id,$redirectFilter,$redirectSearch,$redirectPage),true,303);exit;
}
$notice=(string)($_SESSION['admin_registrations_notice']??'');unset($_SESSION['admin_registrations_notice']);
admin_shell_start('registrations','Inscrições',$state);?>
<?php if($notice!==''):?><div class="admin-notice"><?=h($notice)?></div><?php endif;?>
<?php if(!$course):
$courseQ=trim((string)($_GET['q']??''));$coursePage=max(1,(int)($_GET['page']??1));$coursePageSize=25;$where=["c.activity_id=?","c.status!='archived'"];$args=[$activityId];if($courseQ!==''){$where[]='(c.title LIKE ? OR c.slug LIKE ?)';$like='%'.$courseQ.'%';array_push($args,$like,$like);}$whereSql=implode(' AND ',$where);$count=$db->prepare("SELECT COUNT(*) FROM courses c WHERE $whereSql");$count->execute($args);$courseTotal=(int)$count->fetchColumn();$coursePages=max(1,(int)ceil($courseTotal/$coursePageSize));if($coursePage>$coursePages)$coursePage=$coursePages;$offset=($coursePage-1)*$coursePageSize;$sql="SELECT c.*,(SELECT COUNT(*) FROM cms_form_submissions s WHERE s.course_id=c.id AND s.status!='archived') total,(SELECT COUNT(*) FROM cms_form_submissions s WHERE s.course_id=c.id AND s.status!='archived' AND (s.status='converted' OR s.payment_status='paid') AND s.cohort_id IS NULL) unassigned FROM courses c WHERE $whereSql ORDER BY c.title COLLATE NOCASE,c.id LIMIT $coursePageSize OFFSET $offset";$q=$db->prepare($sql);$q->execute($args);$courseRows=$q->fetchAll();?>
<section class="overview-hero"><div><p class="admin-kicker">Inscrições</p><h2>Escolha o curso</h2><p>Inscrições são administradas no contexto do curso. Use a busca quando o catálogo crescer.</p></div></section>
<form class="admin-data-toolbar" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><label class="grow">Buscar curso<input name="q" value="<?=h($courseQ)?>" placeholder="Nome ou slug"></label><button class="admin-button secondary" type="submit">Buscar</button><?php if($courseQ!==''):?><a class="admin-button secondary" href="<?=h(registration_admin_url($activityId))?>">Limpar</a><?php endif;?></form>
<?php if(!$courseRows):?><section class="admin-card"><div class="admin-empty"><?=$courseQ!==''?'Nenhum curso corresponde à busca.':'Nenhum curso foi configurado.'?></div></section><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Curso</th><th>Inscrições</th><th>Confirmadas sem turma</th><th></th></tr></thead><tbody><?php foreach($courseRows as $row):?><tr><td><div class="admin-table-primary"><strong><?=h((string)$row['title'])?></strong><span><?=h((string)$row['slug'])?></span></div></td><td class="admin-table-number"><?=(int)$row['total']?></td><td class="admin-table-number"><?=(int)$row['unassigned']?></td><td class="actions"><a class="admin-button secondary admin-table-action" href="<?=h(registration_admin_url($activityId,(int)$row['id']))?>">Abrir</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<div class="admin-pagination"><span><?php if($courseTotal>0):?>Mostrando <?=($offset+1)?>–<?=min($offset+$coursePageSize,$courseTotal)?> de <?=$courseTotal?> curso(s)<?php else:?>0 cursos<?php endif;?></span><?php if($coursePages>1):?><nav aria-label="Paginação de cursos"><?php if($coursePage>1):?><a href="<?=h(registration_admin_url($activityId,0,0,'',$courseQ,$coursePage-1))?>">← Anterior</a><?php endif;?><span>Página <?=$coursePage?> de <?=$coursePages?></span><?php if($coursePage<$coursePages):?><a href="<?=h(registration_admin_url($activityId,0,0,'',$courseQ,$coursePage+1))?>">Próxima →</a><?php endif;?></nav><?php endif;?></div>
<?php else:$courseId=(int)$course['id'];
$statsQ=$db->prepare("SELECT COUNT(*) total,SUM(CASE WHEN status!='archived' AND payment_status!='paid' AND status!='converted' THEN 1 ELSE 0 END) pending,SUM(CASE WHEN status!='archived' AND (payment_status='paid' OR status='converted') AND cohort_id IS NULL THEN 1 ELSE 0 END) unassigned,SUM(CASE WHEN status!='archived' AND cohort_id IS NOT NULL THEN 1 ELSE 0 END) assigned FROM cms_form_submissions WHERE course_id=?");$statsQ->execute([$courseId]);$stats=$statsQ->fetch()?:['total'=>0,'pending'=>0,'unassigned'=>0,'assigned'=>0];
$availabilityQ=$db->prepare("SELECT s.payload_json,s.form_snapshot_json FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE s.course_id=? AND s.status!='archived' AND f.purpose='enrollment' ORDER BY s.created_at DESC");$availabilityQ->execute([$courseId]);$availability=registration_availability_summary($availabilityQ->fetchAll());
$allowedFilters=['','pending','unassigned','assigned','cancelled'];$filter=(string)($_GET['status']??'');if(!in_array($filter,$allowedFilters,true))$filter='';$search=trim((string)($_GET['q']??''));$page=max(1,(int)($_GET['page']??1));$pageSize=50;$where=['s.course_id=?',"f.purpose='enrollment'"];$args=[$courseId];if($filter==='pending')$where[]="s.status!='archived' AND s.payment_status!='paid' AND s.status!='converted'";elseif($filter==='unassigned')$where[]="s.status!='archived' AND (s.payment_status='paid' OR s.status='converted') AND s.cohort_id IS NULL";elseif($filter==='assigned')$where[]="s.status!='archived' AND s.cohort_id IS NOT NULL";elseif($filter==='cancelled')$where[]="s.status='archived'";if($search!==''){$where[]='(s.payload_json LIKE ? OR CAST(s.id AS TEXT) LIKE ? OR f.title LIKE ?)';$like='%'.$search.'%';array_push($args,$like,$like,$like);}$whereSql=implode(' AND ',$where);$count=$db->prepare("SELECT COUNT(*) FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE $whereSql");$count->execute($args);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$pageSize));if($page>$pages)$page=$pages;$offset=($page-1)*$pageSize;$sql="SELECT s.*,f.title form_title FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE $whereSql ORDER BY s.created_at DESC,s.id DESC LIMIT $pageSize OFFSET $offset";$q=$db->prepare($sql);$q->execute($args);$rows=$q->fetchAll();$selectedId=(int)($_GET['submission']??0);if(!$selectedId&&$rows)$selectedId=(int)$rows[0]['id'];$selected=null;if($selectedId){$q=$db->prepare("SELECT s.*,f.title form_title FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE s.id=? AND s.course_id=? AND f.purpose='enrollment'");$q->execute([$selectedId,$courseId]);$selected=$q->fetch()?:null;}$cohorts=course_cohorts_for_course($db,$courseId);
admin_course_context($course,$activityId,'registrations','Pagamento e turma são estados independentes; filtre e localize a inscrição antes de abrir o detalhe.');?>
<div class="admin-stat-grid"><div class="admin-stat"><span>Total</span><strong><?=(int)$stats['total']?></strong></div><div class="admin-stat"><span>Aguardando pagamento</span><strong><?=(int)$stats['pending']?></strong></div><div class="admin-stat"><span>Confirmadas sem turma</span><strong><?=(int)$stats['unassigned']?></strong></div><div class="admin-stat"><span>Com turma</span><strong><?=(int)$stats['assigned']?></strong></div></div>
<?php if($availability):?><section class="admin-card"><header><div><h2>Disponibilidade agregada</h2><p>Leitura operacional das opções marcadas nas inscrições ativas para ajudar a formar turmas.</p></div></header><div class="admin-availability-grid"><?php foreach($availability as $label=>$count):?><div class="admin-availability-item"><strong><?=(int)$count?></strong><span><?=h((string)$label)?></span></div><?php endforeach;?></div></section><?php endif;?>
<nav class="admin-subtabs" aria-label="Filtrar inscrições"><a href="<?=h(registration_admin_url($activityId,$courseId,0,'',$search))?>"<?=$filter===''?' aria-current="page"':''?>>Todas</a><a href="<?=h(registration_admin_url($activityId,$courseId,0,'pending',$search))?>"<?=$filter==='pending'?' aria-current="page"':''?>>Aguardando pagamento</a><a href="<?=h(registration_admin_url($activityId,$courseId,0,'unassigned',$search))?>"<?=$filter==='unassigned'?' aria-current="page"':''?>>Confirmadas sem turma</a><a href="<?=h(registration_admin_url($activityId,$courseId,0,'assigned',$search))?>"<?=$filter==='assigned'?' aria-current="page"':''?>>Com turma</a><a href="<?=h(registration_admin_url($activityId,$courseId,0,'cancelled',$search))?>"<?=$filter==='cancelled'?' aria-current="page"':''?>>Canceladas</a></nav>
<form class="admin-data-toolbar" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><input type="hidden" name="course" value="<?=$courseId?>"><?php if($filter!==''):?><input type="hidden" name="status" value="<?=h($filter)?>"><?php endif;?><label class="grow">Buscar inscrição<input name="q" value="<?=h($search)?>" placeholder="Nome, e-mail, telefone, número da inscrição..."></label><button class="admin-button secondary" type="submit">Buscar</button><?php if($search!==''):?><a class="admin-button secondary" href="<?=h(registration_admin_url($activityId,$courseId,0,$filter))?>">Limpar</a><?php endif;?></form>
<div class="admin-list-summary"><span><?php if($total>0):?>Mostrando <?=($offset+1)?>–<?=min($offset+$pageSize,$total)?> de <?=$total?> inscrição(ões)<?php else:?>Nenhuma inscrição neste filtro<?php endif;?></span></div>
<div class="submissions-layout inbox-layout"><section class="submission-list inbox-list" aria-label="Inscrições do curso"><?php if(!$rows):?><div class="admin-empty compact">Nenhuma inscrição encontrada.</div><?php endif;?><?php foreach($rows as $row):$payload=registration_payload($row);?><a class="submission-row<?=$selectedId===(int)$row['id']?' selected':''?>" href="<?=h(registration_admin_url($activityId,$courseId,(int)$row['id'],$filter,$search,$page))?>"><div class="submission-row-main"><strong><?=h(registration_name($row))?></strong><span><?=h((string)($payload['email']??$payload['phone']??''))?></span></div><div class="submission-row-meta"><time><?=h(date('d/m · H:i',strtotime((string)$row['created_at'])))?></time><small><?=h(registration_status_label($row))?></small></div></a><?php endforeach;?></section>
<?php if($selected):$payload=registration_payload($selected);$fields=registration_fields($selected);?><aside class="submission-detail inbox-detail"><header class="inbox-detail-header"><div><p>Inscrição #<?=(int)$selected['id']?></p><h2><?=h(registration_name($selected))?></h2><span><?=h(date('d/m/Y · H:i',strtotime((string)$selected['created_at'])))?></span></div></header>
<section class="registration-admin-status"><div><span>Status</span><strong><?=h(registration_status_label($selected))?></strong></div></section>
<section class="registration-admin-group"><h3>Contato</h3><dl class="inbox-fields"><?php foreach(['cpf'=>'CPF','phone'=>'WhatsApp','email'=>'E-mail','instagram'=>'Instagram','city_state'=>'Cidade/UF','city'=>'Cidade'] as $key=>$label):$value=$payload[$key]??'';if($value===''||$value===[])continue;?><div><dt><?=h($label)?></dt><dd><?=h(registration_value_label($fields[$key]??[],$value))?></dd></div><?php endforeach;?></dl></section>
<section class="registration-admin-group"><h3>Disponibilidade</h3><?php $shown=false;foreach(['availability','preferred_days','preferred_time'] as $key):$value=$payload[$key]??'';if($value===''||$value===[])continue;$shown=true;?><p><strong><?=h((string)($fields[$key]['label']??$key))?>:</strong> <?=h(registration_value_label($fields[$key]??[],$value))?></p><?php endforeach;?><?php if(!$shown):?><p class="muted">Nenhuma disponibilidade registrada neste formulário.</p><?php endif;?></section>
<section class="registration-admin-group"><h3>Turma</h3><p>Defina a turma somente depois de considerar as disponibilidades. Isso não depende da confirmação do pagamento.</p><?php if((int)($selected['cohort_id']??0)>0):$current=course_cohort_by_id($db,(int)$selected['cohort_id']);?><p><strong><?=h((string)($current['title']??'Turma definida'))?></strong></p><form method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('course-registrations'))?>"><input type="hidden" name="action" value="unassign_cohort"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="submission_id" value="<?=(int)$selected['id']?>"><input type="hidden" name="filter_status" value="<?=h($filter)?>"><input type="hidden" name="search_q" value="<?=h($search)?>"><input type="hidden" name="list_page" value="<?=$page?>"><button class="admin-button secondary" type="submit">Remover atribuição</button></form><?php else:?><form class="admin-inline-actions" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('course-registrations'))?>"><input type="hidden" name="action" value="assign_cohort"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="submission_id" value="<?=(int)$selected['id']?>"><input type="hidden" name="filter_status" value="<?=h($filter)?>"><input type="hidden" name="search_q" value="<?=h($search)?>"><input type="hidden" name="list_page" value="<?=$page?>"><select name="cohort_id" required><option value="">Escolha a turma</option><?php foreach($cohorts as $cohort):?><option value="<?=(int)$cohort['id']?>"><?=h((string)$cohort['title'])?></option><?php endforeach;?></select><button class="admin-button" type="submit">Atribuir turma</button></form><?php endif;?></section>
<section class="registration-admin-payment"><p class="admin-kicker">Pagamento</p><h3><?=($selected['payment_status']??'pending')==='paid'?'Confirmado':'Aguardando confirmação'?></h3><form method="post" class="registration-payment-form"><input type="hidden" name="_csrf" value="<?=h(csrf_token('course-registrations'))?>"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="submission_id" value="<?=(int)$selected['id']?>"><input type="hidden" name="filter_status" value="<?=h($filter)?>"><input type="hidden" name="search_q" value="<?=h($search)?>"><input type="hidden" name="list_page" value="<?=$page?>"><label>Informações do pagamento<textarea name="payment_note" rows="3"><?=h((string)($selected['payment_note']??''))?></textarea></label><div class="registration-payment-actions"><?php if(($selected['payment_status']??'pending')!=='paid'):?><button class="admin-button" type="submit" name="action" value="confirm">Confirmar pagamento</button><?php else:?><button class="admin-button secondary" type="submit" name="action" value="pending">Marcar como aguardando</button><?php endif;?><button class="admin-button secondary" type="submit" name="action" value="archive">Cancelar inscrição</button></div></form></section>
<section class="registration-admin-delete"><h3>Excluir inscrição</h3><p>Remove esta inscrição. A identidade global da pessoa não é apagada.</p><form method="post" data-confirm="Excluir definitivamente esta inscrição?"><input type="hidden" name="_csrf" value="<?=h(csrf_token('course-registrations'))?>"><input type="hidden" name="action" value="delete_registration"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="submission_id" value="<?=(int)$selected['id']?>"><input type="hidden" name="filter_status" value="<?=h($filter)?>"><input type="hidden" name="search_q" value="<?=h($search)?>"><input type="hidden" name="list_page" value="<?=$page?>"><button class="admin-button danger" type="submit">Excluir definitivamente</button></form></section></aside><?php endif;?></div>
<div class="admin-pagination"><span>Página <?=$page?> de <?=$pages?></span><?php if($pages>1):?><nav aria-label="Paginação de inscrições"><?php if($page>1):?><a href="<?=h(registration_admin_url($activityId,$courseId,0,$filter,$search,$page-1))?>">← Anterior</a><?php endif;?><?php if($page<$pages):?><a href="<?=h(registration_admin_url($activityId,$courseId,0,$filter,$search,$page+1))?>">Próxima →</a><?php endif;?></nav><?php endif;?></div>
<link rel="stylesheet" href="<?=h(admin_asset_url('/assets/admin-inbox.css'))?>"><link rel="stylesheet" href="<?=h(admin_asset_url('/assets/admin-registration.css'))?>">
<?php endif;?>
<?php admin_shell_end();
