<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/admin_shell.php';security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];$selectedId=(int)($_GET['page']??$_POST['page_id']??0);$notice=null;
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('cms-seo',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}
    try{$page=cms_page_by_id($db,$selectedId);if(!$page||(int)$page['activity_id']!==$activityId)throw new RuntimeException('page_not_found');cms_page_seo_save($db,$selectedId,['title'=>$_POST['title']??'','description'=>$_POST['description']??'','socialTitle'=>$_POST['social_title']??'','socialDescription'=>$_POST['social_description']??'','socialImage'=>$_POST['social_image']??'','canonicalUrl'=>$_POST['canonical_url']??'','robots'=>$_POST['robots']??'index,follow']);$_SESSION['admin_notice']='SEO da página atualizado.';header('Location: /admin/seo.php?activity='.$activityId.'&page='.$selectedId);exit;}catch(RuntimeException $e){$notice=$e->getMessage();}
}
$pages=cms_pages($db,$activityId,null,false);if(!$selectedId&&$pages)$selectedId=(int)$pages[0]['id'];$selected=$selectedId?cms_page_by_id($db,$selectedId):null;if($selected&&(int)$selected['activity_id']!==$activityId)$selected=null;$seo=$selected?cms_page_seo($db,(int)$selected['id']):cms_page_seo_defaults();$flash=$_SESSION['admin_notice']??null;unset($_SESSION['admin_notice']);$images=array_values(array_filter(media_list($db),fn(array $a)=>$a['kind']==='image'));
admin_shell_start('seo','SEO e compartilhamento',$state);?>
<?php if($flash||$notice):?><div class="admin-notice"><?=h((string)($flash?:$notice))?></div><?php endif;?>
<section class="overview-hero"><div><p class="admin-kicker">SEO por página</p><h2>Busca e compartilhamento social</h2><p>Defina título e descrição de busca, imagem e textos sociais, URL canônica e indexação sem alterar o conteúdo visual da página.</p></div></section>
<div class="form-builder-workspace seo-workspace"><aside class="admin-editor-card"><p class="admin-kicker">Páginas</p><nav class="seo-page-list"><?php foreach($pages as $p):?><a href="/admin/seo.php?activity=<?=$activityId?>&page=<?=(int)$p['id']?>"<?=$selectedId===(int)$p['id']?' aria-current="page"':''?>><strong><?=h($p['title'])?></strong><span><?=h(public_language_label($p['locale']))?> · <?=h($p['is_home']?'home':$p['slug'])?></span></a><?php endforeach;?></nav></aside>
<?php if($selected):?><section class="admin-editor-card"><div class="admin-editor-header"><div><p class="admin-kicker"><?=h(public_language_label($selected['locale']))?></p><h2><?=h($selected['title'])?></h2></div><a class="link-button" href="<?=h(cms_page_url($activity,$selected,$selected['locale']))?>" target="_blank" rel="noopener">Abrir página</a></div>
<form method="post" class="cms-settings-form"><input type="hidden" name="_csrf" value="<?=h(csrf_token('cms-seo'))?>"><input type="hidden" name="page_id" value="<?=(int)$selected['id']?>">
<label>Título para busca<input name="title" value="<?=h($seo['title'])?>" maxlength="180" placeholder="Se vazio, usa o título SEO da página ou o padrão global"></label>
<label>Descrição para busca<textarea name="description" rows="4" maxlength="500" placeholder="Resumo claro da página para mecanismos de busca"><?=h($seo['description'])?></textarea></label>
<div class="form-grid two-columns"><label>Título social<input name="social_title" value="<?=h($seo['socialTitle'])?>" maxlength="180" placeholder="Se vazio, usa o título de busca"></label><label>Robôs<select name="robots"><?php foreach(['index,follow'=>'Indexar e seguir links','noindex,follow'=>'Não indexar; seguir links','index,nofollow'=>'Indexar; não seguir links','noindex,nofollow'=>'Não indexar nem seguir'] as $value=>$label):?><option value="<?=$value?>"<?=$seo['robots']===$value?' selected':''?>><?=h($label)?></option><?php endforeach;?></select></label></div>
<label>Descrição social<textarea name="social_description" rows="3" maxlength="500" placeholder="Se vazia, usa a descrição de busca"><?=h($seo['socialDescription'])?></textarea></label>
<label>Imagem de compartilhamento<select id="seo-social-image-picker"><option value="">Usar imagem social global</option><?php foreach($images as $asset):?><option value="<?=h($asset['url'])?>"<?=$seo['socialImage']===$asset['url']?' selected':''?>>#<?=(int)$asset['id']?> · <?=h($asset['title']?:$asset['original_name'])?></option><?php endforeach;?></select></label><label>Caminho/URL da imagem<input id="seo-social-image" name="social_image" value="<?=h($seo['socialImage'])?>" placeholder="/uploads/media/... ou https://..."></label>
<label>URL canônica<input name="canonical_url" value="<?=h($seo['canonicalUrl'])?>" placeholder="https://seu-dominio.com/pagina/"></label><p class="admin-muted">Se a URL canônica ficar vazia, o sistema usa automaticamente a URL pública desta página e deste idioma.</p>
<div class="seo-preview"><p class="admin-kicker">Prévia aproximada de busca</p><strong id="seo-preview-title"><?=h($seo['title']?:$selected['title'])?></strong><span><?=h(cms_page_url($activity,$selected,$selected['locale']))?></span><p id="seo-preview-description"><?=h($seo['description'])?></p></div>
<div class="dialog-actions"><button class="admin-button" type="submit">Salvar SEO</button></div></form></section><?php endif;?></div>
<script>(()=>{const picker=document.querySelector('#seo-social-image-picker'),image=document.querySelector('#seo-social-image'),title=document.querySelector('[name="title"]'),desc=document.querySelector('[name="description"]'),pt=document.querySelector('#seo-preview-title'),pd=document.querySelector('#seo-preview-description');picker?.addEventListener('change',()=>{image.value=picker.value});title?.addEventListener('input',()=>pt.textContent=title.value||<?=json_encode($selected['title']??'',JSON_UNESCAPED_UNICODE)?>);desc?.addEventListener('input',()=>pd.textContent=desc.value)})();</script>
<style>.seo-workspace{grid-template-columns:minmax(250px,.38fr) minmax(0,1fr)}.seo-page-list{display:flex;flex-direction:column}.seo-page-list a{display:flex;flex-direction:column;gap:3px;padding:12px 0;border-bottom:1px solid #d8d8d2;text-decoration:none;color:inherit}.seo-page-list a[aria-current="page"]{font-weight:700}.seo-page-list span{font-size:12px;color:#686b68}.seo-preview{margin-top:22px;padding:18px;border:1px solid #d8d8d2;background:#fff}.seo-preview strong,.seo-preview span,.seo-preview p{display:block}.seo-preview strong{font-size:20px}.seo-preview span{font-size:12px;margin:5px 0;color:#186f4d}.seo-preview p{max-width:70ch}@media(max-width:900px){.seo-workspace{grid-template-columns:1fr}}</style>
<?php admin_shell_end();
