<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
security_headers();
require_admin();

function admin_seo_url(int $activityId,int $pageId=0,string $locale=PUBLIC_LOCALE_PT_BR,string $query='',int $listPage=1): string {
    $args=['activity'=>$activityId,'lang'=>public_locale_query($locale)];if($pageId)$args['page']=$pageId;if($query!=='')$args['q']=$query;if($listPage>1)$args['p']=$listPage;return '/admin/seo.php?'.http_build_query($args);
}

$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}
$activityId=(int)$activity['id'];$locale=normalize_public_locale($_GET['lang']??$_POST['locale']??PUBLIC_LOCALE_PT_BR)??PUBLIC_LOCALE_PT_BR;$query=trim((string)($_GET['q']??$_POST['return_q']??''));$listPage=max(1,(int)($_GET['p']??$_POST['return_page']??1));$pageSize=50;$selectedId=(int)($_GET['page']??$_POST['page_id']??0);$site=cms_site_settings($db,$activityId,$locale);$notice=null;
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('cms-seo',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}
    $action=(string)($_POST['action']??'page');
    try{
        if($action==='global'){
            $settings=$site;$settings['seo']=['defaultTitle'=>trim((string)($_POST['default_title']??'')),'defaultDescription'=>trim((string)($_POST['default_description']??'')),'socialImage'=>trim((string)($_POST['global_social_image']??'')),'favicon'=>trim((string)($_POST['favicon']??''))];cms_settings_save($db,'site',$activityId,$locale,$settings);$_SESSION['admin_notice']='SEO global atualizado.';header('Location: '.admin_seo_url($activityId,$selectedId,$locale,$query,$listPage).'#global-seo');exit;
        }
        $page=cms_page_by_id($db,$selectedId);if(!$page||(int)$page['activity_id']!==$activityId)throw new RuntimeException('page_not_found');
        cms_page_seo_save($db,$selectedId,['title'=>$_POST['title']??'','description'=>$_POST['description']??'','socialTitle'=>$_POST['social_title']??'','socialDescription'=>$_POST['social_description']??'','socialImage'=>$_POST['social_image']??'','canonicalUrl'=>$_POST['canonical_url']??'','robots'=>$_POST['robots']??'index,follow']);$_SESSION['admin_notice']='SEO da página atualizado.';header('Location: '.admin_seo_url($activityId,$selectedId,$locale,$query,$listPage).'#page-seo');exit;
    }catch(RuntimeException $error){$notice=$error->getMessage();}
}

$where=["activity_id=?","status!='archived'"];$args=[$activityId];if($query!==''){$where[]='(LOWER(title) LIKE ? OR LOWER(slug) LIKE ?)';$needle='%'.mb_strtolower($query).'%';$args[]=$needle;$args[]=$needle;}$whereSql=implode(' AND ',$where);$countQ=$db->prepare('SELECT COUNT(*) FROM cms_pages WHERE '.$whereSql);$countQ->execute($args);$pageCount=(int)$countQ->fetchColumn();$listPages=max(1,(int)ceil($pageCount/$pageSize));if($listPage>$listPages)$listPage=$listPages;$offset=($listPage-1)*$pageSize;$pageQ=$db->prepare("SELECT * FROM cms_pages WHERE {$whereSql} ORDER BY locale,is_home DESC,sort_order,id LIMIT {$pageSize} OFFSET {$offset}");$pageQ->execute($args);$pages=$pageQ->fetchAll();
if(!$selectedId&&$pages)$selectedId=(int)$pages[0]['id'];$selected=$selectedId?cms_page_by_id($db,$selectedId):null;if($selected&&((int)$selected['activity_id']!==$activityId||(string)$selected['status']==='archived'))$selected=null;$seo=$selected?cms_page_seo($db,(int)$selected['id']):cms_page_seo_defaults();$flash=$_SESSION['admin_notice']??null;unset($_SESSION['admin_notice']);
admin_shell_start('seo','SEO',$state,['/assets/admin-site.css','/assets/admin-seo.css']);?>
<?php if($flash||$notice):?><div class="admin-notice"><?=h((string)($flash?:$notice))?></div><?php endif;?>
<section class="site-intro"><p class="site-intro-copy">Defina os padrões de busca e compartilhamento do site e, quando necessário, sobrescreva esses valores página por página.</p><div class="site-intro-actions"><div class="site-language-switch" aria-label="Idioma dos padrões globais"><a href="<?=h(admin_seo_url($activityId,$selectedId,PUBLIC_LOCALE_PT_BR,$query,$listPage))?>"<?=$locale===PUBLIC_LOCALE_PT_BR?' aria-current="page"':''?>>PT</a><a href="<?=h(admin_seo_url($activityId,$selectedId,PUBLIC_LOCALE_EN,$query,$listPage))?>"<?=$locale===PUBLIC_LOCALE_EN?' aria-current="page"':''?>>EN</a></div></div></section>
<section class="site-settings-section" id="global-seo"><header><div><h2>Padrões globais · <?=h(public_language_label($locale))?></h2><p>Valores usados como fallback quando uma página não define sua própria informação. Imagens podem ser escolhidas na Biblioteca e referenciadas pelo caminho público.</p></div><a class="link-button" href="/admin/media.php?activity=<?=$activityId?>">Abrir mídia ↗</a></header><form method="post" class="cms-settings-form"><input type="hidden" name="_csrf" value="<?=h(csrf_token('cms-seo'))?>"><input type="hidden" name="action" value="global"><input type="hidden" name="locale" value="<?=h($locale)?>"><input type="hidden" name="page_id" value="<?=$selectedId?>"><input type="hidden" name="return_q" value="<?=h($query)?>"><input type="hidden" name="return_page" value="<?=$listPage?>"><label>Título padrão<input name="default_title" value="<?=h((string)$site['seo']['defaultTitle'])?>" maxlength="180"></label><label>Descrição padrão<textarea name="default_description" rows="4" maxlength="500"><?=h((string)$site['seo']['defaultDescription'])?></textarea></label><div class="form-grid two-columns"><label>Imagem social padrão<input name="global_social_image" value="<?=h((string)$site['seo']['socialImage'])?>" placeholder="/uploads/media/..."></label><label>Favicon<input name="favicon" value="<?=h((string)$site['seo']['favicon'])?>" placeholder="/uploads/media/..."></label></div><div class="dialog-actions"><button class="admin-button" type="submit">Salvar padrões globais</button></div></form></section>
<div class="site-seo-workspace" id="page-seo"><aside class="site-page-picker"><form class="site-page-picker-search" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><input type="hidden" name="lang" value="<?=h(public_locale_query($locale))?>"><input type="search" name="q" value="<?=h($query)?>" placeholder="Buscar página" aria-label="Buscar página"></form><nav class="site-page-picker-list" aria-label="Páginas"><?php if(!$pages):?><div class="site-empty-inline">Nenhuma página encontrada.</div><?php endif;?><?php foreach($pages as $page):?><a href="<?=h(admin_seo_url($activityId,(int)$page['id'],$locale,$query,$listPage))?>"<?=$selectedId===(int)$page['id']?' aria-current="page"':''?>><strong><?=h((string)$page['title'])?></strong><span><?=h(public_language_label((string)$page['locale']).' · '.((int)$page['is_home']===1?'home':(string)$page['slug']))?></span></a><?php endforeach;?></nav><?php if($listPages>1):?><div class="admin-pagination"><span><?=$listPage?> / <?=$listPages?></span><nav><?php for($p=max(1,$listPage-1);$p<=min($listPages,$listPage+1);$p++):?><a href="<?=h(admin_seo_url($activityId,0,$locale,$query,$p))?>"<?=$p===$listPage?' aria-current="page"':''?>><?=$p?></a><?php endfor;?></nav></div><?php endif;?></aside>
<?php if($selected):?><div class="site-settings-stack"><section class="site-context-bar"><div><span>Página</span><strong><?=h((string)$selected['title'])?></strong></div><div class="site-context-actions"><a class="link-button" href="<?=h(cms_page_url($activity,$selected,$selected['locale']))?>" target="_blank" rel="noopener">Abrir página ↗</a></div></section><form method="post" class="site-settings-stack"><input type="hidden" name="_csrf" value="<?=h(csrf_token('cms-seo'))?>"><input type="hidden" name="action" value="page"><input type="hidden" name="locale" value="<?=h($locale)?>"><input type="hidden" name="page_id" value="<?=(int)$selected['id']?>"><input type="hidden" name="return_q" value="<?=h($query)?>"><input type="hidden" name="return_page" value="<?=$listPage?>">
<section class="site-settings-section"><header><div><h2>Busca</h2><p>Título e descrição apresentados a mecanismos de busca. Vazios herdam os padrões disponíveis.</p></div></header><label>Título para busca<input name="title" data-seo-title value="<?=h((string)$seo['title'])?>" maxlength="180" placeholder="Usar fallback"></label><label>Descrição para busca<textarea name="description" data-seo-description rows="4" maxlength="500" placeholder="Resumo claro da página"><?=h((string)$seo['description'])?></textarea></label><div class="site-seo-preview"><strong data-seo-preview-title data-fallback="<?=h((string)$selected['title'])?>"><?=h((string)($seo['title']?:$selected['title']))?></strong><span><?=h(cms_page_url($activity,$selected,$selected['locale']))?></span><p data-seo-preview-description><?=h((string)$seo['description'])?></p></div></section>
<section class="site-settings-section"><header><div><h2>Compartilhamento social</h2><p>Textos e imagem usados quando a página é compartilhada. Campos vazios reutilizam os valores de busca ou os padrões globais.</p></div><a class="link-button" href="/admin/media.php?activity=<?=$activityId?>">Abrir mídia ↗</a></header><label>Título social<input name="social_title" value="<?=h((string)$seo['socialTitle'])?>" maxlength="180"></label><label>Descrição social<textarea name="social_description" rows="3" maxlength="500"><?=h((string)$seo['socialDescription'])?></textarea></label><label>Imagem de compartilhamento<input data-seo-social-image name="social_image" value="<?=h((string)$seo['socialImage'])?>" placeholder="/uploads/media/... ou https://..."></label></section>
<section class="site-settings-section"><header><div><h2>Indexação e URL canônica</h2><p>Controles técnicos para páginas que precisam divergir do comportamento padrão.</p></div></header><div class="form-grid two-columns"><label>Robôs<select name="robots"><?php foreach(['index,follow'=>'Indexar e seguir links','noindex,follow'=>'Não indexar; seguir links','index,nofollow'=>'Indexar; não seguir links','noindex,nofollow'=>'Não indexar nem seguir'] as $value=>$label):?><option value="<?=$value?>"<?=$seo['robots']===$value?' selected':''?>><?=h($label)?></option><?php endforeach;?></select></label><label>URL canônica<input name="canonical_url" value="<?=h((string)$seo['canonicalUrl'])?>" placeholder="Automática quando vazia"></label></div><p class="admin-muted">Se a URL canônica ficar vazia, o sistema usa automaticamente a URL pública desta página e deste idioma.</p></section><div class="site-savebar"><button class="admin-button" type="submit">Salvar SEO da página</button></div></form></div><?php endif;?></div>
<script src="<?=h(admin_asset_url('/assets/admin-site.js'))?>"></script>
<?php admin_shell_end();
