<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
security_headers();
require_admin();

$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}
$activityId=(int)$activity['id'];$locale=normalize_public_locale($_GET['lang']??$_POST['locale']??PUBLIC_LOCALE_PT_BR)??PUBLIC_LOCALE_PT_BR;
$site=cms_site_settings($db,$activityId,$locale);
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('cms-site',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}
    $links=[];foreach(($_POST['footer_links']??[]) as $row)if(is_array($row)&&trim((string)($row['label']??''))!==''&&trim((string)($row['url']??''))!=='')$links[]=['label'=>trim((string)$row['label']),'url'=>trim((string)$row['url'])];
    $settings=$site;
    $settings['siteName']=(string)($_POST['siteName']??'');
    $settings['wordmark']=(string)($_POST['wordmark']??'');
    $settings['header']=['sticky'=>!empty($_POST['header']['sticky']),'showLanguageSwitch'=>!empty($_POST['header']['showLanguageSwitch']),'showThemeSwitch'=>!empty($_POST['header']['showThemeSwitch']),'ctaLabel'=>$_POST['header']['ctaLabel']??'','ctaUrl'=>$_POST['header']['ctaUrl']??''];
    $settings['navigation']=['items'=>is_array($_POST['navigation_items']??null)?$_POST['navigation_items']:[]];
    $settings['footer']=['line1'=>$_POST['footer']['line1']??'','line2'=>$_POST['footer']['line2']??'','links'=>$links];
    $settings['seo']=$site['seo'];
    cms_settings_save($db,'site',$activityId,$locale,$settings);$_SESSION['admin_notice']='Navegação e identidade do site atualizadas.';header('Location: /admin/site.php?activity='.$activityId.'&lang='.rawurlencode(public_locale_query($locale)));exit;
}
$pages=cms_pages($db,$activityId,$locale,false);$pageById=[];foreach($pages as $page)$pageById[(int)$page['id']]=$page;$pageTree=cms_page_tree_rows($pages);
$navItems=$site['navigation']['items']??[];if(!$navItems){foreach($pages as $page)if(!empty($page['show_in_nav']))$navItems[]=['type'=>'page','pageId'=>(int)$page['id'],'label'=>'','newTab'=>false];}
$notice=$_SESSION['admin_notice']??null;unset($_SESSION['admin_notice']);
$pageData=[];foreach($pageTree as $treeRow){$treePage=$treeRow['page'];$parentId=(int)($treePage['parent_page_id']??0);$pageData[]=['id'=>(int)$treePage['id'],'title'=>(string)$treePage['title'],'depth'=>(int)$treeRow['depth'],'parentId'=>$parentId,'parentTitle'=>$parentId>0?(string)($pageById[$parentId]['title']??''):'' ];}
admin_shell_start('site','Navegação',$state,['/assets/admin-site.css']);?>
<?php if($notice):?><div class="admin-notice"><?=h((string)$notice)?></div><?php endif;?>
<section class="site-intro"><p class="site-intro-copy">Administre a identidade editorial e os elementos persistentes desta versão do site. O nome do curso é uma propriedade do curso; SEO tem uma área própria.</p><div class="site-intro-actions"><div class="site-language-switch" aria-label="Idioma do site"><a href="/admin/site.php?activity=<?=$activityId?>&lang=pt-br"<?=$locale===PUBLIC_LOCALE_PT_BR?' aria-current="page"':''?>>PT</a><a href="/admin/site.php?activity=<?=$activityId?>&lang=en"<?=$locale===PUBLIC_LOCALE_EN?' aria-current="page"':''?>>EN</a></div></div></section>
<nav class="site-section-nav" aria-label="Seções de navegação"><a href="#site-identity">Identidade</a><a href="#site-header">Cabeçalho</a><a href="#site-navigation">Menu</a><a href="#site-footer">Rodapé</a></nav>
<form method="post" data-site-settings-form><input type="hidden" name="_csrf" value="<?=h(csrf_token('cms-site'))?>"><input type="hidden" name="locale" value="<?=h($locale)?>"><div class="site-settings-stack">
<section class="site-settings-section" id="site-identity"><header><div><h2>Identidade do site</h2><p>Textos editoriais usados no cabeçalho e na identificação desta versão localizada.</p></div></header><div class="form-grid two-columns"><label>Nome do site<input name="siteName" value="<?=h((string)$site['siteName'])?>"><small class="admin-muted">Base editorial da versão <?=h(public_language_label($locale))?>.</small></label><label>Wordmark no cabeçalho<input name="wordmark" value="<?=h((string)$site['wordmark'])?>"><small class="admin-muted">Texto de marca mostrado no cabeçalho público.</small></label></div></section>
<section class="site-settings-section" id="site-header"><header><div><h2>Cabeçalho</h2><p>Comportamento e ação principal presentes nas páginas públicas.</p></div></header><div class="form-grid two-columns"><label class="check-row"><input type="checkbox" name="header[sticky]" value="1"<?=!empty($site['header']['sticky'])?' checked':''?>> Cabeçalho fixo</label><label class="check-row"><input type="checkbox" name="header[showLanguageSwitch]" value="1"<?=!empty($site['header']['showLanguageSwitch'])?' checked':''?>> Mostrar troca de idioma</label><label class="check-row"><input type="checkbox" name="header[showThemeSwitch]" value="1"<?=!empty($site['header']['showThemeSwitch'])?' checked':''?>> Mostrar controle claro/escuro</label></div><div class="form-grid two-columns admin-block-gap"><label>Texto da ação principal<input name="header[ctaLabel]" value="<?=h((string)$site['header']['ctaLabel'])?>" placeholder="Ex.: Inscreva-se"></label><label>Destino da ação<input name="header[ctaUrl]" value="<?=h((string)$site['header']['ctaUrl'])?>" placeholder="/inscricao/"></label></div></section>
<section class="site-settings-section" id="site-navigation"><header><div><h2>Menu principal</h2><p>Escolha presença, rótulo e ordem. A hierarquia vem de <strong>Páginas</strong>: uma subpágina aparece dentro da página superior e não pode virar um destino solto neste editor.</p></div><span class="admin-badge admin-badge--neutral"><?=count($navItems)?> itens</span></header><div class="site-nav-list" data-site-nav-builder data-pages="<?=h(json_encode($pageData,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?>"><?php foreach($navItems as $item):$type=($item['type']??'page')==='custom'?'custom':'page';$pageId=(int)($item['pageId']??0);$pageItem=$pageById[$pageId]??null;$parentId=(int)($pageItem['parent_page_id']??0);$parentTitle=$parentId>0?(string)($pageById[$parentId]['title']??''):'';?><div class="site-nav-row" draggable="true" data-nav-row><span class="site-nav-handle" aria-hidden="true">⋮⋮</span><input type="hidden" data-field="type" value="<?=h($type)?>"><?php if($type==='page'):?><label>Página<select data-field="pageId"><?php foreach($pageTree as $treeRow):$page=$treeRow['page'];$depth=(int)$treeRow['depth'];?><option value="<?=(int)$page['id']?>"<?=$pageId===(int)$page['id']?' selected':''?>><?=h(str_repeat('— ',$depth).(string)$page['title'])?></option><?php endforeach;?></select><small class="site-nav-parent-hint" data-nav-parent-hint<?=$parentTitle===''?' hidden':''?>><?=$parentTitle!==''?'Dentro de: '.h($parentTitle):''?></small></label><label>Rótulo<input data-field="label" value="<?=h((string)($item['label']??''))?>" placeholder="<?=h((string)($pageItem['nav_title']??'Usar título da página'))?>"></label><?php else:?><label>Rótulo<input data-field="label" value="<?=h((string)($item['label']??''))?>"></label><label>URL<input data-field="url" value="<?=h((string)($item['url']??''))?>"></label><?php endif;?><label class="check-row compact"><input type="checkbox" data-field="newTab" value="1"<?=!empty($item['newTab'])?' checked':''?>> Nova aba</label><button type="button" class="link-button danger" data-remove-nav>Remover</button></div><?php endforeach;?></div><div class="admin-inline-actions admin-block-gap"><button type="button" class="admin-button secondary" data-add-nav-page>+ Página</button><button type="button" class="admin-button secondary" data-add-nav-custom>+ Link externo</button></div></section>
<section class="site-settings-section" id="site-footer"><header><div><h2>Rodapé</h2><p>Linhas editoriais e links persistentes exibidos no fim das páginas.</p></div></header><div class="form-grid two-columns"><label>Linha principal<input name="footer[line1]" value="<?=h((string)$site['footer']['line1'])?>"></label><label>Linha secundária<input name="footer[line2]" value="<?=h((string)$site['footer']['line2'])?>"></label></div><div class="site-footer-links admin-block-gap" data-footer-links><?php foreach($site['footer']['links'] as $index=>$link):?><div class="site-footer-link" data-footer-link><label>Rótulo<input name="footer_links[<?=$index?>][label]" value="<?=h((string)$link['label'])?>"></label><label>URL<input name="footer_links[<?=$index?>][url]" value="<?=h((string)$link['url'])?>"></label><button type="button" class="link-button danger" data-remove-footer>Remover</button></div><?php endforeach;?></div><button type="button" class="link-button admin-block-gap" data-add-footer-link>+ Adicionar link</button></section>
</div><div class="site-savebar"><a class="link-button" href="<?=h(admin_public_activity_url($activity).'?lang='.public_locale_query($locale))?>" target="_blank" rel="noopener">Ver site ↗</a><button class="admin-button" type="submit">Salvar navegação</button></div></form>
<script src="<?=h(admin_asset_url('/assets/admin-site.js'))?>"></script>
<?php admin_shell_end();
