<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/admin_shell.php';security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];$locale=normalize_public_locale($_GET['lang']??$_POST['locale']??PUBLIC_LOCALE_PT_BR)??PUBLIC_LOCALE_PT_BR;
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('cms-site',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}
    $links=[];foreach(($_POST['footer_links']??[]) as $row)if(is_array($row)&&trim((string)($row['label']??''))!==''&&trim((string)($row['url']??''))!=='')$links[]=['label'=>trim((string)$row['label']),'url'=>trim((string)$row['url'])];
    $settings=[
        'siteName'=>$_POST['siteName']??'',
        'wordmark'=>$_POST['wordmark']??'',
        'header'=>['sticky'=>!empty($_POST['header']['sticky']),'showLanguageSwitch'=>!empty($_POST['header']['showLanguageSwitch']),'showThemeSwitch'=>!empty($_POST['header']['showThemeSwitch']),'ctaLabel'=>$_POST['header']['ctaLabel']??'','ctaUrl'=>$_POST['header']['ctaUrl']??''],
        'navigation'=>['items'=>is_array($_POST['navigation_items']??null)?$_POST['navigation_items']:[]],
        'footer'=>['line1'=>$_POST['footer']['line1']??'','line2'=>$_POST['footer']['line2']??'','links'=>$links],
        'seo'=>['defaultTitle'=>$_POST['seo']['defaultTitle']??'','defaultDescription'=>$_POST['seo']['defaultDescription']??'','socialImage'=>$_POST['seo']['socialImage']??'','favicon'=>$_POST['seo']['favicon']??''],
    ];
    cms_settings_save($db,'site',$activityId,$locale,$settings);$_SESSION['admin_notice']='Configurações do site atualizadas.';header('Location: /admin/site.php?activity='.$activityId.'&lang='.rawurlencode(public_locale_query($locale)));exit;
}
$site=cms_site_settings($db,$activityId,$locale);$pages=cms_pages($db,$activityId,$locale,false);$pageById=[];foreach($pages as $p)$pageById[(int)$p['id']]=$p;
$navItems=$site['navigation']['items']??[];if(!$navItems){foreach($pages as $p)if(!empty($p['show_in_nav']))$navItems[]=['type'=>'page','pageId'=>(int)$p['id'],'label'=>'','newTab'=>false];}
$notice=$_SESSION['admin_notice']??null;unset($_SESSION['admin_notice']);
admin_shell_start('site','Site e navegação',$state);?>
<?php if($notice):?><div class="admin-notice"><?=h((string)$notice)?></div><?php endif;?>
<section class="overview-hero"><div><p class="admin-kicker">Configuração global</p><h2>Identidade, navegação, header, footer e SEO</h2><p>Estas áreas são administráveis sem tocar no código. O menu pode misturar páginas do CMS e links externos, com ordem independente da lista de páginas.</p></div><div class="hero-actions"><a class="admin-button" href="/admin/site.php?activity=<?=$activityId?>&lang=pt-br"<?=$locale===PUBLIC_LOCALE_PT_BR?' aria-current="page"':''?>>PT</a><a class="admin-button" href="/admin/site.php?activity=<?=$activityId?>&lang=en"<?=$locale===PUBLIC_LOCALE_EN?' aria-current="page"':''?>>EN</a></div></section>
<form class="admin-editor-card cms-settings-form" method="post" id="site-settings-form"><input type="hidden" name="_csrf" value="<?=h(csrf_token('cms-site'))?>"><input type="hidden" name="locale" value="<?=h($locale)?>">
<section><p class="admin-kicker">Identidade</p><label>Nome do site<input name="siteName" value="<?=h($site['siteName'])?>"></label><label>Wordmark no header<input name="wordmark" value="<?=h($site['wordmark'])?>"></label></section>
<section><p class="admin-kicker">Header</p><label class="check-row"><input type="checkbox" name="header[sticky]" value="1"<?=!empty($site['header']['sticky'])?' checked':''?>> Header fixo</label><label class="check-row"><input type="checkbox" name="header[showLanguageSwitch]" value="1"<?=!empty($site['header']['showLanguageSwitch'])?' checked':''?>> Mostrar troca de idioma</label><label class="check-row"><input type="checkbox" name="header[showThemeSwitch]" value="1"<?=!empty($site['header']['showThemeSwitch'])?' checked':''?>> Mostrar controle claro/escuro</label><div class="form-grid two-columns"><label>CTA do header<input name="header[ctaLabel]" value="<?=h($site['header']['ctaLabel'])?>" placeholder="Ex.: Inscreva-se"></label><label>URL do CTA<input name="header[ctaUrl]" value="<?=h($site['header']['ctaUrl'])?>" placeholder="/inscricao/"></label></div></section>
<section><p class="admin-kicker">Navegação principal</p><p class="admin-muted">Arraste os itens para reorganizar. Links de página acompanham automaticamente a URL atual da página; você pode sobrescrever apenas o rótulo mostrado no menu.</p><div id="nav-builder" class="nav-builder"><?php foreach($navItems as $item):$type=($item['type']??'page')==='custom'?'custom':'page';$pageId=(int)($item['pageId']??0);$page=$pageById[$pageId]??null;?><div class="nav-builder-row" draggable="true" data-nav-row><span class="nav-drag" aria-hidden="true">⋮⋮</span><input type="hidden" data-field="type" value="<?=h($type)?>"><?php if($type==='page'):?><label>Página<select data-field="pageId"><?php foreach($pages as $p):?><option value="<?=(int)$p['id']?>"<?=$pageId===(int)$p['id']?' selected':''?>><?=h($p['title'])?></option><?php endforeach;?></select></label><label>Rótulo<input data-field="label" value="<?=h((string)($item['label']??''))?>" placeholder="<?=h($page['nav_title']??'')?>"></label><?php else:?><label>Rótulo<input data-field="label" value="<?=h((string)($item['label']??''))?>"></label><label>URL<input data-field="url" value="<?=h((string)($item['url']??''))?>"></label><?php endif;?><label class="check-row compact"><input type="checkbox" data-field="newTab" value="1"<?=!empty($item['newTab'])?' checked':''?>> Nova aba</label><button type="button" class="link-button danger" data-remove-nav>Remover</button></div><?php endforeach;?></div><div class="button-row"><button type="button" class="link-button" id="add-nav-page">+ Página</button><button type="button" class="link-button" id="add-nav-custom">+ Link externo</button></div></section>
<section><p class="admin-kicker">Footer</p><label>Linha principal<input name="footer[line1]" value="<?=h($site['footer']['line1'])?>"></label><label>Linha secundária<input name="footer[line2]" value="<?=h($site['footer']['line2'])?>"></label><div id="footer-links"><?php foreach($site['footer']['links'] as $i=>$link):?><div class="form-grid two-columns"><input name="footer_links[<?=$i?>][label]" value="<?=h((string)$link['label'])?>" placeholder="Rótulo"><input name="footer_links[<?=$i?>][url]" value="<?=h((string)$link['url'])?>" placeholder="URL"></div><?php endforeach;?></div><button type="button" class="link-button" id="add-footer-link">+ Link no footer</button></section>
<section><p class="admin-kicker">SEO global</p><label>Título padrão<input name="seo[defaultTitle]" value="<?=h($site['seo']['defaultTitle'])?>"></label><label>Descrição padrão<textarea name="seo[defaultDescription]" rows="3"><?=h($site['seo']['defaultDescription'])?></textarea></label><div class="form-grid two-columns"><label>Imagem social padrão<input name="seo[socialImage]" value="<?=h($site['seo']['socialImage'])?>" placeholder="/uploads/..."></label><label>Favicon<input name="seo[favicon]" value="<?=h($site['seo']['favicon'])?>" placeholder="/uploads/..."></label></div></section>
<div class="dialog-actions"><button class="admin-button" type="submit">Salvar configurações</button><a class="link-button" href="<?=h(admin_public_activity_url($activity).'?lang='.public_locale_query($locale))?>" target="_blank" rel="noopener">Ver site</a></div></form>
<script>
(()=>{const pages=<?=json_encode(array_map(fn($p)=>['id'=>(int)$p['id'],'title'=>$p['title'],'nav'=>$p['nav_title']],$pages),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>,host=document.querySelector('#nav-builder'),form=document.querySelector('#site-settings-form');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function pageOptions(){return pages.map(p=>`<option value="${p.id}">${esc(p.title)}</option>`).join('')}
function row(type){const d=document.createElement('div');d.className='nav-builder-row';d.draggable=true;d.dataset.navRow='';d.innerHTML=`<span class="nav-drag" aria-hidden="true">⋮⋮</span><input type="hidden" data-field="type" value="${type}">${type==='page'?`<label>Página<select data-field="pageId">${pageOptions()}</select></label><label>Rótulo<input data-field="label" placeholder="Rótulo da página"></label>`:`<label>Rótulo<input data-field="label"></label><label>URL<input data-field="url" placeholder="https://…"></label>`}<label class="check-row compact"><input type="checkbox" data-field="newTab" value="1"> Nova aba</label><button type="button" class="link-button danger" data-remove-nav>Remover</button>`;bind(d);return d}
let drag=null;function bind(r){r.querySelector('[data-remove-nav]').onclick=()=>r.remove();r.ondragstart=()=>{drag=r;r.classList.add('dragging')};r.ondragend=()=>{r.classList.remove('dragging');drag=null};r.ondragover=e=>{e.preventDefault();if(!drag||drag===r)return;const box=r.getBoundingClientRect(),after=e.clientY>box.top+box.height/2;after?r.after(drag):r.before(drag)}}
host.querySelectorAll('[data-nav-row]').forEach(bind);document.querySelector('#add-nav-page').onclick=()=>host.append(row('page'));document.querySelector('#add-nav-custom').onclick=()=>host.append(row('custom'));
form.addEventListener('submit',()=>{host.querySelectorAll('[data-generated-nav]').forEach(n=>n.remove());[...host.querySelectorAll('[data-nav-row]')].forEach((r,i)=>{r.querySelectorAll('[data-field]').forEach(el=>{const f=el.dataset.field,input=document.createElement('input');input.type='hidden';input.dataset.generatedNav='1';input.name=`navigation_items[${i}][${f}]`;input.value=el.type==='checkbox'?(el.checked?'1':''):el.value;form.append(input)})})});
document.querySelector('#add-footer-link')?.addEventListener('click',()=>{const h=document.querySelector('#footer-links'),i=h.children.length,r=document.createElement('div');r.className='form-grid two-columns';r.innerHTML=`<input name="footer_links[${i}][label]" placeholder="Rótulo"><input name="footer_links[${i}][url]" placeholder="URL">`;h.append(r)});
})();
</script>
<?php admin_shell_end();
