<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/admin_shell.php';security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];$locale=normalize_public_locale($_GET['lang']??$_POST['locale']??PUBLIC_LOCALE_PT_BR)??PUBLIC_LOCALE_PT_BR;
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('cms-site',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}
    $links=[];foreach(($_POST['footer_links']??[]) as $row)if(is_array($row)&&trim((string)($row['label']??''))!==''&&trim((string)($row['url']??''))!=='')$links[]=['label'=>trim((string)$row['label']),'url'=>trim((string)$row['url'])];
    $settings=[
        'siteName'=>$_POST['siteName']??'',
        'wordmark'=>$_POST['wordmark']??'',
        'header'=>['sticky'=>!empty($_POST['header']['sticky']),'showLanguageSwitch'=>!empty($_POST['header']['showLanguageSwitch']),'showThemeSwitch'=>!empty($_POST['header']['showThemeSwitch']),'ctaLabel'=>$_POST['header']['ctaLabel']??'','ctaUrl'=>$_POST['header']['ctaUrl']??''],
        'footer'=>['line1'=>$_POST['footer']['line1']??'','line2'=>$_POST['footer']['line2']??'','links'=>$links],
        'seo'=>['defaultTitle'=>$_POST['seo']['defaultTitle']??'','defaultDescription'=>$_POST['seo']['defaultDescription']??'','socialImage'=>$_POST['seo']['socialImage']??'','favicon'=>$_POST['seo']['favicon']??''],
    ];
    cms_settings_save($db,'site',$activityId,$locale,$settings);$_SESSION['admin_notice']='Configurações do site atualizadas.';header('Location: /admin/site.php?activity='.$activityId.'&lang='.rawurlencode(public_locale_query($locale)));exit;
}
$site=cms_site_settings($db,$activityId,$locale);$pages=cms_pages($db,$activityId,$locale,false);$notice=$_SESSION['admin_notice']??null;unset($_SESSION['admin_notice']);
admin_shell_start('site','Site e navegação',$state);?>
<?php if($notice):?><div class="admin-notice"><?=h((string)$notice)?></div><?php endif;?>
<section class="overview-hero"><div><p class="admin-kicker">Configuração global</p><h2>Identidade, header, footer e SEO</h2><p>O conteúdo destas áreas deixa de ficar fixo no código. A ordem e visibilidade das páginas continuam sendo administradas em Páginas.</p></div><div class="hero-actions"><a class="admin-button" href="/admin/site.php?activity=<?=$activityId?>&lang=pt-br">PT</a><a class="admin-button" href="/admin/site.php?activity=<?=$activityId?>&lang=en">EN</a></div></section>
<form class="admin-editor-card cms-settings-form" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('cms-site'))?>"><input type="hidden" name="locale" value="<?=h($locale)?>">
<section><p class="admin-kicker">Identidade</p><label>Nome do site<input name="siteName" value="<?=h($site['siteName'])?>"></label><label>Wordmark no header<input name="wordmark" value="<?=h($site['wordmark'])?>"></label></section>
<section><p class="admin-kicker">Header</p><label class="check-row"><input type="checkbox" name="header[sticky]" value="1"<?=!empty($site['header']['sticky'])?' checked':''?>> Header fixo</label><label class="check-row"><input type="checkbox" name="header[showLanguageSwitch]" value="1"<?=!empty($site['header']['showLanguageSwitch'])?' checked':''?>> Mostrar troca de idioma</label><label class="check-row"><input type="checkbox" name="header[showThemeSwitch]" value="1"<?=!empty($site['header']['showThemeSwitch'])?' checked':''?>> Mostrar controle claro/escuro</label><div class="form-grid two-columns"><label>CTA do header<input name="header[ctaLabel]" value="<?=h($site['header']['ctaLabel'])?>" placeholder="Ex.: Inscreva-se"></label><label>URL do CTA<input name="header[ctaUrl]" value="<?=h($site['header']['ctaUrl'])?>" placeholder="/inscricao/"></label></div></section>
<section><p class="admin-kicker">Footer</p><label>Linha principal<input name="footer[line1]" value="<?=h($site['footer']['line1'])?>"></label><label>Linha secundária<input name="footer[line2]" value="<?=h($site['footer']['line2'])?>"></label><div id="footer-links"><?php foreach($site['footer']['links'] as $i=>$link):?><div class="form-grid two-columns"><input name="footer_links[<?=$i?>][label]" value="<?=h((string)$link['label'])?>" placeholder="Rótulo"><input name="footer_links[<?=$i?>][url]" value="<?=h((string)$link['url'])?>" placeholder="URL"></div><?php endforeach;?></div><button type="button" class="link-button" id="add-footer-link">+ Link no footer</button></section>
<section><p class="admin-kicker">SEO global</p><label>Título padrão<input name="seo[defaultTitle]" value="<?=h($site['seo']['defaultTitle'])?>"></label><label>Descrição padrão<textarea name="seo[defaultDescription]" rows="3"><?=h($site['seo']['defaultDescription'])?></textarea></label><div class="form-grid two-columns"><label>Imagem social padrão<input name="seo[socialImage]" value="<?=h($site['seo']['socialImage'])?>" placeholder="/uploads/..."></label><label>Favicon<input name="seo[favicon]" value="<?=h($site['seo']['favicon'])?>" placeholder="/uploads/..."></label></div></section>
<section><p class="admin-kicker">Navegação</p><p>As páginas abaixo entram no menu quando “Exibir no menu” estiver ativo. A reorganização visual será feita diretamente no editor de páginas.</p><div class="overview-grid"><?php foreach($pages as $page):?><article class="overview-card"><p class="admin-kicker"><?=$page['show_in_nav']?'Visível':'Oculta'?></p><h2><?=h($page['nav_title'])?></h2><p><code><?=h(cms_page_url($activity,$page,$locale))?></code></p><a href="/editor/?page=<?=(int)$page['id']?>">Editar página</a></article><?php endforeach;?></div></section>
<div class="dialog-actions"><button class="admin-button" type="submit">Salvar configurações</button><a class="link-button" href="<?=h(admin_public_activity_url($activity).'?lang='.public_locale_query($locale))?>" target="_blank" rel="noopener">Ver site</a></div></form>
<script>document.querySelector('#add-footer-link')?.addEventListener('click',()=>{const host=document.querySelector('#footer-links'),i=host.children.length,row=document.createElement('div');row.className='form-grid two-columns';row.innerHTML=`<input name="footer_links[${i}][label]" placeholder="Rótulo"><input name="footer_links[${i}][url]" placeholder="URL">`;host.append(row)});</script>
<?php admin_shell_end();
