<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
security_headers();
require_admin();

$db=database();
$state=admin_activity_resolution($db);
$activity=$state['activity'];
if(!$activity){header('Location: /admin/activities.php');exit;}
$activityId=(int)$activity['id'];
student_account_reconcile_confirmed_registrations($db,$activityId);
course_default_cohort($db,$activityId,true);

$views=['overview','cohorts','students','tests','lessons'];
$view=(string)($_GET['view']??'overview');
if($view==='pages'){header('Location: /admin/pages.php?activity='.$activityId,true,303);exit;}
if(!in_array($view,$views,true))$view='overview';

function student_admin_url(int $activityId,string $view,array $extra=[]): string {
    return '/admin/student-area.php?'.http_build_query(['activity'=>$activityId,'view'=>$view]+$extra);
}
function student_admin_page_links(int $activityId,string $view,int $page,int $pages,array $extra=[]): string {
    if($pages<=1)return '';$out='<nav aria-label="Paginação">';
    for($i=max(1,$page-2);$i<=min($pages,$page+2);$i++)$out.='<a '.($i===$page?'aria-current="page" ':'').'href="'.h(student_admin_url($activityId,$view,$extra+['p'=>$i])).'">'.$i.'</a>';
    return $out.'</nav>';
}
function student_admin_datetime(?string $value): string {$value=trim((string)$value);if($value==='')return '—';$ts=strtotime($value);return $ts===false?$value:date('d/m/Y H:i',$ts);}
function student_admin_value(mixed $value): string {$value=trim((string)$value);return $value===''?'—':h($value);}
function student_admin_tabs(int $activityId,string $view): void {
    $items=['overview'=>'Visão geral','cohorts'=>'Turmas','students'=>'Alunos','tests'=>'Testes','lessons'=>'Aulas'];
    echo '<nav class="admin-subtabs" aria-label="Área do aluno">';foreach($items as $key=>$label)echo '<a href="'.h(student_admin_url($activityId,$key)).'"'.($view===$key?' aria-current="page"':'').'>'.h($label).'</a>';echo '</nav>';
}

if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('student-area',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}
    $action=(string)($_POST['action']??'');$returnView=(string)($_POST['return_view']??$view);if(!in_array($returnView,$views,true))$returnView='overview';$extra=[];
    try{
        if($action==='create_cohort'){$created=course_create_cohort($db,$activityId,(string)($_POST['title']??''),(string)($_POST['slug']??''),!empty($_POST['make_default']));$extra=['cohort'=>(int)$created['id']];}
        elseif($action==='update_cohort'){$cohortId=(int)($_POST['cohort_id']??0);course_update_cohort_details($db,$activityId,$cohortId,$_POST);$extra=['cohort'=>$cohortId];}
        elseif($action==='set_default_cohort')course_set_default_cohort($db,$activityId,(int)($_POST['cohort_id']??0));
        elseif($action==='set_cohort_status')course_set_cohort_status($db,$activityId,(int)($_POST['cohort_id']??0),(string)($_POST['status']??'active'));
        elseif($action==='add_lesson')course_add_lesson($db,$activityId,(string)($_POST['title']??''),(string)($_POST['lesson_key']??''));
        elseif($action==='set_release'){
            $mode=(string)($_POST['release_mode']??'blocked');$at=null;
            if($mode==='now')$at=(new DateTimeImmutable('now'))->format('Y-m-d\TH:i');
            elseif($mode==='scheduled'){$at=trim((string)($_POST['release_at']??''));if($at==='')throw new RuntimeException('Informe a data e a hora da liberação.');}
            elseif($mode!=='blocked')throw new RuntimeException('Modo de liberação inválido.');
            course_set_lesson_release_schedule($db,(int)($_POST['cohort_id']??0),(int)($_POST['lesson_id']??0),$at);
        }
        elseif($action==='assign_submission_cohort')student_account_assign_submission_cohort($db,(int)($_POST['submission_id']??0),$activityId,(int)($_POST['cohort_id']??0));
        elseif($action==='test_message'){$testId=(int)($_POST['test_id']??0);student_test_add_admin_message($db,$testId,$activityId,(string)($_POST['message']??''));$extra=['test'=>$testId];}
        elseif($action==='test_status'){$testId=(int)($_POST['test_id']??0);student_test_set_review_status($db,$testId,$activityId,(string)($_POST['status']??'submitted'));$extra=['test'=>$testId];}
        elseif($action==='reconcile')student_account_reconcile_confirmed_registrations($db,$activityId);
        else throw new RuntimeException('Ação inválida.');
        if(!isset($_SESSION['admin_notice']))$_SESSION['admin_notice']='Alteração salva.';
    }catch(Throwable $e){$_SESSION['admin_notice']='Não foi possível concluir: '.$e->getMessage();}
    header('Location: '.student_admin_url($activityId,$returnView,$extra),true,303);exit;
}

$cohorts=course_cohorts($db,$activityId);$lessons=course_lessons($db,$activityId);$notice=$_SESSION['admin_notice']??null;unset($_SESSION['admin_notice']);
$enrollmentCountQ=$db->prepare("SELECT COUNT(*) FROM course_enrollments e JOIN course_cohorts c ON c.id=e.cohort_id WHERE c.activity_id=? AND e.status='active'");$enrollmentCountQ->execute([$activityId]);$enrollmentCount=(int)$enrollmentCountQ->fetchColumn();
$releasedCountQ=$db->prepare("SELECT COUNT(*) FROM cohort_lesson_releases r JOIN course_cohorts c ON c.id=r.cohort_id WHERE c.activity_id=? AND r.released_at IS NOT NULL AND datetime(r.released_at)<=datetime('now')");$releasedCountQ->execute([$activityId]);$releasedCount=(int)$releasedCountQ->fetchColumn();
$testCountQ=$db->prepare("SELECT COUNT(*) FROM student_tests t JOIN course_cohorts c ON c.id=t.cohort_id WHERE c.activity_id=? AND t.status IN ('submitted','needs_revision')");$testCountQ->execute([$activityId]);$testAttentionCount=(int)$testCountQ->fetchColumn();

admin_shell_start('students','Área do aluno',$state);?>
<?php if($notice):?><div class="admin-notice"><?=h((string)$notice)?></div><?php endif;?>
<section class="overview-hero"><div><p class="admin-kicker">Inscrições</p><h2>Área do aluno</h2><p>Turmas, alunos, testes e liberações de aula. Estrutura, acesso e agendamento de páginas e seções pertencem ao editor do CMS.</p></div><div class="hero-actions"><form method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-area'))?>"><input type="hidden" name="action" value="reconcile"><input type="hidden" name="return_view" value="<?=h($view)?>"><button class="admin-button secondary" type="submit">Sincronizar inscrições</button></form></div></section>
<?php student_admin_tabs($activityId,$view);?>

<?php if($view==='overview'):?>
<div class="admin-stat-grid"><div class="admin-stat"><span>Turmas</span><strong><?=count($cohorts)?></strong></div><div class="admin-stat"><span>Alunos</span><strong><?=$enrollmentCount?></strong></div><div class="admin-stat"><span>Testes em andamento</span><strong><?=$testAttentionCount?></strong></div><div class="admin-stat"><span>Aulas liberadas</span><strong><?=$releasedCount?></strong></div></div>
<div class="overview-grid">
  <article class="overview-card"><h2>Turmas</h2><p>Nome, período, estado e comportamento de novas matrículas.</p><div class="admin-card-actions"><a href="<?=h(student_admin_url($activityId,'cohorts'))?>">Ver turmas</a></div></article>
  <article class="overview-card"><h2>Alunos</h2><p><?=$enrollmentCount?> matrícula(s) ativa(s). Importação histórica por CSV também fica aqui.</p><div class="admin-card-actions"><a href="<?=h(student_admin_url($activityId,'students'))?>">Ver alunos</a></div></article>
  <article class="overview-card"><h2>Testes</h2><p><?=$testAttentionCount?> teste(s) aguardando avaliação ou ajuste.</p><div class="admin-card-actions"><a href="<?=h(student_admin_url($activityId,'tests'))?>">Avaliar testes</a></div></article>
  <article class="overview-card"><h2>Aulas</h2><p><?=count($lessons)?> aula(s) cadastrada(s). A liberação pode ser imediata ou agendada para cada turma.</p><div class="admin-card-actions"><a href="<?=h(student_admin_url($activityId,'lessons'))?>">Gerenciar aulas</a></div></article>
</div>

<?php elseif($view==='cohorts'):
$selectedId=(int)($_GET['cohort']??0);$selected=$selectedId?course_cohort_by_id($db,$selectedId):null;if($selected&&(int)$selected['activity_id']!==$activityId)$selected=null;$showNew=!empty($_GET['new'])||!$cohorts;?>
<div class="admin-section-stack">
<section class="admin-card"><header><div><h2>Turmas</h2><p>Abra uma turma para alterar seus próprios dados. Matrículas e liberações permanecem vinculadas à mesma identidade.</p></div><div class="admin-card-actions"><a class="admin-button" href="<?=h(student_admin_url($activityId,'cohorts',['new'=>1]))?>">Nova turma</a></div></header><?php if(!$cohorts):?><div class="admin-empty">Nenhuma turma cadastrada.</div><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Turma</th><th>Período</th><th>Status</th><th>Padrão</th><th></th></tr></thead><tbody><?php foreach($cohorts as $cohort):?><tr><td><strong><?=h((string)$cohort['title'])?></strong><div class="muted"><?=h((string)$cohort['slug'])?></div></td><td><?=h((string)($cohort['starts_at']?:'—'))?> → <?=h((string)($cohort['ends_at']?:'—'))?></td><td><?=h((string)$cohort['status'])?></td><td><?=$cohort['is_registration_default']?'Sim':'—'?></td><td><a class="admin-button secondary" href="<?=h(student_admin_url($activityId,'cohorts',['cohort'=>(int)$cohort['id']]))?>">Abrir</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php if($selected):?><section class="admin-card"><header><div><p class="admin-kicker">Turma</p><h2><?=h((string)$selected['title'])?></h2><p>Editar a turma não recria sua identidade interna.</p></div></header><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-area'))?>"><input type="hidden" name="action" value="update_cohort"><input type="hidden" name="return_view" value="cohorts"><input type="hidden" name="cohort_id" value="<?=(int)$selected['id']?>"><label class="admin-form-span-2">Nome<input name="title" value="<?=h((string)$selected['title'])?>" required></label><label>Slug<input name="slug" value="<?=h((string)$selected['slug'])?>" required></label><label>Status<select name="status"><option value="active"<?=$selected['status']==='active'?' selected':''?>>Ativa</option><option value="closed"<?=$selected['status']==='closed'?' selected':''?>>Encerrada</option><option value="archived"<?=$selected['status']==='archived'?' selected':''?>>Arquivada</option></select></label><label>Início<input type="date" name="starts_at" value="<?=h((string)($selected['starts_at']??''))?>"></label><label>Fim<input type="date" name="ends_at" value="<?=h((string)($selected['ends_at']??''))?>"></label><label class="admin-form-span-2">Observações<textarea name="notes" rows="5" placeholder="Informações administrativas. Não são mostradas ao aluno."><?=h((string)($selected['notes']??''))?></textarea></label><label class="admin-form-span-2"><span>Turma padrão</span><span class="admin-inline-actions"><input type="checkbox" name="make_default" value="1"<?=$selected['is_registration_default']?' checked':''?>> receber novas matrículas confirmadas</span></label><div class="admin-form-actions"><button class="admin-button" type="submit">Salvar alterações</button></div></form></section><?php endif;?>
<?php if($showNew):?><section class="admin-card"><header><div><h2>Nova turma</h2></div></header><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-area'))?>"><input type="hidden" name="action" value="create_cohort"><input type="hidden" name="return_view" value="cohorts"><label class="admin-form-span-2">Nome<input name="title" required></label><label>Slug<input name="slug" placeholder="outubro-2026"></label><label><span>Turma padrão</span><span class="admin-inline-actions"><input type="checkbox" name="make_default" value="1"> receber novas matrículas</span></label><div class="admin-form-actions"><button class="admin-button" type="submit">Criar turma</button></div></form></section><?php endif;?></div>

<?php elseif($view==='students'):
$q=trim((string)($_GET['q']??''));$cohortFilter=(int)($_GET['cohort']??0);$p=max(1,(int)($_GET['p']??1));$perPage=50;$where=["c.activity_id=?","e.status='active'"];$params=[$activityId];if($cohortFilter>0){$where[]='c.id=?';$params[]=$cohortFilter;}if($q!==''){$where[]='(u.name LIKE ? OR u.email LIKE ? OR p.cpf_last4 LIKE ?)';$like='%'.$q.'%';array_push($params,$like,$like,$like);}$whereSql=implode(' AND ',$where);$count=$db->prepare("SELECT COUNT(*) FROM course_enrollments e JOIN student_users u ON u.id=e.student_id LEFT JOIN student_profiles p ON p.student_id=u.id JOIN course_cohorts c ON c.id=e.cohort_id WHERE $whereSql");$count->execute($params);$total=(int)$count->fetchColumn();$pagesCount=max(1,(int)ceil($total/$perPage));if($p>$pagesCount)$p=$pagesCount;$studentsQ=$db->prepare("SELECT u.id,u.name,u.email,u.activated_at,u.last_login_at,p.cpf_last4,e.status enrollment_status,c.title cohort_title,c.id cohort_id FROM course_enrollments e JOIN student_users u ON u.id=e.student_id LEFT JOIN student_profiles p ON p.student_id=u.id JOIN course_cohorts c ON c.id=e.cohort_id WHERE $whereSql ORDER BY u.name COLLATE NOCASE LIMIT ? OFFSET ?");$bind=1;foreach($params as $value)$studentsQ->bindValue($bind++,$value,is_int($value)?PDO::PARAM_INT:PDO::PARAM_STR);$studentsQ->bindValue($bind++,$perPage,PDO::PARAM_INT);$studentsQ->bindValue($bind,($p-1)*$perPage,PDO::PARAM_INT);$studentsQ->execute();$students=$studentsQ->fetchAll();$submissions=student_account_confirmed_submissions($db,$activityId);$showImport=!empty($_GET['import']);$batches=$showImport?student_import_batches($db,$activityId,25):[];$batchId=(int)($_GET['batch']??0);$batchRows=$showImport&&$batchId>0?student_import_batch_rows($db,$batchId,$activityId):[];?>
<div class="admin-section-stack">
<?php if($showImport):?><section class="admin-card"><header><div><p class="admin-kicker">Alunos</p><h2>Importar CSV</h2><p>Importe participantes de turmas anteriores diretamente para a turma escolhida.</p></div><div class="admin-card-actions"><a class="admin-button secondary" href="/assets/modelo-importacao-alunos.csv" download>Baixar modelo CSV</a><a class="admin-button secondary" href="<?=h(student_admin_url($activityId,'students'))?>">Voltar à lista</a></div></header><form class="admin-form-grid" method="post" action="/admin/student-import-csv.php?activity=<?=$activityId?>" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-area'))?>"><label>Turma de destino<select name="cohort_id" required><option value="">Escolha</option><?php foreach($cohorts as $cohort):if($cohort['status']==='archived')continue;?><option value="<?=(int)$cohort['id']?>"><?=h((string)$cohort['title'])?></option><?php endforeach;?></select></label><label class="admin-form-span-2">Arquivo CSV<input type="file" name="spreadsheet" accept=".csv,text/csv" required></label><div class="admin-form-span-2"><p><strong>Obrigatórias:</strong> Nome, E-mail e CPF. <strong>Opcionais:</strong> Telefone, Instagram, Endereço, Cidade/UF e CEP.</p><p class="muted">CSV · até 5 MB · até 2.000 alunos. Contas já existentes são reaproveitadas. O CPF não é armazenado no relatório.</p><p class="muted"><strong>Exemplo:</strong> <code>Maria da Silva;maria@email.com;12345678900;(24) 99999-9999;@maria;Rua Exemplo, 123;Petrópolis/RJ;25600-000</code></p></div><div class="admin-form-actions"><button class="admin-button" type="submit">Importar CSV</button></div></form></section>
<section class="admin-card"><header><div><h2>Importações recentes</h2></div></header><?php if(!$batches):?><div class="admin-empty">Nenhuma importação realizada.</div><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Arquivo</th><th>Turma</th><th>Resultado</th><th>Data</th><th></th></tr></thead><tbody><?php foreach($batches as $batch):?><tr><td><?=h((string)$batch['original_name'])?></td><td><?=h((string)$batch['cohort_title'])?></td><td><?=(int)$batch['imported_rows']?> novas · <?=(int)$batch['existing_rows']?> existentes · <?=(int)$batch['error_rows']?> erros</td><td class="muted"><?=h(student_admin_datetime((string)$batch['created_at']))?></td><td><a class="admin-button secondary" href="<?=h(student_admin_url($activityId,'students',['import'=>1,'batch'=>(int)$batch['id']]))?>">Ver relatório</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php if($batchId>0):?><section class="admin-card"><header><div><h2>Relatório da importação</h2><p>O relatório não armazena o CPF bruto da planilha.</p></div></header><?php if(!$batchRows):?><div class="admin-empty">Importação não encontrada neste site.</div><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Linha</th><th>Aluno</th><th>Resultado</th><th>Observação</th></tr></thead><tbody><?php foreach($batchRows as $row):?><tr><td><?=(int)$row['row_number']?></td><td><strong><?=h((string)$row['name'])?></strong><div class="muted"><?=h((string)$row['email'])?></div></td><td><?=h((string)$row['status'])?></td><td><?=h((string)($row['message']?:'—'))?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section><?php endif;?><?php endif;?>
<section class="admin-card"><header><div><h2>Alunos</h2><p><?=$total?> resultado(s). Cada linha representa uma matrícula ativa.</p></div><div class="admin-card-actions"><a class="admin-button" href="<?=h(student_admin_url($activityId,'students',['import'=>1]))?>">Importar CSV</a></div></header><form class="admin-data-toolbar" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><input type="hidden" name="view" value="students"><label class="grow">Buscar<input name="q" value="<?=h($q)?>" placeholder="Nome, e-mail ou final do CPF"></label><label>Turma<select name="cohort"><option value="0">Todas</option><?php foreach($cohorts as $cohort):?><option value="<?=(int)$cohort['id']?>"<?=$cohortFilter===(int)$cohort['id']?' selected':''?>><?=h((string)$cohort['title'])?></option><?php endforeach;?></select></label><button class="admin-button secondary" type="submit">Filtrar</button></form><?php if(!$students):?><div class="admin-empty">Nenhum aluno encontrado.</div><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Aluno</th><th>CPF</th><th>Turma</th><th>Conta</th><th>Último acesso</th></tr></thead><tbody><?php foreach($students as $studentRow):?><tr><td><strong><?=h((string)$studentRow['name'])?></strong><div class="muted"><?=h((string)$studentRow['email'])?></div></td><td><?=$studentRow['cpf_last4']?'***.'.h((string)$studentRow['cpf_last4']):'—'?></td><td><?=h((string)$studentRow['cohort_title'])?></td><td><?=$studentRow['activated_at']?'Ativa':'Primeiro acesso pendente'?></td><td class="muted"><?=h((string)($studentRow['last_login_at']?:'—'))?></td></tr><?php endforeach;?></tbody></table></div><div class="admin-pagination"><span>Página <?=$p?> de <?=$pagesCount?></span><?=student_admin_page_links($activityId,'students',$p,$pagesCount,['q'=>$q,'cohort'=>$cohortFilter])?></div><?php endif;?></section>
<section class="admin-card"><header><div><h2>Inscrições confirmadas</h2><p>Mova uma matrícula confirmada para outra turma sem recriar a conta.</p></div></header><?php if(!$submissions):?><div class="admin-empty">Nenhuma inscrição confirmada.</div><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Inscrição</th><th>Turma</th></tr></thead><tbody><?php foreach(array_slice($submissions,0,100) as $submission):$payload=json_decode((string)$submission['payload_json'],true)?:[];?><tr><td><strong><?=h((string)($payload['name']??'Sem nome'))?></strong><div class="muted"><?=h((string)($payload['email']??''))?></div></td><td><form class="admin-inline-actions" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-area'))?>"><input type="hidden" name="action" value="assign_submission_cohort"><input type="hidden" name="return_view" value="students"><input type="hidden" name="submission_id" value="<?=(int)$submission['id']?>"><select name="cohort_id"><?php foreach($cohorts as $cohort):?><option value="<?=(int)$cohort['id']?>"<?=isset($submission['cohort_id'])&&(int)$submission['cohort_id']===(int)$cohort['id']?' selected':''?>><?=h((string)$cohort['title'])?></option><?php endforeach;?></select><button class="admin-button secondary" type="submit">Salvar</button></form></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section></div>

<?php elseif($view==='tests'):
$cohortFilter=(int)($_GET['cohort']??0);$statusFilter=(string)($_GET['status']??'');$q=trim((string)($_GET['q']??''));$tests=student_tests_for_admin($db,$activityId,$cohortFilter,$statusFilter,$q);$testId=(int)($_GET['test']??0);$selectedTest=$testId>0?student_test_for_admin($db,$testId,$activityId):null;$media=$selectedTest?student_test_media($db,(int)$selectedTest['id']):[];$messages=$selectedTest?student_test_messages($db,(int)$selectedTest['id']):[];?>
<div class="admin-section-stack">
<section class="admin-card"><header><div><h2>Testes</h2><p>Fila de experimentações registradas pelos alunos. Ficha, imagens e conversa seguem a visibilidade escolhida pelo autor.</p></div></header><form class="admin-data-toolbar" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><input type="hidden" name="view" value="tests"><label class="grow">Buscar<input name="q" value="<?=h($q)?>" placeholder="Aluno, e-mail ou título do teste"></label><label>Turma<select name="cohort"><option value="0">Todas</option><?php foreach($cohorts as $cohort):?><option value="<?=(int)$cohort['id']?>"<?=$cohortFilter===(int)$cohort['id']?' selected':''?>><?=h((string)$cohort['title'])?></option><?php endforeach;?></select></label><label>Estado<select name="status"><option value="">Todos</option><?php foreach(['submitted'=>'Aguardando avaliação','needs_revision'=>'Ajustes solicitados','reviewed'=>'Revisado','draft'=>'Rascunho'] as $value=>$label):?><option value="<?=h($value)?>"<?=$statusFilter===$value?' selected':''?>><?=h($label)?></option><?php endforeach;?></select></label><button class="admin-button secondary" type="submit">Filtrar</button></form><?php if(!$tests):?><div class="admin-empty">Nenhum teste encontrado.</div><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Teste</th><th>Aluno</th><th>Turma</th><th>Visibilidade</th><th>Estado</th><th></th></tr></thead><tbody><?php foreach($tests as $test):?><tr><td><strong><?=h((string)$test['title'])?></strong><div class="muted"><?=h((string)($test['test_date']?:'sem data'))?></div></td><td><?=h((string)$test['student_name'])?><div class="muted"><?=h((string)$test['student_email'])?></div></td><td><?=h((string)$test['cohort_title'])?></td><td><?=h(student_test_visibility_label((string)($test['visibility']??'private')))?></td><td><?=h(student_test_status_label((string)$test['status']))?></td><td><a class="admin-button secondary" href="<?=h(student_admin_url($activityId,'tests',['test'=>(int)$test['id'],'cohort'=>$cohortFilter,'status'=>$statusFilter,'q'=>$q]))?>">Abrir</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php if($testId>0&&!$selectedTest):?><section class="admin-card"><div class="admin-empty">Teste não encontrado neste site.</div></section><?php endif;?>
<?php if($selectedTest):?><section class="admin-card"><header><div><p class="admin-kicker"><?=h((string)$selectedTest['cohort_title'])?> · <?=h((string)$selectedTest['student_name'])?></p><h2><?=h((string)$selectedTest['title'])?></h2><p><?=h(student_test_status_label((string)$selectedTest['status']))?> · <?=h(student_test_visibility_label((string)($selectedTest['visibility']??'private')))?> · atualizado <?=h(student_admin_datetime((string)$selectedTest['updated_at']))?></p></div></header><div class="admin-table-scroll"><table class="admin-data-table"><tbody><tr><th>Data</th><td><?=student_admin_value($selectedTest['test_date'])?></td><th>Filme</th><td><?=student_admin_value($selectedTest['film'])?></td></tr><tr><th>Lote</th><td><?=student_admin_value($selectedTest['lot'])?></td><th>EI / ISO</th><td><?=student_admin_value($selectedTest['iso_reference'])?></td></tr><tr><th>Diafragma</th><td><?=student_admin_value($selectedTest['aperture'])?></td><th>Tempo calculado</th><td><?=student_admin_value($selectedTest['calculated_time'])?></td></tr><tr><th>Reciprocidade</th><td><?=student_admin_value($selectedTest['reciprocity_time'])?></td><th>Luz</th><td><?=student_admin_value($selectedTest['light_condition'])?></td></tr><tr><th>Claras/sombras</th><td colspan="3"><?=student_admin_value($selectedTest['tonal_range'])?></td></tr><tr><th>Revelador</th><td><?=student_admin_value($selectedTest['developer'])?></td><th>Diluição</th><td><?=student_admin_value($selectedTest['dilution'])?></td></tr><tr><th>Temperatura</th><td><?=student_admin_value($selectedTest['temperature'])?></td><th>Tempo de revelação</th><td><?=student_admin_value($selectedTest['development_time'])?></td></tr><tr><th>Branqueador</th><td colspan="3"><?=student_admin_value($selectedTest['bleach']??'')?></td></tr><tr><th>Movimentação</th><td colspan="3"><?=student_admin_value($selectedTest['agitation'])?></td></tr><tr><th>Observações</th><td colspan="3"><?=nl2br(student_admin_value($selectedTest['notes']))?></td></tr></tbody></table></div><div class="admin-inline-actions admin-block-gap"><?php foreach(['needs_revision'=>'Solicitar ajustes','reviewed'=>'Marcar como revisado','submitted'=>'Voltar para avaliação'] as $status=>$label):?><form method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-area'))?>"><input type="hidden" name="action" value="test_status"><input type="hidden" name="return_view" value="tests"><input type="hidden" name="test_id" value="<?=(int)$selectedTest['id']?>"><input type="hidden" name="status" value="<?=h($status)?>"><button class="admin-button secondary" type="submit"><?=h($label)?></button></form><?php endforeach;?></div></section>
<section class="admin-card"><header><div><h2>Imagens</h2><p><?=$media?count($media).' arquivo(s) enviado(s).':'Nenhuma imagem enviada.'?></p></div></header><?php if($media):?><div class="admin-media-grid"><?php foreach($media as $item):$src='/admin/student-test-media.php?'.http_build_query(['activity'=>$activityId,'id'=>(int)$item['id']]);?><a href="<?=h($src)?>" target="_blank" rel="noopener"><img class="admin-media-grid-image" src="<?=h($src)?>" alt="<?=h((string)$item['original_name'])?>" loading="lazy"><span class="muted"><?=h((string)($item['phase']??'result'))?> · <?=h((string)$item['original_name'])?></span></a><?php endforeach;?></div><?php endif;?></section>
<section class="admin-card"><header><div><h2>Avaliação e dúvidas</h2><p>Quando o teste é compartilhado com turma ou curso, esta conversa faz parte do mesmo registro compartilhado. Outros alunos permanecem em modo somente leitura.</p></div></header><?php if(!$messages):?><div class="admin-empty">Ainda não há mensagens neste teste.</div><?php else:?><div class="admin-section-stack"><?php foreach($messages as $message):?><article><p class="admin-kicker"><?=$message['author_role']==='admin'?'João / avaliação':h((string)($message['student_name']?:$selectedTest['student_name']))?> · <?=h(student_admin_datetime((string)$message['created_at']))?></p><p><?=nl2br(h((string)$message['body']))?></p></article><?php endforeach;?></div><?php endif;?><form class="admin-form-grid admin-block-gap" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-area'))?>"><input type="hidden" name="action" value="test_message"><input type="hidden" name="return_view" value="tests"><input type="hidden" name="test_id" value="<?=(int)$selectedTest['id']?>"><label class="admin-form-span-2">Comentário para o aluno<textarea name="message" rows="6" required placeholder="Avaliação, orientação ou resposta à dúvida"></textarea></label><div class="admin-form-actions"><button class="admin-button" type="submit">Enviar comentário</button></div></form></section><?php endif;?></div>

<?php elseif($view==='lessons'):?>
<div class="admin-section-stack">
<?php foreach($cohorts as $cohort):$releaseRows=course_lesson_release_rows($db,(int)$cohort['id'],$activityId);?><section class="admin-card"><header><div><h2><?=h((string)$cohort['title'])?></h2><p>Aqui você controla somente quando cada aula fica disponível para esta turma. Quais seções pertencem à aula é configurado no editor da própria página.</p></div></header><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Aula</th><th>Identificador</th><th>Estado</th><th>Liberação</th></tr></thead><tbody><?php foreach($releaseRows as $lesson):$releaseState=course_lesson_release_state($lesson['released_at']??null);?><tr><td><?=h((string)$lesson['title'])?></td><td class="muted"><?=h((string)$lesson['lesson_key'])?></td><td><?php if($releaseState==='released'):?>Liberada<?php elseif($releaseState==='scheduled'):?>Agendada para <?=h(student_admin_datetime((string)$lesson['released_at']))?><?php else:?>Bloqueada<?php endif;?></td><td><form class="admin-inline-actions" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-area'))?>"><input type="hidden" name="action" value="set_release"><input type="hidden" name="return_view" value="lessons"><input type="hidden" name="cohort_id" value="<?=(int)$cohort['id']?>"><input type="hidden" name="lesson_id" value="<?=(int)$lesson['id']?>"><select name="release_mode" aria-label="Modo de liberação"><option value="blocked"<?=$releaseState==='blocked'?' selected':''?>>Bloqueada</option><option value="now"<?=$releaseState==='released'?' selected':''?>>Liberar agora</option><option value="scheduled"<?=$releaseState==='scheduled'?' selected':''?>>Agendar</option></select><input type="datetime-local" name="release_at" value="<?=h($releaseState==='scheduled'?cms_access_datetime_local_value((string)$lesson['released_at']):'')?>" aria-label="Data e hora da liberação"><button class="admin-button secondary" type="submit">Salvar</button></form></td></tr><?php endforeach;?></tbody></table></div></section><?php endforeach;?>
<section class="admin-card"><header><div><h2>Nova aula</h2><p>A aula é uma condição de autorização reutilizável pelas seções do CMS.</p></div></header><form class="admin-form-grid" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-area'))?>"><input type="hidden" name="action" value="add_lesson"><input type="hidden" name="return_view" value="lessons"><label class="admin-form-span-2">Nome<input name="title" required></label><label>Identificador<input name="lesson_key" placeholder="aula-4"></label><div class="admin-form-actions"><button class="admin-button" type="submit">Adicionar aula</button></div></form></section></div>
<?php endif;?>
<?php admin_shell_end();
