<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
require_once __DIR__.'/../app/student_auth.php';
security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activities=$state['activities'];$notice='';$error='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('students',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}
    $action=(string)($_POST['action']??'');
    try{
        if($action==='create'){
            student_create($db,(string)($_POST['username']??''),(string)($_POST['display_name']??''),(string)($_POST['email']??''),(string)($_POST['password']??''),(array)($_POST['activity_ids']??[]));
            $notice='Aluno criado. A senha informada é provisória e deverá ser trocada no primeiro acesso.';
        }elseif($action==='reset_password'){
            $id=(int)($_POST['student_id']??0);if(!student_by_id($db,$id))throw new RuntimeException('student_not_found');student_set_password($db,$id,(string)($_POST['password']??''),true);$notice='Senha provisória atualizada. Todas as sessões anteriores foram invalidadas.';
        }elseif($action==='toggle'){
            $id=(int)($_POST['student_id']??0);$student=student_by_id($db,$id)??throw new RuntimeException('student_not_found');$next=$student['status']==='active'?'disabled':'active';$db->prepare('UPDATE student_users SET status=?,session_version=session_version+1,updated_at=? WHERE id=?')->execute([$next,utc_now(),$id]);$notice=$next==='active'?'Acesso reativado.':'Acesso desativado e sessões invalidadas.';
        }elseif($action==='access'){
            $id=(int)($_POST['student_id']??0);if(!student_by_id($db,$id))throw new RuntimeException('student_not_found');$db->beginTransaction();try{student_replace_enrollments($db,$id,(array)($_POST['activity_ids']??[]));$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}$notice='Acessos atualizados.';
        }elseif($action==='profile'){
            $id=(int)($_POST['student_id']??0);$student=student_by_id($db,$id)??throw new RuntimeException('student_not_found');$name=trim((string)($_POST['display_name']??''));$email=strtolower(trim((string)($_POST['email']??'')));if($name==='')throw new RuntimeException('invalid_display_name');if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))throw new RuntimeException('invalid_email');$db->prepare('UPDATE student_users SET display_name=?,email=?,updated_at=? WHERE id=?')->execute([$name,$email,utc_now(),$id]);$notice='Dados atualizados.';
        }
    }catch(Throwable $e){$error=match($e->getMessage()){'password_too_short'=>'A senha provisória precisa ter pelo menos '.STUDENT_PASSWORD_MIN_LENGTH.' caracteres.','invalid_username'=>'Use um usuário com pelo menos 3 caracteres: letras, números, ponto, sublinhado, @, + ou hífen.','invalid_email'=>'E-mail inválido.','invalid_display_name'=>'Informe o nome do aluno.','student_not_found'=>'Aluno não encontrado.',default=>(str_contains(strtolower($e->getMessage()),'unique')?'Este usuário já existe.':'Não foi possível concluir a operação.')};}
}
$q=$db->query("SELECT u.*,COALESCE((SELECT group_concat(a.admin_name, ' · ') FROM student_enrollments e JOIN activities a ON a.id=e.activity_id WHERE e.user_id=u.id),'') AS access_names FROM student_users u ORDER BY u.status='active' DESC,u.display_name COLLATE NOCASE,u.id DESC");$students=$q->fetchAll();
$editId=(int)($_GET['edit']??0);$editing=$editId?student_by_id($db,$editId):null;$editingAccess=$editing?student_enrollment_ids($db,$editId):[];
admin_shell_start('students','Alunos',$state);?>
<?php if($notice):?><div class="admin-notice"><?=h($notice)?></div><?php endif;?><?php if($error):?><div class="admin-notice" style="border-color:#8b2c2c"><?=h($error)?></div><?php endif;?>
<section class="overview-hero"><div><h2>Área do aluno</h2><p>Contas individuais, senhas com hash seguro e acesso por curso. Desativar um aluno invalida imediatamente as sessões existentes.</p></div><div class="hero-actions"><button class="admin-button" type="button" data-dialog-open="new-student">Novo aluno</button><a class="admin-button admin-button-secondary" href="/admin/student-materials.php<?= $state['activity']?'?activity='.(int)$state['activity']['id']:'' ?>">Materiais</a></div></section>
<?php if(!$students):?><section class="admin-empty"><h2>Nenhum aluno</h2><p>Crie a primeira conta para liberar a área protegida.</p></section><?php else:?><section class="admin-list" aria-label="Alunos"><div class="admin-list-head"><div>Aluno</div><div>Acesso</div><div>Estado</div><div>Ações</div></div><?php foreach($students as $student):?><article class="admin-list-row"><div class="admin-list-title"><strong><?=h((string)$student['display_name'])?></strong><span><?=h((string)$student['username'])?><?=trim((string)$student['email'])!==''?' · '.h((string)$student['email']):''?></span></div><div class="admin-list-meta"><?=h((string)($student['access_names']?:'Nenhum curso'))?></div><div class="admin-list-status"><?= $student['status']==='active'?'Ativo':'Desativado' ?><?= (int)$student['must_change_password']===1?' · senha provisória':'' ?></div><div class="admin-list-actions"><a href="/admin/students.php?edit=<?=(int)$student['id']?>">Editar</a><details class="admin-list-menu"><summary aria-label="Mais ações">•••</summary><form method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('students'))?>"><input type="hidden" name="student_id" value="<?=(int)$student['id']?>"><button name="action" value="toggle"><?= $student['status']==='active'?'Desativar acesso':'Reativar acesso' ?></button></form></details></div></article><?php endforeach;?></section><?php endif;?>
<?php if($editing):?><section class="admin-card" style="margin-top:24px"><h2>Editar <?=h((string)$editing['display_name'])?></h2><div class="admin-grid two"><form method="post" class="admin-form"><input type="hidden" name="_csrf" value="<?=h(csrf_token('students'))?>"><input type="hidden" name="action" value="profile"><input type="hidden" name="student_id" value="<?=(int)$editing['id']?>"><label>Nome<input name="display_name" value="<?=h((string)$editing['display_name'])?>" required></label><label>E-mail<input type="email" name="email" value="<?=h((string)$editing['email'])?>"></label><button class="admin-button" type="submit">Salvar dados</button></form><form method="post" class="admin-form"><input type="hidden" name="_csrf" value="<?=h(csrf_token('students'))?>"><input type="hidden" name="action" value="reset_password"><input type="hidden" name="student_id" value="<?=(int)$editing['id']?>"><label>Nova senha provisória<input type="password" name="password" minlength="<?=STUDENT_PASSWORD_MIN_LENGTH?>" autocomplete="new-password" required></label><p class="admin-help">Mínimo de <?=STUDENT_PASSWORD_MIN_LENGTH?> caracteres. O aluno será obrigado a trocar a senha e todas as sessões atuais serão encerradas.</p><button class="admin-button" type="submit">Redefinir senha</button></form></div><form method="post" class="admin-form" style="margin-top:24px"><input type="hidden" name="_csrf" value="<?=h(csrf_token('students'))?>"><input type="hidden" name="action" value="access"><input type="hidden" name="student_id" value="<?=(int)$editing['id']?>"><fieldset><legend>Cursos liberados</legend><?php foreach($activities as $activity):?><label style="display:flex;gap:10px;align-items:center"><input type="checkbox" name="activity_ids[]" value="<?=(int)$activity['id']?>"<?=in_array((int)$activity['id'],$editingAccess,true)?' checked':''?>><?=h((string)$activity['admin_name'])?></label><?php endforeach;?></fieldset><button class="admin-button" type="submit">Salvar acessos</button></form></section><?php endif;?>
<dialog id="new-student" class="admin-dialog"><form method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('students'))?>"><input type="hidden" name="action" value="create"><header><h2>Novo aluno</h2></header><label>Nome<input name="display_name" required></label><label>Usuário<input name="username" autocomplete="off" required></label><label>E-mail <span>(opcional)</span><input type="email" name="email"></label><label>Senha provisória<input type="password" name="password" minlength="<?=STUDENT_PASSWORD_MIN_LENGTH?>" autocomplete="new-password" required></label><fieldset><legend>Cursos liberados</legend><?php foreach($activities as $activity):?><label style="display:flex;gap:10px;align-items:center"><input type="checkbox" name="activity_ids[]" value="<?=(int)$activity['id']?>"<?=($state['activity']&&(int)$state['activity']['id']===(int)$activity['id'])?' checked':''?>><?=h((string)$activity['admin_name'])?></label><?php endforeach;?></fieldset><div class="dialog-actions"><button type="button" data-dialog-close>Cancelar</button><button class="admin-button" type="submit">Criar aluno</button></div></form></dialog>
<?php admin_shell_end();
