<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];
$courses=course_list($db,$activityId);$courseId=max(0,(int)($_GET['course']??0));$cohortId=max(0,(int)($_GET['cohort']??0));$q=trim((string)($_GET['q']??''));$status=(string)($_GET['status']??'active');if(!in_array($status,['active','inactive','all'],true))$status='active';$page=max(1,(int)($_GET['page']??1));$pageSize=50;
$course=$courseId>0?course_by_id($db,$courseId):null;if($course&&(int)$course['activity_id']!==$activityId){$course=null;$courseId=0;}
$cohortOptions=[];$cohortArgs=[$activityId];$cohortSql="SELECT cc.id,cc.title,cc.course_id,c.title course_title FROM course_cohorts cc LEFT JOIN courses c ON c.id=cc.course_id WHERE cc.activity_id=?";if($courseId>0){$cohortSql.=' AND cc.course_id=?';$cohortArgs[]=$courseId;}$cohortSql.=" AND cc.status!='archived' ORDER BY c.title COLLATE NOCASE,cc.title COLLATE NOCASE";$stmt=$db->prepare($cohortSql);$stmt->execute($cohortArgs);$cohortOptions=$stmt->fetchAll();if($cohortId>0&&!array_filter($cohortOptions,static fn(array $row): bool=>(int)$row['id']===$cohortId))$cohortId=0;
function students_admin_url(int $activityId,int $courseId=0,int $cohortId=0,string $q='',string $status='active',int $page=1): string {$args=['activity'=>$activityId];if($courseId>0)$args['course']=$courseId;if($cohortId>0)$args['cohort']=$cohortId;if($q!=='')$args['q']=$q;if($status!=='active')$args['status']=$status;if($page>1)$args['page']=$page;return '/admin/students.php?'.http_build_query($args);}
$where=['cc.activity_id=?'];$args=[$activityId];if($courseId>0){$where[]='cc.course_id=?';$args[]=$courseId;}if($cohortId>0){$where[]='cc.id=?';$args[]=$cohortId;}if($status==='active')$where[]="e.status='active'";elseif($status==='inactive')$where[]="e.status!='active'";if($q!==''){$where[]='(u.name LIKE ? OR u.email LIKE ? OR p.cpf_last4 LIKE ? OR cc.title LIKE ? OR cr.title LIKE ?)';$like='%'.$q.'%';array_push($args,$like,$like,$like,$like,$like);}$whereSql=implode(' AND ',$where);
$count=$db->prepare("SELECT COUNT(*) FROM course_enrollments e JOIN course_cohorts cc ON cc.id=e.cohort_id JOIN student_users u ON u.id=e.student_id LEFT JOIN student_profiles p ON p.student_id=u.id LEFT JOIN courses cr ON cr.id=cc.course_id WHERE $whereSql");$count->execute($args);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$pageSize));if($page>$pages)$page=$pages;$offset=($page-1)*$pageSize;
$sql="SELECT e.id enrollment_id,e.status enrollment_status,e.confirmed_at,e.source_submission_id,u.id student_id,u.name,u.email,p.cpf_last4,cc.id cohort_id,cc.title cohort_title,cc.course_id,cr.title course_title FROM course_enrollments e JOIN course_cohorts cc ON cc.id=e.cohort_id JOIN student_users u ON u.id=e.student_id LEFT JOIN student_profiles p ON p.student_id=u.id LEFT JOIN courses cr ON cr.id=cc.course_id WHERE $whereSql ORDER BY u.name COLLATE NOCASE,u.id,e.id DESC LIMIT $pageSize OFFSET $offset";$stmt=$db->prepare($sql);$stmt->execute($args);$rows=$stmt->fetchAll();
admin_shell_start('students','Alunos',$state);?>
<form class="admin-data-toolbar" method="get"><input type="hidden" name="activity" value="<?=$activityId?>">
<label>Curso<select name="course"><option value="0">Todos os cursos</option><?php foreach($courses as $item):?><option value="<?=(int)$item['id']?>"<?=$courseId===(int)$item['id']?' selected':''?>><?=h((string)$item['title'])?></option><?php endforeach;?></select></label>
<label>Turma<select name="cohort"><option value="0">Todas as turmas</option><?php foreach($cohortOptions as $item):?><option value="<?=(int)$item['id']?>"<?=$cohortId===(int)$item['id']?' selected':''?>><?=h(($courseId>0?'':(string)$item['course_title'].' · ').(string)$item['title'])?></option><?php endforeach;?></select></label>
<label>Status<select name="status"><option value="active"<?=$status==='active'?' selected':''?>>Ativos</option><option value="inactive"<?=$status==='inactive'?' selected':''?>>Inativos</option><option value="all"<?=$status==='all'?' selected':''?>>Todos</option></select></label>
<label class="grow">Buscar<input name="q" value="<?=h($q)?>" placeholder="Nome, e-mail, CPF, turma ou curso"></label>
<div class="admin-inline-actions"><button class="admin-button secondary" type="submit">Aplicar</button><?php if($courseId>0||$cohortId>0||$q!==''||$status!=='active'):?><a class="admin-button secondary" href="<?=h(students_admin_url($activityId))?>">Limpar</a><?php endif;?></div></form>
<div class="admin-list-summary"><span><?php if($total>0):?>Mostrando <?=($offset+1)?>–<?=min($offset+$pageSize,$total)?> de <?=$total?> matrícula(s)<?php else:?>Nenhuma matrícula neste filtro<?php endif;?></span><span>Aluno é participação educacional; Pessoa é a identidade global.</span></div>
<?php if(!$rows):?><div class="admin-empty">Nenhum aluno encontrado.</div><?php else:?><div class="admin-table-scroll"><table class="admin-data-table"><thead><tr><th>Aluno</th><th>Curso</th><th>Turma</th><th>Status</th><th>Matrícula</th><th>Origem</th><th></th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><div class="admin-table-primary"><strong><?=h((string)$row['name'])?></strong><span><?=h((string)$row['email'])?><?=$row['cpf_last4']?' · ***.'.h((string)$row['cpf_last4']):''?></span></div></td><td><?php if((int)($row['course_id']??0)>0):?><a href="<?=h(admin_course_url($activityId,(int)$row['course_id']))?>"><?=h((string)$row['course_title'])?></a><?php else:?><span class="muted">Sem curso associado</span><?php endif;?></td><td><?=h((string)$row['cohort_title'])?></td><td><?=h((string)$row['enrollment_status'])?></td><td><?=h((string)($row['confirmed_at']?date('d/m/Y',strtotime((string)$row['confirmed_at'])):'—'))?></td><td><?=($row['source_submission_id']??null)?'Inscrição #'.(int)$row['source_submission_id']:'Importação/manual'?></td><td class="actions"><a class="admin-button secondary admin-table-action" href="/admin/people.php?<?=h(http_build_query(['activity'=>$activityId,'person'=>(int)$row['student_id']]))?>">Pessoa</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<div class="admin-pagination"><span>Página <?=$page?> de <?=$pages?></span><?php if($pages>1):?><nav aria-label="Paginação de alunos"><?php if($page>1):?><a href="<?=h(students_admin_url($activityId,$courseId,$cohortId,$q,$status,$page-1))?>">← Anterior</a><?php endif;?><?php if($page<$pages):?><a href="<?=h(students_admin_url($activityId,$courseId,$cohortId,$q,$status,$page+1))?>">Próxima →</a><?php endif;?></nav><?php endif;?></div>
<?php admin_shell_end();
