<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
require_once __DIR__.'/../app/student_auth.php';
security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];$notice='';$error='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('student-materials',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}
    try{$action=(string)($_POST['action']??'');if($action==='upload'){$file=$_FILES['html_file']??null;if(!is_array($file)||($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('upload_failed');if((int)($file['size']??0)>15*1024*1024)throw new RuntimeException('html_too_large');$tmp=(string)($file['tmp_name']??'');$html=is_file($tmp)?file_get_contents($tmp):false;if(!is_string($html))throw new RuntimeException('upload_failed');student_material_upsert($db,$activityId,(string)($_POST['title']??''),(string)($_POST['slug']??''),$html);$notice='Material protegido salvo. O conteúdo ficou armazenado no banco de dados, não no repositório público.';}elseif($action==='archive'){$id=(int)($_POST['material_id']??0);$db->prepare("UPDATE student_materials SET status='archived',updated_at=? WHERE id=? AND activity_id=?")->execute([utc_now(),$id,$activityId]);$notice='Material arquivado.';}}catch(Throwable $e){$error=match($e->getMessage()){'invalid_html'=>'Envie um arquivo HTML completo, com <html> e <body>.','unsafe_html'=>'O HTML contém scripts, iframes ou código ativo não permitido.','html_too_large'=>'O HTML excede 15 MB.','upload_failed'=>'Não foi possível ler o arquivo enviado.','invalid_title'=>'Informe o título do material.',default=>'Não foi possível salvar o material.'};}
}
$q=$db->prepare("SELECT * FROM student_materials WHERE activity_id=? AND status='active' ORDER BY title COLLATE NOCASE,id DESC");$q->execute([$activityId]);$materials=$q->fetchAll();
admin_shell_start('student-materials','Materiais dos alunos',$state);?>
<?php if($notice):?><div class="admin-notice"><?=h($notice)?></div><?php endif;?><?php if($error):?><div class="admin-notice" style="border-color:#8b2c2c"><?=h($error)?></div><?php endif;?>
<section class="overview-hero"><div><h2>Materiais protegidos</h2><p>O HTML é armazenado no SQLite persistente e só é entregue depois da autenticação e da verificação de acesso ao curso. O conteúdo não entra no GitHub nem no pacote público de atualização.</p></div><div class="hero-actions"><button class="admin-button" type="button" data-dialog-open="new-material">Enviar material</button><a class="admin-button admin-button-secondary" href="/admin/students.php">Alunos</a></div></section>
<div class="admin-notice" style="margin-bottom:20px"><strong>Para proteção completa:</strong> envie um HTML autocontido. Imagens privadas devem estar incorporadas no próprio arquivo (data URI). Referências a arquivos públicos continuam públicas mesmo quando a página está protegida.</div>
<?php if(!$materials):?><section class="admin-empty"><h2>Nenhum material</h2><p>Envie o primeiro HTML protegido para <?=h((string)$activity['admin_name'])?>.</p></section><?php else:?><section class="admin-list" aria-label="Materiais"><div class="admin-list-head"><div>Material</div><div>Endereço</div><div>Publicado</div><div>Ações</div></div><?php foreach($materials as $material):?><article class="admin-list-row"><div class="admin-list-title"><strong><?=h((string)$material['title'])?></strong><span>ID <?=h((string)$material['material_uuid'])?></span></div><div class="admin-list-meta"><?=h((string)$material['slug'])?></div><div class="admin-list-status"><?=h((string)$material['published_at'])?></div><div class="admin-list-actions"><a href="/aluno/material.php?m=<?=rawurlencode((string)$material['material_uuid'])?>" target="_blank" rel="noopener">Abrir ↗</a><details class="admin-list-menu"><summary aria-label="Mais ações">•••</summary><form method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-materials'))?>"><input type="hidden" name="material_id" value="<?=(int)$material['id']?>"><button class="danger" name="action" value="archive" data-confirm="Arquivar este material?">Arquivar</button></form></details></div></article><?php endforeach;?></section><?php endif;?>
<dialog id="new-material" class="admin-dialog"><form method="post" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-materials'))?>"><input type="hidden" name="action" value="upload"><header><h2>Enviar material protegido</h2></header><label>Título<input name="title" required></label><label>Identificador da página<input name="slug" placeholder="ex.: positivo-direto-filme-raio-x"></label><label>Arquivo HTML<input type="file" name="html_file" accept="text/html,.html,.htm" required></label><p class="admin-help">Se o identificador já existir neste curso, o conteúdo será substituído sem mudar o link do material.</p><div class="dialog-actions"><button type="button" data-dialog-close>Cancelar</button><button class="admin-button" type="submit">Salvar material</button></div></form></dialog>
<?php admin_shell_end();
