<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/admin_shell.php';security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('student-area',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}
    $action=(string)($_POST['action']??'');
    try{
        if($action==='create_student'){
            $result=student_admin_create_or_enroll($db,$activityId,(string)($_POST['name']??''),(string)($_POST['email']??''),trim((string)($_POST['password']??''))?:null);
            $message='Acesso criado/ativado.';if(is_string($result['generated_password']??null))$message.=' Senha temporária: '.$result['generated_password'].' — copie agora; ela não será exibida novamente.';$_SESSION['admin_notice']=$message;
        }elseif($action==='reset_password'){
            $password=student_admin_reset_password($db,(int)($_POST['student_id']??0));$_SESSION['admin_notice']='Nova senha temporária: '.$password.' — copie agora; ela não será exibida novamente.';
        }elseif($action==='set_enrollment'){
            student_admin_set_enrollment($db,(int)($_POST['student_id']??0),$activityId,(string)($_POST['status']??'disabled'));$_SESSION['admin_notice']='Acesso do aluno atualizado.';
        }elseif($action==='import_material'){
            $file=$_FILES['html_file']??null;if(!is_array($file)||($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new RuntimeException('Selecione um arquivo HTML.');if((int)($file['size']??0)>20*1024*1024)throw new RuntimeException('O HTML excede 20 MB.');
            $tmp=(string)($file['tmp_name']??'');$html=is_file($tmp)?file_get_contents($tmp):false;if(!is_string($html)||trim($html)==='')throw new RuntimeException('Não foi possível ler o HTML.');
            $material=student_material_upsert($db,$activityId,(string)($_POST['locale']??PUBLIC_LOCALE_PT_BR),(string)($_POST['title']??''),(string)($_POST['slug']??''),$html,(string)($_POST['status']??'active'));$_SESSION['admin_notice']='Material salvo: '.$material['title'].'.';
        }elseif($action==='set_material_status'){
            student_material_set_status($db,(int)($_POST['material_id']??0),$activityId,(string)($_POST['status']??'draft'));$_SESSION['admin_notice']='Estado do material atualizado.';
        }
    }catch(Throwable $e){$_SESSION['admin_notice']='Não foi possível concluir: '.$e->getMessage();}
    header('Location: /admin/student-area.php?activity='.$activityId,true,303);exit;
}
$students=student_admin_list($db,$activityId);$materials=student_materials($db,$activityId,null,false);$notice=$_SESSION['admin_notice']??null;unset($_SESSION['admin_notice']);
admin_shell_start('students','Área do aluno',$state);?>
<?php if($notice):?><div class="admin-notice"><?=h((string)$notice)?></div><?php endif;?>
<section class="overview-hero"><div><h2>Área do aluno</h2><p>Contas individuais e materiais que só podem ser lidos depois do login.</p></div></section>
<section class="admin-card" style="margin-top:24px"><h2>Novo acesso</h2><form method="post" style="display:grid;grid-template-columns:1fr 1fr;gap:16px"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-area'))?>"><input type="hidden" name="action" value="create_student"><label>Nome<input name="name" required></label><label>E-mail<input name="email" type="email" required></label><label>Senha inicial <span style="font-weight:400">(opcional)</span><input name="password" type="text" minlength="12" autocomplete="off"><small>Se ficar em branco, o sistema gera uma senha temporária.</small></label><div style="display:flex;align-items:end"><button class="admin-button" type="submit">Criar acesso</button></div></form></section>
<section class="admin-card" style="margin-top:24px"><h2>Alunos</h2><?php if(!$students):?><p>Nenhum aluno cadastrado neste site.</p><?php else:?><div class="admin-list"><div class="admin-list-head"><div>Aluno</div><div>Estado</div><div>Último acesso</div><div>Ações</div></div><?php foreach($students as $student):?><article class="admin-list-row"><div class="admin-list-title"><strong><?=h((string)$student['name'])?></strong><span><?=h((string)$student['email'])?></span></div><div class="admin-list-meta"><?=h((string)$student['enrollment_status'])?><?= (int)$student['must_change_password']===1?' · senha temporária':'' ?></div><div class="admin-list-meta"><?=h((string)($student['last_login_at']?:'—'))?></div><div class="admin-list-actions"><form method="post" style="display:inline"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-area'))?>"><input type="hidden" name="action" value="reset_password"><input type="hidden" name="student_id" value="<?=(int)$student['id']?>"><button type="submit">Redefinir senha</button></form><form method="post" style="display:inline"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-area'))?>"><input type="hidden" name="action" value="set_enrollment"><input type="hidden" name="student_id" value="<?=(int)$student['id']?>"><input type="hidden" name="status" value="<?=$student['enrollment_status']==='active'?'disabled':'active'?>"><button type="submit"><?=$student['enrollment_status']==='active'?'Desativar':'Ativar'?></button></form></div></article><?php endforeach;?></div><?php endif;?></section>
<section class="admin-card" style="margin-top:24px"><h2>Publicar material protegido</h2><p>O conteúdo não entra no repositório público: o arquivo é gravado no banco privado da instalação. Para preservar o visual e impedir URLs públicas de imagens, prefira um HTML autônomo com as imagens incorporadas no próprio arquivo.</p><form method="post" enctype="multipart/form-data" style="display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:16px"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-area'))?>"><input type="hidden" name="action" value="import_material"><label>Título<input name="title" required></label><label>Endereço<input name="slug" placeholder="positivo-direto-filme-raio-x" required></label><label>Idioma<select name="locale"><option value="pt-BR">Português (Brasil)</option><option value="en">English</option></select></label><label>Estado<select name="status"><option value="active">Disponível</option><option value="draft">Rascunho</option></select></label><label style="grid-column:1/-1">Arquivo HTML<input name="html_file" type="file" accept="text/html,.html,.htm" required></label><div style="grid-column:1/-1"><button class="admin-button" type="submit">Salvar material</button></div></form></section>
<section class="admin-card" style="margin-top:24px"><h2>Materiais</h2><?php if(!$materials):?><p>Nenhum material protegido cadastrado.</p><?php else:?><div class="admin-list"><div class="admin-list-head"><div>Material</div><div>Idioma</div><div>Estado</div><div>Ações</div></div><?php foreach($materials as $material):$url=student_url('/aluno/material.php',$activity,['slug'=>(string)$material['slug'],'lang'=>(string)$material['locale']]);?><article class="admin-list-row"><div class="admin-list-title"><strong><?=h((string)$material['title'])?></strong><span><?=h((string)$material['slug'])?></span></div><div class="admin-list-meta"><?=h(public_language_label((string)$material['locale']))?></div><div class="admin-list-meta"><?=h((string)$material['status'])?></div><div class="admin-list-actions"><a href="<?=h($url)?>" target="_blank" rel="noopener">Abrir ↗</a><form method="post" style="display:inline"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-area'))?>"><input type="hidden" name="action" value="set_material_status"><input type="hidden" name="material_id" value="<?=(int)$material['id']?>"><input type="hidden" name="status" value="<?=$material['status']==='active'?'draft':'active'?>"><button type="submit"><?=$material['status']==='active'?'Tornar rascunho':'Disponibilizar'?></button></form></div></article><?php endforeach;?></div><?php endif;?></section>
<?php admin_shell_end();
