<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/admin_shell.php';security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];
$courseId=max(0,(int)($_GET['course']??$_POST['course_id']??0));$course=$courseId>0?course_by_id($db,$courseId):null;if($course&&(int)$course['activity_id']!==$activityId){$course=null;$courseId=0;}
$cohortId=max(0,(int)($_GET['cohort']??$_POST['cohort_id']??0));$cohort=$course&&$cohortId>0?admin_course_cohort($db,$courseId,$cohortId,false):null;if($cohortId>0&&!$cohort){$cohortId=0;}
$q=trim((string)($_GET['q']??''));$studentId=max(0,(int)($_GET['student']??0));$showImport=!empty($_GET['import']);$batchId=max(0,(int)($_GET['batch']??0));$page=max(1,(int)($_GET['page']??1));$pageSize=50;
function students_workspace_url(int $activityId,int $courseId=0,int $cohortId=0,int $studentId=0,string $q='',int $page=1,array $extra=[]): string {$args=['activity'=>$activityId];if($courseId>0)$args['course']=$courseId;if($cohortId>0)$args['cohort']=$cohortId;if($studentId>0)$args['student']=$studentId;if($q!=='')$args['q']=$q;if($page>1)$args['page']=$page;$args+=$extra;return '/admin/students.php?'.http_build_query($args);}
function admin_students_datetime(?string $value): string {if(!$value)return '—';$ts=strtotime($value);return $ts===false?$value:date('d/m/Y · H:i',$ts);}
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
 if(!verify_csrf('students-admin',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}$action=(string)($_POST['action']??'');
 try{
  if(!$course)throw new RuntimeException('Escolha um curso.');
  if($action==='move_registration'){course_registration_assign_cohort($db,(int)($_POST['submission_id']??0),$courseId,(int)($_POST['target_cohort_id']??0));student_enrollment_reconcile_confirmed($db,$activityId);$_SESSION['admin_students_notice']='Aluno movido para a turma escolhida.';}
  elseif($action==='disable_enrollment'){$enrollmentId=(int)($_POST['enrollment_id']??0);$check=$db->prepare('SELECT e.id FROM course_enrollments e JOIN course_cohorts cc ON cc.id=e.cohort_id WHERE e.id=? AND cc.course_id=?');$check->execute([$enrollmentId,$courseId]);if(!$check->fetchColumn())throw new RuntimeException('Matrícula inválida.');$db->prepare("UPDATE course_enrollments SET status='disabled',updated_at=? WHERE id=?")->execute([utc_now(),$enrollmentId]);$_SESSION['admin_students_notice']='Participação desativada.';}
  else throw new RuntimeException('Ação inválida.');
 }catch(Throwable $e){$_SESSION['admin_students_notice']='Não foi possível concluir: '.$e->getMessage();}
 header('Location: '.students_workspace_url($activityId,$courseId,$cohortId,$studentId),true,303);exit;
}
$notice=(string)($_SESSION['admin_students_notice']??$_SESSION['admin_notice']??'');unset($_SESSION['admin_students_notice'],$_SESSION['admin_notice']);$tone=str_starts_with($notice,'Não foi possível')?'error':'success';
admin_shell_start('students',$course?($cohort?'Alunos · '.(string)$cohort['title']:'Alunos · '.(string)$course['title']):'Alunos',$state,['/assets/admin-operations.css','/assets/admin-teaching.css']);?>
<?php if($notice!==''):?><div class="admin-notice <?=h($tone)?>" role="<?=$tone==='error'?'alert':'status'?>"><?=h($notice)?></div><?php endif;?>
<?php if(!$course):
$where=[];$args=[];if($q!==''){$where[]='(u.name LIKE ? OR u.email LIKE ? OR p.cpf_last4 LIKE ?)';$like='%'.$q.'%';array_push($args,$like,$like,$like);}$whereSql=$where?' WHERE '.implode(' AND ',$where):'';$count=$db->prepare('SELECT COUNT(*) FROM student_users u LEFT JOIN student_profiles p ON p.student_id=u.id'.$whereSql);$count->execute($args);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$pageSize));if($page>$pages)$page=$pages;$offset=($page-1)*$pageSize;$stmt=$db->prepare("SELECT u.id,u.name,u.email,u.status,u.activated_at,u.last_login_at,p.cpf_last4,(SELECT COUNT(*) FROM course_enrollments e JOIN course_cohorts cc ON cc.id=e.cohort_id WHERE e.student_id=u.id AND e.status='active' AND cc.status!='archived') active_enrollments FROM student_users u LEFT JOIN student_profiles p ON p.student_id=u.id$whereSql ORDER BY u.name COLLATE NOCASE,u.id LIMIT $pageSize OFFSET $offset");$stmt->execute($args);$rows=$stmt->fetchAll();?>
<section class="admin-card admin-teaching-detail"><header><div><p class="admin-kicker">Ensino</p><h2>Alunos</h2><p>Busca global de pessoas com histórico de participação nos cursos.</p></div></header></section>
<form class="admin-data-toolbar" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><label class="grow">Buscar aluno<input name="q" value="<?=h($q)?>" placeholder="Nome, e-mail ou final do CPF"></label><button class="admin-button secondary" type="submit">Buscar</button></form>
<?php if(!$rows):?><div class="admin-empty">Nenhum aluno encontrado.</div><?php else:?><div class="admin-table-scroll" tabindex="0" aria-label="Lista global de alunos"><table class="admin-data-table"><thead><tr><th>Aluno</th><th>Conta</th><th>Participações ativas</th><th>Último acesso</th><th></th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><div class="admin-table-primary"><strong><?=h((string)$row['name'])?></strong><span><?=h((string)$row['email'])?><?=$row['cpf_last4']?' · ***.'.h((string)$row['cpf_last4']):''?></span></div></td><td><?=admin_badge(admin_status_label('account',(string)$row['status']),admin_status_tone('account',(string)$row['status']))?><?php if(!$row['activated_at']):?><div class="muted">Ativação pendente</div><?php endif;?></td><td class="admin-table-number"><?=(int)$row['active_enrollments']?></td><td><?=h(admin_students_datetime($row['last_login_at']??null))?></td><td class="actions"><a class="admin-button secondary admin-table-action" href="/admin/people.php?<?=h(http_build_query(['activity'=>$activityId,'person'=>(int)$row['id']]))?>#person-detail">Ver histórico</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<div class="admin-pagination"><span>Página <?=$page?> de <?=$pages?></span><?php if($pages>1):?><nav><?php if($page>1):?><a href="<?=h(students_workspace_url($activityId,0,0,0,$q,$page-1))?>">← Anterior</a><?php endif;?><?php if($page<$pages):?><a href="<?=h(students_workspace_url($activityId,0,0,0,$q,$page+1))?>">Próxima →</a><?php endif;?></nav><?php endif;?></div>
<?php else:
$cohortOptions=course_cohorts_for_course($db,$courseId);if($cohort)admin_cohort_context($course,$cohort,$activityId,'students','Participantes desta turma.');else admin_course_context($course,$activityId,'cohorts','Alunos matriculados nas turmas deste curso.');
$where=["cc.course_id=?","e.status='active'"];$args=[$courseId];if($cohortId>0){$where[]='cc.id=?';$args[]=$cohortId;}if($q!==''){$where[]='(u.name LIKE ? OR u.email LIKE ? OR p.cpf_last4 LIKE ?)';$like='%'.$q.'%';array_push($args,$like,$like,$like);}$whereSql=implode(' AND ',$where);$count=$db->prepare("SELECT COUNT(*) FROM course_enrollments e JOIN course_cohorts cc ON cc.id=e.cohort_id JOIN student_users u ON u.id=e.student_id LEFT JOIN student_profiles p ON p.student_id=u.id WHERE $whereSql");$count->execute($args);$total=(int)$count->fetchColumn();$pages=max(1,(int)ceil($total/$pageSize));if($page>$pages)$page=$pages;$offset=($page-1)*$pageSize;$stmt=$db->prepare("SELECT e.id enrollment_id,e.source_submission_id,e.confirmed_at,u.id student_id,u.name,u.email,u.status account_status,u.activated_at,u.last_login_at,p.cpf_last4,cc.id cohort_id,cc.title cohort_title FROM course_enrollments e JOIN course_cohorts cc ON cc.id=e.cohort_id JOIN student_users u ON u.id=e.student_id LEFT JOIN student_profiles p ON p.student_id=u.id WHERE $whereSql ORDER BY u.name COLLATE NOCASE,u.id LIMIT $pageSize OFFSET $offset");$stmt->execute($args);$rows=$stmt->fetchAll();$selected=null;if($studentId>0){foreach($rows as $candidate)if((int)$candidate['student_id']===$studentId){$selected=$candidate;break;}if(!$selected){$stmt=$db->prepare("SELECT e.id enrollment_id,e.source_submission_id,e.confirmed_at,u.id student_id,u.name,u.email,u.status account_status,u.activated_at,u.last_login_at,p.cpf_last4,cc.id cohort_id,cc.title cohort_title FROM course_enrollments e JOIN course_cohorts cc ON cc.id=e.cohort_id JOIN student_users u ON u.id=e.student_id LEFT JOIN student_profiles p ON p.student_id=u.id WHERE u.id=? AND cc.course_id=? AND e.status='active' ORDER BY e.confirmed_at DESC LIMIT 1");$stmt->execute([$studentId,$courseId]);$selected=$stmt->fetch()?:null;}}
$batches=$showImport?student_import_batches($db,$activityId,25):[];$batchRows=$showImport&&$batchId>0?student_import_batch_rows($db,$batchId,$activityId):[];?>
<section class="admin-card admin-teaching-detail"><header><div><h2><?=$cohort?h((string)$cohort['title']).' · Alunos':'Alunos do curso'?></h2><p><?=$total?> matrícula(s) ativa(s) no contexto atual.</p></div><?php if($cohort):?><a class="admin-button" href="<?=h(students_workspace_url($activityId,$courseId,$cohortId,0,'',1,['import'=>1]))?>">Importar CSV</a><?php endif;?></header></section>
<form class="admin-data-toolbar" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><input type="hidden" name="course" value="<?=$courseId?>"><?php if(!$cohort):?><label>Turma<select name="cohort"><option value="0">Todas as turmas</option><?php foreach($cohortOptions as $item):?><option value="<?=(int)$item['id']?>"><?=h((string)$item['title'])?></option><?php endforeach;?></select></label><?php else:?><input type="hidden" name="cohort" value="<?=$cohortId?>"><?php endif;?><label class="grow">Buscar aluno<input name="q" value="<?=h($q)?>" placeholder="Nome, e-mail ou final do CPF"></label><button class="admin-button secondary" type="submit">Filtrar</button></form>
<?php if($showImport&&$cohort):?><section class="admin-card"><header><div><h2>Importar alunos</h2><p>As pessoas importadas serão matriculadas diretamente em <?=h((string)$cohort['title'])?>.</p></div><div class="admin-card-actions"><a class="admin-button secondary" href="/assets/modelo-importacao-alunos.csv" download>Baixar modelo CSV</a><a class="admin-button secondary" href="<?=h(students_workspace_url($activityId,$courseId,$cohortId))?>">Fechar</a></div></header><form class="admin-form-grid" method="post" action="/admin/student-import-csv.php?<?=h(http_build_query(['activity'=>$activityId,'course'=>$courseId,'cohort'=>$cohortId]))?>" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="<?=h(csrf_token('students-import'))?>"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="cohort_id" value="<?=$cohortId?>"><label class="admin-form-span-2">Arquivo CSV<input type="file" name="spreadsheet" accept=".csv,text/csv" required></label><div class="admin-form-span-2"><p><strong>Obrigatórias:</strong> Nome, E-mail e CPF. Contas já existentes são reaproveitadas.</p></div><div class="admin-form-actions"><button class="admin-button" type="submit">Importar CSV</button></div></form></section>
<section class="admin-card"><header><div><h2>Importações recentes</h2></div></header><?php if(!$batches):?><div class="admin-empty">Nenhuma importação realizada.</div><?php else:?><div class="admin-table-scroll" tabindex="0"><table class="admin-data-table"><thead><tr><th>Arquivo</th><th>Turma</th><th>Resultado</th><th>Data</th><th></th></tr></thead><tbody><?php foreach($batches as $batch):if((int)($batch['cohort_id']??0)!==$cohortId)continue;?><tr><td><?=h((string)$batch['original_name'])?></td><td><?=h((string)$batch['cohort_title'])?></td><td><?=(int)$batch['imported_rows']?> novas · <?=(int)$batch['existing_rows']?> existentes · <?=(int)$batch['error_rows']?> erros</td><td><?=h(admin_students_datetime($batch['created_at']??null))?></td><td><a class="admin-button secondary admin-table-action" href="<?=h(students_workspace_url($activityId,$courseId,$cohortId,0,'',1,['import'=>1,'batch'=>(int)$batch['id']]))?>">Relatório</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section><?php if($batchId>0):?><section class="admin-card"><header><div><h2>Relatório da importação</h2></div></header><?php if(!$batchRows):?><div class="admin-empty">Importação não encontrada.</div><?php else:?><div class="admin-table-scroll" tabindex="0"><table class="admin-data-table"><thead><tr><th>Linha</th><th>Aluno</th><th>Resultado</th><th>Observação</th></tr></thead><tbody><?php foreach($batchRows as $row):?><tr><td><?=(int)$row['row_number']?></td><td><strong><?=h((string)$row['name'])?></strong><div class="muted"><?=h((string)$row['email'])?></div></td><td><?=h((string)$row['status'])?></td><td><?=h((string)($row['message']?:'—'))?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section><?php endif;?><?php endif;?>
<?php if($selected):?><section class="admin-card admin-operation-detail" id="student-detail"><header><div><p class="admin-kicker">Aluno</p><h2><?=h((string)$selected['name'])?></h2><div class="admin-detail-meta"><span><?=h((string)$selected['email'])?></span><?=admin_badge((string)$selected['account_status']==='active'?'Conta ativa':'Conta '.(string)$selected['account_status'],admin_status_tone('account',(string)$selected['account_status']))?><?php if(!$selected['activated_at']):?><?=admin_badge('Ativação pendente','attention')?><?php endif;?></div></div><div class="admin-card-actions"><a class="admin-button secondary" href="/admin/people.php?<?=h(http_build_query(['activity'=>$activityId,'person'=>$studentId]))?>#person-detail">Ver histórico completo</a></div></header><dl class="admin-teaching-summary"><div><dt>Turma</dt><dd><?=h((string)$selected['cohort_title'])?></dd></div><div><dt>Matrícula</dt><dd><?=h(admin_students_datetime($selected['confirmed_at']??null))?></dd></div><div><dt>Último acesso</dt><dd><?=h(admin_students_datetime($selected['last_login_at']??null))?></dd></div></dl><?php if((int)($selected['source_submission_id']??0)>0):?><section class="admin-operation-section"><h3>Alterar turma</h3><form class="admin-inline-actions" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('students-admin'))?>"><input type="hidden" name="action" value="move_registration"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="cohort_id" value="<?=$cohortId?>"><input type="hidden" name="student" value="<?=$studentId?>"><input type="hidden" name="submission_id" value="<?=(int)$selected['source_submission_id']?>"><select name="target_cohort_id" required><?php foreach($cohortOptions as $item):?><option value="<?=(int)$item['id']?>"<?=(int)$item['id']===(int)$selected['cohort_id']?' selected':''?>><?=h((string)$item['title'])?></option><?php endforeach;?></select><button class="admin-button secondary" type="submit">Mover aluno</button></form><p><a href="<?=h(registration_admin_url($activityId,$courseId,0,(int)$selected['source_submission_id']))?>">Ver inscrição original</a></p></section><?php endif;?><section class="admin-operation-danger"><h3>Desativar participação</h3><p>Interrompe o acesso por esta matrícula sem apagar o histórico da pessoa.</p><form method="post" data-confirm="Desativar esta participação?"><input type="hidden" name="_csrf" value="<?=h(csrf_token('students-admin'))?>"><input type="hidden" name="action" value="disable_enrollment"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="cohort_id" value="<?=$cohortId?>"><input type="hidden" name="student" value="<?=$studentId?>"><input type="hidden" name="enrollment_id" value="<?=(int)$selected['enrollment_id']?>"><button class="admin-button danger" type="submit">Desativar participação</button></form></section></section><?php endif;?>
<?php if(!$rows):?><div class="admin-empty">Nenhum aluno encontrado.</div><?php else:?><div class="admin-table-scroll" tabindex="0" aria-label="Alunos do curso"><table class="admin-data-table"><thead><tr><th>Aluno</th><?php if(!$cohort):?><th>Turma</th><?php endif;?><th>Conta</th><th>Último acesso</th><th></th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td><div class="admin-table-primary"><strong><?=h((string)$row['name'])?></strong><span><?=h((string)$row['email'])?><?=$row['cpf_last4']?' · ***.'.h((string)$row['cpf_last4']):''?></span></div></td><?php if(!$cohort):?><td><?=h((string)$row['cohort_title'])?></td><?php endif;?><td><?=$row['activated_at']?admin_badge('Ativa','good'):admin_badge('Ativação pendente','attention')?></td><td><?=h(admin_students_datetime($row['last_login_at']??null))?></td><td class="actions"><a class="admin-button secondary admin-table-action" href="<?=h(students_workspace_url($activityId,$courseId,$cohortId,(int)$row['student_id'],$q,$page))?>#student-detail">Abrir</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<div class="admin-pagination"><span>Página <?=$page?> de <?=$pages?></span><?php if($pages>1):?><nav><?php if($page>1):?><a href="<?=h(students_workspace_url($activityId,$courseId,$cohortId,0,$q,$page-1))?>">← Anterior</a><?php endif;?><?php if($page<$pages):?><a href="<?=h(students_workspace_url($activityId,$courseId,$cohortId,0,$q,$page+1))?>">Próxima →</a><?php endif;?></nav><?php endif;?></div>
<?php endif;?>
<?php admin_shell_end();