<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/admin_shell.php';security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];cms_forms_seed($db,$activityId);
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('cms-submissions',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}
    $id=(int)($_POST['submission_id']??0);$status=(string)($_POST['status']??'new');if(!in_array($status,['new','contacted','converted','archived'],true))$status='new';$notes=trim((string)($_POST['notes']??''));$q=$db->prepare('UPDATE cms_form_submissions SET status=?,notes=?,updated_at=? WHERE id=? AND activity_id=?');$q->execute([$status,$notes,utc_now(),$id,$activityId]);header('Location: /admin/submissions.php?activity='.$activityId.'&submission='.$id);exit;
}
$formFilter=(int)($_GET['form']??0);$statusFilter=(string)($_GET['status']??'');$sql='SELECT s.*,f.title form_title,f.form_key,f.locale form_locale,p.title page_title FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id LEFT JOIN cms_pages p ON p.id=s.page_id WHERE s.activity_id=?';$args=[$activityId];if($formFilter){$sql.=' AND s.form_id=?';$args[]=$formFilter;}if(in_array($statusFilter,['new','contacted','converted','archived'],true)){$sql.=' AND s.status=?';$args[]=$statusFilter;}$sql.=' ORDER BY s.created_at DESC LIMIT 250';$q=$db->prepare($sql);$q->execute($args);$rows=$q->fetchAll();$forms=cms_forms($db,$activityId);$selectedId=(int)($_GET['submission']??0);$selected=null;if($selectedId){$q=$db->prepare('SELECT s.*,f.title form_title,f.form_key FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE s.id=? AND s.activity_id=?');$q->execute([$selectedId,$activityId]);$selected=$q->fetch()?:null;}$legacyQ=$db->prepare('SELECT COUNT(*) FROM interest_submissions WHERE activity_id=?');$legacyQ->execute([$activityId]);$legacy=(int)$legacyQ->fetchColumn();
function cms_submission_summary(array $row): string {$payload=json_decode((string)$row['payload_json'],true)?:[];foreach(['name','email','phone'] as $key)if(!empty($payload[$key]))return is_array($payload[$key])?implode(', ',$payload[$key]):(string)$payload[$key];return 'Envio '.$row['submission_uuid'];}
admin_shell_start('responses','Respostas',$state);?>
<section class="overview-hero"><div><p class="admin-kicker">Formulários do site</p><h2><?=count($rows)?> respostas encontradas</h2><p>As respostas de inscrição e pesquisa ficam associadas ao formulário e à página em que foram enviadas.</p></div><div class="hero-actions"><a class="admin-button secondary" href="/admin/submissions-export.php?activity=<?=$activityId?><?=$formFilter?'&form='.$formFilter:''?>">Exportar CSV</a></div></section>
<form class="admin-filters" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><label>Formulário<select name="form"><option value="0">Todos</option><?php foreach($forms as $form):?><option value="<?=(int)$form['id']?>"<?=$formFilter===(int)$form['id']?' selected':''?>><?=h($form['title'].' · '.public_language_label($form['locale']))?></option><?php endforeach;?></select></label><label>Status<select name="status"><option value="">Todos</option><?php foreach(['new'=>'Novo','contacted'=>'Contatado','converted'=>'Convertido','archived'=>'Arquivado'] as $value=>$label):?><option value="<?=$value?>"<?=$statusFilter===$value?' selected':''?>><?=$label?></option><?php endforeach;?></select></label><button class="admin-button secondary" type="submit">Filtrar</button></form>
<div class="submissions-layout"><section class="submission-list"><?php if(!$rows):?><p class="admin-empty">Nenhuma resposta ainda.</p><?php endif;?><?php foreach($rows as $row):?><a class="submission-row<?=$selectedId===(int)$row['id']?' selected':''?>" href="/admin/submissions.php?activity=<?=$activityId?>&submission=<?=(int)$row['id']?><?=$formFilter?'&form='.$formFilter:''?>"><strong><?=h(cms_submission_summary($row))?></strong><span><?=h($row['form_title'])?> · <?=h(date('d/m/Y H:i',strtotime($row['created_at'])))?></span><small><?=h($row['status'])?></small></a><?php endforeach;?></section><?php if($selected):$payload=json_decode((string)$selected['payload_json'],true)?:[];$snapshot=json_decode((string)$selected['form_snapshot_json'],true)?:[];$labels=[];foreach($snapshot['fields']??[] as $field)$labels[$field['id']]=$field['label'];?><aside class="submission-detail"><p class="admin-kicker"><?=h($selected['form_title'])?></p><h2><?=h(cms_submission_summary($selected))?></h2><dl><?php foreach($payload as $key=>$value):?><dt><?=h($labels[$key]??$key)?></dt><dd><?=h(is_array($value)?implode(', ',$value):(string)$value)?></dd><?php endforeach;?></dl><form method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('cms-submissions'))?>"><input type="hidden" name="submission_id" value="<?=(int)$selected['id']?>"><label>Status<select name="status"><?php foreach(['new'=>'Novo','contacted'=>'Contatado','converted'=>'Convertido','archived'=>'Arquivado'] as $value=>$label):?><option value="<?=$value?>"<?=$selected['status']===$value?' selected':''?>><?=$label?></option><?php endforeach;?></select></label><label>Notas<textarea name="notes" rows="5"><?=h($selected['notes'])?></textarea></label><button class="admin-button" type="submit">Salvar acompanhamento</button></form></aside><?php endif;?></div>
<?php if($legacy):?><p class="legacy-note">Existem <?= $legacy ?> respostas do formulário anterior preservadas. <a href="/admin/interests.php?activity=<?=$activityId?>">Abrir respostas legadas</a>.</p><?php endif;?>
<?php admin_shell_end();
