<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
require __DIR__.'/../app/admin_shell.php';
security_headers();
require_admin();

function response_payload(array $row): array {return json_decode((string)($row['payload_json']??''),true)?:[];}
function response_snapshot(array $row): array {return json_decode((string)($row['form_snapshot_json']??''),true)?:[];}
function response_fields(array $row): array {$map=[];foreach(response_snapshot($row)['fields']??[] as $field)if(is_array($field)&&isset($field['id']))$map[(string)$field['id']]=$field;return $map;}
function response_name(array $row): string {$payload=response_payload($row);foreach(['name','full_name','email','phone'] as $key){$value=trim((string)($payload[$key]??''));if($value!=='')return $value;}return 'Resposta '.substr((string)$row['submission_uuid'],0,8);}
function response_secondary(array $row): string {$payload=response_payload($row);foreach(['email','phone','city_state','city'] as $key){$value=trim((string)($payload[$key]??''));if($value!=='')return $value;}return (string)$row['form_title'];}
function response_value_label(array $field,mixed $value): string {if(is_array($value))return implode(', ',array_map(fn($item)=>response_value_label($field,(string)$item),$value));$raw=(string)$value;foreach($field['options']??[] as $option)if(is_array($option)&&(string)($option['value']??'')===$raw)return (string)($option['label']??$raw);return $raw;}
function response_status_label(string $status): string {return match($status){'contacted'=>'Em contato','converted'=>'Concluída','archived'=>'Arquivada',default=>'Nova'};}
function response_list_url(int $activityId,int $id=0,string $status='',int $form=0,int $page=1): string {$args=['activity'=>$activityId];if($id)$args['submission']=$id;if($status!=='')$args['status']=$status;if($form)$args['form']=$form;if($page>1)$args['page']=$page;return '/admin/submissions.php?'.http_build_query($args);}

$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];cms_forms_seed($db,$activityId);
$formFilter=(int)($_GET['form']??$_POST['filter_form']??0);$statusFilter=(string)($_GET['status']??$_POST['filter_status']??'');$page=max(1,(int)($_GET['page']??$_POST['filter_page']??1));$pageSize=50;
if(!in_array($statusFilter,['new','contacted','converted','archived'],true))$statusFilter='';

if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('cms-submissions',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}
    $id=(int)($_POST['submission_id']??0);
    $q=$db->prepare("SELECT s.*,f.form_key,f.purpose FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE s.id=? AND s.activity_id=? AND COALESCE(f.purpose,'common')!='enrollment'");$q->execute([$id,$activityId]);$row=$q->fetch()?:null;
    if(!$row){http_response_code(404);exit('Response not found');}
    $allowed=['new','contacted','converted','archived'];$status=(string)($_POST['status']??'new');if(!in_array($status,$allowed,true))$status='new';$notes=trim((string)($_POST['notes']??''));$db->prepare('UPDATE cms_form_submissions SET status=?,notes=?,updated_at=? WHERE id=? AND activity_id=?')->execute([$status,$notes,utc_now(),$id,$activityId]);
    $_SESSION['admin_submissions_notice']='Resposta atualizada.';
    header('Location: '.response_list_url($activityId,$id,$statusFilter,$formFilter,$page));exit;
}

$formsQ=$db->prepare("SELECT * FROM cms_forms WHERE activity_id=? AND status!='archived' AND COALESCE(purpose,'common')!='enrollment' ORDER BY locale,title,id");$formsQ->execute([$activityId]);$forms=$formsQ->fetchAll();
$allowedFormIds=array_fill_keys(array_map(static fn(array $form): int=>(int)$form['id'],$forms),true);if($formFilter&&!isset($allowedFormIds[$formFilter]))$formFilter=0;
$where=["s.activity_id=?","COALESCE(f.purpose,'common')!='enrollment'"];$args=[$activityId];if($formFilter){$where[]='s.form_id=?';$args[]=$formFilter;}if($statusFilter!==''){$where[]='s.status=?';$args[]=$statusFilter;}$whereSql=implode(' AND ',$where);
$countQ=$db->prepare("SELECT COUNT(*) FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE {$whereSql}");$countQ->execute($args);$total=(int)$countQ->fetchColumn();$totalPages=max(1,(int)ceil($total/$pageSize));if($page>$totalPages)$page=$totalPages;$offset=($page-1)*$pageSize;
$sql="SELECT s.*,f.title form_title,f.form_key,f.purpose,f.locale form_locale FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE {$whereSql} ORDER BY CASE s.status WHEN 'new' THEN 0 WHEN 'contacted' THEN 1 WHEN 'converted' THEN 2 ELSE 3 END,s.created_at DESC LIMIT {$pageSize} OFFSET {$offset}";$q=$db->prepare($sql);$q->execute($args);$rows=$q->fetchAll();
$selectedId=(int)($_GET['submission']??0);if(!$selectedId&&$rows)$selectedId=(int)$rows[0]['id'];$selected=null;if($selectedId){$q=$db->prepare("SELECT s.*,f.title form_title,f.form_key,f.purpose,f.locale form_locale FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE s.id=? AND s.activity_id=? AND COALESCE(f.purpose,'common')!='enrollment'");$q->execute([$selectedId,$activityId]);$selected=$q->fetch()?:null;}
$countStatusQ=$db->prepare("SELECT s.status,COUNT(*) n FROM cms_form_submissions s JOIN cms_forms f ON f.id=s.form_id WHERE s.activity_id=? AND COALESCE(f.purpose,'common')!='enrollment' GROUP BY s.status");$countStatusQ->execute([$activityId]);$counts=['new'=>0,'contacted'=>0,'converted'=>0,'archived'=>0];foreach($countStatusQ->fetchAll() as $row)if(isset($counts[$row['status']]))$counts[$row['status']]=(int)$row['n'];
$notice=(string)($_SESSION['admin_submissions_notice']??'');unset($_SESSION['admin_submissions_notice']);

admin_shell_start('responses','Outras respostas',$state,['/assets/admin-inbox.css','/assets/admin-site.css']);?>
<?php if($notice!==''):?><div class="admin-notice"><?=h($notice)?></div><?php endif;?>
<section class="site-intro"><p class="site-intro-copy">Respostas de pesquisas, interesse e formulários comuns. Inscrições que geram matrícula são administradas exclusivamente em Operação → Inscrições.</p><div class="site-intro-actions"><a class="link-button" href="/admin/forms.php?activity=<?=$activityId?>">Editar formulários</a><a class="admin-button secondary" href="/admin/submissions-export.php?activity=<?=$activityId?><?=$formFilter?'&form='.$formFilter:''?>">Exportar CSV</a></div></section>
<nav class="inbox-status-tabs" aria-label="Status das respostas"><a href="<?=h(response_list_url($activityId,0,'',$formFilter))?>"<?=$statusFilter===''?' aria-current="page"':''?>>Todas <span><?=array_sum($counts)?></span></a><?php foreach(['new'=>'Novas','contacted'=>'Em contato','converted'=>'Concluídas','archived'=>'Arquivadas'] as $value=>$label):?><a href="<?=h(response_list_url($activityId,0,$value,$formFilter))?>"<?=$statusFilter===$value?' aria-current="page"':''?>><?=h($label)?> <span><?=$counts[$value]?></span></a><?php endforeach;?></nav>
<section class="inbox-toolbar"><div class="inbox-toolbar-summary"><strong><?=$total?> <?=($total===1?'resposta':'respostas')?></strong><span>· página <?=$page?> de <?=$totalPages?></span></div><div class="inbox-toolbar-controls"><?php if(count($forms)>1):?><form class="inbox-form-filter" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><input type="hidden" name="status" value="<?=h($statusFilter)?>"><label><span>Formulário</span><select name="form" onchange="this.form.submit()"><option value="0">Todos</option><?php foreach($forms as $form):?><option value="<?=(int)$form['id']?>"<?=$formFilter===(int)$form['id']?' selected':''?>><?=h($form['title'].' · '.public_language_label($form['locale']))?></option><?php endforeach;?></select></label></form><?php endif;?></div></section>
<div class="submissions-layout inbox-layout"><section class="submission-list inbox-list" aria-label="Lista de respostas"><?php if(!$rows):?><div class="site-empty-inline">Nenhuma resposta corresponde aos filtros atuais.</div><?php endif;?><?php foreach($rows as $row):?><a class="submission-row<?=$selectedId===(int)$row['id']?' selected':''?><?=$row['status']==='new'?' is-new':''?>" href="<?=h(response_list_url($activityId,(int)$row['id'],$statusFilter,$formFilter,$page))?>"><div class="submission-row-main"><strong><?=h(response_name($row))?></strong><span><?=h(response_secondary($row))?></span></div><div class="submission-row-meta"><time><?=h(date('d/m · H:i',strtotime($row['created_at'])))?></time><small data-status="<?=h((string)$row['status'])?>"><?=h(response_status_label((string)$row['status']))?></small></div></a><?php endforeach;?></section>
<?php if($selected):$payload=response_payload($selected);$fields=response_fields($selected);?><aside class="submission-detail inbox-detail"><header class="inbox-detail-header"><div><p><?=h((string)$selected['form_title'])?> · <?=h(public_language_label((string)$selected['form_locale']))?></p><h2><?=h(response_name($selected))?></h2><span><?=h(date('d/m/Y · H:i',strtotime($selected['created_at'])))?></span></div></header><dl class="inbox-fields"><?php foreach($payload as $key=>$value):?><div><dt><?=h((string)($fields[$key]['label']??$key))?></dt><dd><?=h(response_value_label($fields[$key]??[],$value))?></dd></div><?php endforeach;?></dl><form method="post" class="inbox-followup"><input type="hidden" name="_csrf" value="<?=h(csrf_token('cms-submissions'))?>"><input type="hidden" name="submission_id" value="<?=(int)$selected['id']?>"><input type="hidden" name="filter_status" value="<?=h($statusFilter)?>"><input type="hidden" name="filter_form" value="<?=$formFilter?>"><input type="hidden" name="filter_page" value="<?=$page?>"><label>Notas<textarea name="notes" rows="4"><?=h((string)$selected['notes'])?></textarea></label><div class="inbox-status-actions"><?php foreach(['new'=>'Nova','contacted'=>'Em contato','converted'=>'Concluída','archived'=>'Arquivada'] as $value=>$label):?><button type="submit" name="status" value="<?=$value?>"<?=$selected['status']===$value?' aria-current="true"':''?>><?=h($label)?></button><?php endforeach;?></div></form></aside><?php endif;?></div>
<?php if($totalPages>1):?><div class="admin-pagination admin-block-gap"><span>Exibindo <?=min($total,$offset+1)?>–<?=min($total,$offset+$pageSize)?> de <?=$total?></span><nav aria-label="Paginação das respostas"><?php for($p=max(1,$page-2);$p<=min($totalPages,$page+2);$p++):?><a href="<?=h(response_list_url($activityId,0,$statusFilter,$formFilter,$p))?>"<?=$p===$page?' aria-current="page"':''?>><?=$p?></a><?php endfor;?></nav></div><?php endif;?>
<?php admin_shell_end();
