<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';require __DIR__.'/../app/admin_shell.php';security_headers();require_admin();
$db=database();$state=admin_activity_resolution($db);$activity=$state['activity'];if(!$activity){header('Location: /admin/activities.php');exit;}$activityId=(int)$activity['id'];
$courseId=max(0,(int)($_GET['course']??$_POST['course_id']??0));$course=$courseId>0?course_by_id($db,$courseId):null;if(!$course||(int)$course['activity_id']!==$activityId){header('Location: /admin/courses.php?activity='.$activityId,true,302);exit;}
$cohortId=max(0,(int)($_GET['cohort']??$_POST['cohort_id']??0));$cohort=$cohortId>0?admin_course_cohort($db,$courseId,$cohortId,false):null;if($cohortId>0&&!$cohort)$cohortId=0;
$status=(string)($_GET['status']??'');if(!in_array($status,['','submitted','needs_revision','reviewed','draft'],true))$status='';$q=trim((string)($_GET['q']??''));$testId=max(0,(int)($_GET['test']??$_POST['test_id']??0));
function admin_tests_url(int $activityId,int $courseId,int $cohortId=0,int $testId=0,string $status='',string $q=''): string {$args=['activity'=>$activityId,'course'=>$courseId];if($cohortId>0)$args['cohort']=$cohortId;if($testId>0)$args['test']=$testId;if($status!=='')$args['status']=$status;if($q!=='')$args['q']=$q;return '/admin/tests.php?'.http_build_query($args);}
function admin_test_datetime(?string $value): string {if(!$value)return '—';$ts=strtotime($value);return $ts===false?$value:date('d/m/Y · H:i',$ts);}
function admin_test_value(mixed $value): string {$value=trim((string)$value);return $value===''?'—':h($value);}
$courseCohorts=course_cohorts_for_course($db,$courseId);$courseCohortIds=array_fill_keys(array_map(static fn(array $row): int=>(int)$row['id'],$courseCohorts),true);
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
 if(!verify_csrf('admin-tests',$_POST['_csrf']??null)){http_response_code(403);exit('Invalid request');}$action=(string)($_POST['action']??'');
 try{$targetId=(int)($_POST['test_id']??0);$target=student_test_for_admin($db,$targetId,$activityId)??throw new RuntimeException('Teste não encontrado.');if(!isset($courseCohortIds[(int)$target['cohort_id']]))throw new RuntimeException('Teste não pertence a este curso.');if($cohortId>0&&(int)$target['cohort_id']!==$cohortId)throw new RuntimeException('Teste não pertence a esta turma.');if($action==='message'){student_test_add_admin_message($db,$targetId,$activityId,(string)($_POST['message']??''));$_SESSION['admin_tests_notice']='Comentário enviado.';}elseif($action==='status'){student_test_set_review_status($db,$targetId,$activityId,(string)($_POST['review_status']??'submitted'));$_SESSION['admin_tests_notice']='Estado da avaliação atualizado.';}else throw new RuntimeException('Ação inválida.');header('Location: '.admin_tests_url($activityId,$courseId,$cohortId,$targetId,$status,$q),true,303);exit;}catch(Throwable $e){$_SESSION['admin_tests_notice']='Não foi possível concluir: '.$e->getMessage();header('Location: '.admin_tests_url($activityId,$courseId,$cohortId,$testId,$status,$q),true,303);exit;}
}
$tests=student_tests_for_admin($db,$activityId,$cohortId,$status,$q);if($cohortId===0)$tests=array_values(array_filter($tests,static fn(array $row): bool=>isset($courseCohortIds[(int)($row['cohort_id']??0)])));
$selectedTest=$testId>0?student_test_for_admin($db,$testId,$activityId):null;if($selectedTest&&!isset($courseCohortIds[(int)$selectedTest['cohort_id']]))$selectedTest=null;if($selectedTest&&$cohortId>0&&(int)$selectedTest['cohort_id']!==$cohortId)$selectedTest=null;$media=$selectedTest?student_test_media($db,(int)$selectedTest['id']):[];$messages=$selectedTest?student_test_messages($db,(int)$selectedTest['id']):[];
$notice=(string)($_SESSION['admin_tests_notice']??'');unset($_SESSION['admin_tests_notice']);$tone=str_starts_with($notice,'Não foi possível')?'error':'success';
admin_shell_start('tests','Testes · '.($cohort?(string)$cohort['title']:(string)$course['title']),$state,['/assets/admin-teaching.css','/assets/admin-operations.css']);
if($cohort)admin_cohort_context($course,$cohort,$activityId,'tests','Experimentações desta turma.');else admin_course_context($course,$activityId,'followup','Acompanhamento das turmas deste curso.');?>
<?php if(!$cohort):?><nav class="admin-content-tabs" aria-label="Acompanhamento do curso"><a href="<?=h(admin_course_url($activityId,$courseId,'questions'))?>">Dúvidas</a><a href="<?=h(admin_course_url($activityId,$courseId,'tests'))?>" aria-current="page">Testes</a></nav><?php endif;?>
<?php if($notice!==''):?><div class="admin-notice <?=h($tone)?>" role="<?=$tone==='error'?'alert':'status'?>"><?=h($notice)?></div><?php endif;?>
<?php if($selectedTest):?>
<section class="admin-card admin-teaching-detail"><header><div><a class="admin-back" href="<?=h(admin_tests_url($activityId,$courseId,$cohortId,0,$status,$q))?>">← Testes</a><p class="admin-kicker"><?=h((string)$selectedTest['cohort_title'])?> · <?=h((string)$selectedTest['student_name'])?></p><h2><?=h((string)$selectedTest['title'])?></h2><div class="admin-teaching-meta"><?=admin_badge(student_test_status_label((string)$selectedTest['status']),in_array((string)$selectedTest['status'],['submitted','needs_revision'],true)?'attention':'good')?><span><?=h(student_test_visibility_label((string)($selectedTest['visibility']??'private')))?></span><span>Atualizado <?=h(admin_test_datetime((string)$selectedTest['updated_at']))?></span></div></div></header></section>
<section class="admin-card"><header><div><h2>Dados do teste</h2></div></header><div class="admin-table-scroll" tabindex="0"><table class="admin-data-table"><tbody><tr><th>Data</th><td><?=admin_test_value($selectedTest['test_date'])?></td><th>Filme</th><td><?=admin_test_value($selectedTest['film'])?></td></tr><tr><th>Lote</th><td><?=admin_test_value($selectedTest['lot'])?></td><th>EI / ISO</th><td><?=admin_test_value($selectedTest['iso_reference'])?></td></tr><tr><th>Diafragma</th><td><?=admin_test_value($selectedTest['aperture'])?></td><th>Tempo calculado</th><td><?=admin_test_value($selectedTest['calculated_time'])?></td></tr><tr><th>Reciprocidade</th><td><?=admin_test_value($selectedTest['reciprocity_time'])?></td><th>Luz</th><td><?=admin_test_value($selectedTest['light_condition'])?></td></tr><tr><th>Claras/sombras</th><td colspan="3"><?=admin_test_value($selectedTest['tonal_range'])?></td></tr><tr><th>Revelador</th><td><?=admin_test_value($selectedTest['developer'])?></td><th>Diluição</th><td><?=admin_test_value($selectedTest['dilution'])?></td></tr><tr><th>Temperatura</th><td><?=admin_test_value($selectedTest['temperature'])?></td><th>Tempo de revelação</th><td><?=admin_test_value($selectedTest['development_time'])?></td></tr><tr><th>Movimentação</th><td colspan="3"><?=admin_test_value($selectedTest['agitation'])?></td></tr><tr><th>Observações</th><td colspan="3"><?=nl2br(admin_test_value($selectedTest['notes']))?></td></tr></tbody></table></div><div class="admin-inline-actions admin-block-gap"><?php foreach(['needs_revision'=>'Solicitar ajustes','reviewed'=>'Marcar como revisado','submitted'=>'Voltar para avaliação'] as $value=>$label):?><form method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('admin-tests'))?>"><input type="hidden" name="action" value="status"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="cohort_id" value="<?=$cohortId?>"><input type="hidden" name="test_id" value="<?=(int)$selectedTest['id']?>"><input type="hidden" name="review_status" value="<?=h($value)?>"><button class="admin-button secondary" type="submit"><?=h($label)?></button></form><?php endforeach;?></div></section>
<section class="admin-card"><header><div><h2>Imagens</h2><p><?=$media?count($media).' arquivo(s) enviado(s).':'Nenhuma imagem enviada.'?></p></div></header><?php if($media):?><div class="admin-media-grid"><?php foreach($media as $item):$src='/admin/student-test-media.php?'.http_build_query(['activity'=>$activityId,'id'=>(int)$item['id']]);?><a href="<?=h($src)?>" target="_blank" rel="noopener"><img class="admin-media-grid-image" src="<?=h($src)?>" alt="<?=h((string)$item['original_name'])?>" loading="lazy"><span class="muted"><?=h((string)($item['phase']??'result'))?> · <?=h((string)$item['original_name'])?></span></a><?php endforeach;?></div><?php endif;?></section>
<section class="admin-card"><header><div><h2>Avaliação e conversa</h2><p>Esta conversa é privada entre aluno e professor.</p></div></header><?php if(!$messages):?><div class="admin-empty">Ainda não há mensagens neste teste.</div><?php else:?><div class="admin-thread"><?php foreach($messages as $message):?><article class="admin-note"><p class="admin-kicker"><?=$message['author_role']==='admin'?'Professor':h((string)($message['student_name']?:$selectedTest['student_name']))?> · <?=h(admin_test_datetime((string)$message['created_at']))?></p><p><?=nl2br(h((string)$message['body']))?></p></article><?php endforeach;?></div><?php endif;?><form class="admin-form-grid admin-block-gap" method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('admin-tests'))?>"><input type="hidden" name="action" value="message"><input type="hidden" name="course_id" value="<?=$courseId?>"><input type="hidden" name="cohort_id" value="<?=$cohortId?>"><input type="hidden" name="test_id" value="<?=(int)$selectedTest['id']?>"><label class="admin-form-span-2">Comentário para o aluno<textarea name="message" rows="6" required></textarea></label><div class="admin-form-actions"><button class="admin-button" type="submit">Enviar comentário</button></div></form></section>
<?php else:?>
<section class="admin-card admin-teaching-detail"><header><div><h2>Testes</h2><p>Experimentações enviadas pelos alunos para avaliação.</p></div></header></section>
<form class="admin-data-toolbar" method="get"><input type="hidden" name="activity" value="<?=$activityId?>"><input type="hidden" name="course" value="<?=$courseId?>"><?php if($cohort):?><input type="hidden" name="cohort" value="<?=$cohortId?>"><?php else:?><label>Turma<select name="cohort"><option value="0">Todas</option><?php foreach($courseCohorts as $item):?><option value="<?=(int)$item['id']?>"><?=h((string)$item['title'])?></option><?php endforeach;?></select></label><?php endif;?><label>Estado<select name="status"><option value="">Todos</option><option value="submitted"<?=$status==='submitted'?' selected':''?>>Aguardando avaliação</option><option value="needs_revision"<?=$status==='needs_revision'?' selected':''?>>Ajustes solicitados</option><option value="reviewed"<?=$status==='reviewed'?' selected':''?>>Revisados</option><option value="draft"<?=$status==='draft'?' selected':''?>>Rascunhos</option></select></label><label class="grow">Buscar<input name="q" value="<?=h($q)?>" placeholder="Aluno, e-mail ou título"></label><button class="admin-button secondary" type="submit">Filtrar</button></form>
<div class="admin-list-summary"><span><?=count($tests)?> teste(s)</span></div><?php if(!$tests):?><div class="admin-empty">Nenhum teste encontrado.</div><?php else:?><div class="admin-table-scroll" tabindex="0" aria-label="Testes"><table class="admin-data-table"><thead><tr><th>Teste</th><th>Aluno<?php if(!$cohort):?> / turma<?php endif;?></th><th>Visibilidade</th><th>Estado</th><th></th></tr></thead><tbody><?php foreach($tests as $test):?><tr><td><div class="admin-table-primary"><strong><?=h((string)$test['title'])?></strong><span><?=h((string)($test['test_date']?:'sem data'))?></span></div></td><td><div class="admin-table-primary"><strong><?=h((string)$test['student_name'])?></strong><?php if(!$cohort):?><span><?=h((string)$test['cohort_title'])?></span><?php endif;?></div></td><td><?=h(student_test_visibility_label((string)($test['visibility']??'private')))?></td><td><?=admin_badge(student_test_status_label((string)$test['status']),in_array((string)$test['status'],['submitted','needs_revision'],true)?'attention':'neutral')?></td><td class="actions"><a class="admin-button secondary admin-table-action" href="<?=h(admin_tests_url($activityId,$courseId,$cohortId,(int)$test['id'],$status,$q))?>">Revisar</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
<?php endif;?>
<?php admin_shell_end();