<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
security_headers();student_private_headers();$db=database();$student=student_account_current($db);if(!$student){header('Location: /aluno/login.php?next=%2Faluno%2Fcaderno.php',true,303);exit;}$studentId=(int)$student['id'];$ids=array_values(array_unique(array_filter(array_map('intval',(array)($_GET['id']??[])))));if(count($ids)!==2){$_SESSION['student_process_notice']='Selecione exatamente dois registros para comparar.';header('Location: /aluno/caderno.php',true,303);exit;}$records=[];foreach($ids as $id){$record=student_test_for_student($db,$id,$studentId);if(!$record){http_response_code(404);exit('Registro não encontrado.');}$record['steps']=student_process_steps($db,$id);$records[]=$record;}
[$a,$b]=$records;$fields=['Data'=>'test_date','Filme'=>'film','Lote'=>'lot','EI / ISO'=>'iso_reference','Diafragma'=>'aperture','Tempo calculado'=>'calculated_time','Tempo corrigido'=>'reciprocity_time','Condição de luz'=>'light_condition','Faixa tonal / intenção'=>'tonal_range'];
student_shell_start('Comparar processos',null,$student);?>
<div class="student-appbar"><a class="student-back" href="/aluno/caderno.php">← Caderno de Processos</a></div><p class="student-kicker">Comparação</p><h1 class="student-title">Dois registros, uma leitura</h1><p class="student-lead">Os valores diferentes ficam marcados para facilitar a identificação do que mudou.</p>
<section class="student-section"><div class="student-compare-grid student-compare-head"><div></div><h2><?=h((string)$a['title'])?></h2><h2><?=h((string)$b['title'])?></h2></div><?php foreach($fields as $label=>$key):$av=trim((string)($a[$key]??''));$bv=trim((string)($b[$key]??''));$different=$av!==$bv;?><div class="student-compare-grid<?=$different?' is-different':''?>"><strong><?=h($label)?></strong><span><?=h($av!==''?$av:'—')?></span><span><?=h($bv!==''?$bv:'—')?></span></div><?php endforeach;?></section>
<section class="student-section"><div class="student-section-heading"><div><p class="student-kicker">Processamento</p><h2 class="student-subtitle">Caminhos</h2></div></div><div class="student-compare-processes"><article><h3><?=h((string)$a['title'])?></h3><?=student_compare_steps_html($a['steps'])?></article><article><h3><?=h((string)$b['title'])?></h3><?=student_compare_steps_html($b['steps'])?></article></div></section>
<?php student_shell_end();
function student_compare_steps_html(array $steps): string {if(!$steps)return '<p class="student-empty">Sem etapas registradas.</p>';$html='<ol class="student-process-summary">';foreach($steps as $step){$detail=[];if($step['calculated_dilution']!=='')$detail[]=$step['calculated_dilution'];if($step['temperature']!=='')$detail[]=$step['temperature'];if($step['duration']!=='')$detail[]=$step['duration'];$name=$step['chemical_name']!==''?$step['chemical_name']:$step['label'];$html.='<li><strong>'.h((string)$name).'</strong>'.($detail?'<span>'.h(implode(' · ',$detail)).'</span>':'').'</li>';}$html.='</ol>';return $html;}