<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
security_headers();student_private_headers();
$db=database();$student=student_account_current($db);if(!$student){header('Location: /aluno/login.php?next=%2Faluno%2Fcaderno.php',true,303);exit;}$studentId=(int)$student['id'];
$ids=array_values(array_unique(array_filter(array_map('intval',(array)($_GET['id']??$_POST['compare_id']??[])),static fn(int $id): bool=>$id>0)));if(count($ids)>2)$ids=array_slice($ids,0,2);
$allRecords=student_process_records_for_student($db,$studentId);$recordMap=[];foreach($allRecords as $item)$recordMap[(int)$item['id']]=$item;
foreach($ids as $id)if(!isset($recordMap[$id])){http_response_code(404);exit('Registro não encontrado.');}
$error='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('student-research-compare',$_POST['_csrf']??null))$error='Solicitação inválida.';
    else try{
        $action=(string)($_POST['action']??'');
        if($action!=='fork')throw new RuntimeException('Ação inválida.');
        $baseId=(int)($_POST['source_test_id']??0);if(!in_array($baseId,$ids,true))throw new RuntimeException('Escolha um dos registros comparados como base.');
        $intent=(string)($_POST['research_intent']??'');$created=student_research_fork($db,$baseId,$studentId,$intent);$base=$recordMap[$baseId];
        $_SESSION['student_process_notice']='Próxima variação criada a partir de “'.(string)$base['title'].'”. Intenção: '.(string)$created['research_intent'].' Revise a exposição antes de continuar.';
        header('Location: /aluno/teste.php?id='.(int)$created['id'].'&view=exposure',true,303);exit;
    }catch(Throwable $e){$error=$e->getMessage();}
}
student_shell_start('Comparar experimentações',null,$student);?>
<div class="student-appbar"><a class="student-back" href="/aluno/caderno.php">← Caderno de Processos</a></div>
<p class="student-kicker">Comparação</p><h1 class="student-title">Comparar experimentações</h1><p class="student-lead">Veja o que foi registrado de modo diferente e leia essas diferenças junto com os resultados. A comparação descreve os registros; não atribui causa ao resultado.</p>
<?php if($error!==''):?><p class="ui-alert ui-alert-error" role="alert"><?=h($error)?></p><?php endif;?>
<?php if(count($allRecords)<2):?>
<section class="student-section"><div class="student-empty"><strong>São necessários dois registros.</strong><p>Crie outra experimentação no Caderno para poder comparar.</p><a class="button button-primary" href="/aluno/caderno.php">Voltar ao Caderno</a></div></section>
<?php elseif(count($ids)<2):?>
<section class="student-section student-research-picker" aria-labelledby="compare-pick-title"><div class="student-section-heading"><div><p class="student-kicker">Escolha</p><h2 class="student-subtitle" id="compare-pick-title"><?=count($ids)===1?'Escolha o segundo registro':'Escolha dois registros'?></h2></div><p>Use dois registros que façam sentido lado a lado para a pergunta que você quer investigar.</p></div>
<form method="get" class="student-research-picker-form">
<?php if(count($ids)===1):$base=$recordMap[$ids[0]];?><input type="hidden" name="id[]" value="<?=(int)$base['id']?>"><article class="student-research-picked"><span class="student-card-label">Registro A</span><h3><?=h((string)$base['title'])?></h3><p><?=h((string)($base['test_date']?:'Sem data'))?> · <?=h((string)(($base['context_scope']??'course')==='personal'?'Pessoal':$base['public_title'].' · '.$base['cohort_title']))?></p></article><label class="form-field">Registro B<select name="id[]" required><option value="">Escolha…</option><?php foreach($allRecords as $candidate):if((int)$candidate['id']===(int)$base['id'])continue;?><option value="<?=(int)$candidate['id']?>"><?=h((string)$candidate['title'])?> · <?=h((string)($candidate['test_date']?:'sem data'))?></option><?php endforeach;?></select></label>
<?php else:?><label class="form-field">Registro A<select name="id[]" required><option value="">Escolha…</option><?php foreach($allRecords as $candidate):?><option value="<?=(int)$candidate['id']?>"><?=h((string)$candidate['title'])?> · <?=h((string)($candidate['test_date']?:'sem data'))?></option><?php endforeach;?></select></label><label class="form-field">Registro B<select name="id[]" required><option value="">Escolha…</option><?php foreach($allRecords as $candidate):?><option value="<?=(int)$candidate['id']?>"><?=h((string)$candidate['title'])?> · <?=h((string)($candidate['test_date']?:'sem data'))?></option><?php endforeach;?></select></label><?php endif;?><div class="student-actions"><button class="button button-primary" type="submit">Comparar registros</button></div></form></section>
<?php else:
$a=$recordMap[$ids[0]];$b=$recordMap[$ids[1]];$stepsA=student_process_steps($db,(int)$a['id']);$stepsB=student_process_steps($db,(int)$b['id']);$differences=student_research_difference_rows($a,$b,$stepsA,$stepsB);$exposureRows=student_research_exposure_rows($a,$b);$resultMediaA=student_test_media_by_phase(student_test_media($db,(int)$a['id']),'result');$resultMediaB=student_test_media_by_phase(student_test_media($db,(int)$b['id']),'result');?>
<section class="student-section student-research-differences" aria-labelledby="research-differences-title"><div class="student-section-heading"><div><p class="student-kicker">O que mudou</p><h2 class="student-subtitle" id="research-differences-title">Diferenças registradas</h2></div><p>Somente campos comparáveis que realmente mudaram aparecem aqui.</p></div>
<div class="student-research-comparison-head" aria-hidden="true"><span></span><strong>A · <?=h((string)$a['title'])?></strong><strong>B · <?=h((string)$b['title'])?></strong></div>
<?php if(!$differences):?><div class="student-research-no-difference"><strong>Nenhuma diferença técnica detectada.</strong><p>Nos campos comparáveis preenchidos, os registros são iguais. Isso não significa que tudo o que aconteceu no laboratório tenha sido idêntico.</p></div><?php else:?><div class="student-research-difference-list"><?php foreach($differences as $row):?><div class="student-research-difference-row"><div><small><?=h((string)$row['group'])?></small><strong><?=h((string)$row['label'])?></strong></div><span><?=h((string)$row['a'])?></span><span><?=h((string)$row['b'])?></span></div><?php endforeach;?></div><?php endif;?></section>

<section class="student-section student-research-results" aria-labelledby="research-results-title"><div class="student-section-heading"><div><p class="student-kicker">Resultado observado</p><h2 class="student-subtitle" id="research-results-title">Leia os resultados lado a lado</h2></div><p>As imagens e anotações são evidência do que foi obtido, não uma conclusão automática sobre a causa.</p></div><div class="student-research-result-grid"><?=student_research_result_card($a,$resultMediaA,'A')?><?=student_research_result_card($b,$resultMediaB,'B')?></div></section>

<section class="student-section student-research-evidence" aria-labelledby="research-evidence-title"><div class="student-section-heading"><div><p class="student-kicker">Dados registrados</p><h2 class="student-subtitle" id="research-evidence-title">Conferir exposição e processamento</h2></div><p>Use os dados completos para verificar a leitura acima.</p></div><details open><summary>Exposição</summary><div class="student-compare-grid student-compare-head"><div></div><h2><?=h((string)$a['title'])?></h2><h2><?=h((string)$b['title'])?></h2></div><?php foreach($exposureRows as $row):?><div class="student-compare-grid<?=$row['different']?' is-different':''?>"><strong><?=h((string)$row['label'])?></strong><span><?=h((string)$row['a'])?></span><span><?=h((string)$row['b'])?></span></div><?php endforeach;?></details><details><summary>Processamento</summary><div class="student-compare-processes"><article><h3><?=h((string)$a['title'])?></h3><?=student_research_steps_html($stepsA)?></article><article><h3><?=h((string)$b['title'])?></h3><?=student_research_steps_html($stepsB)?></article></div></details></section>

<section class="student-section student-research-next" aria-labelledby="research-next-title"><div class="student-section-heading"><div><p class="student-kicker">Próxima tentativa</p><h2 class="student-subtitle" id="research-next-title">Continue a pesquisa</h2></div><p>Escolha qual registro será o ponto de partida e declare o que pretende mudar antes de criar a próxima tentativa.</p></div><form method="post" class="student-research-next-form" data-ui-validate><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-research-compare'))?>"><input type="hidden" name="action" value="fork"><?php foreach($ids as $compareId):?><input type="hidden" name="compare_id[]" value="<?=$compareId?>"><?php endforeach;?><fieldset class="choice-field"><legend>Usar como base</legend><div class="student-research-basis-options"><label class="choice-option"><input type="radio" name="source_test_id" value="<?=(int)$a['id']?>" required><span>A · <?=h((string)$a['title'])?></span></label><label class="choice-option"><input type="radio" name="source_test_id" value="<?=(int)$b['id']?>" required><span>B · <?=h((string)$b['title'])?></span></label></div></fieldset><label class="form-field">O que você pretende mudar nesta próxima tentativa?<textarea name="research_intent" rows="4" maxlength="1200" required placeholder="Ex.: manter o processamento e testar EI 400; reduzir o tempo da primeira revelação; repetir a exposição com outra condição de luz."></textarea></label><p class="student-field-help">O novo registro começa com os dados de exposição da base. Processamento e resultado não são copiados como fatos já realizados.</p><div class="student-actions"><button class="button button-primary" type="submit">Criar próxima variação</button></div></form></section>
<?php endif;?>
<?php student_shell_end();
function student_research_steps_html(array $steps): string {if(!$steps)return '<p class="student-empty">Sem etapas registradas.</p>';$html='<ol class="student-process-summary">';foreach($steps as $step){$detail=[];if(trim((string)($step['calculated_dilution']??''))!=='')$detail[]=(string)$step['calculated_dilution'];if(trim((string)($step['temperature']??''))!=='')$detail[]=(string)$step['temperature'];if(trim((string)($step['duration']??''))!=='')$detail[]=(string)$step['duration'];$name=student_research_step_name($step);$html.='<li><strong>'.h($name).'</strong>'.($detail?'<span>'.h(implode(' · ',$detail)).'</span>':'').'</li>';}$html.='</ol>';return $html;}
function student_research_result_card(array $record,array $media,string $label): string {$html='<article class="student-research-result-card"><span class="student-card-label">Registro '.h($label).'</span><h3>'.h((string)$record['title']).'</h3>';if($media){$html.='<div class="student-research-result-media">';foreach($media as $item)$html.='<img src="/aluno/teste-media.php?id='.(int)$item['id'].'" alt="Resultado de '.h((string)$record['title']).'" loading="lazy">';$html.='</div>';}else $html.='<div class="student-research-result-placeholder">Sem imagem de resultado.</div>';$notes=trim((string)($record['notes']??''));$html.='<div class="student-research-result-notes"><small>Anotações</small><p>'.($notes!==''?nl2br(h($notes)):'Sem anotações de resultado.').'</p></div><a class="student-link" href="/aluno/teste.php?id='.(int)$record['id'].'&amp;view=review">Abrir resultado</a></article>';return $html;}
