<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
security_headers();student_private_headers();
$db=database();student_enrollment_reconcile_confirmed($db);$student=student_account_current($db);if(!$student){header('Location: /aluno/login.php?next=%2Faluno%2Fcursos.php',true,303);exit;}
$studentId=(int)$student['id'];$enrollments=student_enrollment_list($db,$studentId);$requestedCohortUuid=is_string($_GET['cohort']??null)?trim((string)$_GET['cohort']):'';
$selectedEnrollment=null;if($requestedCohortUuid!=='')$selectedEnrollment=student_enrollment_dashboard_context($enrollments,$requestedCohortUuid);elseif(count($enrollments)===1)$selectedEnrollment=$enrollments[0];
$selectedActivity=null;if($selectedEnrollment){$selectedActivity=activity_by_id($db,(int)$selectedEnrollment['activity_id']);if(!$selectedActivity)$selectedEnrollment=null;}
student_shell_start('Curso',$selectedActivity,$student);?>
<?php if(!$enrollments):?>
  <p class="student-kicker">Curso</p><h1 class="student-title">Nenhuma matrícula ativa</h1><p class="student-lead">Quando uma matrícula estiver ativa, o material e as aulas aparecem aqui.</p>
<?php elseif(!$selectedEnrollment):?>
  <p class="student-kicker">Cursos</p><h1 class="student-title">Escolha a matrícula</h1><p class="student-lead">Esta escolha aparece somente porque há mais de um curso ou turma disponível.</p>
  <nav class="student-academic-choice-list" aria-label="Matrículas disponíveis"><?php foreach($enrollments as $enrollment):$url='/aluno/cursos.php?cohort='.rawurlencode((string)$enrollment['cohort_uuid']);?><a class="student-academic-choice" href="<?=h($url)?>"><span><span class="student-status"><?=h(student_enrollment_cohort_status_label((string)$enrollment['cohort_status']))?></span><h2><?=h((string)$enrollment['course_title'])?></h2><p><?=h((string)$enrollment['cohort_title'])?></p></span><span>→</span></a><?php endforeach;?></nav>
<?php else:
  $enrollment=$selectedEnrollment;$activity=$selectedActivity;$courseId=(int)($enrollment['course_id']??0);$workshopId=(int)($enrollment['workshop_page_id']??0);$pages=student_enrollment_pages_for_enrollment($db,$enrollment);$attention=student_feedback_course_attention($db,$studentId,(int)$enrollment['cohort_id']);
  if($courseId>0)$releases=course_lesson_release_rows_for_course($db,(int)$enrollment['cohort_id'],$courseId);elseif($workshopId>0)$releases=workshop_course_lesson_release_rows($db,(int)$enrollment['cohort_id'],$workshopId);else $releases=course_lesson_release_rows($db,(int)$enrollment['cohort_id'],(int)$enrollment['activity_id']);
  $releaseStates=[];$pendingLessons=[];foreach($releases as $lesson){$state=cms_access_lesson_release_state(isset($lesson['released_at'])?(string)$lesson['released_at']:null);$releaseStates[(int)$lesson['id']]=$state;if($state!=='released')$pendingLessons[]=[$lesson,$state];}
  $materialItems=[];foreach($pages as $page){$url=cms_page_url($activity,$page,(string)$page['locale']);$url.=(str_contains($url,'?')?'&':'?').'cohort='.rawurlencode((string)$enrollment['cohort_uuid']);$summary=$courseId>0?course_material_page_release_summary($db,$courseId,(int)$enrollment['cohort_id'],(int)$page['id'],$releases):['state'=>'available','label'=>'Disponível'];$materialItems[]=['page'=>$page,'url'=>$url,'summary'=>$summary];}
?>
  <header class="student-academic-course-head"><p class="student-kicker">Curso</p><div class="student-academic-course-head-main"><h1 class="student-title"><?=h((string)$enrollment['course_title'])?></h1><span class="student-status"><?=h(student_enrollment_cohort_status_label((string)$enrollment['cohort_status']))?></span></div><div class="student-academic-course-meta"><span><?=h((string)$enrollment['cohort_title'])?></span><?php if(count($enrollments)>1):?><a href="/aluno/cursos.php">Trocar curso</a><?php endif;?></div></header>
  <?php if($attention['has_attention']):$latestFeedback=$attention['feedback'][0]??null;?>
  <section class="student-academic-attention" aria-labelledby="student-course-attention"><div><p class="student-kicker">Acompanhamento</p><h2 id="student-course-attention">Há algo para retomar</h2></div><div class="student-academic-attention-list"><?php if($latestFeedback):$state=student_feedback_state($latestFeedback);?><a href="/aluno/teste.php?id=<?=(int)$latestFeedback['id']?>&amp;view=review"><span><strong><?=h((string)$state['label'])?></strong><small><?=h((string)$latestFeedback['title'])?></small></span><span>→</span></a><?php endif;?><?php if((int)$attention['question_count']>0):?><a href="/aluno/duvidas.php?cohort=<?=h(rawurlencode((string)$enrollment['cohort_uuid']))?>"><span><strong><?=h(student_experience_count((int)$attention['question_count'],'dúvida aberta','dúvidas abertas'))?></strong><small>Continuar conversa</small></span><span>→</span></a><?php endif;?></div></section>
  <?php endif;?>
  <section class="student-academic-study" aria-labelledby="student-course-material"><div class="student-academic-study-head"><div><p class="student-kicker">Estudar</p><h2 id="student-course-material">Material</h2></div></div>
    <?php if(!$materialItems):?><p class="student-academic-empty">Ainda não há material publicado para esta matrícula.</p><?php else:?><div class="student-academic-material-list"><?php foreach($materialItems as $item):$page=$item['page'];$summary=$item['summary'];$detail=match((string)$summary['state']){'partial'=>'Parte desta página já está disponível.','scheduled'=>'O conteúdo desta página está vinculado a uma aula agendada.','blocked'=>'O conteúdo desta página aguarda liberação.',default=>''};?><a class="student-academic-material-row<?=in_array((string)$summary['state'],['scheduled','blocked'],true)?' is-waiting':''?>" href="<?=h((string)$item['url'])?>"><span><strong class="student-academic-material-title"><?=h((string)$page['title'])?></strong><?php if($detail!==''):?><small class="student-academic-material-detail"><?=h($detail)?></small><?php endif;?></span><span class="student-academic-material-state" data-state="<?=h((string)$summary['state'])?>"><?=h((string)$summary['label'])?></span></a><?php endforeach;?></div><?php endif;?>
  </section>
  <?php if($pendingLessons):?><section class="student-academic-release-summary" aria-labelledby="student-course-next-releases"><h3 id="student-course-next-releases">Próximas liberações</h3><div class="student-academic-release-list"><?php foreach($pendingLessons as [$lesson,$state]):$when=$state==='scheduled'?student_course_release_when((string)($lesson['released_at']??'')):'Aguardando liberação';?><div class="student-academic-release-line"><span><?=h((string)$lesson['title'])?></span><small><?=h($when)?></small></div><?php endforeach;?></div></section><?php elseif(!$releases):?><p class="student-academic-empty">As aulas aparecerão conforme forem cadastradas.</p><?php endif;?>
  <div class="student-academic-course-actions"><a class="button button-secondary" href="/aluno/duvidas.php?cohort=<?=h(rawurlencode((string)$enrollment['cohort_uuid']))?>">Dúvidas e respostas</a></div>
<?php endif;?>
<?php student_shell_end();
function student_course_release_when(string $value): string {$ts=strtotime($value);return $ts===false?'Agendada':'Agendada para '.date('d/m/Y · H:i',$ts);}
