<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';security_headers();student_private_headers();$db=database();student_account_reconcile_confirmed_registrations($db);$student=student_account_current($db);if(!$student){header('Location: /aluno/login.php?next=%2Faluno%2Fduvidas.php',true,303);exit;}$studentId=(int)$student['id'];$enrollments=student_enrollment_list($db,$studentId);$cohortUuid=trim((string)($_GET['cohort']??$_POST['cohort']??''));$enrollment=student_enrollment_dashboard_context($enrollments,$cohortUuid);if(!$enrollment&&count($enrollments)===1)$enrollment=$enrollments[0];$error='';$requestedAnnotationId=(int)($_GET['annotation']??$_POST['source_annotation_id']??0);
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'&&$enrollment){if(!verify_csrf('student-questions',$_POST['_csrf']??null))$error='Solicitação inválida.';else try{$action=(string)($_POST['action']??'create');$questionId=(int)($_POST['question_id']??0);if($action==='create'){$sourceAnnotationId=(int)($_POST['source_annotation_id']??0);$db->beginTransaction();try{$created=student_question_create($db,$studentId,(int)$enrollment['cohort_id'],$_POST);$questionId=(int)($created['id']??0);if($sourceAnnotationId>0)student_question_attach_annotation($db,$questionId,$studentId,(int)$enrollment['cohort_id'],$sourceAnnotationId);$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}}elseif($action==='reply'){$target=student_question_for_enrolled_student($db,$studentId,$questionId);if(!$target||!student_question_in_cohort_context($db,$target,(int)$enrollment['cohort_id']))throw new RuntimeException('Dúvida não encontrada nesta turma.');student_question_reply_enrolled($db,$studentId,$questionId,(string)($_POST['body']??''));}elseif($action==='resolve'){$target=student_question_for_enrolled_student($db,$studentId,$questionId);if(!$target||!student_question_in_cohort_context($db,$target,(int)$enrollment['cohort_id']))throw new RuntimeException('Dúvida não encontrada nesta turma.');student_question_resolve($db,$studentId,$questionId);}else throw new RuntimeException('Ação inválida.');$url='/aluno/duvidas.php?cohort='.rawurlencode((string)$enrollment['cohort_uuid']);if($questionId>0)$url.='&id='.$questionId;header('Location: '.$url,true,303);exit;}catch(Throwable $e){$error=$e->getMessage();}}
$sourceAnnotation=$enrollment&&$requestedAnnotationId>0?student_question_annotation_source($db,$studentId,(int)$enrollment['cohort_id'],$requestedAnnotationId):null;if($requestedAnnotationId>0&&$enrollment&&!$sourceAnnotation&&$error==='')$error='Essa anotação não está disponível nesta turma.';
if($sourceAnnotation){$existingQuestion=student_question_from_annotation($db,$studentId,(int)$sourceAnnotation['id']);if($existingQuestion&&($_SERVER['REQUEST_METHOD']??'GET')==='GET'){header('Location: /aluno/duvidas.php?cohort='.rawurlencode((string)$enrollment['cohort_uuid']).'&id='.(int)$existingQuestion['id'],true,303);exit;}}
$activity=$enrollment?activity_by_id($db,(int)$enrollment['activity_id']):null;$questionId=(int)($_GET['id']??$_POST['question_id']??0);$question=$questionId>0?student_question_for_enrolled_student($db,$studentId,$questionId):null;if($question&&$enrollment&&!student_question_in_cohort_context($db,$question,(int)$enrollment['cohort_id']))$question=null;$questionSource=$question&&$enrollment&&(int)$question['cohort_id']===(int)$enrollment['cohort_id']?student_question_source_context($db,$question):null;$messages=$question?student_question_messages($db,$questionId):[];$questions=$enrollment?student_questions_for_cohort($db,$studentId,(int)$enrollment['cohort_id']):[];$records=$enrollment?array_values(array_filter(student_process_records_for_student($db,$studentId),static fn(array $r): bool=>(int)($r['context_cohort_id']??0)===(int)$enrollment['cohort_id'])):[];$evaluationThreads=$enrollment?student_feedback_conversations_for_student($db,$studentId,(int)$enrollment['cohort_id'],20):[];
$failedQuestionCreate=$error!==''&&($_SERVER['REQUEST_METHOD']??'GET')==='POST'&&(string)($_POST['action']??'create')==='create';
$failedQuestionReply=$error!==''&&($_SERVER['REQUEST_METHOD']??'GET')==='POST'&&(string)($_POST['action']??'')==='reply';
$validQuestionTopics=['Exposição','Filme','Química','Revelação','Material','Equipamento','Outro'];
$questionDraftTopic=$failedQuestionCreate?(string)($_POST['topic']??''):($sourceAnnotation?'Material':'Exposição');
if(!in_array($questionDraftTopic,$validQuestionTopics,true))$questionDraftTopic='Exposição';
$questionDraftVisibility=$failedQuestionCreate?(string)($_POST['visibility']??'private'):'private';
if(!in_array($questionDraftVisibility,['private','cohort','course'],true))$questionDraftVisibility='private';
$questionDraftTitle=$failedQuestionCreate?(string)($_POST['title']??''):'';
$questionDraftBody=$failedQuestionCreate?(string)($_POST['body']??''):(string)($sourceAnnotation['body']??'');
$questionDraftRecord=$failedQuestionCreate?(int)($_POST['test_id']??0):0;
$questionReplyDraft=$failedQuestionReply?(string)($_POST['body']??''):'';
$linkedTestUrl=$question?student_question_related_record_href($db,$question,$studentId):'';
student_shell_start('Dúvidas',$activity?:null,$student);?>
<?php if(!$enrollment):?><p class="student-kicker">Cursos</p><h1 class="student-title">Dúvidas</h1><p class="student-lead">Escolha a turma em que deseja abrir a discussão.</p><div class="student-test-list"><?php foreach($enrollments as $row):?><a class="student-test-row" href="/aluno/duvidas.php?cohort=<?=h(rawurlencode((string)$row['cohort_uuid']))?>"><div><h3><?=h((string)$row['course_title'])?></h3><p><?=h((string)$row['cohort_title'])?></p></div><strong>Abrir →</strong></a><?php endforeach;?></div><?php else:$pages=student_enrollment_pages_for_enrollment($db,$enrollment);$materialUrl='';if($pages&&$activity){$materialUrl=cms_page_url($activity,$pages[0],(string)$pages[0]['locale']);$materialUrl.=(str_contains($materialUrl,'?')?'&':'?').'cohort='.rawurlencode((string)$enrollment['cohort_uuid']);}student_course_context_header($enrollment,'questions',$materialUrl);?>
<?php if($error):?><p class="ui-alert ui-alert-error" role="alert"><?=h($error)?></p><?php endif;?>
<?php if($question):?><div data-student-local-key="question-thread"><div class="student-appbar"><a class="student-back" href="/aluno/duvidas.php?cohort=<?=h(rawurlencode((string)$enrollment['cohort_uuid']))?>">← Todas as dúvidas</a><span class="student-status"><?=$question['status']==='resolved'?'Resolvida':'Aberta'?></span></div><section class="student-question-detail"><p class="student-kicker"><?=h((string)$question['topic'])?></p><h2 class="student-subtitle"><?=h((string)$question['title'])?></h2><?php if($questionSource&&trim((string)$questionSource['quote_exact'])!==''):?><div class="student-question-source"><span>Trecho do material</span><blockquote><?=h((string)$questionSource['quote_exact'])?></blockquote></div><?php endif;?><p><?=nl2br(h((string)$question['body']))?></p><?php if($linkedTestUrl!==''):?><a class="student-link" href="<?=h($linkedTestUrl)?>">Abrir registro relacionado →</a><?php endif;?></section><?php if($messages):?><div class="student-message-list"><?php foreach($messages as $message):?><article><strong><?=$message['author_role']==='admin'?'Professor':h((string)($message['student_name']??'Aluno'))?></strong><p><?=nl2br(h((string)$message['body']))?></p><small><?=h(student_test_message_date((string)$message['created_at']))?></small></article><?php endforeach;?></div><?php endif;?><form method="post" class="student-form-grid" data-student-local-form data-local-refresh="question-thread" data-local-success="reset"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-questions'))?>"><input type="hidden" name="action" value="reply"><input type="hidden" name="question_id" value="<?=(int)$question['id']?>"><input type="hidden" name="cohort" value="<?=h((string)$enrollment['cohort_uuid'])?>"><label class="form-field student-span-2">Resposta<textarea name="body" rows="3" required><?=h($questionReplyDraft)?></textarea></label><button class="button button-secondary" type="submit">Enviar resposta</button></form><?php if((int)$question['student_id']===$studentId&&$question['status']!=='resolved'):?><form method="post" class="student-inline-form" data-student-local-form data-local-refresh="question-thread"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-questions'))?>"><input type="hidden" name="action" value="resolve"><input type="hidden" name="question_id" value="<?=(int)$question['id']?>"><input type="hidden" name="cohort" value="<?=h((string)$enrollment['cohort_uuid'])?>"><button class="student-link" type="submit">Marcar como resolvida</button></form><?php endif;?></div>
<?php else:?><div class="student-page-heading"><div><p class="student-kicker">Curso</p><h2 class="student-subtitle">Dúvidas e respostas</h2></div><button class="button button-primary" type="button" data-question-new-toggle aria-expanded="<?=$sourceAnnotation||$failedQuestionCreate?'true':'false'?>">Nova dúvida</button></div><section class="student-section" data-question-new-panel<?=$sourceAnnotation||$failedQuestionCreate?'':' hidden'?>><?php if($sourceAnnotation):?><div class="student-question-source"><span>Da sua anotação</span><?php if(trim((string)$sourceAnnotation['quote_exact'])!==''):?><blockquote><?=h((string)$sourceAnnotation['quote_exact'])?></blockquote><?php endif;?><p><?=nl2br(h((string)$sourceAnnotation['body']))?></p></div><?php endif;?><form method="post" class="student-form-grid"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-questions'))?>"><input type="hidden" name="action" value="create"><input type="hidden" name="cohort" value="<?=h((string)$enrollment['cohort_uuid'])?>"><?php if($sourceAnnotation):?><input type="hidden" name="source_annotation_id" value="<?=(int)$sourceAnnotation['id']?>"><?php endif;?><label class="form-field">Assunto<select name="topic"><?php foreach($validQuestionTopics as $topicName):?><option<?=$questionDraftTopic===$topicName?' selected':''?>><?=h($topicName)?></option><?php endforeach;?></select></label><label class="form-field">Registro relacionado<select name="test_id"><option value="">Nenhum</option><?php foreach($records as $record):?><option value="<?=(int)$record['id']?>"<?=$questionDraftRecord===(int)$record['id']?' selected':''?>><?=h((string)$record['title'])?></option><?php endforeach;?></select></label><label class="form-field student-span-2">Título<input name="title" required maxlength="180" value="<?=h($questionDraftTitle)?>"<?=$sourceAnnotation?' autofocus':''?>></label><label class="form-field student-span-2">Dúvida<textarea name="body" rows="5" required><?=h($questionDraftBody)?></textarea></label><fieldset class="choice-field student-span-2"><legend>Quem pode participar?</legend><div class="choice-row"><label class="choice-option"><input type="radio" name="visibility" value="private"<?=$questionDraftVisibility==='private'?' checked':''?>><span>Somente eu e o professor</span></label><label class="choice-option"><input type="radio" name="visibility" value="cohort"<?=$questionDraftVisibility==='cohort'?' checked':''?>><span>Minha turma</span></label><label class="choice-option"><input type="radio" name="visibility" value="course"<?=$questionDraftVisibility==='course'?' checked':''?>><span>Todas as turmas deste curso</span></label></div></fieldset><div class="student-actions student-span-2"><button class="button button-primary" type="submit">Publicar dúvida</button><button class="button button-secondary" type="button" data-question-new-cancel>Cancelar</button></div></form></section>
<?php if($evaluationThreads):?><section class="student-section student-evaluation-conversations" aria-labelledby="student-evaluation-conversations-title"><div class="student-section-heading"><div><p class="student-kicker">Resultados</p><h3 id="student-evaluation-conversations-title">Conversas de avaliação</h3></div></div><p class="student-field-help">O retorno sobre um resultado continua no próprio registro, junto da fotografia, exposição e processamento avaliados.</p><div class="student-test-list"><?php foreach($evaluationThreads as $thread):$state=student_feedback_state($thread);?><a class="student-test-row" href="/aluno/teste.php?id=<?=(int)$thread['id']?>&amp;view=review"><div><span class="student-status"><?=h((string)$state['label'])?></span><h3><?=h((string)$thread['title'])?></h3><p><?=(int)$thread['message_count']>0?h(student_experience_count((int)$thread['message_count'],'mensagem','mensagens')):'Sem mensagens ainda'?></p></div><strong>Abrir resultado →</strong></a><?php endforeach;?></div></section><?php endif;?>
<section class="student-section" aria-labelledby="student-general-questions"><div class="student-section-heading"><div><p class="student-kicker">Material e prática</p><h3 id="student-general-questions">Dúvidas da turma e do curso</h3></div></div><?php if(!$questions):?><div class="student-empty">Ainda não há dúvidas nesta turma ou curso.</div><?php else:?><div class="student-test-list"><?php foreach($questions as $row):?><a class="student-test-row" href="/aluno/duvidas.php?cohort=<?=h(rawurlencode((string)$enrollment['cohort_uuid']))?>&amp;id=<?=(int)$row['id']?>"><div><span class="student-status"><?=$row['status']==='resolved'?'Resolvida':'Aberta'?></span><span class="student-status"><?=$row['visibility']==='private'?'Privada':($row['visibility']==='course'?'Curso':'Turma')?></span><h3><?=h((string)$row['title'])?></h3><p><?=h((string)$row['student_name'])?> · <?=h((string)$row['topic'])?></p></div><strong>Abrir →</strong></a><?php endforeach;?></div><?php endif;?></section><?php endif;?><?php endif;?>
<?php student_shell_end();
