<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';security_headers();student_private_headers();$db=database();$student=student_account_current($db);if(!$student){header('Location: /aluno/login.php?next=%2Faluno%2Fferramentas.php',true,303);exit;}
$tools=student_tools_for_student($db,(int)$student['id']);$byKey=[];foreach($tools as $tool)$byKey[(string)$tool['tool_key']]=$tool;$formulas=student_solution_formulas();$recipeNotes=student_experience_recipe_notes();student_shell_start('Bancada',null,$student);?>
<header class="student-bench-intro"><div><p class="student-kicker">Ferramentas</p><h1 class="student-title">Bancada</h1><p class="student-lead">Ferramentas pequenas ficam aqui, já abertas. Use sem entrar e sair de várias páginas.</p></div></header>
<?php if(!$tools):?><div class="student-empty">Nenhuma ferramenta está disponível para esta conta.</div><?php else:?><div class="student-bench-grid">
<?php if(isset($byKey['reciprocity'])):?><section class="student-bench-tool" id="reciprocidade" data-quick-reciprocity><p class="student-kicker">Exposição</p><h2>Reciprocidade</h2><p>Informe o tempo calculado e veja a correção usada no curso.</p><div class="student-form-grid"><label class="form-field">Tempo calculado<input data-quick-reciprocity-source placeholder="4 s, 02:30 ou 00:00:04"></label><label class="form-field">Tempo corrigido<input data-quick-reciprocity-target readonly></label></div></section><?php endif;?>
<?php if(isset($byKey['exposure'])):?><section class="student-bench-tool" id="exposicao" data-exposure-tool><p class="student-kicker">Exposição</p><h2>Exposição equivalente</h2><div class="student-form-grid"><label class="form-field">Tempo de partida (s)<input type="number" min="0" step="0.001" value="1" data-exposure-time></label><label class="form-field">Abertura inicial<input type="number" min="0.1" step="0.1" value="8" data-exposure-f-start></label><label class="form-field">EI inicial<input type="number" min="1" step="1" value="100" data-exposure-ei-start></label><label class="form-field">Abertura desejada<input type="number" min="0.1" step="0.1" value="8" data-exposure-f-target></label><label class="form-field">EI desejado<input type="number" min="1" step="1" value="100" data-exposure-ei-target></label><label class="form-field">Compensação (EV)<input type="number" step="0.1" value="0" data-exposure-ev></label></div><div class="student-tool-result"><span>Tempo equivalente</span><strong data-exposure-result>1 s</strong><small data-exposure-reciprocity></small></div></section><?php endif;?>
<?php if(isset($byKey['lab_timer'])):?><section class="student-bench-tool is-wide" id="temporizador" data-lab-timer><p class="student-kicker">Processamento</p><h2>Temporizador</h2><div class="student-form-grid student-timer-settings"><label class="form-field">Tempo total<input type="text" value="7:00" inputmode="numeric" data-timer-duration></label><label class="form-field">Aviso de agitação a cada<input type="text" value="1:00" inputmode="numeric" data-timer-interval></label></div><output class="student-timer-display" data-timer-display>07:00</output><p class="student-timer-cue" data-timer-cue aria-live="polite"></p><div class="student-actions"><button class="button button-primary" type="button" data-timer-start>Iniciar</button><button class="button button-secondary" type="button" data-timer-pause>Pausar</button><button class="button button-secondary" type="button" data-timer-reset>Reiniciar</button></div></section><?php endif;?>
<?php if(isset($byKey['solution_prep'])):?><section class="student-bench-tool is-wide" id="receitas" data-solution-tool><p class="student-kicker">Química</p><h2>Receitas e preparo</h2><p>Quantidades, modo de preparo e origem ficam juntos. Ajuste o volume e a ficha inteira acompanha.</p><div class="student-form-grid"><label class="form-field">Receita<select data-solution-select><?php foreach($formulas as $key=>$formula):?><option value="<?=h($key)?>"><?=h((string)$formula['label'])?></option><?php endforeach;?></select></label><label class="form-field">Volume desejado (ml)<input type="number" min="1" step="1" value="250" data-solution-volume></label></div>
<?php foreach($formulas as $key=>$formula):$note=$recipeNotes[$key]??null;?><article class="student-solution-formula" data-solution-formula="<?=h($key)?>" data-base-volume="<?=h((string)$formula['base_volume'])?>"<?=$key!==array_key_first($formulas)?' hidden':''?>><div class="student-record-context"><h3><?=h((string)$formula['label'])?></h3><?php if(!empty($formula['fresh'])):?><span class="student-status">Uso imediato</span><?php endif;?></div><div class="student-solution-ingredients"><?php foreach($formula['ingredients'] as $ingredient):?><div><span><?=h((string)$ingredient['name'])?></span><strong data-solution-amount="<?=h((string)$ingredient['amount'])?>" data-unit="<?=h((string)$ingredient['unit'])?>"><?=h((string)$ingredient['amount'].' '.$ingredient['unit'])?></strong></div><?php endforeach;?></div><?php if($note):?><div class="student-recipe-preparation"><strong>Modo de preparo</strong><p><?=h((string)$note['preparation'])?></p><?php if(!empty($note['warning'])):?><p><strong>Segurança:</strong> <?=h((string)$note['warning'])?></p><?php endif;?><small><?=h((string)$note['source'])?></small></div><?php endif;?></article><?php endforeach;?>
<div class="student-recipe-preparation"><strong>Referências clássicas de branqueamento</strong><p>Kodak R-9 e o processo de reversão da Ilford são referências úteis para estudar fórmulas com dicromato ou permanganato. Elas ficam como referência externa, não como adaptação automática de reagentes: concentração e substituições precisam ser verificadas na fonte antes do preparo.</p><div class="student-actions"><a class="button button-secondary button-compact" href="https://www.ilfordphoto.com/reversal-processing/" target="_blank" rel="noopener">Ilford · Reversal Processing</a><a class="button button-secondary button-compact" href="https://gmo.lme.usp.br/sensors/ti2525.pdf" target="_blank" rel="noopener">Kodak R-9 · referência</a></div></div></section><?php endif;?>
<section class="student-bench-tool is-wide"><p class="student-kicker">Organizar</p><h2>Dados do laboratório</h2><div class="student-toolbox-links"><?php if(isset($byKey['lab_inventory'])):?><a href="/aluno/inventario.php"><span>Inventário</span><span>→</span></a><?php endif;?><?php if(isset($byKey['calibration'])):?><a href="/aluno/calibracao.php"><span>Calibrações</span><span>→</span></a><?php endif;?><a href="/aluno/preparos.php"><span>Preparos salvos</span><span>→</span></a></div></section>
</div><?php endif;?>
<?php student_shell_end();
