<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
security_headers();student_private_headers();
$db=database();$student=student_account_current($db);$next='/aluno/processamentos.php';
if(!$student){header('Location: /aluno/login.php?next='.rawurlencode($next),true,303);exit;}
$studentId=(int)$student['id'];student_tool_require($db,$studentId,'lab_timer');
$testId=(int)($_GET['test']??$_POST['test_id']??0);$test=$testId>0?student_test_for_student($db,$testId,$studentId):null;if($testId>0&&!$test){http_response_code(404);student_shell_start('Registro não encontrado',null,$student);?><div class="student-empty">Registro não encontrado.</div><?php student_shell_end();exit;}
$id=(int)($_GET['id']??$_POST['template_id']??0);$error='';$notice=(string)($_SESSION['student_process_template_notice']??'');unset($_SESSION['student_process_template_notice']);
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('student-process-templates',$_POST['_csrf']??null))$error='Solicitação inválida.';
    else try{
        $action=(string)($_POST['action']??'');
        if($action==='create'){$template=student_process_template_create($db,$studentId,$_POST);$id=(int)$template['id'];$_SESSION['student_process_template_notice']='Processamento criado.';}
        elseif($action==='copy_standard'){
            $template=student_process_standard_copy($db,$studentId,(string)($_POST['standard_key']??''),(string)($_POST['developer_key']??'parodinal'));$id=(int)$template['id'];$_SESSION['student_process_template_notice']='Processamento padrão adicionado.';
            if($testId>0){student_process_plan_apply_template($db,$id,$testId,$studentId);header('Location: /aluno/processar.php?test='.$testId,true,303);exit;}
        }
        elseif($action==='save'){$id=(int)($_POST['template_id']??0);student_process_template_update($db,$id,$studentId,$_POST);$_SESSION['student_process_template_notice']='Processamento salvo.';}
        elseif($action==='add_step'){$id=(int)($_POST['template_id']??0);student_process_template_add_step($db,$id,$studentId,$_POST);$_SESSION['student_process_template_notice']='Etapa adicionada.';}
        elseif($action==='delete_step'){$id=(int)($_POST['template_id']??0);student_process_template_delete_step($db,$id,(int)($_POST['step_id']??0),$studentId);$_SESSION['student_process_template_notice']='Etapa removida.';}
        elseif($action==='move_step'){$id=(int)($_POST['template_id']??0);student_process_template_move_step($db,$id,(int)($_POST['step_id']??0),$studentId,(int)($_POST['direction']??1));$_SESSION['student_process_template_notice']='Ordem atualizada.';}
        elseif($action==='delete'){$deleteId=(int)($_POST['template_id']??0);student_process_template_delete($db,$deleteId,$studentId);$id=0;$_SESSION['student_process_template_notice']='Processamento removido.';}
        elseif($action==='apply_template'){
            $id=(int)($_POST['template_id']??0);if($testId<1)throw new RuntimeException('Escolha um registro do Caderno.');student_process_plan_apply_template($db,$id,$testId,$studentId);header('Location: /aluno/processar.php?test='.$testId,true,303);exit;
        }else throw new RuntimeException('Ação inválida.');
        $url='/aluno/processamentos.php'.($id>0?'?id='.$id:'');if($testId>0)$url.=($id>0?'&':'?').'test='.$testId;header('Location: '.$url,true,303);exit;
    }catch(Throwable $e){$error=$e->getMessage();}
}
$templates=student_process_templates($db,$studentId);$template=$id>0?student_process_template_for_student($db,$id,$studentId):null;if($id>0&&!$template){$id=0;$error=$error?:'Processamento não encontrado.';}
$steps=$template?student_process_template_steps($db,(int)$template['id']):[];$catalog=student_process_stage_catalog();$developers=student_process_developer_catalog();$preparations=student_saved_preparations($db,$studentId);$standards=student_process_standard_catalog();$standardDevelopers=student_process_standard_developers();$csrf=csrf_token('student-process-templates');
student_shell_start('Processamentos',null,$student);?>
<header class="student-page-heading student-process-library-heading"><div><p class="student-kicker">Laboratório</p><h1 class="student-title">Processamentos</h1><?php if($test):?><p class="student-process-context">Para o registro <strong><?=h((string)$test['title'])?></strong>.</p><?php else:?><p class="student-process-context">Monte uma sequência uma vez e use no Caderno ou diretamente no modo laboratório.</p><?php endif;?></div><?php if($template):?><a class="button button-secondary" href="/aluno/processamentos.php<?=$testId>0?'?test='.$testId:''?>">← Todos</a><?php endif;?></header>
<?php if($notice!==''):?><p class="ui-alert ui-alert-notice"><?=h($notice)?></p><?php endif;?><?php if($error!==''):?><p class="ui-alert ui-alert-error" role="alert"><?=h($error)?></p><?php endif;?>

<?php if(!$template):?>
<section class="student-process-standards" aria-labelledby="student-process-standards-title"><div class="student-process-standard-heading"><p class="student-kicker">Padrões do workshop</p><h2 class="student-subtitle" id="student-process-standards-title">Começar por um processo pronto</h2><p>Escolha a rota de branqueamento e o revelador. Os tempos que dependem da imagem continuam livres.</p></div><div class="student-process-library"><?php foreach($standards as $standardKey=>$standard):?><article class="student-process-template-card"><div class="student-process-template-main"><span class="student-process-step-number"><?=str_pad((string)count((array)$standard['steps']),2,'0',STR_PAD_LEFT)?></span><div><h2><?=h((string)$standard['name'])?></h2><p><?=h((string)$standard['description'])?></p></div><strong><?=h(student_process_standard_duration_summary((array)$standard['steps']))?></strong></div><form method="post" class="student-process-template-actions student-process-standard-actions"><input type="hidden" name="_csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="copy_standard"><input type="hidden" name="standard_key" value="<?=h((string)$standardKey)?>"><input type="hidden" name="test_id" value="<?=$testId?>"><label class="form-field">Revelador<select name="developer_key"><?php foreach($standardDevelopers as $developerKey=>$developer):?><option value="<?=h((string)$developerKey)?>"><?=h((string)$developer['label'])?></option><?php endforeach;?></select></label><button class="button button-primary button-compact" type="submit"><?=$testId>0?'Usar neste registro':'Adicionar aos meus'?></button></form></article><?php endforeach;?></div></section>
<section class="student-process-create"><div><p class="student-kicker">Novo roteiro</p><h2 class="student-subtitle">Criar processamento</h2></div><form method="post" class="student-form-grid"><input type="hidden" name="_csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="create"><input type="hidden" name="test_id" value="<?=$testId?>"><label class="form-field student-span-2">Nome<input name="name" required maxlength="160" placeholder="Ex.: Positivo direto — FeCl₃ + amônia"></label><label class="form-field student-span-2">Descrição<textarea name="description" rows="2" maxlength="1000" placeholder="Opcional"></textarea></label><div class="student-actions student-span-2"><button class="button button-primary" type="submit">Criar processamento</button></div></form></section>
<section class="student-process-library" aria-label="Processamentos salvos">
<?php if(!$templates):?><div class="student-empty">Você ainda não salvou nenhum processamento.</div><?php else:foreach($templates as $item):$href='/aluno/processamentos.php?id='.(int)$item['id'].($testId>0?'&amp;test='.$testId:'');?><article class="student-process-template-card"><a class="student-process-template-main" href="<?=$href?>"><span class="student-process-step-number"><?=str_pad((string)(int)$item['step_count'],2,'0',STR_PAD_LEFT)?></span><div><h2><?=h((string)$item['name'])?></h2><p><?=h((string)($item['description']!==''?$item['description']:'Sem descrição.'))?></p></div><strong><?=h(student_process_template_duration_summary($db,(int)$item['id']))?></strong></a><div class="student-process-template-actions"><?php if($testId>0):?><form method="post"><input type="hidden" name="_csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="apply_template"><input type="hidden" name="template_id" value="<?=(int)$item['id']?>"><input type="hidden" name="test_id" value="<?=$testId?>"><button class="button button-primary button-compact" type="submit"<?=(int)$item['step_count']<1?' disabled':''?>>Usar neste registro</button></form><?php else:?><a class="button button-primary button-compact" href="/aluno/processar.php?template=<?=(int)$item['id']?>"<?=(int)$item['step_count']<1?' aria-disabled="true"':''?>>Iniciar</a><?php endif;?><a class="button button-secondary button-compact" href="<?=$href?>">Editar</a></div></article><?php endforeach;endif;?>
</section>
<?php else:?>
<section class="student-process-editor">
<form method="post" class="student-form-grid student-process-meta"><input type="hidden" name="_csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="save"><input type="hidden" name="template_id" value="<?=(int)$template['id']?>"><input type="hidden" name="test_id" value="<?=$testId?>"><label class="form-field student-span-2">Nome<input name="name" required maxlength="160" value="<?=h((string)$template['name'])?>"></label><label class="form-field student-span-2">Descrição<textarea name="description" rows="2" maxlength="1000"><?=h((string)$template['description'])?></textarea></label><div class="student-actions student-span-2"><button class="button button-secondary" type="submit">Salvar dados</button><?php if($steps):?><?php if($testId>0):?><button class="button button-primary" type="submit" name="action" value="apply_template">Usar neste registro</button><?php else:?><a class="button button-primary" href="/aluno/processar.php?template=<?=(int)$template['id']?>">Iniciar processamento</a><?php endif;?><?php endif;?></div></form>
<div class="student-process-editor-heading"><div><p class="student-kicker">Roteiro</p><h2 class="student-subtitle"><?=count($steps)?> <?=count($steps)===1?'etapa':'etapas'?></h2></div><strong><?=h(student_process_template_duration_summary($db,(int)$template['id']))?></strong></div>
<?php if(!$steps):?><div class="student-empty">Adicione a primeira etapa.</div><?php else:?><ol class="student-process-step-list"><?php foreach($steps as $index=>$step):$payload=student_process_json_array((string)$step['payload_json']);?><li class="student-process-step-card"><span class="student-process-step-index"><?=str_pad((string)($index+1),2,'0',STR_PAD_LEFT)?></span><div class="student-process-step-body"><h3><?=h((string)$step['label'])?></h3><p><?php $bits=[];if((string)($payload['developer_name']??'')!=='')$bits[]=(string)$payload['developer_name'];if((string)($payload['temperature']??'')!=='')$bits[]=(string)$payload['temperature'];if((string)$step['duration']!=='')$bits[]='Tempo '.(string)$step['duration'];if((string)$step['agitation_interval']!=='')$bits[]='Aviso '.(string)$step['agitation_interval'];echo h($bits?implode(' · ',$bits):'Sem temporização.');?></p></div><div class="student-process-step-actions"><?php if($index>0):?><form method="post"><input type="hidden" name="_csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="move_step"><input type="hidden" name="template_id" value="<?=(int)$template['id']?>"><input type="hidden" name="test_id" value="<?=$testId?>"><input type="hidden" name="step_id" value="<?=(int)$step['id']?>"><input type="hidden" name="direction" value="-1"><button class="student-link" type="submit" aria-label="Mover etapa para cima">↑</button></form><?php endif;?><?php if($index<count($steps)-1):?><form method="post"><input type="hidden" name="_csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="move_step"><input type="hidden" name="template_id" value="<?=(int)$template['id']?>"><input type="hidden" name="test_id" value="<?=$testId?>"><input type="hidden" name="step_id" value="<?=(int)$step['id']?>"><input type="hidden" name="direction" value="1"><button class="student-link" type="submit" aria-label="Mover etapa para baixo">↓</button></form><?php endif;?><form method="post" onsubmit="return confirm('Remover esta etapa?')"><input type="hidden" name="_csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="delete_step"><input type="hidden" name="template_id" value="<?=(int)$template['id']?>"><input type="hidden" name="test_id" value="<?=$testId?>"><input type="hidden" name="step_id" value="<?=(int)$step['id']?>"><button class="student-link" type="submit">Remover</button></form></div></li><?php endforeach;?></ol><?php endif;?>

<details class="student-process-add" open><summary>Adicionar etapa</summary><form method="post" class="student-form-grid" data-process-template-step-form><input type="hidden" name="_csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="add_step"><input type="hidden" name="template_id" value="<?=(int)$template['id']?>"><input type="hidden" name="test_id" value="<?=$testId?>"><label class="form-field student-span-2">Etapa<select name="stage_key" data-process-template-stage><?php foreach($catalog as $key=>$stage):?><option value="<?=h($key)?>"><?=h((string)$stage['label'])?></option><?php endforeach;?></select></label><label class="form-field student-span-2" data-process-template-custom hidden>Nome da etapa<input name="custom_label" maxlength="120"></label><div class="student-span-2 student-form-grid" data-process-template-development><label class="form-field">Revelador<select name="developer_key"><?php foreach($developers as $key=>$developer):?><option value="<?=h($key)?>"><?=h((string)$developer['label'])?></option><?php endforeach;?></select></label><label class="form-field">Predefinição de revelação<select name="saved_preparation_id"><option value="">Nenhuma</option><?php foreach($preparations as $prep):?><option value="<?=(int)$prep['id']?>"><?=h((string)$prep['label'])?></option><?php endforeach;?></select></label><label class="form-field">Revelador ou solução estoque (ml)<input type="number" min="0" step="0.1" name="developer_amount"></label><label class="form-field">Água (ml)<input type="number" min="0" step="0.1" name="water_amount"></label><label class="form-field student-span-2">Outro revelador<input name="developer_name"></label></div><label class="form-field">Tempo<input name="duration" placeholder="7:00"></label><label class="form-field">Aviso de agitação<input name="agitation_interval" placeholder="1:00"></label><label class="form-field">Temperatura<input name="temperature" placeholder="26 °C"></label><label class="form-field">Agitação<input name="agitation" placeholder="Descrição opcional"></label><label class="form-field student-span-2">Anotações<textarea name="notes" rows="2" maxlength="3000"></textarea></label><div class="student-actions student-span-2"><button class="button button-primary" type="submit">Adicionar etapa</button></div></form></details>
<form method="post" class="student-process-delete" onsubmit="return confirm('Excluir este processamento salvo?')"><input type="hidden" name="_csrf" value="<?=h($csrf)?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="template_id" value="<?=(int)$template['id']?>"><input type="hidden" name="test_id" value="<?=$testId?>"><button class="student-link" type="submit">Excluir processamento</button></form>
</section>
<?php endif;?>
<?php student_shell_end();
