<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
security_headers();student_private_headers();
$db=database();student_account_reconcile_confirmed_registrations($db);$student=student_account_current($db);
$id=(int)($_GET['id']??$_POST['id']??0);$view=(string)($_GET['view']??$_POST['view']??'exposure');if(!in_array($view,['exposure','process','review'],true))$view='exposure';
$next='/aluno/teste.php?id='.$id.'&view='.rawurlencode($view);if(!$student){header('Location: /aluno/login.php?next='.rawurlencode($next),true,303);exit;}$studentId=(int)$student['id'];$record=student_test_for_student($db,$id,$studentId);
if(!$record){http_response_code(404);student_shell_start('Registro não encontrado',null,$student);?><div class="student-empty">Registro não encontrado.</div><?php student_shell_end();exit;}
$error='';$contextScope=(string)($record['context_scope']??'course');
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'){
    if(!verify_csrf('student-process-'.$id,$_POST['_csrf']??null))$error='Solicitação inválida.';
    else try{
        $action=(string)($_POST['action']??'');
        if($action==='save_exposure'){student_test_update_exposure($db,$id,$studentId,$_POST);$view='process';$_SESSION['student_process_notice']='Exposição salva. Agora registre o processamento.';}
        elseif($action==='add_step'){
            $stageKey=(string)($_POST['stage_key']??'');student_process_add_guided_step($db,$id,$studentId,$_POST);
            if($stageKey==='dry'){$view='review';$_SESSION['student_process_notice']='Secagem registrada. O processamento terminou; registre agora o resultado.';}
            else{$view='process';$_SESSION['student_process_notice']='Etapa registrada.';}
        }
        elseif($action==='delete_step'){student_process_delete_from_step($db,$id,(int)($_POST['step_id']??0),$studentId);$view='process';$_SESSION['student_process_notice']='Última etapa desfeita.';}
        elseif($action==='save_result'){$notes=student_workspace_text($_POST['notes']??'',4000);$db->prepare('UPDATE student_tests SET notes=?,updated_at=? WHERE id=? AND student_id=?')->execute([$notes,utc_now(),$id,$studentId]);$view='review';$_SESSION['student_process_notice']='Resultado salvo.';}
        elseif($action==='upload'){
            $phase=(string)($_POST['phase']??'result');
            if($phase==='scene')student_test_update_exposure($db,$id,$studentId,$_POST);
            else{$notes=student_workspace_text($_POST['notes']??'',4000);$db->prepare('UPDATE student_tests SET notes=?,updated_at=? WHERE id=? AND student_id=?')->execute([$notes,utc_now(),$id,$studentId]);}
            $file=$_FILES['image']??null;if(!is_array($file))throw new RuntimeException('Selecione uma imagem.');student_test_add_media_phase($db,$id,$studentId,$file,$phase);$view=$phase==='scene'?'exposure':'review';$_SESSION['student_process_notice']='Imagem adicionada.';
        }
        elseif($action==='delete_media'){student_test_delete_media($db,(int)($_POST['media_id']??0),$studentId);$view=(string)($_POST['phase']??'result')==='scene'?'exposure':'review';$_SESSION['student_process_notice']='Imagem removida.';}
        elseif($action==='submit'){if($contextScope!=='course')throw new RuntimeException('Registros pessoais não são enviados para avaliação.');student_test_submit($db,$id,$studentId);$view='review';$_SESSION['student_process_notice']='Registro enviado para avaliação.';}
        elseif($action==='message'){student_test_add_student_message($db,$id,$studentId,(string)($_POST['message']??''));$view='review';$_SESSION['student_process_notice']='Mensagem enviada.';}
        else throw new RuntimeException('Ação inválida.');
        header('Location: /aluno/teste.php?id='.$id.'&view='.$view,true,303);exit;
    }catch(Throwable $e){$error=$e->getMessage();}
}
$record=student_test_for_student($db,$id,$studentId)??$record;$steps=student_process_steps($db,$id);$complete=student_experience_process_complete($steps);$nextChoices=student_experience_next_choices($steps);$media=student_test_media($db,$id);$sceneMedia=student_test_media_by_phase($media,'scene');$resultMedia=student_test_media_by_phase($media,'result');$inventory=student_inventory_items($db,$studentId);$preparations=student_saved_preparations($db,$studentId);$messages=student_test_messages($db,$id);$notice=(string)($_SESSION['student_process_notice']??'');unset($_SESSION['student_process_notice']);$locked=(string)$record['status']==='reviewed';$developers=student_process_developer_catalog();$lastStep=$steps?($steps[array_key_last($steps)]??null):null;$resultReady=$complete||$locked||$resultMedia||trim((string)$record['notes'])!==''||in_array((string)$record['status'],['submitted','needs_revision','reviewed'],true);
student_shell_start((string)$record['title'].' · Caderno',null,$student);?>
<header class="student-record-header"><div class="student-record-context"><a class="student-back" href="/aluno/caderno.php">← Caderno</a><span class="student-status student-status-<?=h((string)$record['status'])?>"><?=h(student_test_status_label((string)$record['status']))?></span></div><p class="student-kicker"><?=$contextScope==='personal'?'Registro pessoal':h((string)$record['public_title'].' · '.$record['cohort_title'])?></p><h1 class="student-title student-title-record"><?=h((string)$record['title'])?></h1></header>
<?php if($notice!==''):?><p class="ui-alert ui-alert-notice"><?=h($notice)?></p><?php endif;?><?php if($error!==''):?><p class="ui-alert ui-alert-error" role="alert"><?=h($error)?></p><?php endif;?>
<nav class="student-step-nav" aria-label="Partes do registro"><a href="/aluno/teste.php?id=<?=$id?>&amp;view=exposure"<?=$view==='exposure'?' aria-current="step"':''?>><span>01</span><strong>Exposição</strong></a><a href="/aluno/teste.php?id=<?=$id?>&amp;view=process"<?=$view==='process'?' aria-current="step"':''?>><span>02</span><strong>Processamento</strong></a><a href="<?=$resultReady?'/aluno/teste.php?id='.$id.'&amp;view=review':'#'?>"<?=$view==='review'?' aria-current="step"':''?><?=$resultReady?'':' aria-disabled="true"'?>> <span>03</span><strong>Resultado</strong></a></nav>

<?php if($view==='exposure'):?>
<section class="student-workflow-panel"><div class="student-section-heading"><div><p class="student-kicker">01 · Exposição</p><h2 class="student-subtitle">Registre a fotografia</h2></div><p>Preencha o que realmente interessa para repetir ou comparar depois. O restante é opcional.</p></div>
<form method="post" enctype="multipart/form-data" class="student-mobile-form" data-ui-validate><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-process-'.$id))?>"><input type="hidden" name="id" value="<?=$id?>"><input type="hidden" name="view" value="exposure"><input type="hidden" name="phase" value="scene"><input type="hidden" name="action" value="save_exposure" data-process-action>
<div class="student-capture-block"><div><span class="student-capture-number">A</span><div><h3>Cena</h3><p>Opcional, apenas se ajudar a lembrar a situação.</p></div></div><?php if(!$locked&&count($media)<STUDENT_TEST_MEDIA_MAX_FILES):?><label class="button button-secondary student-capture-button">Fotografar ou anexar<input type="file" name="image" accept="image/jpeg,image/png,image/webp" capture="environment" onchange="this.form.querySelector('[data-process-action]').value='upload';this.form.submit()"></label><?php endif;?></div>
<?php if($sceneMedia):?><div class="student-media-strip"><?php foreach($sceneMedia as $item):?><figure class="student-media-card"><img src="/aluno/teste-media.php?id=<?=(int)$item['id']?>" alt="Cena registrada" loading="lazy"><?php if(!$locked):?><figcaption><button class="student-link" type="submit" name="media_id" value="<?=(int)$item['id']?>" onclick="this.form.querySelector('[data-process-action]').value='delete_media'">Remover</button></figcaption><?php endif;?></figure><?php endforeach;?></div><?php endif;?>
<div class="student-form-grid"><label class="form-field student-span-2">Título<input name="title" value="<?=h((string)$record['title'])?>" required maxlength="180"<?=$locked?' disabled':''?>></label><label class="form-field">Data<input type="date" name="test_date" value="<?=h((string)($record['test_date']??''))?>"<?=$locked?' disabled':''?>></label><label class="form-field">Filme<input name="film" value="<?=h((string)$record['film'])?>"<?=$locked?' disabled':''?>></label><label class="form-field">EI / ISO<input name="iso_reference" value="<?=h((string)$record['iso_reference'])?>"<?=$locked?' disabled':''?>></label><label class="form-field">Diafragma<input name="aperture" value="<?=h((string)$record['aperture'])?>" placeholder="f/64"<?=$locked?' disabled':''?>></label><label class="form-field">Tempo medido / calculado<input name="calculated_time" value="<?=h((string)$record['calculated_time'])?>" data-reciprocity-source<?=$locked?' disabled':''?>></label><label class="form-field">Com reciprocidade<input name="reciprocity_time" value="<?=h((string)$record['reciprocity_time'])?>" data-reciprocity-target readonly></label><details class="student-optional-fields student-span-2"><summary>Dados opcionais</summary><div class="student-form-grid"><label class="form-field">Lote<input name="lot" value="<?=h((string)$record['lot'])?>"<?=$locked?' disabled':''?>></label><label class="form-field student-span-2">Condição da luz<textarea name="light_condition" rows="2"<?=$locked?' disabled':''?>><?=h((string)$record['light_condition'])?></textarea></label><label class="form-field student-span-2">Faixa tonal / intenção<textarea name="tonal_range" rows="2"<?=$locked?' disabled':''?>><?=h((string)$record['tonal_range'])?></textarea></label></div></details></div>
<?php if(!$locked):?><div class="student-sticky-action"><button class="button button-primary" type="submit">Salvar e ir para processamento →</button></div><?php endif;?></form></section>

<?php elseif($view==='process'):?>
<section class="student-workflow-panel"><div class="student-section-heading"><div><p class="student-kicker">02 · Processamento</p><h2 class="student-subtitle">O que você faz agora</h2></div><p>O histórico fica abaixo. Aqui o foco é somente a etapa atual.</p></div>
<?php if($complete):?>
<div class="student-process-complete"><p class="student-process-now-label">Processamento concluído</p><h2>Secagem concluída.</h2><p>Não há próxima etapa de processamento. A fotografia já pode seguir para o resultado.</p><a class="button button-primary" href="/aluno/teste.php?id=<?=$id?>&amp;view=review">Registrar resultado →</a></div>
<?php elseif(!$locked):?>
<div class="student-process-now"><p class="student-process-now-label"><?=$steps?'Próxima etapa':'Primeira etapa'?></p><h2><?=h((string)(($nextChoices[array_key_first($nextChoices)]['label']??'Escolha o próximo passo')))?></h2><p>Escolha a etapa, registre apenas os dados que usou e siga adiante.</p></div>
<form method="post" class="student-process-step-form" data-process-step-form><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-process-'.$id))?>"><input type="hidden" name="action" value="add_step">
<fieldset class="choice-field"><legend>Etapa</legend><div class="choice-row student-process-choice-row"><?php foreach($nextChoices as $key=>$choice):?><label class="choice-option"><input type="radio" name="stage_key" value="<?=h($key)?>"<?=$key===array_key_first($nextChoices)?' checked':''?> data-stage-choice><span><?=h((string)$choice['label'])?></span></label><?php endforeach;?></div></fieldset>
<div data-stage-fields="development" class="student-process-stage-fields"><div class="student-form-grid"><label class="form-field student-span-2">Revelador<select name="developer_key" data-developer-select><?php foreach($developers as $key=>$developer):?><option value="<?=h($key)?>" data-preparation-mode="<?=h((string)$developer['mode'])?>"><?=h((string)$developer['label'])?></option><?php endforeach;?></select></label><label class="form-field student-span-2" data-custom-developer hidden>Nome do revelador<input name="developer_name"></label><label class="form-field student-span-2">Preparo salvo<select name="saved_preparation_id" data-saved-preparation><option value="">Nenhum</option><?php foreach($preparations as $prep):?><option value="<?=(int)$prep['id']?>" data-developer-key="<?=h((string)$prep['developer_key'])?>" data-mode="<?=h((string)$prep['preparation_mode'])?>" data-developer-amount="<?=h((string)$prep['developer_amount'])?>" data-water-amount="<?=h((string)$prep['water_amount'])?>" data-temperature="<?=h((string)$prep['temperature'])?>" data-duration="<?=h((string)$prep['duration'])?>" data-agitation="<?=h((string)$prep['agitation'])?>"><?=h((string)$prep['label'])?></option><?php endforeach;?></select></label><div class="student-span-2 student-developer-mix" data-developer-mix><label class="form-field">Revelador / solução estoque (ml)<input type="number" min="0" step="0.1" name="developer_amount" data-developer-amount></label><label class="form-field">Água (ml)<input type="number" min="0" step="0.1" name="water_amount" data-water-amount></label><output class="student-dilution-output student-span-2" data-dilution-output></output></div><label class="form-field student-span-2" data-fresh-volume hidden>Volume preparado/usado (ml)<input type="number" min="0" step="0.1" name="fresh_volume" data-fresh-volume-input></label><?=student_process_inventory_select_html($inventory,'Usar item do inventário')?><label class="form-field">Temperatura<input name="temperature" placeholder="26 °C"></label><label class="form-field">Tempo<input name="duration" placeholder="7 min" data-development-duration></label><label class="form-field student-span-2">Agitação<input name="agitation"></label></div></div>
<div data-stage-fields="simple" class="student-process-stage-fields"><div class="student-form-grid"><label class="form-field">Tempo<input name="duration_simple"></label><?=student_process_inventory_select_html($inventory,'Usar item do inventário',true)?><label class="form-field">Quantidade utilizada<input type="number" min="0" step="0.1" name="inventory_amount_simple"></label></div></div>
<div data-stage-fields="custom" class="student-process-stage-fields"><div class="student-form-grid"><label class="form-field student-span-2">Nome da etapa<input name="custom_label"></label><label class="form-field">Tempo<input name="duration_custom"></label></div></div>
<input type="hidden" data-stage-duration><input type="hidden" data-stage-inventory-item><input type="hidden" data-stage-inventory-amount><details class="student-optional-fields"><summary>Anotações da etapa</summary><label class="form-field"><textarea name="notes" rows="3" maxlength="3000"></textarea></label></details>
<section class="student-context-timer" data-lab-timer><p class="student-kicker">Cronômetro</p><div class="student-form-grid student-timer-settings"><label class="form-field">Tempo total<input type="text" value="7:00" inputmode="numeric" data-timer-duration></label><label class="form-field">Aviso de agitação a cada<input type="text" value="1:00" inputmode="numeric" data-timer-interval></label></div><output class="student-timer-display" data-timer-display>07:00</output><p class="student-timer-cue" data-timer-cue aria-live="polite"></p><div class="student-actions"><button class="button button-secondary" type="button" data-timer-start>Iniciar</button><button class="button button-secondary" type="button" data-timer-pause>Pausar</button><button class="button button-secondary" type="button" data-timer-reset>Reiniciar</button></div></section>
<div class="student-sticky-action"><button class="button button-primary" type="submit"><?=array_key_exists('dry',$nextChoices)?'Registrar secagem e ir ao resultado →':'Registrar etapa →'?></button></div></form>
<?php endif;?>
<?php if($steps):?><details class="student-process-history"><summary>Histórico do processamento · <?=h(student_experience_count(count($steps),'etapa','etapas'))?></summary><ol class="student-process-summary"><?php foreach($steps as $step):$detail=[];if($step['calculated_dilution']!=='')$detail[]=$step['calculated_dilution'];if($step['temperature']!=='')$detail[]=$step['temperature'];if($step['duration']!=='')$detail[]=$step['duration'];$stepName=$step['chemical_name']!==''?$step['chemical_name']:$step['label'];?><li><div><span class="student-process-step-number"><?=str_pad((string)$step['position'],2,'0',STR_PAD_LEFT)?></span><strong><?=h((string)$stepName)?></strong><?php if($detail):?><small><?=h(implode(' · ',$detail))?></small><?php endif;?><?php if($step['notes']!==''):?><p><?=h((string)$step['notes'])?></p><?php endif;?></div></li><?php endforeach;?></ol><?php if(!$locked&&$lastStep):?><div class="student-process-history-actions"><form method="post" onsubmit="return confirm('Desfazer somente a última etapa registrada?')"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-process-'.$id))?>"><input type="hidden" name="action" value="delete_step"><input type="hidden" name="step_id" value="<?=(int)$lastStep['id']?>"><button class="button button-secondary button-compact" type="submit">Desfazer última etapa</button></form></div><?php endif;?></details><?php endif;?></section>

<?php else:?>
<section class="student-workflow-panel"><div class="student-section-heading"><div><p class="student-kicker">03 · Resultado</p><h2 class="student-subtitle">Registre o que saiu do processo</h2></div><p>Fotografe a chapa, anote o que importa e, se este registro pertence ao curso, envie para avaliação quando estiver pronto.</p></div>
<div class="student-result-flow"><form method="post" enctype="multipart/form-data" class="student-mobile-form"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-process-'.$id))?>"><input type="hidden" name="phase" value="result"><input type="hidden" name="action" value="save_result" data-process-action><div class="student-capture-block"><div><span class="student-capture-number">B</span><div><h3>Imagem do resultado</h3><p>Fotografe ou anexe a chapa processada.</p></div></div><?php if(!$locked&&count($media)<STUDENT_TEST_MEDIA_MAX_FILES):?><label class="button button-secondary student-capture-button">Fotografar ou anexar<input type="file" name="image" accept="image/jpeg,image/png,image/webp" capture="environment" onchange="this.form.querySelector('[data-process-action]').value='upload';this.form.submit()"></label><?php endif;?></div><?php if($resultMedia):?><div class="student-media-strip"><?php foreach($resultMedia as $item):?><figure class="student-media-card"><img src="/aluno/teste-media.php?id=<?=(int)$item['id']?>" alt="Resultado" loading="lazy"><?php if(!$locked):?><figcaption><button class="student-link" type="submit" name="media_id" value="<?=(int)$item['id']?>" onclick="this.form.querySelector('[data-process-action]').value='delete_media'">Remover</button></figcaption><?php endif;?></figure><?php endforeach;?></div><?php endif;?><label class="form-field">Anotações sobre o resultado<textarea name="notes" rows="5"<?=$locked?' disabled':''?>><?=h((string)$record['notes'])?></textarea></label><?php if(!$locked):?><div class="student-result-actions"><button class="button button-primary" type="submit">Salvar resultado</button></div><?php endif;?></form>
<?php if($contextScope==='course'):?><section class="student-review-thread"><p class="student-kicker">Curso</p><h3>Avaliação</h3><?php if(!$locked&&$record['status']!=='submitted'):?><form method="post"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-process-'.$id))?>"><input type="hidden" name="action" value="submit"><button class="button button-primary" type="submit">Enviar para avaliação</button></form><?php else:?><p>Este registro já foi enviado ou revisado.</p><?php endif;?><details class="student-optional-fields"<?=$messages?' open':''?>><summary>Conversa sobre este registro<?=$messages?' · '.count($messages):''?></summary><?php if($messages):?><div class="student-message-list"><?php foreach($messages as $message):?><article><strong><?=$message['author_role']==='admin'?'Professor':'Você'?></strong><p><?=nl2br(h((string)$message['body']))?></p><small><?=h(student_test_message_date((string)$message['created_at']))?></small></article><?php endforeach;?></div><?php endif;?><form method="post" class="student-form-grid"><input type="hidden" name="_csrf" value="<?=h(csrf_token('student-process-'.$id))?>"><input type="hidden" name="action" value="message"><label class="form-field student-span-2">Mensagem<textarea name="message" rows="3"></textarea></label><button class="button button-secondary" type="submit">Enviar mensagem</button></form></details></section><?php endif;?></div></section>
<?php endif;?>
<?php student_shell_end();
function student_process_inventory_select_html(array $inventory,string $label,bool $simple=false): string {if(!$inventory)return '';ob_start();?><label class="form-field student-span-2"<?=$simple?'':' data-developer-inventory'?>><?=h($label)?><select name="<?=$simple?'inventory_item_id_simple':'inventory_item_id'?>"><option value="">Não vincular ao inventário</option><?php foreach($inventory as $item):?><option value="<?=(int)$item['id']?>"><?=h((string)$item['name'])?> · <?=h(student_workbench_number((float)$item['quantity']).' '.$item['unit'])?></option><?php endforeach;?></select></label><?php return (string)ob_get_clean();}
