<?php
declare(strict_types=1);
require __DIR__.'/../app/bootstrap.php';
security_headers();student_private_headers();
$db=database();$student=student_account_current($db);
$id=(int)($_GET['id']??0);$cohortValue=$_GET['cohort']??null;$requestedCohortUuid=is_string($cohortValue)?trim((string)$cohortValue):'';$nextParams=['id'=>$id];if($requestedCohortUuid!=='')$nextParams['cohort']=$requestedCohortUuid;$next='/aluno/teste-compartilhado.php?'.http_build_query($nextParams);
if(!$student){header('Location: /aluno/login.php?next='.rawurlencode($next),true,303);exit;}
$record=student_test_accessible_to_student($db,$id,(int)$student['id']);
if(!$record){http_response_code(404);student_shell_start('Registro não encontrado',null,$student);?><div class="student-empty">Registro não encontrado.</div><?php student_shell_end();exit;}
if((int)$record['student_id']===(int)$student['id']){header('Location: /aluno/teste.php?id='.$id,true,303);exit;}
$activity=activity_by_id($db,(int)$record['activity_id']);$steps=student_process_steps($db,$id);$media=student_test_media($db,$id);$sceneMedia=student_test_media_by_phase($media,'scene');$resultMedia=student_test_media_by_phase($media,'result');$messages=student_test_messages($db,$id);
student_shell_start((string)$record['title'].' · Compartilhado',$activity?:null,$student);?>
<div class="student-appbar"><a class="student-back" href="/aluno/caderno.php">← Caderno de Processos</a><span class="student-status"><?=h(student_test_visibility_label((string)$record['visibility']))?></span></div>
<p class="student-kicker"><?=h((string)($activity['public_title']??''))?><?=!empty($activity)?' · ':''?><?=h((string)$record['student_name'])?> · <?=h((string)$record['cohort_title'])?></p>
<h1 class="student-title student-title-record"><?=h((string)$record['title'])?></h1>
<?php if($steps):?><p class="student-process-path student-process-path-large"><?=h(student_process_path_label($steps))?></p><?php endif;?>
<section class="student-workflow-panel">
  <div class="student-review-grid">
    <article><span>Exposição</span><dl><div><dt>Filme</dt><dd><?=student_review_value($record['film'])?></dd></div><div><dt>Lote</dt><dd><?=student_review_value($record['lot'])?></dd></div><div><dt>EI / ISO</dt><dd><?=student_review_value($record['iso_reference'])?></dd></div><div><dt>Diafragma</dt><dd><?=student_review_value($record['aperture'])?></dd></div><div><dt>Tempo calculado</dt><dd><?=student_review_value($record['calculated_time'])?></dd></div><div><dt>Após reciprocidade</dt><dd><?=student_review_value($record['reciprocity_time'])?></dd></div></dl><?php if(trim((string)$record['light_condition'])!==''):?><p><?=nl2br(h((string)$record['light_condition']))?></p><?php endif;?><?php if(trim((string)$record['tonal_range'])!==''):?><p><?=nl2br(h((string)$record['tonal_range']))?></p><?php endif;?></article>
    <article><span>Processamento</span><?php if($steps):?><ol class="student-process-summary student-process-summary-compact"><?php foreach($steps as $step):$detail=[];if((string)$step['calculated_dilution']!=='')$detail[]=(string)$step['calculated_dilution'];if((string)$step['temperature']!=='')$detail[]=(string)$step['temperature'];if((string)$step['duration']!=='')$detail[]=(string)$step['duration'];$name=(string)$step['chemical_name']!==''?(string)$step['chemical_name']:(string)$step['label'];?><li><div><span class="student-process-step-number"><?=str_pad((string)$step['position'],2,'0',STR_PAD_LEFT)?></span><strong><?=h($name)?></strong><?php if($detail):?><small><?=h(implode(' · ',$detail))?></small><?php endif;?><?php if((string)$step['notes']!==''):?><p><?=nl2br(h((string)$step['notes']))?></p><?php endif;?></div></li><?php endforeach;?></ol><?php else:?><dl><div><dt>Revelador</dt><dd><?=student_review_value($record['developer'])?></dd></div><div><dt>Diluição</dt><dd><?=student_review_value($record['dilution'])?></dd></div><div><dt>Temperatura</dt><dd><?=student_review_value($record['temperature'])?></dd></div><div><dt>Tempo</dt><dd><?=student_review_value($record['development_time'])?></dd></div><div><dt>Branqueador</dt><dd><?=student_review_value($record['bleach']??'')?></dd></div></dl><?php endif;?></article>
  </div>
  <div class="student-review-media"><div><span>Cena</span><?php if($sceneMedia):?><div class="student-media-strip"><?php foreach($sceneMedia as $item):$src='/aluno/teste-media.php?id='.(int)$item['id'];?><a href="<?=h($src)?>" target="_blank" rel="noopener"><img src="<?=h($src)?>" alt="Cena do registro" loading="lazy"></a><?php endforeach;?></div><?php else:?><p>Nenhuma foto da cena.</p><?php endif;?></div><div><span>Resultado</span><?php if($resultMedia):?><div class="student-media-strip"><?php foreach($resultMedia as $item):$src='/aluno/teste-media.php?id='.(int)$item['id'];?><a href="<?=h($src)?>" target="_blank" rel="noopener"><img src="<?=h($src)?>" alt="Resultado do registro" loading="lazy"></a><?php endforeach;?></div><?php else:?><p>Nenhuma foto do resultado.</p><?php endif;?><?php if(trim((string)$record['notes'])!==''):?><p><?=nl2br(h((string)$record['notes']))?></p><?php endif;?></div></div>
</section>
<section class="student-workflow-panel student-conversation"><header class="student-workflow-heading"><div><p class="student-kicker">Acompanhamento</p><h2 class="student-subtitle">Avaliação e conversa</h2></div><p>A conversa acompanha o registro compartilhado.</p></header><?php if(!$messages):?><div class="student-empty">Ainda não há mensagens neste registro.</div><?php else:?><div class="student-thread"><?php foreach($messages as $message):?><article class="student-message <?=$message['author_role']==='admin'?'student-message-admin':'student-message-student'?>"><header><strong><?=$message['author_role']==='admin'?'Professor':h((string)$record['student_name'])?></strong><span><?=h(student_test_message_date((string)$message['created_at']))?></span></header><p><?=nl2br(h((string)$message['body']))?></p></article><?php endforeach;?></div><?php endif;?></section>
<?php student_shell_end();