<?php
declare(strict_types=1);
const BUILD_DIR='.build';
const MANIFEST='.build/dist-managed-files.json';
const DIRS=['app','admin','assets','editor','preview','template','install','migrations','inscricao'];
const FILES=['.htaccess','index.php','interest-submit.php','form-submit.php','media-stream.php'];
const STRUCTURAL=['config/install.example.php','config/local.example.php','storage/.htaccess','uploads/.htaccess','editor/.htaccess'];
const PERSISTENT_PATHS=['config/local.php','storage/database.sqlite','storage/installed.lock'];
function fail(string $message): never { fwrite(STDERR,"build-dist: $message\n"); exit(1); }
function path(string $root,string $relative): string { $relative=str_replace(['\\','/'],DIRECTORY_SEPARATOR,$relative); if(str_contains($relative,'..')) fail('unsafe path'); return $root.DIRECTORY_SEPARATOR.$relative; }
function is_protected_path(string $p): bool { $p=str_replace('\\','/',$p); return in_array($p,PERSISTENT_PATHS,true)||str_starts_with($p,'uploads/')||str_starts_with($p,'storage/logs/')||str_starts_with($p,'logs/'); }
function copy_file(string $from,string $to): void { if(!is_dir(dirname($to))&&!mkdir(dirname($to),0777,true)&&!is_dir(dirname($to))) fail('cannot create staging directory'); if(!copy($from,$to)) fail("cannot copy $from"); }
function staged_files(string $root): array { $out=[]; foreach(array_merge(DIRS,FILES,STRUCTURAL) as $entry){$source=path($root,$entry);if(!file_exists($source)) fail("missing deployable path: $entry");if(is_file($source)){$out[]=$entry;continue;} $it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($source,FilesystemIterator::SKIP_DOTS));foreach($it as $file)if($file->isFile()){$rel=str_replace('\\','/',substr($file->getPathname(),strlen($root)+1));if(!is_protected_path($rel))$out[]=$rel;}} sort($out);return array_values(array_unique($out)); }
function validate(string $stage,array $files): void { foreach(['media-stream.php','form-submit.php','admin','editor','preview','template','assets','inscricao'] as $need)if(!file_exists(path($stage,$need))) fail("validation missing $need");foreach(range(1,17) as $n)if(!glob(path($stage,'migrations/'.sprintf('%03d',$n).'_*.php'))) fail("validation missing migration $n");foreach($files as $rel){$full=path($stage,$rel);if(str_ends_with($rel,'.php')){exec('php -l '.escapeshellarg($full),$o,$rc);if($rc)fail("PHP lint failed: $rel");}if(str_ends_with($rel,'.js')){exec('node --check '.escapeshellarg($full),$o,$rc);if($rc)fail("JS check failed: $rel");}}$bad=['database.sqlite','installed.lock','local.php','.git','output','.playwright-cli','.codex-local-backup'];$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($stage,FilesystemIterator::SKIP_DOTS));foreach($it as $f){$rel=str_replace('\\','/',substr($f->getPathname(),strlen($stage)+1));foreach($bad as $needle)if(basename($rel)===$needle||str_starts_with($rel,$needle.'/'))fail("forbidden staged path: $rel");}}
function load_manifest(string $root): array {$f=path($root,MANIFEST);if(!is_file($f))return []; $v=json_decode((string)file_get_contents($f),true);return is_array($v)?array_values(array_filter($v,'is_string')):[];}
function remove_stage(string $stage,string $build):void{$base=realpath($build);$real=realpath($stage);if($base===false||$real===false||!str_starts_with($real,$base.DIRECTORY_SEPARATOR))fail('unsafe staging cleanup');$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($real,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($it as $f){if($f->isLink())fail('staging contains link: '.$f->getPathname());$p=$f->getPathname();if($f->isFile()){chmod($p,0666);for($i=0;$i<3;$i++){if(unlink($p))continue 2;usleep(100000);}fail('cannot remove staging file: '.$p);}if(!$f->isDir())fail('unsupported staging entry');for($i=0;$i<3;$i++){if(rmdir($p))continue 2;usleep(100000);}fail('cannot remove staging directory');}if(!rmdir($real))fail('cannot remove staging root');}
function main(array $argv): void {$args=$argv;$root=getcwd();$verify=in_array('--verify',$args,true);$dry=in_array('--dry-run',$args,true);foreach($args as $arg)if(str_starts_with($arg,'--root='))$root=substr($arg,7);$root=realpath($root)?:fail('invalid root');if($verify&&$dry)fail('choose one mode');$stage='';try{if(!$verify){$build=path($root,BUILD_DIR);if(!is_dir($build)&&!mkdir($build,0777,true))fail('cannot create build directory');$stage=$build.'/dist-next-'.getmypid().'-'.bin2hex(random_bytes(4));if(!mkdir($stage,0777,true))fail('cannot create staging');$files=staged_files($root);foreach($files as $rel)copy_file(path($root,$rel),path($stage,$rel));validate($stage,$files);}else{$stage=path($root,'dist');$files=staged_files($stage);validate($stage,$files);} $old=load_manifest($root);$remove=array_values(array_diff($old,$files));if($verify){echo "Verified dist: ".count($files)." managed files\n";return;}foreach($files as $rel){$dest=path($root,'dist/'.$rel);if($dry||!is_file($dest)||hash_file('sha256',path($stage,$rel))!==hash_file('sha256',$dest))echo "ADD/UPDATE $rel\n";}foreach($remove as $rel)if(!is_protected_path($rel))echo "REMOVE $rel\n";if($dry){echo "Dry run complete\n";return;}foreach($remove as $rel)if(!is_protected_path($rel)&&is_file(path($root,'dist/'.$rel)))unlink(path($root,'dist/'.$rel));foreach($files as $rel)copy_file(path($stage,$rel),path($root,'dist/'.$rel));file_put_contents(path($root,MANIFEST),json_encode($files,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)."\n");echo "Build complete: ".count($files)." managed files\n";}finally{if($stage!==''&&str_contains($stage,'dist-next-')&&is_dir($stage))remove_stage($stage,path($root,BUILD_DIR));}}
try{main($argv);}catch(Throwable $e){fwrite(STDERR,"build-dist: {$e->getMessage()}\n");exit(1);}
