<?php
declare(strict_types=1);

function must(bool $ok,string $message): void {if(!$ok){fwrite(STDERR,"task-centric-admin: $message\n");exit(1);}}
$root=dirname(__DIR__);
$admin=(string)file_get_contents($root.'/admin/index.php');
$editor=(string)file_get_contents($root.'/editor/index.html');
$editorEntry=(string)file_get_contents($root.'/editor/index.php');
$coreEditor=(string)file_get_contents($root.'/editor/cms-editor-v3.js');
$videoEditor=(string)file_get_contents($root.'/editor/cms-video-library.js');
$quickFormEditor=(string)file_get_contents($root.'/editor/cms-form-quick-editor.js');
$client=(string)file_get_contents($root.'/editor/task-centric.js');
$autosave=(string)file_get_contents($root.'/editor/autosave.js');
$context=(string)file_get_contents($root.'/admin/api/editor-context.php');
$shell=(string)file_get_contents($root.'/app/admin_shell.php');
$submissions=(string)file_get_contents($root.'/admin/submissions.php');
$media=(string)file_get_contents($root.'/admin/media.php');
$mediaTask=(string)file_get_contents($root.'/assets/admin-media-task.js');
$mediaLibrary=(string)file_get_contents($root.'/editor/media-library.js');
$publicCss=(string)file_get_contents($root.'/assets/cms-v3.css');
$renderer=(string)file_get_contents($root.'/app/cms_renderer.php');
$adminCss=(string)file_get_contents($root.'/admin/pro-admin.css');
$adminControls=(string)file_get_contents($root.'/assets/admin-controls.css');
$formsLayout=(string)file_get_contents($root.'/assets/forms-admin-layout.css');
$formsLayoutJs=(string)file_get_contents($root.'/assets/forms-admin-layout.js');

must(!str_contains($admin,"Location: /editor/?page="),'admin entry point must not bypass the dashboard');
must(str_contains($admin,"admin_shell_start('overview','Visão geral'"),'admin entry point must render the overview dashboard');
must(str_contains($admin,'admin-dashboard-status'),'dashboard must surface operational status');
must(str_contains($admin,'Editar página inicial'),'dashboard must keep direct editing as an explicit action');
must(str_contains($editor,'id="editor-page-switcher"'),'editor must expose page switching in context');
must(str_contains($editor,'id="editor-submissions"'),'editor must expose inscriptions without leaving the site mental model');
must(str_contains($editor,'id="media-library-search"'),'image replacement must have inline library search');
must(str_contains($editor,'/editor/cms-form-quick-editor.js'),'page editor must load the simplified form editor');
must(str_contains($editor,'/editor/cms-form-quick-editor.css'),'page editor must load simplified form-editor styling');
must(str_contains($editor,'<button type="button" id="save-page">Salvar agora</button>'),'manual save must remain available but secondary');
must(strpos($editor,'id="publish-page"')<strpos($editor,'id="save-page"'),'publish must be the primary visible editorial action');
if(str_contains($coreEditor,"$('#editor-title').textContent"))must(str_contains($editor,'id="editor-title"'),'editor core title target must exist');
if(str_contains($coreEditor,"$('#editor-locale').textContent"))must(str_contains($editor,'id="editor-locale"'),'editor core locale target must exist');
must(str_contains($editorEntry,"deploy-info.json"),'editor entry point must derive an installed-version token for its assets');
must(str_contains($editorEntry,"?v='.$version"),'editor entry point must append the installed version to editor CSS/JS URLs');
must(strpos($editor,'/editor/cms-video-library.js')<strpos($editor,'/editor/cms-pro-editor.js'),'dedicated video interception must load before legacy pro-editor video hooks');
must(str_contains($autosave,'MutationObserver'),'autosave must react to dirty-state changes');
must(str_contains($autosave,'setTimeout(flush,3200)'),'autosave must debounce short editing pauses');
must(!str_contains($autosave,'setInterval'),'autosave must not wait on a fixed polling interval');
must(str_contains($client,'/admin/api/editor-context.php'),'editor context must be loaded from the authenticated endpoint');
must(str_contains($client,"includes('não salvas')"),'page switching must protect unsaved changes');
must(str_contains($context,"status='new'"),'editor context must surface new inscriptions');
must(!str_contains($shell,"'overview'=>['Início'"),'overview must remain a dashboard, not a redundant context-tab entry');
must(str_contains($shell,"'site'=>['Site','/admin/'"),'site workspace must lead to the dashboard');
must(str_contains($shell,'admin_asset_version'),'admin shell must version local CSS/JS after application updates');
must(str_contains($shell,'admin-controls.css?v=<?=$assetVersion?>'),'shared admin choice-control invariants must load after the normal admin styles');
must(str_contains($shell,'forms-admin-layout.css?v=<?=$assetVersion?>'),'full form editor must receive the simplified layout layer');
must(str_contains($shell,'forms-admin-layout.js?v=<?=$assetVersion?>'),'advanced form settings must be progressively collapsed by the admin shell');
must(str_contains($submissions,"foreach(['name','full_name','email','phone']"),'inbox must identify registrations by participant name before email');
must(str_contains($submissions,'Aguardando pagamento'),'registration inbox must expose payment state directly');
must(str_contains($submissions,'Confirmar inscrição e pagamento'),'registration admin must make confirmation the primary operational action');
must(str_contains($media,'id="media-selection-toggle"'),'bulk media actions must be an explicit mode');
must(str_contains($mediaTask,'previewSrc(item,480)'),'media grid must use thumbnail-sized sources');
must(str_contains($mediaLibrary,'previewSrc(item,target=480)'),'media library must choose responsive previews');
must(str_contains($videoEditor,"querySelectorAll('video')"),'page editor must bind every video element, including legacy/process videos without a special editor marker');
must(str_contains($videoEditor,"video.addEventListener('pointerdown'"),'video selection must intercept pointer interaction on the video element itself');
must(str_contains($videoEditor,"video.addEventListener('click'"),'video selection must intercept click interaction on the video element itself');
must(str_contains($videoEditor,'event.preventDefault()')&&str_contains($videoEditor,'event.stopImmediatePropagation()'),'video editor must override native player/default section interaction before selecting the video');
must(str_contains($videoEditor,"frame.addEventListener('load',installFrameControls)"),'video interception must be installed synchronously on iframe load before later legacy hooks');
must(!str_contains($videoEditor,'data-cms-editor-video-selector'),'video selection must not insert an editable overlay/button above the player');
must(str_contains($videoEditor,'MediaLibrary.videos'),'video editor must use the video collection, not the image collection');
must(!str_contains($videoEditor,'MediaLibrary.images'),'video editor must not reuse image-library controls');
must(str_contains($quickFormEditor,'/admin/api/cms-form-load.php?form='),'inline form editor must load the form schema without leaving the page editor');
must(str_contains($quickFormEditor,"data-q-label"),'inline form editor must allow field-label editing');
must(str_contains($quickFormEditor,"data-q-option-label")&&str_contains($quickFormEditor,"data-q-option-value"),'inline form editor must expose both visible option labels and stored option values');
must(str_contains($quickFormEditor,"data-q-required"),'inline form editor must expose the common required toggle');
must(str_contains($quickFormEditor,"/admin/api/cms-form-save.php"),'inline form editor must save through the canonical form API');
must(str_contains($quickFormEditor,"/admin/api/cms-form-publish.php"),'inline form editor must support publishing form changes from the page editor');
must(str_contains($quickFormEditor,'Abrir editor completo'),'inline editor must keep the full form editor available for structural work');
must(str_contains($publicCss,'.cms-public input[type="checkbox"],.cms-public input[type="radio"]'),'native public choice controls must be normalized at the shared page layer, not in one page or form instance');
must(str_contains($publicCss,'min-height:18px'),'public choice controls must override legacy text-input height');
must(str_contains($renderer,'cms_public_asset_version'),'public renderer must version shared assets after application updates');
must(str_contains($renderer,'cms-system-choice-controls'),'public renderer must enforce choice-control geometry independently of cached external CSS');
must(str_contains($adminCss,'.admin-page input[type="checkbox"],.admin-page input[type="radio"]'),'legacy admin layer must still acknowledge native choice controls');
must(str_contains($adminControls,'body.admin-page input[type="checkbox"]')&&str_contains($adminControls,'body.admin-page input[type="radio"]'),'admin choice controls must be normalized in a final shared stylesheet, not per form page');
must(str_contains($adminControls,'max-width:16px!important')&&str_contains($adminControls,'max-height:16px!important'),'admin native choice controls must not inherit text-field geometry');
must(str_contains($formsLayout,'.form-builder{display:block}'),'full form editor must avoid the previous three-column squeeze');
must(str_contains($formsLayoutJs,"cards.slice(1)"),'secondary form configuration panels must collapse by default');

echo "Task-centric admin tests passed\n";
