<?php
declare(strict_types=1);

function fail_replanning(string $message): never {fwrite(STDERR,"student-process-replanning: $message\n");exit(1);}
function must_replanning(bool $ok,string $message): void {if(!$ok)fail_replanning($message);}
function utc_now(): string {return gmdate('c');}
function student_uuid(): string {return bin2hex(random_bytes(16));}
function student_process_json_array(string $json): array {$v=json_decode($json,true);return is_array($v)?$v:[];}
function student_test_for_student(PDO $db,int $testId,int $studentId): ?array {$q=$db->prepare('SELECT * FROM student_tests WHERE id=? AND student_id=?');$q->execute([$testId,$studentId]);return $q->fetch(PDO::FETCH_ASSOC)?:null;}
function student_process_plan_for_test(PDO $db,int $testId,int $studentId): ?array {$q=$db->prepare('SELECT * FROM student_process_plans WHERE test_id=? AND student_id=? LIMIT 1');$q->execute([$testId,$studentId]);return $q->fetch(PDO::FETCH_ASSOC)?:null;}
function student_process_plan_steps(PDO $db,int $planId): array {$q=$db->prepare('SELECT * FROM student_process_plan_steps WHERE plan_id=? ORDER BY position,id');$q->execute([$planId]);return $q->fetchAll(PDO::FETCH_ASSOC);}
function student_process_steps(PDO $db,int $testId): array {$q=$db->prepare('SELECT * FROM student_process_steps WHERE test_id=? ORDER BY position,id');$q->execute([$testId]);return $q->fetchAll(PDO::FETCH_ASSOC);}
function student_process_change_log(PDO $db,string $actorRole,?int $adminId,?int $studentId,string $entityType,int $entityId,string $action,array $before=[],array $after=[],string $note=''): void {$db->prepare('INSERT INTO student_process_change_log(entity_type,entity_id,action,before_json,after_json) VALUES(?,?,?,?,?)')->execute([$entityType,$entityId,$action,json_encode($before),json_encode($after)]);}

require_once dirname(__DIR__).'/app/student_process_replanning.php';

function replanning_db(): PDO {
    $db=new PDO('sqlite::memory:');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);
    $db->exec("CREATE TABLE student_tests(id INTEGER PRIMARY KEY,student_id INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'draft');
CREATE TABLE student_process_steps(id INTEGER PRIMARY KEY AUTOINCREMENT,test_id INTEGER NOT NULL,position INTEGER NOT NULL,stage_key TEXT NOT NULL,label TEXT NOT NULL,duration TEXT NOT NULL DEFAULT '',metadata_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE student_process_plans(id INTEGER PRIMARY KEY AUTOINCREMENT,plan_uuid TEXT NOT NULL UNIQUE,student_id INTEGER NOT NULL,test_id INTEGER NOT NULL UNIQUE,source_template_id INTEGER NULL,source_global_version_id INTEGER NULL,source_name TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'planned',started_at TEXT NULL,completed_at TEXT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE student_process_plan_steps(id INTEGER PRIMARY KEY AUTOINCREMENT,plan_id INTEGER NOT NULL,position INTEGER NOT NULL,stage_key TEXT NOT NULL,label TEXT NOT NULL,duration TEXT NOT NULL DEFAULT '',agitation_interval TEXT NOT NULL DEFAULT '',payload_json TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'planned',actual_step_id INTEGER NULL,started_at TEXT NULL,completed_at TEXT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE student_process_execution_sessions(plan_id INTEGER PRIMARY KEY,student_id INTEGER NOT NULL,plan_step_id INTEGER NULL,state TEXT NOT NULL,duration_seconds INTEGER NULL,remaining_seconds INTEGER NULL,timer_started_at TEXT NULL,timer_ends_at TEXT NULL,paused_at TEXT NULL,revision INTEGER NOT NULL DEFAULT 0,last_client_token TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE student_process_change_log(id INTEGER PRIMARY KEY AUTOINCREMENT,entity_type TEXT,entity_id INTEGER,action TEXT,before_json TEXT,after_json TEXT);");
    $db->exec("INSERT INTO student_tests(id,student_id,status) VALUES(40,7,'draft')");return $db;
}
function route_source(string $name,array $keys): array {return ['name'=>$name,'source_template_id'=>null,'source_global_version_id'=>2,'steps'=>array_map(static fn(string $key): array=>['stage_key'=>$key,'label'=>$key,'duration'=>$key==='first_development'?'7:00':'1:00','agitation_interval'=>'','payload_json'=>'{}'],$keys)];}
function insert_plan(PDO $db,string $name,array $keys,array $statuses=[],array $actualIds=[]): array {$now=utc_now();$db->prepare("INSERT INTO student_process_plans(plan_uuid,student_id,test_id,source_name,status,created_at,updated_at) VALUES('same-plan',7,40,?,'planned',?,?)")->execute([$name,$now,$now]);$id=(int)$db->lastInsertId();$q=$db->prepare('INSERT INTO student_process_plan_steps(plan_id,position,stage_key,label,duration,payload_json,status,actual_step_id,created_at,updated_at) VALUES(?,?,?,?,?,\'{}\',?,?,?,?)');foreach($keys as $i=>$key)$q->execute([$id,$i+1,$key,$key,$key==='first_development'?'7:00':'1:00',$statuses[$i]??'planned',$actualIds[$i]??null,$now,$now]);return student_process_plan_for_test($db,40,7)??[];}
function insert_fact(PDO $db,string $key,bool $legacyInterrupted=false): int {$position=(int)$db->query('SELECT COALESCE(MAX(position),0)+1 FROM student_process_steps WHERE test_id=40')->fetchColumn();$now=utc_now();$q=$db->prepare('INSERT INTO student_process_steps(test_id,position,stage_key,label,duration,metadata_json,created_at,updated_at) VALUES(40,?,?,?,?,?,?,?)');$q->execute([$position,$key,$key,'1:00',json_encode($legacyInterrupted?['interrupted'=>true]:[]),$now,$now]);return (int)$db->lastInsertId();}

$routeA=route_source('FeCl3',['first_development','wash_after_first','ferric','final_wash']);$routeB=route_source('Peracética',['first_development','wash_after_first','peracetic','final_wash']);

$db=replanning_db();insert_plan($db,'FeCl3',['first_development','wash_after_first','ferric','final_wash']);$changed=student_process_replan($db,40,7,$routeB);must_replanning((string)$changed['source_name']==='Peracética','planned switch must replace the selected route');must_replanning((string)$changed['plan_uuid']==='same-plan','planned switch must preserve plan identity');must_replanning(count(student_process_steps($db,40))===0,'planned switch must not invent facts');must_replanning(count(student_process_plan_steps($db,(int)$changed['id']))===4,'planned switch must carry the new future route');

$db=replanning_db();$f1=insert_fact($db,'first_development');$f2=insert_fact($db,'wash_after_first');insert_plan($db,'FeCl3',['first_development','wash_after_first','ferric','final_wash'],['completed','completed','planned','planned'],[$f1,$f2,null,null]);$changed=student_process_replan($db,40,7,$routeB);$rows=student_process_plan_steps($db,(int)$changed['id']);must_replanning(count(student_process_steps($db,40))===2,'route change must preserve completed factual steps');must_replanning((int)$rows[0]['actual_step_id']===$f1&&(int)$rows[1]['actual_step_id']===$f2,'matching factual prefix must stay linked');must_replanning((string)$rows[2]['stage_key']==='peracetic'&&(string)$rows[2]['status']==='planned','only future branch must change');must_replanning((int)$changed['_change']['matched_prefix']===2&&(int)$changed['_change']['pending_steps']===2,'route summary must distinguish history and future');

$db=replanning_db();insert_fact($db,'first_development');insert_fact($db,'wash_after_first');$ferric=insert_fact($db,'ferric');$changed=student_process_replan($db,40,7,$routeB);$rows=student_process_plan_steps($db,(int)$changed['id']);must_replanning(count(student_process_steps($db,40))===3,'divergent history must survive route adoption');must_replanning((int)$changed['_change']['matched_prefix']===2&&(int)$changed['_change']['divergent_steps']===1,'divergent facts must be reported, not rewritten');must_replanning((int)$db->query('SELECT COUNT(*) FROM student_process_plan_steps WHERE actual_step_id='.(int)$ferric)->fetchColumn()===0,'divergent old fact must remain history instead of being relabeled');

// A running/paused timer is interface state. Replanning must never turn it into
// an interrupted laboratory fact.
$db=replanning_db();$plan=insert_plan($db,'FeCl3',['first_development','wash_after_first'],['running','planned']);$first=student_process_plan_steps($db,(int)$plan['id'])[0];$oldPlanId=(int)$plan['id'];$now=utc_now();$db->prepare("UPDATE student_process_plans SET status='running',started_at=? WHERE id=?")->execute([$now,$oldPlanId]);$db->prepare("INSERT INTO student_process_execution_sessions(plan_id,student_id,plan_step_id,state,duration_seconds,remaining_seconds,revision,created_at,updated_at) VALUES(?,7,?,'paused',420,300,2,?,?)")->execute([$oldPlanId,(int)$first['id'],$now,$now]);$changed=student_process_replan($db,40,7,$routeB);must_replanning(count(student_process_steps($db,40))===0,'route change must not invent a fact from timer state');must_replanning((int)$db->query('SELECT COUNT(*) FROM student_process_execution_sessions')->fetchColumn()===0,'successful route change may discard obsolete timer state');$newRows=student_process_plan_steps($db,(int)$changed['id']);must_replanning((string)$newRows[0]['status']==='planned','without facts the new route must remain unconsolidated');must_replanning(!array_key_exists('interrupted_step_added',$changed['_change']),'route summary must not expose obsolete interruption inference');

// Atomicity: if route replacement fails, old plan/session return exactly and no
// factual/audit residue survives the failed transaction.
$db=replanning_db();$plan=insert_plan($db,'FeCl3',['first_development','wash_after_first'],['running','planned']);$first=student_process_plan_steps($db,(int)$plan['id'])[0];$oldPlanId=(int)$plan['id'];$now=utc_now();$db->prepare("UPDATE student_process_plans SET status='running',started_at=? WHERE id=?")->execute([$now,$oldPlanId]);$db->prepare("INSERT INTO student_process_execution_sessions(plan_id,student_id,plan_step_id,state,duration_seconds,remaining_seconds,revision,created_at,updated_at) VALUES(?,7,?,'paused',420,300,2,?,?)")->execute([$oldPlanId,(int)$first['id'],$now,$now]);$db->exec("CREATE TRIGGER fail_route_replacement BEFORE INSERT ON student_process_plans WHEN NEW.source_name='FAIL_ROUTE' BEGIN SELECT RAISE(ABORT,'forced route replacement failure'); END");$failed=false;try{student_process_replan($db,40,7,route_source('FAIL_ROUTE',['first_development','peracetic']));}catch(Throwable){$failed=true;}must_replanning($failed,'forced route replacement failure must surface');must_replanning(count(student_process_steps($db,40))===0,'failed route change must not create factual residue');$oldPlan=student_process_plan_for_test($db,40,7);must_replanning((int)($oldPlan['id']??0)===$oldPlanId&&(string)($oldPlan['source_name']??'')==='FeCl3','failed route change must restore previous plan');must_replanning((int)$db->query('SELECT COUNT(*) FROM student_process_execution_sessions WHERE plan_id='.$oldPlanId)->fetchColumn()===1,'failed route change must restore previous timer session');must_replanning((int)$db->query('SELECT COUNT(*) FROM student_process_change_log')->fetchColumn()===0,'failed transaction must not leave audit event');

// Legacy interrupted rows are preserved as old history but never adopted as a
// completed prefix in a newly selected route.
$db=replanning_db();$legacy=insert_fact($db,'first_development',true);$changed=student_process_replan($db,40,7,$routeB);$rows=student_process_plan_steps($db,(int)$changed['id']);must_replanning(count(student_process_steps($db,40))===1&&(int)student_process_steps($db,40)[0]['id']===$legacy,'legacy interrupted history must remain untouched');must_replanning((int)$changed['_change']['matched_prefix']===0&&(string)$rows[0]['status']==='planned','legacy interrupted history must not become a completed route stage');

$db=replanning_db();$f1=insert_fact($db,'first_development');$f2=insert_fact($db,'wash_after_first');$changed=student_process_replan($db,40,7,$routeB);$rows=student_process_plan_steps($db,(int)$changed['id']);must_replanning((int)$rows[0]['actual_step_id']===$f1&&(int)$rows[1]['actual_step_id']===$f2,'manual facts matching route prefix must be adopted without duplication');must_replanning(count(student_process_steps($db,40))===2,'adopting route after manual facts must not duplicate facts');

$db=replanning_db();$db->exec("UPDATE student_tests SET status='reviewed' WHERE id=40");$blocked=false;try{student_process_replan($db,40,7,$routeB);}catch(RuntimeException $e){$blocked=str_contains($e->getMessage(),'revisado');}must_replanning($blocked,'reviewed records must remain protected from replanning');

echo "student-process-replanning: ok\n";
