<?php
declare(strict_types=1);
$root=dirname(__DIR__);
function ux_expect(bool $ok,string $message): void {if(!$ok){fwrite(STDERR,"ux-audit: $message\n");exit(1);}}
$adminShell=(string)file_get_contents($root.'/app/admin_shell.php');
$studentShell=(string)file_get_contents($root.'/app/student_shell.php');
$courses=(string)file_get_contents($root.'/admin/courses.php');
$registrations=(string)file_get_contents($root.'/admin/registrations.php');
$cohorts=(string)file_get_contents($root.'/admin/cohorts.php');
$students=(string)file_get_contents($root.'/admin/students.php');
$people=(string)file_get_contents($root.'/admin/people.php');
$lessons=(string)file_get_contents($root.'/admin/lessons.php');
$material=(string)file_get_contents($root.'/admin/material.php');
$tests=(string)file_get_contents($root.'/admin/tests.php');
$preview=(string)file_get_contents($root.'/admin/course-preview.php');
$studentHome=(string)file_get_contents($root.'/aluno/index.php');
$studentCourses=(string)file_get_contents($root.'/aluno/cursos.php');
$studentNotebook=(string)file_get_contents($root.'/aluno/caderno.php');
$studentRecord=(string)file_get_contents($root.'/aluno/teste.php');
$studentBench=(string)file_get_contents($root.'/aluno/ferramentas.php');
$processManager=(string)file_get_contents($root.'/aluno/processamentos.php');
$processRunner=(string)file_get_contents($root.'/aluno/processar.php');
$legacyTests=(string)file_get_contents($root.'/aluno/testes.php');
$uiCss=(string)file_get_contents($root.'/assets/ui-core.css');
$adminCss=(string)file_get_contents($root.'/assets/admin-system.css');
$studentCss=(string)file_get_contents($root.'/assets/student-area.css');
$experienceCss=(string)file_get_contents($root.'/assets/student-experience.css');
$academicCss=(string)file_get_contents($root.'/assets/student-academic.css');
$renderedCss=(string)file_get_contents($root.'/assets/student-rendered-fixes.css');
$workspaceDoc=(string)file_get_contents($root.'/docs/ADMIN_COURSE_COHORT_WORKSPACE_2026-10-03.md');
$studentDoc=(string)file_get_contents($root.'/docs/STUDENT_AREA_WORKFLOW_REDESIGN_2026-09-30.md');
$processDoc=(string)file_get_contents($root.'/docs/STUDENT_PROCESS_MANAGER_AND_LAB_RUNNER_2026-10-01.md');
$navStart=strpos($adminShell,'function admin_navigation_groups');$navEnd=strpos($adminShell,'function admin_navigation_active_key');$globalNav=($navStart!==false&&$navEnd!==false&&$navEnd>$navStart)?substr($adminShell,$navStart,$navEnd-$navStart):'';

ux_expect($globalNav!=='','administração precisa de uma árvore global explícita');
ux_expect(str_contains($globalNav,"'Principal'=>")&&str_contains($globalNav,"'Ensino'=>")&&str_contains($globalNav,"'Laboratório'=>")&&str_contains($globalNav,"'Site'=>")&&str_contains($globalNav,"'Sistema'=>"),'sidebar deve refletir ensino, laboratório, site e sistema');
ux_expect(str_contains($globalNav,"'Ensino'=>admin_context_items('courses'")&&str_contains($adminShell,"'courses'=>['Cursos'")&&str_contains($adminShell,"'students'=>['Alunos'"),'Ensino deve expor somente as entradas globais de Cursos e Alunos');
ux_expect(!str_contains($globalNav,"'registrations'=>")&&!str_contains($globalNav,"'cohorts'=>")&&!str_contains($globalNav,"'people'=>")&&!str_contains($globalNav,"'lessons'=>")&&!str_contains($globalNav,"'material'=>"),'coleções dependentes de curso/turma não devem competir na navegação global');
ux_expect(str_contains($adminShell,'function admin_course_workspace_items')&&str_contains($adminShell,'function admin_cohort_workspace_items'),'curso e turma precisam de navegação contextual própria');
ux_expect(str_contains($adminShell,"'registrations'=>['Inscrições',admin_course_url")&&str_contains($adminShell,"'cohorts'=>['Turmas',admin_course_url")&&str_contains($adminShell,"'content'=>['Conteúdo',admin_course_url")&&str_contains($adminShell,"'followup'=>['Acompanhamento',admin_course_url"),'workspace do curso deve expor as tarefas canônicas');
ux_expect(str_contains($adminShell,"'students'=>['Alunos',admin_cohort_url")&&str_contains($adminShell,"'lessons'=>['Aulas e acesso',admin_cohort_url")&&str_contains($adminShell,"'questions'=>['Dúvidas',admin_cohort_url")&&str_contains($adminShell,"'tests'=>['Testes',admin_cohort_url"),'workspace da turma deve expor operação e acompanhamento');
ux_expect(str_contains($adminShell,'class="admin-workspace-nav"'),'navegação contextual deve usar o componente compartilhado de workspace');
ux_expect(str_contains($globalNav,"'Site'=>admin_context_items('site'")&&str_contains($adminShell,"'forms'=>['Formulários'"),'Formulários deve ficar em Site');
ux_expect(str_contains($globalNav,"'Sistema'=>admin_context_items('settings'")&&str_contains($adminShell,"'integrity'=>['Integridade'"),'Integridade deve ficar em Sistema');
ux_expect(str_contains($courses,'in_array($view,[\'overview\',\'setup\',\'new\'],true)'),'curso deve conservar visão geral e configuração próprias');
ux_expect(str_contains($courses,'Escolha um curso para administrar inscrições, turmas, alunos, conteúdo e acompanhamento.'),'catálogo de cursos deve explicar a tarefa, não o modelo de dados');
ux_expect(str_contains($courses,'Abrir curso')&&str_contains($courses,'admin_course_context($course'),'abrir curso deve entrar no workspace persistente');
ux_expect(str_contains($courses,'Precisa de atenção')&&str_contains($courses,'pending_payment')&&str_contains($courses,'unassigned'),'visão geral do curso deve priorizar pendências operacionais');
ux_expect(str_contains($courses,'Buscar curso')&&str_contains($courses,'LIMIT $pageSize OFFSET $offset'),'catálogo de cursos deve pesquisar e paginar no servidor');

ux_expect(!str_contains($registrations,'Todos os cursos')&&str_contains($registrations,'admin_course_context($course'),'Inscrições deve operar dentro de um curso explícito');
ux_expect(str_contains($registrations,'Pagas sem turma')&&str_contains($registrations,'assign_cohort'),'Inscrições deve preservar pagamento sem turma e atribuição explícita');
ux_expect(str_contains($registrations,'Ver disponibilidade agregada'),'Inscrições deve oferecer disponibilidade agregada já no escopo correto do curso');
ux_expect(str_contains($registrations,'LIMIT $pageSize OFFSET $offset')&&str_contains($registrations,'admin-pagination'),'Inscrições deve paginar no servidor');
ux_expect(!str_contains($registrations,'LIMIT 500'),'Inscrições não pode truncar silenciosamente em 500 registros');

ux_expect(str_contains($cohorts,'admin_course_context($course')&&str_contains($cohorts,'admin_cohort_context($course,$cohort'),'Turmas deve alternar entre coleção do curso e workspace da turma');
ux_expect(str_contains($cohorts,"\$action==='update'")&&str_contains($cohorts,"\$action==='archive'")&&str_contains($cohorts,"\$action==='restore'"),'turma deve permitir edição, arquivamento e reativação');
ux_expect(str_contains($cohorts,'Abrir turma')&&str_contains($cohorts,'Nova turma'),'turma deve ser objeto operacional diretamente descobrível');

ux_expect(str_contains($students,'Busca global de pessoas com histórico de participação nos cursos.'),'Alunos deve oferecer uma entrada global por identidade sem expor Pessoas como decisão principal');
ux_expect(str_contains($students,'admin_course_context($course')&&str_contains($students,'admin_cohort_context($course,$cohort'),'Alunos deve preservar contexto de curso e turma quando presente');
ux_expect(str_contains($students,'Importar CSV')&&str_contains($students,'student-import-csv.php'),'importação deve estar disponível em Turma → Alunos');
ux_expect(str_contains($students,"\$action==='move_registration'")&&str_contains($students,"\$action==='disable_manual_enrollment'"),'participação educacional precisa permitir as operações canônicas suportadas');
ux_expect(str_contains($people,'LIMIT $pageSize OFFSET $offset')&&str_contains($people,'admin-pagination'),'Pessoas deve continuar disponível como histórico global paginado');
ux_expect(str_contains($people,'FROM student_users u'),'Pessoas deve continuar baseada na autoridade global de identidade');

ux_expect(str_contains($lessons,'admin_course_context($course')&&str_contains($lessons,'admin_cohort_context($course,$cohort'),'Aulas deve separar estrutura do curso e acesso da turma');
ux_expect(str_contains($lessons,"\$action==='update_lesson'")&&str_contains($lessons,"\$action==='move_lesson'"),'estrutura de aulas deve permitir correção de nome e ordem');
ux_expect(str_contains($lessons,'Ver conteúdo afetado')&&str_contains($lessons,'Liberar agora')&&str_contains($lessons,'Agendar')&&str_contains($lessons,'Bloquear'),'liberação deve mostrar consequência e ações no próprio contexto da turma');
ux_expect(str_contains($lessons,'Visualizar como esta turma'),'Aulas e acesso deve permitir verificar o resultado efetivo');
ux_expect(str_contains($material,'course_material_add_page'),'Material deve preservar a relação canônica com páginas CMS');
ux_expect(str_contains($material,'/editor/?page='),'Material deve continuar usando o editor CMS canônico');
ux_expect(!str_contains($material,'Gerenciar liberação'),'Material não deve se apresentar como autoridade de liberação por turma');
ux_expect(str_contains($tests,'admin_course_context')||str_contains($tests,'admin_cohort_context'),'Testes deve pertencer ao acompanhamento corrente de curso/turma');
ux_expect(str_contains($preview,'cms_access_filter_html'),'prévia da turma deve usar o filtro real de acesso');

foreach(['>Início</a>','>Curso</a>','>Caderno</a>'] as $destination)ux_expect(str_contains($studentShell,$destination),'navegação principal do aluno perdeu '.$destination);
ux_expect(str_contains($studentShell,'data-student-toolbox')&&str_contains($studentShell,'data-toolbox-open'),'ferramentas pequenas deixaram de ser contextuais');
ux_expect(str_contains($studentShell,'student-user-menu')&&str_contains($studentShell,'Gerenciar conta'),'conta, tema e sessão devem ficar subordinados');
ux_expect(str_contains($studentHome,'student_experience_dashboard_state')&&str_contains($studentHome,'student-dashboard-focus')&&str_contains($studentHome,'<h1 class="student-title">Início</h1>'),'Início deve priorizar a próxima ação real sem texto de bastidor');
ux_expect(str_contains($studentCourses,'elseif(count($enrollments)===1)$selectedEnrollment=$enrollments[0]'),'uma única matrícula não pode exigir página intermediária');
ux_expect(str_contains($studentCourses,'student-academic-study')&&str_contains($studentCourses,'course_material_page_release_summary')&&str_contains($studentCourses,'Dúvidas e respostas'),'curso deve reunir material, disponibilidade e dúvidas no mesmo contexto acadêmico');
ux_expect(str_contains($academicCss,'.student-dashboard-focus[hidden]{display:none}'),'estados alternativos do dashboard não podem aparecer simultaneamente');
ux_expect(str_contains($studentNotebook,'Mais ações')&&str_contains($studentNotebook,'student-record-summary')&&!str_contains($studentNotebook,'student-record-progress'),'Caderno deve priorizar o registro e resumir o que existe sem prescrever uma etapa atual');
ux_expect(str_contains($studentNotebook,'data-record-create-dialog'),'novo registro deve abrir diretamente em diálogo, sem etapa intermediária');
ux_expect(!str_contains($studentNotebook,'student-process-compare'),'comparação não pode ocupar permanentemente cada registro');
ux_expect(str_contains($studentRecord,'id="exposicao"')&&str_contains($studentRecord,'id="processamento"')&&str_contains($studentRecord,'id="resultado"'),'registro deve manter Exposição, Processamento e Resultado acessíveis na mesma página');
ux_expect(str_contains($studentRecord,'student-process-path-choice')&&str_contains($studentRecord,'student-process-history')&&!str_contains($studentRecord,'$resultReady'),'processamento deve oferecer ações sem bloquear outras partes do registro');
ux_expect(str_contains($studentRecord,'Marcar ✓')&&str_contains($studentRecord,'edit_plan_step=')&&str_contains($studentRecord,"?'Timer':'Abrir etapa'")&&str_contains($studentRecord,'Adicionar etapa ao roteiro')&&!str_contains($studentRecord,'Desfazer última etapa'),'processamento deve expor check reversível, edição e timer diretamente no Caderno');
ux_expect(str_contains($studentBench,'data-exposure-tool')&&str_contains($studentBench,'data-quick-reciprocity'),'ferramentas pequenas de exposição devem continuar inline');
ux_expect(!str_contains($studentBench,'data-lab-timer')&&str_contains($studentBench,'/aluno/processamentos.php'),'processamento multietapas não pode permanecer reduzido a um temporizador inline');
ux_expect(str_contains($processManager,'student-process-step-list')&&str_contains($processRunner,'data-process-runner'),'processamento multietapas deve ter gerenciador e superfície operacional próprias');
ux_expect(str_contains($studentBench,'Modo de preparo')&&str_contains($studentBench,'student_experience_recipe_notes'),'receitas devem reunir cálculo e modo de preparo');
foreach(['Continue de onde faz sentido','Ferramentas pequenas ficam aqui','sem entrar e sair de várias páginas','O histórico fica abaixo','Aqui o foco é somente a etapa atual'] as $internalCopy)ux_expect(!str_contains($studentHome.$studentBench.$studentRecord,$internalCopy),'texto interno vazou para a interface do aluno: '.$internalCopy);
ux_expect(str_contains($legacyTests,"header('Location: /aluno/caderno.php'"),'rota legada de testes deve convergir para o Caderno global');

ux_expect(str_contains($uiCss,'--ux-space-7:48px'),'sistema deve possuir escala global de espaçamento na camada de primitivas');
ux_expect(str_contains($adminCss,'.admin-content{display:flex;flex-direction:column;gap:var(--ux-space-6)'),'ritmo de primeiro nível da administração deve pertencer à autoridade administrativa');
ux_expect(str_contains($adminCss,'row-gap:var(--ux-space-5,24px)'),'formulários administrativos devem consumir a escala global');
ux_expect(str_contains($adminCss,'gap:var(--ux-space-4,16px)'),'componentes de dados devem usar tokens da escala');
ux_expect(str_contains($studentCss,'gap:var(--ux-space-5) 20px'),'forms do aluno devem consumir ritmo global');
ux_expect(str_contains($experienceCss,'.student-process-now')&&str_contains($experienceCss,'.student-toolbox')&&str_contains($experienceCss,'.student-bench-grid'),'camada de experiência deve expressar foco operacional e ferramentas contextuais');
ux_expect(str_contains($renderedCss,'.student-sticky-action{margin-top:30px;padding-top:22px')&&str_contains($renderedCss,'.student-form-grid{gap:28px 20px}'),'ação principal não pode ficar colada aos campos');
ux_expect(str_contains($studentCss,'.student-link{display:inline-flex;min-height:40px'),'ações textuais do aluno devem ter affordance explícita');
ux_expect(str_contains($workspaceDoc,'curso, o contexto passa a ser persistente')&&str_contains($workspaceDoc,'turma, ela passa a ser a unidade operacional concreta'),'documentação administrativa deve fixar os workspaces de curso e turma');
ux_expect(str_contains($workspaceDoc,'Inscrições deixam de misturar cursos por padrão')&&str_contains($workspaceDoc,'A disponibilidade pertence à turma'),'documentação deve fixar escopo de inscrições e liberação');
ux_expect(str_contains($workspaceDoc,'Nenhum fluxo reintroduz matrícula automática em turma padrão'),'documentação deve preservar a proibição de atribuição automática');
ux_expect(str_contains($studentDoc,'Secagem encerra o processamento')&&str_contains($studentDoc,'Uma utilidade simples não ganha subpágina'),'documentação canônica da experiência do aluno está incompleta');
ux_expect(str_contains($processDoc,'Processamento passa a ser a entidade central')&&str_contains($processDoc,'template → snapshot do registro → execução real'),'documentação do novo fluxo deve distinguir workflow operacional de utilidade simples');

echo "ux-audit: ok\n";