<?php
declare(strict_types=1);
function fail_coherence(string $message): never {fwrite(STDERR,"student-platform-coherence: $message\n");exit(1);}
if(!function_exists('app_config')){function app_config(): array{return ['timezone'=>'UTC'];}}
if(!function_exists('utc_now')){function utc_now(): string{return gmdate('c');}}
function workshop_course_scope_available(PDO $db): bool{return false;}
function workshop_lesson_scope_available(PDO $db): bool{return false;}
function course_domain_available(PDO $db): bool{return false;}
$root=dirname(__DIR__);
$studentAdmin=(string)file_get_contents($root.'/admin/student-area.php');$peopleAdmin=(string)file_get_contents($root.'/admin/people.php');$courseAdmin=(string)file_get_contents($root.'/admin/courses.php');$materialAdmin=(string)file_get_contents($root.'/admin/material.php');$adminShell=(string)file_get_contents($root.'/app/admin_shell.php');$studentShell=(string)file_get_contents($root.'/app/student_shell.php');$site=(string)file_get_contents($root.'/admin/site.php');$adminJs=(string)file_get_contents($root.'/assets/admin.js');$media=(string)file_get_contents($root.'/admin/media.php');$mediaPrivacy=(string)file_get_contents($root.'/app/media_privacy.php');$sharing=(string)file_get_contents($root.'/app/student_sharing.php');$sharedTest=(string)file_get_contents($root.'/aluno/teste-compartilhado.php');$testPage=(string)file_get_contents($root.'/aluno/teste.php');$workbench=(string)file_get_contents($root.'/app/student_workbench.php');$editorAccess=(string)file_get_contents($root.'/editor/cms-access-controls.js');$editorHtml=(string)file_get_contents($root.'/editor/index.html');$index=(string)file_get_contents($root.'/index.php');$registrations=(string)file_get_contents($root.'/admin/registrations.php');

foreach(['cms_design_font_import_css','cms_design_css','/template/page.css'] as $needle)if(!str_contains($studentShell,$needle))fail_coherence('student shell does not consume canonical design authority: '.$needle);
if(!str_contains($studentShell,'installation_brand_name()')||str_contains($studentShell,'student_account_enrollments('))fail_coherence('student shell still conflates global identity/design with first enrollment');
if(!str_contains($studentShell,'student_course_context_header')||!str_contains($studentShell,'>Cursos</a>')||!str_contains($studentShell,'>Laboratório</a>'))fail_coherence('student task navigation/course context architecture missing');
if(!str_contains($courseAdmin,'name="title"')||!str_contains($courseAdmin,'course_update($db,$courseId,$_POST)'))fail_coherence('course title is not editable from the canonical course configuration');
if(str_contains($site,'name="course_public_title"')||str_contains($site,'Nome público do curso'))fail_coherence('Site navigation still owns course identity instead of the course domain');
foreach(['private','cohort','course'] as $visibility)if(!str_contains($sharing,"'".$visibility."'"))fail_coherence('missing record visibility: '.$visibility);
if(!str_contains($sharedTest,'student_test_messages($db,$id)')||!str_contains($sharedTest,'A conversa acompanha o registro compartilhado.'))fail_coherence('shared conversation does not follow record visibility');
if(str_contains($sharedTest,'name="message"'))fail_coherence('shared students can write into another student record');
if(!str_contains($registrations,'name="action" value="delete_registration"')||!str_contains($registrations,'admin_registration_delete'))fail_coherence('permanent registration deletion missing from canonical registration workspace');
foreach(['data-cms-access-controls','cms-access-audience','cms-access-availability','cms-visible-from','cms-visible-until','cms-access-lesson'] as $needle)if(!str_contains($editorAccess,$needle))fail_coherence('section access control missing from canonical editor: '.$needle);
if(!str_contains($editorHtml,'/editor/cms-access-controls.js'))fail_coherence('canonical editor does not load access controls');
if(!str_contains($index,'cms_access_filter_html'))fail_coherence('public renderer path does not apply generic section authorization');
if(!str_contains($studentAdmin,'/admin/people.php'))fail_coherence('legacy student administration route does not delegate to global people authority');
if(!str_contains($peopleAdmin,'FROM student_users u')||!str_contains($peopleAdmin,'c.course_id IS NULL'))fail_coherence('global people administration hides identities when course links are incomplete');
if(!str_contains($adminShell,"'material'=>['Material'")||!str_contains($courseAdmin,"admin_course_url(\$activityId,\$courseId,'material')")||!str_contains($materialAdmin,'course_material_add_page')||!str_contains($materialAdmin,'/editor/?page='))fail_coherence('course material is not a global filtered view of canonical CMS pages/editor');
if(str_contains($materialAdmin,'material-editor')||str_contains($materialAdmin,'material_renderer'))fail_coherence('parallel material editor/renderer introduced');
foreach(['Agendar','Liberar agora','Bloquear','/admin/api/course-lesson-release.php'] as $needle)if(!str_contains($adminJs,$needle))fail_coherence('lesson scheduling missing from existing lessons interface: '.$needle);
if(!str_contains($media,'admin-media-privacy.js')||!str_contains($mediaPrivacy,"['public','private']"))fail_coherence('media library is not privacy authority');
foreach(["'fixer'=>","'peracetic'=>","'ferric'=>","'dichromate'=>","'permanganate'=>"] as $needle)if(!str_contains($workbench,$needle))fail_coherence('guided processing branch missing: '.$needle);
foreach(['Solução peroxiacética','Cloreto férrico','Dicromato','Permanganato','Banho de amônia','Segunda revelação'] as $needle)if(!str_contains($workbench,$needle))fail_coherence('guided processing terminology/route missing: '.$needle);
if(str_contains($testPage,'Ácido peracético'))fail_coherence('obsolete bleach terminology returned');
if(!str_contains($testPage,'student_process_next_choices($steps)')||!str_contains($testPage,'name="stage_key"'))fail_coherence('record processing is no longer driven by the guided stage engine');
$migration66=(string)file_get_contents($root.'/migrations/066_cms_section_access_and_test_bleach.php');
if(!str_contains($migration66,'ALTER TABLE student_tests ADD COLUMN bleach'))fail_coherence('legacy bleach database column migration missing for compatibility');
if(!str_contains($migration66,'data-cms-availability')||!str_contains($migration66,'data-cms-lesson-id'))fail_coherence('legacy section-to-lesson mapping is not migrated into CMS sections');

require_once $root.'/app/cms_access.php';
$db=new PDO('sqlite::memory:',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$db->exec('CREATE TABLE course_cohorts(id INTEGER PRIMARY KEY,activity_id INTEGER,title TEXT,cohort_uuid TEXT,status TEXT);');$db->exec('CREATE TABLE course_enrollments(id INTEGER PRIMARY KEY,student_id INTEGER,cohort_id INTEGER,status TEXT,confirmed_at TEXT);');$db->exec('CREATE TABLE course_lessons(id INTEGER PRIMARY KEY,activity_id INTEGER,lesson_key TEXT,title TEXT);');$db->exec('CREATE TABLE cohort_lesson_releases(cohort_id INTEGER,lesson_id INTEGER,released_at TEXT,created_at TEXT,updated_at TEXT,PRIMARY KEY(cohort_id,lesson_id));');$db->exec("INSERT INTO course_cohorts VALUES(7,1,'Turma A','a','active'),(8,1,'Turma B','b','active');");$db->exec("INSERT INTO course_enrollments VALUES(1,10,7,'active','2026-01-01T00:00:00Z');");$db->exec("INSERT INTO course_lessons VALUES(3,1,'aula-3','Aula 3');");$db->exec("INSERT INTO cohort_lesson_releases VALUES(7,3,'2030-01-02T12:00:00Z','x','x');");
$activity=['id'=>1];$user=['id'=>10];
if(!cms_access_section_allowed($db,$activity,['access'=>'authenticated','availability'=>'immediate'],$user))fail_coherence('authenticated section rejects authenticated user');if(cms_access_section_allowed($db,$activity,['access'=>'authenticated','availability'=>'immediate'],null))fail_coherence('authenticated section reaches anonymous visitor');if(!cms_access_section_allowed($db,$activity,['access'=>'activity','availability'=>'immediate'],$user))fail_coherence('activity section rejects active participant');if(!cms_access_section_allowed($db,$activity,['access'=>'cohort','cohort_id'=>7,'availability'=>'immediate'],$user))fail_coherence('cohort section rejects its cohort');if(cms_access_section_allowed($db,$activity,['access'=>'cohort','cohort_id'=>8,'availability'=>'immediate'],$user))fail_coherence('cohort section leaks to another cohort');
$before=strtotime('2030-01-02T11:00:00Z');$after=strtotime('2030-01-02T13:00:00Z');if(cms_access_section_allowed($db,$activity,['access'=>'activity','availability'=>'lesson','lesson_id'=>3],$user,$before))fail_coherence('future lesson release is treated as released');if(!cms_access_section_allowed($db,$activity,['access'=>'activity','availability'=>'lesson','lesson_id'=>3],$user,$after))fail_coherence('lesson does not release when scheduled time arrives');$scheduled=['access'=>'public','availability'=>'scheduled','visible_from'=>'2030-01-02T12:00','visible_until'=>'2030-01-02T14:00'];if(cms_access_section_allowed($db,$activity,$scheduled,null,$before))fail_coherence('scheduled section is visible before its start');if(!cms_access_section_allowed($db,$activity,$scheduled,null,$after))fail_coherence('scheduled section is hidden inside its window');if(cms_access_section_allowed($db,$activity,$scheduled,null,strtotime('2030-01-02T15:00:00Z')))fail_coherence('scheduled section remains visible after its end');
$html='<section data-cms-section="public">PUBLIC</section><section data-cms-section="auth" data-cms-access="authenticated">AUTH</section><section data-cms-section="course" data-cms-access="activity">COURSE</section>';$anonymous=cms_access_filter_html($db,$activity,$html,null,false,$after);if(!str_contains($anonymous,'PUBLIC')||str_contains($anonymous,'AUTH')||str_contains($anonymous,'COURSE'))fail_coherence('anonymous CMS filtering is incorrect');$logged=cms_access_filter_html($db,$activity,$html,$user,false,$after);if(!str_contains($logged,'PUBLIC')||!str_contains($logged,'AUTH')||!str_contains($logged,'COURSE'))fail_coherence('authenticated CMS filtering is incorrect');
echo "student-platform-coherence: ok\n";
