<?php
declare(strict_types=1);
function fail_replanning(string $message): never {fwrite(STDERR,"student-process-replanning: $message\n");exit(1);}
function must_replanning(bool $ok,string $message): void {if(!$ok)fail_replanning($message);}
function utc_now(): string {return gmdate('c');}
function student_uuid(): string {return bin2hex(random_bytes(16));}
function student_process_json_array(string $json): array {$v=json_decode($json,true);return is_array($v)?$v:[];}
function student_test_for_student(PDO $db,int $testId,int $studentId): ?array {$q=$db->prepare('SELECT * FROM student_tests WHERE id=? AND student_id=?');$q->execute([$testId,$studentId]);return $q->fetch(PDO::FETCH_ASSOC)?:null;}
function student_process_plan_for_test(PDO $db,int $testId,int $studentId): ?array {$q=$db->prepare('SELECT * FROM student_process_plans WHERE test_id=? AND student_id=? LIMIT 1');$q->execute([$testId,$studentId]);return $q->fetch(PDO::FETCH_ASSOC)?:null;}
function student_process_plan_steps(PDO $db,int $planId): array {$q=$db->prepare('SELECT * FROM student_process_plan_steps WHERE plan_id=? ORDER BY position,id');$q->execute([$planId]);return $q->fetchAll(PDO::FETCH_ASSOC);}
function student_process_steps(PDO $db,int $testId): array {$q=$db->prepare('SELECT * FROM student_process_steps WHERE test_id=? ORDER BY position,id');$q->execute([$testId]);return $q->fetchAll(PDO::FETCH_ASSOC);}
function student_process_change_log(PDO $db,string $actorRole,?int $adminId,?int $studentId,string $entityType,int $entityId,string $action,array $before=[],array $after=[],string $note=''): void {$db->prepare('INSERT INTO student_process_change_log(entity_type,entity_id,action,before_json,after_json) VALUES(?,?,?,?,?)')->execute([$entityType,$entityId,$action,json_encode($before),json_encode($after)]);}
require_once dirname(__DIR__).'/app/student_process_replanning.php';

function replanning_db(): PDO {
    $db=new PDO('sqlite::memory:');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);
    $db->exec("CREATE TABLE student_tests(id INTEGER PRIMARY KEY,student_id INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'draft');
CREATE TABLE student_process_steps(id INTEGER PRIMARY KEY AUTOINCREMENT,test_id INTEGER NOT NULL,position INTEGER NOT NULL,stage_key TEXT NOT NULL,label TEXT NOT NULL,duration TEXT NOT NULL DEFAULT '',metadata_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE student_process_plans(id INTEGER PRIMARY KEY AUTOINCREMENT,plan_uuid TEXT NOT NULL UNIQUE,student_id INTEGER NOT NULL,test_id INTEGER NOT NULL UNIQUE,source_template_id INTEGER NULL,source_global_version_id INTEGER NULL,source_name TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'planned',started_at TEXT NULL,completed_at TEXT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE student_process_plan_steps(id INTEGER PRIMARY KEY AUTOINCREMENT,plan_id INTEGER NOT NULL,position INTEGER NOT NULL,stage_key TEXT NOT NULL,label TEXT NOT NULL,duration TEXT NOT NULL DEFAULT '',agitation_interval TEXT NOT NULL DEFAULT '',payload_json TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'planned',actual_step_id INTEGER NULL,started_at TEXT NULL,completed_at TEXT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE student_process_execution_sessions(plan_id INTEGER PRIMARY KEY,student_id INTEGER NOT NULL,plan_step_id INTEGER NULL,state TEXT NOT NULL,duration_seconds INTEGER NULL,remaining_seconds INTEGER NULL,timer_started_at TEXT NULL,timer_ends_at TEXT NULL,paused_at TEXT NULL,revision INTEGER NOT NULL DEFAULT 0,last_client_token TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE student_process_step_timers(plan_step_id INTEGER PRIMARY KEY,plan_id INTEGER NOT NULL,student_id INTEGER NOT NULL,state TEXT NOT NULL DEFAULT 'idle',duration_seconds INTEGER NULL,remaining_seconds INTEGER NULL,timer_started_at TEXT NULL,timer_ends_at TEXT NULL,paused_at TEXT NULL,completion_applied_at TEXT NULL,revision INTEGER NOT NULL DEFAULT 0,last_client_token TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE student_process_change_log(id INTEGER PRIMARY KEY AUTOINCREMENT,entity_type TEXT,entity_id INTEGER,action TEXT,before_json TEXT,after_json TEXT);");
    $db->exec("INSERT INTO student_tests(id,student_id,status) VALUES(40,7,'draft')");return $db;
}
function route_source(string $name,array $keys): array {return ['name'=>$name,'source_template_id'=>null,'source_global_version_id'=>2,'steps'=>array_map(static fn(string $key): array=>['stage_key'=>$key,'label'=>$key,'duration'=>$key==='first_development'?'7:00':'1:00','agitation_interval'=>'','payload_json'=>'{}'],$keys)];}
function insert_plan(PDO $db,string $name,array $keys,array $statuses=[]): array {$now=utc_now();$db->prepare("INSERT INTO student_process_plans(plan_uuid,student_id,test_id,source_name,status,created_at,updated_at) VALUES('same-plan',7,40,?,'planned',?,?)")->execute([$name,$now,$now]);$id=(int)$db->lastInsertId();$q=$db->prepare('INSERT INTO student_process_plan_steps(plan_id,position,stage_key,label,duration,payload_json,status,created_at,updated_at,completed_at) VALUES(?,?,?,?,?,\'{}\',?,?,?,?)');foreach($keys as $i=>$key){$status=$statuses[$i]??'planned';$q->execute([$id,$i+1,$key,$key,$key==='first_development'?'7:00':'1:00',$status,$now,$now,$status==='completed'?$now:null]);}return student_process_plan_for_test($db,40,7)??[];}
function insert_fact(PDO $db,string $key): int {$position=(int)$db->query('SELECT COALESCE(MAX(position),0)+1 FROM student_process_steps WHERE test_id=40')->fetchColumn();$now=utc_now();$q=$db->prepare('INSERT INTO student_process_steps(test_id,position,stage_key,label,duration,metadata_json,created_at,updated_at) VALUES(40,?,?,?,?,\'{}\',?,?)');$q->execute([$position,$key,$key,'1:00',$now,$now]);return (int)$db->lastInsertId();}

$routeB=route_source('Peracética',['first_development','wash_after_first','peracetic','final_wash']);

$db=replanning_db();insert_plan($db,'FeCl3',['first_development','wash_after_first','ferric','final_wash']);$changed=student_process_replan($db,40,7,$routeB);must_replanning((string)$changed['source_name']==='Peracética','route switch must replace reference');must_replanning((string)$changed['plan_uuid']==='same-plan','route switch must preserve plan identity');must_replanning(count(student_process_steps($db,40))===0,'route switch must not invent facts');must_replanning(count(student_process_plan_steps($db,(int)$changed['id']))===4,'new reference steps missing');

// Checks are independent. A later checked stage survives even if an earlier stage is unchecked.
$db=replanning_db();insert_plan($db,'FeCl3',['first_development','wash_after_first','ferric','final_wash'],['completed','planned','planned','completed']);$changed=student_process_replan($db,40,7,$routeB);$rows=student_process_plan_steps($db,(int)$changed['id']);must_replanning((string)$rows[0]['status']==='completed','compatible first check was lost');must_replanning((string)$rows[1]['status']==='planned','unchecked stage was fabricated');must_replanning((string)$rows[2]['status']==='planned','different branch must not inherit a check');must_replanning((string)$rows[3]['status']==='completed','later compatible check must survive independently of prefix');must_replanning((int)$changed['_change']['preserved_checks']===2,'independent preserved-check count is wrong');

// Free factual notes do not imply route checks.
$db=replanning_db();insert_fact($db,'first_development');insert_fact($db,'wash_after_first');$changed=student_process_replan($db,40,7,$routeB);$rows=student_process_plan_steps($db,(int)$changed['id']);must_replanning(count(student_process_steps($db,40))===2,'free facts must survive route association');foreach($rows as $row)must_replanning((string)$row['status']==='planned','route association inferred completion from free facts');

// Timer state is a tool state and is discarded with the old route without creating process facts.
$db=replanning_db();$plan=insert_plan($db,'FeCl3',['first_development','wash_after_first']);$first=student_process_plan_steps($db,(int)$plan['id'])[0];$now=utc_now();$db->prepare("INSERT INTO student_process_execution_sessions(plan_id,student_id,plan_step_id,state,duration_seconds,remaining_seconds,revision,created_at,updated_at) VALUES(?,7,?,'paused',420,300,2,?,?)")->execute([(int)$plan['id'],(int)$first['id'],$now,$now]);$db->prepare("INSERT INTO student_process_step_timers(plan_step_id,plan_id,student_id,state,duration_seconds,remaining_seconds,revision,created_at,updated_at) VALUES(?,?,7,'running',420,300,2,?,?)")->execute([(int)$first['id'],(int)$plan['id'],$now,$now]);$changed=student_process_replan($db,40,7,$routeB);must_replanning(count(student_process_steps($db,40))===0,'timer state fabricated a process fact');must_replanning((int)$db->query('SELECT COUNT(*) FROM student_process_execution_sessions')->fetchColumn()===0,'legacy timer session survived route replacement');must_replanning((int)$db->query('SELECT COUNT(*) FROM student_process_step_timers')->fetchColumn()===0,'per-step timer survived route replacement');

// Replacement is atomic.
$db=replanning_db();$plan=insert_plan($db,'FeCl3',['first_development','wash_after_first'],['completed','planned']);$oldPlanId=(int)$plan['id'];$db->exec("CREATE TRIGGER fail_route_replacement BEFORE INSERT ON student_process_plans WHEN NEW.source_name='FAIL_ROUTE' BEGIN SELECT RAISE(ABORT,'forced route replacement failure'); END");$failed=false;try{student_process_replan($db,40,7,route_source('FAIL_ROUTE',['first_development','peracetic']));}catch(Throwable){$failed=true;}must_replanning($failed,'forced failure must surface');$old=student_process_plan_for_test($db,40,7);must_replanning((int)($old['id']??0)===$oldPlanId&&(string)($old['source_name']??'')==='FeCl3','failed replacement did not restore old route');must_replanning((string)student_process_plan_steps($db,$oldPlanId)[0]['status']==='completed','failed replacement lost an existing check');must_replanning((int)$db->query('SELECT COUNT(*) FROM student_process_change_log')->fetchColumn()===0,'failed transaction left audit residue');

echo "student-process-replanning: ok\n";