<?php
declare(strict_types=1);

function must(bool $ok,string $message): void {if(!$ok){fwrite(STDERR,"task-centric-admin: $message\n");exit(1);}}
$root=dirname(__DIR__);
$admin=(string)file_get_contents($root.'/admin/index.php');
$editor=(string)file_get_contents($root.'/editor/index.html');
$editorEntry=(string)file_get_contents($root.'/editor/index.php');
$coreEditor=(string)file_get_contents($root.'/editor/cms-editor-v3.js');
$videoEditor=(string)file_get_contents($root.'/editor/cms-video-library.js');
$client=(string)file_get_contents($root.'/editor/task-centric.js');
$autosave=(string)file_get_contents($root.'/editor/autosave.js');
$context=(string)file_get_contents($root.'/admin/api/editor-context.php');
$shell=(string)file_get_contents($root.'/app/admin_shell.php');
$submissions=(string)file_get_contents($root.'/admin/submissions.php');
$media=(string)file_get_contents($root.'/admin/media.php');
$mediaTask=(string)file_get_contents($root.'/assets/admin-media-task.js');
$mediaLibrary=(string)file_get_contents($root.'/editor/media-library.js');
$publicCss=(string)file_get_contents($root.'/assets/cms-v3.css');
$renderer=(string)file_get_contents($root.'/app/cms_renderer.php');
$adminCss=(string)file_get_contents($root.'/admin/pro-admin.css');

must(!str_contains($admin,"Location: /editor/?page="),'admin entry point must not bypass the dashboard');
must(str_contains($admin,"admin_shell_start('overview','Visão geral'"),'admin entry point must render the overview dashboard');
must(str_contains($admin,'admin-dashboard-status'),'dashboard must surface operational status');
must(str_contains($admin,'Editar página inicial'),'dashboard must keep direct editing as an explicit action');
must(str_contains($editor,'id="editor-page-switcher"'),'editor must expose page switching in context');
must(str_contains($editor,'id="editor-submissions"'),'editor must expose inscriptions without leaving the site mental model');
must(str_contains($editor,'id="media-library-search"'),'image replacement must have inline library search');
must(str_contains($editor,'<button type="button" id="save-page">Salvar agora</button>'),'manual save must remain available but secondary');
must(strpos($editor,'id="publish-page"')<strpos($editor,'id="save-page"'),'publish must be the primary visible editorial action');
if(str_contains($coreEditor,"$('#editor-title').textContent"))must(str_contains($editor,'id="editor-title"'),'editor core title target must exist');
if(str_contains($coreEditor,"$('#editor-locale').textContent"))must(str_contains($editor,'id="editor-locale"'),'editor core locale target must exist');
must(str_contains($editorEntry,"deploy-info.json"),'editor entry point must derive an installed-version token for its assets');
must(str_contains($editorEntry,"?v='.\$version"),'editor entry point must append the installed version to editor CSS/JS URLs');
must(strpos($editor,'/editor/cms-video-library.js')<strpos($editor,'/editor/cms-pro-editor.js'),'dedicated video interception must load before legacy pro-editor video hooks');
must(str_contains($autosave,'MutationObserver'),'autosave must react to dirty-state changes');
must(str_contains($autosave,'setTimeout(flush,3200)'),'autosave must debounce short editing pauses');
must(!str_contains($autosave,'setInterval'),'autosave must not wait on a fixed polling interval');
must(str_contains($client,'/admin/api/editor-context.php'),'editor context must be loaded from the authenticated endpoint');
must(str_contains($client,"includes('não salvas')"),'page switching must protect unsaved changes');
must(str_contains($context,"status='new'"),'editor context must surface new inscriptions');
must(!str_contains($shell,"'overview'=>['Início'"),'overview must remain a dashboard, not a redundant context-tab entry');
must(str_contains($shell,"'site'=>['Site','/admin/'"),'site workspace must lead to the dashboard');
must(str_contains($submissions,"foreach(['name','full_name','email','phone']"),'inbox must identify registrations by participant name before email');
must(str_contains($submissions,'Aguardando pagamento'),'registration inbox must expose payment state directly');
must(str_contains($submissions,'Confirmar inscrição e pagamento'),'registration admin must make confirmation the primary operational action');
must(str_contains($media,'id="media-selection-toggle"'),'bulk media actions must be an explicit mode');
must(str_contains($mediaTask,'previewSrc(item,480)'),'media grid must use thumbnail-sized sources');
must(str_contains($mediaLibrary,'previewSrc(item,target=480)'),'media library must choose responsive previews');
must(str_contains($videoEditor,"querySelectorAll('video')"),'page editor must bind every video element, including legacy/process videos without a special editor marker');
must(str_contains($videoEditor,"video.addEventListener('pointerdown'"),'video selection must intercept pointer interaction on the video element itself');
must(str_contains($videoEditor,"video.addEventListener('click'"),'video selection must intercept click interaction on the video element itself');
must(str_contains($videoEditor,'event.preventDefault()')&&str_contains($videoEditor,'event.stopImmediatePropagation()'),'video editor must override native player/default section interaction before selecting the video');
must(str_contains($videoEditor,"frame.addEventListener('load',installFrameControls)"),'video interception must be installed synchronously on iframe load before later legacy hooks');
must(!str_contains($videoEditor,'data-cms-editor-video-selector'),'video selection must not insert an editable overlay/button above the player');
must(!str_contains($videoEditor,'Editar vídeo</span>'),'video selection must not create a fake editable control inside the page');
must(str_contains($videoEditor,'MutationObserver'),'video binding must survive dynamic editor DOM changes');
must(str_contains($videoEditor,'MediaLibrary.videos'),'video editor must use the video collection, not the image collection');
must(!str_contains($videoEditor,'MediaLibrary.images'),'video editor must not reuse image-library controls');
must(str_contains($videoEditor,'Biblioteca de vídeos'),'video replacement must have a dedicated video-only library');
must(str_contains($videoEditor,'Arquivo de vídeo')&&str_contains($videoEditor,'Capa do vídeo'),'video source and poster/cover must be distinct controls');
must(str_contains($videoEditor,"video.dataset.mediaVersionMode='latest'"),'managed video replacement must preserve the media-asset relationship');
must(str_contains($videoEditor,'delete video.dataset.mediaAssetId'),'switching to an external URL must remove the managed-asset binding so the resolver cannot overwrite it');
must(str_contains($videoEditor,'accept="video/mp4,video/webm,video/quicktime"'),'video dialog must upload video media, not images');
must(str_contains($videoEditor,"video.classList.add('cms-selection')"),'video selection must reuse the core transient selection class that is stripped during serialization');
must(str_contains($publicCss,'.cms-public input[type="checkbox"],.cms-public input[type="radio"]'),'native public choice controls must be normalized at the shared page layer, not in one page or form instance');
must(str_contains($publicCss,'min-height:18px'),'public choice controls must override legacy text-input height');
must(str_contains($renderer,'cms_public_asset_version'),'public renderer must version shared assets after application updates');
must(str_contains($renderer,'cms-system-choice-controls'),'public renderer must enforce choice-control geometry independently of cached external CSS');
must(str_contains($renderer,'cms_public_system_css_imports($assetVersion,$design)'),'public stylesheets must be rendered through the versioned system import helper with current Design settings');
must(str_contains($renderer,"'/template/page.css'")&&str_contains($renderer,'rawurlencode($assetVersion)'),'public base stylesheet must use the installed application version in its layered import URL');
must(str_contains($renderer,'layer(cms-system)'),'public stylesheets must remain in the lower system cascade layer');
must(str_contains($renderer,'public.js?v=<?=$assetVersionHtml?>'),'public JavaScript must use the escaped installed application version in its URL');
must(str_contains($adminCss,'.admin-page input[type="checkbox"],.admin-page input[type="radio"]'),'admin must explicitly size native choice controls');
must(str_contains($adminCss,'min-height:18px'),'admin choice controls must override generic admin input height');

echo "Task-centric admin tests passed\n";
