<?php
declare(strict_types=1);
function must(bool $ok,string $message): void {if(!$ok){fwrite(STDERR,"form-editor-integration: $message\n");exit(1);}}
$root=dirname(__DIR__);
$editor=(string)file_get_contents($root.'/editor/index.html');
$controller=(string)file_get_contents($root.'/editor/cms-form-editor.js');
$adminShell=(string)file_get_contents($root.'/app/admin_shell.php');
$formCss=(string)file_get_contents($root.'/assets/admin-form-ux.css');
$forms=(string)file_get_contents($root.'/admin/forms.php');

must(str_contains($editor,'/editor/cms-form-editor.js'),'page editor must load the unified form visual-edit controller');
must(!str_contains($editor,'/editor/cms-form-quick-edit.js'),'obsolete layered form controller must not remain active');
must(str_contains($editor,'/editor/cms-form-quick-edit.css'),'page editor may reuse the existing form inspector styles');
must(strpos($editor,'/editor/cms-form-editor.js')<strpos($editor,'/editor/cms-editor-v3.js'),'form capture controller must register before the core iframe hooks');
must(str_contains($controller,'/admin/api/cms-form-load.php?form='),'visual form editor must load canonical form schema');
must(str_contains($controller,'/admin/api/cms-form-save.php'),'visual form editor must save through the canonical form API');
must(str_contains($controller,'/admin/api/cms-form-publish.php'),'visual form editor must support explicit form publishing');
must(str_contains($controller,"part:'field-label'")&&str_contains($controller,"part:'option-label'")&&str_contains($controller,"part:'field-help'")&&str_contains($controller,"part:'submit-label'"),'field labels, option labels, help text and submit text must be independent visual targets');
must(str_contains($controller,"part:'field-control'"),'actual input/select/textarea controls must remain selectable as field context');
must(str_contains($controller,"part:'content-text'")&&str_contains($controller,"part:'content-image'")&&str_contains($controller,"part:'content-block'"),'editorial form blocks, their text and their images must be first-class visual targets');
must(str_contains($controller,'data-cms-form-content-id'),'editorial form content must bind to canonical schema blocks');
must(str_contains($controller,'syncContentBlockFromDom'),'changes inside editorial form blocks must be serialized back into the form schema');
must(str_contains($controller,'openImagePicker'),'images inside conditional/payment content must use the media library');
must(str_contains($controller,'data-cms-image'),'form content image targets must be recognized directly');
must(str_contains($controller,'conditionControls'),'conditional editorial blocks must expose their public visibility rule without hiding the block in the editor');
must(str_contains($controller,'decorateAll(d)'),'all rendered form sub-targets must be prepared when the preview document is installed');
must(str_contains($controller,'resolveTarget(event.target)'),'interaction must resolve the clicked descendant, not treat the form as one entity');
must(str_contains($controller,'.cms-choice-grid > label')&&str_contains($controller,'.cms-choice-group > legend')&&str_contains($controller,'.cms-field')&&str_contains($controller,'.cms-consent'),'resolver must cover visible field and option structures even when the exact nested span is not the event target');
must(str_contains($controller,"setAttribute('contenteditable','true')"),'visible form copy must become editable in place');
must(str_contains($controller,"addEventListener('pointerdown'")&&str_contains($controller,'stopImmediatePropagation'),'recognized form descendants must win before legacy wrapper handlers');
must(str_contains($controller,'neutralizeLegacyWrapperSelection'),'rendered forms must explicitly disable the obsolete whole-form selection fallback');
must(str_contains($controller,'block.onclick=null'),'expanded form wrappers must not send clicks back to the legacy form inspector');
must(str_contains($controller,'setTimeout(()=>neutralizeLegacyWrapperSelection(d),0)'),'legacy wrapper selection must be removed after the core load hook has had a chance to attach it');
must(str_contains($controller,'placeCaret'),'direct form text editing must place the caret at the clicked point');
must(!str_contains($controller,'id="fq-field"'),'visual editor must not reduce the form to a field dropdown in the inspector');
must(!str_contains($controller,'Rótulo<input id="fq-label"'),'visible field labels must not be edited through a duplicate inspector text box');
must(str_contains($controller,'Valor interno da opção'),'non-visible option value may remain a contextual property of the clicked option');
must(str_contains($controller,'Configuração estrutural do formulário'),'full form builder must be an explicit secondary structural action, never the click fallback');
must(!str_contains($controller,'MutationObserver'),'form visual editing must not watch and rewrite the inspector recursively');
must(!str_contains($controller,'renderFormHint'),'whole-form inspector hint recursion must not exist');
must(!str_contains($controller,'bf-type')&&!str_contains($controller,'condition_source'),'visual editor must not duplicate the legacy structural form builder');
must(str_contains($adminShell,'admin_asset_version'),'admin shell must version its CSS/JS after application updates');
must(str_contains($adminShell,'admin-system-choice-controls'),'admin shell must enforce native checkbox/radio geometry independently of cached styles');
must(str_contains($adminShell,'/assets/admin-form-ux.css'),'admin shell must load the form-specific admin UX layer');
must(str_contains($formCss,'body.admin-page input[type="checkbox"],body.admin-page input[type="radio"]'),'admin checkbox/radio normalization must be global, not page-specific');
must(str_contains($formCss,'max-width:18px!important')&&str_contains($formCss,'max-height:18px!important'),'admin choice controls must not inherit text-input geometry');
must(str_contains($formCss,'.admin-section-forms .form-builder{display:block}'),'full form editor settings must not consume a permanent side column');
must(str_contains($formCss,'.admin-section-forms .form-builder-workspace{display:grid;grid-template-columns:1fr'),'form editor workspace must prioritize field editing over a cramped multi-column layout');
must(str_contains($forms,'forms-admin.js'),'full form builder must remain available for structural editing');

echo "Form editor integration tests passed\n";
