<?php
declare(strict_types=1);

function fail(string $message): never {fwrite(STDERR,"student-accounts: $message\n");exit(1);}
function utc_now(): string {return gmdate('c');}
function activity_slug(string $value): string {$value=strtolower(trim((string)preg_replace('~[^a-z0-9]+~i','-',$value)));return trim($value,'-')?:'item';}
function app_config(): array {return ['app_secret'=>str_repeat('a',40),'ip_hash_secret'=>str_repeat('b',40)];}
function h(mixed $value): string {return htmlspecialchars((string)$value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function csrf_token(string $scope): string {return 'csrf-'.$scope;}
function cms_page_document(array $document): array {return ['version'=>2,'theme'=>$document['theme']??'auto','meta'=>$document['meta']??['title'=>'','description'=>''],'html'=>(string)($document['html']??'')];}
function cms_page_by_id(PDO $db,int $id): ?array {$q=$db->prepare('SELECT * FROM cms_pages WHERE id=?');$q->execute([$id]);return $q->fetch()?:null;}
function cms_page_doc(array $page,bool $published=true): array {$json=$published?($page['published_document_json']??null):($page['draft_document_json']??null);$decoded=json_decode((string)$json,true);return is_array($decoded)?$decoded:[];}
function cms_form_by_key(PDO $db,int $activityId,string $locale,string $key): ?array {$q=$db->prepare('SELECT * FROM cms_forms WHERE activity_id=? AND locale=? AND form_key=?');$q->execute([$activityId,$locale,$key]);return $q->fetch()?:null;}
const PUBLIC_LOCALE_PT_BR='pt-BR';const PUBLIC_LOCALE_EN='en';

$_SERVER['REMOTE_ADDR']='127.0.0.1';$_SERVER['REQUEST_METHOD']='GET';$_SESSION=[];
require __DIR__.'/../app/student_auth.php';
require __DIR__.'/../app/student_accounts.php';

$db=new PDO('sqlite::memory:',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$db->exec('PRAGMA foreign_keys=ON');
$db->exec("CREATE TABLE activities(id INTEGER PRIMARY KEY AUTOINCREMENT,admin_name TEXT NOT NULL,public_title TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,status TEXT NOT NULL DEFAULT 'active',is_root INTEGER NOT NULL DEFAULT 0);INSERT INTO activities(admin_name,public_title,slug,status,is_root) VALUES('Curso','Curso','curso','active',1);");
$db->exec("CREATE TABLE cms_pages(id INTEGER PRIMARY KEY AUTOINCREMENT,page_uuid TEXT NOT NULL UNIQUE,activity_id INTEGER NOT NULL,locale TEXT NOT NULL,slug TEXT NOT NULL DEFAULT '',title TEXT NOT NULL,nav_title TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',is_home INTEGER NOT NULL DEFAULT 0,show_in_nav INTEGER NOT NULL DEFAULT 1,sort_order INTEGER NOT NULL DEFAULT 0,draft_document_json TEXT NOT NULL,published_document_json TEXT NULL,draft_revision INTEGER NOT NULL DEFAULT 1,published_revision INTEGER NULL,draft_updated_at TEXT NOT NULL,published_at TEXT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);");
$db->exec("CREATE TABLE cms_forms(id INTEGER PRIMARY KEY AUTOINCREMENT,form_uuid TEXT NOT NULL UNIQUE,activity_id INTEGER NOT NULL,locale TEXT NOT NULL,form_key TEXT NOT NULL,title TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'active',draft_schema_json TEXT NOT NULL,published_schema_json TEXT NULL,draft_revision INTEGER NOT NULL DEFAULT 1,published_revision INTEGER NULL,draft_updated_at TEXT NOT NULL,published_at TEXT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);");
$db->exec("CREATE TABLE cms_form_submissions(id INTEGER PRIMARY KEY AUTOINCREMENT,submission_uuid TEXT NOT NULL UNIQUE,form_id INTEGER NOT NULL,page_id INTEGER NULL,activity_id INTEGER NOT NULL,locale TEXT NOT NULL,payload_json TEXT NOT NULL,form_snapshot_json TEXT NOT NULL,source_url TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'new',notes TEXT NOT NULL DEFAULT '',consent INTEGER NOT NULL DEFAULT 0,ip_hash TEXT NOT NULL,user_agent_hash TEXT NOT NULL,payment_status TEXT NOT NULL DEFAULT 'pending',payment_confirmed_at TEXT NULL,payment_note TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);");
$m46=require __DIR__.'/../migrations/046_student_area.php';$m46($db);$m47=require __DIR__.'/../migrations/047_student_accounts_cohorts_privacy.php';$m47($db);

$now=utc_now();$schema=json_encode(['fields'=>[]],JSON_THROW_ON_ERROR);$db->prepare('INSERT INTO cms_forms(form_uuid,activity_id,locale,form_key,title,draft_schema_json,published_schema_json,draft_updated_at,published_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute(['form1',1,'pt-BR','registration','Inscrição',$schema,$schema,$now,$now,$now,$now]);$formId=(int)$db->lastInsertId();
$payload=['name'=>'Aluno Teste','cpf'=>'123.456.789-00','phone'=>'24999999999','email'=>'aluno@example.com','instagram'=>'@aluno','address'=>'Rua Um, 10','city_state'=>'Petrópolis/RJ','postal_code'=>'25600-000'];
$db->prepare("INSERT INTO cms_form_submissions(submission_uuid,form_id,activity_id,locale,payload_json,form_snapshot_json,status,consent,ip_hash,user_agent_hash,payment_status,payment_confirmed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,'converted',1,'ip','ua','paid',?,?,?)")->execute(['sub1',$formId,1,'pt-BR',json_encode($payload,JSON_THROW_ON_ERROR),$schema,$now,$now,$now]);
$result=student_account_reconcile_confirmed_registrations($db,1);if(($result['processed']??0)!==1)fail('confirmed registration was not reconciled');$user=$db->query('SELECT * FROM student_users')->fetch();if(!$user)fail('student account not created');if(password_verify('12345678900',(string)$user['password_hash']))fail('CPF was stored as password');$profile=student_account_profile($db,(int)$user['id']);if(($profile['cpf']??'')!=='12345678900')fail('encrypted CPF did not roundtrip');if(($profile['phone']??'')!=='24999999999')fail('profile data missing');if(!student_account_has_activity($db,(int)$user['id'],1))fail('confirmed enrollment missing');

$activation=student_account_begin_activation($db,'aluno@example.com','12345678900');if($activation!=='ok')fail('first access identity proof failed');student_account_complete_activation($db,'uma-senha-segura-123',true);$activated=$db->query('SELECT * FROM student_users')->fetch();if(empty($activated['activated_at'])||!password_verify('uma-senha-segura-123',(string)$activated['password_hash']))fail('activation did not create personal password');if(password_verify('12345678900',(string)$activated['password_hash']))fail('CPF still authenticates as password');

$document=['version'=>2,'theme'=>'auto','meta'=>['title'=>'Material','description'=>''],'html'=>'<section data-cms-section="intro" data-cms-section-name="Introdução"><p>ABERTO</p></section><section data-cms-section="conteudo-aula-1"><p>AULA1</p></section><section data-cms-section="conteudo-aula-2"><p>AULA2</p></section>'];$json=json_encode($document,JSON_THROW_ON_ERROR);$db->prepare('INSERT INTO cms_pages(page_uuid,activity_id,locale,slug,title,nav_title,status,is_home,show_in_nav,sort_order,draft_document_json,published_document_json,draft_updated_at,published_at,created_at,updated_at,access_level) VALUES(?,?,?,?,?,?,"active",0,0,1,?,?,?,?,?,?,"enrolled")')->execute(['page1',1,'pt-BR','material','Material','Material',$json,$json,$now,$now,$now,$now]);$pageId=(int)$db->lastInsertId();$lessons=course_lessons($db,1);if(count($lessons)<2)fail('default lessons missing');student_page_set_section_lesson($db,$pageId,'conteudo-aula-1',(int)$lessons[0]['id']);student_page_set_section_lesson($db,$pageId,'conteudo-aula-2',(int)$lessons[1]['id']);$enrollment=student_account_enrollment_for_activity($db,(int)$user['id'],1);if(!$enrollment)fail('page access enrollment missing');course_set_lesson_release($db,(int)$enrollment['cohort_id'],(int)$lessons[0]['id'],true);$page=cms_page_by_id($db,$pageId);$filtered=student_page_filter_document($db,$page,$document,$enrollment);if(!str_contains($filtered['html'],'ABERTO')||!str_contains($filtered['html'],'AULA1')||str_contains($filtered['html'],'AULA2'))fail('server-side lesson filtering failed');

$uuid=str_repeat('c',32);student_private_media_mkdir();$relative=$uuid.'.jpg';file_put_contents(student_private_media_root().'/'.$relative,'fake');$db->prepare('INSERT INTO student_private_media(asset_uuid,activity_id,page_id,title,original_name,mime_type,byte_size,storage_path,checksum,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute([$uuid,1,$pageId,'Imagem','imagem.jpg','image/jpeg',4,$relative,hash('sha256','fake'),$now,$now]);$expires=time()+60;$sig=student_private_media_sig((int)$user['id'],$uuid,$pageId,(int)$enrollment['cohort_id'],$expires);if(!student_private_media_authorize($db,$user,$uuid,$pageId,(int)$enrollment['cohort_id'],$expires,$sig))fail('signed private media authorization failed');if(student_private_media_authorize($db,$user,$uuid,$pageId,(int)$enrollment['cohort_id'],$expires,str_repeat('0',64)))fail('invalid private media signature accepted');@unlink(student_private_media_root().'/'.$relative);

echo "student-accounts: ok\n";
