<?php
declare(strict_types=1);
function fail_student_test_workflow(string $message): never {fwrite(STDERR,"student-test-workflow: $message\n");exit(1);}
require_once dirname(__DIR__).'/app/student_enrollments.php';
$enrollments=[['cohort_id'=>10,'cohort_uuid'=>'cohort-a','activity_id'=>100],['cohort_id'=>11,'cohort_uuid'=>'cohort-a2','activity_id'=>100],['cohort_id'=>20,'cohort_uuid'=>'cohort-b','activity_id'=>200]];
$owned=['cohort_id'=>10,'activity_id'=>100];
if((student_enrollment_owned_test_navigation_context($enrollments,$owned,'cohort-a')['cohort_uuid']??'')!=='cohort-a')fail_student_test_workflow('legacy contextual record lost its exact enrollment context');
if(student_enrollment_owned_test_navigation_context($enrollments,$owned,'cohort-a2')!==null)fail_student_test_workflow('legacy contextual record accepted a different cohort context');
if((student_enrollment_owned_test_navigation_context($enrollments,$owned)['cohort_uuid']??'')!=='cohort-a')fail_student_test_workflow('legacy contextual record cannot recover its own active enrollment');
$sharedCohort=['cohort_id'=>10,'activity_id'=>100,'visibility'=>'cohort'];
if((student_enrollment_shared_test_navigation_context($enrollments,$sharedCohort,'cohort-a')['cohort_uuid']??'')!=='cohort-a')fail_student_test_workflow('cohort-shared record lost the matching cohort');
if(student_enrollment_shared_test_navigation_context($enrollments,$sharedCohort,'cohort-a2')!==null)fail_student_test_workflow('cohort-shared record accepted another cohort from the same course');
$sharedCourse=['cohort_id'=>10,'activity_id'=>100,'visibility'=>'course'];
if((student_enrollment_shared_test_navigation_context($enrollments,$sharedCourse,'cohort-a2')['cohort_uuid']??'')!=='cohort-a2')fail_student_test_workflow('course-shared record cannot return through another enrolled cohort of the same course');
if(student_enrollment_shared_test_navigation_context($enrollments,$sharedCourse,'cohort-b')!==null)fail_student_test_workflow('course-shared record accepted a context from another course');
$root=dirname(__DIR__);$test=(string)file_get_contents($root.'/aluno/teste.php');$routePicker=(string)file_get_contents($root.'/aluno/registro-roteiro.php');$shared=(string)file_get_contents($root.'/aluno/teste-compartilhado.php');$shell=(string)file_get_contents($root.'/app/student_shell.php');$reciprocity=(string)file_get_contents($root.'/assets/student-reciprocity.js');$workbench=(string)file_get_contents($root.'/app/student_workbench.php');$hardening=(string)file_get_contents($root.'/app/student_workbench_hardening.php');$manager=(string)file_get_contents($root.'/aluno/processamentos.php');$runner=(string)file_get_contents($root.'/aluno/processar.php');
if(!str_contains($test,'name="action" value="save_exposure"')||!str_contains($test,'Salvar exposição')||str_contains($test,'Salvar exposição e continuar'))fail_student_test_workflow('exposure is no longer an independently saved section');
if(!str_contains($test,'data-process-step-form')||!str_contains($test,'name="action" value="add_step"')||!str_contains($test,'name="stage_key"')||!str_contains($test,'Registrar etapa'))fail_student_test_workflow('manual processing no longer records a selected factual stage');
if(!str_contains($test,'student_experience_next_choices($steps)'))fail_student_test_workflow('manual workflow no longer derives the available physical stages');
if(!str_contains($hardening,'O processamento terminou na secagem. Registre o resultado.'))fail_student_test_workflow('drying no longer terminates the physical process server-side');
if(!str_contains($test,'data-developer-amount')||!str_contains($test,'data-water-amount')||!str_contains($test,'data-dilution-output'))fail_student_test_workflow('developer preparation no longer records measured developer and water amounts');
if(!str_contains($test,'data-saved-preparation')||!str_contains($test,'student_saved_preparations'))fail_student_test_workflow('manual workflow lost saved personal preparations');
if(!str_contains($test,'student_process_inventory_select_html')||!str_contains($workbench,'student_inventory'))fail_student_test_workflow('manual workflow lost inventory integration');
if(str_contains($test,'data-lab-timer'))fail_student_test_workflow('Caderno reintroduced the legacy contextual timer instead of laboratory mode');
if(!str_contains($test,'/aluno/registro-roteiro.php?test=<?=$id?>')||!str_contains($test,'Usar um roteiro'))fail_student_test_workflow('Caderno no longer offers route association inside the current record');
if(!str_contains($test,'Registrar manualmente')||!str_contains($test,'/aluno/processamento-realizado.php?test=<?=$id?>'))fail_student_test_workflow('Caderno no longer offers direct manual/retroactive recording');
if(!str_contains($routePicker,'student_process_replan_template')||!str_contains($routePicker,'student_process_replan_standard')||!str_contains($routePicker,'voltar ao registro'))fail_student_test_workflow('record route selection is not reversible and contextual');
if(!str_contains($manager,'Associar ao registro')||!str_contains($manager,'Nenhuma execução foi iniciada.'))fail_student_test_workflow('process library lost neutral planning semantics');
if(!str_contains($manager,'Usar no laboratório')||!str_contains($manager,"\$target=\$intent==='live'?'/aluno/processar.php?test='.\$testId.'&intent=live'"))fail_student_test_workflow('declared live intent is not preserved through legacy process selection');
if(!str_contains($test,'intent=live')||!str_contains($test,'Abrir laboratório')||!str_contains($runner,"\$intent!=='live'"))fail_student_test_workflow('laboratory mode no longer requires explicit execution intent');
if(!str_contains($runner,'student_process_execution_transition')||!str_contains($runner,"'timer_start'")||!str_contains($runner,'data-runner-start>Iniciar'))fail_student_test_workflow('laboratory execution can begin without the explicit persisted runner Start action');
if(!str_contains($test,'student_process_plan_for_test')||!str_contains($test,'Continuar laboratório')||!str_contains($test,'Alterar roteiro'))fail_student_test_workflow('Caderno no longer exposes continuation and replanning of an applied route');
foreach(['id="exposicao"','id="processamento"','id="resultado"'] as $anchor)if(!str_contains($test,$anchor))fail_student_test_workflow('record no longer keeps all documentary sections accessible together');
if(str_contains($test,'$resultReady')||str_contains($test,'aria-disabled'))fail_student_test_workflow('record navigation is again gated by completion state');
if(!str_contains($test,"isset(\$_GET['view'])")||!str_contains($test,"'process'=>'processamento'")||!str_contains($test,"'review'=>'resultado'"))fail_student_test_workflow('legacy view links no longer canonicalize to record anchors');
if(!str_contains($test,'href="/aluno/caderno.php"'))fail_student_test_workflow('owned record no longer returns to the global process notebook');
if(!str_contains($shared,'student_test_accessible_to_student')||!str_contains($shared,'href="/aluno/caderno.php"'))fail_student_test_workflow('shared record lost canonical sharing authorization or notebook return');
if(!str_contains($test,'name="calculated_time"')||!str_contains($test,'name="reciprocity_time"'))fail_student_test_workflow('exposure no longer exposes the calculated and reciprocity time pair');
if(!str_contains($shell,'/assets/student-reciprocity.js'))fail_student_test_workflow('student shell does not load the client-side reciprocity calculator');
if(!str_contains($reciprocity,'const RECIPROCITY_EXPONENT=1.38542662'))fail_student_test_workflow('reciprocity research exponent changed or disappeared');
if(!str_contains($reciprocity,'input[name="calculated_time"]')||!str_contains($reciprocity,'input[name="reciprocity_time"]'))fail_student_test_workflow('reciprocity calculator is no longer bound to the exposure fields');
echo "student-test-workflow: ok\n";